package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;

public class OCOHORHCROHICRRIHCIHHRRCIHICRI implements IIHRRHORCRCROCHHOHORCHCROCIHRO, Serializable {
   private static final long ORIROCRIICIIORHRRCCHHOICRHCCIH = 1L;
   protected static final int IORHCRIRICICCHHOCHIIIIRCOCRHIR = 9999;
   @Deprecated
   private final boolean IHCRRICROICCHHCRCOOHORHHOHCOCI;
   public static final OCOHORHCROHICRRIHCIHHRRCIHICRI IHOHRCIRIRHIROIIHORHOHHRIOCHHH = new OCOHORHCROHICRRIHCIHHRRCIHICRI();

   public OCOHORHCROHICRRIHCIHHRRCIHICRI(boolean var1) {
      this.IHCRRICROICCHHCRCOOHORHHOHCOCI = var1;
   }

   protected OCOHORHCROHICRRIHCIHHRRCIHICRI() {
      this(false);
   }

   @Deprecated
   public static OCOHORHCROHICRRIHCIHHRRCIHICRI OIIHHROICRCRHOHCCOCIHRHIRIICRC(boolean var0) {
      return new OCOHORHCROHICRRIHCIHHRRCIHICRI(var0);
   }

   public int OCHCRHICHHIIOHIOHCHOCCIIRCOOCC() {
      return 9999;
   }

   public boolean RCHRRIRIHHIRICRCIICIOCICRIOOIC() {
      return !this.IHCRRICROICCHHCRCOOHORHHOHCOCI;
   }

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO OCOIORCRROIOOCHORHHHROCHCCIHRR(boolean var1) {
      return var1 ? RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRIRORCOCHIHIRROORCRRCOHRHRIOC() : RRCRRCORICCHOHHIRCHIROOHIIOHCO.CCIHHCCCHHRRRHCOHHIORHHIIHHORC();
   }

   public IRRCCOICORICIHCHRHIHIHROIRHOCR OIOOOIIHRRRRRCROIHIORCOOCRROCI() {
      return IRRCCOICORICIHCHRHIHIHROIRHOCR.IROIHCCHHRCOOHCORIOOHIRIHCICIC();
   }

   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR ORHCROIRORROHCCHHHOCCROIHROORH() {
      return IIRHCHHOICHRICOOCRORCCIOOIHOIR.CHOHIHIICIHHHRHOORRCHRCORCIRIR();
   }

   public RICRIRRCOHRCOCRRHHCRHRROOIOHHR CRICCOOHHHCHOORCICOCOHIHOIRHOO(byte var1) {
      return CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCCICOORIOHOHOHOCCCOCICRCCHHHI(var1);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR CRRRICCRROCOHHOHIICIHORCOORRRH(Byte var1) {
      return var1 == null ? this.OIOOOIIHRRRRRCROIHIORCOOCRROCI() : CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCCICOORIOHOHOHOCCCOCICRCCHHHI(var1.intValue());
   }

   public RICRIRRCOHRCOCRRHHCRHRROOIOHHR CORCOCICIRIOHROHROIIOOHICCHCRR(short var1) {
      return IHIRRIIORRHORHRORIHOROIRCORCOO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR RRCRRCORICCHOHHIRCHIROOHIIOHCO(Short var1) {
      return var1 == null ? this.OIOOOIIHRRRRRCROIHIORCOOCRROCI() : IHIRRIIORRHORHRORIHOROIRCORCOO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1);
   }

   public RICRIRRCOHRCOCRRHHCRHRROOIOHHR RIICOCRRRHIHCHHRICOCHRCRCIOIRO(int var1) {
      return CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCCICOORIOHOHOHOCCCOCICRCCHHHI(var1);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR ORIOHRCIHRCOOHICCCRIIIHCRHHIHI(Integer var1) {
      return var1 == null ? this.OIOOOIIHRRRRRCROIHIORCOOCRROCI() : CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCCICOORIOHOHOHOCCCOCICRCCHHHI(var1);
   }

   public RICRIRRCOHRCOCRRHHCRHRROOIOHHR RHIHRRICIHORIHHIHHOIIOHHRCIIIH(long var1) {
      return IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IOIHHIORCICCHIIHOIOIOHHRICRHIO(var1);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR IIHRRHORCRCROCHHOHORCHCROCIHRO(Long var1) {
      return var1 == null ? this.OIOOOIIHRRRRRCROIHIORCOOCRROCI() : IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IOIHHIORCICCHIIHOIOIOHHRICRHIO(var1);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR HRCHROOHRIHCRCRHRIIROCIRHOIRHH(BigInteger var1) {
      return var1 == null ? this.OIOOOIIHRRRRRCROIHIORCOOCRROCI() : HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
   }

   public RICRIRRCOHRCOCRRHHCRHRROOIOHHR IHHOICIRHRHHRRCROIOROOCCCOROIR(float var1) {
      return CORCOCICIRIOHROHROIIOOHICCHCRR.ORIHOCRRHHCCOIHICIOHCIOCIIHOOO(var1);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR RIROICHCRROROHCCROOCCCCOCHCCRI(Float var1) {
      return var1 == null ? this.OIOOOIIHRRRRRCROIHIORCOOCRROCI() : CORCOCICIRIOHROHROIIOOHICCHCRR.ORIHOCRRHHCCOIHICIOHCIOCIIHOOO(var1);
   }

   public RICRIRRCOHRCOCRRHHCRHRROOIOHHR CICOIHIRIIHHCIOICHRHICRIRCIOHC(double var1) {
      return OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHIOCIRHCHIRHHRIRCHOIRORHCRCRI(var1);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR IIRHCHHOICHRICOOCRORCCIOOIHOIR(Double var1) {
      return var1 == null ? this.OIOOOIIHRRRRRCROIHIORCOOCRROCI() : OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHIOCIRHCHIRHHRIRCHOIRORHCRCRI(var1);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR IOIICIRIICICIIOORHCIIIIRRIHRHI(BigDecimal var1) {
      return var1 == null ? this.OIOOOIIHRRRRRCROIHIORCOOCRROCI() : HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHRIICOIOORCHCOIICOOIHIRHHICRI(var1);
   }

   public IOIICIRIICICIIOORHCIIIIRRIHRHI HOCOIRCICOHHICICIHICIHICRCHROI(String var1) {
      return IOIICIRIICICIIOORHCIIIIRRIHRHI.OOCCIOOOOHCCIOHHIOIOCOHOCHOHHC(var1);
   }

   public CRRRICCRROCOHHOHIICIHORCOORRRH IIIIRHIHROIRCROHHROIHIIHRCRRHO(byte[] var1) {
      return CRRRICCRROCOHHOHIICIHORCOORRRH.IIHHICHCCCOHCHROIRIHICCHHOROCR(var1);
   }

   public CRRRICCRROCOHHOHIICIHORCOORRRH CCHHCIRHICHHHHRRIHIORCCORCCIHR(byte[] var1, int var2, int var3) {
      return CRRRICCRROCOHHOHIICIHORCOORRRH.RHOORRIIOCHIRRHOHOOHIROHCRICRO(var1, var2, var3);
   }

   @Override
   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IHCRIRCRIOCRRCRHCOOCIHOHRHORHR() {
      return new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this);
   }

   @Override
   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HRHOORCROIRCCCIHRHHRHHIRCOCOHR(int var1) {
      return new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, var1);
   }

   @Override
   public HICRRICCHCCROOHHCHOCOCCHOIHHOC HCHHCOCCORCCROIRHORIIOOORRCCHH() {
      return new HICRRICCHCCROOHHCHOCOCCHOIHHOC(this);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR RORROCOIOHHOCCHRCHIIOHIHCRIIOO(Object var1) {
      return new RIROICHCRROROHCCROOCCCCOCHCCRI(var1);
   }

   @Override
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO var1
   ) {
      return new RIROICHCRROROHCCROOCCCCOCHCCRI(var1);
   }

   protected boolean IOHCCIRCCICICHHHIOIOHCICICROIO(long var1) {
      int var3 = (int)var1;
      long var4 = var3;
      return var4 == var1;
   }
}
