package com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.annotation.Nullable;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH[] CIORCRRCCOIHCHRHHHRIOOIRRIHIRH = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH[32];
   public int CRHROHRHCIRIIIIOCOHIIIRRICOOIC;
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HICIHHCCOOOCHOORHRHHORICIHROCI;
   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ROIHRCICHIRCIRHCCRHIHOOOHCCCCC = new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      int var2
   ) {
      this.HICIHHCCOOOCHOORHRHHORICIHROCI = var1;
      this.CRHROHRHCIRIIIIOCOHIIIRRICOOIC = var2;
   }

   @Nullable
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      Set<RORCHCIIICOHIRROOORHOCCCCIOCCI> var3,
      float var4,
      int var5,
      float var6
   ) {
      this.ROIHRCICHIRCIRHCCRHIHOOOHCCCCC.clear();
      this.HICIHHCCOOOCHOORHRHHORICIHROCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2);
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = this.HICIHHCCOOOCHOORHRHHORICIHROCI
         .OOIRHICCOHIOIRORHRHROOIIOOCCCC();
      if (var7 == null) {
         return null;
      }

      HashMap var8 = new HashMap();

      for (RORCHCIIICOHIRROOORHOCCCCIOCCI var10 : var3) {
         var8.put(this.HICIHHCCOOOCHOORHRHHORICIHROCI.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(var10), var10);
      }

      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var11 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var7, var8, var4, var5, var6
      );
      this.HICIHHCCOOOCHOORHRHHORICIHROCI.done();
      return var11;
   }

   private float RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      Set<com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> var2
   ) {
      float var3 = Float.MAX_VALUE;

      for (com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 : var2) {
         float var6 = var1.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var5);
         var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, var1);
         var3 = Math.min(var6, var3);
      }

      return var3;
   }

   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      RORCHCIIICOHIRROOORHOCCCCIOCCI var2,
      boolean var3
   ) {
      ArrayList var4 = Lists.newArrayList();
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = var1;
      var4.add(0, var5);

      while (var5.CHROHRCOCORRRRHOHOCCICOOOHOHRI != null) {
         var5 = var5.CHROHRCOCORRRRHOHOCCICOOOHOHRI;
         var4.add(0, var5);
      }

      return new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var4, var2, var3
      );
   }

   @Nullable
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      Map<com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH, RORCHCIIICOHIRROOORHOCCCCIOCCI> var2,
      float var3,
      int var4,
      float var5
   ) {
      Set var6 = var2.keySet();
      var1.RHIROICHORCRHOORIORROCROHIOHCC = 0.0F;
      var1.HHIHRIHOHHRCOCIIORIIRRCOROHIHC = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var6);
      var1.CIIOHIICORHCRHRIOOCIOIHIIIRHHI = var1.HHIHRIHOHHRCOCIIORIIRRCOROHIHC;
      this.ROIHRCICHIRCIRHCCRHIHOOOHCCCCC.clear();
      this.ROIHRCICHIRCIRHCCRHIHOOOHCCCCC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      int var7 = 0;
      HashSet var8 = Sets.newHashSetWithExpectedSize(var6.size());
      int var9 = (int)(this.CRHROHRHCIRIIIIOCOHIIIRRICOOIC * var5);

      while (!this.ROIHRCICHIRCIRHCCRHIHOOOHCCCCC.isEmpty()) {
         if (++var7 >= var9) {
            break;
         }

         com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var10 = this.ROIHRCICHIRCIRHCCRHIHOOOHCCCCC
            .HROCIHIHCIOCCHCICRHICIICIRRCOR();
         var10.closed = true;

         for (com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var12 : var6) {
            if (var10.CORCOCICIRIOHROHROIIOOHICCHCRR(var12) <= var4) {
               var12.OROOORROIOIIOHCIRHOORROHRRCCCI();
               var8.add(var12);
            }
         }

         if (!var8.isEmpty()) {
            break;
         }

         if (!(var10.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var1) >= var3)) {
            int var16 = this.HICIHHCCOOOCHOORHRHHORICIHROCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.CIORCRRCCOIHCHRHHHRIOOIRRIHIRH, var10);

            for (int var17 = 0; var17 < var16; var17++) {
               com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var13 = this.CIORCRRCCOIHCHRHHHRIOOIRRIHIRH[var17];
               float var14 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var10, var13);
               var13.OIRCRIHOIIRCCOORCHRRCIIROICCRH = var10.OIRCRIHOIIRCCOORCHRRCIIROICCRH + var14;
               float var15 = var10.RHIROICHORCRHOORIORROCROHIOHCC + var14 + var13.OCRIOCCRHHIHCCCOHRIORIHCCROROC;
               if (var13.OIRCRIHOIIRCCOORCHRRCIIROICCRH < var3 && (!var13.HIIRIHHHRIHIHIHOCOOHOICOOOHROH() || var15 < var13.RHIROICHORCRHOORIORROCROHIOHCC)) {
                  var13.CHROHRCOCORRRRHOHOCCICOOOHOHRI = var10;
                  var13.RHIROICHORCRHOORIORROCROHIOHCC = var15;
                  var13.HHIHRIHOHHRCOCIIORIIRRCOROHIHC = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var13, var6) * 1.5F;
                  if (var13.HIIRIHHHRIHIHIHOCOOHOICOOOHROH()) {
                     this.ROIHRCICHIRCIRHCCRHIHOOOHCCCCC
                        .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var13, var13.RHIROICHORCRHOORIORROCROHIOHCC + var13.HHIHRIHOHHRCOCIIORIIRRCOROHIHC);
                  } else {
                     var13.CIIOHIICORHCRHRIOOCIOIHIIIRHHI = var13.RHIROICHORCRHOORIORROCROHIOHCC + var13.HHIHRIHOHHRCOCIIORIIRRCOROHIHC;
                     this.ROIHRCICHIRCIRHCCRHIHOOOHCCCCC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var13);
                  }
               }
            }
         }
      }

      return (!var8.isEmpty()
            ? var8.stream()
               .map(var2x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x.RHIHIHCHCHRIIIIOHRHHIHHCHRCHHH(), (RORCHCIIICOHIRROOORHOCCCCIOCCI)var2.get(var2x), true))
               .min(
                  Comparator.comparingInt(
                     com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::OOOORICIOCRIHOORRHOCHOOHHCOOOR
                  )
               )
            : var6.stream()
               .map(
                  var2x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x.RHIHIHCHCHRIIIIOHRHHIHHCHRCHHH(), (RORCHCIIICOHIRROOORHOCCCCIOCCI)var2.get(var2x), false)
               )
               .min(
                  Comparator.comparingDouble(
                        com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::IROOICRHCCROOIRCCOHIRIRRRRCHOH
                     )
                     .thenComparingInt(
                        com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::OOOORICIOCRIHOORRHOCHOOHHCOOOR
                     )
               ))
         .orElse(null);
   }

   private float RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      return var1.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var2);
   }
}
