package com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import java.util.Map;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private double[] HCOOHHIRRRHRHOCHOHRIORHCCIHHIH;
   private HHCCIRHCCCIIRHCROHIORHIRHHIORH[] ROCRICOIOICCCRIOOCORHRHHORIOOR;
   private Boolean debug;
   private Double HHCHIIRORHOROICCICRRIRIROCCOIO;
   private Map<String, HRCHROOHRIHCRCRHRIIROCIRHOIRHH> IRIOHHHIRROIICIRHIORRIOOCRCCCI;
   private Boolean ROCHRICHCIIIRRIHHOHOIOIIRHHCOO;
   private String name;
   private Boolean CCRHOHRHCORICIHRRCROHICCOHRIIO;
   private String parent;
   private double[] CRHCOHHHOIHOHCIRHOHRCOHHHOIHRI = new double[]{0.0, 0.0, 0.0};
   private CRICCOOHHHCHOORCICOCOHIHOIRHOO ROORIIIICCIOCIHCRICOHHHCCRRIOR;
   private Long IROHIOCORIHOIORIRIIIHHCRHCHOOC;
   private Boolean IRIHCOCHCIIHCHOIRHHOOIIRIRCRCC;
   private double[] CIRHHIRRIICIHCORHORICIHHHIIICH = new double[]{0.0, 0.0, 0.0};
   private CIOHHCORHRCCRICCCORIHCRHCCCRRR[] RRCRCCCCCOIIIHRCRORRRHHICORCRC;

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("bind_pose_rotation")
   public double[] RIRCCIIOHOORIICOCRROIRIICCICOC() {
      return this.HCOOHHIRRRHRHOCHOHRIORHCCIHHIH;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("bind_pose_rotation")
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(double[] var1) {
      this.HCOOHHIRRRHRHOCHOHRIORHCCIHHIH = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("cubes")
   public HHCCIRHCCCIIRHCROHIORHIRHHIORH[] HCIHHIIHCRHOOROIIOOOHHROIIIORR() {
      return this.ROCRICOIOICCCRIOOCORHRHHORIOOR;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("cubes")
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HHCCIRHCCCIIRHCROHIORHIRHHIORH[] var1) {
      this.ROCRICOIOICCCRIOOCORHRHHORIOOR = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("debug")
   public Boolean getDebug() {
      return this.debug;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("debug")
   public void setDebug(Boolean var1) {
      this.debug = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("inflate")
   public Double ICIHIROIIHCHCRIOIHIIHHOIHRHCHC() {
      return this.HHCHIIRORHOROICCICRRIRIROCCOIO;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("inflate")
   public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(Double var1) {
      this.HHCHIIRORHOROICCICRRIRIROCCOIO = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("locators")
   public Map<String, HRCHROOHRIHCRCRHRIIROCIRHOIRHH> IOROCHIIOHOCRRIIIRCICOCHCCCRRO() {
      return this.IRIOHHHIRROIICIRHIORRIOOCRCCCI;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("locators")
   public void HICRRICCHCCROOHHCHOCOCCHOIHHOC(Map<String, HRCHROOHRIHCRCRHRIIROCIRHOIRHH> var1) {
      this.IRIOHHHIRROIICIRHIORRIOOCRCCCI = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("mirror")
   public Boolean OOCHCICIHRICCIIORHRHHIORRHRHRO() {
      return this.ROCHRICHCIIIRRIHHOHOIOIIRHHCOO;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("mirror")
   public void RCCCROCHCICCROHCOCCRRROCIIHCCH(Boolean var1) {
      this.ROCHRICHCIIIRRIHHOHOIOIIRHHCOO = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("name")
   public String getName() {
      return this.name;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("name")
   public void setName(String var1) {
      this.name = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("neverRender")
   public Boolean HIROOOCHROOIHRCIRHHHCHIIOHCRRH() {
      return this.CCRHOHRHCORICIHRRCROHICCOHRIIO;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("neverRender")
   public void OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(Boolean var1) {
      this.CCRHOHRHCORICIHRRCROHICCOHRIIO = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("parent")
   public String HROHCCOIIOHRRICCIICHCRCHOICRIC() {
      return this.parent;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("parent")
   public void OHCICOOIHRRRHHRHCOICICCROHCIII(String var1) {
      this.parent = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("pivot")
   public double[] OOIIORCRROOIIIRCHCOHCOIRRRIORR() {
      return this.CRHCOHHHOIHOHCIRHOHRCOHHHOIHRI;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("pivot")
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(double[] var1) {
      this.CRHCOHHHOIHOHCIRHOHRCOHHHOIHRI = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("poly_mesh")
   public CRICCOOHHHCHOORCICOCOHIHOIRHOO OICIRCOOOHHCOROICIIROHHORIHOIH() {
      return this.ROORIIIICCIOCIHCRICOHHHCCRRIOR;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("poly_mesh")
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CRICCOOHHHCHOORCICOCOHIHOIRHOO var1) {
      this.ROORIIIICCIOCIHCRICOHHHCCRRIOR = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("render_group_id")
   public Long HCOICIIROHHIOICHRRCRCHOROROIIR() {
      return this.IROHIOCORIHOIORIRIIIHHCRHCHOOC;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("render_group_id")
   public void CRRRICCRROCOHHOHIICIHORCOORRRH(Long var1) {
      this.IROHIOCORIHOIORIRIIIHHCRHCHOOC = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("reset")
   public Boolean ORICRCHHIICCIHCRCHHHORCIICOHOO() {
      return this.IRIHCOCHCIIHCHOIRHHOOIIRIRCRCC;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("reset")
   public void RHRRHOHCRCHCCRRHOHHIRCCHOCICHC(Boolean var1) {
      this.IRIHCOCHCIIHCHOIRHHOOIIRIRCRCC = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("rotation")
   public double[] RRORHIIIOOCIRCOCHRHHCHROOCIHRH() {
      return this.CIRHHIRRIICIHCORHORICIHHHIIICH;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("rotation")
   public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(double[] var1) {
      this.CIRHHIRRIICIHCORHORICIHHHIIICH = var1;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("texture_meshes")
   public CIOHHCORHRCCRICCCORIHCRHCCCRRR[] OHHORCOCCIHHOHRHROORHIOHHIOIIH() {
      return this.RRCRCCCCCOIIIHRCRORRRHHICORCRC;
   }

   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("texture_meshes")
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CIOHHCORHRCCRICCCORIHCRHCCCRRR[] var1) {
      this.RRCRCCCCCOIIIHRCRORRRHHICORCRC = var1;
   }
}
