package com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.eliotlash.molang.ast.Evaluatable;
import com.eliotlash.molang.utils.MolangUtils;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH;

public class RRCRRCORICCHOHHIRCHIROOHIIOHCO extends CIOHHCORHRCCRICCCORIHCRHCCCRRR<Evaluatable> {
   public Evaluatable RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2
   ) {
      RIRHOCHIORCCIIOIIRHOCCCRHHCHHH var3 = var1.HHIHOIRIOCOCIOROHCCCRRIOOOIRIC();
      if (var3 instanceof IOIICIRIICICIIOORHCIIIIRRIHRHI var4) {
         return com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORRRCRCCHIRHIHRHIROROCOHROCHCO(
            var4.HICIIICICHHHRCORHRHHCCHOHHIROR()
         );
      } else if (var3 instanceof com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var5
         )
       {
         return new com.moonsworth.lunar.client.IHIRRIIORRHORHRORIHOROIRCORCOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5.intValue());
      } else if (var3 instanceof com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.CORCOCICIRIOHROHROIIOOHICCHCRR var6
         )
       {
         return new com.moonsworth.lunar.client.IHIRRIIORRHORHRORIHOROIRCORCOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6.floatValue());
      } else if (var3 instanceof com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var7
         )
       {
         return new com.moonsworth.lunar.client.IHIRRIIORRHORHRORIHOROIRCORCOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7.doubleValue());
      } else {
         return var3 instanceof com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO var8
            ? new com.moonsworth.lunar.client.IHIRRIIORRHORHRORIHOROIRCORCOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               MolangUtils.booleanToFloat(var8.ICRRRCOCRCCHCIIOHHORHORHRCOCIC())
            )
            : null;
      }
   }
}
