package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IOHIHIIHCCCCCIHRORIOIOORCIOHII;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeSet;
import java.util.Map.Entry;
import java.util.concurrent.ConcurrentHashMap;

public class RICRIRRCOHRCOCRRHHCRHRROOIOHHR extends IRRCCOICORICIHCHRHIHIHROIRHOCR {
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> OIRIRCORHRORCORROCRCIIOHICRICH;
   protected final ConcurrentHashMap<String, String> HOHRCHOIHOIRRHHHIHIRRIIIICRROC;
   protected final Map<String, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI> ORHOICRCRHIHORHIRRCHIHHOROOHRI;
   protected final boolean HOIOROCOIIIHCCCHCIICRIHCRHCOCH;

   protected RICRIRRCOHRCOCRRHHCRHRROOIOHHR(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2,
      ConcurrentHashMap<String, String> var3,
      HashMap<String, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI> var4
   ) {
      super(var2, var1.CRRIRCRIRCHCHIRCICOROIIOIIICCC());
      this.OIRIRCORHRORCORROCRCIIOHICRICH = var1;
      this.HOHRCHOIHOIRRHHHIHIRRIIIICRROC = var3;
      this.ORHOICRCRHIHORHIRRCHIHHOROOHRI = var4;
      this.HOIOROCOIIIHCCCHCIICRIHCRHCOCH = var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.ACCEPT_CASE_INSENSITIVE_VALUES
      );
   }

   public static RICRIRRCOHRCOCRRHHCRHRROOIOHHR RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var0,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      Collection<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH> var2,
      boolean var3,
      boolean var4
   ) {
      if (var3 == var4) {
         throw new IllegalArgumentException();
      }

      ConcurrentHashMap var5;
      HashMap var6;
      if (var3) {
         var5 = new ConcurrentHashMap();
         var6 = null;
      } else {
         var6 = new HashMap();
         var5 = new ConcurrentHashMap(4);
      }

      boolean var7 = var0.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.ACCEPT_CASE_INSENSITIVE_VALUES
      );
      if (var2 != null) {
         for (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var9 : var2) {
            Class var10 = var9.getType();
            String var11 = var9.hasName() ? var9.getName() : IOHCCIRCCICICHHHIOIOHCICICROIO(var10);
            if (var3) {
               var5.put(var10.getName(), var11);
            }

            if (var4) {
               if (var7) {
                  var11 = var11.toLowerCase();
               }

               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var12 = (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI)var6.get(
                  var11
               );
               if (var12 == null || !var10.isAssignableFrom(var12.RRICIOOORRIORHHICIRCIOCHRHRCHH())) {
                  var6.put(var11, var0.HHOIOCRIRIOCOIHHOOHICIOIIOHCOR(var10));
               }
            }
         }
      }

      return new RICRIRRCOHRCOCRRHHCRHRROOIOHHR(var0, var1, var5, var6);
   }

   @Override
   public IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH CRIRRRICIRCHIOORRCCOHCCORHCRCR() {
      return IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NAME;
   }

   @Override
   public String OICOHRRRRCOICCHOIOROHOCOORCHII(Object var1) {
      return this.CHRHCRCCIICRORCOHCORHRROIHRCHO(var1.getClass());
   }

   protected String CHRHCRCCIICRORCOHCORHRROIHRCHO(Class<?> var1) {
      if (var1 == null) {
         return null;
      }

      String var2 = var1.getName();
      String var3 = this.HOHRCHOIHOIRRHHHIHIRRIIIICRROC.get(var2);
      if (var3 == null) {
         Class var4 = this.CCCOCCHRCRRCCCIOOIHOHICCIIROOR.OCOHORHCROHICRRIHCIHHRRCIHICRI(var1).RRICIOOORRIORHHICIRCIOCHRHRCHH();
         if (this.OIRIRCORHRORCORROCRCIIOHICRICH.HCRCRHHORCRHCCCHORCCCRORRIRRRC()) {
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var5 = this.OIRIRCORHRORCORROCRCIIOHICRICH
               .IOOCHIRHCRICHIHORCRCHCRHCICROH(var4);
            var3 = this.OIRIRCORHRORCORROCRCIIOHICRICH.RCRORHCOCRIIOHICORIHOHRIIRIORH().RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var5.OHCIIOIHROOORHCCRIORCOOHCHRHHH());
         }

         if (var3 == null) {
            var3 = IOHCCIRCCICICHHHIOIOHCICICROIO(var4);
         }

         this.HOHRCHOIHOIRRHHHIHIRRIIIICRROC.put(var2, var3);
      }

      return var3;
   }

   @Override
   public String CORCOCICIRIOHROHROIIOOHICCHCRR(Object var1, Class<?> var2) {
      return var1 == null ? this.CHRHCRCCIICRORCOHCORHRROIHRCHO(var2) : this.OICOHRRRRCOICCHOIOROHOCOORCHII(var1);
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1, String var2
   ) {
      return this.OCCHORHIHRCOOHCRIRHOOICRROHOII(var2);
   }

   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI OCCHORHIHRCOOHCRIRHOOICRROHOII(
      String var1
   ) {
      if (this.HOIOROCOIIIHCCCHCIICRIHCRHCOCH) {
         var1 = var1.toLowerCase();
      }

      return this.ORHOICRCRHIHORHIRRCHIHHOROOHRI.get(var1);
   }

   @Override
   public String ICHRHRHHICHCHIHOHRCHOIRCHIHOOC() {
      TreeSet var1 = new TreeSet();

      for (Entry var3 : this.ORHOICRCRHIHORHIRRCHIHHOROOHRI.entrySet()) {
         if (((com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI)var3.getValue())
            .RIOIOCRRCHIICRIRHHHRIHORCRHHOO()) {
            var1.add(var3.getKey());
         }
      }

      return var1.toString();
   }

   @Override
   public String toString() {
      return String.format("[%s; id-to-type=%s]", this.getClass().getName(), this.ORHOICRCRHIHORHIRRCHIHHOROOHRI);
   }

   protected static String IOHCCIRCCICICHHHIOIOHCICICROIO(Class<?> var0) {
      String var1 = var0.getName();
      int var2 = var1.lastIndexOf(46);
      return var2 < 0 ? var1 : var1.substring(var2 + 1);
   }
}
