package com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.lunarclient.dfu.serialization.Codec;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ICICIOCHHHIHOCHCOHORIHRCOHHOCR;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import lombok.Generated;
import org.jetbrains.annotations.Nullable;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ORHIRCIHOOCRRCRIOOIHCOICHCRICR;
   private final RRCRRCORICCHOHHIRCHIROOHIIOHCO CORHIRCIIICOOCHCCIHIIHCHHHIOOO = new RRCRRCORICCHOHHIRCHIROOHIIOHCO(200L);

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      super("crosshairDraw", Codec.BOOL, true);
      this.ORHIRCIHOOCRRCRIOOIHCOICHCRICR = var1;
      this.CORHIRCIIICOOCHCCIHIIHCHHHIOOO.start();
   }

   public float CORRCIRIIIIROHHIIORHCHRORRCRCR() {
      return this.get()
         ? this.CORHIRCIIICOOCHCCIHIIHCHHHIOOO.OICICHCIIHCIHHRRROIIIIHIIICCRI()
         : 1.0F - this.CORHIRCIIICOOCHCCIHIIHCHHHIOOO.OICICHCIIHCIHHRRROIIIIHIIICCRI();
   }

   public void IRIRRHOHIIOOOOCIRIHOIHCHCRIHHO() {
      this.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(!this.get());
      this.CORHIRCIIICOOCHCCIHIIHCHHHIOOO.start();
   }

   @Nullable
   @Override
   protected ICICIOCHHHIHOCHCOHORIHRCOHHOCR<?> CIOHHCORHRCCRICCCORIHCRHCCCRRR(
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      return new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this, var1
      );
   }

   @Generated
   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IHOOHIOIIHORORHCHHCHCCCCORHRCO() {
      return this.ORHIRCIHOOCRRCRIOOIHCOICHCRICR;
   }
}
