package com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;

import lombok.Generated;

public class CRICCOOHHHCHOORCICOCOHIHOIRHOO extends com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO HIRHHRHCRCCOICHOOOCIHCCRCHCIIC;
   private float CHOOROOOOCHOHRICORCOCICIOOCOCI;

   @Generated
   public CRICCOOHHHCHOORCICOCOHIHOIRHOO(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1,
      float var2
   ) {
      this.HIRHHRHCRCCOICHOOOCIHCCRCHCIIC = var1;
      this.CHOOROOOOCHOHRICORCOCICIOOCOCI = var2;
   }

   @Generated
   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO HRRCCRCOCCHHCORHIHCRCOHRHHOIRC() {
      return this.HIRHHRHCRCCOICHOOOCIHCCRCHCIIC;
   }

   @Generated
   public float ROIRICOHOICIIHRCROHICOOHIOIHCI() {
      return this.CHOOROOOOCHOHRICORCOCICIOOCOCI;
   }

   @Generated
   public void RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(float var1) {
      this.CHOOROOOOCHOHRICORCOCICIOOCOCI = var1;
   }
}
