package com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;

import lombok.Generated;

public class OOROOCCIRCCRHOIOIORIHCHHOOCCOR extends com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH {
   private float IROORIICOORCHOHRHRROCHROORHOHR;

   @Generated
   public OOROOCCIRCCRHOIOIORIHCHHOOCCOR(float var1) {
      this.IROORIICOORCHOHRHRROCHROORHOHR = var1;
   }

   @Generated
   public float RHHHRIIROORRIHCHRHCOCOCIHRCCIC() {
      return this.IROORIICOORCHOHRHRROCHROORHOHR;
   }

   @Generated
   public void ICICIOCHHHIHOCHCOHORIHRCOHHOCR(float var1) {
      this.IROORIICOORCHOHRHRROCHROORHOHR = var1;
   }
}
