package com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;

public interface RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   extends com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH {
   IIRHCHHOICHRICOOCRORCCIOOIHOIR bridge$getHelmet();

   IIRHCHHOICHRICOOCRORCCIOOIHOIR bridge$getChestplate();

   IIRHCHHOICHRICOOCRORCCIOOIHOIR bridge$getLeggings();

   IIRHCHHOICHRICOOCRORCCIOOIHOIR bridge$getBoots();

   IIRHCHHOICHRICOOCRORCCIOOIHOIR bridge$getMainHand();

   @com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 5)
   IIRHCHHOICHRICOOCRORCCIOOIHOIR bridge$getOffhand();

   boolean bridge$isMarker();
}
