package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

abstract class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends RRCRRCORICCHOHHIRCHIROOHIIOHCO {
   public static final int CCOHCHIRCRCCICROOIIICCHOROOOHC = 2147483643;
   static final long HOCRIIROHHRCHHIRHCIHICOIRHOCRO = 1000000000000000000L;
   static final int HORIIROHCHRRRORIRCORCRORHHRCHC = 1024;
}
