package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;
import java.util.ArrayList;
import java.util.List;
import toxi.geom.Line3D;
import toxi.geom.Vec3D;
import toxi.geom.Line3D.LineIntersection;
import toxi.geom.Line3D.LineIntersection.Type;

public class IIRHCHHOICHRICOOCRORCCIOOIHOIR extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI IOCICCICOCORRIOCHHORCHCRCOHHHR = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.class
   );
   private IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH OICOIOROOCHOIOCCRCHOCCICROCCII = IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.USED_NONE;
   private final List<IHIRRIIORRHORHRORIHOROIRCORCOO> HHRROROHHIROOCIOHIIORHIHHOHOHC = new ArrayList<>();
   private Line3D CCOCOOHOCOIHRORRCCIRHHRRORRCHR;
   private Line3D IHHHCOOHORHOCICCHHHOICCCRCICIH;
   private Vec3D RRCCCOHOIIHRCIOCROCIIOCCRCCORI;
   private long RCIIRHCOOORIRHRCCRHRHIHIHRIOCC;
   private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHOOIOHCHICOCHIICHCICCOHRCIII.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CRICCHIHCOCCIRRCCIRICCHIOHRORO;

   public IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.MINING
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI::RRRCCHIOCICOIOIRRCOOIRHHCORCIH
         )
      );
      this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(this::onDisable);
      this.handle(IHIRRIIORRHORHRORIHOROIRCORCOO.class, this::OOROOCCIRCCRHOIOIORIHCHHOOCCOR);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         this::IIHRRHORCRCROCHHOHORCHCROCIHRO
      );
      this.handle(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         var1x -> {
            if (var1x.COCHHOHRHIHICIHOHHHHICHRIIHCRI()
               == com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DOWN) {
               if (!var1x.OOHCOIRICORORHOHHORCICOOICIORO()) {
                  this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x.CCICCIOCIHOOIHCIRCHHHRROHIHHIH(), var1x);
               }
            }
         }
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class,
         var1x -> {
            if (var1x.ROIHIHCOHOIRHORHOROHHOICOIOHRC() >= 0 && var1x.ROIHIHCOHOIRHORHOROHHOICOIOHRC() <= 15) {
               if (var1x.COCHHOHRHIHICIHOHHHHICHRIIHCRI()
                  == com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DOWN) {
                  this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x.CCICCIOCIHOOIHCIRCHHHRROHIHHIH(), var1x);
               }
            }
         }
      );
   }

   private void onDisable() {
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH((RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH)null);
   }

   @OIHCOHRCICCCRHRCROOCIOIRRHHHIH
   @Override
   public String getId() {
      return "SKYBLOCK_WISHING_COMPASS";
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOIICIRIICICIIOORHCIIIIRRIHRHI var1) {
      if (this.CRICCHIHCOCCIRRCCIRICCHIOHRORO != null && this.CRICCHIHCOCCIRRCCIRICCHIOHRORO.getDistance() < 15.0) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HOHHHORIIORRRROHRIIRCHCCICHHCI()
            .HRCHROOHRIHCRCRHRIIROCIRHOIRHH(this.CRICCHIHCOCCIRRCCIRICCHIOHRORO);
         this.CRICCHIHCOCCIRRCCIRICCHIOHRORO = null;
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      if (var1 == IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getGameSettings().bridge$keyBindUseItem().bridge$getKey()) {
         IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = this.CIRCCCOOOIOHROORICOOORHHRRHOCI();
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
               HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
            )
            .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
         switch (var3) {
            case ACCEPT_SUCCESS:
               if (this.OICOIOROOCHOIOCCRCHOCCICROCCII == IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.USED_NONE) {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OROORIICIOOOOIHIRHRHOIOCIHRRIO(
                     var4.IRCIIHHICIHRCOCRROCOICRIHHCCHH("wishingCompassSuccess")
                  );
               }

               this.RCIIRHCOOORIRHRCCRHRHIHIHRIOCC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
               break;
            case IN_NUCLEUS_REJECTION:
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OROORIICIOOOOIHIRHRHOIOCIHRRIO(
                  var4.IRCIIHHICIHRCOCRROCOICRIHHCCHH("wishingCompassNucleus")
               );
               var2.cancel();
               break;
            case TOO_CLOSE_REJECTION:
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OROORIICIOOOOIHIRHRHOIOCIHRRIO(
                  var4.IRCIIHHICIHRCOCRROCOICRIHHCCHH("wishingCompassMove")
               );
               var2.cancel();
               break;
            case SPAM_REJECTION:
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OROORIICIOOOOIHIRHRHOIOCIHRRIO(
                  var4.IRCIIHHICIHRCOCRROCOICRIHHCCHH("wishingCompassWait")
               );
               var2.cancel();
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.OICOIOROOCHOIOCCRCHOCCICROCCII = IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.USED_NONE;
      this.CCOCOOHOCOIHRORRCCIRHHRRORRCHR = null;
      this.IHHHCOOHORHOCICCHHHOICCCRCICIH = null;
      this.RRCCCOHOIIHRCIOCROCIIOCCRCCORI = null;
      if (this.CRICCHIHCOCCIRRCCIRICCHIOHRORO != null) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HOHHHORIIORRRROHRIIRCHCCICHHCI()
            .HRCHROOHRIHCRCRHRIIROCIRHOIRHH(this.CRICCHIHCOCCIRRCCIRICCHIOHRORO);
         this.CRICCHIHCOCCIRRCCIRICCHIOHRORO = null;
      }
   }

   private void IIHRRHORCRCROCHHOHORCHCROCIHRO(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      String var2 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.getTextContent(
         var1.RRCIOIRIRCCHCRCOOICRRORCRIHHRC()
      );
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      if (var3 != null) {
         if (var2.equals("Your Wishing Compass shattered into pieces!")) {
            this.HHRROROHHIROOCIOHIIORHIHHOHOHC.clear();
            this.RCIIRHCOOORIRHRCCRHRHIHIHRIOCC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
            if (this.OICOIOROOCHOIOCCRCHOCCICROCCII == IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.USED_NONE) {
               this.RRCCCOHOIIHRCIOCROCIIOCCRCCORI = new Vec3D((float)var3.bridge$getPosX(), (float)var3.bridge$getPosY(), (float)var3.bridge$getPosZ());
            }
         }
      }
   }

   private void OOROOCCIRCCRHOIOIORIHCHHOOCCOR(IHIRRIIORRHORHRORIHOROIRCORCOO var1) {
      if (var1.ICRCIIIHROCRHOHHHHRCCCOOCICHOO()
         == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HAPPY_VILLAGER
         )
       {
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() - this.RCIIRHCOOORIRHRCCRHRHIHIHRIOCC <= 5000L) {
            if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
               == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRYSTAL_HOLLOWS
               )
             {
               if (this.HHRROROHHIROOCIOHIIORHIHHOHOHC.size() < 5) {
                  this.HHRROROHHIROOCIOHIIORHIHHOHOHC.add(var1);
                  if (this.HHRROROHHIROOCIOHIIORHIHHOHOHC.size() == 5) {
                     IHIRRIIORRHORHRORIHOROIRCORCOO var2 = this.HHRROROHHIROOCIOHIIORHIHHOHOHC.get(0);
                     IHIRRIIORRHORHRORIHOROIRCORCOO var3 = this.HHRROROHHIROOCIOHIIORHIHHOHOHC.get(4);
                     Vec3D var4 = new Vec3D(
                        (float)var2.ICIHOIHROICHIHRIIOOCHOCCOHRIRR(),
                        (float)var2.HRRIHICRHIHCCOIRIOROIHOHRHCOHI(),
                        (float)var2.IIOCRCOCCHCIOCCORROCIRHOICIICR()
                     );
                     Vec3D var5 = new Vec3D(
                        (float)var3.ICIHOIHROICHIHRIIOOCHOCCOHRIRR(),
                        (float)var3.HRRIHICRHIHCCOIRIOROIHOHRHCOHI(),
                        (float)var3.IIOCRCOCCHCIOCCORROCIRHOICIICR()
                     );
                     Line3D var6 = new Line3D(var4, var5);
                     if (this.OICOIOROOCHOIOCCRCHOCCICROCCII == IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.USED_NONE) {
                        this.CCOCOOHOCOIHRORRCCIRHHRRORRCHR = var6;
                        this.OICOIOROOCHOIOCCRCHOCCICROCCII = IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.USED_FIRST;
                     } else {
                        this.IHHHCOOHORHOCICCHHHOICCCRCICIH = var6;
                        this.COCICIHIRRRCOIICHIHRRCIHOICCCR();
                        this.OICOIOROOCHOIOCCRCHOCCICROCCII = IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.USED_NONE;
                     }

                     this.RCIIRHCOOORIRHRCCRHRHIHIHRIOCC = 0L;
                     this.HHRROROHHIROOCIOHIIORHIHHOHOHC.clear();
                  }
               }
            }
         }
      }
   }

   private void COCICIHIRRRCOIICHIHRRCIHOICCCR() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
            HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
         )
         .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
      LineIntersection var2 = this.CCOCOOHOCOIHRORRCCIRHHRRORRCHR.closestLineTo(this.IHHHCOOHORHOCICCHHHOICCCRCICIH);
      if (var2.getType() == Type.NON_INTERSECTING) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OROORIICIOOOOIHIRHRHOIOCIHRRIO(
            var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH("wishingCompassFail")
         );
      } else {
         Vec3D var3 = var2.getLine().getMidPoint();
         IIHRHCCOOHOOOOCHRRCOROOIOHCOOO var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HOHHHORIIORRRROHRIIRCHCCICHHCI();
         if (this.CRICCHIHCOCCIRRCCIRICCHIOHRORO != null) {
            var4.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(this.CRICCHIHCOCCIRRCCIRICCHIOHRORO);
         }

         this.CRICCHIHCOCCIRRCCIRICCHIOHRORO = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHOOIOHCHICOCHIICHCICCOHRCIII.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIROORIICIROCCOIROCRIRCCRHCIOI()
            .RRHCHIHOIRICOICHIHOIRIOHHRHOOI("Wishing Compass Estimate")
            .OCOHORHCROHICRRIHCIHHRRCIHICRI(CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var3.x(), var3.y(), var3.z()))
            .ICOHOCROHOHHHCCOCIHHRHOCOOCOCC(com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR().getWorld())
            .RCOROOHHCORIRCRHOHRCCIHRCORCHH(IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH().bridge$getDimensionId())
            .HRIOHRORCHIICCICIHRIIHHCHHOHHO(IIHRHCCOOHOOOOCHRRCOROOIOHCOOO.HIRHRIOCOCCCORCRICIICOIIIOCOHI())
            .OOCHIIROORIOCCCCCOORRIRIOHOORH(true)
            .OIHHRHHICRCHRIORRIHHOICCHCCRRR();
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OROORIICIOOOOIHIRHRHOIOCIHRRIO(
            var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH("wishingCompassEstimateMade")
         );
         var4.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CRICCHIHCOCCIRRCCIRICCHIOHRORO);
         this.OICOIOROOCHOIOCCRCHOCCICROCCII = IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.USED_NONE;
      }
   }

   private IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CIRCCCOOOIOHROORICOOORHHRRHOCI() {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      if (var1 == null) {
         return IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ACCEPT_IRRELEVANT;
      }

      if (!this.IOCICCICOCORRIOCHHORCHCRCOHHHR.COHRHRIIROIICHHHHCHCCHOIRROOHO().equals("WISHING_COMPASS")) {
         return IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ACCEPT_IRRELEVANT;
      }

      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() - this.RCIIRHCOOORIRHRCCRHRHIHIHRIOCC < 5000L) {
         return IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SPAM_REJECTION;
      }

      if (var1.bridge$getPosY() >= 67.0
         && var1.bridge$getPosX() <= 560.0
         && var1.bridge$getPosZ() <= 560.0
         && var1.bridge$getPosX() >= 440.0
         && var1.bridge$getPosZ() >= 440.0) {
         return IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IN_NUCLEUS_REJECTION;
      }

      if (this.OICOIOROOCHOIOCCRCHOCCICROCCII == IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.USED_NONE) {
         return IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ACCEPT_SUCCESS;
      }

      Vec3D var2 = new Vec3D((float)var1.bridge$getPosX(), (float)var1.bridge$getPosY(), (float)var1.bridge$getPosZ());
      return var2.distanceToSquared(this.RRCCCOHOIIHRCIOCROCIIOCCRCCORI) <= 400.0F
         ? IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.TOO_CLOSE_REJECTION
         : IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ACCEPT_SUCCESS;
   }

   private enum IRCIIHHICIHRCOCRROCOICRIHHCCHH {
      USED_NONE,
      USED_FIRST;
   }

   private enum RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      IN_NUCLEUS_REJECTION,
      TOO_CLOSE_REJECTION,
      ACCEPT_IRRELEVANT,
      ACCEPT_SUCCESS,
      SPAM_REJECTION;
   }
}
