package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private static final RCIROOOOICRHCCRRCIORHHIRCOIIIC IRRIROCIRHORIRHOHRRHIHCRCHIRCO = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "minecraft", "textures/skins/wide/steve.png"
   );
   private final RCIROOOOICRHCCRRCIORHHIRCOIIIC HCCHCIICCIHIHIHHRCOOICCCIRROHO = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "lunar", "ui/images/crystal-hollows-map.png"
   );

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            new IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.MINING
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this,
            () -> com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
               == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRYSTAL_HOLLOWS
         )
      );
   }

   @Override
   public String getId() {
      return "SKYBLOCK_CRYSTAL_HOLLOWS_MAP";
   }

   private class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
         super(0.0F, 0.0F, com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.TOP_LEFT);
         this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(128.0F, 128.0F);
      }

      @Override
      public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
         float var2,
         float var3,
         boolean var4
      ) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = var1.RCHHRIOCRHHIHIROCIRCRHRIOOOCOO();
         var5.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0 -> {
            var0.HHIIOHOORHHCCHRHHRCIORCROORCOI().CHHHIRRRHHCOOHRRICOCICHHROHHIR();
            var0.HHIIOHOORHHCCHRHHRCIORCROORCOI().IRCHOHHOOROOHIIHHROOOOIIHHOIIH();
         });
         if (var4) {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5, var2, var3, IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIROCIRHORIRHOHRRHIHCRCHIRCO, 468.0, 402.0, 135.0F);
         } else {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var6 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
            if (var6 == null) {
               com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  var5, IRCIIHHICIHRCOCRROCOICRIHHCCHH.this.HCCHCIICCIHIHIHHRCOOICCCIRROHO, var2, var3, this.getWidth(), this.getHeight(), -1
               );
            } else {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var5, var2, var3, var6.bridge$getLocationSkin(), var6.bridge$getPosX(), var6.bridge$getPosZ(), (float)var6.bridge$getRotationYaw()
               );
            }
         }
      }

      private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         float var2,
         float var3,
         RCIROOOOICRHCCRRCIORHHIRCOIIIC var4,
         double var5,
         double var7,
         float var9
      ) {
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            var1, IRCIIHHICIHRCOCRROCOICRIHHCCHH.this.HCCHCIICCIHIHIHHRCOOICCCIRROHO, var2, var3, this.getWidth(), this.getHeight(), -1
         );
         if (var4 != null) {
            float var10 = (float)(var5 - 202.0) / 621.0F * this.getWidth();
            float var11 = (float)(var7 - 202.0) / 621.0F * this.getHeight();
            var1.push();
            var1.CRICCOOHHHCHOORCICOCOHIHOIRHOO(var2 + var10, var3 + var11, 0.0F);
            var1.IIHRRHORCRCROCHHOHORCHCROCIHRO(var9 - 180.0F);
            com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1, var4, -4.0F, -4.0F, -1, true
            );
            var1.pop();
         }
      }

      @Override
      public boolean ORCOCORROHIROCCIORORRRRCHIOOCH(boolean var1) {
         return true;
      }
   }
}
