package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.util.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;
import com.moonsworth.lunar.client.util.OOOOCCOOOHCHCIIHOIHCRIIOOROHRC;
import com.moonsworth.lunar.lib.adventure.text.Component;
import com.moonsworth.lunar.lib.adventure.text.TextComponent;
import org.jetbrains.annotations.Nullable;

public class IIRHCHHOICHRICOOCRORCCIOOIHOIR extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private OOOOCCOOOHCHCIIHOIHCRIIOOROHRC OIOCRCOHOHRIHOOOOCCCCOICCOOOIC;

   public IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            new IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
         )
      );
   }

   @OIHCOHRCICCCRHRCROOCIOIRRHHHIH
   @Override
   public String getId() {
      return "DEBUG_TIMER_HUD";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
         IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH("start").RCIROOOOICRHCCRRCIORHHIRCOIIIC(this::start),
         IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH("stop").RCIROOOOICRHCCRRCIORHHIRCOIIIC(this::IOCHOHHHHIRIIHOIHIIOHHRCCORROI),
         IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH("reset").RCIROOOOICRHCCRRCIORHHIRCOIIIC(this::reset)
      );
   }

   private boolean reset() {
      this.OIOCRCOHOHRIHOOOOCCCCOICCOOOIC = null;
      return true;
   }

   private boolean start() {
      if (this.OIOCRCOHOHRIHOOOOCCCCOICCOOOIC == null) {
         this.OIOCRCOHOHRIHOOOOCCCCOICCOOOIC = new OOOOCCOOOHCHCIIHOIHCRIIOOROHRC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
            .IICCOOCHCHROORHHIIHROHCCRHRCOR(0L)
            .OIRHHRHOICCRORRCOOROHIOROHHCRI()
            .CRHOOHHCIOOCCHRCRICCIICIOHHCRR(true)
            .OHRHHOOHHCRORRROIROCHORCROHHCI();
      }

      this.OIOCRCOHOHRIHOOOOCCCCOICCOOOIC.HRHIIHCRHHIIHCHCOHHHROORIIHOCR();
      return true;
   }

   private boolean IOCHOHHHHIRIIHOIHIIOHHRCCORROI() {
      this.OIOCRCOHOHRIHOOOOCCCCOICCOOOIC.stop();
      return true;
   }

   private class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO<TextComponent> {
      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
         super(0.0F, 0.0F, com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.MIDDLE_LEFT);
      }

      @Override
      public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH HRRIHHICORIHCHICOHCCRCHCHOHRCH() {
         return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            10, 15, 30, 70, 120, 170
         );
      }

      @Nullable
      public TextComponent RCRCCORIIOICRIIRHCCIIOCICRHIOC(boolean var1) {
         if (var1) {
            return this.HCRRCORHCHHHCOCRROROIIROROROHO("13.37s");
         } else {
            return IIRHCHHOICHRICOOCRORCCIOOIHOIR.this.OIOCRCOHOHRIHOOOOCCCCOICCOOOIC == null
               ? this.HCRRCORHCHHHCOCRROROIIROROROHO("Debug Timer")
               : this.HCRRCORHCHHHCOCRROROIIROROROHO(IIRHCHHOICHRICOOCRORCCIOOIHOIR.this.OIOCRCOHOHRIHOOOOCCCCOICCOOOIC.RRHIICCHIOCIHCOIHHIROHCHCOHOHO());
         }
      }

      private TextComponent HCRRCORHCHHHCOCRROROIIROROROHO(String var1) {
         return Component.text(var1);
      }
   }
}
