package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class OHHRIOHROOIHOROCIRHCHORIHRRRRI extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private static final String CIRICOORCHRRCHRHOCHCHOROCOIICI = "previewIsolationSnapshot.json";
   private static final String HHCIIHIIORCROIHOORIOOICHCHHIOC = "SKYBLOCK_TAB_WIDGET_";
   private static final Set<String> RIRCHCOORORHROCIHORCHRHIRRIOOI = Set.of(
      "SKYBLOCK_CHOCOLATE_SHOP_HELPER",
      "SKYBLOCK_CHOCOLATE_STATS",
      "SKYBLOCK_RABBIT_COLLECTION_OVERLAY",
      "BETTERMAP_PRIMARY",
      "BETTERMAP_SECONDARY",
      "SKYBLOCK_DRAGON_FEATURES",
      "SKYBLOCK_DUNGEON_BLESSING_HUD",
      "SKYBLOCK_DUNGEON_MILESTONE_HUD",
      "SKYBLOCK_TICK_TIMER_HUD",
      "SKYBLOCK_FLOOR_FOUR",
      "SKYBLOCK_INVINCIBILITY_HUD",
      "SKYBLOCK_SKELETON_HELMET_HUD",
      "SKYBLOCK_STORM_HUD",
      "SKYBLOCK_DUNGEON_TIMER",
      "SKYBLOCK_COMPOSTER_HUD",
      "SKYBLOCK_CROP_TRACKER_HUD",
      "SKYBLOCK_FARMING_HUD",
      "SKYBLOCK_GARDEN_PESTS",
      "SKYBLOCK_HARVEST_FEAST_TRACKER_HUD",
      "SKYBLOCK_VISITOR_SHOPPING_LIST_HUD",
      "SKYBLOCK_VISITOR_TRACKER_HUD",
      "SKYBLOCK_VISITOR_HUD",
      "SKYBLOCK_FISHING_BAIT_HUD",
      "SKYBLOCK_FISHING_INFO_HUD",
      "SKYBLOCK_FISHING_REEL_TIMER_HUD",
      "SKYBLOCK_SPIDER_DEN_RAIN_HUD",
      "SKYBLOCK_TROPHY_FISH_EXCHANGE_RATE",
      "SKYBLOCK_WHISPER_TRACKER_HUD",
      "SKYBLOCK_CHEST_PROFIT",
      "SKYBLOCK_ARROW_POISON_HUD",
      "SKYBLOCK_BITS_SHOP_HELPER",
      "SKYBLOCK_ENHANCED_MINION_MENU",
      "SKYBLOCK_QUIVER_HUD",
      "SKYBLOCK_SKYMART_HELPER",
      "SKYBLOCK_CRYSTAL_HOLLOWS_MAP",
      "SKYBLOCK_POWDER_TRACKER_HUD",
      "SKYBLOCK_SCATHA_TRACKER_HUD",
      "SKYBLOCK_NETHER_BOSS_HUD",
      "SKYBLOCK_RAFFLE_TASKS_HUD",
      "SKYBLOCK_SKILL_PROGRESS_HUD",
      "SKYBLOCK_SKILL_XP_TRACKER_HUD",
      "SKYBLOCK_BLAZE_SLAYER",
      "SKYBLOCK_ENDERMAN_SLAYER",
      "SKYBLOCK_SPEED_HUD"
   );

   public OHHRIOHROOIHOROCIRHCHORIHRRRRI(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
   }

   @OIHCOHRCICCCRHRCROOCIOIRRHHHIH
   @Override
   public String getId() {
      return "SKYBLOCK_PREVIEW_ISOLATION_DEBUG";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
         IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH("isolatePreviews").RCIROOOOICRHCCRRCIORHHIRCOIIIC(this::HHRRICRIORRHIOIRIOIORRROROIHHI)
      );
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
         IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH("restoreSnapshot").RCIROOOOICRHCCRRCIORHHIRCOIIIC(this::HHHCIRHHOICIHORHCRROOOHHIICHIC)
      );
   }

   private boolean IOHIHIIHCCCCCIHRORIOIOORCIOHII(com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      String var2 = var1.getId();
      return RIRCHCOORORHROCIHORCHRHIRRIOOI.contains(var2) || var2.startsWith("SKYBLOCK_TAB_WIDGET_");
   }

   private List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      ArrayList var2 = new ArrayList();
      var2.add(var1);
      var1.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IICCRHIHRIHOHICHCRIROICOICROOR)
         .ifPresent(var1x -> var1x.OOCCRCRCOHIIORCCORCRCIRRROIOOR(var1xx -> var2.add(var1xx)));
      return var2;
   }

   private void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, boolean var2) {
      var1.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRIIIRORRHRROOOIRHROOOIIHIHIRH).ifPresent(var1x -> var1x.setEnabled(var2));
   }

   private void HHRRICRIORRHIOIRIOIORRROROIHHI() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .IHIIROIOIHOHCHICOIIIHOHHCOIOCI();
      List var2 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      OHHRIOHROOIHOROCIRHCHORIHRRRRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = new OHHRIOHROOIHOROCIRHCHORIHRRRRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 : var2) {
         var5.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRIIIRORRHRROOOIRHROOOIIHIHIRH)
            .ifPresent(var2x -> var3.HICCIIHOOCRCICHIORCIRRCHCRRCCO.put(var5.getId(), var2x.isEnabled()));
      }

      var3.ICICRCOIOIRRIOHCOROCIOHOOIORCO = var1.HOHOCHCHIIHOHOHIIRCICCRORHIROH().get();
      var1.ORICRIRORRCHHHRRHOORHIRCICHCCO().HRCHROOHRIHCRCRHRIIROCIRHOIRHH("previewIsolationSnapshot.json", var3);
      var1.HOHOCHCHIIHOHOHIIRCICCRORHIROH()
         .RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ALWAYS
         );
      HashSet var9 = new HashSet();
      var9.add(var1);

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var6 : var2) {
         if (this.IOHIHIIHCCCCCIHRORIOIOORCIOHII(var6)) {
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7 = var6;

            while (var7 != null) {
               var9.add(var7);
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH var8 = var7.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
                  HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
               );
               var7 = var8 == null ? null : var8.RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            }
         }
      }

      int var11 = 0;
      int var12 = 0;

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var14 : var2) {
         if (var9.contains(var14)) {
            this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var14, true);
            var11++;
         } else if (var14.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO)) {
            this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var14, false);
            var12++;
         }
      }

      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .IHCHHRRIIIORORCHIICIIOORCOIOIO()
         .ORCOCORROHIROCCIORORRRRCHIOOCH("Previews isolated", var11 + " kept on, " + var12 + " HUDs off. Snapshot saved.");
   }

   private void HHHCIRHHOICIHORHCRROOOHHIICHIC() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .IHIIROIOIHOHCHICOIIIHOHHCOIOCI();
      OHHRIOHROOIHOROCIRHCHORIHRRRRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = var1.ORICRIRORRCHHHRRHOORHIRCICHCCO()
         .CRRRICCRROCOHHOHIICIHORCOORRRH("previewIsolationSnapshot.json", OHHRIOHROOIHOROCIRHCHORIHRRRRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class);
      if (var2 != null && var2.HICCIIHOOCRCICHIORCIRRCHCRRCCO != null) {
         int var3 = 0;

         for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 : this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1)) {
            Boolean var6 = var2.HICCIIHOOCRCICHIORCIRRCHCRRCCO.get(var5.getId());
            if (var6 != null) {
               this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var5, var6);
               var3++;
            }
         }

         if (var2.ICICRCOIOIRRIOHCOROCIOHOOIORCO != null) {
            var1.HOHOCHCHIIHOHOHIIRCICCRORHIROH().RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(var2.ICICRCOIOIRRIOHCOROCIOHOOIORCO);
         }

         IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .IHCHHRRIIIORORCHIICIIOORCOIOIO()
            .ORCOCORROHIROCCIORORRRRCHIOOCH("Snapshot restored", var3 + " features returned to their saved state.");
      } else {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .IHCHHRRIIIORORCHIICIIOORCOIOIO()
            .ORCOCORROHIROCCIORORRRRCHIOOCH("Nothing to restore", "Run \"Isolate previews\" first to save a snapshot.");
      }
   }

   private static final class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      Map<String, Boolean> HICCIIHOOCRCICHIORCIRRCHCRRCCO = new LinkedHashMap<>();
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ICICRCOIOIRRIOHCOROCIOHOOIORCO;
   }
}
