package com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import java.util.function.BiConsumer;
import java.util.function.BiFunction;
import java.util.function.BiPredicate;
import java.util.function.Predicate;
import java.util.function.Supplier;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.Nullable;
import org.joml.Vector3d;
import org.joml.Vector3dc;

public interface HHCCIRHCCCIIRHCROHIORHIRHHIORH<T, I, H extends HRCHROOHRIHCRCRHRIIROCIRHOIRHH<H, ? extends H>, S extends com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH> {
   default void HOHRIOCOOOORORHICHRIROHRRRIHIC() {
   }

   RRCRRCORICCHOHHIRCHIROOHIIOHCO<T, ?, I, H, S> IOHICRIORIIOCOCCHCIHIRCHOHHICH();

   @Nullable
   S IOIHOICIIROHRRIRCCOCIOHIOCRHRO();

   CRHROHHHCIHHCOHCOORCRIHHIICROR IHHHCCIORHCHIHHCOIHOHHCHRRHIHR();

   CRHROHHHCIHHCOHCOORCRIHHIICROR IRCIOOHIOIHHOIHRHHCRHICOOCRIRH();

   BiFunction<T, I, H> ICICHRHIRIRROOIHCCCCROHRCIIIIH();

   default Supplier<H> ICIIRHROROOOROOHHHCOOIIROCRHII() {
      return this.IOHICRIORIIOCOCCHCIHIRCHOHHICH().OCCOOORHCCCCOROCCOHIRRIHOHHIOH();
   }

   default H CHRCRHHRCCOICCOOIIRIOHCOHCHHIC(T var1) {
      return this.IOHICRIORIIOCOCCHCIHIRCHOHHICH().OCHRCOIRRHCORRRHRIIRCIIRRHROCI().traverse(var1, this);
   }

   static <T, O, I, H extends HRCHROOHRIHCRCRHRIIROCIRHOIRHH<H, S>, S extends H, E extends com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH> HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RRCRRCORICCHOHHIRCHIROOHIIOHCO<T, O, I, H, E> var0
   ) {
      return new HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<>(var0);
   }

   class IRCIIHHICIHRCOCRROCOICRIHHCCHH<T, O, I, H extends HRCHROOHRIHCRCRHRIIROCIRHOIRHH<H, S>, S extends H, E extends com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH>
      extends HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> {
      private Supplier<CRRRICCRROCOHHOHIICIHORCOORRRH> CRCROHIRRICHCROHIOCORCCHCRCCIO;

      protected IRCIIHHICIHRCOCRROCOICRIHHCCHH(RRCRRCORICCHOHHIRCHIROOHIIOHCO<T, O, I, H, E> var1) {
         super(var1);
      }

      protected IRCIIHHICIHRCOCRROCOICRIHHCCHH(HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> var1) {
         super(var1);
      }

      @Override
      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<T, O, I, H, S, E> OOCHRIIIRIHRRCRIORHCROIIHCRRIC(
         Supplier<CRRRICCRROCOHHOHIICIHORCOORRRH> var1
      ) {
         this.CICOHOCROHICRICHOHIORRRICHROIC();
         this.CRCROHIRRICHCROHIOCORCCHCRCCIO = var1;
         return this;
      }

      @Override
      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1, double var2
      ) {
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<T, O, I, H, S, E>)this.OOCHRIIIRIHRRCRIORHCROIIHCRRIC(
            () -> {
               CRHROHHHCIHHCOHCOORCRIHHIICROR var3 = var1.bridge$getEyePosition();
               CRHROHHHCIHHCOHCOORCRIHHIICROR var4 = var1.RCRCIHCOCOOORIRCOHHOIOHROOOHOC();
               return CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                  var3,
                  CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
                     var3.bridge$xCoord() + var4.bridge$xCoord() * var2,
                     var3.bridge$yCoord() + var4.bridge$yCoord() * var2,
                     var3.bridge$zCoord() + var4.bridge$zCoord() * var2
                  )
               );
            }
         );
      }

      @Override
      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         double var2,
         CRHROHHHCIHHCOHCOORCRIHHIICROR var4
      ) {
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)this.OOCHRIIIRIHRRCRIORHCROIIHCRRIC(
            () -> {
               CRHROHHHCIHHCOHCOORCRIHHIICROR var4x = var1.bridge$getEyePosition();
               CRHROHHHCIHHCOHCOORCRIHHIICROR var5 = CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
                  var4x.bridge$xCoord() + var4.bridge$xCoord(), var4x.bridge$yCoord() + var4.bridge$yCoord(), var4x.bridge$zCoord() + var4.bridge$zCoord()
               );
               CRHROHHHCIHHCOHCOORCRIHHIICROR var6 = var1.RCRCIHCOCOOORIRCOHHOIOHROOOHOC();
               return CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                  var5,
                  CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
                     var5.bridge$xCoord() + var6.bridge$xCoord() * var2,
                     var5.bridge$yCoord() + var6.bridge$yCoord() * var2,
                     var5.bridge$zCoord() + var6.bridge$zCoord() * var2
                  )
               );
            }
         );
      }

      @Override
      public HHCCIRHCCCIIRHCROHIORHIRHHIORH<T, I, H, E> OHCOIORHOCCRICIHIOIRHRIRROCHRR() {
         if (this.HOICRHCHOORIIIHICRIHIOIHHHCRHR == null) {
            throw new RuntimeException("RayContext must have at least one trigger!");
         } else if (this.CRCRHIIRIOCCIOCIIRHOOIOCIROIOO == null && this.HCRCOHROCCOHRROOCHCHCOROORIRRO == null) {
            throw new RuntimeException("RayContext can only have a null predicate if a function is set!");
         } else {
            return this.HOICRHCHOORIIIHICRIHIOIHHHCRHR
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  this.CRCROHIRRICHCROHIOCORCCHCRCCIO,
                  this.ICIICHCOHRRICOCHIRHIOHOOHRIICH,
                  this.CRCRHIIRIOCCIOCIIRHOOIOCIROIOO,
                  this.HCRCOHROCCOHRROOCHCHCOROORIRRO
               );
         }
      }

      @Override
      protected void CICOHOCROHICRICHOHIORRRICHROIC() {
         super.CICOHOCROHICRICHOHIORRRICHROIC();
         if (this.CRCROHIRRICHCROHIOCORCCHCRCCIO != null) {
            throw new RuntimeException("Ray already has positions assigned! - RayPointSupplier");
         }
      }
   }

   class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H extends HRCHROOHRIHCRCRHRIIROCIRHOIRHH<H, S>, S extends H, E extends com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH> {
      private CRHROHHHCIHHCOHCOORCRIHHIICROR IIOIOHCCOHOHHRHIRCCHHOHHOORHII;
      private CRHROHHHCIHHCOHCOORCRIHHIICROR IICICIRRCRHHCIOIHRRIHIOHRHOCIR;
      @Nullable
      protected E ICIICHCOHRRICOCHIRHIOHOOHRIICH = (E)null;
      protected BiPredicate<I, O> CRCRHIIRIOCCIOCIIRHOOIOCIROIOO;
      @Nullable
      protected RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, E> HCRCOHROCCOHRROOCHCHCOROORIRRO;
      protected final RRCRRCORICCHOHHIRCHIROOHIIOHCO<T, O, I, H, E> HOICRHCHOORIIIHICRIHIOIHHHCRHR;

      protected RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RRCRRCORICCHOHHIRCHIROOHIIOHCO<T, O, I, H, E> var1) {
         this.HOICRHCHOORIIIHICRIHIOIHHHCRHR = var1;
      }

      protected RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> var1) {
         this.IIOIOHCCOHOHHRHIRCCHHOHHOORHII = var1.IIOIOHCCOHOHHRHIRCCHHOHHOORHII;
         this.IICICIRRCRHHCIOIHRRIHIOHRHOCIR = var1.IICICIRRCRHHCIOIHRRIHIOHRHOCIR;
         this.ICIICHCOHRRICOCHIRHIOHOOHRIICH = var1.ICIICHCOHRRICOCHIRHIOHOOHRIICH;
         this.CRCRHIIRIOCCIOCIIRHOOIOCIROIOO = var1.CRCRHIIRIOCCIOCIIRHOOIOCIROIOO;
         this.HCRCOHROCCOHRROOCHCHCOROORIRRO = var1.HCRCOHROCCOHRROOCHCHCOROORIRRO;
         this.HOICRHCHOORIIIHICRIHIOIHHHCRHR = var1.HOICRHCHOORIIIHICRIHIOIHHHCRHR;
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(E var1) {
         this.ICIICHCOHRRICOCHIRHIOHOOHRIICH = (E)var1;
         return this;
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         CRHROHHHCIHHCOHCOORCRIHHIICROR var1, CRHROHHHCIHHCOHCOORCRIHHIICROR var2
      ) {
         this.CICOHOCROHICRICHOHIORRRICHROIC();
         this.IIOIOHCCOHOHHRHIRCCHHOHHOORHII = var1;
         this.IICICIRRCRHHCIOIHRRIHIOHRHOCIR = var2;
         return this;
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Vector3dc var1, Vector3dc var2) {
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1.x(), var1.y(), var1.z()),
            CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2.x(), var2.y(), var2.z())
         );
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         CRHROHHHCIHHCOHCOORCRIHHIICROR var1, CRHROHHHCIHHCOHCOORCRIHHIICROR var2, double var3
      ) {
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            var1,
            CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
               var1.bridge$xCoord() + var2.bridge$xCoord() * var3,
               var1.bridge$yCoord() + var2.bridge$yCoord() * var3,
               var1.bridge$zCoord() + var2.bridge$zCoord() * var3
            )
         );
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         Vector3dc var1, Vector3dc var2, double var3
      ) {
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1.x(), var1.y(), var1.z()),
            CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2.x(), var2.y(), var2.z()),
            var3
         );
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         RORCHCIIICOHIRROOORHOCCCCIOCCI var1, RORCHCIIICOHIRROOORHOCCCCIOCCI var2
      ) {
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, true);
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         RORCHCIIICOHIRROOORHOCCCCIOCCI var1, RORCHCIIICOHIRROOORHOCCCCIOCCI var2, boolean var3
      ) {
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)(var3
            ? this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1.bridge$getX() + 0.5F, var1.bridge$getY() + 0.5F, var1.bridge$getZ() + 0.5F),
               CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2.bridge$getX() + 0.5F, var2.bridge$getY() + 0.5F, var2.bridge$getZ() + 0.5F)
            )
            : this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1.bridge$getX(), var1.bridge$getY(), var1.bridge$getZ()),
               CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2.bridge$getX(), var2.bridge$getY(), var2.bridge$getZ())
            ));
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1, double var2, float var4
      ) {
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1.bridge$getEyePosition(var4), var1.bridge$getViewVector(var4), var2
         );
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         double var2,
         CRHROHHHCIHHCOHCOORCRIHHIICROR var4,
         float var5
      ) {
         CRHROHHHCIHHCOHCOORCRIHHIICROR var6 = var1.bridge$getEyePosition(var5);
         CRHROHHHCIHHCOHCOORCRIHHIICROR var7 = CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
            var6.bridge$xCoord() + var4.bridge$xCoord(), var6.bridge$yCoord() + var4.bridge$yCoord(), var6.bridge$zCoord() + var4.bridge$zCoord()
         );
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var7, var1.bridge$getViewVector(var5), var2
         );
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         double var2,
         Vector3d var4,
         float var5
      ) {
         CRHROHHHCIHHCOHCOORCRIHHIICROR var6 = var1.bridge$getEyePosition(var5);
         CRHROHHHCIHHCOHCOORCRIHHIICROR var7 = CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
            var6.bridge$xCoord() + var4.x(), var6.bridge$yCoord() + var4.y(), var6.bridge$zCoord() + var4.z()
         );
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var7, var1.bridge$getViewVector(var5), var2
         );
      }

      @Contract(pure = true)
      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<T, O, I, H, S, E> OOCHRIIIRIHRRCRIORHCROIIHCRRIC(
         Supplier<CRRRICCRROCOHHOHIICIHORCOORRRH> var1
      ) {
         HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = new HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<>(this);
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<T, O, I, H, S, E>)var2.OOCHRIIIRIHRRCRIORHCROIIHCRRIC(var1);
      }

      @Contract(pure = true)
      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1, double var2
      ) {
         HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = new HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<>(this);
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<T, O, I, H, S, E>)var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2);
      }

      @Contract(pure = true)
      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         double var2,
         CRHROHHHCIHHCOHCOORCRIHHIICROR var4
      ) {
         HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = new HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<>(this);
         return (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E>)var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var4);
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(BiPredicate<I, O> var1) {
         this.CRCRHIIRIOCCIOCIIRHOOIOCIROIOO = var1;
         return this;
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> OCOHORHCROHICRRIHCIHHRRCIHICRI(Predicate<O> var1) {
         this.CRCRHIIRIOCCIOCIIRHOOIOCIROIOO = (var1x, var2) -> var1.test(var2);
         return this;
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, E> var1
      ) {
         this.CROHCCHOCIHCOCHCIICHCROIICRCRC();
         this.HCRCOHROCCOHRROOCHCHCOROORIRRO = var1;
         return this;
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T, O, I, H, S, E> HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
         BiConsumer<S, HHCCIRHCCCIIRHCROHIORHIRHHIORH<T, I, H, E>> var1
      ) {
         this.CROHCCHOCIHCOCHCIICHCROIICRCRC();
         this.HCRCOHROCCOHRROOCHCHCOROORIRRO = (var2, var3, var4, var5) -> {
            if (this.CRCRHIIRIOCCIOCIIRHOOIOCIROIOO.test(var4, var5)) {
               HRCHROOHRIHCRCRHRIIROCIRHOIRHH var6 = this.HOICRHCHOORIIIHICRIHIOIHHHCRHR.OHIHHRHOHOIHRCRIHCHICIHCOHHOHC().create(var2, var3, var4, var5);
               if (var6 != null) {
                  var6.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var2x -> var1.accept(var2x, var3));
               }
            }

            return null;
         };
         return this;
      }

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH<T, I, H, E> OHCOIORHOCCRICIHIOIRHRIRROCHRR() {
         if (this.HOICRHCHOORIIIHICRIHIOIHHHCRHR == null) {
            throw new RuntimeException("RayContext must have at least one trigger!");
         } else if (this.CRCRHIIRIOCCIOCIIRHOOIOCIROIOO == null && this.HCRCOHROCCOHRROOCHCHCOROORIRRO == null) {
            throw new RuntimeException("RayContext can only have a null predicate if a function is set!");
         } else {
            return this.HOICRHCHOORIIIHICRIHIOIHHHCRHR
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  this.IIOIOHCCOHOHHRHIRCCHHOHHOORHII,
                  this.IICICIRRCRHHCIOIHRRIHIOHRHOCIR,
                  this.ICIICHCOHRRICOCHIRHIOHOOHRIICH,
                  this.CRCRHIIRIOCCIOCIIRHOOIOCIROIOO,
                  this.HCRCOHROCCOHRROOCHCHCOROORIRRO
               );
         }
      }

      protected void CICOHOCROHICRICHOHIORRRICHROIC() {
         if (this.IIOIOHCCOHOHHRHIRCCHHOHHOORHII != null) {
            throw new RuntimeException(
               "Ray already has positions assigned! - [" + this.IIOIOHCCOHOHHRHIRCCHHOHHOORHII + ", " + this.IICICIRRCRHHCIOIHRRIHIOHRHOCIR + "]"
            );
         }
      }

      private void CROHCCHOCIHCOCHCIICHCROIICRCRC() {
         if (this.HCRCOHROCCOHRROOCHCHCOROORIRRO != null) {
            throw new RuntimeException(
               "Ray already has a function assigned! - [" + this.IIOIOHCCOHOHHRHIRCCHHOHHOORHII + ", " + this.IICICIRRCRHHCIOIHRRIHIOHRHOCIR + "]"
            );
         }
      }
   }
}
