package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.client.util.OOOOCCOOOHCHCIIHOIHCRIIOOROHRC;
import com.moonsworth.lunar.lib.adventure.text.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import lombok.Generated;
import org.jetbrains.annotations.NotNull;

public class RHOCHHIRRCHHHOHOIRROIROHHHIHIO {
   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH IIOOCRIHICIIHIHICHCCHIICIORRIH;
   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH RCIOOOIHROIRCROOIICOHHCORROHHR;
   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH RROICOIOIIIHRHRCIIOOCIRICOIHHO;
   private String owner;
   private RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH CCHRCRRHRROCOOIRHHOCIIICIORRHH;
   private List<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> ROHHRIHOCHHOCRCORRHHRIOROHIIOR;
   private List<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> CHIHHOCHHOCCIHCRIOIROOCOHOIROH;
   private OOOOCCOOOHCHCIIHOIHCRIIOOROHRC RHOHOCOOROCIOOHHCCRCIIRRRRHCHR;
   private RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ORHIIIOHCCCCRROHORHIICRHROIORH;
   private RORCHCIIICOHIRROOORHOCCCCIOCCI ICRHCOHOHIRRROHOCICOOCCIIHOOHI;

   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO(
      @NotNull CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      @NotNull CRRRICCRROCOHHOHIICIHORCOORRRH var2,
      @NotNull CRRRICCRROCOHHOHIICIHORCOORRRH var3,
      @NotNull String var4
   ) {
      this.IIOOCRIHICIIHIHICHCCHIICIORRIH = var1;
      this.RCIOOOIHROIRCROOIICOHHCORROHHR = var2;
      this.RROICOIOIIIHRHRCIIOOCIRICOIHHO = var3;
      this.owner = var4;
      this.CCHRCRRHRROCOOIRHHOCIIICIORRHH = RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SHIELD;
      this.ROHHRIHOCHHOCRCORRHHRIOROHIIOR = new ArrayList<>();
      this.CHIHHOCHHOCCIHCRIOIROOCOHOIROH = new ArrayList<>();
      this.RHOHOCOOROCIOOHHCCRCIIRRRRHCHR = null;
   }

   public boolean isValid() {
      if (this.RROICOIOIIIHRHRCIIOOCIRICOIHHO.bridge$getPosX() - this.RCIOOOIHROIRCROOIICOHHCORROHHR.bridge$getPosX() > 0.1
         || this.RROICOIOIIIHRHRCIIOOCIRICOIHHO.bridge$getPosY() - this.RCIOOOIHROIRCROOIICOHHCORROHHR.bridge$getPosY() > 0.5
         || this.RROICOIOIIIHRHRCIIOOCIRICOIHHO.bridge$getPosZ() - this.RCIOOOIHROIRCROOIICOHHCORROHHR.bridge$getPosZ() > 0.1) {
         return false;
      } else {
         return HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IIOOCRIHICIIHIHICHCCHIICIORRIH, this.RROICOIOIIIHRHRCIIOOCIRICOIHHO) > 4.0F
            ? false
            : !(HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IIOOCRIHICIIHIHICHCCHIICIORRIH, this.RCIOOOIHROIRCROOIICOHHCORROHHR) > 4.0F);
      }
   }

   public void IIIRIOIHIHIIROIIOHCRCOCHIRIIOI() {
      Component var1 = this.RIRRCRRIIRCCHIHOIIOICOOHIHROHR().bridge$getCustomName();
      if (var1 != null) {
         RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = this.RIRORIRROHIHOROIOCHHOHCCICIIIO();
         String var3 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.getTextContent(var1);
         Matcher var4 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OHRROOROCOIOCOCIHCRHRIHHCOOCOI
            .matcher(var3);
         if (var4.find()) {
            if (this.IIOOCRIHICIIHIHICHCCHIICIORRIH.bridge$isRiding()) {
               this.CCHRCRRHRROCOOIRHHOCIIICIORRHH = RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RADIATION;
            } else {
               String var5 = var4.group("extraData");
               this.CCHRCRRHRROCOOIRHHOCIIICIORRHH = var5.contains("Hit")
                  ? RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SHIELD
                  : RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NONE;
            }
         }

         if (this.CCHRCRRHRROCOOIRHHOCIIICIORRHH == RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RADIATION
            && var2 != RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RADIATION
            && (this.RHOHOCOOROCIOOHHCCRCIIRRRRHCHR == null || this.RHOHOCOOROCIOOHHCCRCIIRRRRHCHR.get() < 0L)) {
            this.RHOHOCOOROCIOOHHCCRCIIRRRRHCHR = new OOOOCCOOOHCHCIIHOIHCRIIOOROHRC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
               .RORCOCROCHRHROIIOCIOIRHIIIICOI()
               .CHCIRRHIOCIRHHRCOOOHIOOIOOOOHH()
               .IICCOOCHCHROORHHIIHROHCCRHRCOR(8000L)
               .OHRHHOOHHCRORRROIROCHORCROHHCI()
               .HRHIIHCRHHIIHCHCOHHHROORIIHOCR();
         }
      }
   }

   @Generated
   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH IHIIOCHCHICRHRHRIOOICIIICOCIIO() {
      return this.IIOOCRIHICIIHIHICHCCHIICIORRIH;
   }

   @Generated
   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH RIRRCRRIIRCCHIHOIIOICOOHIHROHR() {
      return this.RCIOOOIHROIRCROOIICOHHCORROHHR;
   }

   @Generated
   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH ROCHHIIHHCHORORHRHHIROOHROOIOC() {
      return this.RROICOIOIIIHRHRCIIOOCIRICOIHHO;
   }

   @Generated
   public String getOwner() {
      return this.owner;
   }

   @Generated
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH RIRORIRROHIHOROIOCHHOHCCICIIIO() {
      return this.CCHRCRRHRROCOOIRHHOCIIICIORRHH;
   }

   @Generated
   public List<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> CRIHIRIIIHHRRICRRICHCIIRRCCRIC() {
      return this.ROHHRIHOCHHOCRCORRHHRIOROHIIOR;
   }

   @Generated
   public List<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> OHRRIRCHRRHOCICRCCCCHCOIHCRRRC() {
      return this.CHIHHOCHHOCCIHCRIOIROOCOHOIROH;
   }

   @Generated
   public OOOOCCOOOHCHCIIHOIHCRIIOOROHRC HHHOIOCCIRCOCRRIOIIIHCCOHCCHHI() {
      return this.RHOHOCOOROCIOOHHCCRCIIRRRRHCHR;
   }

   @Generated
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IICOHORCCHRCOHRHIIHRORIOIIORIR() {
      return this.ORHIIIOHCCCCRROHORHIICRHROIORH;
   }

   @Generated
   public RORCHCIIICOHIRROOORHOCCCCIOCCI OIHCCHRCHICHRRIHORHCHIHCCOCIRI() {
      return this.ICRHCOHOHIRRROHOCICOOCCIIHOOHI;
   }

   @Generated
   public void IIIIRHIHROIRCROHHROIHIIHRCRRHO(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      this.IIOOCRIHICIIHIHICHCCHIICIORRIH = var1;
   }

   @Generated
   public void RRRHHIRORHCHHCOOCIHOICORHHCHHO(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      this.RCIOOOIHROIRCROOIICOHHCORROHHR = var1;
   }

   @Generated
   public void ORIOHRCIHRCOOHICCCRIIIHCRHHIHI(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      this.RROICOIOIIIHRHRCIIOOCIRICOIHHO = var1;
   }

   @Generated
   public void setOwner(String var1) {
      this.owner = var1;
   }

   @Generated
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.CCHRCRRHRROCOOIRHHOCIIICIORRHH = var1;
   }

   @Generated
   public void IHRHHHORORIROOCORCIORRCOCHHHRI(
      List<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> var1
   ) {
      this.ROHHRIHOCHHOCRCORRHHRIOROHIIOR = var1;
   }

   @Generated
   public void OIOORROOHCRRCOCOHICICRCIOCIIOH(
      List<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> var1
   ) {
      this.CHIHHOCHHOCCIHCRIOIROOCOHOIROH = var1;
   }

   @Generated
   public void RRCRRCORICCHOHHIRCHIROOHIIOHCO(OOOOCCOOOHCHCIIHOIHCRIIOOROHRC var1) {
      this.RHOHOCOOROCIOOHHCCRCIIRRRRHCHR = var1;
   }

   @Generated
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1) {
      this.ORHIIIOHCCCCRROHORHIICRHROIORH = var1;
   }

   @Generated
   public void IOIICIRIICICIIOORHCIIIIRRIHRHI(RORCHCIIICOHIRROOORHOCCCCIOCCI var1) {
      this.ICRHCOHOHIRRROHOCICOOCCIIHOOHI = var1;
   }

   public enum IRCIIHHICIHRCOCRROCOICRIHHCCHH {
      SHIELD,
      RADIATION,
      NONE;
   }

   public static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH OCOIORCRROIOOCHORHHHROCHCCIHRR;
      private CRHROHHHCIHHCOHCOORCRIHHIICROR RRIHRHCOCCRROCCHIRHHHIIICHCRRR;
      private long HHHCOOHOIIHCIHIOCRCOHRHRCIROHI;

      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
      ) {
         this.OCOIORCRROIOOCHORHHHROCHCCIHRR = var1;
         this.RRIHRHCOCCRROCCHIRHHHIIICHCRRR = null;
         this.HHHCOOHOIIHCIHIOCRCOHRHRCIROHI = -1L;
      }

      @Generated
      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         CRHROHHHCIHHCOHCOORCRIHHIICROR var2,
         long var3
      ) {
         this.OCOIORCRROIOOCHORHHHROCHCCIHRR = var1;
         this.RRIHRHCOCCRROCCHIRHHHIIICHCRRR = var2;
         this.HHHCOOHOIIHCIHIOCRCOHRHRCIROHI = var3;
      }

      @Generated
      public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH HCICROIHRHRCORRHCOIHIHCCCCHRHH() {
         return this.OCOIORCRROIOOCHORHHHROCHCCIHRR;
      }

      @Generated
      public CRHROHHHCIHHCOHCOORCRIHHIICROR IIOIIRRORRRIOHHCIIHHCCIHHROIRI() {
         return this.RRIHRHCOCCRROCCHIRHHHIIICHCRRR;
      }

      @Generated
      public long ICRRIHIRHIHIIOCRIIRCHRCCCHHCOI() {
         return this.HHHCOOHOIIHCIHIOCRCOHRHRCIROHI;
      }

      @Generated
      public void CHHIICHRIIROIOHIHIIROICOCCROCI(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
      ) {
         this.OCOIORCRROIOOCHORHHHROCHCCIHRR = var1;
      }

      @Generated
      public void HICHRCOHCCRHOHCICOOCHOIHCCHIRI(CRHROHHHCIHHCOHCOORCRIHHIICROR var1) {
         this.RRIHRHCOCCRROCCHIRHHHIIICHCRRR = var1;
      }

      @Generated
      public void IOIOHIORIROHRRCOOOHCROHORCOIIH(long var1) {
         this.HHHCOOHOIIHCIHIOCRCOHRHRCIROHI = var1;
      }
   }
}
