package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import java.time.Duration;
import java.util.concurrent.Callable;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
public interface CCHHCIRHICHHHHRRIHIORCCORCCIHR extends RHOORRIIOCHIRRHOHOOHIROHCRICRO, ScheduledExecutorService {
   RHRRHOHCRCHCCRRHOHHIRCCHOCICHC<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Runnable var1, long var2, TimeUnit var4);

   default RHRRHOHCRCHCCRRHOHHIRCCHOCICHC<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Runnable var1, Duration var2) {
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, IOHHOIIOCRHCHHCRORICCOHOHROOIH.toNanosSaturated(var2), TimeUnit.NANOSECONDS);
   }

   <V> RHRRHOHCRCHCCRRHOHHIRCCHOCICHC<V> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Callable<V> var1, long var2, TimeUnit var4);

   default <V> RHRRHOHCRCHCCRRHOHHIRCCHOCICHC<V> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Callable<V> var1, Duration var2) {
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, IOHHOIIOCRHCHHCRORICCOHOHROOIH.toNanosSaturated(var2), TimeUnit.NANOSECONDS);
   }

   RHRRHOHCRCHCCRRHOHHIRCCHOCICHC<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Runnable var1, long var2, long var4, TimeUnit var6);

   default RHRRHOHCRCHCCRRHOHHIRCCHOCICHC<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Runnable var1, Duration var2, Duration var3) {
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1, IOHHOIIOCRHCHHCRORICCOHOHROOIH.toNanosSaturated(var2), IOHHOIIOCRHCHHCRORICCOHOHROOIH.toNanosSaturated(var3), TimeUnit.NANOSECONDS
      );
   }

   RHRRHOHCRCHCCRRHOHHIRCCHOCICHC<?> IRCIIHHICIHRCOCRROCOICRIHHCCHH(Runnable var1, long var2, long var4, TimeUnit var6);

   default RHRRHOHCRCHCCRRHOHHIRCCHOCICHC<?> IRCIIHHICIHRCOCRROCOICRIHHCCHH(Runnable var1, Duration var2, Duration var3) {
      return this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         var1, IOHHOIIOCRHCHHCRORICCOHOHROOIH.toNanosSaturated(var2), IOHHOIIOCRHCHHCRORICCOHOHROOIH.toNanosSaturated(var3), TimeUnit.NANOSECONDS
      );
   }
}
