package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import java.time.Duration;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
final class IOHHOIIOCRHCHHCRORICCOHOHROOIH {
   static long toNanosSaturated(Duration var0) {
      try {
         return var0.toNanos();
      } catch (ArithmeticException var2) {
         return var0.isNegative() ? Long.MIN_VALUE : Long.MAX_VALUE;
      }
   }

   private IOHHOIIOCRHCHHCRORICCOHOHROOIH() {
   }
}
