package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.DoNotMock;
import java.time.Duration;
import java.util.concurrent.Executor;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

@DoNotMock("Use FluentFuture.from(Futures.immediate*Future) or SettableFuture")
@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
   emulated = true
)
public abstract class ORHIOICIOCRRHOOCOHRORIHICHRCRR<V> extends HCHRIROHHHCORIOCROOCHRCIOROOCI<V> {
   ORHIOICIOCRRHOOCOHRORIHICHRCRR() {
   }

   public static <V> ORHIOICIOCRRHOOCOHRORIHICHRCRR<V> RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(RCCCROCHCICCROHCOCCRRROCIIHCCH<V> var0) {
      return var0 instanceof ORHIOICIOCRRHOOCOHRORIHICHRCRR ? (ORHIOICIOCRRHOOCOHRORIHICHRCRR)var0 : new RIRHOCHIORCCIIOIIRHOCCCRHHCHHH<>(var0);
   }

   @Deprecated
   public static <V> ORHIOICIOCRRHOOCOHRORIHICHRCRR<V> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(ORHIOICIOCRRHOOCOHRORIHICHRCRR<V> var0) {
      return com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var0
      );
   }

   @IOIOHIORIROHRRCOOOHCROHORCOIIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("AVAILABLE but requires exceptionType to be Throwable.class")
   public final <X extends Throwable> ORHIOICIOCRRHOOCOHRORIHICHRCRR<V> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Class<X> var1,
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<? super X, ? extends V> var2,
      Executor var3
   ) {
      return (ORHIOICIOCRRHOOCOHRORIHICHRCRR<V>)OHIIIOHIRIRCCRRIOIICCHHIORRHOH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, var1, var2, var3);
   }

   @IOIOHIORIROHRRCOOOHCROHORCOIIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("AVAILABLE but requires exceptionType to be Throwable.class")
   public final <X extends Throwable> ORHIOICIOCRRHOOCOHRORIHICHRCRR<V> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Class<X> var1, IIHRRHORCRCROCHHOHORCHCROCIHRO<? super X, ? extends V> var2, Executor var3
   ) {
      return (ORHIOICIOCRRHOOCOHRORIHICHRCRR<V>)OHIIIOHIRIRCCRRIOIICCHHIORRHOH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, var1, var2, var3);
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
   public final ORHIOICIOCRRHOOCOHRORIHICHRCRR<V> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Duration var1, ScheduledExecutorService var2) {
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IOHHOIIOCRHCHHCRORICCOHOHROOIH.toNanosSaturated(var1), TimeUnit.NANOSECONDS, var2);
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
   public final ORHIOICIOCRRHOOCOHRORIHICHRCRR<V> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(long var1, TimeUnit var3, ScheduledExecutorService var4) {
      return (ORHIOICIOCRRHOOCOHRORIHICHRCRR<V>)OHIIIOHIRIRCCRRIOIICCHHIORRHOH.<V>RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, var1, var3, var4);
   }

   public final <T> ORHIOICIOCRRHOOCOHRORIHICHRCRR<T> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIHRRHORCRCROCHHOHORCHCROCIHRO<? super V, T> var1, Executor var2) {
      return (ORHIOICIOCRRHOOCOHRORIHICHRCRR<T>)OHIIIOHIRIRCCRRIOIICCHHIORRHOH.<V, T>IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, var1, var2);
   }

   public final <T> ORHIOICIOCRRHOOCOHRORIHICHRCRR<T> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<? super V, T> var1,
      Executor var2
   ) {
      return (ORHIOICIOCRRHOOCOHRORIHICHRCRR<T>)OHIIIOHIRIRCCRRIOIICCHHIORRHOH.<V, T>IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, var1, var2);
   }

   public final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(OOCCRCRCOHIIORCCORCRCIRRROIOOR<? super V> var1, Executor var2) {
      OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, var1, var2);
   }

   abstract static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<V>
      extends ORHIOICIOCRRHOOCOHRORIHICHRCRR<V>
      implements com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR<V> {
      @CanIgnoreReturnValue
      @Override
      public final V get() {
         return super.get();
      }

      @CanIgnoreReturnValue
      @Override
      public final V get(long var1, TimeUnit var3) {
         return super.get(var1, var3);
      }

      @Override
      public final boolean isDone() {
         return super.isDone();
      }

      @Override
      public final boolean isCancelled() {
         return super.isCancelled();
      }

      @Override
      public final void addListener(Runnable var1, Executor var2) {
         super.addListener(var1, var2);
      }

      @CanIgnoreReturnValue
      @Override
      public final boolean cancel(boolean var1) {
         return super.cancel(var1);
      }
   }
}
