package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH;

import com.google.common.cache.Cache;
import com.google.common.cache.CacheBuilder;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH;
import io.netty.util.concurrent.DefaultThreadFactory;
import it.unimi.dsi.fastutil.longs.Long2ObjectArrayMap;
import it.unimi.dsi.fastutil.longs.Long2ObjectMap;
import it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.longs.LongIterator;
import it.unimi.dsi.fastutil.longs.LongOpenHashSet;
import it.unimi.dsi.fastutil.longs.LongSet;
import it.unimi.dsi.fastutil.longs.Long2ObjectMap.Entry;
import it.unimi.dsi.fastutil.objects.ObjectIterator;
import java.io.IOException;
import java.util.Queue;
import java.util.concurrent.ConcurrentLinkedDeque;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.BiConsumer;
import lombok.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.joml.Vector3i;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private int RIORORCRCCCHOHHOCHHHOCIIOCRORH = 14;
   private int RIIOCOIOOHIIRHCCRCRRHRCHRROROC = 14;
   private int HHORHRICOICOHHOCRRIRHIORICOHII = 0;
   private int CCHRHOHCCRCRRHROOIHCIHRCRRIRHO = 0;
   private boolean ROIHCIIIRIORHORHIRRHROCCCORIOC = false;
   protected int RHHOOHRCRRHROICORIIIOOCHRRCHHC;
   protected int RRRROCOHORIIRHHRCIHOHOIICIHHRC;
   private int OCOORORHRCRRIOICICCIHOIIOCHROI;
   private int OIOORHORRHCOCOHHOOCHIHRCICRCCI;
   private int HOOCOOOIHHROHHRIIIHCOICCHOHOHI;
   private int OIOOICHIIHICCRCOOIOIOCIRRIIIRC;
   private double IRCIORRIRHIRCCRHHOOCCICOOCIROO;
   private double OHRCCHROOOCCCRIIHOROIIIRRRRHHC;
   private Vector3i HHOHHRRROCOIRICHOORHIRCRHCHIRO;
   private final ExecutorService CCHHRCCIRCOIHCHCROIIOROHHIICRI = Executors.newSingleThreadExecutor(new DefaultThreadFactory("lunar-map-manager-thread", true));
   private final LongSet OHCRIHOORRHHRIORCOROIHOIORCROO = new LongOpenHashSet();
   private final Cache<Long, com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH> HRICCRCCRIIHIHOHIROCHHCOOIOHHI = CacheBuilder.newBuilder()
      .maximumSize(8192L)
      .expireAfterAccess(5L, TimeUnit.MINUTES)
      .build();
   private final Long2ObjectMap<LongSet> ICCOROICHHORIOIOICHHRIHHICHHHC = new Long2ObjectOpenHashMap();
   private final LongSet OCHROOIOCIRCOOOIRORROCCIRRRCCR = new LongOpenHashSet();
   private final RCIROOOOICRHCCRRCIORHHIRCOIIIC HICOROIHOHHIOCOIRIIIHRCIORHIII = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "minimap-mod-texture");
   private IRRCCOICORICIHCHRHIHIHROIRHOCR HCHIHOIROHHIIRCIRORRRCORHOORCC;
   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH ROOOCCIOHHICHRHRHCIRORICRCRIOR;
   private final Queue<RIOOCHICIHRHOHCCCCCHOCCCOHCRHI> IHHIRRICHOHHCIRRCCHRHOIHHRCRHR = new ConcurrentLinkedDeque<>();
   private final RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HRIROOROIICRRRICCHRIHHIORCRCOC = new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();

   public void setup() {
      this.HHRIICOIOORCHCOIICOOIHIRHHICRI((this.RIORORCRCCCHOHHOCHHHOCIIOCRORH - 1) * 16, (this.RIIOCOIOOHIIRHCCRCRRHRCHRROROC - 1) * 16);
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() != null) {
         this.CRRRICCRROCOHHOHIICIHORCOORRRH(this.OCOORORHRCRRIOICICCIHOIIOCHROI, this.OIOORHORRHCOCOHHOOCHIHRCICRCCI, true);
      }
   }

   public void clear() {
      this.HRICCRCCRIIHIHOHIROCHHCOOIOHHI.invalidateAll();
      this.ICCOROICHHORIOIOICHHRIHHICHHHC.clear();
      this.OCHROOIOCIRCOOOIRORROCCIRRRCCR.clear();
      this.OHCRIHOORRHHRIORCOROIHOIORCROO.clear();
      this.IHHIRRICHOHHCIRRCCHRHOIHHRCRHR.clear();
      if (this.HCHIHOIROHHIIRCIRORRRCORHOORCC != null) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getTextureManager().bridge$deleteTexture(this.HICOROIHOHHIOCOIRIIIHRCIORHIII);
         this.HCHIHOIROHHIIRCIRORRRCORHOORCC = null;
      }

      this.HHOHHRRROCOIRICHOORHIRCRHCHIRO = null;
      this.ROIHCIIIRIORHORHIRRHROCCCORIOC = false;
      this.HRIROOROIICRRRICCHRIHHIORCRCOC.reset();
   }

   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(@NotNull RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1) {
      long var2 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
         var1.bridge$getX(), var1.bridge$getZ()
      );
      if (this.OHCRIHOORRHHRIORCOROIHOIORCROO.contains(var2)) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var4 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH)this.HRICCRCCRIIHIHOHIROCHHCOOIOHHI
            .getIfPresent(var2);
         if (var4 != null) {
            var4.COIRRRCIORROCHIROCHROCHICCICIC(false);
         }

         this.CCHHRCCIRCOIHCHCROIIOROHHIICRI
            .submit(
               () -> {
                  RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var4x = new RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
                     RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SINGLE_CHUNK,
                     this.RHHOOHRCRRHROICORIIIOOCHRRCHHC,
                     this.RRRROCOHORIIRHHRCIHOHOIICIHHRC
                  );
                  this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var4x);
                  if (!var4x.RRROIOOCOCOIHIHHHOOHRRHRIROHHR().isEmpty()) {
                     this.IHHIRRICHOHHCIRRCCHRHOIHHRCRHR.add(var4x);
                  }
               }
            );
      }
   }

   public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(@NotNull RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1) {
      if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.IICRHHRRIROHOIICHRIOROHIHROORO()) {
         long var2 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(
            var1.bridge$getX(), var1.bridge$getZ()
         );
         LongSet var4 = (LongSet)this.ICCOROICHHORIOIOICHHRIHHICHHHC.get(var2);
         if (var4 != null) {
            var4.remove(
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
                  var1.bridge$getX(), var1.bridge$getZ()
               )
            );
            if (var4.isEmpty()) {
               this.ICCOROICHHORIOIOICHHRIHHICHHHC.remove(var2);
               this.OCHROOIOCIRCOOOIRORROCCIRRRCCR.remove(var2);

               try {
                  HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var1.bridge$getWorld().bridge$getDimensionId(), var2, this.HRICCRCCRIIHIHOHIROCHHCOOIOHHI, this
                  );
               } catch (IOException var6) {
                  throw new RuntimeException(var6);
               }
            }
         }
      }
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      if (var2 != null) {
         double var3 = RHRIIOOOCRHIIOORCOCRCHRCCRRCIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            var2.RHRCCCOORROCRICCICHHCCCCIICIHH(),
            var2.bridge$getPosX(),
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$isGamePaused() ? 1.0F : var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR()
         );
         double var5 = RHRIIOOOCRHIIOORCOCRCHRCCRRCIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            var2.RHOROIIHICOCIICIICRHHOOOROIIOO(),
            var2.bridge$getPosZ(),
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$isGamePaused() ? 1.0F : var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR()
         );
         this.IRCIORRIRHIRCCRHHOOCCICOOCIROO = var3;
         this.OHRCCHROOOCCCRIIHOROIIIRRRRHHC = var5;
      }
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
      boolean var3
   ) {
      if (var2 != null) {
         int var4 = RHRIIOOOCRHIIOORCOCRCHRCCRRCIH.IICCOOCHCHROORHHIIHROHCCRHRCOR(this.IRCIORRIRHIRCCRHHOOCCICOOCIROO);
         int var5 = RHRIIOOOCRHIIOORCOCRCHRCCRRCIH.IICCOOCHCHROORHHIIHROHCCRHRCOR(this.OHRCCHROOOCCCRIIHOROIIIRRRRHHC);
         int var6 = RHRIIOOOCRHIIOORCOCRCHRCCRRCIH.IICCOOCHCHROORHHIIHROHCCRHRCOR(var2.bridge$getPosY());
         if (this.HHOHHRRROCOIRICHOORHIRCRHCHIRO == null
            || this.HHOHHRRROCOIRICHOORHIRCRHCHIRO.x != var4 >> 4
            || this.HHOHHRRROCOIRICHOORHIRCRHCHIRO.z != var5 >> 4) {
            this.IHHIRRICHOHHCIRRCCHRHOIHHRCRHR.clear();
            this.CRRRICCRROCOHHOHIICIHORCOORRRH(var4, var5, false);
            this.HHOHHRRROCOIRICHOORHIRCRHCHIRO = new Vector3i(var4 >> 4, var6, var5 >> 4);
         }

         if (this.HICOROIHOHHIOCOIRIIIHRCIORHIII != null) {
            double var7 = this.OOOROOHIIHOOHOOHOOCIIRHHCRIIOH();
            double var9 = this.IICCRORROHORHRRCHIIORRHCHHROHH();
            var1.push();
            float var11 = (int)(this.RIORORCRCCCHOHHOCHHHOCIIOCRORH / 2.0F) * 16;
            float var12 = (int)(this.RIIOCOIOOHIIRHCCRCRRHRCHRROROC / 2.0F) * 16;
            if (var3) {
               var1.CRICCOOHHHCHOORCICOCOHIHOIRHOO(-var11 + 16.0F, -var12 + 16.0F, 0.0F);
               var1.CRICCOOHHHCHOORCICOCOHIHOIRHOO((float)(-var7), (float)(-var9), 0.0F);
            }

            com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
               var1, 0.0F, 0.0F, this.HHORHRICOICOHHOCRRIRHIORICOHII, this.CCHRHOHCCRCRRHROOIHCIHRCRRIRHO, -16777216
            );
            com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               var1, this.HICOROIHOHHIOCOIRIIIHRCIORHIII, 0.0F, 0.0F, this.HHORHRICOICOHHOCRRIRHIORICOHII, this.CCHRHOHCCRCRRHROOIHCIHRCRRIRHO, -1
            );
            var1.pop();
         }
      }
   }

   public void OCROHICRHIRRHCCIIRCOCIHROROORO() {
      if (this.HHORHRICOICOHHOCRRIRHIORICOHII > 0
         && this.CCHRHOHCCRCRRHROOIHCIHRCRRIRHO > 0
         && this.ROIHCIIIRIORHORHIRRHROCCCORIOC
         && !IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$isGamePaused()) {
         RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var1 = this.IHHIRRICHOHHCIRRCCHRHOIHHRCRHR.peek();
         if (var1 != null) {
            Long2ObjectOpenHashMap var2 = new Long2ObjectOpenHashMap();

            do {
               if (var1.RHCOORIIHHOCHICIOICOIOOCCIOROC() == RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.FULL_MAP) {
                  this.ROOOCCIOHHICHRHRHCIRORICRCRIOR.bridge$framebufferClear(true);
                  IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
                     .bridge$overrideMainRenderTarget(IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getMainRenderTarget(), false, true);
               }

               while (
                  !var1.RRROIOOCOCOIHIHHHOOHRRHRIROHHR().isEmpty() && !IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$isGamePaused()
               ) {
                  RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = var1.RRROIOOCOCOIHIHHHOOHRRHRIROHHR().remove();
                  if (this.OHCRIHOORRHHRIORCOROIHOIORCROO.contains(var3.RIOOIRROIOIORCICHIOHCHCOCROICO())) {
                     int var4 = (
                           com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRIICOIOORCHCOIICOOIHIRHHICRI(
                                 var3.RIOOIRROIOIORCICHIOHCHCOCROICO()
                              )
                              << 4
                        )
                        - var1.HIOOIIHCHICIRIORHIOIHRHHICOICO();
                     int var5 = (
                           com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
                                 var3.RIOOIRROIOIORCICHIOHCHCOCROICO()
                              )
                              << 4
                        )
                        - var1.OHHCHRIRCROOIIHRHOOOOCCHCOIIRH();
                     if (var4 >= 0 && var4 <= this.HHORHRICOICOHHOCRRIRHIORICOHII - 16 && var5 >= 0 && var5 <= this.CCHRHOHCCRCRRHROOIHCIHRCRRIRHO - 16) {
                        int var6 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHCHRCCRRHORIOCIOHHCRHCHICRIHH()
                           .IIIORCCOIHHRCIRHOCIIICOHOOCHIH()
                           .HIRRIHOOOHHRRCHOIRIHHOIHIRRCRC;
                        if (16 > var6) {
                           throw new IllegalStateException("glTexSubImage2D: Texture dimensions exceed maximum allowed size!");
                        }

                        this.HCHIHOIROHHIIRCIRORRRCORHOORCC.bridge$upload(var4, var5, 16, 16, var3.HRRHOORRIRIRRHHCHIORORRCHRIHCR());
                     }
                  }
               }

               boolean var7 = !var1.RRROIOOCOCOIHIHHHOOHRRHRIROHHR().isEmpty();
               if (var7) {
                  return;
               }

               var2.putAll(var1.RRRRIOOCHIIIIHOOCOOROCICIHIHIH());
               if (var1.RHCOORIIHHOCHICIOICOIOOCCIOROC() == RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.FULL_MAP) {
                  this.HOOCOOOIHHROHHRIIIHCOICCHOHOHI = this.OCOORORHRCRRIOICICCIHOIIOCHROI;
                  this.OIOOICHIIHICCRCOOIOIOCIRRIIIRC = this.OIOORHORRHCOCOHHOOCHIHRCICRCCI;
               }

               this.IHHIRRICHOHHCIRRCCHRHOIHHRCRHR.poll();
               var1 = this.IHHIRRICHOHHCIRRCCHRHOIHHRCRHR.peek();
            } while (var1 != null && var1.RHCOORIIHHOCHICIOICOIOOCCIOROC() == RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SINGLE_CHUNK);

            if (!var2.isEmpty()) {
               this.HRIROOROIICRRRICCHRIHHIORCRCOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2);
            }
         }
      }
   }

   private Long2ObjectMap<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      @Nullable RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1, long var2, RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var4
   ) {
      Object var5 = null;

      try {
         if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.IICRHHRRIROHOIICHRIOROHIHROORO()) {
            long var6 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRIICOIOORCHCOIICOOIHIRHHICRI(
                  var2
               ),
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
                  var2
               )
            );
            if (!this.OCHROOIOCIRCOOOIRORROCCIRRRCCR.contains(var6) && var1 != null) {
               this.OCHROOIOCIRCOOOIRORROCCIRRRCCR.add(var6);
               var5 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.bridge$getWorld().bridge$getDimensionId(), var6, this);
               if (var1.bridge$isLoaded()) {
                  ((LongSet)this.ICCOROICHHORIOIOICHHRIHHICHHHC.computeIfAbsent(var6, var0 -> new LongOpenHashSet())).add(var2);
               }
            }
         }

         if (var5 == null) {
            var5 = new Long2ObjectArrayMap();
         }

         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var11 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH)this.HRICCRCCRIIHIHOHIROCHHCOOIOHHI
            .getIfPresent(var2);
         if (var11 != null) {
            if (var1 != null && !var1.bridge$isLoaded()) {
               this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
               return (Long2ObjectMap<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH>)var5;
            }
         } else {
            if (var1 == null || !var1.bridge$isLoaded()) {
               return (Long2ObjectMap<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH>)var5;
            }

            var11 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH();
            this.HRICCRCCRIIHIHOHIROCHHCOOIOHHI.put(var2, var11);
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var7 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
            if (var7 != null) {
               int var8 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRIICOIOORCHCOIICOOIHIRHHICRI(
                  var2
               );
               int var9 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
                  var2
               );
               this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var7.bridge$getChunk(var8, var9 - 1));
            }
         }

         if (!var11.RCORROCRRCHROICOICHOIOOHRHRHCC()) {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var12 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
            boolean var14 = var11.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, var1, var2, var12 != null && var12.bridge$getDimensionId() == -1);
            if (var14) {
               var5.put(var2, var11);
            }
         }

         var4.RRROIOOCOCOIHIHHHOOHRRHRIROHHR()
            .add(new RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var11.HCCROOIHHOCIHOROHOOIIHHRORICOH()));
         ObjectIterator var13 = var5.long2ObjectEntrySet().iterator();

         while (var13.hasNext()) {
            Entry var15 = (Entry)var13.next();
            var4.RRRRIOOCHIIIIHOOCOOROCICIHIHIH()
               .put(
                  var15.getLongKey(),
                  ((com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH)var15.getValue())
                     .HCCROOIHHOCIHOROHOOIIHHRORICOH()
               );
         }
      } catch (Throwable var10) {
         var10.printStackTrace();
         com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH(
            "Minimap", "Failed to run computeColorMapAndUpdateTexture()", var10
         );
      }

      return (Long2ObjectMap<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH>)(var5
            == null
         ? new Long2ObjectArrayMap()
         : var5);
   }

   private void IRCCOOIIROIHRHIHHCICHHCOOIOHIR() {
      RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var1 = new RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
         RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.FULL_MAP, this.RHHOOHRCRRHROICORIIIOOCHRRCHHC, this.RRRROCOHORIIRHHRCIHOHOIICIHHRC
      );
      this.OHCRIHOORRHHRIORCOROIHOIORCROO
         .forEach(
            var2 -> {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
               if (var4 != null) {
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = var4.bridge$getChunk(
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRIICOIOORCHCOIICOOIHIRHHICRI(
                        var2
                     ),
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
                        var2
                     )
                  );
                  this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5, var2, var1);
               }
            }
         );
      if (!var1.RRROIOOCOCOIHIHHHOOHRRHRIROHHR().isEmpty()) {
         this.IHHIRRICHOHHCIRRCCHRHOIHHRCRHR.add(var1);
      } else {
         this.HOOCOOOIHHROHHRIIIHCOICCHOHOHI = this.OCOORORHRCRRIOICICCIHOIIOCHROI;
         this.OIOOICHIIHICCRCOOIOIOCIRRIIIRC = this.OIOORHORRHCOCOHHOOCHIHRCICRCCI;
      }
   }

   public void CRRRICCRROCOHHOHIICIHORCOORRRH(int var1, int var2, boolean var3) {
      int var4 = this.OCOORORHRCRRIOICICCIHOIIOCHROI;
      int var5 = this.OIOORHORRHCOCOHHOOCHIHRCICRCCI;
      if (var3 || (var4 & -16) != (var1 & -16) || (var5 & -16) != (var2 & -16)) {
         this.OCOORORHRCRRIOICICCIHOIIOCHROI = var1 & -16;
         this.OIOORHORRHCOCOHHOOCHIHRCICRCCI = var2 & -16;
         this.RHHOOHRCRRHROICORIIIOOCHRRCHHC = this.OCOORORHRCRRIOICICCIHOIIOCHROI - (this.RIORORCRCCCHOHHOCHHHOCIIOCRORH - 1) / 2 * 16;
         this.RRRROCOHORIIRHHRCIHOHOIICIHHRC = this.OIOORHORRHCOCOHHOOCHIHRCICRCCI - (this.RIIOCOIOOHIIRHCCRCRRHRCHRROROC - 1) / 2 * 16;
         int var6 = this.RIORORCRCCCHOHHOCHHHOCIIOCRORH / 2;
         int var7 = this.RIIOCOIOOHIIRHCCRCRRHRCHRROROC / 2;
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var8 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
         if (var8 != null) {
            LongIterator var9 = this.OHCRIHOORRHHRIORCOROIHOIORCROO.iterator();

            while (var9.hasNext()) {
               Long var10 = (Long)var9.next();
               int var11 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRIICOIOORCHCOIICOOIHIRHHICRI(
                     var10
                  )
                  - (this.OCOORORHRCRRIOICICCIHOIIOCHROI >> 4);
               int var12 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
                     var10
                  )
                  - (this.OIOORHORRHCOCOHHOOCHIHRCICRCCI >> 4);
               if (var11 <= -var6 || var11 >= var6 || var12 <= -var7 || var12 >= var7) {
                  this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var8.bridge$getChunk(var11, var12));
               }
            }
         }

         this.OHCRIHOORRHHRIORCOROIHOIORCROO.clear();
         int var15 = this.OCOORORHRCRRIOICICCIHOIIOCHROI >> 4;
         int var16 = this.OIOORHORRHCOCOHHOOCHIHRCICRCCI >> 4;

         for (int var17 = -var6 + 1; var17 < var6; var17++) {
            for (int var18 = -var7 + 1; var18 < var7; var18++) {
               int var13 = var15 + var17;
               int var14 = var16 + var18;
               this.OHCRIHOORRHHRIORCOROIHOIORCROO
                  .add(
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
                        var13, var14
                     )
                  );
            }
         }

         this.CCHHRCCIRCOIHCHCROIIOROHHIICRI.submit(this::IRCCOOIIROIHRHIHHCICHHCOOIOHIR);
      }
   }

   public void reset() {
      this.IHHIRRICHOHHCIRRCCHRHOIHHRCRHR.clear();
      this.OHCRIHOORRHHRIORCOROIHOIORCROO.clear();
      this.HRICCRCCRIIHIHOHIROCHHCOOIOHHI.invalidateAll();
      this.ICCOROICHHORIOIOICHHRIHHICHHHC.clear();
      this.OCHROOIOCIRCOOOIRORROCCIRRRCCR.clear();
      this.CCHHRCCIRCOIHCHCROIIOROHHIICRI.submit(this::IRCCOOIIROIHRHIHHCICHHCOOIOHIR);
      this.HRIROOROIICRRRICCHRIHHIORCRCOC.reset();
   }

   public void IOIICIRIICICIIOORHCIIIIRRIHRHI(int var1, int var2) {
      if ((var1 != this.RIORORCRCCCHOHHOCHHHOCIIOCRORH || var2 != this.RIIOCOIOOHIIRHCCRCRRHRCHRROROC)
         && !IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$isGamePaused()) {
         this.RIORORCRCCCHOHHOCHHHOCIIOCRORH = var1;
         this.RIIOCOIOOHIIRHCCRCRRHRCHRROROC = var2;
         this.HHRIICOIOORCHCOIICOOIHIRHHICRI((var1 - 1) * 16, (var2 - 1) * 16);
         this.IHHIRRICHOHHCIRRCCHRHOIHHRCRHR.clear();
         this.CRRRICCRROCOHHOHIICIHORCOORRRH(this.OCOORORHRCRRIOICICCIHOIIOCHROI, this.OIOORHORRHCOCOHHOOCHIHRCICRCCI, true);
      }
   }

   private void HHRIICOIOORCHCOIICOOIHIRHHICRI(int var1, int var2) {
      this.ROIHCIIIRIORHORHIRRHROCCCORIOC = false;
      this.HHORHRICOICOHHOCRRIRHIORICOHII = var1;
      this.CCHRHOHCCRCRRHROOIHCIHRCRRIRHO = var2;
      if (this.HCHIHOIROHHIIRCIRORRRCORHOORCC != null) {
         this.HCHIHOIROHHIIRCIRORRRCORHOORCC.IRCCCOIIORORHIRCIROHHRCRROORRO();
      }

      this.HCHIHOIROHHIIRCIRORRRCORHOORCC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
         .bridge$getTextureManager()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.HICOROIHOHHIOCOIRIIIHRCIORHIII, new com.moonsworth.lunar.client.util.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI()
         );
      this.ROOOCCIOHHICHRHRHCIRORICRCRIOR = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHORRHCCCIROIRCIRIRCIORHRRRHRR()
         .CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1, var2)
         .IRCIIHHICIHRCOCRROCOICRIHHCCHH(this.HCHIHOIROHHIIRCIRORRRCORHOORCC)
         .HICRRICCHCCROOHHCHOCOCCHOIHHOC(true)
         .OHHHOIRORRRHROOROCHCIIICIRCROH();
      this.ROOOCCIOHHICHRHRHCIRORICRCRIOR.bridge$setClearColor(0.0F, 0.0F, 0.0F, 0.0F);
      this.ROIHCIIIRIORHORHIRRHROCCCORIOC = true;
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(double var1, double var3, BiConsumer<Float, Float> var5) {
      int var6 = this.HHORHRICOICOHHOCRRIRHIORICOHII / 2 + 16;
      int var7 = this.CCHRHOHCCRCRRHROOIHCIHRCRRIRHO / 2 + 16;
      float var8 = (float)(var1 - this.IRCIORRIRHIRCCRHHOOCCICOOCIROO);
      float var9 = (float)(var3 - this.OHRCCHROOOCCCRIIHOROIIIRRRRHHC);
      float var10 = (float)(var1 - this.HOOCOOOIHHROHHRIIIHCOICCHOHOHI);
      float var11 = (float)(var3 - this.OIOOICHIIHICCRCOOIOIOCIRRIIIRC);
      if (!(var10 < -var6) && !(var11 < -var7) && !(var10 > var6) && !(var11 > var7)) {
         var5.accept(var8, var9);
      }
   }

   public int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(@Nullable RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1, int var2, int var3, int var4) {
      if (var1 == null) {
         return var3;
      }

      long var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
         var2 >> 4, var4 >> 4
      );
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var7 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH)this.HRICCRCCRIIHIHOHIROCHHCOOIOHHI
         .getIfPresent(var5);
      if (var7 != null) {
         if (!var7.RCORROCRRCHROICOICHOIOOHRHRHCC()) {
            return var3;
         }

         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var8 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
         return var7.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var8 != null && var8.bridge$getDimensionId() == -1, var2, var4).CHROHOHIHHCHCCRIRHOHICRCHHHORO();
      } else {
         return var3;
      }
   }

   public double OOOROOHIIHOOHOOHOOCIIRHHCRIIOH() {
      return this.IRCIORRIRHIRCCRHHOOCCICOOCIROO - this.HOOCOOOIHHROHHRIIIHCOICCHOHOHI;
   }

   public double IICCRORROHORHRRCHIIORRHCHHROHH() {
      return this.OHRCCHROOOCCCRIIHOROIIIRRRRHHC - this.OIOOICHIIHICCRCOOIOIOCIRRIIIRC;
   }

   @Generated
   public int IICCHHIHRCOOHIIIRROCHICHIRORCI() {
      return this.RIORORCRCCCHOHHOCHHHOCIIOCRORH;
   }

   @Generated
   public int IOOOOCIHHRHRCOOHCHOIIOHORIRHCC() {
      return this.RIIOCOIOOHIIRHCCRCRRHRCHRROROC;
   }

   @Generated
   public int getTextureWidth() {
      return this.HHORHRICOICOHHOCRRIRHIORICOHII;
   }

   @Generated
   public int getTextureHeight() {
      return this.CCHRHOHCCRCRRHROOIHCIHRCRRIRHO;
   }

   @Generated
   public int RCOOHRCIIIROICHOICHOHCCHIHIOHI() {
      return this.OCOORORHRCRRIOICICCIHOIIOCHROI;
   }

   @Generated
   public int IIOCIOIRHCCCHOICCHHRHIIIHHHCOC() {
      return this.OIOORHORRHCOCOHHOOCHIHRCICRCCI;
   }

   @Generated
   public int HIRHHCRHCIRHROICHHIIICOICHHOCH() {
      return this.HOOCOOOIHHROHHRIIIHCOICCHOHOHI;
   }

   @Generated
   public int CCCIOCCRRCOIRORIRRICIIHRRCOICC() {
      return this.OIOOICHIIHICCRCOOIOIOCIRRIIIRC;
   }

   @Generated
   public LongSet ORIHOCIROOORCRHCROCIHIORRCHCRH() {
      return this.OHCRIHOORRHHRIORCOROIHOIORCROO;
   }

   @Generated
   public Cache<Long, com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH> OHCCOCHHROIHRHICIIOHHCHIOCIHRO() {
      return this.HRICCRCCRIIHIHOHIROCHHCOOIOHHI;
   }

   @Generated
   public Long2ObjectMap<LongSet> HIHROCICIIOCRORRCCHOHIIRCCOCCC() {
      return this.ICCOROICHHORIOIOICHHRIHHICHHHC;
   }

   @Generated
   public LongSet IIORHCRCRHRROORHIOOOHROIRIIIIC() {
      return this.OCHROOIOCIRCOOOIRORROCCIRRRCCR;
   }

   @Generated
   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HCHRIRRCIHCRCROCCCORHICHCICRHC() {
      return this.HRIROOROIICRRRICCHRIHHIORCRCOC;
   }
}
