package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCCCROCHCICCROHCOCCRRROCIIHCCH;

public class CRRRICCRROCOHHOHIICIHORCOORRRH {
   public static final int ROROCRHRHCHICIICORCRIRCHOIIRRR = 16;
   public static final int OOOOCRROOICORRHROOCHIIOCIICCRR = 4;
   public static final int RIIHCRRCIRICIHHHIROCRHCHCCCHHI = 32;
   public static final int HOOROIOIOICHCOHCIROOIHOHICIRHH = 5;
}
