package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR;

public class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends CRRRICCRROCOHHOHIICIHORCOORRRH {
   protected final CIOHHCORHRCCRICCCORIHCRHCCCRRR IOICIRROHRCCRRRRROROCRCOHHRRHH;

   public HHCCIRHCCCIIRHCROHIORHIRHHIORH(String var1) {
      this(CIOHHCORHRCCRICCCORIHCRHCCCRRR.RROOOHCORRIIHHCOOOCOCORRRRRHCO(var1));
   }

   public HHCCIRHCCCIIRHCROHIORHIRHHIORH(CIOHHCORHRCCRICCCORIHCRHCCCRRR var1) {
      this.IOICIRROHRCCRRRRROROCRCOHHRRHH = var1;
   }

   @Override
   public CRRRICCRROCOHHOHIICIHORCOORRRH HOIIRICIHIHCOCHIHHICIIOOOCICOO(int var1) {
      CIOHHCORHRCCRICCCORIHCRHCCCRRR var2 = this.IOICIRROHRCCRRRRROROCRCOHHRRHH.CCIRCRIOOIIICIIRIIIOOCOIHOORIC(var1);
      if (var2 == null) {
         return null;
      } else {
         return var2.matches() ? CRRRICCRROCOHHOHIICIHORCOORRRH.COCIRHCOOIHRCRHHHOHCCIOIIRRROO : new HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2);
      }
   }

   @Override
   public CRRRICCRROCOHHOHIICIHORCOORRRH CRICCIOICHOOOOCOHROROORIORHRHI(String var1) {
      CIOHHCORHRCCRICCCORIHCRHCCCRRR var2 = this.IOICIRROHRCCRRRRROROCRCOHHRRHH.ROIHICOCOIRORRORIHRIHRIOHRRHHC(var1);
      if (var2 == null) {
         return null;
      } else {
         return var2.matches() ? CRRRICCRROCOHHOHIICIHORCOORRRH.COCIRHCOOIHRCRHHHOHCCIOIIRRROO : new HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2);
      }
   }

   @Override
   public CRRRICCRROCOHHOHIICIHORCOORRRH RIIRIHCCIOIRHHIIHCCROIORIRHROO() {
      return this;
   }

   @Override
   public CRRRICCRROCOHHOHIICIHORCOORRRH RHIRHHORHCCOCHHRRRCROHCOHHCCHI() {
      return this;
   }

   @Override
   protected boolean RHOROHHOHCRRCHHHRIROORIIRCOOHR() {
      return this.IOICIRROHRCCRRRRROROCRCOHHRRHH.matches();
   }

   @Override
   public String toString() {
      return "[JsonPointerFilter at: " + this.IOICIRROHRCCRRRRROROCRCOHHRRHH + "]";
   }
}
