package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR;

import com.google.common.collect.Sets;
import com.lunarclient.generated.skyblockprofileresponse.profile.Member;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHRIICOIOORCHCOIICOOIHIRHHICRI;
import com.moonsworth.lunar.client.util.CIIHHCHIRCRRIHOIOCCCROHOIOCCII;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IIIIRHIHROIRCROHHROIHIIHRCRRHO;
import com.moonsworth.lunar.lib.adventure.text.Component;
import com.moonsworth.lunar.lib.adventure.text.format.TextColor;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.jetbrains.annotations.Nullable;

public class RIOOCHICIHRHOHCCCCCHOCCCOHCRHI extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private static final Pattern OHRIOOHOCROIORRCHHRCOCCCHCCHHI = Pattern.compile("^ §.\\[Lvl (?<level>\\d{1,3})] §(?<rarity>.)Dolphin.*$");
   private static final NumberFormat OHIICCHHCRCRIOHOIOOROIICIHCROH = NumberFormat.getIntegerInstance(Locale.ROOT);
   private static final int OROCHOOCOOCRCOCIICIOOCRIOIRHHO = 120000;
   private static final Set<String> HOCCCCIOIOHOHOIIOOOCHCCRCOICHI = Sets.newHashSet(new String[]{"GRAPPLING_HOOK", "SOUL_WHIP", "FLAMING_FLAY"});
   private static final RCIROOOOICRHCCRRCIORHHIRCOIIIC HCHOICOCRRIIICOHCOCCOCCCOIOHHC = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "lunar", "skyblock/hud/dolphin.png"
   );
   private static final RCIROOOOICRHCCRRCIORHHIRCOIIIC RHOCIOIHROHOIHCOHHIOOHOHRRCICI = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "mobs/squid.png");
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR HIORIRHRCHCOIHHIOOHIIIHICCCOOH = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR.class
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.OCOHORHCROHICRRIHCIHHRRCIHICRI IOHIRIIIICCROCHHOOHIRHCCRHCHIR = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.OCOHORHCROHICRRIHCIHHRRCIHICRI.class
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH IOICIHRHHHIIORCRHCOCRHCRCIOCHH = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.class
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH RROCHOCCHIHORIIIHOOOCCCCIOHCOR = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class
   );
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IRIHOOIORROHRCCRIRHICOHHIHIHIO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showIfRodInHotbar"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI RRHRCHIIIHCOOIOCCRCRROHIOCCHIO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showTitle"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI HHIOCOCCOOIHHIORCHCHRHOHIORRIR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showFishingTime"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IHIRCOCRHOHRCHIICIOCRRCHOIICOC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showSeaCreatures"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI COIRHHHOHCIRICORHRIOOHCIHIOOIC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showMilestone"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI CIHHCHROCOCHIIRHOIOHRHOCCCIROI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showSessionXp"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IICHICCHICHHCORROCRRRRHOORHIHI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showDolphinBoost"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI CHCIRIRCCOCCHCRORRCRIHRCROCRIR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showFishingProgress"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI CHHHIOROOCCOCIOCIHCIHOIHIOHORC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("titleColor")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-43521)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI CHOIHHRCRIHHICHIRHCCORRHHIICRI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "fishingTimeColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-11141121)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI ICOORRRHRCOHRHOHHROROCOIOHHRII = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "seaCreaturesColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-171)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI IOOIOCORCCOOORRCROCIIRIICOIOIR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("milestoneColor")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-43521)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI HICCICCCOCHCIICCOHOIIRHHHOHHRH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("sessionXpColor")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-11141291)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI HHOHRHCRHHCCOCCOORRIORIHOOOIRR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "dolphinBoostColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-16777046)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI HIIHCOCCHCCHHCRRORHHCIOROIHRCI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "fishingProgressColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-16733526)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private long RROIIROCOROCHRHIOCRRHCIRHROCCO;
   private boolean isActive;
   private long OHCHIRCRCOCIOOHHICHCCIHRIORHOO;
   private String RIRCHOIHHICCICOHHRROCIROROCHRO;
   private int OHORHHCRCCOIOCRORICOOOIOHHCRCR;
   private long OHCRIHCRHIORCOICHOHRCHCHCHOOOO;
   private double CHHROIIIHOCHRCOHOCCOCOCHCRIRCI;
   private String CCRHCCRCCCICIOOCOCRHHROCIHICII;
   private String RIHCHOIHHHCHHCIRHROIOHRHHCRCRH;
   private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH ICORCRRRCOOICRHHHIRRHCRICIRHCO;
   private int HRCOOCICHICCCCORICICRIHHIRCORI;

   public RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            new RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FISHING
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI::RRRCCHIOCICOIOIRRCOOIRHHCORCIH
         )
      );
      this.handle(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.class,
         this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      );
      this.handle(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.class,
         this::IRCIIHHICIHRCOCRROCOICRIHHCCHH
      );
      this.handle(HHRIICOIOORCHCOIICOOIHIRHHICRI.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, var1x -> {
         this.OCOHORHCROHICRRIHCIHHRRCIHICRI(var1x);
         this.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1x);
      });
      this.handle(RIROICHCRROROHCCROOCCCCOCHCCRI.class, this::RIOOCHICIHRHOHCCCCCHOCCCOHCRHI);
      this.handle(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.handle(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class,
         var1x -> this.OOROHCCRRIIICRIRORORCOCRCIORRH()
      );
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1
   ) {
      this.OHORHHCRCCOIOCRORICOOOIOHHCRCR = this.OHORHHCRCCOIOCRORICOOOIOHHCRCR + var1.getCount();
      this.OHCRIHCRHIORCOICHOHRCHCHCHOOOO = this.OHCRIHCRHIORCOICHOHRCHCHCHOOOO + var1.getCount();
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1
   ) {
      if (var1.HICCHRRICORHCHRRORRORROHORRRHR()
         == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.FISHING
         )
       {
         this.CHHROIIIHOCHRCOHOCCOCOCHCRIRCI = this.CHHROIIIHOCHRCOHOCCOCOCHCRIRCI + var1.OCOHCCIHCRRRRHORHCIRORCOIOIHRO();
         int var2 = this.HIORIRHRCHCOIHHIOOHIIIHICCCOOH
            .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.FISHING
            );
         String var3 = var1.IOHRCCOCOCHHHRRCIIOHOROHICCHOR() > 0L ? String.format("%.2f", var1.CHIRHOCIOROCRCHCIRORICOHCICIRR()) + "%" : "MAX";
         this.RIHCHOIHHHCHHCIRHROIOHRHHCRCRH = "Fishing " + var2 + ": " + var3;
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HHRIICOIOORCHCOIICOOIHIRHHICRI var1) {
      this.ICORCRRRCOOICRHHHIRRHCRICIRHCO = null;
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = this.IOHIRIIIICCROCHHOOHIRHCCRHCHIR
         .RICICCIOICOIRHOIIRORHCIOICIOHH()
         .get("pet");
      if (var2 != null) {
         for (Component var4 : var2.RCOOOHHIRHHOOIIOIOOCCHIOCRRHCC()) {
            String var5 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.asLegacyString(var4);
            Matcher var6 = OHRIOOHOCROIORRCHHRCOCCCHCCHHI.matcher(var5);
            if (var6.matches()) {
               this.ICORCRRRCOOICRHHHIRRHCRICIRHCO = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.fromCode(
                  var6.group("rarity").charAt(0)
               );
               this.HRCOOCICHICCCCORICICRIHHIRCORI = Integer.parseInt(var6.group("level"));
               return;
            }
         }
      }
   }

   private void OCOHORHCROHICRRIHCIHHRRCIHICRI(IOIICIRIICICIIOORHCIIIIRRIHRHI var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      if (var2 != null && var3 != null) {
         if (this.ICORCRRRCOOICRHHHIRRHCRICIRHCO != null) {
            double var4 = this.HRCOOCICHICCCCORICICRIHHIRCORI * switch (this.ICORCRRRCOOICRHHHIRRHCRICIRHCO) {
               case COMMON -> 0.03;
               case UNCOMMON -> 0.04;
               case RARE -> 0.04;
               case EPIC -> 0.05;
               case LEGENDARY -> 0.05;
               default -> 0.03;
            };

            double var6 = switch (this.ICORCRRRCOOICRHHHIRRHCRICIRHCO) {
               case COMMON -> 15.0;
               case UNCOMMON -> 20.0;
               case RARE -> 20.0;
               case EPIC -> 25.0;
               case LEGENDARY -> 25.0;
               default -> 15.0;
            };
            int var8 = 0;

            for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var10 : var2.bridge$getPlayerEntities()) {
               if (!var10.bridge$isSelf()
                  && !IIIIRHIHROIRCROHHROIHIIHRCRRHO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var10, true)
                  && var10.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3) <= 100.0) {
                  var8++;
               }
            }

            double var11 = com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.clamp(
               var4 * var8, 0.0, var6
            );
            this.CCRHCCRCCCICIOOCOCRHHROCIHICII = String.format("%.2f", var11) + "%";
         }
      }
   }

   private void CIOHHCORHRCCRICCCORIHCRHCCCRRR(IOIICIRIICICIIOORHCIIIIRRIHRHI var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = this.IOICIHRHHHIIORCRHCOCRHCRCIOCHH
         .IIHCHIICOHORHHICCRRROORCIOROHH();
      if (var2 != null && !var2.bridge$isRemoved()) {
         if (this.IOICIHRHHHIIORCRHCOCRHCRCIOCHH.IHIRIHOHCHIOHCROORHOIIIOIIIRHO()) {
            this.OHCHIRCRCOCIOOHHICHCCIHRIORHOO = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
            if (!this.isActive) {
               this.isActive = true;
               this.RROIIROCOROCHRHIOCRRHCIRHROCCO = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
               this.OHORHHCRCCOIOCRORICOOOIOHHCRCR = 0;
               this.CHHROIIIHOCHRCOHOCCOCOCHCRIRCI = 0.0;
            }
         }
      }
   }

   private void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(RIROICHCRROROHCCROOCCCCOCHCCRI var1) {
      if (this.isActive) {
         this.RIRCHOIHHICCICOHHRROCIROROCHRO = CIIHHCHIRCRRIHOIOCCCROHOIOCCII.IHRHHHORORIROOCORCIORRCOCHHHRI(
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() - this.RROIIROCOROCHRHIOCRRHCIRHROCCO
         );
         if (this.OHCHIRCRCOCIOOHHICHCCIHRIORHOO + 120000L < IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime()) {
            this.isActive = false;
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.isActive = false;
   }

   private boolean RHOORRIIOCHIRRHOHOOHIROHCRICRO(IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      if (var1 != null && !var1.bridge$isEmpty()) {
         if (var1.bridge$getItem()
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CIHHIHOORIIHCOORRRICHHCCRRRCHO()
               .CHHIOCRRHIICCIOOORRRHRRROIRHRR()) {
            return false;
         }

         String var2 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.CHHIICHRIIROIOHIHIIROICOCCROCI(
            var1
         );
         return !HOCCCCIOIOHOHOIIOOOCHCCRCOICHI.contains(var2);
      } else {
         return false;
      }
   }

   @Override
   public void COIHORRCHRRCHOCIRHHRRIOIHRIHCC(boolean var1) {
      if (var1) {
         this.OOROHCCRRIIICRIRORORCOCRCIORRH();
      }
   }

   private void OOROHCCRRIIICRIRORORCOCRCIORRH() {
      Member var1 = this.RROCHOCCHIHORIIIHOOOCCCCIOHCOR.COHORHIORRCRCRHRIIOICCCCRCHOHC();
      if (var1 != null) {
         Double var2 = var1.playerStats().pets().milestone().seaCreaturesKilled().orElse(null);
         if (var2 != null) {
            this.OHCRIHCRHIORCOICHOHRCHCHCHOOOO = var2.longValue();
         }
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HUD,
         var1x -> {
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IRIHOOIORROHRCCRIRHICOHHIHIHIO);
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RRHRCHIIIHCOOIOCCRCRROHIOCCHIO, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CHHHIOROOCCOCIOCIHCIHOIHIOHORC)
            );
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.HHIOCOCCOOIHHIORCHCHRHOHIORRIR, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CHOIHHRCRIHHICHIRHCCORRHHIICRI)
            );
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.IHIRCOCRHOHRCHIICIOCRRCHOIICOC, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.ICOORRRHRCOHRHOHHROROCOIOHHRII)
            );
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.COIRHHHOHCIRICORHRIOOHCIHIOOIC, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IOOIOCORCCOOORRCROCIIRIICOIOIR)
            );
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.CIHHCHROCOCHIIRHOIOHRHOCCCIROI, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HICCICCCOCHCIICCOHOIIRHHHOHHRH)
            );
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.IICHICCHICHHCORROCRRRRHOORHIHI, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HHOHRHCRHHCCOCCOORRIORIHOOOIRR)
            );
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.CHCIRIRCCOCCHCRORRCRIHRCROCRIR, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HIIHCOCCHCCHHCRRORHHCIOROIHRCI)
            );
         }
      );
   }

   @Override
   public String getId() {
      return "SKYBLOCK_FISHING_INFO_HUD";
   }

   private class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO<List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR>> {
      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
         super(
            0.0F,
            0.0F,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.TOP_CENTER,
            true,
            true
         );
      }

      @Override
      public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH HRRIHHICORIHCHICOHCCRCHCHOHRCH() {
         return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            15, 120, 200, 60, 180, 300
         );
      }

      @Nullable
      public List<OOROOCCIRCCRHOIOIORIHCHHOOCCOR> IROCHOHCORHCOCCCOCHORCICRORIIC(boolean var1) {
         if (var1) {
            return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(true, "12m 34s", 251, 5327L, 18425.0, true, "5.00%", "Fishing 32: 46.18%");
         }

         if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IRIHOOIORROHRCCRIRHICOHHIHIHIO.get()) {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
            if (var2 == null) {
               return null;
            }

            boolean var3 = var2.bridge$getInventory()
               .bridge$getMainInventory()
               .stream()
               .limit(9L)
               .anyMatch(var1x -> RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.RHOORRIIOCHIRRHOHOOHIROHCRICRO(var1x));
            if (!var3) {
               return null;
            }
         }

         return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.isActive,
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.RIRCHOIHHICCICOHHRROCIROROCHRO,
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.OHORHHCRCCOIOCRORICOOOIOHHCRCR,
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.OHCRIHCRHIORCOICHOHRCHCHCHOOOO,
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.CHHROIIIHOCHRCOHOCCOCOCHCRIRCI,
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.ICORCRRRCOOICRHHHIRRHCRICIRHCO != null,
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.CCRHCCRCCCICIOOCOCRHHROCIHICII,
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.RIHCHOIHHHCHHCIRHROIOHRHHCRCRH
         );
      }

      private List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         boolean var1, String var2, int var3, long var4, double var6, boolean var8, String var9, String var10
      ) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var11 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CIHHIHOORIIHCOORRRICHHCCRRRCHO();
         ArrayList var12 = new ArrayList();
         if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.RRHRCHIIIHCOOIOCCRCRROHIOCCHIO.get()) {
            var12.add(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  var11.CHHIOCRRHIICCIOOORRRHRRROIRHRR(),
                  Component.text(
                     RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("title")
                        + " ("
                        + RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1 ? "active" : "inactive")
                        + ")",
                     TextColor.color(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.CHHHIOROOCCOCIOCIHCIHOIHIOHORC.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F))
                  )
               )
            );
         }

         if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.HHIOCOCCOOIHHIORCHCHRHOHIORRIR.get()) {
            String var13 = var2 != null ? var2 : RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("startFishing");
            var12.add(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  var11.IRORICOCICICOIRIHOICHOROCHORIR(),
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("fishingTime"))
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH(var13)
                     .ROIIRHIRRRCRROCIIOICIIRICHCCHO(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.CHOIHHRCRIHHICHIRHCCORRHHIICRI.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F))
                     .ROCHIOHIOIOCIIHRORROHIHICOHOCC(this.HROICIRRHHHICCCORCOOHRRRHOROIO == null || this.HROICIRRHHHICCCORCOOHRRRHOROIO.get())
                     .build()
               )
            );
         }

         if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IHIRCOCRHOHRCHIICIOCRRCHOIICOC.get()) {
            var12.add(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHOCIOIHROHOIHCOHHIOOHOHRRCICI,
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("seaCreatures"))
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OHIICCHHCRCRIOHOIOOROIICIHCROH.format(var3))
                     .ROIIRHIRRRCRROCIIOICIIRICHCCHO(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.ICOORRRHRCOHRHOHHROROCOIOHHRII.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F))
                     .ROCHIOHIOIOCIIHRORROHIHICOHOCC(this.HROICIRRHHHICCCORCOOHRRRHOROIO == null || this.HROICIRRHHHICCCORCOOHRRRHOROIO.get())
                     .build()
               )
            );
         }

         if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.COIRHHHOHCIRICORHRIOOHCIHIOOIC.get()) {
            var12.add(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  var11.RIHRHORCOOCIICRRICHOOORCOHICRO(),
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("milestone"))
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OHIICCHHCRCRIOHOIOOROIICIHCROH.format(var4))
                     .ROIIRHIRRRCRROCIIOICIIRICHCCHO(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IOOIOCORCCOOORRCROCIIRIICOIOIR.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F))
                     .ROCHIOHIOIOCIIHRORROHIHICOHOCC(this.HROICIRRHHHICCCORCOOHRRRHOROIO == null || this.HROICIRRHHHICCCORCOOHRRRHOROIO.get())
                     .build()
               )
            );
         }

         if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.CIHHCHROCOCHIIRHOIOHRHOCCCIROI.get()) {
            var12.add(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  var11.ICRRIHOIRCIOIRRRCHCRORCIHHICRI(),
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("sessionXp"))
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OHIICCHHCRCRIOHOIOOROIICIHCROH.format(var6))
                     .ROIIRHIRRRCRROCIIOICIIRICHCCHO(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.HICCICCCOCHCIICCOHOIIRHHHOHHRH.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F))
                     .ROCHIOHIOIOCIIHRORROHIHICOHOCC(this.HROICIRRHHHICCCORCOOHRRRHOROIO == null || this.HROICIRRHHHICCCORCOOHRRRHOROIO.get())
                     .build()
               )
            );
         }

         if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IICHICCHICHHCORROCRRRRHOORHIHI.get() && var8) {
            var12.add(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HCHOICOCRRIIICOHCOCCOCCCOIOHHC,
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("dolphinBoost"))
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH(var9)
                     .ROIIRHIRRRCRROCIIOICIIRICHCCHO(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.HHOHRHCRHHCCOCCOORRIORIHOOOIRR.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F))
                     .ROCHIOHIOIOCIIHRORROHIHICOHOCC(this.HROICIRRHHHICCCORCOOHRRRHOROIO == null || this.HROICIRRHHHICCCORCOOHRRRHOROIO.get())
                     .build()
               )
            );
         }

         if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.CHCIRIRCCOCCHCRORRCRIHRCROCRIR.get() && var10 != null) {
            var12.add(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  var11.CHHIOCRRHIICCIOOORRRHRRROIRHRR(),
                  Component.text(
                     var10, TextColor.color(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.HIIHCOCCHCCHHCRRORHHCIOROIHRCI.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F))
                  )
               )
            );
         }

         return var12;
      }

      @Override
      protected boolean OOHOCHOCHHOCROOIRICCIHCCCRCCRC() {
         return true;
      }

      @Override
      protected com.moonsworth.lunar.client.IHCRORHRORIICHRHRCHRRIRRHHOCOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IIHHOIIRORCHCIHROROHOORCCCRCOH() {
         return com.moonsworth.lunar.client.IHCRORHRORIICHRHRCHRRIRRHHOCOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.LEFT;
      }
   }
}
