package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR;
import java.time.DateTimeException;
import java.time.OffsetTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

public class CRICCOOHHHCHOORCICOCOHIHOIRHOO extends HHCCIRHCCCIIRHCROHIORHIRHHIORH<OffsetTime> {
   private static final long ROHOCIOIRRHICOHIRIROCRCHHHHCOI = 1L;
   public static final CRICCOOHHHCHOORCICOCOHIHOIRHOO IICCHCROOHHHHOIHOCRHHHCOOCCRHC = new CRICCOOHHHCHOORCICOCOHIHOIRHOO();

   protected CRICCOOHHHCHOORCICOCOHIHOIRHOO() {
      this(DateTimeFormatter.ISO_OFFSET_TIME);
   }

   protected CRICCOOHHHCHOORCICOCOHIHOIRHOO(DateTimeFormatter var1) {
      super(OffsetTime.class, var1);
   }

   protected CRICCOOHHHCHOORCICOCOHIHOIRHOO(CRICCOOHHHCHOORCICOCOHIHOIRHOO var1, Boolean var2) {
      super(var1, var2);
   }

   protected CRICCOOHHHCHOORCICOCOHIHOIRHOO OCOHORHCROHICRRIHCIHHRRCIHICRI(DateTimeFormatter var1) {
      return new CRICCOOHHHCHOORCICOCOHIHOIRHOO(var1);
   }

   protected CRICCOOHHHCHOORCICOCOHIHOIRHOO OOHRIIOOHROIOHCIRIHRHRRICRRHOI(Boolean var1) {
      return new CRICCOOHHHCHOORCICOCOHIHOIRHOO(this, var1);
   }

   protected CRICCOOHHHCHOORCICOCOHIHOIRHOO CORCOCICIRIOHROHROIIOOHICCHCRR(CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1) {
      return this;
   }

   public OffsetTime HORHCHIIOCRROHOHRCORCCICCRCCHO(
      OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2
   ) {
      if (var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_STRING)) {
         return this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(var1, var2, var1.getText());
      }

      if (var1.OCHOCCOIOCOHOHOOIOHOCOHRRRCRCI()) {
         return this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(var1, var2, var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, this, this.handledType()));
      }

      if (!var1.CHIOIROOIOCOCCORRHCIOOORHCRHHR()) {
         if (var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_EMBEDDED_OBJECT)) {
            return (OffsetTime)var1.RRIHRHCOCCRROCCHIRHHHIIICHCRRR();
         }

         if (var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT)) {
            this.HIHCCHCCOCOHRICOICHRCOIHIIRIHO(var1, var2);
         }

         throw var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, this.handledType(), OHHRIOHROOIHOROCIRHCHORIHRRRRI.START_ARRAY, "Expected array or string.");
      } else {
         OHHRIOHROOIHOROCIRHCHORIHRRRRI var3 = var1.OHHCRICRRCCHOHIRIRIHOIRHIROOIC();
         if (var3 != OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT) {
            if (var3 == OHHRIOHROOIHOROCIRHCHORIHRRRRI.END_ARRAY) {
               return null;
            }

            if ((var3 == OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_STRING || var3 == OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_EMBEDDED_OBJECT)
               && var2.CRRRICCRROCOHHOHIICIHORCOORRRH(
                  com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.UNWRAP_SINGLE_VALUE_ARRAYS
               )) {
               OffsetTime var10 = this.HORHCHIIOCRROHOHRCORCCICCRCCHO(var1, var2);
               if (var1.OHHCRICRRCCHOHIRIRIHOIRHIROOIC() != OHHRIOHROOIHOROCIRHCHORIHRRRRI.END_ARRAY) {
                  this.handleMissingEndArrayForSingle(var1, var2);
               }

               return var10;
            }

            var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.handledType(), "Unexpected token (%s) within Array, expected VALUE_NUMBER_INT", new Object[]{var3});
         }

         int var4 = var1.HHHRCIIIIHOCHICIORORCCOCHOIHIO();
         int var5 = var1.CCIHIRRIHCOICHHHIHCHHHHCHRIICR(-1);
         if (var5 == -1) {
            var3 = var1.RCICCOICCHHORCCIROCIIRHHIIICOH();
            if (var3 == OHHRIOHROOIHOROCIRHCHORIHRRRRI.END_ARRAY) {
               return null;
            }

            if (var3 != OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT) {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT, "minutes");
            }

            var5 = var1.HHHRCIIIIHOCHICIORORCCOCHOIHIO();
         }

         int var6 = 0;
         int var7 = 0;
         if (var1.OHHCRICRRCCHOHIRIRIHOIRHIROOIC() == OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT) {
            var7 = var1.HHHRCIIIIHOCHICIORORCCOCHOIHIO();
            if (var1.OHHCRICRRCCHOHIRIRIHOIRHIROOIC() == OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT) {
               var6 = var1.HHHRCIIIIHOCHICIORORCCOCHOIHIO();
               if (var6 < 1000
                  && !var2.CRRRICCRROCOHHOHIICIHORCOORRRH(
                     com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.READ_DATE_TIMESTAMPS_AS_NANOSECONDS
                  )) {
                  var6 *= 1000000;
               }

               var1.OHHCRICRRCCHOHIRIRIHOIRHIROOIC();
            }
         }

         if (var1.RCICCOICCHHORCCIROCIIRHHIIICOH() == OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_STRING) {
            OffsetTime var8 = OffsetTime.of(var4, var5, var7, var6, ZoneOffset.of(var1.getText()));
            if (var1.OHHCRICRRCCHOHIRIRIHOIRHIROOIC() != OHHRIOHROOIHOROCIRHCHORIHRRRRI.END_ARRAY) {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, OHHRIOHROOIHOROCIRHCHORIHRRRRI.END_ARRAY, "timezone");
            }

            return var8;
         } else {
            throw var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1, this.handledType(), OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_STRING, "Expected string for TimeZone after numeric values"
            );
         }
      }
   }

   protected OffsetTime CRICCOOHHHCHOORCICOCOHIHOIRHOO(
      OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2,
      String var3
   ) {
      String var4 = var3.trim();
      if (var4.length() == 0) {
         return this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, var2, var4);
      }

      try {
         return OffsetTime.parse(var4, this.RORIIOOOOHCRRIHIRICCRIHHROHRRI);
      } catch (DateTimeException var6) {
         return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var6, var4);
      }
   }
}
