package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR;
import java.time.DateTimeException;
import java.time.Year;
import java.time.format.DateTimeFormatter;

public class HICHRCOHCCRHOHCICOOCHOIHCCHIRI extends HHCCIRHCCCIIRHCROHIORHIRHHIORH<Year> {
   private static final long HHCRRHCCICCORCRHRRIOORCIHOOCRC = 1L;
   public static final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HCIHCRRHOIOCHIRCOCOIOICRRORORO = new HICHRCOHCCRHOHCICOOCHOIHCCHIRI();

   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI() {
      this(null);
   }

   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI(DateTimeFormatter var1) {
      super(Year.class, var1);
   }

   protected HICHRCOHCCRHOHCICOOCHOIHCCHIRI(HICHRCOHCCRHOHCICOOCHOIHCCHIRI var1, Boolean var2) {
      super(var1, var2);
   }

   protected HICHRCOHCCRHOHCICOOCHOIHCCHIRI CIOHHCORHRCCRICCCORIHCRHCCCRRR(DateTimeFormatter var1) {
      return new HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1);
   }

   protected HICHRCOHCCRHOHCICOOCHOIHCCHIRI RHHIOCHRCICCHOHCIHOOHOIHCCHRCO(Boolean var1) {
      return new HICHRCOHCCRHOHCICOOCHOIHCCHIRI(this, var1);
   }

   protected HICHRCOHCCRHOHCICOOCHOIHCCHIRI CRICCOOHHHCHOORCICOCOHIHOIRHOO(CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1) {
      return this;
   }

   public Year CIHCOICOOICHOCCHICIHRCOCIHRIOC(
      OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2
   ) {
      OHHRIOHROOIHOROCIRHCHORIHRRRRI var3 = var1.COCHOCOHRICCHIIIHIOORCIIRROOHI();
      if (var3 == OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_STRING) {
         return this.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1, var2, var1.getText());
      } else if (var3 == OHHRIOHROOIHOROCIRHCHORIHRRRRI.START_OBJECT) {
         return this.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1, var2, var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, this, this.handledType()));
      } else if (var3 == OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT) {
         return this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var1.HHHRCIIIIHOCHICIORORCCOCHOIHIO());
      } else if (var3 == OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_EMBEDDED_OBJECT) {
         return (Year)var1.RRIHRHCOCCRROCCHIRHHHIIICHCRRR();
      } else {
         return var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(OHHRIOHROOIHOROCIRHCHORIHRRRRI.START_ARRAY)
            ? this._deserializeFromArray(var1, var2)
            : this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var1, OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_STRING, OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT);
      }
   }

   protected Year HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
      OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2,
      String var3
   ) {
      String var4 = var3.trim();
      if (var4.length() == 0) {
         return this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, var2, var4);
      }

      if (var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IHIRRIIORRHORHRORIHOROIRCORCOO.UNTYPED_SCALARS) && this.RIROOHCHCHIHCOHOICHOCRHCHHOIIC(var4)) {
         return this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            var2,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IIHRRHORCRCROCHHOHORCHCROCIHRO.parseInt(
               var4
            )
         );
      }

      try {
         return this.RORIIOOOOHCRRIHIRICCRIHHROHRRI == null ? Year.parse(var4) : Year.parse(var4, this.RORIIOOOOHCRRIHIRICCRIHHROHRRI);
      } catch (DateTimeException var6) {
         return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var6, var4);
      }
   }

   protected Year IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1, int var2
   ) {
      return Year.of(var2);
   }
}
