package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import java.io.ByteArrayInputStream;
import java.io.InputStream;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   protected final InputStream RRORCIRORCIOOHOOOCORRCHICIORRH;
   protected final byte[] HRRIOCORROHORHRCRHRHIRHCCCRHII;
   protected final int CIHROHHHRRROOHRCIIRCOOCICROHCC;
   protected final int OOHRHOICRHICROHIOIHIRICHHIRIOC;
   protected final HRCHROOHRIHCRCRHRIIROCIRHOIRHH COCHCHRCRICCHRRORHOIRIORIIIHRR;
   protected final CRRRICCRROCOHHOHIICIHORCOORRRH HIRHOCCCHOORRICORRIHRICIIRROHH;

   protected IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      InputStream var1, byte[] var2, int var3, int var4, HRCHROOHRIHCRCRHRIIROCIRHOIRHH var5, CRRRICCRROCOHHOHIICIHORCOORRRH var6
   ) {
      this.RRORCIRORCIOOHOOOCORRCHICIORRH = var1;
      this.HRRIOCORROHORHRCRHRHIRHCCCRHII = var2;
      this.CIHROHHHRRROOHRCIIRCOOCICROHCC = var3;
      this.OOHRHOICRHICROHIOIHIRICHHIRIOC = var4;
      this.COCHCHRCRICCHRRORHOIRIORIIIHRR = var5;
      this.HIRHOCCCHOORRICORRIHRICIIRROHH = var6;
      if ((var3 | var4) < 0 || var3 + var4 > var2.length) {
         throw new IllegalArgumentException(String.format("Illegal start/length (%d/%d) wrt input array of %d bytes", var3, var4, var2.length));
      }
   }

   public boolean CIHHOIICHOIRRCIICCORORHIIRHHOO() {
      return this.COCHCHRCRICCHRRORHOIRIORIIIHRR != null;
   }

   public CRRRICCRROCOHHOHIICIHORCOORRRH CORHRRRCIICROORCCCCHCOCIOORRRI() {
      return this.HIRHOCCCHOORRICORRIHRICIIRROHH == null ? CRRRICCRROCOHHOHIICIHORCOORRRH.INCONCLUSIVE : this.HIRHOCCCHOORRICORRIHRICIIRROHH;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH OCHRHIIRCOIRHCIROCIIRRHRORHCHC() {
      return this.COCHCHRCRICCHRRORHOIRIORIIIHRR;
   }

   public String OORORCIOCCHICOIIIOIIHORRRRHOHO() {
      return this.CIHHOIICHOIRRCIICCORORHIIRHHOO() ? this.OCHRHIIRCOIRHCIROCIIRRHRORHCHC().CIIOHHIHHRRRHOCIRHHOOIHHCCOCRO() : null;
   }

   public OCOHORHCROHICRRIHCIHHRRCIHICRI COOCOCIOIOIIRORICHIHRIHRHCOIRC() {
      if (this.COCHCHRCRICCHRRORHOIRIORIIIHRR == null) {
         return null;
      } else {
         return this.RRORCIRORCIOOHOOOCORRCHICIORRH == null
            ? this.COCHCHRCRICCHRRORHOIRIORIIIHRR
               .OIHCOHRCICCCRHRCROOCIOIRRHHHIH(this.HRRIOCORROHORHRCRHRHIRHCCCRHII, this.CIHROHHHRRROOHRCIIRCOOCICROHCC, this.OOHRHOICRHICROHIOIHIRICHHIRIOC)
            : this.COCHCHRCRICCHRRORHOIRIORIIIHRR.IIOIROIHIHHCCRICRCOOCHIICHRCOI(this.RIRCHHIRIHIHHIIROORRRIICHIRRIH());
      }
   }

   public InputStream RIRCHHIRIHIHHIIROORRRIICHIRRIH() {
      return this.RRORCIRORCIOOHOOOCORRCHICIORRH == null
         ? new ByteArrayInputStream(this.HRRIOCORROHORHRCRHRHIRHCCCRHII, this.CIHROHHHRRROOHRCIIRCOOCICROHCC, this.OOHRHOICRHICROHIOIHIRICHHIRIOC)
         : new HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
            null,
            this.RRORCIRORCIOOHOOOCORRCHICIORRH,
            this.HRRIOCORROHORHRCRHRHIRHCCCRHII,
            this.CIHROHHHRRROOHRCIIRCOOCICROHCC,
            this.OOHRHOICRHICROHIOIHIRICHHIRIOC
         );
   }
}
