package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;

import com.google.errorprone.annotations.CanIgnoreReturnValue;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
@CanIgnoreReturnValue
public interface IIRHCHHOICHRICOOCRORCCIOOIHOIR extends ICICIOCHHHIHOCHCOHORIHRCOHHOCR {
   IIRHCHHOICHRICOOCRORCCIOOIHOIR HRCHROOHRIHCRCRHRIIROCIRHOIRHH(byte var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR HCHRIROHHHCORIOCROOCHRCIOROOCI(byte[] var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR IHCRORHRORIICHRHRCHRRIRRHHOCOO(byte[] var1, int var2, int var3);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR CIOHHCORHRCCRICCCORIHCRHCCCRRR(ByteBuffer var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR CRRRICCRROCOHHOHIICIHORCOORRRH(short var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR IRCIRRIICRHCRHOCCRCRRCRORIHHHO(int var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR CIROHHHIOIHIROHCHICORCCCRROHCC(long var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR CHRHCRCCIICRORCOHCORHRROIHRCHO(float var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR IHRHHHORORIROOCORCIORRCOCHHHRI(double var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR RCIRHRRIOOCIOCCHHIOHCHHIROICRH(boolean var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR HICRRICCHCCROOHHCHOCOCCHOIHHOC(char var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(CharSequence var1);

   IIRHCHHOICHRICOOCRORCCIOOIHOIR RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CharSequence var1, Charset var2);

   <T> IIRHCHHOICHRICOOCRORCCIOOIHOIR RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(T var1, IIHRRHORCRCROCHHOHORCHCROCIHRO<? super T> var2);

   CIOHHCORHRCCRICCCORIHCRHCCCRRR CIRIIOORHHIHICORIOIIRIIHHCOCCI();

   @Deprecated
   @Override
   int hashCode();
}
