package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;

import com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.ICOHIIIRCIORCORHRRROOOOCOOROIC;
import com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IOCCCRIHOCHRCHRHCRHROIRIRHHHIR;
import java.util.Collections;
import java.util.Map;
import java.util.Set;

final class HICHRCOHCCRHOHCICOOCHOIHCCHIRI<N, E> extends IRCIIHHICIHRCOCRROCOICRIHHCCHH<N, E> {
   protected HICHRCOHCCRHOHCICOOCHOIHCCHIRI(Map<E, N> var1, Map<E, N> var2, int var3) {
      super(var1, var2, var3);
   }

   static <N, E> HICHRCOHCCRHOHCICOOCHOIHCCHIRI<N, E> RHHHHROCRIORIOCRRIRRROHICRRHOI() {
      return new HICHRCOHCCRHOHCICOOCHOIHCCHIRI<>(
         IOCCCRIHOCHRCHRHCRHROIRIRHHHIR.RIOHCCCCIRIROIHCHIIRCCHOHHIOHR(2), IOCCCRIHOCHRCHRHCRHROIRIRHHHIR.RIOHCCCCIRIROIHCHIIRCCHOHHIOHR(2), 0
      );
   }

   static <N, E> HICHRCOHCCRHOHCICOOCHOIHCCHIRI<N, E> IRCIIHHICIHRCOCRROCOICRIHHCCHH(Map<E, N> var0, Map<E, N> var1, int var2) {
      return new HICHRCOHCCRHOHCICOOCHOIHCCHIRI<>(
         ICOHIIIRCIORCORHRRROOOOCOOROIC.CRHROHHHCIHHCOHCOORCRIHHIICROR(var0), ICOHIIIRCIORCORHRRROOOOCOOROIC.CRHROHHHCIHHCOHCOORCRIHHIICROR(var1), var2
      );
   }

   @Override
   public Set<N> predecessors() {
      return Collections.unmodifiableSet(
         ((com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IHIRRIIORRHORHRORIHOROIRCORCOO)this.COHCCICHIOHOHCIICCCOHOHOCOIORI)
            .values()
      );
   }

   @Override
   public Set<N> successors() {
      return Collections.unmodifiableSet(
         ((com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IHIRRIIORRHORHRORIHOROIRCORCOO)this.CCCRIHCHRHCOHROOICCRIOHIOIHCCH)
            .values()
      );
   }

   @Override
   public Set<E> edgesConnecting(N var1) {
      return new IIHRRHORCRCROCHHOHORCHCROCIHRO<>(
         ((com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IHIRRIIORRHORHRORIHOROIRCORCOO)this.CCCRIHCHRHCOHROOICCRIOHIOIHCCH)
            .HOCCROIICHRHHCOCIICIROCCIHRCOR(),
         var1
      );
   }
}
