package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;

import com.google.errorprone.annotations.Immutable;
import com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IOIHHIORCICCHIIHOIOIOHHRICRHIO;
import com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.ROCHRRCORRCOOOOOCOICOCROIIHIHH;
import java.util.Comparator;
import java.util.Map;
import org.checkerframework.checker.nullness.qual.Nullable;

@Immutable
@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
public final class OCOHORHCROHICRRIHCIHHRRCIHICRI<T> {
   private final OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CIHCIOCROOHOHCHHHCOCRRCCRHROII;
   private final @Nullable Comparator<T> OCICIHHOIRRCICCHICIOCROHHIOIHI;

   private OCOHORHCROHICRRIHCIHHRRCIHICRI(OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1, @Nullable Comparator<T> var2) {
      this.CIHCIOCROOHOHCHHHCOCRRCCRHROII = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      this.OCICIHHOIRRCICCHICIOCROHHIOIHI = var2;
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkState(
         var1 == OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SORTED == (var2 != null)
      );
   }

   public static <S> OCOHORHCROHICRRIHCIHHRRCIHICRI<S> IHIIIRCHRRCIRIHRCHCIOCHRCRIOOO() {
      return new OCOHORHCROHICRRIHCIHHRRCIHICRI(OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.UNORDERED, null);
   }

   public static <S> OCOHORHCROHICRRIHCIHHRRCIHICRI<S> OCROOOCROCHIRIIOHOIOORHRCOICIH() {
      return new OCOHORHCROHICRRIHCIHHRRCIHICRI(OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.STABLE, null);
   }

   public static <S> OCOHORHCROHICRRIHCIHHRRCIHICRI<S> HRHHCROIIHCROIRHHCHCCROHIIRORH() {
      return new OCOHORHCROHICRRIHCIHHRRCIHICRI(OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.INSERTION, null);
   }

   public static <S extends Comparable<? super S>> OCOHORHCROHICRRIHCIHHRRCIHICRI<S> OIRRHROOOHIIRRCHHROHRCHICHHRRI() {
      return new OCOHORHCROHICRRIHCIHHRRCIHICRI<>(
         OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SORTED, IOIHHIORCICCHIIHOIOIOHHRICRHIO.OHOOIHRHCOIOIRHICHOOROHHIHOCRC()
      );
   }

   public static <S> OCOHORHCROHICRRIHCIHHRRCIHICRI<S> ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(Comparator<S> var0) {
      return new OCOHORHCROHICRRIHCIHHRRCIHICRI(
         OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SORTED,
         com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
            var0
         )
      );
   }

   public OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IROIICIHOCCHCRIRHRORRIIIHHRCCC() {
      return this.CIHCIOCROOHOHCHHHCOCRRCCRHROII;
   }

   public Comparator<T> comparator() {
      if (this.OCICIHHOIRRCICCHICIOCROHHIOIHI != null) {
         return this.OCICIHHOIRRCICCHICIOCROHHIOIHI;
      } else {
         throw new UnsupportedOperationException("This ordering does not define a comparator.");
      }
   }

   @Override
   public boolean equals(@Nullable Object var1) {
      if (var1 == this) {
         return true;
      }

      if (!(var1 instanceof OCOHORHCROHICRRIHCIHHRRCIHICRI)) {
         return false;
      }

      OCOHORHCROHICRRIHCIHHRRCIHICRI var2 = (OCOHORHCROHICRRIHCIHHRRCIHICRI)var1;
      return this.CIHCIOCROOHOHCHHHCOCRRCCRHROII == var2.CIHCIOCROOHOHCHHHCOCRRCCRHROII
         && com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHRIICOIOORCHCOIICOOIHIRHHICRI.equal(
            this.OCICIHHOIRRCICCHICIOCROHHIOIHI, var2.OCICIHHOIRRCICCHICIOCROHHIOIHI
         );
   }

   @Override
   public int hashCode() {
      return com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHRIICOIOORCHCOIICOOIHIRHHICRI.hashCode(
         this.CIHCIOCROOHOHCHHHCOCRRCCRHROII, this.OCICIHHOIRRCICCHICIOCROHHIOIHI
      );
   }

   @Override
   public String toString() {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IOIICIRIICICIIOORHCIIIIRRIHRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IOIICIRIICICIIOORHCIIIIRRIHRHI.COIOORHCRHCRCOROOHCHIRRIIOIOHR(
            this
         )
         .RHOCHHIRRCHHHOHOIRROIROHHHIHIO("type", this.CIHCIOCROOHOHCHHHCOCRRCCRHROII);
      if (this.OCICIHHOIRRCICCHICIOCROHHIOIHI != null) {
         var1.RHOCHHIRRCHHHOHOIRROIROHHHIHIO("comparator", this.OCICIHHOIRRCICCHICIOCROHHIOIHI);
      }

      return var1.toString();
   }

   <K extends T, V> Map<K, V> createMap(int var1) {
      switch (this.CIHCIOCROOHOHCHHHCOCRRCCRHROII) {
         case UNORDERED:
            return ROCHRRCORRCOOOOOCOICOCROIIHIHH.newHashMapWithExpectedSize(var1);
         case INSERTION:
         case STABLE:
            return ROCHRRCORRCOOOOOCOICOCROIIHIHH.newLinkedHashMapWithExpectedSize(var1);
         case SORTED:
            return ROCHRRCORRCOOOOOCOICOCROIIHIHH.newTreeMap(this.comparator());
         default:
            throw new AssertionError();
      }
   }

   <T1 extends T> OCOHORHCROHICRRIHCIHHRRCIHICRI<T1> OIRCOOCOIRIIHRCRRIOHIOROIHHHRR() {
      return this;
   }

   public enum RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      UNORDERED,
      STABLE,
      INSERTION,
      SORTED;
   }
}
