package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import java.util.Objects;
import java.util.Optional;

@com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
public class IIHRRHORCRCROCHHOHORCHCROCIHRO
   extends ROOCOCCCIRHHHIRIOIHHHHRHIICHHR<Object>
   implements com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR {
   private static final long HRCOICCHRIRORRCIIRHHHIRCOOHIRC = 1L;
   protected Object[] IOCOHHCIOIOCCRIHHHRRHIHRIICCCR;
   private final Enum<?> RRIHRRRRHOCRROIOCIRIIIHRCOOHRH;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CORCOCICIRIOHROHROIIOOHICCHCRR ICCIICIOCCCORROIRHRHHIRICCHIII;
   protected volatile com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CORCOCICIRIOHROHROIIOOHICCHCRR CCIRRRROOIRCOIHHRHOCHRRCCIRHIC;
   protected final Boolean HRRHHOHICOCRIHHCRIOIIHRCIHHHII;
   private Boolean CCCHOOROOIIHHRHCRHROOCHHOCCCIC;
   private Boolean COROHORIOHRRHOCIROCCHHORCOCIHR;
   protected final boolean IRRORROOIHRRRRHRHOICCOCOIOHRCO;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CORCOCICIRIOHROHROIIOOHICCHCRR ROHIRRCCOOORRHHOCIOHCCRHRHCRIR;

   public IIHRRHORCRCROCHHOHORCHCROCIHRO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var1,
      Boolean var2
   ) {
      this(var1, var2, null);
   }

   public IIHRRHORCRCROCHHOHORCHCROCIHRO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var1,
      boolean var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var3
   ) {
      super(var1.IRRCRHOROHRORORIHOOCRRRHCROHOH());
      this.ICCIICIOCCCORROIRHRHHIRICCHIII = var1.HCOOOOCRIORIICCCHIRIHCIIRIOHOI();
      this.IOCOHHCIOIOCCRIHHHRRHIHRIICCCR = var1.OHIHCHCIHRHIHRORCRICHOCHIRHOOR();
      this.RRIHRRRRHOCRROIOCIRIIIHRCOOHRH = var1.RORRICHOOOHOORIHHRICIRHIICIRHC();
      this.HRRHHOHICOCRIHHCRIOIIHRCIHHHII = var2;
      this.IRRORROOIHRRRRHRHOICCOCOIOHRCO = var1.ROHROHHOROOHRIHHOOHORRCRCCRCII();
      this.ROHIRRCCOOORRHHOCIOHCCRHRHCRIR = var3 == null ? null : var3.HCOOOOCRIORIICCCHIRIHCIIRIOHOI();
   }

   protected IIHRRHORCRCROCHHOHORCHCROCIHRO(IIHRRHORCRCROCHHOHORCHCROCIHRO var1, Boolean var2, Boolean var3, Boolean var4) {
      super(var1);
      this.ICCIICIOCCCORROIRHRHHIRICCHIII = var1.ICCIICIOCCCORROIRHRHHIRICCHIII;
      this.IOCOHHCIOIOCCRIHHHRRHIHRIICCCR = var1.IOCOHHCIOIOCCRIHHHRRHIHRIICCCR;
      this.RRIHRRRRHOCRROIOCIRIIIHRCOOHRH = var1.RRIHRRRRHOCRROIOCIRIIIHRCOOHRH;
      this.HRRHHOHICOCRIHHCRIOIIHRCIHHHII = var2;
      this.IRRORROOIHRRRRHRHOICCOCOIOHRCO = var1.IRRORROOIHRRRRHRHOICCOCOIOHRCO;
      this.CCCHOOROOIIHHRHCRHROOCHHOCCCIC = var3;
      this.COROHORIOHRRHOCIROCCHHORCOCIHR = var4;
      this.ROHIRRCCOOORRHHOCIOHCCRHRHCRIR = var1.ROHIRRCCOOORRHHOCIOHCCRHRHCRIR;
   }

   @Deprecated
   protected IIHRRHORCRCROCHHOHORCHCROCIHRO(IIHRRHORCRCROCHHOHORCHCROCIHRO var1, Boolean var2) {
      this(var1, var2, null, null);
   }

   @Deprecated
   public IIHRRHORCRCROCHHOHORCHCROCIHRO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var1
   ) {
      this(var1, null);
   }

   @Deprecated
   public static com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var0,
      Class<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2
   ) {
      return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, var2, null, null);
   }

   public static com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var0,
      Class<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHRIICOIOORCHCOIICOOIHIRHHICRI var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIROICHCRROROHCCROOCCCCOCHCCRI[] var4
   ) {
      if (var0.RCRHHOOOIHIOOIROCIRCRRIOOHHROR()) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2.getMember(),
            var0.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.OVERRIDE_PUBLIC_ACCESS_MODIFIERS
            )
         );
      }

      return new IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1, var2, var2.RCICCRIHIORCCCRCCORIROCOIIORHC(0), var3, var4);
   }

   public static com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<?> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var0,
      Class<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2
   ) {
      if (var0.RCRHHOOOIHIOOIROCIRCRRIOOHHROR()) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2.getMember(),
            var0.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.OVERRIDE_PUBLIC_ACCESS_MODIFIERS
            )
         );
      }

      return new IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1, var2);
   }

   public IIHRRHORCRCROCHHOHORCHCROCIHRO RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Boolean var1, Boolean var2, Boolean var3) {
      return Objects.equals(this.HRRHHOHICOCRIHHCRIOIIHRCIHHHII, var1)
            && Objects.equals(this.CCCHOOROOIIHHRHCRHROOCHHOCCCIC, var2)
            && Objects.equals(this.COROHORIOHRRHOCIROCCHHORCOCIHR, var3)
         ? this
         : new IIHRRHORCRCROCHHOHORCHCROCIHRO(this, var1, var2, var3);
   }

   @Deprecated
   public IIHRRHORCRCROCHHOHORCHCROCIHRO OCRCHRHOCCHCHRCORHIHRRRRHCHHCH(Boolean var1) {
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, this.CCCHOOROOIIHHRHCRHROOCHHOCCCIC, this.COROHORIOHRRHOCIROCCHHORCOCIHR);
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<?> createContextual(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      Boolean var3 = Optional.ofNullable(
            this.findFormatFeature(
               var1,
               var2,
               this.handledType(),
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ACCEPT_CASE_INSENSITIVE_PROPERTIES
            )
         )
         .orElse(this.HRRHHOHICOCRIHHCRIOIIHRCIHHHII);
      Boolean var4 = Optional.ofNullable(
            this.findFormatFeature(
               var1,
               var2,
               this.handledType(),
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE
            )
         )
         .orElse(this.CCCHOOROOIIHHRHCRHROOCHHOCCCIC);
      Boolean var5 = Optional.ofNullable(
            this.findFormatFeature(
               var1,
               var2,
               this.handledType(),
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.READ_UNKNOWN_ENUM_VALUES_AS_NULL
            )
         )
         .orElse(this.COROHORIOHRRHOCIROCCHHORCOCIHR);
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var4, var5);
   }

   @Override
   public boolean isCachable() {
      return true;
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH logicalType() {
      return com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.Enum;
   }

   @Override
   public Object getEmptyValue(com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1) {
      return this.RRIHRRRRHOCRROIOCIRIIIHRCOOHRH;
   }

   @Override
   public Object deserialize(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2
   ) {
      if (var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_STRING
      )) {
         return this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var1.getText());
      } else if (var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT
      )) {
         return this.IRRORROOIHRRRRHRHOICCOCOIOHRCO
            ? this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var1.getText())
            : this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var1.HHHRCIIIIHOCHICIORORCCOCHOIHIO());
      } else {
         return var1.OCHOCCOIOCOHOHOOIOHOCOHRRRCRCI()
            ? this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, this, this._valueClass))
            : this.IIOIROIHIHHCCRICRCOOCHIICHRCOI(var1, var2);
      }
   }

   protected Object IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2,
      String var3
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CORCOCICIRIOHROHROIIOOHICCHCRR var4 = this.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
         var2
      );
      Object var5 = var4.HIOCCRHOROOHCHHHICHOCRCIHHOHOR(var3);
      if (var5 == null) {
         String var6 = var3.trim();
         if (var6 == var3 || (var5 = var4.HIOCCRHOROOHCHHHICHOCRCIHHOHOR(var6)) == null) {
            return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var4, var6);
         }
      }

      return var5;
   }

   private com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CORCOCICIRIOHROHROIIOOHICCHCRR HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1
   ) {
      if (this.ROHIRRCCOOORRHHOCIOHCCRHRHCRIR != null) {
         return this.ROHIRRCCOOORRHHOCIOHCCRHRHCRIR;
      } else {
         return var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.READ_ENUMS_USING_TO_STRING
            )
            ? this.IIHRRHORCRCROCHHOHORCHCROCIHRO(var1)
            : this.ICCIICIOCCCORROIRHRHHIRICCHIII;
      }
   }

   protected Object RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2,
      int var3
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.logicalType(),
         this.handledType(),
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.Integer
      );
      if (var4
         == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.Fail
         )
       {
         if (var2.CRRRICCRROCOHHOHIICIHORCOORRRH(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.FAIL_ON_NUMBERS_FOR_ENUMS
         )) {
            return var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.HCCIHCIHHOICHCRCOOCCOIHCHIRROH(),
               var3,
               "not allowed to deserialize Enum value out of number: disable DeserializationConfig.DeserializationFeature.FAIL_ON_NUMBERS_FOR_ENUMS to allow"
            );
         }

         this._checkCoercionFail(var2, var4, this.handledType(), var3, "Integer value (" + var3 + ")");
      }

      switch (var4) {
         case AsNull:
            return null;
         case AsEmpty:
            return this.getEmptyValue(var2);
         case TryConvert:
         default:
            if (var3 >= 0 && var3 < this.IOCOHHCIOIOCCRIHHHRRHIHRIICCCR.length) {
               return this.IOCOHHCIOIOCCRIHHHRRHIHRIICCCR[var3];
            } else if (this.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var2)) {
               return this.RRIHRRRRHOCRROIOCIRIIIHRCOOHRH;
            } else {
               return !this.OCOHORHCROHICRRIHCIHHRRCIHICRI(var2)
                  ? var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     this.HCCIHCIHHOICHCRCOOCCOIHCHIRROH(),
                     var3,
                     "index value outside legal index range [0..%s]",
                     this.IOCOHHCIOIOCCRIHHHRRHIHRIICCCR.length - 1
                  )
                  : null;
            }
      }
   }

   private final Object RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CORCOCICIRIOHROHROIIOOHICCHCRR var3,
      String var4
   ) {
      String var5 = var4.trim();
      if (var5.isEmpty()) {
         if (this.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var2)) {
            return this.RRIHRRRRHOCRROIOCIRIIIHRCOOHRH;
         }

         if (this.OCOHORHCROHICRRIHCIHHRRCIHICRI(var2)) {
            return null;
         }

         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var11;
         if (var4.isEmpty()) {
            var11 = this._findCoercionFromEmptyString(var2);
            var11 = this._checkCoercionFail(var2, var11, this.handledType(), var4, "empty String (\"\")");
         } else {
            var11 = this._findCoercionFromBlankString(var2);
            var11 = this._checkCoercionFail(var2, var11, this.handledType(), var4, "blank String (all whitespace)");
         }

         switch (var11) {
            case AsNull:
            default:
               return null;
            case AsEmpty:
            case TryConvert:
               return this.getEmptyValue(var2);
         }
      } else {
         if (Boolean.TRUE.equals(this.HRRHHOHICOCRIHHCRIOIIHRCIHHHII)) {
            Object var6 = var3.HRHIOHRHORHOCIICRCHICCOIROORHC(var5);
            if (var6 != null) {
               return var6;
            }
         }

         if (!var2.CRRRICCRROCOHHOHIICIHORCOORRRH(
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.FAIL_ON_NUMBERS_FOR_ENUMS
            )
            && !this.IRRORROOIHRRRRHRHOICCOCOIOHRCO) {
            char var9 = var5.charAt(0);
            if (var9 >= '0' && var9 <= '9') {
               try {
                  int var7 = Integer.parseInt(var5);
                  if (!var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.ALLOW_COERCION_OF_SCALARS
                  )) {
                     return var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        this.HCCIHCIHHOICHCRCOOCCOIHCHIRROH(),
                        var5,
                        "value looks like quoted Enum index, but `MapperFeature.ALLOW_COERCION_OF_SCALARS` prevents use"
                     );
                  }

                  if (var7 >= 0 && var7 < this.IOCOHHCIOIOCCRIHHHRRHIHRIICCCR.length) {
                     return this.IOCOHHCIOIOCCRIHHHRRHIHRIICCCR[var7];
                  }
               } catch (NumberFormatException var8) {
               }
            }
         }

         if (this.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var2)) {
            return this.RRIHRRRRHOCRROIOCIRIIIHRCOOHRH;
         } else {
            return this.OCOHORHCROHICRRIHCIHHRRCIHICRI(var2)
               ? null
               : var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  this.HCCIHCIHHOICHCRCOOCCOIHCHIRROH(), var5, "not one of the values accepted for Enum class: %s", var3.IIOHOHOHCRRRORCROOIOCHCRCOHHHR()
               );
         }
      }
   }

   protected Object IIOIROIHIHHCCRICRCOOCHIICHRCOI(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2
   ) {
      return var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.START_ARRAY
         )
         ? this._deserializeFromArray(var1, var2)
         : var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.HCCIHCIHHOICHCRCOOCCOIHCHIRROH(), var1);
   }

   protected Class<?> HCCIHCIHHOICHCRCOOCCOIHCHIRROH() {
      return this.handledType();
   }

   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CORCOCICIRIOHROHROIIOOHICCHCRR IIHRRHORCRCROCHHOHORCHCROCIHRO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CORCOCICIRIOHROHROIIOOHICCHCRR var2 = this.CCIRRRROOIRCOIHHRHOCHRRCCIRHIC;
      if (var2 == null) {
         synchronized (this) {
            var2 = this.CCIRRRROOIRCOIHHRHOCHRRCCIRHIC;
            if (var2 == null) {
               var2 = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
                     var1.IIICIOIHIHICHHIHRICHCIRHHIIRII(), this.HCCIHCIHHOICHCRCOOCCOIHCHIRROH()
                  )
                  .HCOOOOCRIORIICCCHIRIHCIIRIOHOI();
               this.CCIRRRROOIRCOIHHRHOCHRRCCIRHIC = var2;
            }
         }
      }

      return var2;
   }

   protected boolean OCOHORHCROHICRRIHCIHHRRCIHICRI(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1
   ) {
      return Boolean.TRUE.equals(this.COROHORIOHRRHOCIROCCHHORCOCIHR)
         || var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.READ_UNKNOWN_ENUM_VALUES_AS_NULL
         );
   }

   protected boolean CIOHHCORHRCCRICCCORIHCRHCCCRRR(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1
   ) {
      return this.RRIHRRRRHOCRROIOCIRIIIHRCOOHRH != null
         && (
            Boolean.TRUE.equals(this.CCCHOOROOIIHHRHCRHROOCHHOCCCIC)
               || var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
                  com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE
               )
         );
   }
}
