package com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import lombok.Generated;

public class RRCRRCORICCHOHHIRCHIROOHIIOHCO {
   public static RCIROOOOICRHCCRRCIORHHIRCOIIIC IHHRHOCRCOCRCHIIOICCHRHCHOOIHI;
   public static Gson OCRCCIOHHRIIRRRROIHOHRIROOHIRC;
   public String identifier = "";
   public CRRRICCRROCOHHOHIICIHORCOORRRH ROCOIOORRCCICOIHOROIIHHCCIIIRO = CRRRICCRROCOHHOHIICIHORCOORRRH.OPAQUE;
   public RCIROOOOICRHCCRRCIORHHIRCOIIIC texture;
   public Map<String, RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> IROHHIRIRHIICICCHHRIHHOICRHHIR;
   public List<com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> HRCCOHCRHCHHOOHRICOHHIROROOROI;
   public List<com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH> ORRCICCORRIHIHCRHCIIRRCICRIORC;
   public List<com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH> CCRRIRRIOCOCIIHHCHORRIHHIIHIII;
   public List<com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO> HROOCHOCOOHIHCCRCHOIRCHCRCCRCR;
   public List<HRCHROOHRIHCRCRHRIIROCIRHOIRHH> CCOHOCORICRHIHHOOHORRIROCOCIRO;
   public List<com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI> CHIIROIHCCROIIHIHHCCHCCIIIRCRO;
   private boolean CIOORRHOOORCROOICCCOORROCIIORR;
   public String bone;
   public com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RCIIHCRHCCRORIIOHCCICRRIICIHCI;

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO() {
      this.texture = IHHRHOCRCOCRCHIIOICCHRHCHOOIHI;
      this.IROHHIRIRHIICICCHHRIHHOICRHHIR = new HashMap<>();
      this.HRCCOHCRHCHHOOHRICOHHIROROOROI = new ArrayList<>();
      this.RCIIHCRHCCRORIIOHCCICRRIICIHCI = new com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH();
   }

   public static void ORRCOOOCHCIIRRRCORIIOOHHOHCOIH(RCIROOOOICRHCCRRCIORHHIRCOIIIC var0) {
      IHHRHOCRCOCRCHIIOICCHRHCHOOIHI = var0;
   }

   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var0) {
      OCRCCIOHHRIIRRRROIHOHRIROOHIRC = new GsonBuilder().registerTypeAdapter(RRCRRCORICCHOHHIRCHIROOHIIOHCO.class, var0).create();
   }

   public static RRCRRCORICCHOHHIRCHIROOHIIOHCO OOHHROCHCORCRHCOOHIOCRRICCHHOI(String var0) {
      return OCRCCIOHHRIIRRRROIHOHRIROOHIRC.fromJson(var0, RRCRRCORICCHOHHIRCHIROOHIIOHCO.class);
   }

   public static RRCRRCORICCHOHHIRCHIROOHIIOHCO IOIICIRIICICIIOORHCIIIIRRIHRHI(JsonElement var0) {
      return OCRCCIOHHRIIRRRROIHOHRIROOHIRC.fromJson(var0, RRCRRCORICCHOHHIRCHIROOHIIOHCO.class);
   }

   public static JsonElement RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RRCRRCORICCHOHHIRCHIROOHIIOHCO var0) {
      return OCRCCIOHHRIIRRRROIHOHRIROOHIRC.toJsonTree(var0);
   }

   public static RRCRRCORICCHOHHIRCHIROOHIIOHCO IRCIIHHICIHRCOCRROCOICRIHHCCHH(RRCRRCORICCHOHHIRCHIROOHIIOHCO var0) {
      return IOIICIRIICICIIOORHCIIIIRRIHRHI(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0));
   }

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO CHCCIROOIHCCRCIHCIOIHRIIHROIRO(boolean var1) {
      this.CIOORRHOOORCROOICCCOORROCIIORR = var1;
      return this;
   }

   public boolean HOCCRHOROOIHOHHHRCIOOIIRHIRIHO() {
      return this.CIOORRHOOORCROOICCCOORROCIIORR;
   }

   public void setup() {
      this.OIHCOHRCICCCRHRCROOCIOIRRHHHIH(
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class
      );
      this.ORRCICCORRIHIHCRHCIIRRCICRIORC = this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class
      );
      this.CCRRIRRIOCOCIIHHCHORRIHHIIHIII = this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.class
      );
      this.HROOCHOCOOHIHCCRCHOIRCHCRCCRCR = this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.class
      );
      this.CCOHOCORICRHIHHOOHORRIROCOCIRO = this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(HRCHROOHRIHCRCRHRIIROCIRHOIRHH.class);
      this.CHIIROIHCCROIIHIHHCCHCCIIIRCRO = this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.class
      );

      for (Entry var2 : this.IROHHIRIRHIICICCHHRIHHOICRHHIR.entrySet()) {
         ((RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var2.getValue()).HOOHRHCIHCRRHCORCHHIRCHOROHOII = this.RCIIHCRHCCRORIIOHCCICRRIICIHCI
            .HHIOCIRHCHIRHHRIRCHOIRORHCRCRI
            .get(var2.getKey());
      }
   }

   public <T extends com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> List<T> ICICIOCHHHIHOCHCOHORIHRCOHHOCR(
      Class<T> var1
   ) {
      ArrayList var2 = new ArrayList();

      for (com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 : this.HRCCOHCRHCHHOOHRICOHHIROROOROI) {
         if (var1.isAssignableFrom(var4.getClass())) {
            var2.add(
               (com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var4
            );
         }
      }

      if (var2.size() > 1) {
         Collections.sort(
            var2,
            Comparator.comparingInt(
               com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH::IHHCCIORHRCORORHHIOICIRCHCHOHH
            )
         );
      }

      return var2;
   }

   public <T extends com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> T IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
      Class<T> var1
   ) {
      for (com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 : this.HRCCOHCRHCHHOOHRICOHHIROROOROI) {
         if (var1.isAssignableFrom(var3.getClass())) {
            return (T)var3;
         }
      }

      return null;
   }

   public <T extends com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> T RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
      Class<T> var1
   ) {
      com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = null;

      try {
         var2 = (com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var1.getConstructor(
               
            )
            .newInstance();
         this.HRCCOHCRHCHHOOHRICOHHIROROOROI.add(var2);
         this.setup();
      } catch (Exception var4) {
      }

      return (T)var2;
   }

   public <T extends com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> T OIHCOHRCICCCRHRCROOCIOIRRHHHIH(
      Class<T> var1
   ) {
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var1);
   }

   public <T extends com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> T RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Class<T> var1, Class var2
   ) {
      com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = this.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
         var1
      );
      if (var3 == null) {
         var3 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(var2);
      }

      return (T)var3;
   }

   public <T extends com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> T ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(
      Class<T> var1
   ) {
      Iterator var2 = this.HRCCOHCRHCHHOOHRICOHHIROROOROI.iterator();

      while (var2.hasNext()) {
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = (com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var2.next();
         if (var1.isAssignableFrom(var3.getClass())) {
            var2.remove();
            return (T)var3;
         }
      }

      return null;
   }

   public <T extends com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> T IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      Class<T> var1, Class var2
   ) {
      this.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(var1);
      return this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(var2);
   }

   public void RRCIHRORRHHIRHCHHICCCRICORHCIO() {
      for (RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 : this.IROHHIRIRHIICICCHHRIHHOICRHHIR.values()) {
         if (var2.HOOHRHCIHCRRHCORCHHIRCHOROHOII != null) {
            var2.HOOHRHCIHCRRHCORCHHIRCHOROHOII.set(var2.RIIRORCICICCCHHHOCROOHRRCOHOCC());
         }
      }
   }

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO OOHCOCOHIOCCHIROOOORIORIRHIHIO() {
      RRCRRCORICCHOHHIRCHIROOHIIOHCO var1 = new RRCRRCORICCHOHHIRCHIROOHIIOHCO();
      var1.identifier = "";
      var1.ROCOIOORRCCICOIHOROIIHHCCIIIRO = CRRRICCRROCOHHOHIICIHORCOORRRH.OPAQUE;
      var1.texture = IHHRHOCRCOCRCHIIOICCHRHCHOOIHI;
      var1.bone = this.bone;
      var1.IROHHIRIRHIICICCHHRIHHOICRHHIR = this.IROHHIRIRHIICICCHHRIHHOICRHHIR;
      var1.HRCCOHCRHCHHOOHRICOHHIROROOROI = this.HRCCOHCRHCHHOOHRICOHHIROROOROI;
      var1.ORRCICCORRIHIHCRHCIIRRCICRIORC = this.ORRCICCORRIHIHCRHCIIRRCICRIORC;
      var1.CCRRIRRIOCOCIIHHCHORRIHHIIHIII = this.CCRRIRRIOCOCIIHHCHORRIHHIIHIII;
      var1.HROOCHOCOOHIHCCRCHOIRCHCRCCRCR = this.HROOCHOCOOHIHCCRCHOIRCHCRCCRCR;
      var1.CCOHOCORICRHIHHOOHORRIROCOCIRO = this.CCOHOCORICRHIHHOOHORRIROCOCIRO;
      var1.CHIIROIHCCROIIHIHHCCHCCIIIRCRO = this.CHIIROIHCCROIIHIHHCCHCCIIIRCRO;
      var1.CIOORRHOOORCROOICCCOORROCIIORR = this.CIOORRHOOORCROOICCCOORROCIIORR;
      return var1;
   }

   @Generated
   public String getBone() {
      return this.bone;
   }

   static {
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         new com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
      );
      ORRCOOOCHCIIRRRCORIIOOHHOHCOIH(RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "particles/textures/default_particles.webp"));
   }
}
