package com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   public IRCIIHHICIHRCOCRROCOICRIHHCCHH CRIICOHHOHICHOHIHOOIRIIOIRRHRI = IRCIIHHICIHRCOCRROCOICRIHHCCHH.LINEAR;
   public com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH[] HOHRICCIHOCCRRCOIRIIOOCIROOHII = new com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH[]{
      com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCICRRHIHHRIOIHCOOHCIRIIICCCH,
      com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IORRCOHROOHHORCRCOOIRHRCORHHHH,
      com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCICRRHIHHRIOIHCOOHCIRIIICCCH
   };
   public com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OCORIOIROCRCCHCOOOIOICOICHICHR;
   public com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HRCICOHIOOCICCIIHHICRIOOCCOOII;
   public CRICCOOHHHCHOORCICOCOHIHOIRHOO HOOHRHCIHCRRHCORCHHIRCHOROHOII;

   public double RIIRORCICICCCHHHOCROOHRRCOHOCC() {
      return this.RRRHHIRORHCHHCOOCIHOICORHHCHHO(this.OCORIOIROCRCCHCOOOIOICOICHICHR.get() / this.HRCICOHIOOCICCIIHHICRIOOCCOOII.get());
   }

   private double RRRHHIRORHCHHCOOCIHOICORHHCHHO(double var1) {
      int var3 = this.HOHRICCIHOCCRRCOIRIIOOCIROOHII.length;
      if (var3 == 0) {
         return 0.0;
      }

      if (var3 == 1) {
         return this.HOHRICCIHOCCRRCOIRIIOOCIROOHII[0].get();
      }

      if (var1 < 0.0) {
         var1 = -(1.0 + var1);
      }

      var1 = com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.clamp(
         var1, 0.0, 1.0
      );
      if (this.CRIICOHHOHICHOHIHOOIRIIOIRRHRI == IRCIIHHICIHRCOCRROCOICRIHHCCHH.HERMITE) {
         if (var3 <= 3) {
            return this.HOHRICCIHOCCRRCOIRIIOOCIROOHII[var3 - 2].get();
         }

         var1 *= var3 - 3;
         int var12 = (int)var1 + 1;
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var13 = this.RHIRIIORHCHHOIOROHORCOHIIIOOCH(
            var12 - 1
         );
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var14 = this.RHIRIIORHCHHOIOROHORCOHIIIOOCH(
            var12
         );
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7 = this.RHIRIIORHCHHOIOROHORCOHIIIOOCH(
            var12 + 1
         );
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var8 = this.RHIRIIORHCHHOIOROHORCOHIIIOOCH(
            var12 + 2
         );
         return com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.cubicHermite(
            var13.get(), var14.get(), var7.get(), var8.get(), var1 % 1.0
         );
      } else {
         var1 *= var3 - 1;
         int var4 = (int)var1;
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = this.RHIRIIORHCHHOIOROHORCOHIIIOOCH(
            var4
         );
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var6 = this.RHIRIIORHCHHOIOROHORCOHIIIOOCH(
            var4 + 1
         );
         return com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.lerp(
            var5.get(), var6.get(), var1 % 1.0
         );
      }
   }

   private com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RHIRIIORHCHHOIOROHORCOHIIIOOCH(
      int var1
   ) {
      if (var1 < 0) {
         return this.HOHRICCIHOCCRRCOIRIIOOCIROOHII[0];
      } else {
         return var1 >= this.HOHRICCIHOCCRRCOIRIIOOCIROOHII.length
            ? this.HOHRICCIHOCCRRCOIRIIOOCIROOHII[this.HOHRICCIHOCCRRCOIRIIOOCIROOHII.length - 1]
            : this.HOHRICCIHOCCRRCOIRIIOOCIROOHII[var1];
      }
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      JsonObject var1, com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      if (var1.has("type")) {
         this.CRIICOHHOHICHOHIHOOIRIIOIRRHRI = IRCIIHHICIHRCOCRROCOICRIHHCCHH.fromString(var1.get("type").getAsString());
      }

      if (var1.has("input")) {
         this.OCORIOIROCRCCHCOOOIOICOICHICHR = var2.IHIRRIIORRHORHRORIHOROIRCORCOO(var1.get("input"));
      }

      if (var1.has("horizontal_range")) {
         this.HRCICOHIOOCICCIIHHICRIOOCCOOII = var2.IHIRRIIORRHORHRORIHOROIRCORCOO(var1.get("horizontal_range"));
      }

      if (var1.has("nodes")) {
         JsonArray var3 = var1.getAsJsonArray("nodes");
         com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH[] var4 = new com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH[var3.size()];
         int var5 = 0;

         for (int var6 = var4.length; var5 < var6; var5++) {
            var4[var5] = var2.IHIRRIIORRHORHRORIHOROIRCORCOO(var3.get(var5));
         }

         this.HOHRICCIHOCCRRCOIRIIOOCIROOHII = var4;
      }
   }

   public JsonElement RCHIIHHHCCIOHHRORHOORICCCRHOOI() {
      JsonObject var1 = new JsonObject();
      JsonArray var2 = new JsonArray();
      var1.addProperty("type", this.CRIICOHHOHICHOHIHOOIRIIOIRRHRI.id);
      var1.add("nodes", var2);
      var1.add("input", this.OCORIOIROCRCCHCOOOIOICOICHICHR.RCHIIHHHCCIOHHRORHOORICCCRHOOI());
      var1.add("horizontal_range", this.HRCICOHIOOCICCIIHHICRIOOCCOOII.RCHIIHHHCCIOHHRORHOORICCCRHOOI());

      for (com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var6 : this.HOHRICCIHOCCRRCOIRIIOOCIROOHII) {
         var2.add(var6.RCHIIHHHCCIOHHRORHOORICCCRHOOI());
      }

      return var1;
   }
}
