package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import java.io.IOException;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;

public abstract class HICRRICCHCCROOHHCHOCOCCHOIHHOC implements Serializable {
   private static final long CICIIOHIHRRRHHIICHHRHOCCICIORI = 1L;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH OCCHCICIOCRIRROIIHCHRCOCRHHHHC;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO IOCICHROCOIRIOOOCICHCOICRIROIO;
   protected final boolean IRRCRIOCHCCRCRHCHICRIOCOCHCOOR;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI IRRCRCCCCRIOCHRCOOCIHHIORIRCIC;
   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> HHIHOICCHHRHIRHHHOOHRRICCHIORR;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI COHCIOOHRORCHOHHHHIRIOOHRICHIO;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRRCCOICORICIHCHRHIHIHROIRHOCR ORRIOHHRRRIRIRRHICRCCIRRIHCICR;

   public HICRRICCHCCROOHHCHOCOCCHOIHHOC(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRRCCOICORICIHCHRHIHIHROIRHOCR var4,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var5,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var6
   ) {
      this.OCCHCICIOCRIRROIIHCHRCOCRHHHHC = var1;
      this.IOCICHROCOIRIOOOCICHCOICRIROIO = var2;
      this.IRRCRCCCCRIOCHRCOOCIHHIORIRCIC = var3;
      this.HHIHOICCHHRHIRHHHOOHRRICCHIORR = var5;
      this.COHCIOOHRORCHOHHHHIRIOOHRICHIO = var6;
      this.ORRIOHHRRRIRIRRHICRCCIRRIHCICR = var4;
      this.IRRCRIOCHCCRCRHCHICRIOCOCHCOOR = var2 instanceof com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
   }

   public static HICRRICCHCCROOHHCHOCOCCHOIHHOC RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var0,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRRCCOICORICIHCHRHIHIHROIRHOCR var4,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var5,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var6
   ) {
      return new HICRRICCHCCROOHHCHOCOCCHOIHHOC.CRRRICCRROCOHHOHIICIHORCOORRRH(var1, var2, var3, var4, var5, var6);
   }

   public static HICRRICCHCCROOHHCHOCOCCHOIHHOC IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var0,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRRCCOICORICIHCHRHIHIHROIRHOCR var4,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var5,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var6
   ) {
      Class var7 = var2.getRawType();
      if (var7 == Map.class) {
         var7 = LinkedHashMap.class;
      }

      HHRIICOIOORCHCOIICOOIHIRHHICRI var8 = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH(
         var0.IIICIOIHIHICHHIHRICHCIRHHIIRII(), var7
      );
      return new HICRRICCHCCROOHHCHOCOCCHOIHHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1, var2, var3, var4, var5, var6, var8);
   }

   public static HICRRICCHCCROOHHCHOCOCCHOIHHOC RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var0,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var4
   ) {
      return new HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3, var4, var0.RROHHIIHIOOOHHIRRROOCRORRCRCHI());
   }

   public abstract HICRRICCHCCROOHHCHOCOCCHOIHHOC CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var1
   );

   public void RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1
   ) {
      this.IOCICHROCOIRIOOOCICHCOICRIROIO
         .HRRIIOOHRHHHOOOHCHRCIOCICRCRIH(
            var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.OVERRIDE_PUBLIC_ACCESS_MODIFIERS
            )
         );
   }

   Object readResolve() {
      if (this.IOCICHROCOIRIOOOCICHCOICRIROIO != null && this.IOCICHROCOIRIOOOCICHCOICRIROIO.RHCHIIHIHIRCRIRHRCIRIIOROOOHOC() != null) {
         return this;
      } else {
         throw new IllegalArgumentException("Missing method/field (broken JDK (de)serialization?)");
      }
   }

   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH CROIRIHRHRHCIHHCRHROIOHHORIIOI() {
      return this.OCCHCICIOCRIRROIIHCHRCOCRHHHHC;
   }

   public boolean RRCRCHHOOCOCIROCCRRCIRHRORCRRR() {
      return this.HHIHOICCHHRHIRHHHOOHRRICCHIORR != null;
   }

   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI getType() {
      return this.IRRCRCCCCRIOCHRCOOCIHHIORIRCIC;
   }

   public String HCOCORHRRHOCRCCRCHRIICIIORROOR() {
      return this.OCCHCICIOCRIRROIIHCHRCOCRHHHHC.getName();
   }

   public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2,
      Object var3,
      String var4
   ) {
      try {
         Object var5 = this.ORRIOHHRRRIRIRRHICRCCIRRIHCICR == null ? var4 : this.ORRIOHHRRRIRIRRHICRCCIRRIHCICR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var2);
         this.set(var3, var5, this.deserialize(var1, var2));
      } catch (IHIRRIIORRHORHRORIHOROIRCORCOO var7) {
         if (this.HHIHOICCHHRHIRHHHOOHRRICCHIORR.getObjectIdReader() == null) {
            throw com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1, "Unresolved forward reference but no identity info.", var7
            );
         }

         HICRRICCHCCROOHHCHOCOCCHOIHHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = new HICRRICCHCCROOHHCHOCOCCHOIHHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this, var7, this.IRRCRCCCCRIOCHRCOOCIHHIORIRCIC.RRICIOOORRIORHHICIRCIOCHRHRCHH(), var3, var4
         );
         var7.IIOHOOHCRCCORROHROOHCOHCRIOHRI().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6);
      }
   }

   public Object deserialize(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2
   ) {
      if (var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NULL
      )) {
         return this.HHIHOICCHHRHIRHHHOOHRRICCHIORR.getNullValue(var2);
      } else {
         return this.COHCIOOHRORCHOHHHHIRIOOHRICHIO != null
            ? this.HHIHOICCHHRHIRHHHOOHRRICCHIORR.deserializeWithType(var1, var2, this.COHCIOOHRORCHOHHHHIRIOOHRICHIO)
            : this.HHIHOICCHHRHIRHHHOOHRRICCHIORR.deserialize(var1, var2);
      }
   }

   public void set(Object var1, Object var2, Object var3) {
      try {
         this.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1, var2, var3);
      } catch (IOException var5) {
         throw var5;
      } catch (Exception var6) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, var2, var3);
      }
   }

   protected abstract void CIOHHCORHRCCRICCCORIHCRHCCCRRR(Object var1, Object var2, Object var3);

   protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Exception var1, Object var2, Object var3) {
      if (var1 instanceof IllegalArgumentException) {
         String var7 = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RRROIHOIHOORCCOHOOCHRRRCIIRHHH(
            var3
         );
         StringBuilder var5 = new StringBuilder("Problem deserializing \"any-property\" '").append(var2);
         var5.append("' of class " + this.getClassName() + " (expected type: ").append(this.IRRCRCCCCRIOCHRCOOCIHHIORIRCIC);
         var5.append("; actual type: ").append(var7).append(")");
         String var6 = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IHIRRIIORRHORHRORIHOROIRCORCOO(
            var1
         );
         if (var6 != null) {
            var5.append(", problem: ").append(var6);
         } else {
            var5.append(" (no error message provided)");
         }

         throw new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
            null, var5.toString(), var1
         );
      } else {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRRCCOICORICIHCHRHIHIHROIRHOCR(
            var1
         );
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RHOCHHIRRCHHHOHOIRROIROHHHIHIO(
            var1
         );
         Throwable var4 = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.getRootCause(
            var1
         );
         throw new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
            null,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IHIRRIIORRHORHRORIHOROIRCORCOO(
               var4
            ),
            var4
         );
      }
   }

   private String getClassName() {
      return com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.ROIHROCROORRCCOIRRIHHORCROOORO(
         this.IOCICHROCOIRIOOOCICHCOICRIROIO.getDeclaringClass()
      );
   }

   @Override
   public String toString() {
      return "[any property on class " + this.getClassName() + "]";
   }

   protected static class CRRRICCRROCOHHOHIICIHORCOORRRH extends HICRRICCHCCROOHHCHOCOCCHOIHHOC implements Serializable {
      private static final long CICCHCRHIOCCRHRHIOCHRRHOHICCIH = 1L;

      public CRRRICCRROCOHHOHIICIHORCOORRRH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var3,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRRCCOICORICIHCHRHIHIHROIRHOCR var4,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var5,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var6
      ) {
         super(var1, var2, var3, var4, var5, var6);
      }

      @Override
      protected void CIOHHCORHRCCRICCCORIHCRHCCCRRR(Object var1, Object var2, Object var3) {
         ((com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI)this.IOCICHROCOIRIOOOCICHCOICRIROIO)
            .IIHRRHORCRCROCHHOHORCHCROCIHRO(var1, var2, var3);
      }

      @Override
      public HICRRICCHCCROOHHCHOCOCCHOIHHOC CRRRICCRROCOHHOHIICIHORCOORRRH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var1
      ) {
         return new HICRRICCHCCROOHHCHOCOCCHOIHHOC.CRRRICCRROCOHHOHIICIHORCOORRRH(
            this.OCCHCICIOCRIRROIIHCHRCOCRHHHHC,
            this.IOCICHROCOIRIOOOCICHCOICRIROIO,
            this.IRRCRCCCCRIOCHRCOOCIHHIORIRCIC,
            this.ORRIOHHRRRIRIRRHICRCCIRRIHCICR,
            var1,
            this.COHCIOOHRORCHOHHHHIRIOOHRICHIO
         );
      }
   }

   protected static class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends HICRRICCHCCROOHHCHOCOCCHOIHHOC implements Serializable {
      private static final long OHRIOOORCOHOHRCCIRHORICORIOCOR = 1L;
      protected final HHRIICOIOORCHCOIICOOIHIRHHICRI ICHCIIIIIIRHRCRORCRCIOHHICORCO;

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var3,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRRCCOICORICIHCHRHIHIHROIRHOCR var4,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var5,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var6,
         HHRIICOIOORCHCOIICOOIHIRHHICRI var7
      ) {
         super(var1, var2, var3, var4, var5, var6);
         this.ICHCIIIIIIRHRCRORCRCIOHHICORCO = var7;
      }

      @Override
      public HICRRICCHCCROOHHCHOCOCCHOIHHOC CRRRICCRROCOHHOHIICIHORCOORRRH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var1
      ) {
         return new HICRRICCHCCROOHHCHOCOCCHOIHHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            this.OCCHCICIOCRIRROIIHCHRCOCRHHHHC,
            this.IOCICHROCOIRIOOOCICHCOICRIROIO,
            this.IRRCRCCCCRIOCHRCOOCIHHIORIRCIC,
            this.ORRIOHHRRRIRIRRHICRCCIRRIHCICR,
            var1,
            this.COHCIOOHRORCHOHHHHIRIOOHRICHIO,
            this.ICHCIIIIIIRHRCRORCRCIOHHICORCO
         );
      }

      @Override
      protected void CIOHHCORHRCCRICCCORIHCRHCCCRRR(Object var1, Object var2, Object var3) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var4 = (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR)this.IOCICHROCOIRIOOOCICHCOICRIROIO;
         Map var5 = (Map)var4.getValue(var1);
         if (var5 == null) {
            var5 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(null, var4, var1, var2);
         }

         var5.put(var2, var3);
      }

      protected Map<Object, Object> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2,
         Object var3,
         Object var4
      ) {
         if (this.ICHCIIIIIIRHRCRORCRCIOHHICORCO == null) {
            throw com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1,
               String.format(
                  "Cannot create an instance of %s for use as \"any-setter\" '%s'",
                  com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.ROIHROCROORRCCOIRRIHHORCROOORO(
                     this.IRRCRCCCCRIOCHRCOOCIHHIORIRCIC.RRICIOOORRIORHHICIRCIOCHRHRCHH()
                  ),
                  this.OCCHCICIOCRIRROIIHCHRCOCRHHHHC.getName()
               )
            );
         }

         Map var5 = (Map)this.ICHCIIIIIIRHRCRORCRCIOHHICORCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1);
         var2.HHIRHRHHRHIHRHOHCHRHIORRHIIHOR(var3, var5);
         return var5;
      }
   }

   protected static class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends HICRRICCHCCROOHHCHOCOCCHOIHHOC implements Serializable {
      private static final long OCHCRIHRHOCOCICHRIHCORRORHORRC = 1L;
      protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.OCOHORHCROHICRRIHCIHHRRCIHICRI RCCCRRRRIICHOHIROOCOIOIOHICCIO;

      public IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var3,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var4,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.OCOHORHCROHICRRIHCIHHRRCIHICRI var5
      ) {
         super(var1, var2, var3, null, var4, null);
         this.RCCCRRRRIICHOHIROOCOIOIOHICCIO = var5;
      }

      @Override
      public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2,
         Object var3,
         String var4
      ) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var3,
            var4,
            (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR)this.deserialize(var1, var2)
         );
      }

      @Override
      public Object deserialize(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2
      ) {
         return this.HHIHOICCHHRHIRHHHOOHRRICCHIORR.deserialize(var1, var2);
      }

      @Override
      protected void CIOHHCORHRCCRICCCORIHCRHCCCRRR(Object var1, Object var2, Object var3) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1, (String)var2, (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR)var3
         );
      }

      protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         Object var1, String var2, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR var3
      ) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var4 = (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR)this.IOCICHROCOIRIOOOCICHCOICRIROIO;
         Object var5 = var4.getValue(var1);
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.HICRRICCHCCROOHHCHOCOCCHOIHHOC var6;
         if (var5 == null) {
            var6 = this.RCCCRRRRIICHOHIROOCOIOIOHICCIO.HCHHCOCCORCCROIRHORIIOOORRCCHH();
            var4.HHIRHRHHRHIHRHOHCHRHIORRHIIHOR(var1, var6);
         } else {
            if (!(
               var5 instanceof com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.HICRRICCHCCROOHHCHOCOCCHOIHHOC
            )) {
               throw com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR)null,
                  String.format(
                     "Value \"any-setter\" '%s' not `ObjectNode` but %s",
                     this.HCOCORHRRHOCRCCRCHRIICIIORROOR(),
                     com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.ROIHROCROORRCCOIRRIHHORCROOORO(
                        var5.getClass()
                     )
                  )
               );
            }

            var6 = (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.HICRRICCHCCROOHHCHOCOCCHOIHHOC)var5;
         }

         var6.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3);
      }

      @Override
      public HICRRICCHCCROOHHCHOCOCCHOIHHOC CRRRICCRROCOHHOHIICIHORCOORRRH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> var1
      ) {
         return this;
      }
   }

   private static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      extends com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      private final HICRRICCHCCROOHHCHOCOCCHOIHHOC IRCICIHRHHOHIHCCCOIOIIOIRRCCRC;
      private final Object IIICROOOIOCOHCRHIHHIOOCCHCCCHO;
      private final String CRCRHCCHORRHHCICCIICRHIOCIRHHI;

      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC var1, IHIRRIIORRHORHRORIHOROIRCORCOO var2, Class<?> var3, Object var4, String var5) {
         super(var2, var3);
         this.IRCICIHRHHOHIHCCCOIOIIOIRRCCRC = var1;
         this.IIICROOOIOCOHCRHIHHIOOCCHCCCHO = var4;
         this.CRCRHCCHORRHHCICCIICRHIOCIRHHI = var5;
      }

      @Override
      public void IOIOHIORIROHRRCOOOHCROHORCOIIH(Object var1, Object var2) {
         if (!this.HICROROICOCOHOOHHCRCROOCCRCIHR(var1)) {
            throw new IllegalArgumentException("Trying to resolve a forward reference with id [" + var1.toString() + "] that wasn't previously registered.");
         }

         this.IRCICIHRHHOHIHCCCOIOIIOIRRCCRC.set(this.IIICROOOIOCOHCRHIHHIOOCCHCCCHO, this.CRCRHCCHORRHHCICCIICRHIOCIRHHI, var2);
      }
   }
}
