package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;

import com.google.gson.annotations.SerializedName;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.util.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO;
import com.moonsworth.lunar.client.util.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import java.util.Map.Entry;
import java.util.function.Function;
import lombok.Generated;
import org.apache.commons.lang3.Range;

@RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO
public abstract class CRRRICCRROCOHHOHIICIHORCOORRRH<T extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO<T>> {
   @SerializedName("id")
   private final UUID ORICCHCRRCIICCHIIRIHHCIOROCIHH = UUID.randomUUID();
   @SerializedName("layers")
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<T> IIHCOCICOOICRIHRIHCOOCIHROICRO;
   @SerializedName("type")
   private final String COCOOCCOHCRCCOOOORHIHCROOOHOII = this.type();
   @SerializedName("showKeyframes")
   private boolean IORRROIOORHIORHOOCCHIHHIIHICCO = true;
   @SerializedName("enabled")
   private boolean enabled = true;

   public CRRRICCRROCOHHOHIICIHORCOORRRH(
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      this.IIHCOCICOOICRIHRIHCOOCIHROICRO = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<>(
         var1, var2
      );
      this.IIHCOCICOOICRIHRIHCOOCIHROICRO.OCOHORHCROHICRRIHCIHHRRCIHICRI(() -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(null));
   }

   public Entry<Range<Integer>, T> IOHCRRIIHCIHORROOCHCCORIHRHCII(int var1) {
      return this.IIHCOCICOOICRIHRIHCOOCIHROICRO.HICRRICCHCCROOHHCHOCOCCHOIHHOC(var1);
   }

   public boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      IIHRHCCOOHOOOOCHRRCOROOIOHCOOO<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH> var1,
      int var2
   ) {
      if (!this.enabled) {
         return false;
      } else {
         Entry var3 = this.IOHCRRIIHCIHORROOCHCCORIHRHCII(var2);
         if (var3 != null) {
            ((com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO)var3.getValue())
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, (Range<Integer>)var3.getKey(), var2);
            return true;
         } else {
            return false;
         }
      }
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      IIHRHCCOOHOOOOCHRRCOROOIOHCOOO<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH> var1
   ) {
      for (Entry var3 : new HashMap<>(this.IIHCOCICOOICRIHRIHCOOCIHROICRO.HHOIOOOROHCHIRORCICOCIICCRROCO()).entrySet()) {
         Range var4 = (Range)var3.getKey();
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var5 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO)var3.getValue();
         int var6 = var5.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var4);
         if (Math.abs(var6) > 1) {
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7 = var1
                  == null
               ? null
               : ((com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH)var1.get())
                  .RCRHOCOIIRCHRIRIIOHCOCCRHCHCCR();
            int var8 = var7 == null ? 0 : var7.IHRHCHOCCHHICIIOIORIRCIHHHHHIH();
            var8 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, (T)var5, var6, var8);
            if (var7 != null) {
               var7.ROCHRRCORRCOOOOOCOICOCROIIHIHH(var8);
            }
         } else {
            int var9 = (Integer)var4.getMaximum() - (Integer)var4.getMinimum();
            var5.ROIOROHRIHRRHIHRRRIHHHIICCHIOI(Math.max(0, var9 - var5.ORCCRCCOCICHHRCICHHHHCOHRICOCI()));
         }
      }
   }

   private int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Range<Integer> var1, T var2, int var3, int var4) {
      int var5 = (Integer)var1.getMinimum();
      int var6 = (Integer)var1.getMaximum() - var5;
      int var7 = (Integer)var1.getMaximum() + var3;
      int var8 = Math.max(1, var6 - var2.HIHIOOHCRCRCCCROCOHRCOHRIOCHOH());
      int var9 = Math.max(1, var2.ORCCRCCOCICHHRCICHHHHCOHRICOCI());
      double var10 = (double)var9 / var8;
      this.IIHCOCICOOICRIHRIHCOOCIHROICRO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var1);
      this.IIHCOCICOOICRIHRIHCOOCIHROICRO.RRCRRCORICCHOHHIRCHIROOHIIOHCO((Integer)var1.getMaximum(), var3, true);
      Range var12 = Range.between(var5, var7);
      this.IIHCOCICOOICRIHRIHCOOCIHROICRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var12, (T)var2);
      var2.ROIOROHRIHRRHIHRRRIHHHIICCHIOI(Math.max(0, var7 - var5 - var9));
      Function var13 = var2x -> (int)Math.round(var2x.intValue() * var10);
      Range var14 = Range.between(0, var6);
      var2.HIIHOIHOCORCOOHHRCCCRCIIIIHIIH()
         .values()
         .stream()
         .map(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH::HCIORRCRIRHIOIHORHHHRRIRRIROIC
         )
         .map(Map::values)
         .flatMap(Collection::stream)
         .map(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI::HORCHIIOIHRCHOIIRIRHIHRCOIIRCO)
         .forEach(var2x -> {
            HashMap var3x = new HashMap();

            for (Integer var5x : new ArrayList(var2x.keySet())) {
               if (var14.contains(var5x)) {
                  var3x.put((Integer)var13.apply(var5x), (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var2x.remove(var5x));
               }
            }

            for (Entry var7x : var3x.entrySet()) {
               var2x.put((Integer)var7x.getKey(), (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var7x.getValue());
            }
         });
      if (var1.contains(var4)) {
         var4 = var5 + (Integer)var13.apply(var4 - var5);
      }

      return var4;
   }

   public abstract String type();

   @Generated
   public UUID getId() {
      return this.ORICCHCRRCIICCHIIRIHHCIOROCIHH;
   }

   @Generated
   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<T> ICHOIHIROCIHOOOCCOORRIIHRHICRO() {
      return this.IIHCOCICOOICRIHRIHCOOCIHROICRO;
   }

   @Generated
   public String getType() {
      return this.COCOOCCOHCRCCOOOORHIHCROOOHOII;
   }

   @Generated
   public boolean OIIOIHCCRCOHORCIHROIHCROROOICR() {
      return this.IORRROIOORHIORHOOCCHIHHIIHICCO;
   }

   @Generated
   public boolean isEnabled() {
      return this.enabled;
   }

   @Generated
   public void RICHIIOOOHORCHORORHIHIRRHCOOIH(boolean var1) {
      this.IORRROIOORHIORHOOCCHIHHIIHICCO = var1;
   }

   @Generated
   public void setEnabled(boolean var1) {
      this.enabled = var1;
   }
}
