package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IIHRRHORCRCROCHHOHORCHCROCIHRO;

import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap;
import it.unimi.dsi.fastutil.objects.ObjectIterator;
import java.util.Locale;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

public class RIOOCHICIHRHOHCCCCCHOCCCOHCRHI extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI HHRIIHHIOHHRIORHIRRROHRICOIROO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showItemEnchant"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI COIIOOOHIOCOHHCOHOOHIOCHIOOCIR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showBookEnchant"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IRCOCOCHICHORRICRCOIHIRHHCHRHI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showUltimateEnchant"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IRHCOOHHRHIRCRHHROCRHCHIOIROHH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showEnchant"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI HHICOIRCIIRIRRICOOCROCCOHRCRRI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showEnchantOnlyOnBook"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI ICORCRCHRIICOHOOIHHIHOIHIIRCOR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "ultimateEnchantColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-43521)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI IIIIIOCCCIIOHOCRRCCOOCHOHRCRCO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "enchantColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-11141121)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RIROICHCRROROHCCROOCCCCOCHCCRI<com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> HOOOHOORHRIOCRICIIOCHIRHOOCHCC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         "position", com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.TOP_LEFT
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final IHIRRIIORRHORHRORIHOROIRCORCOO OHORHCCCORHIRHHCROHIRORRROROOH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH("scale")
      .RROIIRROOOOHIORHRICHOCHIHCRRCH(0.6666667F)
      .CRHROHHHCIHHCOHCOORCRIHHIICROR(0.25F, 1.0F)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();

   public RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(true);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ITEMS
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI::RRRCCHIOCICOIOIRRCOOIRHHCORCIH
         )
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class,
         this::IRCIIHHICIHRCOCRROCOICRIHHCCHH
      );
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR var2 = var1.getItem();
      Object2IntOpenHashMap var3 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.IICCOOCHCHROORHHIIHROHCCRHRCOR(
         var2
      );
      if (!var3.isEmpty()) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var4 = var2.bridge$getItem();
         if (var4
            == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CIHHIHOORIIHCOORRRICHHCCRRRCHO()
               .IOCCIHRHOIRHORIRIRHOHRHIIOCRIO()) {
            if (!this.COIIOOOHIOCOHHCOHOOHIOCHIOOCIR.get()) {
               return;
            }

            String var5 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, true);
            if (var5 != null) {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5, var1);
            }
         } else {
            if (!this.HHRIIHHIOHHRIORHIRRROHRICOIROO.get()) {
               return;
            }

            String var6 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, false);
            if (var6 != null) {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, var1);
            }
         }
      }
   }

   @Nullable
   private String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Object2IntOpenHashMap<String> var1, boolean var2) {
      if (this.IRCOCOCHICHORRICRCOIHIRHHCHRHI.get()) {
         ObjectIterator var3 = var1.keySet().iterator();

         while (var3.hasNext()) {
            String var4 = (String)var3.next();
            if (var4.startsWith("ultimate_")) {
               return var4;
            }
         }
      }

      return !this.IRHCOOHHRHIRCRHHROCRHCHIOIROHH.get() || var1.size() != 1 || !var2 && this.HHICOIRCIIRIRRICOOCROCCOHRCRRI.get()
         ? null
         : (String)var1.keySet().iterator().next();
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var1,
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      Map var3 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
         )
         .<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH>RHHCIICOCRRIHOOCHHHRHICRORCCRI()
         .ORICRIRORRCHHHRRHOORHIRCICHCCO()
         .HCHRCHROOIICOIOHHIRCIIIOIIOCRH();
      if (var3 != null) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH)var3.get(
            var1.toUpperCase(Locale.ROOT)
         );
         if (var4 != null) {
            String var5 = var4.COHIOCRCIROCIHIOOOHICRIHHICHHC();
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var6 = var2.RCHHRIOCRHHIHIROCIRCRHRIOOOCOO();
            var6.push();
            float var7 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR().bridge$getStringWidth(var5);
            float var8 = this.OHORHCCCORHIRHHCROHIRORRROROOH.get();
            com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9 = this.HOOOHOORHRIOCRICIIOCHIRHOOCHCC
               .get();
            float var10 = var9
                     != com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.TOP_RIGHT
                  && var9
                     != com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BOTTOM_RIGHT
               ? 0.0F
               : 17.0F - var7 * var8;
            float var11 = var9
                     != com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BOTTOM_LEFT
                  && var9
                     != com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BOTTOM_RIGHT
               ? 0.0F
               : 10.0F;
            var6.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(var2.getX() + var10, var2.getY() + var11);
            var6.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var8, var8);
            int var12 = var4.CIRRIOOIHOHHRICCICOOCOROHCROCI()
               ? this.ICORCRCHRIICOHOOIHHIHOIHIIRCOR.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F)
               : this.IIIIIOCCCIIOHOCRRCCOOCHOHRCRCO.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F);
            var6.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR(), var5, 0, 0, var12, true);
            var6.pop();
         }
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.GENERAL,
         var1x -> {
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HHRIIHHIOHHRIORHIRRROHRICOIROO, this.COIIOOOHIOCOHHCOHOOHIOCHIOOCIR);
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.IRHCOOHHRHIRCRHHROCRHCHIOIROHH, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HHICOIRCIIRIRRICOOCROCCOHRCRRI)
            );
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IRCOCOCHICHORRICRCOIHIRHHCHRHI, this.HOOOHOORHRIOCRICIIOCHIRHOOCHCC, this.OHORHCCCORHIRHHCROHIRORRROROOH);
         }
      );
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.COLOR,
         var1x -> var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IIIIIOCCCIIOHOCRRCCOOCHOHRCRCO, this.ICORCRCHRIICOHOOIHHIHOIHIIRCOR)
      );
   }

   @Override
   public String getId() {
      return "SKYBLOCK_ENCHANT_DISPLAY";
   }
}
