package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;

public interface RIOOCHICIHRHOHCCCCCHOCCCOHCRHI<T> {
   T createInstance();
}
