package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.HashSet;
import org.joml.Vector3i;

public class CRRRICCRROCOHHOHIICIHORCOORRRH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR OHCRRHOCHRCORIOOIHOHIOOCRCIIOI = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.class
   );
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RHROOHORROCIIIHHHOIIICHHOIHCIO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "skyblockHighlightHideonleafs"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI CICRIIIRCRCHOIROOIRHIIRHOCHCRR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "skyblockHideonleafHighlightColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(2130706687)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI OCOIIHOCHCOCIRRCIHRHCRHHCROORH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "skyblockHighlightInvisibugs"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI HOROHIOCHROIHROIHHIHROHOHCCORR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "skyblockInvisibugsColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(2130771712)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HRHHHHIICCCIROOOHIIIHIHIHHHOHC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "skyblockInvisibugShowText"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HRHHIOCOCRHHCHHROHRIIOOCICIICO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "skyblockHighlightMudworms"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI CHCRRRHHRCCRHCCCCRROHHRICICROO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "skyblockMudwormColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(2147467467)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO<CORCOCICIRIOHROHROIIOOHICCHCRR> OIOIRRIOHOIRCHRCRCIRCOOOCOCHOR = this.OHCRRHOCHRCORIOOIHOHIOOCRCIIOI
      .CCIOIIOHRCIHOIROCRORORCHHORHRO()
      .HICRRICCHCCROOHHCHOCOCCHOIHHOC(CORCOCICIRIOHROHROIIOOHICCHCRR.class)
      .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, this.RHROOHORROCIIIHHHOIIICHHOIHCIO::get);
   private final HashSet<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> CIHIRCIHRHIRHCOOHRICRIRIHIRHCH = new HashSet<>();
   private final HashSet<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> HIOCIRRHOHCRORHHHHOICIHHRHIOHH = new HashSet<>();
   private final HashSet<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> RRRRIIIRRHICCCOOOORHROHRHOOCRC = new HashSet<>();
   private final HashSet<Vector3i> COICIRIRIHIIIOIHOIRCOCRHCOHICH = new HashSet<>();

   public CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FORAGING
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this,
            () -> com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
                  == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.GALATEA
               || com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
                  == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.TORRHUS_CANYON
               || com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
                  == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.SAFARI
         )
      );
      this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(this::onDisable);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.class,
         this::HICHRCOHCCRHOHCICOOCHOIHCCHIRI
      );
      this.handle(IIRHCHHOICHRICOOCRORCCIOOIHOIR.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.handle(IHIRRIIORRHORHRORIHOROIRCORCOO.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class,
         var1x -> {
            this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(var1x);
            this.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1x);
            this.IIHRRHORCRCROCHHOHORCHCROCIHRO(var1x);
         }
      );
      this.handle(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
   }

   private void onDisable() {
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH((RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH)null);
   }

   private void HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1
   ) {
      if (this.HRHHIOCOCRHHCHHROHRIIOOCICIICO.get()) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var2 = var1.OCOIORCRROIOOCHORHHHROCHCCIHRR;
         if (var2 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var3
            )
          {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR var4 = var3.bridge$getItemStack();
            if (var4 == null || var4.bridge$isEmpty()) {
               return;
            }

            if (var4.bridge$getItem()
               != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CIHHIHOORIIHCOORRRICHHCCRRRCHO()
                  .ICHOCHHROIHCROICCIRIHHCHRHROCO()) {
               return;
            }

            this.COICIRIRIHIIIOIHOIRCOCRHCOHICH.add(var2.bridge$getBlockPos().bridge$toJoml());
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var2 = var1.HCICROIHRHRCORRHCOIHIHCCCCHRHH();
      if (var2 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH
         )
       {
         this.COICIRIRIHIIIOIHOIRCOCRHCOHICH.remove(var2.bridge$getBlockPos().bridge$toJoml());
      } else if (var2 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
         )
       {
         this.CIHIRCIHRHIRHCOOHRICRIRIHIRHCH.remove(var2);
         this.HIOCIRRHOHCRORHHHHOICIHHRHIOHH.remove(var2);
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IHIRRIIORRHORHRORIHOROIRCORCOO var1) {
      if (this.OCOIIHOCHCOCIRRCIHRHCRHHCROORH.get()) {
         if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
            == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.GALATEA
            )
          {
            if (var1.ICRCIIIHROCRHOHHHHRCCCOOCICHOO()
               == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRIT
               )
             {
               double var2 = var1.ICIHOIHROICHIHRIIOOCHOCCOHRIRR();
               double var4 = var1.HRRIHICRHIHCCOIRIOROIHOHRHCOHI();
               double var6 = var1.IIOCRCOCCHCIOCCORROCIRHOICIICR();
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
                  var2, var4, var6, var2, var4, var6
               );

               for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var11 : IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH()
                  .bridge$getEntities(
                     var8.OCOHORHCROHICRRIHCIHHRRCIHICRI(0.5, 1.0, 0.5),
                     var0 -> var0 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
                  )) {
                  if (!this.RRRRIIIRRHICCCOOOORHROHRHOOCRC.contains(var11) && !this.HIOCIRRHOHCRORHHHHOICIHHRHIOHH.contains(var11)) {
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var12 = (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var11;
                     if (var12.bridge$getCustomName() == null
                        && this.OHCIIOCHHOHOHCOHHCRRHHCRHOIICC(var12.bridge$getHelmet())
                        && this.OHCIIOCHHOHOHCOHHCRRHHCRHOIICC(var12.bridge$getChestplate())
                        && this.OHCIIOCHHOHOHCOHHCRRHHCRHOIICC(var12.bridge$getLeggings())
                        && this.OHCIIOCHHOHOHCOHHCRRHHCRHOIICC(var12.bridge$getBoots())) {
                        this.CIHIRCIHRHIRHCOOHRICRIRIHIRHCH.add(var11);
                        return;
                     }
                  }
               }
            }
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOIICIRIICICIIOORHCIIIIRRIHRHI var1) {
      if (this.OCOIIHOCHCOCIRRCIHRHCRHHCROORH.get()) {
         if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
            == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.GALATEA
            )
          {
            if (!this.CIHIRCIHRHIRHCOOHRICRIRIHIRHCH.isEmpty()) {
               this.HIOCIRRHOHCRORHHHHOICIHHRHIOHH.removeIf(var1x -> {
                  if (this.HCHRIROHHHCORIOCROOCHRCIOROOCI(var1x) && var1x.bridge$getPosY() != var1x.bridge$lastTickY()) {
                     this.RRRRIIIRRHICCCOOOORHROHRHOOCRC.add(var1x);
                     return true;
                  } else {
                     return false;
                  }
               });
               this.CIHIRCIHRHIRHCOOHRICRIRIHIRHCH.removeIf(var1x -> {
                  if (this.HCHRIROHHHCORIOCROOCHRCIOROOCI(var1x)) {
                     if (var1x.bridge$getPosY() == var1x.bridge$lastTickY()) {
                        this.HIOCIRRHOHCRORHHHHOICIHHRHIOHH.add(var1x);
                     } else {
                        this.RRRRIIIRRHICCCOOOORHROHRHOOCRC.add(var1x);
                     }

                     return true;
                  } else {
                     return false;
                  }
               });
            }
         }
      }
   }

   private void CRICCOOHHHCHOORCICOCOHIHOIRHOO(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      if (this.RHROOHORROCIIIHHHOIIICHHOIHCIO.get()) {
         if (!this.OIOIRRIOHOIRCHRCRCIRCOOOCOCHOR.isEmpty()) {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var2 = var1.HHIIOHOORHHCCHRHHRCIORCROORCOI();
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IHRHHIOIIICOROOORIOHCIROIRCOHH();
            var2.push();
            var2.translate(-var3.bridge$renderPosX(), -var3.bridge$renderPosY(), -var3.bridge$renderPosZ());
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH var4 = var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HCCCRCCCOOCROOHRCHCRIHHRHHOHHC
            );
            var4.HICHHHOOCRROHCCCCOOHOCHHOIOHCR();

            for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var6 : this.OIOIRRIOHOIRCHRCRCIRCOOOCOCHOR) {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = var6.OHHRIOHROOIHOROCIRHCHORIHRRRRI(
                  var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR()
               );
               CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var4,
                  var7.bridge$getMinX() - 0.01,
                  var7.bridge$getMinY() - 0.01,
                  var7.bridge$getMinZ() - 0.01,
                  var7.bridge$getMaxX() + 0.01,
                  var7.bridge$getMaxY() + 0.01,
                  var7.bridge$getMaxZ() + 0.01,
                  this.CICRIIIRCRCHOIROOIRHIIRHOCHCRR.OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F)
               );
            }

            var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.BATCHED
            );
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var10 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
                  HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
               )
               .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var11 = var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               var10.CHICCHOOCRHHRIHOHRCICCOOOIHHII().get()
            );

            for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var8 : this.OIOIRRIOHOIRCHRCRCIRCOOOCOCHOR) {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9 = var8.OHHRIOHROOIHOROCIRHCHORIHRRRRI(
                  var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR()
               );
               CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var11,
                  var9.bridge$getMinX() - 0.01,
                  var9.bridge$getMinY() - 0.01,
                  var9.bridge$getMinZ() - 0.01,
                  var9.bridge$getMaxX() + 0.01,
                  var9.bridge$getMaxY() + 0.01,
                  var9.bridge$getMaxZ() + 0.01,
                  com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI.ICORRRIOCIIRICCCOIHCRRIORHOIIC(
                     this.CICRIIIRCRCHOIROOIRHIIRHOCHCRR.OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F)
                  )
               );
            }

            var11.end();
            var2.pop();
         }
      }
   }

   private void HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      if (this.OCOIIHOCHCOCIRRCIHRHCRHHCROORH.get()) {
         if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
            == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.GALATEA
            )
          {
            if (!this.HIOCIRRHOHCRORHHHHOICIHHRHIOHH.isEmpty()) {
               float var2 = var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR();
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var3 = var1.HHIIOHOORHHCCHRHHRCIORCROORCOI();
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IHRHHIOIIICOROOORIOHCIROIRCOHH();
               var3.push();
               var3.translate(-var4.bridge$renderPosX(), -var4.bridge$renderPosY(), -var4.bridge$renderPosZ());
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH var5 = var3.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HCCCRCCCOOCROOHRCHCRIHHRHHOHHC
               );
               var5.HICHHHOOCRROHCCCCOOHOCHHOIOHCR();

               for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var7 : this.HIOCIRRHOHCRORHHHHOICIHHRHIOHH) {
                  double var8 = var7.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var2);
                  double var10 = var7.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2);
                  double var12 = var7.IIRHCHHOICHRICOOCRORCCIOOIHOIR(var2);
                  CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var5,
                     var8 - 0.5,
                     var10 + 0.3,
                     var12 - 0.5,
                     var8 + 0.5,
                     var10 + 1.3,
                     var12 + 0.5,
                     this.HOROHIOCHROIHROIHHIHROHOHCCORR.OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F)
                  );
               }

               var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.BATCHED
               );
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var16 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
                     HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
                  )
                  .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var17 = var3.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  var16.CHICCHOOCRHHRIHOHRCICCOOOIHHII().get()
               );

               for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var9 : this.HIOCIRRHOHCRORHHHHOICIHHRHIOHH) {
                  double var21 = var9.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var2);
                  double var23 = var9.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2);
                  double var14 = var9.IIRHCHHOICHRICOOCRORCCIOOIHOIR(var2);
                  CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var17,
                     var21 - 0.5,
                     var23 + 0.3,
                     var14 - 0.5,
                     var21 + 0.5,
                     var23 + 1.3,
                     var14 + 0.5,
                     this.HOROHIOCHROIHROIHHIHROHOHCCORR.OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F)
                  );
               }

               var17.end();
               if (this.HRHHHHIICCCIROOOHIIIHIHIHHHOHC.get()) {
                  for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var20 : this.HIOCIRRHOHCRORHHHHOICIHHRHIOHH) {
                     double var22 = var20.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var2);
                     double var24 = var20.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2);
                     double var25 = var20.IIRHCHHOICHRICOOCRORCCIOOIHOIR(var2);
                     CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, "Invisibug", var22, var24 + 1.8, var25, -1, true);
                  }
               }

               var3.pop();
            }
         }
      }
   }

   private void IIHRRHORCRCROCHHOHORCHCROCIHRO(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      if (this.HRHHIOCOCRHHCHHROHRIIOOCICIICO.get()) {
         if (!this.COICIRIRIHIIIOIHOIRCOCRHCOHICH.isEmpty()) {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var2 = var1.HHIIOHOORHHCCHRHHRCIORCROORCOI();
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IHRHHIOIIICOROOORIOHCIROIRCOHH();
            var2.push();
            var2.translate(-var3.bridge$renderPosX(), -var3.bridge$renderPosY(), -var3.bridge$renderPosZ());
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH var4 = var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HCCCRCCCOOCROOHRCHCRIHHRHHOHHC
            );
            var4.HICHHHOOCRROHCCCCOOHOCHHOIOHCR();

            for (Vector3i var6 : this.COICIRIRIHIIIOIHOIRCOCRHCOHICH) {
               int var7 = var6.x();
               int var8 = var6.y();
               int var9 = var6.z();
               CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var4,
                  var7 - 0.01,
                  var8 - 0.01,
                  var9 - 0.01,
                  var7 + 1.01,
                  var8 + 1.01,
                  var9 + 1.01,
                  this.CHCRRRHHRCCRHCCCCRROHHRICICROO.OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F)
               );
            }

            var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.BATCHED
            );
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var12 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
                  HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
               )
               .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var13 = var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               var12.CHICCHOOCRHHRIHOHRCICCOOOIHHII().get()
            );

            for (Vector3i var15 : this.COICIRIRIHIIIOIHOIRCOCRHCOHICH) {
               int var16 = var15.x();
               int var10 = var15.y();
               int var11 = var15.z();
               CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var13,
                  var16 - 0.01,
                  var10 - 0.01,
                  var11 - 0.01,
                  var16 + 1.01,
                  var10 + 1.01,
                  var11 + 1.01,
                  this.CHCRRRHHRCCRHCCCCRROHHRICICROO.OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F)
               );
            }

            var13.end();
            var2.pop();
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.CIHIRCIHRHIRHCOOHRICRIRIHIRHCH.clear();
      this.HIOCIRRHOHCRORHHHHOICIHHRHIOHH.clear();
      this.RRRRIIIRRHICCCOOOORHROHRHOOCRC.clear();
      this.COICIRIRIHIIIOIHOIRCOCRHCOHICH.clear();
   }

   private boolean OHCIIOCHHOHOHCOHHCRRHHCRHOIICC(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR var1
   ) {
      return var1 == null || var1.bridge$isEmpty();
   }

   private boolean HCHRIROHHHCORIOCROOCHRCIOROOCI(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      return var1.bridge$getPosX() != var1.bridge$lastTickX()
         || var1.bridge$getPosY() != var1.bridge$lastTickY()
         || var1.bridge$getPosZ() != var1.bridge$lastTickZ();
   }

   @Override
   public String getId() {
      return "SKYBLOCK_GALATEA_MOB_HIGHLIGHT";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.GENERAL,
         var1x -> {
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RHROOHORROCIIIHHHOIIICHHOIHCIO, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CICRIIIRCRCHOIROOIRHIIRHOCHCRR)
            );
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.OCOIIHOCHCOCIRRCIHRHCRHHCROORH,
               var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HOROHIOCHROIHROIHHIHROHOHCCORR, this.HRHHHHIICCCIROOOHIIIHIHIHHHOHC)
            );
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.HRHHIOCOCRHHCHHROHRIIOOCICIICO, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CHCRRRHHRCCRHCCCCRROHHRICICROO)
            );
         }
      );
   }

   @Override
   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ORIRHOHRHHROCHHRRIOOCRIHRIIIOC() {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIICCCRRHHCHRRHRIRCHOICCHROHCR()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCOCHOCIRORHHORHCROHOIOCRCHIO
         )
         .HRCHROOHRIHCRCRHRIIROCIRHOIRHH("mudworm highlight")
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO(this);
   }
}
