package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;
import com.moonsworth.lunar.client.util.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH;
import com.moonsworth.lunar.lib.adventure.text.Component;
import com.moonsworth.lunar.lib.adventure.text.TextComponent;
import com.moonsworth.lunar.lib.adventure.text.format.NamedTextColor;
import java.util.List;
import java.util.Optional;
import org.jetbrains.annotations.Nullable;

public class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH HRIICOORCCCHHOCICCHCCHHRHORHHC = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class
   );

   public HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FORAGING
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI::RRRCCHIOCICOIOIRRCOOIRHHCORCIH
         )
      );
      this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOIICIRIICICIIOORHCIIIIRRIHRHI var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      if (var2 != null && var3 != null) {
         IIRHCHHOICHRICOOCRORCCIOOIHOIR var4 = var2.bridge$getCurrentEquippedItem();
         String var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.CHHIICHRIIROIOHIHIIROICOCCROCI(
            var4
         );
         if (var5 != null) {
            if (var5.endsWith("_LASSO")) {
               this.RICHCORHRIHHIIHHCORHICOCCOIROH()
                  .ifPresent(
                     var1x -> {
                        com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2x = this.OHIIIOHIRIRCCRRIOIICCHHIORRHOH(
                           var1x
                        );
                        if (var2x != null) {
                           Component var3x = ((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH)var2x.OHICIOOICHICOIOCOROIIOCCHRRCIC)
                              .bridge$getCustomName();
                           if ((Float)var2x.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC >= 100.0F) {
                              this.HRIICOORCCCHHOCICCHCCHHRHORHHC
                                 .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                    com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOHRCCHICIICCOHHCHCHOOCCOCICC()
                                       .OOIRCOCROHROCRHRICCHIHORHROHII("FORAGING_LASSO_PRIMARY")
                                       .RICRIRRCOHRCOCRRHHCRHRROOIOHHR(Component.text("      REEL      ", NamedTextColor.GOLD))
                                       .RHCHRCOCCOIIIHCHRHIRCORHRHRICR(100L)
                                       .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                          com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HIGH
                                       )
                                       .HICRRCCIRRICIHOORRHRROHCIROIRI()
                                 );
                              this.HRIICOORCCCHHOCICCHCCHHRHORHHC
                                 .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                    com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOHRCCHICIICCOHHCHCHOOCCOCICC()
                                       .OOIRCOCROHROCRHRICCHIHORHROHII("FORAGING_LASSO_SECONDARY")
                                       .RICRIRRCOHRCOCRRHHCRHRROOIOHHR(var3x)
                                       .RHCHRCOCCOIIIHCHRHIRCORHRHRICR(100L)
                                       .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                          com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.LOW
                                       )
                                       .HICRRCCIRRICIHOORRHRROHCIROIRI()
                                 );
                           } else {
                              this.HRIICOORCCCHHOCICCHCCHHRHORHHC
                                 .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                    com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOHRCCHICIICCOHHCHCHOOCCOCICC()
                                       .OOIRCOCROHROCRHRICCHIHORHROHII("FORAGING_LASSO_PRIMARY")
                                       .RICRIRRCOHRCOCRRHHCRHRROOIOHHR(
                                          Component.text("          (" + Math.round((Float)var2x.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC) + "%)          ")
                                       )
                                       .RHCHRCOCCOIIIHCHRHIRCORHRHRICR(100L)
                                       .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                          com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HIGH
                                       )
                                       .HICRRCCIRRICIHOORRHRROHCIROIRI()
                                 );
                              this.HRIICOORCCCHHOCICCHCCHHRHORHHC
                                 .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                    com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOHRCCHICIICCOHHCHCHOOCCOCICC()
                                       .OOIRCOCROHROCRHRICCHIHORHROHII("FORAGING_LASSO_SECONDARY")
                                       .RICRIRRCOHRCOCRRHHCRHRROOIOHHR(var3x)
                                       .RHCHRCOCCOIIIHCHRHIRCORHRHRICR(100L)
                                       .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                          com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.LOW
                                       )
                                       .HICRRCCIRRICIHOORRHRROHCIROIRI()
                                 );
                           }
                        }
                     }
                  );
            }
         }
      }
   }

   @Nullable
   private RRCRRCORICCHOHHIRCHIROOHIIOHCO<CRRRICCRROCOHHOHIICIHORCOORRRH, Float> OHIIIOHIRIRCCRRIOIICCHHIORRHOH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var3 : IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH()
         .bridge$getEntities()) {
         if (!(var3.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(var1.bridge$getPosX(), var3.bridge$getPosY(), var1.bridge$getPosZ()) > 9.0)
            && RHRIIOOOCRHIIOORCOCRCHRCCRRCIH.IHICORCROOROHCIHIHCOIHRRHICICO(var3.bridge$getPosY(), var1.bridge$getPosY(), 6.0)) {
            Component var4 = var3.bridge$getCustomName();
            if (var4 != null) {
               Float var5 = this.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var4);
               if (var5 != null) {
                  return com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORCOCORROHIROCCIORORRRRCHIOOCH(
                     var3, var5
                  );
               }
            }
         }
      }

      return null;
   }

   public Optional<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> RICHCORHRIHHIIHHCORHICOCCOIROH() {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH()
         .bridge$getEntities()
         .stream()
         .filter(var1x -> var1x.bridge$isLeashed() && var1x.bridge$getLeashedToEntity() == var1)
         .findAny();
   }

   @Nullable
   public Float OHHRIOHROOIHOROCIRHCHORIHRRRRI(Component var1) {
      if (var1 instanceof TextComponent var2) {
         if (!var2.content().isEmpty()) {
            return null;
         }

         List var3 = var1.children();
         if (var3.size() != 2) {
            return null;
         }

         Component var4 = (Component)var3.get(0);
         Component var5 = (Component)var3.get(1);
         if (var4 instanceof TextComponent var6) {
            if (var5 instanceof TextComponent var7) {
               if (!var6.content().isBlank()) {
                  return null;
               }

               if (!var7.content().isBlank()) {
                  return null;
               }

               float var8 = var7.content().length() * 100.0F / (var7.content().length() + var6.content().length());
               var8 *= 1.1111112F;
               return Math.min(100.0F, var8);
            } else {
               return null;
            }
         } else {
            return null;
         }
      } else {
         return null;
      }
   }

   @OIHCOHRCICCCRHRCROOCIOIRRHHHIH
   @Override
   public String getId() {
      return "SKYBLOCK_LASSO_HELPER";
   }

   @Override
   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ORIRHOHRHHROCHHRRIOOCRIHRIIIOC() {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIICCCRRHHCHRRHRIRCHOICCHROHCR()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCOCHOCIRORHHORHCROHOIOCRCHIO
         )
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO(this);
   }
}
