package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.lib.adventure.text.Component;
import com.moonsworth.lunar.lib.adventure.text.format.NamedTextColor;
import com.moonsworth.lunar.lib.adventure.text.format.TextColor;
import it.unimi.dsi.fastutil.ints.Int2IntMap;
import it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap;
import java.util.List;
import org.jspecify.annotations.Nullable;

public class RIOOCHICIHRHOHCCCCCHOCCCOHCRHI extends IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private static final String HRRRICIIOORRCHCOORHOOHCRORIHCO = "•";
   private final Int2IntMap RICRHROIHRCRRHOHIRCIRRIOCCCOIR = new Int2IntOpenHashMap();
   private RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.@Nullable RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HHHCROCRCHHOHIICIIOHROIHCCCCOH;

   public RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      ORHIOICIOCRRHOOCOHRORIHICHRCRR var1, com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2
   ) {
      super(
         var1,
         var2,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.TERMINAL_MATCH_COLOR
      );
      this.handle(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         var1x -> this.HHHCROCRCHHOHIICIIOHROIHCCCCOH = null
      );
   }

   @Override
   public String getId() {
      return "SKYBLOCK_MATCH_COLORS";
   }

   @Override
   protected void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      String var1,
      List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> var2
   ) {
      this.RICRHROIHRCRRHOHIRCIRRIOCCCOIR.clear();
      if (this.HHHCROCRCHHOHIICIIOHROIHCCCCOH == null) {
         this.HHHCROCRCHHOHIICIIOHROIHCCCCOH = RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(var2);
      }

      if (this.HHHCROCRCHHOHIICIIOHROIHCCCCOH != null) {
         for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 : var2) {
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.colorOf(
               var4.HCHIHOIROHHIIRCIRORRRCORHOORCC()
            );
            if (var5 != null) {
               this.RICRHROIHRCRRHOHIRCIRRIOCCCOIR.put(var4.index(), this.HHHCROCRCHHOHIICIIOHROIHCCCCOH.getDistance(var5));
            }
         }
      }
   }

   @Override
   protected boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1, boolean var2
   ) {
      int var3 = var1.bridge$getIndex();
      if (!this.RICRHROIHRCRRHOHIRCIRRIOCCCOIR.containsKey(var3)) {
         return true;
      }

      int var4 = this.RICRHROIHRCRRHOHIRCIRRIOCCCOIR.get(var3);
      return var4 == 0 ? false : var2 == var4 < 0;
   }

   @Override
   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      boolean var2
   ) {
      RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.colorOf(
         var1.HCHIHOIROHHIIRCIRORRRCORHOORCC()
      );
      return var3 == null ? var1 : var1.CRRRICCRROCOHHOHIICIHORCOORRRH(var3.step(var2 ? -1 : 1).toItemColor());
   }

   @Override
   protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, int var2) {
      if (this.RICRHROIHRCRRHOHIRCIRRIOCCCOIR.containsKey(var2)) {
         this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      }
   }

   @Override
   protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1, int var2) {
      if (this.RICRHROIHRCRRHOHIRCIRRIOCCCOIR.containsKey(var2)) {
         int var3 = this.RICRHROIHRCRRHOHIRCIRRIOCCCOIR.get(var2);
         if (this.ORCORCRRIRIROIORRCCCCHRHRCOHOH(var2)) {
            String var4 = var3 == 0 ? "•" : this.RHCICHRICRIIIHRRCICHOOOIOOOICH(var3);
            var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Component.text(var4, this.COOIOICCIIRROICCORCOCCHICCIHOH()));
         } else if (var3 != 0) {
            var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Component.text(this.RHCICHRICRIIIHRRCICHOOOIOOOICH(var3), this.HIORIIIIOCCCRCHCOROROCCOIOOIIR(var3)));
         }
      }
   }

   private String RHCICHRICRIIIHRRCICHOOOIOOOICH(int var1) {
      if (!this.CIRCHRIHOCCHRORCRHOOCHCCCIHICH().OCROCRRRHHCIICHOHCHRCCRRCCHHRR().get()) {
         return Integer.toString(var1);
      }

      return switch (var1) {
         case -2 -> ">>";
         case -1 -> ">";
         default -> Integer.toString(var1);
         case 1 -> "<";
         case 2 -> "<<";
      };
   }

   private @Nullable TextColor HIORIIIIOCCCRCHCOROROCCOIOOIIR(int var1) {
      if (!this.RIORORCRCCCHOHHOCHHHOCIIOCRORH()) {
         return null;
      } else {
         return var1 > 0 ? NamedTextColor.GREEN : NamedTextColor.RED;
      }
   }

   private static RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.@Nullable RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(
      List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> var0
   ) {
      int[] var1 = new int[RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.values().length];

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 : var0) {
         RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.colorOf(
            var3.HCHIHOIROHHIIRCIRORRRCORHOORCC()
         );
         if (var4 != null) {
            var1[var4.ordinal()]++;
         }
      }

      RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = null;

      for (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 : RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.values()) {
         if (var1[var6.ordinal()] > 0 && (var7 == null || var1[var6.ordinal()] > var1[var7.ordinal()])) {
            var7 = var6;
         }
      }

      return var7;
   }

   private enum RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      RED,
      ORANGE,
      YELLOW,
      GREEN,
      BLUE;

      private static RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.@Nullable RCIRROCCCIIHCIHCCRHHCCHOHHHCHH colorOf(
         CRRRICCRROCOHHOHIICIHORCOORRRH.@Nullable RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0
      ) {
         if (var0 == null) {
            return null;
         }

         try {
            return valueOf(var0.name());
         } catch (IllegalArgumentException var2) {
            return null;
         }
      }

      private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH toItemColor() {
         return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.valueOf(
            this.name()
         );
      }

      private RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH step(int var1) {
         RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH[] var2 = values();
         return var2[Math.floorMod(this.ordinal() + var1, var2.length)];
      }

      private int getDistance(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1) {
         int var2 = this.ordinal() - var1.ordinal();
         if (var2 >= 3) {
            var2 -= 5;
         } else if (var2 <= -3) {
            var2 += 5;
         }

         return var2;
      }
   }
}
