package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import lombok.Generated;

@com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 33)
public final class IRCIIHHICIHRCOCRROCOICRIHHCCHH
   implements com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   private final RIOOCHICIHRHOHCCCCCHOCCCOHCRHI COORHHOIICIHRRORCRORRRIOCIICHH;
   private final HHCCIRHCCCIIRHCROHIORHIRHHIORH RRRRORHRHHHCCIHOIOROCCCRHHOOCO;

   @Override
   public void IHICIORCCHIOORROOIROHHCIRCCIIC(String var1) {
   }

   @Override
   public void OCRIIICORRROHHHROCRRORCCRHIICC(String var1) {
      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HHCCIRORCRCHOIOHRRIRRRIORRCRRR().HRIIIOIIRHOHORIRICIOIORRIRCHHO();
   }

   @Override
   public boolean IIRHHRRRCOHHOOHIIOOIOICROORORC(String var1) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2 = this.RRRRORHRHHHCCIHOIOROCCCRHHOOCO
         .RIOOHRIICCHHHIOCHHRCCHIRHHHORC(var1)
         .orElse(null);
      if (var2 == null) {
         return false;
      }

      IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
         .bridge$displayScreen(
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(new RRCRRCORICCHOHHIRCHIROOHIIOHCO(this.COORHHOIICIHRRORCRORRRIOCIICHH, var2))
         );
      return true;
   }

   @Override
   public void OHCCRIOOIICRHRIRROOOORROCRHIHR(String var1) {
      this.RRRRORHRHHHCCIHOIOROCCCRHHOOCO.RIOOHRIICCHHHIOCHHRCCHIRHHHORC(var1).ifPresent(var0 -> {
         HHCCIRHCCCIIRHCROHIORHIRHHIORH.OIIIHRCICHOHCHHCIOIRCRIIOHRRHI().remove(var0);
         IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HHCCIRORCRCHOIOHRRIRRRIORRCRRR().HRIIIOIIRHOHORIRICIOIORRIRCHHO();
      });
   }

   @Generated
   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var1, HHCCIRHCCCIIRHCROHIORHIRHHIORH var2) {
      this.COORHHOIICIHRRORCRORRRIOCIICHH = var1;
      this.RRRRORHRHHHCCIHOIOROCCCRHHOOCO = var2;
   }
}
