package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.Arrays;
import java.util.List;

public class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private static final RCIROOOOICRHCCRRCIORHHIRCOIIIC HHOIIRIOIRHHHRIICOCIRROOOCCRIC = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "textures/gui/container/inventory.png"
   );
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI CIOROIOOICORCHHRCCHRHCHHHIOCHO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("mcBackground")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI CHOCCOOIIHROROOROICHOICCHICIOR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("showEmpty")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RCCICHORCOOICCCHICHRIOIIHIICCC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("background")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RIORCOOHRIRICOCCRCRIIOOHHIHCOH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("grid")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI HROHHOOOIOCOIHORRIOIHIRHIIIOCO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("gridColor")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(Integer.MIN_VALUE)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI ICHOCCIICCCHCCRCICROOHCORCOOOC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "backgroundColor"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI OHIRRCOOHHHIHIOHIRHHOIOHORHHRI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("color")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-1)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final IIRHCHHOICHRICOOCRORCCIOOIHOIR[] ROCOROHRRIOCOCHRHHOHIRHOIICIRH = new IIRHCHHOICHRICOOCRORCCIOOIHOIR[27];
   private boolean IIIIRRICCHRHOIIHRRIHOIHRHRICOC = true;

   public HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO, new HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
      );
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::ORCOOCHRICHOIHHIHIOHCHCRIOHRCR);
   }

   @Override
   public String getId() {
      return "INVENTORY_HUD";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CHOCCOOIIHROROOROICHOICCHICIOR);
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.RCCICHORCOOICCCHICHRIOIIHIICCC,
         var1x -> {
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CIOROIOOICORCHHRCCHRHCHHHIOCHO);
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  this.RIORCOOHRIRICOCCRCRIIOOHHIHCOH, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HROHHOOOIOCOIHORRIOIHIRHIIIOCO)
               )
               .IIHRRHORCRCROCHHOHORCHCROCIHRO(this.CIOROIOOICORCHHRCCHRHCHHHIOCHO::get);
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.ICHOCCIICCCHCCRCICROOHCORCOOOC, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.OHIRRCOOHHHIHIOHIRHHOIOHORHHRI)
            );
         }
      );
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
         this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO).OOOICCOOHRHIIHHRRHHHROCCHCORRO()
      );
   }

   private void ORCOOCHRICHOIHHIHIOHCHCRIOHRCR() {
      if (this.mc.bridge$getPlayer() != null && this.mc.bridge$getPlayer().bridge$getInventory() != null) {
         List var1 = this.mc.bridge$getPlayer().bridge$getInventory().bridge$getMainInventory();
         this.IIIIRRICCHRHOIIHRRIHOIHRHRICOC = true;

         for (int var2 = 9; var2 < var1.size(); var2++) {
            IIRHCHHOICHRICOOCRORCCIOOIHOIR var3 = (IIRHCHHOICHRICOOCRORCCIOOIHOIR)var1.get(var2);
            if (var3 != null && (var3.bridge$isEmpty() || var3.bridge$getStackSize() < 1)) {
               var3 = null;
            }

            this.ROCOROHRRIOCOCHRHHOHIRHOIICIRH[var2 - 9] = var3;
            if (var3 != null) {
               this.IIIIRRICCHRHOIIHRRIHOIHRHRICOC = false;
            }
         }
      } else {
         Arrays.fill(this.ROCOROHRRIOCOCHRHHOHIRHOIICIRH, null);
         this.IIIIRRICCHRHOIIHRRIHOIHRHRICOC = true;
      }
   }

   private class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
         super(0.0F, 0.0F, com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.TOP_LEFT);
      }

      @Override
      public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
         float var2,
         float var3,
         boolean var4
      ) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = var1.RCHHRIOCRHHIHIROCIRCRHRIOOOCOO();
         var5.push();
         var5.CRICCOOHHHCHOORCICOCOHIHOIRHOO(Math.round(var2), Math.round(var3), 0.0F);
         if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.RCCICHORCOOICCCHICHRIOIIHIICCC.get()) {
            float var6 = this.getWidth();
            float var7 = this.getHeight();
            if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.CIOROIOOICORCHHRCCHRHCHHHIOCHO.get()) {
               this.OCOHORHCROHICRRIHCIHHRRCIHICRI(var5, var6, var7);
            } else {
               int var8 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.ICHOCCIICCCHCCRCICROOHCORCOOOC.get()
                  ? HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.OHIRRCOOHHHIHIOHIRHHOIOHORHHRI.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F)
                  : Integer.MIN_VALUE;
               com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                  var5, 0.0F, 0.0F, var6, var7, var8
               );
               if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.RIORCOOHRIRICOCCRCRIIOOHHIHCOH.get()) {
                  int var9 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HROHHOOOIOCOIHORRIOIHIRHIIIOCO.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F);
                  float var10 = 317.5F;
                  com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                     var5, 2.0F, var10, 36.0F, var9
                  );
                  com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                     var5, 2.0F, var10, var7 - 36.0F, var9
                  );

                  for (int var11 = 1; var11 < 9; var11++) {
                     com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH(
                        var5, var11 * 35.5F, 2.0F, var7 - 2.0F, var9
                     );
                  }
               }
            }
         }

         if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.IIIIRRICCHRHOIIHRRIHOIHRHRICOC) {
            var5.pop();
         } else {
            for (int var15 = 0; var15 < HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.ROCOROHRRIOCOCHRHHOHIRHOIICIRH.length; var15++) {
               IIRHCHHOICHRICOOCRORCCIOOIHOIR var16 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.ROCOROHRRIOCOCHRHHOHIRHOIICIRH[var15];
               if (var16 != null && !var16.bridge$isEmpty() && var16.bridge$getStackSize() >= 1) {
                  var5.push();

                  try {
                     int var17 = var15 % 9;
                     int var18 = var15 / 9;
                     var5.scale(2.0F, 2.0F, 1.0F);
                     var5.CRICCOOHHHCHOORCICOCOHIHOIRHOO(1.0F + var17 * 17.75F, 0.5F + var18 * 18.0F, 0.0F);
                     var5.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        var0 -> {
                           var0.HHIIOHOORHHCCHRHHRCIORCROORCOI().HIOCCRCCCRICORCIIHHRIRROICHRIC();
                           com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROIHROCROORRCCOIRRIHHORCROOORO()
                              .HOORHCHOCROIIROICHOORROHCOOCCI();
                        }
                     );
                     var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var16, 0, 0, true, IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI());
                     var5.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        var0 -> {
                           com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROIHROCROORRCCOIRRIHHORCROOORO()
                              .RIOIHHOROOOHRHCIIHOORROCCICIRI();
                           var0.HHIIOHOORHHCCHRHHRCIORCROORCOI().IHCICHIIIHORHRIICHOHOHHOCHRORO();
                           var0.HHIIOHOORHHCCHRHHRCIORCROORCOI().ROORHICROORIRHCCOOHORCCICRIORO();
                        }
                     );
                  } finally {
                     var5.pop();
                  }
               }
            }

            var5.pop();
         }
      }

      private void OCOHORHCROHICRRIHCIHHRRCIHICRI(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         float var2,
         float var3
      ) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IIOCHOIICCIORCOROIROHICCHIOHIC.RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
            .HOORIHHORRRRHCIRCIHCCCRRCCICIR();
         if (!var4.CHHRRIICRCCRCCHOORHHOOICCROCII()) {
            this.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1, var2, var3);
         } else {
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IIOCHOIICCIORCOROIROHICCHIOHIC.CRRRICCRROCOHHOHIICIHORCOORRRH.RHRCRCIOIOICRHRCCROIICCRRCOOOI(
               var4.COOHOIRCOIRRRHICRIRHHCORRHRIOR()
            );

            try {
               this.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1, var2, var3);
            } finally {
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IIOCHOIICCIORCOROIROHICCHIOHIC.CRRRICCRROCOHHOHIICIHORCOORRRH.CCIIOOICCOIRIOOOCRHCHRRIOCRHIC();
            }
         }
      }

      private void CIOHHCORHRCCRICCCORIHCRHCCCRRR(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         float var2,
         float var3
      ) {
         int var4 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.ICHOCCIICCCHCCRCICROOHCORCOOOC.get()
            ? HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.OHIRRCOOHHHIHIOHIRHHOIOHORHHRI.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F)
            : -570425345;
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION < 30) {
            var4 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IIOCHOIICCIORCOROIROHICCHIOHIC.CRRRICCRROCOHHOHIICIHORCOORRRH.HORHCHIIOCRROHOHRCORCCICCRCCHO(
               var4
            );
         }

         var1.push();
         var1.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var2 / 162.0F, var3 / 54.0F);
         var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHOIIRIOIRHHHRIICOCIRROOOCCRIC, 0.0F, 0.0F, 7.0F, 83.0F, 162.0F, 54.0F, 256.0F, 256.0F, var4
         );
         var1.pop();
      }

      @Override
      public boolean OIHRCOHICIOHHHHRRHRIHORCIIIORO() {
         return false;
      }

      @Override
      public boolean ORCOCORROHIROCCIORORRRRCHIOOCH(boolean var1) {
         boolean var2 = var1
            || HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.CHOCCOOIIHROROOROICHOICCHICIOR.get()
            || !HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.IIIIRRICCHRHOIIHRRIHOIHRHRICOC;
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 36) {
            ORHIOICIOCRRHOOCOHRORIHICHRCRR var3 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.mc.bridge$getCurrentScreen();
            if (var3 != null && !(var3 instanceof RIRHOCHIORCCIIOIIRHOCCCRHHCHHH)) {
               var2 = false;
            }
         }

         if (!var2) {
            this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(0.0F, 0.0F);
            return false;
         } else {
            this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(320.0F, 107.0F);
            return true;
         }
      }

      @Override
      public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
      ) {
      }
   }
}
