package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRHHOOCRCOHHRHOOOCHCROOHIOOCOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

public interface CRRRICCRROCOHHOHIICIHORCOORRRH {
   CRRRICCRROCOHHOHIICIHORCOORRRH HHIRHRHHRHIHRHOHCHRHIORRHIIHOR(long var1);

   long ORHRRRORHHIRRRRIROCHHRORHHHHIO();
}
