package org.openapitools.jackson.nullable;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;

public class JsonNullableSerializers extends IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   @Override
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> findReferenceSerializer(
      ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var1,
      HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2,
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var3,
      CORCOCICIRIOHROHROIIOOHICCHCRR var4,
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> var5
   ) {
      if (!JsonNullable.class.isAssignableFrom(var2.RRICIOOORRIORHHICIRCIOCHRHRCHH())) {
         return null;
      }

      boolean var6 = var4 == null && var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(RICRIRRCOHRCOCRRHHCRHRROOIOHHR.USE_STATIC_TYPING);
      return new JsonNullableSerializer(var2, var6, var4, var5);
   }
}
