package com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;

import com.google.common.collect.ImmutableSet;
import java.util.Set;
import lombok.Generated;

public class CIOHHCORHRCCRICCCORIHCRHCCCRRR
   extends com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRCIIHHICIHRCOCRROCOICRIHHCCHH<com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH>
   implements com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private static CIOHHCORHRCCRICCCORIHCRHCCCRRR CIHIOCHCCRHOOCCHHRROCIRIORCRCR;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH COIICHOROICRRHHRHIRRCHOHHRHOOC;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ORICORORCHCOOCICCIIHOOCOCHCCOC;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH CCRHHRHRRHIRCCIHHCHICOCIHRCOIH;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RHRHORICHRHIHIHORRHRCHHIRIHRRH;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH IICCOOHCORROIOIRCIHHICORRCHHOI;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OHOCCRHCROCIHHCRRRROOHROHOROIC;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH CHHOCCIROIIIIHOCCIHICRHHCRHOCI;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH CCHRRICCCIOCRCICOOCCOIRCCHRHOR;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ICOCOCHIHICIICORROHRIIRIRHIICR;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OHCCCCRIOHORIRCORCCOHOICOIICRR;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH IIIHRCRHHRRHRIOHIRHCHIHICHRIHO;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ICRORIOICCCCOCRCCHIIRRROHHORHI;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ROHIHOCCCROHOOIHOHRRCHICOHHIHC;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH IRHCOHRRRCRIOHCCOCOCICRRRRHRHC;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OCRRCIOHHOOCRICOHIIIRRORCCHHRO;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OOHHOROOICIIIIROIIHOOHHHRIRHOO;
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ICOHOHCIOHRIIOOHORHOCCOCHHCORC;
   private static final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC OIRCROCRHOCHCRHIHOCCIOOHRIHOCO = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "lunar", "fonts/roboto-bold.ttf"
   );
   private static final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC RCCIOCHIHICRCOCCCCROOIOCOICROO = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "lunar", "fonts/roboto-medium.ttf"
   );
   private static final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC RCOHHHIHHRHIHICOHHCRIHORIICOCH = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "lunar", "fonts/roboto-light.ttf"
   );
   private static final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC ICHOOCRIHOOOIRCHRRIORCCCIHRCCO = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "lunar", "fonts/raleway-extrabold.ttf"
   );
   private static final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC IIRCCORIHOOIORHHOOOROOOHHRHICH = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "lunar", "fonts/raleway-light.ttf"
   );

   public CIOHHCORHRCCRICCCORIHCRHCCCRRR() {
      CIHIOCHCCRHOOCCHHRROCIRIORCRCR = this;
   }

   @Override
   protected Set<com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> ORRHHOHHRICCROHHICIOOHOOCRRRCC() {
      return ImmutableSet.of(
         ORICORORCHCOOCICCIIHOOCOCHCCOC = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            OIRCROCRHOCHCRHIHOCCIOOHRIHOCO, 10.0F
         ),
         RHRHORICHRHIHIHORRHRCHHIRIHRRH = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            OIRCROCRHOCHCRHIHOCCIOOHRIHOCO, 12.0F
         ),
         OHOCCRHCROCIHHCRRRROOHROHOROIC = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            OIRCROCRHOCHCRHIHOCCIOOHRIHOCO, 14.0F
         ),
         CCHRRICCCIOCRCICOOCCOIRCCHRHOR = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            OIRCROCRHOCHCRHIHOCCIOOHRIHOCO, 16.0F
         ),
         IIIHRCRHHRRHRIOHIRHCHIHICHRIHO = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            OIRCROCRHOCHCRHIHOCCIOOHRIHOCO, 18.0F
         ),
         IICCOOHCORROIOIRCIHHICORRCHHOI = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            RCOHHHIHHRHIHICOHHCRIHORIICOCH, 14.0F
         ),
         new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH[]{
            CCRHHRHRRHIRCCIHHCHICOCIHRCOIH = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               RCOHHHIHHRHIHICOHHCRIHORIICOCH, 12.0F
            ),
            ICRORIOICCCCOCRCCHIIRRROHHORHI = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               RCCIOCHIHICRCOCCCCROOIOCOICROO, 13.0F
            ),
            COIICHOROICRRHHRHIRRCHOHHRHOOC = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               RCCIOCHIHICRCOCCCCROOIOCOICROO, 10.0F
            ),
            CHHOCCIROIIIIHOCCIHICRHHCRHOCI = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               RCOHHHIHHRHIHICOHHCRIHORIICOCH, 16.0F
            ),
            ICOCOCHIHICIICORROHRIIRIRHIICR = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               RCOHHHIHHRHIHICOHHCRIHORIICOCH, 18.0F
            ),
            OHCCCCRIOHORIRCORCCOHOICOIICRR = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               RCCIOCHIHICRCOCCCCROOIOCOICROO, 18.0F
            ),
            ROHIHOCCCROHOOIHOHRRCHICOHHIHC = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               OIRCROCRHOCHCRHIHOCCIOOHRIHOCO, 22.0F
            ),
            IRHCOHRRRCRIOHCCOCOCICRRRRHRHC = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               RCOHHHIHHRHIHICOHHCRIHORIICOCH, 22.0F
            ),
            ICOHOHCIOHRIIOOHORHOCCOCHHCORC = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               RCOHHHIHHRHIHICOHHCRIHORIICOCH, 38.0F
            ),
            OCRRCIOHHOOCRICOHIIIRRORCCHHRO = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               ICHOOCRIHOOOIRCHRRIORCCCIHRCCO, 22.0F
            ),
            OOHHOROOICIIIIROIIHOOHHHRIRHOO = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               IIRCCORIHOOIORHHOOOROOOHHRHICH, 22.0F
            )
         }
      );
   }

   public static CIOHHCORHRCCRICCCORIHCRHCCCRRR IHIOCOHHHRICIRCOCIIHRRHIRICCIC() {
      return CIHIOCHCCRHOOCCHHRROCIRIORCRCR;
   }

   @Override
   public void init() {
      super.init();
   }

   @Override
   public String getCategory() {
      return "Font Textures";
   }

   @Override
   public Set<? extends com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> HIHCHCHCHROIIHCIHCOCIORCHCOCRC() {
      return this.OHHRCRIOOCIORORHIOHRICRHHORCIH();
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RIHRIHRIORHHHOOCHOHOHHCOCOIOHO() {
      return COIICHOROICRRHHRHIRRCHOHHRHOOC;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RICCOIRRCIHROCHIRIOCRHICIHRCRC() {
      return ORICORORCHCOOCICCIIHOOCOCHCCOC;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OCOHICCCCIROOROOOIRHRRHICOIORC() {
      return CCRHHRHRRHIRCCIHHCHICOCIHRCOIH;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HRRROHCOIORCIOHRRIRHCCRRRCCORC() {
      return RHRHORICHRHIHIHORRHRCHHIRIHRRH;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH IIICHRHOOCHCOROCHHOIIOCRCRIHOO() {
      return IICCOOHCORROIOIRCIHHICORRCHHOI;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HHHCICCCRHIIOCRHOHHRHRHHOROICR() {
      return OHOCCRHCROCIHHCRRRROOHROHOROIC;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RRHIRIIIROHHIORRHOIHCIRRCHHCOH() {
      return CHHOCCIROIIIIHOCCIHICRHHCRHOCI;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RORHCRCHOHHIRCCCICIIHIHCIORCHR() {
      return CCHRRICCCIOCRCICOOCCOIRCCHRHOR;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OHOIIIRRIHCRIRRCHHIRIOROHIIHIO() {
      return ICOCOCHIHICIICORROHRIIRIRHIICR;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RRHCRHHOIORHOHIHOROICIRIRHIIIC() {
      return OHCCCCRIOHORIRCORCCOHOICOIICRR;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HCHOOIHHIIIIIHIOHCORRIRORHIRRR() {
      return IIIHRCRHHRRHRIOHIRHCHIHICHRIHO;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH IOIHCHOOHORCORHHHCHCORHORHCOOC() {
      return ICRORIOICCCCOCRCCHIIRRROHHORHI;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HRRICCHRCRIOCHIIIORRCCCIIHCHCR() {
      return ROHIHOCCCROHOOIHOHRRCHICOHHIHC;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH IHROCOORIHRHIRHROHICOICRRORRIC() {
      return IRHCOHRRRCRIOHCCOCOCICRRRRHRHC;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH CCHIHOOHIROIHOOCICRIIICIIICHRH() {
      return OCRRCIOHHOOCRICOHIIIRRORCCHHRO;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ORCCRIICCCRHIHICHRHRRHRIOIICHR() {
      return OOHHOROOICIIIIROIIHOOHHHRIRHOO;
   }

   @Generated
   public static com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ORIROOICRRICRHRRHCIRHRCCHCHHHI() {
      return ICOHOHCIOHRIIOOHORHOCCOCHHCORC;
   }

   @Generated
   public static com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC HCRCOIIROIRRCCHICHIOIIIICCIIOI() {
      return RCCIOCHIHICRCOCCCCROOIOCOICROO;
   }
}
