package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;

public class CRICCOOHHHCHOORCICOCOHIHOIRHOO extends RIOOCHICIHRHOHCCCCCHOCCCOHCRHI {
   private static final long CIRIHCRHOCHOOCIRHRICOCRIROHCCO = 1L;
   protected final int RIRIHOICROCOOCIIRHHRHOIORIHHIO;
   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI OHRHIIOCOIHCHICHIRRHICCCOCCHHH;

   public CRICCOOHHHCHOORCICOCOHIHOIRHOO(int var1) {
      super(
         Object.class,
         IHHCHHHCRIHOOCOIOOCRIIICIOROIR.OIRRROOOHCOOCIOIRICHIHCHRCHHIR(),
         IIRHCHHOICHRICOOCRORCCIOOIHOIR.HIHOHHRCIOIIOHRRHRRRRCOHORHHOI(),
         null,
         1,
         null,
         null,
         false
      );
      this.RIRIHOICROCOOCIIRHHRHOIORIHHIO = var1;
   }

   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI OHIRCHHRCIIRHCHCHCCOIRICHOIIIR() {
      return this.OHRHIIOCOIHCHICHIRRHICCCOCCHHH;
   }

   public void OHRRHHOCROROCCIRROIHOCCHCIHCIR(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1
   ) {
      this.OHRHIIOCOIHCHICHIRRHICCCOCCHHH = var1;
   }

   @Override
   protected String HIHHIROICOOHOIHRIRICCIIRRRIIRR() {
      return this.toString();
   }

   @Override
   public StringBuilder RRCRRCORICCHOHHIRCHIROOHIIOHCO(StringBuilder var1) {
      return this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
   }

   @Override
   public StringBuilder RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(StringBuilder var1) {
      var1.append('$').append(this.RIRIHOICROCOOCIIRHHRHOIORIHHIO + 1);
      return var1;
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI RCOCHOROICROOIRHRCRIOHIHCOCIII(
      Object var1
   ) {
      return this.CHHHOIRCCHIROHCRIIOCIOHICOCCOO();
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI HCIHORIHHCOOORRIOHIHIICCRHHOHC(
      Object var1
   ) {
      return this.CHHHOIRCCHIROHCRIIOCIOHICOCCOO();
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI OICIRICHOHHIIHIRRRROORCRRRCORH(
      Object var1
   ) {
      return this.CHHHOIRCCHIROHCRIIOCIOHICOCCOO();
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI HIIRCRROICHCOROOCCCCOIOOOCCIIC(
      Object var1
   ) {
      return this.CHHHOIRCCHIROHCRIIOCIOHICOCCOO();
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1
   ) {
      return this.CHHHOIRCCHIROHCRIIOCIOHICOCCOO();
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI HHRHHIOOHOHIHRCHCHRORRRIIRIIHO() {
      return this.CHHHOIRCCHIROHCRIIOCIOHICOCCOO();
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Class<?> var1,
      IHHCHHHCRIHOOCOIOOCRIIICIOROIR var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI[] var4
   ) {
      return this.CHHHOIRCCHIROHCRIIOCIOHICOCCOO();
   }

   @Deprecated
   @Override
   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI IICCOOCHCHROORHHIIHROHCCRHRCOR(
      Class<?> var1
   ) {
      return this.CHHHOIRCCHIROHCRIIOCIOHICOCCOO();
   }

   @Override
   public boolean HCHCCRRRHHICOIRRIOOOOHHHOIIORR() {
      return false;
   }

   @Override
   public String toString() {
      return this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(new StringBuilder()).toString();
   }

   private <T> T CHHHOIRCCHIROHCRIIOCIOHICOCCOO() {
      throw new UnsupportedOperationException("Operation should not be attempted on " + this.getClass().getName());
   }
}
