package com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap;
import it.unimi.dsi.fastutil.objects.Object2DoubleOpenHashMap;
import java.util.Map;
import java.util.Map.Entry;
import javax.annotation.Nullable;

@com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 8)
public abstract class HHCCIRHCCCIIRHCROHIORHIRHHIORH<ID, Context>
   extends IRCIIHHICIHRCOCRROCOICRIHHCCHH<ID, Context, com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH<ID>> {
   public HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      super(var1);
   }

   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH<ID> IHHORCORCRCHIOCOOHHRCRCRCOIROI() {
      return new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
         this.OOHCCRCRRORIICIICRRRHOIOHIOHRO()
      );
   }

   protected abstract boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      CRHROHHHCIHHCOHCOORCRIHHIICROR var1,
      ID var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3
   );

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      @Nullable Context var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2,
      double var3,
      double var5,
      double var7,
      long var9
   ) {
      if (!this.IIOIROIHIHHCCRICRCOOCHIICHRCOI(var1)) {
         if (!this.RCHICRHOICCIICRORRHIRRHOCIRCOO.isEmpty()) {
            var2.bridge$pushPose();
            RHOCHHIRRCHHHOHOIRROIROHHHIHIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH var12 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHCHRCCRRHORIOCIOHHCRHCHICRIHH()
               .HRICOCOIOCCCICCIORHIIIIOROCOHC();
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var11 = var12.RCIHOCCIROCOIOOCCOHICRIIRIIROI()
               .bridge$copy();
            var11.bridge$multiply(var2.bridge$last().bridge$pose());
            CRHROHHHCIHHCOHCOORCRIHHIICROR var13 = this.HHOOICHICHHOIIRIIOOCHOOHICHRIO.HIOCRIRHCICROIHOHOCCRIRHRHICOR();
            com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var14 = this.OOHCCRCRRORIICIICRRRHOIOHIOHRO();
            Object var15 = var14.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var13);
            this.CRCHCHIICCCOCOCIICRHIHRICCHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var13, (ID)var15);
            Object2DoubleOpenHashMap var16 = new Object2DoubleOpenHashMap();
            Object2BooleanOpenHashMap var17 = new Object2BooleanOpenHashMap();

            for (Entry var19 : this.COCCRHRCOHCOOOIHCIRRHROOCIHRHO.entrySet()) {
               Object var20 = var19.getKey();
               com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var21 = (com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var19.getValue();
               if (var21 == null) {
                  var17.put(var20, false);
               } else if (!var21.ICIRICHHROHIROORIHROCHHCIRCHRI()
                  || !var17.computeIfAbsent(var20, var4 -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var13, (ID)var15, var21.RIORHRCCRHRCRCOIOCHCHIIRHIIIRR()))) {
                  this.HHOOICHICHHOIIRIIOOCHOOHICHRIO.RHRIRHHIOCCHRIOHCIOHOCOIOHHIOI().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var21);
               }
            }

            boolean var29 = this.IHOIOCORCICORROIHRHIORRIHRICCO();

            for (Entry var31 : this.RCHICRHOICCIICRORRHIRRHOCIRCOO.entrySet()) {
               IRRCCOICORICIHCHRHIHIHROIRHOCR var32 = (IRRCCOICORICIHCHRHIHIHROIRHOCR)var31.getKey();
               boolean var22 = true;
               Map var23 = (Map)var31.getValue();

               for (Object var25 : this.CRCHCHIICCCOCOCIICRHIHRICCHCHH) {
                  if (!var17.getBoolean(var25)) {
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OHHRIOHROOIHOROCIRHCHORIHRRRRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var26 = (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OHHRIOHROOIHOROCIRHCHORIHRRRRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var23.get(
                        var25
                     );
                     if (var26 != null) {
                        RORCHCIIICOHIRROOORHOCCCCIOCCI var27 = var14.IIOCHOIICCIORCOROIROHICCHIOHIC(var25);
                        com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var28 = var11.bridge$copy();
                        if (var29) {
                           com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              var32,
                              this.HHOOICHICHHOIIRIIOOCHOOHICHRIO.HRRRCROORHIIROROORICHCOHOOIHCO() ? var13 : null,
                              var27,
                              var26,
                              () -> var16.computeIfAbsent(var25, var2xx -> {
                                 RORCHCIIICOHIRROOORHOCCCCIOCCI var3xx = var14.IOIOHIORIROHRRCOOOHCROHORCOIIH(var2xx);
                                 return var13.IIRHCHHOICHRICOOCRORCCIOOIHOIR(var3xx.bridge$getX(), var3xx.bridge$getY(), var3xx.bridge$getZ());
                              }),
                              var9,
                              false,
                              true
                           );
                        }

                        com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           var3, var5, var7, var27, var28
                        );
                        this.HHOOICHICHHOIIRIIOOCHOOHICHRIO
                           .RHRIRHHIOCCHRIOHCIOHOCOIOHHIOI()
                           .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              this.IHIRCORCCOCRCHRHIOIIRIOOROCCII(),
                              var32,
                              () -> com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                                 var28, var32, var26
                              ),
                              var22
                           );
                        if (var22) {
                           var22 = false;
                        }
                     }
                  }
               }
            }

            var2.bridge$popPose();
         }
      }
   }
}
