package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import it.unimi.dsi.fastutil.ints.Int2IntArrayMap;
import it.unimi.dsi.fastutil.ints.IntArrayList;
import it.unimi.dsi.fastutil.ints.IntList;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import lombok.Generated;
import org.jetbrains.annotations.Nullable;
import org.joml.Vector2i;
import org.joml.Vector3i;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   public static final int OHCHCHRICHHOCHIIRRHOIHCCROCOHO = 254;
   public static final int CROCORICROORHOIOIROCCCHCIROCII = 83;
   private static final IntList IRICHCRIOCICHCHORRORHCIRHOCHOC = new IntArrayList(new int[]{5, 35, 54, 68, 77, 144, 146});
   private static final Int2IntArrayMap ICHROHHHIRRRRIHROCCROICRIIHRHC = new Int2IntArrayMap() {
      {
         this.put(8, 9);
         this.put(10, 11);
         this.put(43, 44);
         this.put(62, 61);
         this.put(125, 126);
         this.put(181, 182);
      }
   };

   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var0, boolean var1) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.EAST;
      RORCHCIIICOHIRROOORHOCCCCIOCCI var3 = null;
      boolean var4 = false;
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII()
         .HHHHRHROCRRHCCHRIHICHOHCICHROO();
      RRCRRCORICCHOHHIRCHIROOHIIOHCO var6 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      if (var6 != null) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = var0.ORCRIORCRRCOIOHOIRRHIRHCCRRIII()
            .get(0);
         int var8 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, (int)var7.CRCHOCHORIHICORHICHOIRIIOIRHRO(), (int)var7.ROIRRRROIIHOOIHHHCOORHOOCORIRI());
         IRCIIHHICIHRCOCRROCOICRIHHCCHH var9 = var0.ORIOOHCOHCCOCCRCCOORCHRHRRHRRO().OHICOOCOIOCHRCHRIHCRIIRCROCCOH();
         if (var0.ROROCRCCCCOROCCORROIOIOHICOHHR().ICRHOHIHRIORCIIRIHOCCHOCOHOCRO()
               != com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ADJACENT
            || var9 == null
            || RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var9.ORCRIORCRRCOIOHOIRRHIRHCCRRIII().get(0), var8)) {
            label64:
            for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var11 : var0.ORCRIORCRRCOIOHOIRRHIRHCCRRIII()) {
               if (!var11.isLoaded()) {
                  return;
               }

               HHCCIRHCCCIIRHCROHIORHIRHHIORH var12 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var11.CRCHOCHORIHICORHICHOIRIIOIRHRO(), var8, var11.ROIRRRROIIHOOIHHHCOORHOOCORIRI());
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH[] var13 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.VALUES;
               int var14 = var13.length;
               int var15 = 0;

               while (true) {
                  if (var15 < var14) {
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var16 = var13[var15];
                     Vector3i var17 = new Vector3i(var16.getX(), 0, var16.getZ());
                     RORCHCIIICOHIRROOORHOCCCCIOCCI var18 = var12.bridge$add(var17);
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var19 = var6.CIOHHCORHRCCRICCCORIHCRHCCCRRR(
                        var18
                     );
                     if (var19 != var5) {
                        var15++;
                        continue;
                     }

                     var2 = var16;
                     var3 = var16.getCorner(var18);
                     var4 = true;
                  }

                  if (var4) {
                     break label64;
                  }
                  break;
               }
            }

            if (!var4) {
               var3 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7.CRCHOCHORIHICORHICHOIRIIOIRHRO(), var8, var7.ROIRRRROIIHOOIHHHCOORHOOCORIRI());
            }

            String var20 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, var3, var2, var8);
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var21 = HRRIIOOHRHHHOOOHCHRCIOCICRCRIH(
               var20
            );
            if (var21 == null && !var1) {
               IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                  .IHCHHRRIIIORORCHIICIIOORCOIOIO()
                  .CIICCRHHHOHOIOHCHRHOORCICRCORC(OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH("skyblockUnknownDungeonRoom"));
            }

            var0.IRCIIHHICIHRCOCRROCOICRIHHCCHH(new HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var21, var20, var3, var2));
            if (var21 != null) {
               var0.ORIOOHCOHCCOCCRCCOORCHRHRRHRRO()
                  .RHIOHIRIHHCIHRIIIIIOIRRHRHRIII()
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                        var7.OOORHHCCIHHCCRHHCRRIHOCRRRHHIH(), var20, var3.bridge$toJoml(), var2
                     )
                  );
            }

            if (var21 != null) {
               var0.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var21.roomType());
            }

            if (!var1) {
               IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var0);
            }
         }
      }
   }

   private static boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      IRCIIHHICIHRCOCRROCOICRIHHCCHH var0,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      int var2
   ) {
      List var3 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH(),
         var0.ORCRIORCRRCOIOHOIRRHIRHCCRRIII().get(0),
         var1,
         var2,
         var0.ORIOOHCOHCCOCCRCCOORCHRHRRHRRO()
      );
      if (var3 == null) {
         return false;
      }

      boolean var4 = false;

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 : var3) {
         if (!var0.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var6)) {
            var0.CRRRICCRROCOHHOHIICIHORCOORRRH(var6);
            var4 = true;
         }
      }

      if (var4) {
         var0.ORIOOHCOHCCOCCRCCOORCHRHRRHRRO()
            .RHIOHIRIHHCIHRIIIIIOIRRHRHRIII()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               new CRRRICCRROCOHHOHIICIHORCOORRRH(
                  var3.stream()
                     .map(
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::OOORHHCCIHHCCRHHCRRIHOCRRRHHIH
                     )
                     .toArray(Vector2i[]::new),
                  var0.ROROCRCCCCOROCCORROIOIOHICOHHR().HIHIIIRHCOHCHOOCICRHCRHCHIHIOO()
               )
            );
      }

      return true;
   }

   private static String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RRCRRCORICCHOHHIRCHIROOHIIOHCO var0,
      RORCHCIIICOHIRROOORHOCCCCIOCCI var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      int var3
   ) {
      StringBuilder var4 = new StringBuilder();

      for (int var5 = 1; var5 <= 2; var5++) {
         for (int var6 = 1; var6 <= 2; var6++) {
            RORCHCIIICOHIRROOORHOCCCCIOCCI var7 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1,
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5 * 10, 0, var6 * 10),
               var2
            );
            int var8 = var7.bridge$getX();
            int var9 = var7.bridge$getZ();

            for (int var10 = var3; var10 >= 0; var10--) {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var11 = var0.bridge$getBlockAt(
                  var8, var10, var9
               );
               int var12 = var11.bridge$getPreFlatteningID();
               if (!IRICHCRIOCICHCHORRORHCIRHOCHOC.contains(var12)) {
                  if (!ICHROHHHIRRRRIHROCCROICRIIHRHC.containsKey(var12)) {
                     var4.append(var12);
                  } else {
                     var4.append(ICHROHHHIRRRRIHROCCROICRIIHRHC.get(var12));
                  }
               } else {
                  var4.append(0);
               }
            }
         }
      }

      int var13 = var4.toString().hashCode();
      return var13 + "-" + var3;
   }

   public static com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH HRRIIOOHRHHHOOOHCHRCIOCICRCRIH(
      String var0
   ) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH[] var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .IHIIROIOIHOHCHICOIIIHOHHCOIOCI()
         .ORICRIRORRCHHHRRHOORHIRCICHCCO()
         .RICIOHCOHHOIIRHCHHHIHIHHCIROIO();
      if (var1 == null) {
         return null;
      }

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 : var1) {
         String[] var6 = var5.hashes();

         for (String var10 : var6) {
            if (var10.equals(var0)) {
               return var5;
            }
         }
      }

      return null;
   }

   private static int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RRCRRCORICCHOHHIRCHIROOHIIOHCO var0, int var1, int var2) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII()
         .RRHCOHIOHRCIIOROOHOCOOOCHOHOIH();

      for (int var4 = 254; var4 >= 83; var4--) {
         if (var0.bridge$getBlockAt(var1, var4, var2) != var3) {
            return var4;
         }
      }

      return -1;
   }

   public static Vector3i IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      Vector3i var0,
      Vector3i var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      int var3 = var0.x();
      int var4 = var0.z();
      int var5 = var1.x();
      int var6 = var1.z();
      switch (var2) {
         case EAST:
            var3 += var5;
            var4 += var6;
            break;
         case SOUTH:
            var3 -= var6;
            var4 += var5;
            break;
         case WEST:
            var3 -= var5;
            var4 -= var6;
            break;
         case NORTH:
            var3 += var6;
            var4 -= var5;
      }

      return new Vector3i(var3, var1.y(), var4);
   }

   public static RORCHCIIICOHIRROOORHOCCCCIOCCI RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RORCHCIIICOHIRROOORHOCCCCIOCCI var0,
      RORCHCIIICOHIRROOORHOCCCCIOCCI var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      int var3 = var0.bridge$getX();
      int var4 = var0.bridge$getZ();
      int var5 = var1.bridge$getX();
      int var6 = var1.bridge$getZ();
      switch (var2) {
         case EAST:
            var3 += var5;
            var4 += var6;
            break;
         case SOUTH:
            var3 -= var6;
            var4 += var5;
            break;
         case WEST:
            var3 -= var5;
            var4 -= var6;
            break;
         case NORTH:
            var3 += var6;
            var4 -= var5;
      }

      return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var1.bridge$getY(), var4);
   }

   public static int[] RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RORCHCIIICOHIRROOORHOCCCCIOCCI var0,
      int[] var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      int var3 = var0.bridge$getX();
      int var4 = var0.bridge$getZ();
      int var5 = var1[0];
      int var6 = var1[2];
      switch (var2) {
         case EAST:
            var3 += var5;
            var4 += var6;
            break;
         case SOUTH:
            var3 -= var6;
            var4 += var5;
            break;
         case WEST:
            var3 -= var5;
            var4 -= var6;
            break;
         case NORTH:
            var3 += var6;
            var4 -= var5;
      }

      return new int[]{var3, var1[1], var4};
   }

   public static double[] RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RORCHCIIICOHIRROOORHOCCCCIOCCI var0,
      double var1,
      double var3,
      double var5,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7
   ) {
      double var8 = var0.bridge$getX();
      double var10 = var0.bridge$getZ();
      switch (var7) {
         case EAST:
            var8 += var1;
            var10 += var5;
            break;
         case SOUTH:
            var8 -= var5;
            var10 += var1;
            break;
         case WEST:
            var8 -= var1;
            var10 -= var5;
            break;
         case NORTH:
            var8 += var5;
            var10 -= var1;
      }

      return new double[]{var8, var3, var10};
   }

   public static RORCHCIIICOHIRROOORHOCCCCIOCCI IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      RORCHCIIICOHIRROOORHOCCCCIOCCI var0,
      RORCHCIIICOHIRROOORHOCCCCIOCCI var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      int var3 = var0.bridge$getX();
      int var4 = var0.bridge$getZ();
      int var5 = var1.bridge$getX();
      int var6 = var1.bridge$getZ();
      int var7 = 0;
      int var8 = 0;
      switch (var2) {
         case EAST:
            var7 = var5 - var3;
            var8 = var6 - var4;
            break;
         case SOUTH:
            var7 = var6 - var4;
            var8 = var3 - var5;
            break;
         case WEST:
            var7 = var3 - var5;
            var8 = var4 - var6;
            break;
         case NORTH:
            var7 = var4 - var6;
            var8 = var5 - var3;
      }

      return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7, var1.bridge$getY(), var8);
   }

   public static Vector3i HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      Vector3i var0,
      Vector3i var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      int var3 = var0.x();
      int var4 = var0.z();
      int var5 = var1.x();
      int var6 = var1.z();
      int var7 = 0;
      int var8 = 0;
      switch (var2) {
         case EAST:
            var7 = var5 - var3;
            var8 = var6 - var4;
            break;
         case SOUTH:
            var7 = var6 - var4;
            var8 = var3 - var5;
            break;
         case WEST:
            var7 = var3 - var5;
            var8 = var4 - var6;
            break;
         case NORTH:
            var7 = var4 - var6;
            var8 = var5 - var3;
      }

      return new Vector3i(var7, var1.y(), var8);
   }

   public static int[] RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RORCHCIIICOHIRROOORHOCCCCIOCCI var0,
      int var1,
      int var2,
      int var3,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4
   ) {
      int var5 = var0.bridge$getX();
      int var6 = var0.bridge$getZ();
      int var7 = 0;
      int var8 = 0;
      switch (var4) {
         case EAST:
            var7 = var1 - var5;
            var8 = var3 - var6;
            break;
         case SOUTH:
            var7 = var3 - var6;
            var8 = var5 - var1;
            break;
         case WEST:
            var7 = var5 - var1;
            var8 = var6 - var3;
            break;
         case NORTH:
            var7 = var6 - var3;
            var8 = var1 - var5;
      }

      return new int[]{var7, var2, var8};
   }

   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = new IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         var0,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.SPAWN
      );
      var2.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, true);
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var3 = var2.HRHHIRHRICRCOCOHICCIROOCCCCIOH().orElse(null);
      if (var3 != null
         && var3.CIOHOOICRHROHHIOICCHOCOCOOOHOO() != null
         && var3.CIOHOOICRHROHHIOICCHOCOCOOOHOO().roomType()
            == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.SPAWN
         )
       {
         var2.OHHIORIOCRCOIHRIRICICOIOOICCIH();
         var2.CRRRICCRROCOHHOHIICIHORCOORRRH(var1);
         IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2);
      }
   }

   private static void IHHCHHHCRIHOOCOIOOCRIIICIOROIR(IRCIIHHICIHRCOCRROCOICRIHHCCHH var0) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII();
      RRCRRCORICCHOHHIRCHIROOHIIOHCO var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = var0.ORIOOHCOHCCOCCRCCOORCHRHRRHRRO();
      IIRHCHHOICHRICOOCRORCCIOOIHOIR(var0)
         .forEach(
            var4 -> {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = var2.CIOHHCORHRCCRICCCORIHCRHCCCRRR(
                  var4
               );
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var4.bridge$getX(), var4.bridge$getZ(), var3
               );
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = null;

               for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var11 : com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.VALUES) {
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var12 = var11.asDirectionBridge();
                  var7 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var4.bridge$getX() + var12.getOffsetX() * 5, var4.bridge$getZ() + var12.getOffsetZ() * 5, var3
                  );
                  if (var6.OCOCIOCIIOROHHHCHRHIRCOHIHHOOC() != var7.OCOCIOCIIOROHHHCHRHIRCOHIHHOOC()
                     || var6.HCHRRRICHHOHRCROCIOIOROIHIIOCI() != var7.HCHRRRICHHOHRCROCIOIOROIHIIOCI()) {
                     break;
                  }
               }

               if (var7 != null && var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, var7) == null) {
                  var6.CCIHCCCCCOHOICOCHROCHOIOICCIRC();
                  var7.CCIHCCCCCOHOICOCHROCHOIOICCIRC();
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var14;
                  if (var5 == var1.ICROOCRRHOOICOOIOCOHCHOHOIOOOH()) {
                     var14 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        var3,
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.WITHER_DOOR,
                        var6,
                        var7
                     );
                  } else if (var5 == var1.HCIIHRCRHIHHHCCIORIIHOHROOICIH()) {
                     var14 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        var3,
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.BLOOD,
                        var6,
                        var7
                     );
                  } else if (var5 == var1.RRHCOHIOHRCIIOROOHOCOOOCHOHOIH()
                     && var0.ROROCRCCCCOROCCORROIOIOHICOHHR().HIHIIIRHCOHCHOOCICRHCRHCHIHIOO()
                        != com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.SPAWN
                     )
                   {
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var15 = var2.CIOHHCORHRCCRICCCORIHCRHCCCRRR(
                        var4.bridge$offset(0, -1, 0)
                     );
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var18 = var2.CIOHHCORHRCCRICCCORIHCRHCCCRRR(
                        var4.bridge$offset(0, -2, 0)
                     );
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var19 = var2.CIOHHCORHRCCRICCCORIHCRHCCCRRR(
                        var4.bridge$offset(0, 1, 0)
                     );
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var20 = var2.CIOHHCORHRCCRICCCORIHCRHCCCRRR(
                        var4.bridge$offset(0, 2, 0)
                     );
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var13 = var2.CIOHHCORHRCCRICCCORIHCRHCCCRRR(
                        var4.bridge$offset(0, 3, 0)
                     );
                     if (var15 != var1.RRHCOHIOHRCIIOROOHOCOOOCHOHOIH()
                        || var18 == var1.RRHCOHIOHRCIIOROOHOCOOOCHOHOIH()
                        || var19 != var1.RRHCOHIOHRCIIOROOHOCOOOCHOHOIH()
                        || var20 != var1.RRHCOHIOHRCIIOROOHOCOOOCHOHOIH()
                        || var13 == var1.RRHCOHIOHRCIIOROOHOCOOOCHOHOIH()) {
                        return;
                     }

                     var14 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        var3,
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.UNKNOWN,
                        var6,
                        var7
                     );
                  } else {
                     if (var5 != var1.OCHCRCRIOHHOHCIHOOOCCCORIOCHIH()) {
                        return;
                     }

                     var14 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        var3,
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.UNKNOWN,
                        var6,
                        var7
                     );
                  }

                  if (var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6) == null) {
                     IRCIIHHICIHRCOCRROCOICRIHHCCHH var16 = new IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        var3,
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.UNKNOWN
                     );
                     var16.CRRRICCRROCOHHOHIICIHORCOORRRH(var6);
                     var16.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ADJACENT
                     );
                     var3.RHIOHIRIHHCIHRIIIIIOIRRHRHRIII()
                        .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO(
                              var6.OOORHHCCIHHCCRHHCRRIHOCRRRHHIH()
                           )
                        );
                  } else if (var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7) == null) {
                     IRCIIHHICIHRCOCRROCOICRIHHCCHH var17 = new IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        var3,
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.UNKNOWN
                     );
                     var17.CRRRICCRROCOHHOHIICIHORCOORRRH(var7);
                     var17.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ADJACENT
                     );
                     var3.RHIOHIRIHHCIHRIIIIIOIRRHRHRIII()
                        .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO(
                              var7.OOORHHCCIHHCCRHHCRRIHOCRRRHHIH()
                           )
                        );
                  }

                  var0.ORIOOHCOHCCOCCRCCOORCHRHRRHRRO().CRRRICCRROCOHHOHIICIHORCOORRRH(var14);
                  var3.RHIOHIRIHHCIHRIIIIIOIRRHRHRIII()
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                           var14.HIHIIIRHCOHCHOOCICRHCRHCHIHIOO(),
                           var14.HHHHIHRROHROIHOOROOOIHIRIRHOCO().OOORHHCCIHHCCRHHCRRIHOCRRRHHIH(),
                           var14.ICOCCRORICCOCIHCHHHCOORHCCCHHI().OOORHHCCIHHCCRHHCRRIHOCRRRHHIH()
                        )
                     );
               }
            }
         );
   }

   @Nullable
   private static List<RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RRCRRCORICCHOHHIRCHIROOHIIOHCO var0,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      int var3,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4
   ) {
      ArrayList var5 = new ArrayList();
      var5.add(var1);
      if (var1.equals(var2)) {
         return var5;
      }

      LinkedList var6 = new LinkedList();
      var6.add(var1);

      while (!var6.isEmpty()) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var6.remove();
         HHCCIRHCCCIIRHCROHIORHIRHHIORH var8 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7.CRCHOCHORIHICORHICHOIRIIOIRHRO(), var3, var7.ROIRRRROIIHOOIHHHCOORHOOCORIRI());

         for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var12 : com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.values()) {
            Vector3i var13 = new Vector3i(var12.getX(), 0, var12.getZ());
            RORCHCIIICOHIRROOORHOCCCCIOCCI var14 = var8.bridge$add(var13);
            int var15 = (int)Math.floor(var14.bridge$getX() / 16.0);
            int var16 = (int)Math.floor(var14.bridge$getZ() / 16.0);
            if (!var0.bridge$isChunkLoaded(var15, var16)) {
               return null;
            }

            if (var0.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var14)
               != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII()
                  .RRHCOHIOHRCIIOROOHOCOOOCHOHOIH()) {
               RORCHCIIICOHIRROOORHOCCCCIOCCI var17 = var14.bridge$add(var13);
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var18 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var17.bridge$getX(), var17.bridge$getZ(), var4
               );
               var18.CCIHCCCCCOHOICOCHROCHOIOICCIRC();
               if (!var18.equals(var2) && !var5.contains(var18)) {
                  if (!var18.isLoaded()) {
                     return null;
                  }

                  var5.add(var18);
                  var6.add(var18);
               }
            }
         }
      }

      return var5;
   }

   private static ArrayList<RORCHCIIICOHIRROOORHOCCCCIOCCI> IIRHCHHOICHRICOOCRORCCIOOIHOIR(IRCIIHHICIHRCOCRROCOICRIHHCCHH var0) {
      ArrayList var1 = new ArrayList();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI();
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var3 = var0.HRHHIRHRICRCOCOHICCIROOCCCCIOH().orElse(null);
      if (var3 == null) {
         return var1;
      }

      switch (var0.RORRIHRIRHHRHHOIIICOIOIIIHRHRI()) {
         case ONE_BY_ONE:
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(-1, 70, 15)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(31, 70, 15)));
            break;
         case ONE_BY_TWO:
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(-1, 70, 15)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(63, 70, 15)));
            break;
         case ONE_BY_THREE:
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(-1, 70, 15)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(79, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(79, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(95, 70, 15)));
            break;
         case ONE_BY_FOUR:
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(-1, 70, 15)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(79, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(79, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(111, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(111, 70, 31)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(127, 70, 15)));
            break;
         case TWO_BY_TWO:
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(-1, 70, 15)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(63, 70, 15)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(63, 70, 47)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, 63)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, 63)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(-1, 70, 47)));
            break;
         case L_SHAPE:
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, -1)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(-1, 70, 15)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(31, 70, 15)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(63, 70, 47)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, 63)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(15, 70, 63)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(-1, 70, 47)));
            var1.add(var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(47, 70, 31)));
      }

      return var1;
   }

   private enum RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      NORTH(0, -1),
      EAST(31, 0),
      SOUTH(0, 31),
      WEST(-1, 0);

      private final int x;
      private final int z;

      @Generated
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(int var3, int var4) {
         this.x = var3;
         this.z = var4;
      }

      @Generated
      public int getX() {
         return this.x;
      }

      @Generated
      public int getZ() {
         return this.z;
      }
   }
}
