package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;

import java.lang.annotation.Annotation;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public class RRCRRCORICCHOHHIRCHIROOHIIOHCO {
   private static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH ORHRIIIRIHRCCHHCORRIIORHHHIOII = IIRHCHHOICHRICOOCRORCCIOOIHOIR.CRIORRIRHOOOHRIRIRHOOOICRRHHHH();
   private static final Class<?> CRCCIOCOOHORRHCCICOOIIIICHHIIR = Object.class;
   private static final Class<?> IICORHIHHCRHIRIOIRICCIHHRCCHIH = Enum.class;
   private static final Class<?> RRIRHHHOORHIHOIIICCHRIOROICIRR = List.class;
   private static final Class<?> ICORCOHRRHRORRCCIIRCHCROCHHCIH = Map.class;
   private final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> ORCIOOOOOIIHRCCIOOIIOOCHHIHIOO;
   private final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH CCCIORORRIICIRCIROHOOOIHRIRCRO;
   private final RIROICHCRROROHCCROOCCCCOCHCCRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH COOCRRCCCIHOIIRIHHIHHCHRCHCHIC;
   private final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR RCHCCCRROIROICIORRRCIOHCCIIORR;
   private final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI IHIRRRORCROCHCHOHCIIHRHRCRCCII;
   private final Class<?> RRORIRHCOHCIHOIOHHRHHCRCOCHHCR;
   private final Class<?> RRHHORCCCIRRIICHOHCCIIIRHICHCO;
   private final boolean RICIOHIOHICOIOHHOCRIOHIOCHIHHH;

   RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2,
      RIROICHCRROROHCCROOCCCCOCHCCRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3
   ) {
      this.ORCIOOOOOIIHRCCIOOIIOOCHHIHIOO = var1;
      this.IHIRRRORCROCHCHOHCIIHRHRCRCCII = var2;
      this.RRORIRHCOHCIHOIOHHRHHCRCOCHHCR = var2.RRICIOOORRIORHHICIRCIOCHRHRCHH();
      this.COOCRRCCCIHOIIRIHHIHHCHRCHCHIC = var3;
      this.RCHCCCRROIROICIORRRCIOHCCIIORR = var2.HOHCHIIHCCCCHCOORROOHHOIIRIHRH();
      this.CCCIORORRIICIRCIROHOOOIHRIRCRO = var1.HCRCRHHORCRHCCCHORCCCRORRIRRRC() ? var1.RCRORHCOCRIIOHICORIHOHRIIRIORH() : null;
      this.RRHHORCCCIRRIICHOHCCIIIRHICHCO = var3 == null ? null : var3.IOHOOIOHCHICOCHIICHCICCOHRCIII(this.RRORIRHCOHCIHOIOHHRHHCRCOCHHCR);
      this.RICIOHIOHICOIOHHOCRIOHIOCHIHHH = this.CCCIORORRIICIRCIROHOOOIHRIRCRO != null
         && (
            !com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCCICOCCCHROHOCCHIHORIHHCOHOHH(
                  this.RRORIRHCOHCIHOIOHHRHHCRCOCHHCR
               )
               || !this.IHIRRRORCROCHCHOHCIIHRHRCRCCII.HCHCCRRRHHICOIRRIOOOOHHHOIIORR()
         );
   }

   RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var1,
      Class<?> var2,
      RIROICHCRROROHCCROOCCCCOCHCCRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3
   ) {
      this.ORCIOOOOOIIHRCCIOOIIOOCHHIHIOO = var1;
      this.IHIRRRORCROCHCHOHCIIHRHRCRCCII = null;
      this.RRORIRHCOHCIHOIOHHRHHCRCOCHHCR = var2;
      this.COOCRRCCCIHOIIRIHHIHHCHRCHCHIC = var3;
      this.RCHCCCRROIROICIORRRCIOHCCIIORR = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.OIRRROOOHCOOCIOIRICHIHCHRCHHIR();
      if (var1 == null) {
         this.CCCIORORRIICIRCIROHOOOIHRIRCRO = null;
         this.RRHHORCCCIRRIICHOHCCIIIRHICHCO = null;
      } else {
         this.CCCIORORRIICIRCIROHOOOIHRIRCRO = var1.HCRCRHHORCRHCCCHORCCCRORRIRRRC() ? var1.RCRORHCOCRIIOHICORIHOHRIIRIORH() : null;
         this.RRHHORCCCIRRIICHOHCCIIIRHICHCO = var3 == null ? null : var3.IOHOOIOHCHICOCHIICHCICCOHRCIII(this.RRORIRHCOHCIHOIOHHRHHCRCOCHHCR);
      }

      this.RICIOHIOHICOIOHHOCRIOHIOCHIHHH = this.CCCIORORRIICIRCIROHOOOIHRIRCRO != null;
   }

   public static CRRRICCRROCOHHOHIICIHORCOORRRH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var0,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      RIROICHCRROROHCCROOCCCCOCHCCRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      return var1.OCOHHROOICIIRHRIRHIRHIORORROOI() && HHCCIRHCCCIIRHCROHIORHIRHHIORH(var0, var1.RRICIOOORRIORHHICIRCIOCHRHRCHH())
         ? CRRRICCRROCOHHOHIICIHORCOORRRH(var0, var1.RRICIOOORRIORHHICIRCIOCHRHRCHH())
         : new RRCRRCORICCHOHHIRCHIROOHIIOHCO(var0, var1, var2).HROIOIHHCCIORIOIIHRRHHCIIHHHOO();
   }

   public static CRRRICCRROCOHHOHIICIHORCOORRRH IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var0,
      Class<?> var1
   ) {
      return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, var0);
   }

   public static CRRRICCRROCOHHOHIICIHORCOORRRH IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var0,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      RIROICHCRROROHCCROOCCCCOCHCCRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      return var1.OCOHHROOICIIRHRIRHIRHIORORROOI() && HHCCIRHCCCIIRHCROHIORHIRHHIORH(var0, var1.RRICIOOORRIORHHICIRCIOCHRHRCHH())
         ? CRRRICCRROCOHHOHIICIHORCOORRRH(var0, var1.RRICIOOORRIORHHICIRCIOCHRHRCHH())
         : new RRCRRCORICCHOHHIRCHIROOHIIOHCO(var0, var1, var2).CHRCIRCCRORRCHHIRRORRCIOCIOCOH();
   }

   public static CRRRICCRROCOHHOHIICIHORCOORRRH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var0,
      Class<?> var1,
      RIROICHCRROROHCCROOCCCCOCHCCRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      return var1.isArray() && HHCCIRHCCCIIRHCROHIORHIRHHIORH(var0, var1)
         ? CRRRICCRROCOHHOHIICIHORCOORRRH(var0, var1)
         : new RRCRRCORICCHOHHIRCHIROOHIIOHCO(var0, var1, var2).CHRCIRCCRORRCHHIRRORRCIOCIOCOH();
   }

   private static boolean HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var0,
      Class<?> var1
   ) {
      return var0 == null || var0.IOHOOIOHCHICOCHIICHCICCOHRCIII(var1) == null;
   }

   static CRRRICCRROCOHHOHIICIHORCOORRRH HCHOOCHIOICRRHHIHHHICIRCIOICRI(Class<?> var0) {
      return new CRRRICCRROCOHHOHIICIHORCOORRRH(var0);
   }

   static CRRRICCRROCOHHOHIICIHORCOORRRH CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var0,
      Class<?> var1
   ) {
      return new CRRRICCRROCOHHOHIICIHORCOORRRH(var1);
   }

   CRRRICCRROCOHHOHIICIHORCOORRRH HROIOIHHCCIORIOIIHRRHHCIIHHHOO() {
      ArrayList var1 = new ArrayList(8);
      if (!this.IHIRRRORCROCHCHOHCIIHRHRCRCCII.RIHOOCIHRICOCHRHCOOCCOIHOCHRCR(Object.class)) {
         if (this.IHIRRRORCROCHCHOHCIIHRHRCRCCII.isInterface()) {
            IRCIIHHICIHRCOCRROCOICRIHHCCHH(this.IHIRRRORCROCHCHOHCIIHRHRCRCCII, var1, false);
         } else {
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.IHIRRRORCROCHCHOHCIIHRHRCRCCII, var1, false);
         }
      }

      return new CRRRICCRROCOHHOHIICIHORCOORRRH(
         this.IHIRRRORCROCHCHOHCIIHRHRCRCCII,
         this.RRORIRHCOHCIHOIOHHRHHCRCOCHHCR,
         var1,
         this.RRHHORCCCIRRIICHOHCCIIIRHICHCO,
         this.RRCROCCRIOIROHCCRCCIORICOCIOHC(var1),
         this.RCHCCCRROIROICIORRRCIOHCCIIORR,
         this.CCCIORORRIICIRCIROHOOOIHRIRCRO,
         this.COOCRRCCCIHOIIRIHHIHHCHRCHCHIC,
         this.ORCIOOOOOIIHRCCIOOIIOOCHHIHIOO.CRRIRCRIRCHCHIRCICOROIIOIIICCC(),
         this.RICIOHIOHICOIOHHOCRIOHIOCHIHHH
      );
   }

   CRRRICCRROCOHHOHIICIHORCOORRRH CHRCIRCCRORRCHHIRRORRCIOCIOCOH() {
      List var1 = Collections.emptyList();
      return new CRRRICCRROCOHHOHIICIHORCOORRRH(
         null,
         this.RRORIRHCOHCIHOIOHHRHHCRCOCHHCR,
         var1,
         this.RRHHORCCCIRRIICHOHCCIIIRHICHCO,
         this.RRCROCCRIOIROHCCRCCIORICOCIOHC(var1),
         this.RCHCCCRROIROICIORRRCIOHCCIIORR,
         this.CCCIORORRIICIRCIROHOOOIHRIRCRO,
         this.COOCRRCCCIHOIIRIHHIHHCHRCHCHIC,
         this.ORCIOOOOOIIHRCCIOOIIOOCHHIHIOO.CRRIRCRIRCHCHIRCICOROIIOIIICCC(),
         this.RICIOHIOHICOIOHHOCRIOHIOCHIHHH
      );
   }

   private static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var0,
      List<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI> var1,
      boolean var2
   ) {
      Class var3 = var0.RRICIOOORRIORHHICIRCIOCHRHRCHH();
      if (var3 != CRCCIOCOOHORRHCCICOOIIIICHHIIR && var3 != IICORHIHHCRHIRIOIRICCIHHRCCHIH) {
         if (var2) {
            if (HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1, var3)) {
               return;
            }

            var1.add(var0);
         }

         for (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var5 : var0.getInterfaces()) {
            IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5, var1, true);
         }

         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var6 = var0.ROIOOCRIOROIICCRHICRHRCCIOOIHH();
         if (var6 != null) {
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, var1, true);
         }
      }
   }

   private static void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var0,
      List<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI> var1,
      boolean var2
   ) {
      Class var3 = var0.RRICIOOORRIORHHICIRCIOCHRHRCHH();
      if (var2) {
         if (HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1, var3)) {
            return;
         }

         var1.add(var0);
         if (var3 == RRIRHHHOORHIHOIIICCHRIOROICIRR || var3 == ICORCOHRRHRORRCCIIRCHCROCHHCIH) {
            return;
         }
      }

      for (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var5 : var0.getInterfaces()) {
         IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5, var1, true);
      }
   }

   private static boolean HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      List<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI> var0, Class<?> var1
   ) {
      int var2 = 0;

      for (int var3 = var0.size(); var2 < var3; var2++) {
         if (((com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI)var0.get(var2))
               .RRICIOOORRIORHHICIRCIOCHRHRCHH()
            == var1) {
            return true;
         }
      }

      return false;
   }

   private com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH RRCROCCRIOIROHCCRCCIORICOCIOHC(
      List<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI> var1
   ) {
      if (this.CCCIORORRIICIRCIROHOOOIHRIRCRO == null) {
         return ORHRIIIRIHRCCHHCORRIIORHHHIOII;
      }

      boolean var2 = this.COOCRRCCCIHOIIRIHHIHHCHRCHCHIC != null
         && (
            !(this.COOCRRCCCIHOIIRIHHIHHCHRCHCHIC instanceof IOHIHIIHCCCCCIHRORIOIOORCIOHII)
               || ((IOHIHIIHCCCCCIHRORIOIOORCIOHII)this.COOCRRCCCIHOIIRIHHIHHCHRCHCHIC).IIRCHCHICIRHIIIIIOOCCOHIRROIHH()
         );
      if (!var2 && !this.RICIOHIOHICOIOHHOCRIOHIOCHIHHH) {
         return ORHRIIIRIHRCCHHCORRIIORHHHIOII;
      }

      IIRHCHHOICHRICOOCRORCCIOOIHOIR var3 = IIRHCHHOICHRICOOCRORCCIOOIHOIR.HRRROIOROCICHHRROOHRHHOIOHRCRC();
      if (this.RRHHORCCCIRRIICHOHCCIIIRHICHCO != null) {
         var3 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, this.RRORIRHCOHCIHOIOHHRHHCRCOCHHCR, this.RRHHORCCCIRRIICHOHCCIIIRHICHCO);
      }

      if (this.RICIOHIOHICOIOHHOCRIOHIOCHIHHH) {
         var3 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var3,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CCHCOROOHHCIHOHOCHIHRHOHOCROII(
               this.RRORIRHCOHCIHOIOHHRHHCRCOCHHCR
            )
         );
      }

      for (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var5 : var1) {
         if (var2) {
            Class var6 = var5.RRICIOOORRIORHHICIRCIOCHRHRCHH();
            var3 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var6, this.COOCRRCCCIHOIIRIHHIHHCHRCHCHIC.IOHOOIOHCHICOCHIICHCICCOHRCIII(var6));
         }

         if (this.RICIOHIOHICOIOHHOCRIOHIOCHIHHH) {
            var3 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var3,
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CCHCOROOHHCIHOHOCHIHRHOHOCROII(
                  var5.RRICIOOORRIORHHICIRCIOCHRHRCHH()
               )
            );
         }
      }

      if (var2) {
         var3 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, Object.class, this.COOCRRCCCIHOIIRIHHIHHCHRCHCHIC.IOHOOIOHCHICOCHIICHCICCOHRCIII(Object.class));
      }

      return var3.CHCICCCHOOIHCCCCHHOHIRCROCHCCO();
   }

   private IIRHCHHOICHRICOOCRORCCIOOIHOIR RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIRHCHHOICHRICOOCRORCCIOOIHOIR var1, Class<?> var2, Class<?> var3) {
      if (var3 != null) {
         var1 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CCHCOROOHHCIHOHOCHIHRHOHOCROII(
               var3
            )
         );

         for (Class var5 : com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            var3, var2, false
         )) {
            var1 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1,
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CCHCOROOHHCIHOHOCHIHRHOHOCROII(
                  var5
               )
            );
         }
      }

      return var1;
   }

   private IIRHCHHOICHRICOOCRORCCIOOIHOIR RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIRHCHHOICHRICOOCRORCCIOOIHOIR var1, Annotation[] var2) {
      if (var2 != null) {
         for (Annotation var6 : var2) {
            if (!var1.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var6)) {
               var1 = var1.CRRRICCRROCOHHOHIICIHORCOORRRH(var6);
               if (this.CCCIORORRIICIRCIROHOOOIHRIRCRO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var6)) {
                  var1 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var6);
               }
            }
         }
      }

      return var1;
   }

   private IIRHCHHOICHRICOOCRORCCIOOIHOIR RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIRHCHHOICHRICOOCRORCCIOOIHOIR var1, Annotation var2) {
      for (Annotation var6 : com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CCHCOROOHHCIHOHOCHIHRHOHOCROII(
         var2.annotationType()
      )) {
         if (!(var6 instanceof Target) && !(var6 instanceof Retention) && !var1.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var6)) {
            var1 = var1.CRRRICCRROCOHHOHIICIHORCOORRRH(var6);
            if (this.CCCIORORRIICIRCIROHOOOIHRIRCRO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var6)) {
               var1 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var6);
            }
         }
      }

      return var1;
   }
}
