package com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

import com.google.gson.JsonObject;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHOOIOHCHICOCHIICHCICCOHRCIII.HHCCIRHCCCIIRHCROHIORHIRHHIORH;
import com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends CRRRICCRROCOHHOHIICIHORCOORRRH {
   private final boolean OIHOHIRRIHIHIRCICORCHIHRCIROCI;
   private final Boolean COIHCRRCCCOOHCRHICIOOHOCRHOHCR;

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .IHCOOOOCIIRCCCCCOCCHICRHCRICIO();
      com.moonsworth.lunar.client.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var2 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.IOCHHHIIRIHOIRHHICHICCRIHOIOHC
      );
      this.COIHCRRCCCOOHCRHICIOOHOCRHOHCR = var2 == null ? null : (Boolean)var2.RROOOOIIOCRRHIOHCHRIOIIIHCHCCH().orElse(null);
      this.OIHOHIRRIHIHIRCICORCHIHRCIROCI = var1.isEnabled();
   }

   @Override
   protected void RIROICHCRROROHCCROOCCCCOCHCCRI(JsonObject var1) {
      super.RIROICHCRROROHCCROOCCCCOCHCCRI(var1);
      var1.addProperty("enabled", this.OIHOHIRRIHIHIRCICORCHIHRCIROCI);
      if (this.COIHCRRCCCOOHCRHICIOOHOCRHOHCR != null) {
         var1.addProperty("locked", this.COIHCRRCCCOOHCRHICIOOHOCRHOHCR);
      }
   }
}
