package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import lombok.Generated;
import org.jetbrains.annotations.Nullable;

public class RIOOCHICIHRHOHCCCCCHOCCCOHCRHI {
   private static final double IHIOICOIHHRCICIIIOIHORIOCCIHOI = 60.0;
   private static final double RIHCICCCIIOIOIIRHOIORCHRCCIHHO = 0.5;
   private static final double IIIRCOOIIOOROHROOOOHCIRRCCRRIR = 5.0;
   private boolean IIRORICCORCORRHHCHIIIIHHCOCROR;
   private boolean CRIHOICHCOIHIOHOCOHCORHIOHCOIH;
   private double COROCIOCCICRIHRIOHOOHOICHRIHRC;
   @Nullable
   private RORCHCIIICOHIRROOORHOCCCCIOCCI RICCOOCHIHHCROOCCRCOIRHCCCCICH;

   public void CROOHCCRIHRORCOOROOIOIOOOHIHIO() {
      this.IIRORICCORCORRHHCHIIIIHHCOCROR = !this.IIRORICCORCORRHHCHIIIIHHCOCROR;
      this.COROCIOCCICRIHRIOHOOHOICHRIHRC = 5.0;
      this.RICCOOCHIHHCROOCCRCOIRHCCCCICH = null;
   }

   public void IRORORHIRRCIHRHHCCHHORRCRCROHH() {
      this.CRIHOICHCOIHIOHOCOHCORHIOHCOIH = !this.CRIHOICHCOIHIOHOCOHCORHIOHCOIH;
      this.COROCIOCCICRIHRIOHOOHOICHRIHRC = 5.0;
   }

   public void reset() {
      this.IIRORICCORCORRHHCHIIIIHHCOCROR = false;
      this.RICCOOCHIHHCROOCCRCOIRHCCCCICH = null;
   }

   public void IIRHCHHOICHRICOOCRORCCIOOIHOIR(RORCHCIIICOHIRROOORHOCCCCIOCCI var1) {
      this.RICCOOCHIHHCROOCCRCOIRHCCCCICH = var1;
   }

   public boolean OHHRIOHROOIHOROCIRHCHORIHRRRRI(@Nullable RORCHCIIICOHIRROOORHOCCCCIOCCI var1) {
      if (this.RICCOOCHIHHCROOCCRCOIRHCCCCICH == null) {
         return false;
      }

      if (this.RICCOOCHIHHCROOCCRCOIRHCCCCICH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1)) {
         return true;
      }

      this.RICCOOCHIHHCROOCCRCOIRHCCCCICH = null;
      return false;
   }

   public void IOHHOIIOCRHCHHCRORICCOHOHROOIH(double var1) {
      if (this.IIRORICCORCORRHHCHIIIIHHCOCROR && this.CRIHOICHCOIHIOHOCOHCORHIOHCOIH && var1 != 0.0) {
         double var3 = var1 > 0.0 ? 0.5 : -0.5;
         this.COROCIOCCICRIHRIOHOOHOICHRIHRC = Math.max(1.0, this.COROCIOCCICRIHRIOHOOHOICHRIHRC + var3);
      }
   }

   @Nullable
   public RORCHCIIICOHIRROOORHOCCCCIOCCI CRIOCIIRICICOIRIHOHOOCCIICHIRR() {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      if (var1 != null && var2 != null) {
         double var3 = this.CRIHOICHCOIHIOHOCOHCORHIOHCOIH ? Math.max(1.0, this.COROCIOCCICRIHRIOHOOHOICHRIHRC) : 60.0;
         CRHROHHHCIHHCOHCOORCRIHHIICROR var5 = var1.bridge$getEyePosition();
         RORCHCIIICOHIRROOORHOCCCCIOCCI[] var6 = new RORCHCIIICOHIRROOORHOCCCCIOCCI[1];
         ((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIIROOHHCOOHCHHRIIOOCRRCIHRICH
               )
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var3, 0.0F)
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  (var0, var1x) -> !var1x.bridge$getBlock().bridge$isAir()
                     && var1x.bridge$getRenderShape()
                        != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.INVISIBLE
               )
               .OHCOIORHOCCRICIHIOIRHRIRROCHRR()
               .CHRCRHHRCCOICCOOIIRIOHCOHCHHIC(var2))
            .HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var1x -> var6[0] = var1x.HRICRCHIIHIIICIHCICRHOOCRCCHIO());
         if (var6[0] != null) {
            if (this.CRIHOICHCOIHIOHOCOHCORHIOHCOIH) {
               double var13 = var6[0].bridge$getX() + 0.5 - var5.bridge$xCoord();
               double var14 = var6[0].bridge$getY() + 0.5 - var5.bridge$yCoord();
               double var11 = var6[0].bridge$getZ() + 0.5 - var5.bridge$zCoord();
               this.COROCIOCCICRIHRIOHOOHOICHRIHRC = Math.max(
                  1.0, Math.min(this.COROCIOCCICRIHRIOHOOHOICHRIHRC, Math.sqrt(var13 * var13 + var14 * var14 + var11 * var11))
               );
            }

            return var6[0];
         } else {
            double var7 = this.CRIHOICHCOIHIOHOCOHCORHIOHCOIH ? var3 : 5.0;
            CRHROHHHCIHHCOHCOORCRIHHIICROR var9 = var1.bridge$getViewVector(1.0F);
            return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  (int)Math.floor(var5.bridge$xCoord() + var9.bridge$xCoord() * var7),
                  (int)Math.floor(var5.bridge$yCoord() + var9.bridge$yCoord() * var7),
                  (int)Math.floor(var5.bridge$zCoord() + var9.bridge$zCoord() * var7)
               );
         }
      } else {
         return null;
      }
   }

   @Generated
   public boolean RHRRRICHCCRRIIRCOCCRCRIHICRHRR() {
      return this.IIRORICCORCORRHHCHIIIIHHCOCROR;
   }

   @Generated
   public boolean RCRRCHHCICRCHCCCIRIIOCCCHHORRI() {
      return this.CRIHOICHCOIHIOHOCOHCORHIOHCOIH;
   }
}
