package com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CIOHHCORHRCCRICCCORIHCRHCCCRRR;

import java.awt.image.BufferedImage;

public interface IHIRRIIORRHORHRORIHOROIRCORCOO {
   int ROHIRHRRROOCCHOCIIOIRIOCRIRHII();

   void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(int var1, BufferedImage var2);

   void IOIICIRIICICIIOORHCIIIIRRIHRHI(int var1);
}
