package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import java.util.function.Predicate;
import lombok.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

class OOROOCCIRCCRHOIOIORIHCHHOOCCOR extends RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final Predicate<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH> predicate;

   @Override
   protected boolean IIHRRHORCRCROCHHOHORCHCROCIHRO(@NotNull IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      return this.predicate.test(var1.bridge$getItem());
   }

   @Override
   public float HRCHROOHRIHCRCRHRIIROCIRHOIRHH(@NotNull HHCCIRHCCCIIRHCROHIORHIRHHIORH var1) {
      float var2 = var1.bridge$getCooldown(this.HIROCOCHORRCHIOIIIOIIRHOIROOCH());
      return var2 == -1.0F ? 1.0F : 1.0F - var2;
   }

   @Override
   public boolean CORCOCICIRIOHROHROIIOOHICCHCRR(@NotNull HHCCIRHCCCIIRHCROHIORHIRHHIORH var1) {
      return var1.bridge$getCooldown(this.HIROCOCHORRCHIOIIIOIIRHOIROOCH()) != -1.0F;
   }

   @Nullable
   @Override
   public IIRHCHHOICHRICOOCRORCCIOOIHOIR OOROOCCIRCCRHOIOIORIHCHHOOCCOR(@NotNull HHCCIRHCCCIIRHCROHIORHIRHHIORH var1) {
      return this.HIROCOCHORRCHIOIIIOIIRHOIROOCH();
   }

   @Generated
   public OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
      Predicate<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH> var1
   ) {
      this.predicate = var1;
   }
}
