package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.util.CRHHOOCRCOHHRHOOOCHCROOHIOOCOH;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO;
import lombok.Generated;

public class HRCHROOHRIHCRCRHRIIROCIRHOIRHH extends RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IIHRRHORCRCROCHHOHORCHCROCIHRO HHHHIHCCCHCOCIHIHRHHCIRRHCICOC = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IIHRRHORCRCROCHHOHORCHCROCIHRO();
   private boolean OCIHCCOOROHOOOIIOIOHOHCHORIICH = false;
   private boolean CCOOHCHORCCRHROOCHIOHRIICORCIH = false;
   private int HRHHOCHCOHCOHOICIHHHIHCIORCOCO = 0;
   private int IIROOHRRCROCCHRCROORIHIHIIRORI = 0;
   private int COOIHHHCHOCCRRCOROHOHHHCHCOORC = 0;
   private int OOHOROCRIHRRCCHRIOHHCHHHIIIOCC = 0;
   private boolean IOCHHHCICCHRRIHOIRCRICIHHORRHR = false;
   private boolean HRHOOOCICRRHOOCORRRHIROCRIIIHO = false;
   private boolean ROHIOICICOCHCHHCRIROCRRRIORIHR = true;
   private ORHIOICIOCRRHOOCOHRORIHICHRCRR RRRHICCIOOIIHOCIHORCIROICRRRHI;
   private boolean OIIHHIHCROIROIROIORICRCOICIIOI = false;
   private boolean HHROHHRHCIHHIIRCHIRRIHRRICCRIO = true;
   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH IOIOOOHHOHIHIORIHCIIORHIHOOCHI;

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      IIHRHCCOOHOOOOCHRRCOROOIOHCOOO<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH> var1
   ) {
      super(var1);
   }

   public void OCICIRIHHRIRRCCHIHIRCIHOIROOII() {
      this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.OOICHHIHHIHROCCRRRIIIIRIRICCIH(false);
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION <= 5) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRICIORORHCRHCCCIIIHRRHCICOHOR().ifPresent(var1 -> {
            this.IOCHHHCICCHRRIHOIRCRICIHHORRHR = var1.getConfig().hasFastRender();
            if (this.IOCHHHCICCHRRIHOIRCRICIHHORRHR) {
               var1.getConfig().setFastRender(false);
               var1.getConfig().updateFramebufferSize();
            }
         });
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRICIORORHCRHCCCIIIHRRHCICOHOR()
         .ifPresent(
            var1 -> {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.CRRRICCRROCOHHOHIICIHORCOORRRH var2 = var1.getConfig();
               if (var2.hasAntiAliasing()
                  && var2.getAntialiasingLevel() > 0
                  && com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ROIHIHHCCIIRHRORHHCRCHIOCRIOCC
                     == null) {
                  com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORIOCIHCOOCHRHOIROORHHCIROCIHO = var2.getAntialiasingLevel();
                  com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ROIHIHHCCIIRHRORHHCRCHIOCRIOCC = 0;
                  com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CROCOIRICICICRHCIHHRRRRIIHCOCR = true;
                  this.HRHOOOCICRRHOOCORRRHIROCRIIIHO = true;
               }
            }
         );
      this.OIOROIRHRRIRCHIIORCCCCCCCHCHCO();
   }

   public void CHIIIOCOIIIROOOHCHCICOHCHRHIOI() {
      if (this.ROHIOICICOCHCHHCRIROCRRRIORIHR) {
         this.ROHIOICICOCHCHHCRIROCRRRIORIHR = false;
         this.RRRHICCIOOIIHOCIHORCIROICRRRHI = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen();
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
            .bridge$setCurrentScreenSilent(this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR.get().HHOHIHRCICOIICIIOHHHRHROHCHICI().RCORHIHICHCOORRRHCHCRICCHICOOO());
      }
   }

   public boolean OHIIIOHIRIRCCRRIOIICCHHIORRHOH(int var1, int var2) {
      boolean var3 = this.COOIHHHCHOCCRRCOROHOHHHCHCOORC != IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$logicalWidth()
         || this.OOHOROCRIHRRCCHRIOHHCHHHIIIOCC != IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$logicalHeight();
      if (var3) {
         return false;
      }

      if (this.CCOOHCHORCCRHROOCHIOHRIICORCIH) {
         return true;
      }

      this.HRHHOCHCOHCOHOICIHHHIHCIORCOCO = var1;
      this.IIROOHRRCROCCHRCROORIHIHIIRORI = var2;
      this.CCOOHCHORCCRHROOCHIOHRIICORCIH = true;
      return true;
   }

   public void HRRRCOHOIIOCIRCRIIIHRICROCCOHC() {
      if (this.CCOOHCHORCCRHROOCHIOHRIICORCIH) {
         this.mc.bridge$setDisplayWidth(this.HRHHOCHCOHCOHOICIHHHIHCIORCOCO);
         this.mc.bridge$setDisplayHeight(this.IIROOHRRCROCCHRCROORIHIHIIRORI);
         this.mc.bridge$setGuiScale(this.mc.bridge$getGameSettings().bridge$getGuiScale());
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIHOOHCHOCIIHRIORCRCHHOOCRIRHH(
            false
         );
         CRHHOOCRCOHHRHOOOCHCROOHIOOCOH var1 = new CRHHOOCRCOHHRHOOOCHCROOHIOOCOH(this.mc);
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            var1
         );
         this.CCOOHCHORCCRHROOCHIOHRIICORCIH = false;
      }
   }

   public boolean RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(int var1, int var2, boolean var3) {
      boolean var4 = this.COOIHHHCHOCCRRCOROHOHHHCHCOORC != IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$logicalWidth()
         || this.OOHOROCRIHRRCCHRIOHHCHHHIIIOCC != IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$logicalHeight();
      if (var4) {
         this.COOIHHHCHOCCRRCOROHOHHHCHCOORC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$logicalWidth();
         this.OOHOROCRIHRRCCHRIOHHCHHHIIIOCC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$logicalHeight();
         return false;
      }

      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get()
         .HCIRHHCHORHRORHHCIOHCIHIIRCHIO();
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var6 = var5.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO()
         .RROHROIOCRIORIOIRIHRRRRHRIHRII();
      boolean var7 = var5.RICCCROHOIOCHORIRCHIIOORHIRHHR() && !var5.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().IOHHOICRCORHRCICOCHIORRHHHCORC();
      if (var7) {
         this.OIOROIRHRRIRCHIIORCCCCCCCHCHCO();
      } else {
         this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC
            .OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
               Math.max(1, (int)var5.CRIHIHOIOOCIRHHIROIHCHOHIIHIOC()),
               Math.max(1, (int)var5.CORRCHOOOOOCHRHOCHHOCORRCIHRRO()),
               this.HRHOOOCICRRHOOCORRRHIROCRIIIHO
                  && com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ROIHIHHCCIIRHRORHHCRCHIOCRIOCC
                     == null
            );
      }

      if (var6 != null && !var6.CCRIRHRIHHHRIHCIOHIHOCCCCCOIIR()) {
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIHOOHCHOCIIHRIORCRCHHOOCRIRHH(
            var7
         );
         this.OHIIIOHIRIRCCRRIOIICCHHIORRHOH(var1, var2);
         this.OIIHHIHCROIROIROIORICRCOICIIOI = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$hasOverlay();
         if (!this.OCIHCCOOROHOOOIIOIOHOHCHORIICH) {
            this.IOIOOOHHOHIHIORIHCIIORHIHOOCHI = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getMainRenderTarget();
         }

         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
            .bridge$setMainRenderTarget(this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.HOIHRCIOCIHORHIRHCOHRHHCCHOOOR());
         this.OCIHCCOOROHOOOIIOIOHOHCHORIICH = true;
         this.IRHROROCOIIRCOOOCOCICOIIIOOIHO();
         if (this.HHROHHRHCIHHIIRCHIRRIHRRICCRIO) {
            this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.HOIHRCIOCIHORHIRHCOHRHHCCHOOOR().bridge$framebufferClear();
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.HOIHRCIOCIHORHIRHCOHRHHCCHOOOR(), var3);
         } else {
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getMainRenderTarget().bridge$unbindFrameBuffer();
         }

         this.HRHOOOCICRRHOOCORRRHIROCRIIIHO = com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ROIHIHHCCIIRHRORHHCRCHIOCRIOCC
            != null;
         return true;
      } else {
         this.OCIHCCOOROHOOOIIOIOHOHCHORIICH = false;
         return false;
      }
   }

   public void HOHHOIHOOIOCOCHRHHHRIRICRHIRIO() {
      if (!this.ROHIOICICOCHCHHCRIROCRRRIORIHR) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$setCurrentScreenSilent(this.RRRHICCIOOIIHOCIHORCIROICRRRHI);
         this.ROHIOICICOCHCHHCRIROCRRRIORIHR = true;
      }
   }

   public void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1
   ) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get()
         .HCIRHHCHORHRORHHCIOHCIHIIRCHIO();
      RRCRRCORICCHOHHIRCHIROOHIIOHCO var3 = var2.OIOOIICIICCCIOCHROHIIRCCORIHOR();
      var3.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1);
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 6) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getRenderBuffers().bridge$bufferSource().bridge$endBatch();
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI();
      if (this.OCIHCCOOROHOOOIIOIOHOHCHORIICH) {
         var2.OIRIRIIORHRCHRCHROORRROIRROIRI().OHRHIIIOCRORCRHCOHHIRIORHCORRH();
         this.OCIHCCOOROHOOOIIOIOHOHCHORIICH = false;
         this.HRRRCOHOIIOCIRCRIIIHRICROCCOHC();
         var4.bridge$setMainRenderTarget(this.IOIOOOHHOHIHIORIHCIIORHIHOOCHI);
         this.IOIOOOHHOHIHIORIHCIIORHIHOOCHI = null;
      }

      this.OCIHCCOOROHOOOIIOIOHOHCHORIICH = false;
      IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(null, true);
      this.HRRRCOHOIIOCIRCRIIIHRICROCCOHC();
      float var5 = com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.ROHHOOHOHCHRIICCCHCOHCORROHRIH()
         .IOCIOIHIOOCRHHORHHCOOHIIHICOCH();
      float var6 = com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IOCCCRIHOCHRCHRHCRHROIRIRHHHIR(
         var4.bridge$displayWidth() / var5
      );
      float var7 = com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IOCCCRIHOCHRCHRHCRHROIRIRHHHIR(
         var4.bridge$displayHeight() / var5
      );
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.GL_PROJECTION
      );
      var1.HIHROCOCCHRHHRROHCRCCHOIRCHIHI();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHCHRCCRRHORIOCIOHHCRHCHICRIHH().bridge$loadIdentity();
      var1.HHCCIRHCCCIIRHCROHIORHIRHHIORH(0.0, var6, var7, 0.0, 1000.0, IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 29 ? 21000.0 : 3000.0);
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.GL_MODELVIEW
      );
      var1.HIHROCOCCHRHHRROHCRCCHOIRCHIHI();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHCHRCCRRHORIOCIOHHCRHCHICRIHH().bridge$loadIdentity();
      var1.translate(0.0, 0.0, -2000.0);
      HICHRCOHCCRHOHCICOOCHOIHCCHIRI var8 = var2.RCHHHIICCRCOROCHCCOICIOIIRIHHO();
      var8.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, var3, var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR());
   }

   private void OIOROIRHRRIRCHIIORCCCCCCCHCHCO() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get()
         .HCIRHHCHORHRORHHCIOHCIHIIRCHIO()
         .HOCCHIRHIIOOOIHIHHICHRIRIHHHRO()
         .RROHROIOCRIORIOIRIHRRRRHRIHRII();
      if (var1 != null) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = var1.RHCHIOHOIHHCIROCRCIRIOCRRHROII();
         this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC
            .OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
               Math.max(1, var2.getWidth()),
               Math.max(1, var2.getHeight()),
               this.HRHOOOCICRRHOOCORRRHIROCRIIIHO
                  && com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ROIHIHHCCIIRHRORHHCRCHIOCRIOCC
                     == null
            );
         RRCRRCORICCHOHHIRCHIROOHIIOHCO var3 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR.get().HCIRHHCHORHRORHHCIOHCIHIIRCHIO().OIOOIICIICCCIOCHROHIIRCCORIHOR();
         var3.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var2);
      }
   }

   public void IRHROROCOIIRCOOOCOCICOIIIOOIHO() {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
         .bridge$getGameRenderer();
      if (var1 != null && this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.HOIHRCIOCIHORHIRHCOHRHHCCHOOOR() != null) {
         int var2 = this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.HOIHRCIOCIHORHIRHCOHRHHCCHOOOR().bridge$framebufferWidth();
         int var3 = this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.HOIHRCIOCIHORHIRHCOHRHHCCHOOOR().bridge$framebufferHeight();
         if (var1.bridge$getRenderTargetsWidth() != var2 || var1.bridge$getRenderTargetsHeight() != var3) {
            var1.bridge$resize(var2, var3);
         }

         OOROOCCIRCCRHOIOIORIHCHHOOCCOR var4 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR.get().HCIRHHCHORHRORHHCIOHCIHIIRCHIO().CIORCCHHRCROIIHRORCCIRHCICORHH();
         var4.IIOORRCRHCRIORIOCOHHIROOIIHROC(false);
      }
   }

   public void IOOCOOIHOHRHRRHOHCRICHIRCIIIHO() {
      this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.HOIHRCIOCIHORHIRHCOHRHHCCHOOOR().bridge$framebufferClear();
   }

   public void CRIHCRHCICHOIICRRRCCCHORROIHRC() {
      if (this.IOCHHHCICCHRRIHOIRCRICIHHORRHR) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
            .bridge$schedule(
               () -> com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRICIORORHCRHCCCIIIHRRHCICOHOR().ifPresent(var0 -> {
                  var0.getConfig().setFastRender(true);
                  var0.getConfig().updateFramebufferSize();
               })
            );
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRICIORORHCRHCCCIIIHRRHCICOHOR()
         .ifPresent(
            var0 -> {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.CRRRICCRROCOHHOHIICIHORCOORRRH var1 = var0.getConfig();
               if (com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CROCOIRICICICRHCIHHRRRRIIHCOCR
                  && com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ROIHIHHCCIIRHRORHHCRCHIOCRIOCC
                     == null
                  && var1.getAntialiasingLevel() == 0
                  && com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORIOCIHCOOCHRHOIROORHHCIROCIHO
                     != null) {
                  com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ROIHIHHCCIIRHRORHHCRCHIOCRIOCC = com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORIOCIHCOOCHRHOIROORHHCIROCIHO;
                  com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CROCOIRICICICRHCIHHRRRRIIHCOCR = false;
               }
            }
         );
      IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(null, true);
      this.HRRRCOHOIIOCIRCRIIIHRICROCCOHC();
      if (this.OCIHCCOOROHOOOIIOIOHOHCHORIICH) {
         this.mc.bridge$setMainRenderTarget(this.IOIOOOHHOHIHIORIHCIIORHIHOOCHI);
         this.IOIOOOHHOHIHIORIHCIIORHIHOOCHI = null;
         this.OCIHCCOOROHOOOIIOIOHOHCHORIICH = false;
      }
   }

   public int getWidth() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get()
         .HCIRHHCHORHRORHHCIOHCIHIIRCHIO();
      boolean var2 = var1.RICCCROHOIOCHORIRCHIIOORHIRHHR() && !var1.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().IOHHOICRCORHRCICOCHIORRHHHCORC();
      if (var2) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var1.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO()
            .RROHROIOCRIORIOIRIHRRRRHRIHRII();
         return var3 != null
            ? var3.RHCHIOHOIHHCIROCRCIRIOCRRHROII().getWidth()
            : this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.HOIHRCIOCIHORHIRHCOHRHHCCHOOOR().bridge$framebufferWidth();
      } else {
         return Math.max(1, (int)var1.CRIHIHOIOOCIRHHIROIHCHOHIIHIOC());
      }
   }

   public int getHeight() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get()
         .HCIRHHCHORHRORHHCIOHCIHIIRCHIO();
      boolean var2 = var1.RICCCROHOIOCHORIRCHIIOORHIRHHR() && !var1.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().IOHHOICRCORHRCICOCHIORRHHHCORC();
      if (var2) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var1.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO()
            .RROHROIOCRIORIOIRIHRRRRHRIHRII();
         return var3 != null
            ? var3.RHCHIOHOIHHCIROCRCIRIOCRRHROII().getHeight()
            : this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC.HOIHRCIOCIHORHIRHCOHRHHCCHOOOR().bridge$framebufferHeight();
      } else {
         return Math.max(1, (int)var1.CORRCHOOOOOCHRHOCHHOCORRCIHRRO());
      }
   }

   @Generated
   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IIHRRHORCRCROCHHOHORCHCROCIHRO HHRRRORIICOCHCOOOORHHOOHHIOHHI() {
      return this.HHHHIHCCCHCOCIHIHRHHCIRRHCICOC;
   }

   @Generated
   public boolean HOOHHCICCHCRCHHCOHHICCCOOHHCIH() {
      return this.OCIHCCOOROHOOOIIOIOHOHCHORIICH;
   }

   @Generated
   public void CRICCIRRRCIICCHOOIORCHIHIIROHO(boolean var1) {
      this.OCIHCCOOROHOOOIIOIOHOHCHORIICH = var1;
   }

   @Generated
   public int HIIIRHIIIOHIHORIROOCCRHIIRRCOH() {
      return this.HRHHOCHCOHCOHOICIHHHIHCIORCOCO;
   }

   @Generated
   public void IIHROHOIOHICCRRHRICHCIHRCROOIO(int var1) {
      this.HRHHOCHCOHCOHOICIHHHIHCIORCOCO = var1;
   }

   @Generated
   public int RROHOHHORRCCHCOCOCRHHRHHOOHCRO() {
      return this.IIROOHRRCROCCHRCROORIHIHIIRORI;
   }

   @Generated
   public void CRICCIRRRCIICCHOOIORCHIHIIROHO(int var1) {
      this.IIROOHRRCROCCHRCROORIHIHIIRORI = var1;
   }

   @Generated
   public boolean ORIRCRRRIOCHHHCORCCOOROCIOIIOH() {
      return this.OIIHHIHCROIROIROIORICRCOICIIOI;
   }

   @Generated
   public boolean CHOCHRICCRRICICHORORRICROCOIIO() {
      return this.HHROHHRHCIHHIIRCHIRRIHRRICCRIO;
   }

   @Generated
   public void COCOHIHCICRHOOCHIHCCORHHIRHIOH(boolean var1) {
      this.HHROHHRHCIHHIIRCHIRRIHRRICCRIO = var1;
   }
}
