package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.lunarclient.dfu.serialization.Codec;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IHICORCROOROHCIHIHCOIHRRHICICO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RICRIRRCOHRCOCRRHHCRHRROOIOHHR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IHCRORHRORIICHRHRCHRRIRRHHOCOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO;
import com.moonsworth.lunar.client.util.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.Map.Entry;
import lombok.Generated;
import org.apache.commons.lang3.Range;
import org.joml.Matrix3d;
import org.joml.Vector3d;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CORCOROCCCICOORHHRCOHOIHOIOHHI;
   private final HCHRIROHHHCORIOCROOCHRCIOROOCI<String> OHCHOOIHIOCIRRHRHOIRCOIHIICROH = this.CRCCIIOORIROOIIIHIRHOIHCIIICOR();
   private final RIROICHCRROROHCCROOCCCCOCHCCRI<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> HRRCHROCHCHORHCIRICRIHCIICCRHH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         "cameraMode",
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.POV
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RIROICHCRROROHCCROOCCCCOCHCCRI<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH> IOORRIICROOCRHOORCICRHRCRROCRI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         "follow",
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.POSITION
      )
      .OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
         () -> this.HRRCHROCHCHORHCIRICRIHCIICCRHH.get()
            != com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FOLLOW
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final IHICORCROOROHCIHIHCOIHRRHICICO<Double> RCIHRHRHOHOHOCHORCCIHHIRIHRHIO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "positionRotationFreecam", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
      )
      .IRCIIHHICIHRCOCRROCOICRIHHCCHH(Codec.DOUBLE.listOf())
      .OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
         () -> this.HRRCHROCHCHORHCIRICRIHCIICCRHH.get()
            != com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FREE_CAMERA
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final IHICORCROOROHCIHIHCOIHRRHICICO<Double> HCIHOCCOIHHHCHOHIHRRHCRICRIORH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "positionRotationFollow", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
      )
      .IRCIIHHICIHRCOCRROCOICRIHHCCHH(Codec.DOUBLE.listOf())
      .OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
         () -> this.HRRCHROCHCHORHCIRICRIHCIICCRHH.get()
            != com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FOLLOW
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IIHCHCIOCOIOOICCRICIRRHCHOCCIR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "cameraShake"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final IHIRRIIORRHORHRORIHOROIRCORCOO IOOHRICHRIIHRRCCRIIHHRROHCHRCC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH("intensity")
      .RROIIRROOOOHIORHRICHOCHIHCRRCH(1.0F)
      .CRHROHHHCIHHCOHCOORCRIHHIICROR(0.0F, 10.0F)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final IHIRRIIORRHORHRORIHOROIRCORCOO RCIIIHOHCIOCIOHICCOIIIOCOROCRH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH("speed")
      .RROIIRROOOOHIORHRICHOCHIHCRRCH(1.0F)
      .CRHROHHHCIHHCOHCOORCRIHHIICROR(0.0F, 10.0F)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI ICICHORRHCCCHRHRHICHHCOIIHHHOI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "cameraFov"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final IHIRRIIORRHORHRORIHOROIRCORCOO HHCHCIOROIIHRIORRROIIICHCHORHO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH("fov")
      .RROIIRROOOOHIORHRICHOCHIHCRRCH(70.0F)
      .CRHROHHHCIHHCOHCOORCRIHHIICROR(1.0F, 130.0F)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI ORRICOHORHCIOIRIRHCHHRHCHCHHHC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "hideHud"
      )
      .OOROOCCIRCCRHOIOIORIHCHHOOCCOR(() -> this.HRRCHROCHCHORHCIRICRIHCIICCRHH.get().isFixedToPlayer())
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI ORHIRIHOOHROICROCOHRCHCOHHICCC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "forceHideHud"
      )
      .OOROOCCIRCCRHOIOIORIHCHHOOCCOR(() -> !this.HRRCHROCHCHORHCIRICRIHCIICCRHH.get().isFixedToPlayer())
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IIHRRHORCRCROCHHOHORCHCROCIHRO OCCHICCIRHHHRRRRCCHIOCIROIHOOI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH(
         "teleportToTarget"
      )
      .RCIROOOOICRHCCRRCIORHHIRCOIIIC(
         () -> {
            if (this.CORCOROCCCICOORHHRCOHOIHOIOHHI instanceof com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1x
               )
             {
               var1x.CICRHHROIHRICORCOICIHOIORCRROH();
            }
         }
      )
      .OOROOCCIRCCRHOIOIORIHCHHOOCCOR(() -> this.HRRCHROCHCHORHCIRICRIHCIICCRHH.get().isFixedToPlayer())
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RIHOOOHRRCROHRICOOOOOIHIOOIRHI = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      this
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CCCHCIIOICHRORHOOOCIRROHRRRICH = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      this
   );
   private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OCORHOIOHRHRIIRROCHRRROIOIOCRI = null;

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      IIHRHCCOOHOOOOCHRRCOROOIOHCOOO<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH> var1
   ) {
      super(var1);
      this.handle(OHHRIOHROOIHOROCIRHCHORIHRRRRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.class,
         this::IRCIIHHICIHRCOCRROCOICRIHHCCHH
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.class,
         this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IHIRRIIORRHORHRORIHOROIRCORCOO.class,
         this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      );
      this.handle(RICRIRRCOHRCOCRRHHCRHRROOIOHHR.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(IHCRORHRORIICHRHRCHRRIRRHHOCOO.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION == 1) {
         this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      }

      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.class,
         this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         this::IRCIIHHICIHRCOCRROCOICRIHHCCHH
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class,
         this::RIOOCHICIHRHOHCCCCCHOCCCOHCRHI
      );
      this.update();
   }

   public void update() {
      if (this.OCORHOIOHRHRIIRROCHRRROIOIOCRI != this.CHORCRORCICOCOOORCIOOICCOOIOHC()) {
         this.CORCOROCCCICOORHHRCOHOIHOIOHHI = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.CHORCRORCICOCOOORCIOOICCOOIOHC());
         this.OCORHOIOHRHRIIRROCHRRROIOIOCRI = this.CHORCRORCICOCOOORCIOOICCOOIOHC();
         this.CORCOROCCCICOORHHRCOHOIHOIOHHI.RIHOOCIHRICOCHRHCOOCCOIHOCHRCR(0.0F);
      }
   }

   private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      if (var1.isFixedToPlayer()) {
         return this.CCCHCIIOICHRORHOOOCIRROHRRRICH;
      }

      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = this.OCORHOIOHRHRIIRROCHRRROIOIOCRI;
      IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
         .bridge$schedule(
            () -> {
               if (this.ICHHOIRROHCRCHHOOCRCIHIICORHRR().isDefault()
                  || var2
                        == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FOLLOW
                     && !this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR.get().HCIRHHCHORHRORHHCIOHCIHIIRCHIO().RICCCROHOIOCHORIRCHIIOORHIRHHR()) {
                  ((com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)this.RIHOOOHRRCROHRICOOOOOIHIOOIRHI)
                     .CICRHHROIHRICORCOICIHOIORCRROH();
               }

               this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR.get().HCIRHHCHORHRORHHCIOHCIHIIRCHIO().OIRIRIIORHRCHRCHROORRROIRROIRI().CCROOCHIICHORIRRIHHOIICHORHRCC();
               IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getLevelRenderer().bridge$reloadChunks();
            }
         );
      return this.RIHOOOHRRCROHRICOOOOOIHIOOIRHI;
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(OHHRIOHROOIHOROCIRHCHORIHRRRRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.CORCOROCCCICOORHHRCOHOIHOIOHHI.RIHOOCIHRICOCHRHCOOCCOIHOCHRCR(var1.CRIRICHHRCIORIOHOHHICHROIHOCRR());
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RICRIRRCOHRCOCRRHHCRHRROOIOHHR var1) {
      this.CORCOROCCCICOORHHRCOHOIHOIOHHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH var1) {
      if (!this.CHORCRORCICOCOOORCIOOICCOOIOHC().isFirstPerson()
         || IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getRenderViewEntity()
            != IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH()) {
         var1.cancel();
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var1
   ) {
      if (var1.HIRHCCCROOHORORRRRCHICHROHRRIH().bridge$isSelf()
         && IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSpectatedEntity() != null) {
         var1.cancel();
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      if (this.ICICHORRHCCCHRHRHICHHCOIIHHHOI.get()) {
         var1.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(this.HHCHCIOROIIHRIORRROIIICHCHORHO.get());
      }
   }

   private void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get()
         .HCIRHHCHORHRORHHCIOHCIHIIRCHIO();
      if (!var2.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().IOHHOICRCORHRCICOCHIORRHHHCORC()) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
            .get()
            .RCRHOCOIIRCHRIRIIOHCOCCRHCHCCR();
         if (var3 != null
            && (var3.CHRHOHORRICRRHRCRCICOORCHHCIOH() || !var2.RICCCROHOIOCHORIRCHIIOORHIRHHR())
            && !var2.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IHRHHIOIIICOROOORIOHCIROIRCOHH();
            if (var4 != null) {
               Vector3d var5 = new Vector3d(var4.bridge$renderPosX(), var4.bridge$renderPosY(), var4.bridge$renderPosZ());
               LinkedHashSet var6 = new LinkedHashSet();
               Set var7 = new LinkedHashSet();
               float var8 = 1.54F;
               if (IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getRenderViewEntity() != null) {
                  var8 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getRenderViewEntity().bridge$getEyeHeight();
               }

               for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH var10 : var3.HICICOHCRHIHCCIRHRHOCIRIOOOHII()) {
                  Entry var11 = var10.IOHCRRIIHCIHORROOCHCCORIHRHCII(var3.IHRHCHOCCHHICIIOIORIRCIHHHHHIH());
                  if (var11 != null) {
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var12 = ((com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO)var11.getValue())
                        .HIIHOIHOCORCOOHHRCCCRCIIIIHIIH()
                        .get("camera");
                     if (var12 != null) {
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var13 = var12.HCIORRCRIRHIOIHORHHHRRIRRIROIC()
                           .get(this.ICHHOIRROHCRCHHOOCRCIHIICORHRR().getId());
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var14 = var12.HCIORRCRIRHIOIHORHHHRRIRRIROIC()
                           .get(this.HRRCHROCHCHORHCIRICRIHCIICCRHH.getId());
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var15 = var12.HCIORRCRIRHIOIHORHHHRRIRRIROIC()
                           .get(this.IOORRIICROOCRHOORCICRHRCRROCRI.getId());
                        com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var16 = this.IROCHOOOIORRICOOORROOHOIORIHIH();
                        List var17 = List.of(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
                        if (var16 != null) {
                           double var18 = var16.bridge$getPreviousRotationYaw()
                              + (var16.bridge$getRotationYaw() - var16.bridge$getPreviousRotationYaw()) * var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR();
                           var17 = List.of(
                              var16.RHRCCCOORROCRICCICHHCCCCIICIHH()
                                 + (var16.bridge$getPosX() - var16.RHRCCCOORROCRICCICHHCCCCIICIHH()) * var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR(),
                              var16.IICIIHIHHRCIIRHCRROHIHHOICROIR()
                                 + (var16.bridge$getPosY() - var16.IICIIHIHHRCIIRHCRROHIHHOICROIR()) * var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR(),
                              var16.RHOROIIHICOCIICIICRHHOOOROIIOO()
                                 + (var16.bridge$getPosZ() - var16.RHOROIIHICOCIICIICRHHOOOROIIOO()) * var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR(),
                              var16 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR var20
                                 ? (double)var20.bridge$getPrevRotationYawHead()
                                    + (var20.bridge$getRotationYawHead() - var20.bridge$getPrevRotationYawHead()) * var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR()
                                 : var18,
                              var16.bridge$getPreviousRotationPitch()
                                 + (var16.bridge$getRotationPitch() - var16.bridge$getPreviousRotationPitch()) * var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR(),
                              this.ICHHOIRROHCRCHHOOCRCIHIICORHRR().get().get(5),
                              var18
                           );
                        }

                        if (!this.HRRCHROCHCHORHCIRICRIHCIICCRHH.get().isFixedToPlayer()) {
                           var6 = new LinkedHashSet();
                           int var32 = var3.RHCHIOHOIHHCIROCRCIRIOCRRHROII().getFps();
                           int var19 = 30 * var32;
                           int var33 = Math.max(var3.IHRHCHOCCHHICIIOIORIRCIHHHHHIH() - var19, (Integer)((Range)var11.getKey()).getMinimum());
                           int var21 = Math.min(var3.IHRHCHOCCHHICIIOIORIRCIHHHHHIH() + var19, (Integer)((Range)var11.getKey()).getMaximum());
                           int var22 = Integer.MIN_VALUE;
                           List var23 = null;

                           for (int var24 = var33; var24 <= var21; var24++) {
                              int var25 = var24 - (Integer)((Range)var11.getKey()).getMinimum();
                              List var26 = (List)var13.getAt(var25);
                              com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var27 = null;
                              if (var13.HORCHIIOIHRCHOIIRIRHIHRCOIIRCO().containsKey(var24 - (Integer)((Range)var11.getKey()).getMinimum())) {
                                 if (var24 == var3.IHRHCHOCCHHICIIOIORIRCIHHHHHIH()) {
                                    var23 = null;
                                    continue;
                                 }

                                 if (var14.getAt(var25)
                                    == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FOLLOW
                                    )
                                  {
                                    var27 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH)var15.getAt(
                                       var25
                                    );
                                 }

                                 var6.addAll(this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var26, var17, var27, var8, var5));
                              }

                              if (var23 != null && var24 > var22 + var32 / 10) {
                                 Vector3d var28 = new Vector3d((Double)var23.get(0), (Double)var23.get(1) + var8, (Double)var23.get(2)).sub(var5);
                                 Vector3d var29 = new Vector3d((Double)var26.get(0), (Double)var26.get(1) + var8, (Double)var26.get(2)).sub(var5);
                                 Vector3d var30 = new Vector3d(0.0, 0.0, 0.0);
                                 if (var14.getAt(var25)
                                    == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FOLLOW
                                    )
                                  {
                                    var30 = new Vector3d((Double)var17.get(0), (Double)var17.get(1), (Double)var17.get(2)).sub(var5);
                                 }

                                 var6.add(
                                    new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                                       var28.add(var30), var29.add(var30)
                                    )
                                 );
                                 var22 = var24;
                                 var23 = var26;
                              }

                              if (var23 == null) {
                                 var23 = var26;
                              }
                           }

                           int var34 = var3.IHRHCHOCCHHICIIOIORIRCIHHHHHIH() - (Integer)((Range)var11.getKey()).getMinimum();
                           List var35 = (List)var13.getAt(var34);
                           com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var36 = null;
                           if (var14.getAt(var34)
                              == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FOLLOW
                              )
                            {
                              var36 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH)var15.getAt(
                                 var34
                              );
                           }

                           Vector3d var37 = new Vector3d((Double)var35.get(0), (Double)var35.get(1), (Double)var35.get(2));
                           Vector3d var38 = new Vector3d(
                              this.ICHHOIRROHCRCHHOOCRCIHIICORHRR().get().get(0),
                              this.ICHHOIRROHCRCHHOOCRCIHIICORHRR().get().get(1),
                              this.ICHHOIRROHCRCHHOOCRCIHIICORHRR().get().get(2)
                           );
                           if (var37.distance(var38) > 0.5) {
                              var7 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var35, var17, var36, var8, var5);
                           }
                        } else if (var16 != null && !var2.RICCCROHOIOCHORIRCHIIOORHIRHHR()) {
                           var7 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var17, var17, null, var16.bridge$getEyeHeight(), var5);
                        }
                     }
                  }
               }

               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var31 = var1.HHIIOHOORHHCCHRHHRCIORCROORCOI();
               var31.push();
               if (!var6.isEmpty()) {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var31, var6, -2364929
                  );
               }

               if (!var7.isEmpty()) {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var31, var7, -2171325
                  );
               }

               var31.pop();
            }
         }
      }
   }

   private Set<com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      List<Double> var2,
      List<Double> var3,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4,
      float var5,
      Vector3d var6
   ) {
      LinkedHashSet var7 = new LinkedHashSet();
      double var8 = (Double)var2.get(0);
      double var10 = (Double)var2.get(1) + var5;
      double var12 = (Double)var2.get(2);
      double var14 = (Double)var2.get(3) + 180.0;
      double var16 = (Double)var2.get(4);
      double var18 = (Double)var2.get(5);
      if (var4 != null) {
         if (var4
            == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.POSITION
            )
          {
            var8 += var3.get(0);
            var10 += var3.get(1);
            var12 += var3.get(2);
         } else {
            boolean var20 = var4
               == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.POS_ROT_HEAD;
            double var21 = Math.toRadians((Double)var3.get(var20 ? 3 : 6));
            double var23 = Math.toRadians((Double)var3.get(4));
            double var25 = var8;
            double var27 = var10 * Math.cos(var23) - var12 * Math.sin(var23);
            double var29 = var10 * Math.sin(var23) + var12 * Math.cos(var23);
            double var31 = var25 * Math.cos(var21) - var29 * Math.sin(var21);
            double var33 = var27;
            double var35 = var25 * Math.sin(var21) + var29 * Math.cos(var21);
            var8 = (Double)var3.get(0) + var31;
            var10 = (Double)var3.get(1) + var33;
            var12 = (Double)var3.get(2) + var35;
            if (var20) {
               var14 += var3.get(6);
               var16 += var3.get(4);
            } else {
               var14 += var3.get(3);
            }
         }
      }

      double var74 = Math.toRadians(
         this.ICICHORRHCCCHRHRHICHHCOIIHHHOI.get()
            ? this.HHCHCIOROIIHRIORRROIIICHCHORHO.get().floatValue()
            : IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getGameSettings().bridge$getFov()
      );
      double var22 = (double)var1.RHCHIOHOIHHCIROCRCIRIOCRRHROII().getWidth() / var1.RHCHIOHOIHHCIROCRCIRIOCRRHROII().getHeight();
      double var24 = 0.1;
      double var26 = 0.5;
      Vector3d var28 = new Vector3d(var8, var10, var12);
      double var75 = Math.toRadians(var14);
      double var76 = Math.toRadians(var16);
      double var77 = Math.toRadians(var18);
      double var78 = Math.cos(var76);
      double var37 = Math.sin(var76);
      double var39 = Math.sin(var75);
      double var41 = Math.cos(var75);
      Vector3d var43 = new Vector3d(var39 * var78, -var37, -var41 * var78).normalize();
      Vector3d var44 = new Vector3d(0.0, 1.0, 0.0);
      Vector3d var45 = new Vector3d(var43).cross(var44).normalize();
      Vector3d var46 = new Vector3d(var45).cross(var43).normalize();
      Vector3d var47 = new Vector3d(var46).mul(new Matrix3d().rotation(var77, var43));
      var45 = new Vector3d(var43).cross(var47).normalize();
      Vector3d var48 = new Vector3d(var28).fma(var24, var43).sub(var6);
      Vector3d var49 = new Vector3d(var28).fma(var26, var43).sub(var6);
      double var50 = 2.0 * Math.tan(var74 / 2.0) * var24;
      double var52 = var50 * var22;
      double var54 = 2.0 * Math.tan(var74 / 2.0) * var26;
      double var56 = var54 * var22;
      double var58 = var50 * 0.5;
      double var60 = var52 * 0.5;
      double var62 = var54 * 0.5;
      double var64 = var56 * 0.5;
      Vector3d var66 = new Vector3d(var48).fma(var58, var47).fma(-var60, var45);
      Vector3d var67 = new Vector3d(var48).fma(var58, var47).fma(var60, var45);
      Vector3d var68 = new Vector3d(var48).fma(-var58, var47).fma(-var60, var45);
      Vector3d var69 = new Vector3d(var48).fma(-var58, var47).fma(var60, var45);
      Vector3d var70 = new Vector3d(var49).fma(var62, var47).fma(-var64, var45);
      Vector3d var71 = new Vector3d(var49).fma(var62, var47).fma(var64, var45);
      Vector3d var72 = new Vector3d(var49).fma(-var62, var47).fma(-var64, var45);
      Vector3d var73 = new Vector3d(var49).fma(-var62, var47).fma(var64, var45);
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var66, var67));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var67, var69));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var69, var68));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var68, var66));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var70, var71));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var71, var73));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var73, var72));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var72, var70));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var66, var70));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var67, var71));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var68, var72));
      var7.add(new com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var69, var73));
      return var7;
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1
   ) {
      var1.cancel();
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      if (this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR.get().HCIRHHCHORHRORHHCIOHCIHIIRCHIO().IHHCRHRIORROROHIIIRHOORHHRHOII()) {
         this.CORCOROCCCICOORHHRCOHOIHOIOHHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IHIRRIIORRHORHRORIHOROIRCORCOO var1
   ) {
      var1.cancel();
      this.CORCOROCCCICOORHHRCOHOIHOIOHHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
   }

   public float[] IOIHOCIIIOOIIRHRCOCORIIHIIRIIO() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get()
         .HCIRHHCHORHRORHHCIOHCIHIIRCHIO()
         .HOCCHIRHIIOOOIHIHHICHRIRIHHHRO()
         .RROHROIOCRIORIOIRIHRRRRHRIHRII();
      if (var1 != null && this.IIHCHCIOCOIOOICCRICIRRHCHOCCIR.get()) {
         float var2 = this.IOOHRICHRIIHRRCCRIIHHRROHCHRCC.get();
         float var3 = this.RCIIIHOHCIOCIOHICCOIIIOCOROCRH.get();
         double var4 = var1.RHCHIOHOIHHCIROCRCIRIOCRRHROII().getFps();
         float var6 = (float)Math.sin(var1.IHRHCHOCCHHICIIOIORIRCIHHHHHIH() / var4 * 1.5 * var3) * var2;
         float var7 = (float)Math.cos(var1.IHRHCHOCCHHICIIOIORIRCIHHHHHIH() / var4 * 1.2 * var3) * var2;
         return new float[]{var6, var7};
      } else {
         return new float[]{0.0F, 0.0F};
      }
   }

   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CHORCRORCICOCOOORCIOOICCOOIOHC() {
      return !this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR.get().HCIRHHCHORHRORHHCIOHCIHIIRCHIO().RICCCROHOIOCHORIRCHIIOORHIRHHR()
         ? com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FREE_CAMERA
         : this.HRRCHROCHCHORHCIRICRIHCIICCRHH.get();
   }

   public IHICORCROOROHCIHIHCOIHRRHICICO<Double> ICHHOIRROHCRCHHOOCRCIHIICORHRR() {
      return this.HRRCHROCHCHORHCIRICRIHCIICCRHH.get()
            == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FOLLOW
         ? this.HCIHOCCOIHHHCHOHIHRRHCRICRIORH
         : this.RCIHRHRHOHOHOCHORCCIHHIRIHRHIO;
   }

   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH IROCHOOOIORRICOOORROOHOIORIHIH() {
      try {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
         if (!this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.isDefault()) {
            String var2 = this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.get();
            if (var2.contains("-")) {
               UUID var3 = UUID.fromString(this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.get());
               var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH().bridge$getPlayerByUniqueId(var3).orElseThrow();
            } else {
               var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH().bridge$getEntityById(Integer.parseInt(var2)).orElseThrow();
            }
         }

         return var1;
      } catch (Exception var4) {
         return IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      }
   }

   public boolean CHHCCIOICIIRRIRCHROOCCHRIHOROC() {
      return !this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.isDefault();
   }

   private HCHRIROHHHCORIOCROOCHRCIOROOCI<String> CRCCIIOORIROOIIIHIRHOIHCIIICOR() {
      return IOHHOIIOCRHCHHCRORICCOHOHROOIH.RRCRRCORICCHOHHIRCHIROOHIIOHCO("target", Codec.STRING)
         .ORIOHRCIHRCOOHICCCRIIIHCRHHIHI("")
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.PLAYERS
         )
         .IHIIIRHOOCHRCCCCIORIROCOIRRHCC(
            var1 -> {
               JsonArray var2 = new JsonArray();
               if (IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() != null) {
                  for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4 : IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH()
                     .bridge$getPlayerEntities()) {
                     JsonObject var5 = new JsonObject();
                     var5.addProperty(
                        "name",
                        com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.stripColor(
                                 var4.bridge$getName()
                              )
                              .isBlank()
                           ? var4.bridge$getUniqueID().toString()
                           : var4.bridge$getName()
                     );
                     var5.addProperty("uuid", var4.bridge$getUniqueID().toString());
                     var2.add(var5);
                  }
               }

               if (!this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.get().isEmpty() && !this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.get().contains("-")) {
                  String var7 = null;

                  try {
                     var7 = ORHIOICIOCRRHOOCOHRORIHICHRCRR.IIIORCCOIHHRCIRHOCIIICOHOOCHIH(Integer.parseInt(this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.get()));
                  } catch (Exception var6) {
                     com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        "Rewind", "Failed to get entity name for ID: %s %s", this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.get(), var6.getMessage()
                     );
                  }

                  if (var7 == null) {
                     var7 = "Entity";
                  }

                  String var9 = this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.get();
                  if (var9.length() > 3) {
                     var9 = var9.substring(var9.length() - 3);
                  }

                  JsonObject var10 = new JsonObject();
                  var10.addProperty("name", var7 + " (" + var9 + ")");
                  var10.addProperty("uuid", this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH.get());
                  var10.addProperty("noAvatar", true);
                  var2.add(var10);
               }

               var1.add("players", var2);
               if (IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH() != null) {
                  JsonObject var8 = new JsonObject();
                  var8.addProperty(
                     "name",
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.stripColor(
                              IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH().bridge$getName()
                           )
                           .isBlank()
                        ? IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH().bridge$getUniqueID().toString()
                        : IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH().bridge$getName()
                  );
                  var8.addProperty("uuid", IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH().bridge$getUniqueID().toString());
                  var1.add("player", var8);
               }
            }
         )
         .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   }

   @Generated
   public HCHRIROHHHCORIOCROOCHRCIOROOCI<String> IOCHRCOIIHRRHRCIHIIRHCCCRCHCOC() {
      return this.OHCHOOIHIOCIRRHRHOIRCOIHIICROH;
   }

   @Generated
   public RIROICHCRROROHCCROOCCCCOCHCCRI<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> HRIICIRCRHCICIRIHCIIRRRIOIOOCH() {
      return this.HRRCHROCHCHORHCIRICRIHCIICCRHH;
   }

   @Generated
   public RIROICHCRROROHCCROOCCCCOCHCCRI<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH> ORHCRROOOCRRICRCHHHOORCOIHIRRI() {
      return this.IOORRIICROOCRHOORCICRHRCRROCRI;
   }

   @Generated
   public IHICORCROOROHCIHIHCOIHRRHICICO<Double> CRRRCRORHOHCOIIOHCHOCRHOHHHCHR() {
      return this.RCIHRHRHOHOHOCHORCCIHHIRIHRHIO;
   }

   @Generated
   public IHICORCROOROHCIHIHCOIHRRHICICO<Double> OOIRRCHORHOOOOIOCORCIROHIOCHOH() {
      return this.HCIHOCCOIHHHCHOHIHRRHCRICRIORH;
   }

   @Generated
   public com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI CROIHORRRHHIHHCCOIOCHCCRRHCCII() {
      return this.IIHCHCIOCOIOOICCRICIRRHCHOCCIR;
   }

   @Generated
   public IHIRRIIORRHORHRORIHOROIRCORCOO ORHIIOOIIRIORRIHIRHHOOICHHHHOC() {
      return this.IOOHRICHRIIHRRCCRIIHHRROHCHRCC;
   }

   @Generated
   public IHIRRIIORRHORHRORIHOROIRCORCOO RHORHRHHRIORRIOIHICCROCCRORICH() {
      return this.RCIIIHOHCIOCIOHICCOIIIOCOROCRH;
   }

   @Generated
   public com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI HIRRCOCCOROCHCORIOIHRCRCIOHHRI() {
      return this.ICICHORRHCCCHRHRHICHHCOIIHHHOI;
   }

   @Generated
   public IHIRRIIORRHORHRORIHOROIRCORCOO RICOOORHOIOICOCOCCOCOIHHCCICII() {
      return this.HHCHCIOROIIHRIORRROIIICHCHORHO;
   }

   @Generated
   public com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IHCROOROIICOHOOHRIHIOCCIRHCHOI() {
      return this.ORRICOHORHCIOIRIRHCHHRHCHCHHHC;
   }

   @Generated
   public com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IHCCCCHHOIHCHRORICOCOHCOIHCRIO() {
      return this.ORHIRIHOOHROICROCOHRCHCOHHICCC;
   }

   @Generated
   public com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IIHRRHORCRCROCHHOHORCHCROCIHRO HIOIHIHRCCIRCHHRHCIRHRROIHOOIC() {
      return this.OCCHICCIRHHHRRRRCCHIOCIROIHOOI;
   }
}
