package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import com.moonsworth.lunar.client.util.CRHHOOCRCOHHRHOOOCHCROOHIOOCOH;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO;
import lombok.Generated;

public class OOROOCCIRCCRHOIOIORIHCHHOOCCOR extends RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IHIOIHORHHIHICORRCRCHCIICIIHIO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "show"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RCIROOOOICRHCCRRCIORHHIRCOIIIC HHCHIHRCIIIRCCCHOIOORRHIIHICRH = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "cursors/cursor.png");
   private CRHHOOCRCOHHRHOOOCHCROOHIOOCOH OCOCCOOOHHIROOHICORIOCOHIROIRO;
   private CRHHOOCRCOHHRHOOOCHCROOHIOOCOH OCRHRRCOCCRHOHROIHOIIHCHHHOHOI;

   public OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
      IIHRHCCOOHOOOOCHRRCOROOIOHCOOO<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH> var1
   ) {
      super(var1);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.class,
         this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.class,
         this::HHCCIRHCCCIIRHCROHIORHIRHHIORH
      );
      this.handle(RHOCHHIRRCHHHOHOIRROIROHHHIHIO.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR var1
   ) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH var2 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get();
      boolean var3 = var1.RCORHIHICHCOORRRHCHCRICCHICOOO() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
         || var1.RCORHIHICHCOORRRHCHCRICCHICOOO() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH
         || var1.RCORHIHICHCOORRRHCHCRICCHICOOO() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen()
      );
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var5 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
         var1.RCORHIHICHCOORRRHCHCRICCHICOOO()
      );
      boolean var6 = var4 != null
         && var4.getClass() == com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class;
      boolean var7 = var5 != null
         && var5.getClass() == com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class;
      if ((var2.RCIIORHCCIOHIHRORHRHOOOOCOHCCI() || var3) && !var7) {
         if (var1.RCORHIHICHCOORRRHCHCRICCHICOOO() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO
            )
          {
            var1.cancel();
            var2.HCIRHHCHORHRORHHCIOHCIHIIRCHIO().IHIHIHICHOOIHORICRHICIIIORCIHO();
         } else {
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8 = var2.HHOHIHRCICOIICIIOHHHRHROHCHICI();
            if (var1.RCORHIHICHCOORRRHCHCRICCHICOOO() != null) {
               var8.CRICCOOHHHCHOORCICOCOHIHOIRHOO(var1.RCORHIHICHCOORRRHCHCRICCHICOOO());
            }

            if (var8.RCORHIHICHCOORRRHCHCRICCHICOOO() != null) {
               var1.cancel();
               if (IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen() != null) {
                  com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.class,
                        () -> new com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH(
                           IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen(), var8.RCORHIHICHCOORRRHCHCRICCHICOOO()
                        )
                     );
               }

               this.IIOORRCRHCRIORIOCOHHIROOIIHROC(true);
            } else {
               if (var6) {
                  var1.cancel();
                  if (IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen() != null) {
                     com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
                        .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.class,
                           () -> new com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH(
                              IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen(), null
                           )
                        );
                  }
               }

               var8.OOCCRCRCOHIIORCCORCRCIRRROIOOR(0, 0);
            }
         }
      } else {
         if (var6 && !var7) {
            var1.cancel();
         }
      }
   }

   public boolean IROCIHHRHIHCRIHIOHOOHHRIICCCRH() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH var1 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get();
      return var1.HHOHIHRCICOIICIIOHHHRHROHCHICI().RCORHIHICHCOORRRHCHCRICCHICOOO() != null
         && this.IHIOIHORHHIHICORRCRCHCIICIIHIO.get()
         && IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getRenderViewEntity()
            == IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getPlayer()
         && var1.HCIRHHCHORHRORHHCIOHCIHIIRCHIO().CCRHOIIHHCCIROCCROHHIIOCOHIRRC().CHORCRORCICOCOOORCIOOICCOOIOHC().isFirstPerson()
         && !IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getGameSettings().bridge$isHideGui();
   }

   private void HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH var2 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get();
      if (this.IROCIHHRHIHCRIHIOHOOHHRIICCCRH()) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = var2.HHOHIHRCICOIICIIOHHHRHROHCHICI();
         ORHIOICIOCRRHOOCOHRORIHICHRCRR var4 = var3.RCORHIHICHCOORRRHCHCRICCHICOOO();
         float var5 = var2.HCIRHHCHORHRORHHCIOHCIHIIRCHIO().HRCHICHIOHOROOHHHOHROHCICCROIO().getPartialTick();
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var6 = var1.HHIIOHOORHHCCHRHHRCIORCROORCOI();
         int var7 = IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 6 ? var4.bridge$getInventoryScale() : 0;
         boolean var8 = var7 > 0;
         float var9 = 1.0F;
         CRHHOOCRCOHHRHOOOCHCROOHIOOCOH var10 = null;
         if (var8) {
            double var11 = com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IOOHRICHRIIHRRCCRIIHHRROHCHRCC();
            int var13 = Math.max(1, (int)(this.mc.bridge$getGuiScale() / var11));
            var9 = (float)var7 / var13;
            this.mc.bridge$setRawGuiScale(var7);
            var6.push();
            var6.scale(var9, var9, 1.0F);
            var4.bridge$setInventoryScaleFactor(var9);
            var10 = com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.ROHHOOHOHCHRIICCCHCOHCORROHRIH();
            com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
               this.OOCICRIIIRRIOOCRHRRRRRHIRHRCRO()
            );
         }

         CRHHOOCRCOHHRHOOOCHCROOHIOOCOH var17 = com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.ROHHOOHOHCHRIICCCHCOHCORROHRIH();
         this.OCRHRRCOCCRHOHROIHOIIHCHHHOHOI = var17;
         int var12 = var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5, var17.getScaledWidth());
         int var18 = var3.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5, var17.getScaledHeight());
         var4.bridge$drawScreen(var6, var12, var18, var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR());
         var6.IRCHOHHOOROOHIIHHROOOOIIHHOIIH();
         var6.CHHHIRRRHHCOOHRRICOCICHHROHHIR();
         float var14 = 20.0F / var17.IOCIOIHIOOCRHHORHHCOOHIIHICOCH();
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var15 = var1.RCHHRIOCRHHIHIROCIRCRHRIOOOCOO();
         var15.push();
         var15.CRICCOOHHHCHOORCICOCOHIHOIRHOO(0.0F, 0.0F, 500.0F);
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            var15, this.HHCHIHRCIIIRCCCHOIOORRHIIHICRH, var12, var18, var14, var14, -1
         );
         var15.pop();
         if (var8) {
            var6.pop();
            var4.bridge$setInventoryScaleFactor(1.0F);
            com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
               var10
            );
            this.mc.bridge$setGuiScale(this.mc.bridge$getGameSettings().bridge$getGuiScale());
         }
      }
   }

   private CRHHOOCRCOHHRHOOOCHCROOHIOOCOH OOCICRIIIRRIOOCRHRRRRRHIRHRCRO() {
      int var1 = this.mc.bridge$getGuiScale();
      int var2 = this.mc.bridge$displayWidth();
      int var3 = this.mc.bridge$displayHeight();
      return new CRHHOOCRCOHHRHOOOCHCROOHIOOCOH(var1, var2, var3, (double)var2 / var1, (double)var3 / var1);
   }

   public CRHHOOCRCOHHRHOOOCHCROOHIOOCOH OOHRHRIRICHRRRHRHIHCHCICICHICH() {
      return this.OCRHRRCOCCRHOHROIHOIIHCHHHOHOI != null ? this.OCRHRRCOCCRHOHROIHOIIHCHHHOHOI : this.OCOCCOOOHHIROOHICORIOCOHIROIRO;
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RHOCHHIRRCHHHOHOIRROIROHHHIHIO var1) {
      this.IIOORRCRHCRIORIOCOHHIROOIIHROC(false);
   }

   public void IIOORRCRHCRIORIOCOHHIROOIIHROC(boolean var1) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
         .get()
         .HHOHIHRCICOIICIIOHHHRHROHCHICI();
      ORHIOICIOCRRHOOCOHRORIHICHRCRR var3 = var2.RCORHIHICHCOORRRHCHCRICCHICOOO();
      if (var3 != null) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = this.ICRHCCOCCOIHOIIIIORCIRCCHHIRCR
            .get()
            .HCIRHHCHORHRORHHCIOHCIHIIRCHIO();
         HRCHROOHRIHCRCRHRIIROCIRHOIRHH var5 = var4.HIHCRRIHRIROROCRICHHORIOCRCOCO();
         int var6 = var5.HHRRRORIICOCHCOOOORHHOOHHIOHHI().HOIHRCIOCIHORHIRHCOHRHHCCHOOOR().bridge$framebufferWidth();
         int var7 = var5.HHRRRORIICOCHCOOOORHHOOHHIOHHI().HOIHRCIOCIHORHIRHCOHRHHCCHOOOR().bridge$framebufferHeight();
         if (!var4.RICCCROHOIOCHORIRCHIIOORHIRHHR() || var4.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().IOHHOICRCORHRCICOCHIORRHHHCORC()) {
            var6 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$displayWidth();
            var7 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$displayHeight();
         }

         CRHHOOCRCOHHRHOOOCHCROOHIOOCOH var8 = new CRHHOOCRCOHHRHOOOCHCROOHIOOCOH(IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI(), var6, var7);
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            var8
         );
         if (var1
            || this.OCOCCOOOHHIROOHICORIOCOHIROIRO.getWidth() != var6
            || this.OCOCCOOOHHIROOHICORIOCOHIROIRO.getHeight() != var7
            || this.OCOCCOOOHHIROOHICORIOCOHIROIRO.IOCIOIHIOOCRHHORHHCOOHIIHICOCH() != var8.IOCIOIHIOOCRHHORHHCOOHIIHICOCH()) {
            this.OCOCCOOOHHIROOHICORIOCOHIROIRO = var8;
            var3.bridge$setWorldAndResolution(var6 / var8.IOCIOIHIOOCRHHORHHCOOHIIHICOCH(), var7 / var8.IOCIOIHIOOCRHHORHHCOOHIIHICOCH());
         }
      }
   }

   @Generated
   public CRHHOOCRCOHHRHOOOCHCROOHIOOCOH ROHHOOHOHCHRIICCCHCOHCORROHRIH() {
      return this.OCOCCOOOHHIROOHICORIOCOHIROIRO;
   }
}
