package com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

import com.google.gson.JsonElement;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO;
import com.moonsworth.webosr.javascript.CallbackJS;
import java.util.Optional;
import java.util.UUID;
import org.jetbrains.annotations.Nullable;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH
   implements com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   @CallbackJS("createWaypointGroup")
   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var0, String var1, Boolean var2, Boolean var3, Boolean var4, Boolean var5, Boolean var6, String var7
   ) {
      try {
         com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8 = com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.valueOf(
            var1
         );
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHOOIOHCHICOCHIICHCICCOHRCIII.IRCIIHHICIHRCOCRROCOICRIHHCCHH var9 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHOOIOHCHICOCHIICHCICCOHRCIII.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHROHIOOHCCIOIHOOOHIOOCHCRRHC()
            .CHHOOIOHHRCIRIRRHHHOOCRCCHHOOR(var0)
            .CCHCIRORCRCCICIHRCIIIHIIRCRHRC(IIHRHCCOOHOOOOCHRRCOROOIOHCOOO.HIRHRIOCOCCCORCRICIICOIIIOCOHI())
            .OOCHIIROORIOCCCCCOORRIRIOHOORH(100)
            .HOOOOIOORROCRICOOOCRORCCCICROI();
         var9.CCOIROOCRICIOIHOHCHRRHCCIHCRCO(var2);
         var9.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHOOIOHCHICOCHIICHCICCOHRCIII.CRRRICCRROCOHHOHIICIHORCOORRRH(
               var4, var8, var5, var3, var6
            )
         );
         var9.HOHOIICHHIRIOIIIOHRHOCCRRRRIHR().CHIHRIROCCRICOHIRCRIOOHOHRRCHC().CCHHRCRRIIOCOOCCRHHCRROHRIICOC(var7);
         com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
            .HOHHHORIIORRRROHRIIRCHCCICHHCI()
            .HHCCIRHCCCIIRHCROHIORHIRHHIORH(var9);
      } catch (Exception var10) {
         com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH(
            "Error creating waypoint group: " + var10.getMessage()
         );
      }
   }

   @CallbackJS("deleteWaypointGroup")
   public static void HHCCIRHCCCIIRHCROHIORHIRHHIORH(UUID var0, boolean var1) {
      com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
         .HOHHHORIIORRRROHRIIRCHCCICHHCI()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1);
   }

   @CallbackJS("updateWaypointGroup")
   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      UUID var0, String var1, String var2, Boolean var3, Boolean var4, Boolean var5, Boolean var6, Boolean var7, String var8
   ) {
      try {
         com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9 = com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.valueOf(
            var2
         );
         com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
            .HOHHHORIIORRRROHRIIRCHCCICHHCI()
            .OCRCHRHOCCHCHRCORHIHRRRRHCHHCH(var0)
            .ifPresent(
               var8x -> {
                  var8x.setName(var1);
                  var8x.CCOIROOCRICIOIHOHCHRRHCCIHCRCO(var3);
                  var8x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHOOIOHCHICOCHIICHCICCOHRCIII.CRRRICCRROCOHHOHIICIHORCOORRRH(
                        var5, var9, var6, var4, var7
                     )
                  );
                  var8x.HOHOIICHHIRIOIIIOHRHOCCRRRRIHR().CHIHRIROCCRICOHIRCRIOOHOHRRCHC().CCHHRCRRIIOCOOCCRHHCRROHRIICOC(var8);
                  com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
                     .HOHHHORIIORRRROHRIIRCHCCICHHCI()
                     .ROOCCICICICIRCOHOHCOCIHHCCHRII();
                  com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
                     .HOHHHORIIORRRROHRIIRCHCCICHHCI()
                     .HRIIIOIIRHOHORIRICIOIORRIRCHHO();
               }
            );
      } catch (Exception var10) {
         com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH(
            "Error updating waypoint group: " + var10.getMessage()
         );
      }
   }

   @CallbackJS("setWaypointGroup")
   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var0, String var1, String var2, UUID var3) {
      IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var0, var1, var2)
         .ifPresent(
            var1x -> {
               com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
                  .HOHHHORIIORRRROHRIIRCHCCICHHCI()
                  .OCRCHRHOCCHCHRCORHIHRRRRHCHHCH(var3)
                  .ifPresent(var1x::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
               com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
                  .HOHHHORIIORRRROHRIIRCHCCICHHCI()
                  .ROOCCICICICIRCOHOHCOCIHHCCHRII();
               com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
                  .HOHHHORIIORRRROHRIIRCHCCICHHCI()
                  .HRIIIOIIRHOHORIRICIOIORRIRCHHO();
            }
         );
   }

   private static Optional<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHOOIOHCHICOCHIICHCICCOHRCIII.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
      String var0, String var1, String var2
   ) {
      return com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
         .HOHHHORIIORRRROHRIIRCHCCICHHCI()
         .CRICCOOHHHCHOORCICOCOHIHOIRHOO(var0, var1, var2);
   }

   @Nullable
   @Override
   public JsonElement HRRORHCRHHRROHIOROOOORRIRRCCIC() {
      return null;
   }

   @Override
   public JsonElement provide() {
      return null;
   }
}
