package com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import it.unimi.dsi.fastutil.longs.Long2ObjectMap;
import it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.objects.Object2BooleanMap;
import it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap;
import java.util.EnumSet;
import java.util.Set;
import javax.annotation.Nullable;
import lombok.Generated;
import org.jetbrains.annotations.NotNull;

public class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private final Object2BooleanMap<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> IOCCIRRORRORRCCOIHOOOCRRCRRHHO = new Object2BooleanOpenHashMap();
   private final Long2ObjectMap<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> RHOHIHCOHCICICCOOHOCIIOIROIRRR = new Long2ObjectOpenHashMap();
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH[] CIHCCRRIIIRCIRROICIOCIOCHCRHCC = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH[com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HORIZONTAL
      .size()];

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RRCRRCORICCHOHHIRCHIROOHIIOHCO var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2);
   }

   @Override
   public void done() {
      this.RHOHIHCOHCICICCOOHOCIIOIROIRRR.clear();
      this.IOCCIRRORRORRCCOIHOOOCRRCRRHHO.clear();
      super.done();
   }

   @NotNull
   @Override
   public IRCIIHHICIHRCOCRROCOICRIHHCCHH RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(int var1, int var2, int var3) {
      return new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         this.ORHIOICIOCRRHOOCOHRORIHICHRCRR(var1, var2, var3)
      );
   }

   @Override
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OOIRHICCOHIOIRORHRHROOIIOOCCCC() {
      RORCHCIIICOHIRROOORHOCCCCIOCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
         .IRCIIHHICIHRCOCRROCOICRIHHCCHH(0, 0, 0);
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI
         .HHIRHRHIORICHOHOCOICCRCCIRHIOO();
      int var3;
      int var4;
      int var5;
      if (var2 == null) {
         var3 = (int)Math.floor(this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosX());
         var4 = (int)Math.floor(this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosY());
         var5 = (int)Math.floor(this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosZ());
      } else {
         var3 = var2.bridge$getX();
         var4 = var2.bridge$getY();
         var5 = var2.bridge$getZ();
      }

      var1.HICRRICCHCCROOHHCHOCOCCHOIHHOC(this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosX(), var4, this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosZ());
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = this.RIRIOORHCHOICORIHIOHRCIHHRCRRR
         .IHCRORHRORIICHRHRCHRRIRRHHOCOO(var1);
      if (this.ROIOHOROCRROCHOCIIICHOOHHRIIRH && this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.isInWater()) {
         while (var6.bridge$getBlock().bridge$isWater()) {
            var1.HICRRICCHCCROOHHCHOCOCCHOIHHOC(
               this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosX(), ++var4, this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosZ()
            );
            var6 = this.RIRIOORHCHOICORIHIOHRCIHHRCRRR.IHCRORHRORIICHRHRCHRRIRRHHOCOO(var1);
         }

         var4--;
      } else if (this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.HHICIORROHIIIOIICORIRCORICOCOO()) {
         var4 = (int)Math.floor(this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosY() + 0.5);
      } else {
         var1.HICRRICCHCCROOHHCHOCOCCHOIHHOC(
            this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosX(),
            this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosY() + 1.0,
            this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosZ()
         );

         while (var1.bridge$getY() > this.RIRIOORHCHOICORIHIOHRCIHHRCRRR.ORCORRRCCRHHCORRCRCCHCOIRICIRC().bridge$getMinBuildHeight()) {
            var4 = var1.bridge$getY();
            var1.bridge$setPos(var1.bridge$getX(), var1.bridge$getY() - 1, var1.bridge$getZ());
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = this.RIRIOORHCHOICORIHIOHRCIHHRCRRR
               .IHCRORHRORIICHRHRCHRRIRRHHOCOO(var1);
            if (!var7.bridge$getBlock().bridge$isAir()
               && !var7.bridge$isPathfindable(
                  this.RIRIOORHCHOICORIHIOHRCIHHRCRRR.ORCORRRCCRHHCORRCRCCHCOIRICIRC(),
                  var1,
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.LAND
               )) {
               break;
            }
         }
      }

      var1.bridge$setPos(var3, var4, var5);
      if (!this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(var1)) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8 = this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI
            .OIIHICRIICHCHIROIOHRRCHICOCOCO();
         var1.HICRRICCHCCROOHHCHOCOCCHOIHHOC(var8.bridge$getMinX(), var4, var8.bridge$getMinZ());
         if (this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(var1)) {
            return this.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(var1);
         }

         var1.HICRRICCHCCROOHHCHOCOCCHOIHHOC(var8.bridge$getMinX(), var4, var8.bridge$getMaxX());
         if (this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(var1)) {
            return this.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(var1);
         }

         var1.HICRRICCHCCROOHHCHOCOCCHOIHHOC(var8.bridge$getMaxX(), var4, var8.bridge$getMinZ());
         if (this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(var1)) {
            return this.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(var1);
         }

         var1.HICRRICCHCCROOHHCHOCOCCHOIHHOC(var8.bridge$getMaxX(), var4, var8.bridge$getMaxZ());
         if (this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(var1)) {
            return this.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(var1);
         }
      }

      return this.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2.bridge$getX(), var4, var2.bridge$getZ())
      );
   }

   @Override
   public int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH[] var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      int var3 = 0;
      int var4 = 0;
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = this.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
         var2.x, var2.y + 1, var2.z
      );
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = this.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
         var2.x, var2.y, var2.z
      );
      if (this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5) >= 0.0F
         && var6
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.STICKY_HONEY
         )
       {
         var4 = (int)Math.floor(Math.max(1.0F, this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.RIIRRIORRHICOCCIHOHHCIRRHOORHR()));
      }

      double var7 = this.OIHCOHRCICCCRHRCROOCIOIRRHHHIH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2.x, var2.y, var2.z)
      );

      for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var10 : com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HORIZONTAL) {
         com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var11 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2.x + var10.getOffsetX(), var2.y, var2.z + var10.getOffsetZ(), var4, var7, var10, var6
         );
         this.CIHCCRRIIIRCIRROICIOCIOCHCRHCC[var10.getHorizontal()] = var11;
         if (this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var11, var2)) {
            var1[var3++] = var11;
         }
      }

      for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var14 : com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HORIZONTAL) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var15 = var14.rotateYClockwise();
         if (this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2, this.CIHCCRRIIIRCIRROICIOCIOCHCRHCC[var14.getHorizontal()], this.CIHCCRRIIIRCIRROICIOCIOCHCRHCC[var15.getHorizontal()]
         )) {
            com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var12 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var2.x + var14.getOffsetX() + var15.getOffsetX(), var2.y, var2.z + var14.getOffsetZ() + var15.getOffsetZ(), var4, var7, var14, var6
            );
            if (this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var12)) {
               var1[var3++] = var12;
            }
         }
      }

      return var3;
   }

   public boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      @Nullable com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      return var1 != null && !var1.closed && (var1.OCRIOCCRHHIHCCCOHRIORIHCCROROC >= 0.0F || var2.OCRIOCCRHHIHCCCOHRIORIHCCROROC < 0.0F);
   }

   public boolean RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI
         .OIIHICRIICHCHIROIOHRRCHICOCOCO();
      CRHROHHHCIHHCOHCOORCRIHHIICROR var3 = CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
         var1.x - this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosX() + var2.HHROCOOOROICCOOCHOHCIHOCORIIOO() / 2.0,
         var1.y - this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosY() + var2.HIOOCIRHRRHCRHRCRCHHCICIRIHHCR() / 2.0,
         var1.z - this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.bridge$getPosZ() + var2.CHHCCORHOROHRCHOROOHORCRHHHHCI() / 2.0
      );
      int var4 = (int)Math.ceil(var3.bridge$lengthVector() / var2.bridge$getSize());
      var3 = var3.OCOHORHCROHICRRIHCIHHRRCIHICRI(1.0F / var4);

      for (int var5 = 1; var5 <= var4; var5++) {
         var2 = var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3);
         if (this.CRRRICCRROCOHHOHIICIHORCOORRRH(var2)) {
            return false;
         }
      }

      return true;
   }

   public static double RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HRCHROOHRIHCRCRHRIIROCIRHOIRHH var0, RORCHCIIICOHIRROOORHOCCCCIOCCI var1) {
      RORCHCIIICOHIRROOORHOCCCCIOCCI var2 = var1.bridge$below();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3;
      if (var2 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4) {
         var3 = var4;
      } else {
         var3 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2.bridge$getX(), var2.bridge$getY(), var2.bridge$getZ());
      }

      double var6 = var0.OCOHORHCROHICRRIHCIHHRRCIHICRI(var2).bridge$getCollisionHeight(var0, var3);
      return var2.bridge$getY() + var6;
   }

   public boolean CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      return this.IOCCIRRORRORRCCOIHOOOCRRCRRHHO
         .computeIfAbsent(
            var1,
            var1x -> !this.RIRIOORHCHOICORIHIOHRCIHHRCRRR
               .ORCORRRCCRHHCORRCRCCHCOIRICIRC()
               .bridge$noCollision(
                  null, (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var1x
               )
         );
   }

   public double OIHCOHRCICCCRHRCROOCIOIRRHHHIH(RORCHCIIICOHIRROOORHOCCCCIOCCI var1) {
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var2 = this.RIRIOORHCHOICORIHIOHRCIHHRCRRR.ORCORRRCCRHHCORRCRCCHCOIRICIRC();
      return (this.ROIOHOROCRROCHOCIIICHOOHHRIIRH || this.CHCCCRHICRIOCCRIRIRIIIOCRORCIR()) && var2.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1).bridge$isWater()
         ? var1.bridge$getY() + 0.5
         : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var1);
   }

   public boolean CHCCCRHICRIOCCRIRIRIIIOCRORCIR() {
      return false;
   }

   @Nullable
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      int var1,
      int var2,
      int var3,
      int var4,
      double var5,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9 = null;
      RORCHCIIICOHIRROOORHOCCCCIOCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var10 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
         .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
      double var11 = this.OIHCOHRCICCCRHRCROOCIOIRRHHHIH(var10);
      if (var11 - var5 > this.IHCCHRCHRHORIOOCOIHHIIOOIHCOOC()) {
         return null;
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var13 = this.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
         var1, var2, var3
      );
      float var14 = this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var13);
      if (var14 >= 0.0F) {
         var9 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var13, var14);
      }

      if (CRRRICCRROCOHHOHIICIHORCOORRRH(var8) && var9 != null && var9.OCRIOCCRHHIHCCCOHRIORIHCCROROC >= 0.0F && !this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var9)) {
         var9 = null;
      }

      if (var13
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WALKABLE
         && (
            !this.CHCCCRHICRIOCCRIRIRIIIOCRORCIR()
               || var13
                  != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WATER
         )) {
         if ((var9 == null || var9.OCRIOCCRHHIHCCCOHRIORIHCCROROC < 0.0F)
            && var4 > 0
            && (
               var13
                     != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FENCE
                  || this.CRRHRCCHHROCRHHHRRHOHCIIRHCRCR()
            )
            && var13
               != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.UNPASSABLE_RAIL
            && var13
               != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.TRAPDOOR
            && var13
               != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.POWDER_SNOW
            )
          {
            var9 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var4, var5, var7, var8, var10);
         } else if (!this.CHCCCRHICRIOCCRIRIRIIIOCRORCIR()
            && var13
               == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WATER
            && !this.ROIOHOROCRROCHOCIIICHOOHHRIIRH) {
            var9 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var9);
         } else if (var13
            == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OPEN
            )
          {
            var9 = this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(var1, var2, var3);
         } else if (CRRRICCRROCOHHOHIICIHORCOORRRH(var13) && var9 == null) {
            var9 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var13);
         }
      }

      return var9;
   }

   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(
      RORCHCIIICOHIRROOORHOCCCCIOCCI var1
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = this.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
         var1
      );
      var2.OICHHHIIRORHORCICHHRIOHHOIRHOI = this.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(var2.x, var2.y, var2.z);
      var2.OCRIOCCRHHIHCCCOHRIORIHCCROROC = this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2.OICHHHIIRORHORCICHHRIOHHOIRHOI);
      return var2;
   }

   public static boolean CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0
   ) {
      return var0
            == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FENCE
         || var0
            == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DOOR_CLOSED;
   }

   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      int var1,
      int var2,
      int var3,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4,
      float var5
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = this.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
         var1, var2, var3
      );
      var6.OICHHHIIRORHORCICHHRIOHHOIRHOI = var4;
      var6.OCRIOCCRHHIHCCCOHRIORIHCCROROC = Math.max(var6.OCRIOCCRHHIHCCCOHRIORIHCCROROC, var5);
      return var6;
   }

   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IHCRORHRORIICHRHRCHRRIRRHHOCOO(
      int var1, int var2, int var3
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = this.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
         var1, var2, var3
      );
      var4.OICHHHIIRORHORCICHHRIOHHOIRHOI = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BLOCKED;
      var4.OCRIOCCRHHIHCCCOHRIORIHCCROROC = -1.0F;
      return var4;
   }

   public boolean ICICIOCHHHIHOCHCOHORIHRCOHHOCR(RORCHCIIICOHIRROOORHOCCCCIOCCI var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = this.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
         var1.bridge$getX(), var1.bridge$getY(), var1.bridge$getZ()
      );
      return var2
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OPEN
         && this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2) >= 0.0F;
   }

   public double IHCCHRCHRHORIOOCOIHHIIOOIHCOOC() {
      return Math.max(1.125, this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.RIIRRIORRHICOCCIHOHHCIRRHOORHR());
   }

   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      @Nullable com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      @Nullable com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3
   ) {
      if (var3 != null
         && var2 != null
         && var3.y <= var1.y
         && var2.y <= var1.y
         && var2.OICHHHIIRORHORCICHHRIOHHOIRHOI
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WALKABLE_DOOR
         && var3.OICHHHIIRORHORCICHHRIOHHOIRHOI
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WALKABLE_DOOR
         )
       {
         boolean var4 = var3.OICHHHIIRORHORCICHHRIOHHOIRHOI
               == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FENCE
            && var2.OICHHHIIRORHORCICHHRIOHHOIRHOI
               == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FENCE
            && this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.OIIHICRIICHCHIROIOHRRCHICOCOCO().HHROCOOOROICCOOCHOHCIHOCORIIOO() < 0.5;
         return (var3.y < var1.y || var3.OCRIOCCRHHIHCCCOHRIORIHCCROROC >= 0.0F || var4)
            && (var2.y < var1.y || var2.OCRIOCCRHHIHCCCOHRIORIHCCROROC >= 0.0F || var4);
      } else {
         return false;
      }
   }

   public boolean RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      @Nullable com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      if (var1 == null || var1.closed) {
         return false;
      } else {
         return var1.OICHHHIIRORHORCICHHRIOHHOIRHOI
               == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WALKABLE_DOOR
            ? false
            : var1.OCRIOCCRHHIHCCCOHRIORIHCCROROC >= 0.0F;
      }
   }

   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      int var1,
      int var2,
      int var3,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = this.ORHIOICIOCRRHOOCOHRORIHICHRCRR(
         var1, var2, var3
      );
      var5.closed = true;
      var5.OICHHHIIRORHORCICHHRIOHHOIRHOI = var4;
      var5.OCRIOCCRHHIHCCCOHRIORIHCCROROC = var4.getMalus();
      return var5;
   }

   @Nullable
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      int var1,
      int var2,
      int var3,
      int var4,
      double var5,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8,
      RORCHCIIICOHIRROOORHOCCCCIOCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var10 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1, var2 + 1, var3, var4 - 1, var5, var7, var8
      );
      if (var10 == null) {
         return null;
      }

      if (this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.OIIHICRIICHCHIROIOHRRCHICOCOCO().HHROCOOOROICCOOCHOHCIHOCORIIOO() >= 1.0) {
         return var10;
      }

      if (var10.OICHHHIIRORHORCICHHRIOHHOIRHOI
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OPEN
         && var10.OICHHHIIRORHORCICHHRIOHHOIRHOI
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WALKABLE
         )
       {
         return var10;
      }

      double var11 = var1 - var7.getOffsetX() + 0.5;
      double var13 = var3 - var7.getOffsetZ() + 0.5;
      double var15 = this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.OIIHICRIICHCHIROIOHRRCHICOCOCO().HHROCOOOROICCOOCHOHCIHOCORIIOO() / 2.0;
      var9.HICRRICCHCCROOHHCHOCOCCHOIHHOC(var11, var2 + 1, var13);
      double var17 = this.OIHCOHRCICCCRHRCROOCIOIRRHHHIH(var9) + 0.001;
      var9.bridge$setPos(var10.x, var10.y, var10.z);
      double var19 = this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.OIIHICRIICHCHIROIOHRRCHICOCOCO().HIOOCIRHRRHCRHRCRCHHCICIRIHHCR()
         + this.OIHCOHRCICCCRHRCROOCIOIRRHHHIH(var9)
         - 0.002;
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var21 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
         var11 - var15, var17, var13 - var15, var11 + var15, var19, var13 + var15
      );
      return this.CRRRICCRROCOHHOHIICIHORCOORRRH(var21) ? null : var10;
   }

   @Nullable
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      int var1,
      int var2,
      int var3,
      @Nullable com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4
   ) {
      var2--;

      while (var2 > IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH().bridge$getMinBuildHeight()) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = this.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
            var1, var2, var3
         );
         if (var5
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WATER
            )
          {
            return var4;
         }

         var4 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var5, this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5));
         var2--;
      }

      return var4;
   }

   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ICICIOCHHHIHOCHCOHORIHRCOHHOCR(
      int var1, int var2, int var3
   ) {
      for (int var4 = var2 - 1; var4 >= IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH().bridge$getMinBuildHeight(); var4--) {
         if (var2 - var4 > this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.RRHOIHCOCIOIOIHORHORCORCIICCCH()) {
            return this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(var1, var4, var3);
         }

         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = this.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
            var1, var4, var3
         );
         float var6 = this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5);
         if (var5
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OPEN
            )
          {
            if (var6 >= 0.0F) {
               return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var4, var3, var5, var6);
            }

            return this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(var1, var4, var3);
         }
      }

      return this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(var1, var2, var3);
   }

   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(
      int var1, int var2, int var3
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3);
      return (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)this.RHOHIHCOHCICICCOOHOCIIOIROIRRR
         .computeIfAbsent(
            var4.bridge$asLong(),
            var4x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.RIRIOORHCHOICORIHIOHRCIHHRCRRR, var1, var2, var3, this.COIHCHHCOIIRHOHORIHHCCCOHRHRCI)
         );
   }

   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1,
      int var2,
      int var3,
      int var4,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5
   ) {
      Set var6 = this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3, var4);
      if (var6.contains(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FENCE
      )) {
         return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FENCE;
      }

      if (var6.contains(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.UNPASSABLE_RAIL
      )) {
         return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.UNPASSABLE_RAIL;
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BLOCKED;

      for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9 : var6) {
         if (var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var9) < 0.0F) {
            return var9;
         }

         if (var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var9) >= var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7)) {
            var7 = var9;
         }
      }

      return this.HOCCOIHICOCHHCRICHOCHCCOCCORHO <= 1
            && var7
               != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OPEN
            && var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7) == 0.0F
            && this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var4)
               == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OPEN
         ? com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OPEN
         : var7;
   }

   public Set<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1,
      int var2,
      int var3,
      int var4
   ) {
      EnumSet var5 = EnumSet.noneOf(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class
      );

      for (int var6 = 0; var6 < this.HOCCOIHICOCHHCRICHOCHCCOCCORHO; var6++) {
         for (int var7 = 0; var7 < this.HHOHIRORHCCHCOOOHHHHCHIHCCHHOO; var7++) {
            for (int var8 = 0; var8 < this.CIORICRRCOCIRRRHCIOIHHRIHHHICC; var8++) {
               int var9 = var6 + var2;
               int var10 = var7 + var3;
               int var11 = var8 + var4;
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var12 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1, var9, var10, var11
               );
               var5.add(var12);
            }
         }
      }

      return var5;
   }

   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1,
      int var2,
      int var3,
      int var4
   ) {
      return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1,
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
            .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var3, var4)
      );
   }

   public static com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var0,
      RORCHCIIICOHIRROOORHOCCCCIOCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      int var2 = var1.bridge$getX();
      int var3 = var1.bridge$getY();
      int var4 = var1.bridge$getZ();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         var0, var2, var3, var4
      );
      if (var5
            == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OPEN
         && var3 >= var0.ORCORRRCCRHHCORRCRCCHCOIRICIRC().bridge$getMinBuildHeight() + 1) {
         return switch (HHCCIRHCCCIIRHCROHIORHIRHHIORH(var0, var2, var3 - 1, var4)) {
            case OPEN, WATER, LAVA, WALKABLE -> com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OPEN;
            case DAMAGE_FIRE -> com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DAMAGE_FIRE;
            case DAMAGE_OTHER -> com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DAMAGE_OTHER;
            case STICKY_HONEY -> com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.STICKY_HONEY;
            case POWDER_SNOW -> com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DANGER_POWDER_SNOW;
            case DAMAGE_CAUTIOUS -> com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DAMAGE_CAUTIOUS;
            case TRAPDOOR -> com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DANGER_TRAPDOOR;
            default -> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var0,
               var2,
               var3,
               var4,
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WALKABLE
            );
         };
      } else {
         return var5;
      }
   }

   public static com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var0,
      int var1,
      int var2,
      int var3,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4
   ) {
      for (int var5 = -1; var5 <= 1; var5++) {
         for (int var6 = -1; var6 <= 1; var6++) {
            for (int var7 = -1; var7 <= 1; var7++) {
               if (var5 != 0 || var7 != 0) {
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8 = HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                     var0, var1 + var5, var2 + var6, var3 + var7
                  );
                  if (var8
                     == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DAMAGE_OTHER
                     )
                   {
                     return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DANGER_OTHER;
                  }

                  if (var8
                        == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DAMAGE_FIRE
                     || var8
                        == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.LAVA
                     )
                   {
                     return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DANGER_FIRE;
                  }

                  if (var8
                     == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WATER
                     )
                   {
                     return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WATER_BORDER;
                  }

                  if (var8
                     == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DAMAGE_CAUTIOUS
                     )
                   {
                     return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DAMAGE_CAUTIOUS;
                  }
               }
            }
         }
      }

      return var4;
   }

   public static com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var0,
      int var1,
      int var2,
      int var3
   ) {
      var0.HOHRORCRIIRHIROCHHCHIIIICOCIHH().bridge$setPos(var1, var2, var3);
      return var0.ORCORRRCCRHHCORRCRCCHCOIRICIRC().bridge$getPathTypeFromState(var0.HOHRORCRIIRHIROCHHCHIIIICOCIHH());
   }
}
