package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI;

import java.math.BigDecimal;
import java.math.BigInteger;

public interface IIHRRHORCRCROCHHOHORCHCROCIHRO {
   ORHIOICIOCRRHOOCOHRORIHICHRCRR HRHRRRIROIRIOOCHROIHCRHIROCOIH(boolean var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR CIHCHHIHCIHRRRIOCHOCHOHOHROCRR();

   ORHIOICIOCRRHOOCOHRORIHICHRCRR HICHRCOHCCRHOHCICOOCHOIHCCHIRI(byte var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR CRRRICCRROCOHHOHIICIHORCOORRRH(Byte var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR CRICCOOHHHCHOORCICOCOHIHOIRHOO(short var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR RRCRRCORICCHOHHIRCHIROOHIIOHCO(Short var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR CIHHOOCCORHOIHRRRRCICIOIOIIHIH(int var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR ORIOHRCIHRCOOHICCCRIIIHCRHHIHI(Integer var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR CHRHCRCCIICRORCOHCORHRROIHRCHO(long var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR IIHRRHORCRCROCHHOHORCHCROCIHRO(Long var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR HRCHROOHRIHCRCRHRIIROCIRHOIRHH(BigInteger var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR RRCIRIHRCIOOICCCHOIHOCIRCHHIII(float var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR RIROICHCRROROHCCROOCCCCOCHCCRI(Float var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR HCOIOHCCHIHRCHCCICCIRCIOHCRIHH(double var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR IIRHCHHOICHRICOOCRORCCIOOIHOIR(Double var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR IOIICIRIICICIIOORHCIIIIRRIHRHI(BigDecimal var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR OOCIIOOHHRCORHICCCICRCCHCRHROR(String var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR RRRHHIRORHCHHCOOCIHOICORHHCHHO(byte[] var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR COIHORRCHRRCHOCIRHHRRIOIHRIHCC(byte[] var1, int var2, int var3);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR RORROCOIOHHOCCHRCHIIOHIHCRIIOO(Object var1);

   ORHIOICIOCRRHOOCOHRORIHICHRCRR IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO var1
   );

   RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IHCRIRCRIOCRRCRHCOOCIHOHRHORHR();

   RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HRHOORCROIRCCCIHRHHRHHIRCOCOHR(int var1);

   HICRRICCHCCROOHHCHOCOCCHOIHHOC HCHHCOCCORCCROIRHORIIOOORRCCHH();
}
