package com.moonsworth.lunar.client.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.google.gson.JsonObject;
import java.util.List;

public record RRCRRCORICCHOHHIRCHIROOHIIOHCO() {
   private final JsonObject ORCCHOIOCOCRHIOOCHIRHIHCIOICRI;
   private final JsonObject CIRCRRRRRIRIIHOCOHROIOROHRORIH;
   private final JsonObject HCRROCIIRCOROIRHRRIIIHOHRCCCCC;
   private final JsonObject RCHRCCRIROHRRIOOIROCIOCHIHROHH;
   private final List<String> ORCRIRRIHHHICOCHCCRIOIRIHCIIIO;
   private final List<String> OOHOIHHIOOHHCHOICCROIROHOCCIOC;

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO(JsonObject var1, JsonObject var2, JsonObject var3, JsonObject var4, List<String> var5, List<String> var6) {
      this.ORCCHOIOCOCRHIOOCHIRHIHCIOICRI = var1;
      this.CIRCRRRRRIRIIHOCOHROIOROHRORIH = var2;
      this.HCRROCIIRCOROIRHRRIIIHOHRCCCCC = var3;
      this.RCHRCCRIROHRRIOOIROCIOCHIHROHH = var4;
      this.ORCRIRRIHHHICOCHCCRIOIRIHCIIIO = var5;
      this.OOHOIHHIOOHHCHOICCROIROHOCCIOC = var6;
   }

   public JsonObject CRRIOOICOICOHIOHHRHIRICIRRHOHH() {
      return this.ORCCHOIOCOCRHIOOCHIRHIHCIOICRI;
   }

   public JsonObject OIHIRCCOIHIHCCIHRHIIIRHICHIRRR() {
      return this.CIRCRRRRRIRIIHOCOHROIOROHRORIH;
   }

   public JsonObject ROCCHOOCCOCCICIOHIIOCIIRHOHRIH() {
      return this.HCRROCIIRCOROIRHRRIIIHOHRCCCCC;
   }

   public JsonObject IHRHOIORROCRRCORRHRIOCIOOHCIHO() {
      return this.RCHRCCRIROHRRIOOIROCIOCHIHROHH;
   }

   public List<String> ORIHCIOHCICOORCROIORIHICOCRIHO() {
      return this.ORCRIRRIHHHICOCHCCRIOIRIHCIIIO;
   }

   public List<String> OCHOHHCIIHOOOCRIOCHOIOORICHCCH() {
      return this.OOHOIHHIOOHHCHOICCROIROHOCCIOC;
   }
}
