package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIHRRHORCRCROCHHOHORCHCROCIHRO;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;

public class RRCRRCORICCHOHHIRCHIROOHIIOHCO extends IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH implements Serializable {
   private static final long CCOOOIHHICIHOHHHCHOHORIHHCICOC = 3L;
   protected HashMap<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH, RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?>> HIOIOROOCCRCHHRHHCCRCROCHCROIO = null;
   protected HashMap<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH, RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?>> ORCOHRIRRHORIIIHIRCCOOHHHRRRIR = null;
   protected boolean ORIOIIIIHRRCICRCIHRIIRHIHOCHHR = false;

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO() {
   }

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO(List<RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?>> var1) {
      this.ICRHCCCCOIICOCHHCRCOOIHICROIHI(var1);
   }

   public void HRCHROOHRIHCRCRHRIIROCIRHOIRHH(RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var1) {
      Class var2 = var1.handledType();
      if (var2 != null && var2 != Object.class) {
         this.CRRRICCRROCOHHOHIICIHORCOORRRH(var2, var1);
      } else {
         throw new IllegalArgumentException(
            "JsonSerializer of type "
               + var1.getClass().getName()
               + " does not define valid handledType() -- must either register with method that takes type argument  or make serializer extend 'com.fasterxml.jackson.databind.ser.std.StdSerializer'"
         );
      }
   }

   public <T> void HHCCIRHCCCIIRHCROHIORHIRHHIORH(Class<? extends T> var1, RHOCHHIRRCHHHOHOIRROIROHHHIHIO<T> var2) {
      this.CRRRICCRROCOHHOHIICIHORCOORRRH(var1, var2);
   }

   public void ICRHCCCCOIICOCHHCRCOOIHICROIHI(List<RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?>> var1) {
      for (RHOCHHIRRCHHHOHOIRROIROHHHIHIO var3 : var1) {
         this.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var3);
      }
   }

   @Override
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> findSerializer(
      ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var1,
      OCOHORHCROHICRRIHCIHHRRCIHICRI var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3
   ) {
      Class var4 = var2.RRICIOOORRIORHHICIRCIOCHRHRCHH();
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         var4
      );
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO var6 = null;
      if (var4.isInterface()) {
         if (this.ORCOHRIRRHORIIIHIRCCOOHHHRRRIR != null) {
            var6 = this.ORCOHRIRRHORIIIHIRCCOOHHHRRRIR.get(var5);
            if (var6 != null) {
               return var6;
            }
         }
      } else if (this.HIOIOROOCCRCHHRHHCCRCROCHCROIO != null) {
         var6 = this.HIOIOROOCCRCHHRHHCCRCROCHCROIO.get(var5);
         if (var6 != null) {
            return var6;
         }

         if (this.ORIOIIIIHRRCICRCIHRIIRHIHOCHHR && var2.ORHRHCHCOHHORROCRRRCIHRIOORORC()) {
            var5.RRCIRIHRCIOOICCCHOIHOCIRCHHIII(Enum.class);
            var6 = this.HIOIOROOCCRCHHRHHCCRCROCHCROIO.get(var5);
            if (var6 != null) {
               return var6;
            }
         }

         for (Class var7 = var4; var7 != null; var7 = var7.getSuperclass()) {
            var5.RRCIRIHRCIOOICCCHOIHOCIRCHHIII(var7);
            var6 = this.HIOIOROOCCRCHHRHHCCRCROCHCROIO.get(var5);
            if (var6 != null) {
               return var6;
            }
         }
      }

      if (this.ORCOHRIRRHORIIIHIRCCOOHHHRRRIR != null) {
         var6 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var5);
         if (var6 != null) {
            return var6;
         }

         if (!var4.isInterface()) {
            while ((var4 = var4.getSuperclass()) != null) {
               var6 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var5);
               if (var6 != null) {
                  return var6;
               }
            }
         }
      }

      return null;
   }

   @Override
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> findArraySerializer(
      ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3,
      CORCOCICIRIOHROHROIIOOHICCHCRR var4,
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> var5
   ) {
      return this.findSerializer(var1, var2, var3);
   }

   @Override
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> findCollectionSerializer(
      ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3,
      CORCOCICIRIOHROHROIIOOHICCHCRR var4,
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> var5
   ) {
      return this.findSerializer(var1, var2, var3);
   }

   @Override
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> findCollectionLikeSerializer(
      ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3,
      CORCOCICIRIOHROHROIIOOHICCHCRR var4,
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> var5
   ) {
      return this.findSerializer(var1, var2, var3);
   }

   @Override
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> findMapSerializer(
      ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.CORCOCICIRIOHROHROIIOOHICCHCRR var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3,
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> var4,
      CORCOCICIRIOHROHROIIOOHICCHCRR var5,
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> var6
   ) {
      return this.findSerializer(var1, var2, var3);
   }

   @Override
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> findMapLikeSerializer(
      ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var1,
      OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3,
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> var4,
      CORCOCICIRIOHROHROIIOOHICCHCRR var5,
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> var6
   ) {
      return this.findSerializer(var1, var2, var3);
   }

   protected RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Class<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      for (Class var6 : var1.getInterfaces()) {
         var2.RRCIRIHRCIOOICCCHOIHOCIRCHHIII(var6);
         RHOCHHIRRCHHHOHOIRROIROHHHIHIO var7 = this.ORCOHRIRRHORIIIHIRCCOOHHHRRRIR.get(var2);
         if (var7 != null) {
            return var7;
         }

         var7 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, var2);
         if (var7 != null) {
            return var7;
         }
      }

      return null;
   }

   protected void CRRRICCRROCOHHOHIICIHORCOORRRH(Class<?> var1, RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var2) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         var1
      );
      if (var1.isInterface()) {
         if (this.ORCOHRIRRHORIIIHIRCCOOHHHRRRIR == null) {
            this.ORCOHRIRRHORIIIHIRCCOOHHHRRRIR = new HashMap<>();
         }

         this.ORCOHRIRRHORIIIHIRCCOOHHHRRRIR.put(var3, var2);
      } else {
         if (this.HIOIOROOCCRCHHRHHCCRCROCHCROIO == null) {
            this.HIOIOROOCCRCHHRHHCCRCROCHCROIO = new HashMap<>();
         }

         this.HIOIOROOCCRCHHRHHCCRCROCHCROIO.put(var3, var2);
         if (var1 == Enum.class) {
            this.ORIOIIIIHRRCICRCIHRIIRHIHOCHHR = true;
         }
      }
   }
}
