package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

@com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 1)
public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends RRCRRCORICCHOHHIRCHIROOHIIOHCO {
   @Override
   public boolean CIOHHCORHRCCRICCCORIHCRHCCCRRR(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1) {
      return "testoverlay".equals(this.ORHIOICIOCRRHOOCOHRORIHICHRCRR(var1));
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      ORHIOICIOCRRHOOCOHRORIHICHRCRR var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      int var3,
      int var4,
      float var5
   ) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIHORRIRHIIOOIHRROCCROHCOIHCHC
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("TestOverlay", var1, var2, var3, var4, false);
      String var6 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIHORRIRHIIOOIHRROCCROHCOIHCHC
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("TestOverlay-Textinput", 10, 10, 100, 10, "Text box", true);
      if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIHORRIRHIIOOIHRROCCROHCOIHCHC
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("Text: " + var6, 10, 30, 100, 16)
         != -1) {
         System.out.println("Text button was clicked with '" + var6 + "' as input!");
      }

      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIHORRIRHIIOOIHRROCCROHCOIHCHC
         .end();
   }

   @Override
   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1, int var2, int var3, int var4) {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIHORRIRHIIOOIHRROCCROHCOIHCHC
         .IRCIIHHICIHRCOCRROCOICRIHHCCHH("TestOverlay", var2, var3, var4);
   }

   @Override
   public boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1, int var2, int var3, int var4) {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIHORRIRHIIOOIHRROCCROHCOIHCHC
         .HHCCIRHCCCIIRHCROHIORHIRHHIORH("TestOverlay", var2, var3, var4);
   }

   @Override
   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      ORHIOICIOCRRHOOCOHRORIHICHRCRR var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIHORRIRHIIOOIHRROCCROHCOIHCHC
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("TestOverlay", var2);
   }

   @Override
   public void ROICRIORRCRCIIRRCIOCRCRIHCCIHR() {
      System.out.println("Opened TestOverlay");
   }

   @Override
   public void onClose() {
      System.out.println("Closed TestOverlay");
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIHORRIRHIIOOIHRROCCROHCOIHCHC
         .RHCCOIHOHRIHRRIIRHICRRROCICORR("TestOverlay");
   }
}
