package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import lombok.Generated;

abstract class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   protected int HOHRORCRIIRHIROCHHCHIIIICOCIHH = 0;

   public abstract boolean CIOHHCORHRCCRICCCORIHCRHCCCRRR(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1);

   public abstract void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      ORHIOICIOCRRHOOCOHRORIHICHRCRR var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      int var3,
      int var4,
      float var5
   );

   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1, int var2, int var3, int var4) {
      return false;
   }

   public boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1, int var2, int var3, int var4) {
      return false;
   }

   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1, double var2) {
      return false;
   }

   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1, int var2, int var3, int var4, long var5) {
      return false;
   }

   public void ORCOOCHRICHOIHHIHIOHCHCRIOHRCR() {
      this.HOHRORCRIIRHIROCHHCHIIIICOCIHH++;
   }

   public void ROCCCHHIHCCOROHIHHCCCHIRIRCRHH() {
   }

   public void ROICRIORRCRCIIRRCIOCRCRIHCCIHR() {
   }

   public void onClose() {
   }

   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      ORHIOICIOCRRHOOCOHRORIHICHRCRR var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      return false;
   }

   protected String ORHIOICIOCRRHOOCOHRORIHICHRCRR(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1) {
      return var1 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
         ? com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.getTextContent(
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.asAdventure(var2.bridge$title())
         )
         : null;
   }

   @Generated
   protected RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
   }
}
