package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.ByteBuffer;
import lombok.Generated;
import org.lwjgl.actually3.BufferUtils;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OCIIOOCHCRHICHOHRIHHRHOIHROCOR;
   private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ROROCRCCCCOROCCORROIOIOHICOHHR;
   private Object ICHIHCCCOICHRHIORROCCORRRIHCRH;
   private Object ROHIHHCIICCOICIIIRCRIIHRIORRCC;
   private final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IICOORROIHOICHCRHOIHCOCRORCRRI = IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROHOOHRICIROORROHCROCCOHHCORRI();
   private ByteBuffer CIOHOCIHRRHOHOIRIHCCRCHIICIHOR;
   private byte[] data;
   private File file;
   private OutputStream ORHROIHIHCHRIIHOIIHHHCOHRIOOCC;
   private long OICCIHOCIHOCIORIHHOICROHOCHHRC;
   private long RHHCHROCOOCOHHIHIRHRIRRIIHRCCH;

   public void RRRIICRCOOICOICIORRCRRIRORHHRR() {
      if (this.ICHIHCCCOICHRHIORROCCORRRIHCRH != null && this.ICHIHCCCOICHRHIORROCCORRRIHCRH != 0L) {
         try {
            this.IICOORROIHOICHCRHOIHCOCRORCRRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(this.ICHIHCCCOICHRHIORROCCORRRIHCRH);
            this.IICOORROIHOICHCRHOIHCOCRORCRRI.IIHRRHORCRCROCHHOHORCHCROCIHRO(this.ICHIHCCCOICHRHIORROCCORRRIHCRH);
         } catch (Exception var3) {
            var3.printStackTrace();
         }
      }

      this.ICHIHCCCOICHRHIORROCCORRRIHCRH = this.IICOORROIHOICHCRHOIHCOCRORCRRI.CROHHORHOOORICOCHCOOHIROIOCIRO(null);
      if (this.ICHIHCCCOICHRHIORROCCORRRIHCRH != null && this.ICHIHCCCOICHRHIORROCCORRRIHCRH != 0L) {
         int var1 = this.ROROCRCCCCOROCCORROIOIOHICOHHR.OCROHCHHCOIIOCCIIHROHCIRHIORCR() ? 5377 : 5376;
         if (!this.IICOORROIHOICHCRHOIHCOCRORCRRI
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.ICHIHCCCOICHRHIORROCCORRRIHCRH, this.ROROCRCCCCOROCCORROIOIOHICOHHR.getFrequency(), var1, 5122)) {
            throw new IllegalStateException("The loopback device does not support the required format.");
         } else {
            int[] var2 = new int[]{4103, this.ROROCRCCCCOROCCORROIOIOHICOHHR.getFrequency(), 6544, var1, 6545, 5122, 6554, 1, 0};
            this.ROHIHHCIICCOICIIIRCRIIHRIORRCC = this.IICOORROIHOICHCRHOIHCOCRORCRRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.ICHIHCCCOICHRHIORROCCORRRIHCRH, var2);
            if (this.ROHIHHCIICCOICIIIRCRIIHRIORRCC == null || this.ROHIHHCIICCOICIIIRCRIIHRIORRCC == 0L) {
               throw new IllegalStateException("Failed to create the loopback context.");
            }
         }
      } else {
         throw new IllegalStateException("Failed to open the loopback device.");
      }
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      File var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3
   ) {
      this.file = var1;
      this.ROROCRCCCCOROCCORROIOIOHICOHHR = var2;
      this.OCIIOOCHCRHICHOHRIHHRHOIHROCOR = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.getFormat(
         var2.OCROHCHHCOIIOCCIIHROHCIRHIORCR() ? 2 : 1, 2
      );
      float var4 = var2.getFrequency() / 1000.0F;
      int var5 = (int)(var4 * Math.ceil(1000.0F / var2.ICRCHRIRHCRROORHCROHHICRCCCCHO())) * this.OCIIOOCHCRHICHOHRIHHRHOIHROCOR.getChannels();
      int var6 = var5 * this.OCIIOOCHCRHICHOHRIHHRHOIHROCOR.getBytesPerSample();
      this.CIOHOCIHRRHOHOIRIHCCRCHIICIHOR = BufferUtils.createByteBuffer(var6);
      this.data = new byte[var6];
      this.ORHROIHIHCHRIIHOIIHHHCOHRIOOCC = new BufferedOutputStream(new FileOutputStream(var1));
      this.OICCIHOCIHOCIORIHHOICROHOCHHRC = 0L;
      this.RHHCHROCOOCOHHIHIRHRIRRIIHRCCH = 0L;
      IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSoundHandler().bridge$reload();
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      long var2
   ) {
      long var4 = var2 * this.ROROCRCCCCOROCCORROIOIOHICOHHR.getFrequency() / this.ROROCRCCCCOROCCORROIOIOHICOHHR.ICRCHRIRHCRROORHCROHHICRCCCCHO();
      int var6 = (int)(var4 - this.OICCIHOCIHOCIORIHHOICROHOCHHRC);
      this.OICCIHOCIHOCIORIHHOICROHOCHHRC = var4;
      long var7 = var2 * 1000L / this.ROROCRCCCCOROCCORROIOIOHICOHHR.ICRCHRIRHCRROORHCROHHICRCCCCHO();
      long var9 = var7 - this.RHHCHROCOOCOHHIHIRHRIRRIIHRCCH;
      this.RHHCHROCOOCOHHIHIRHRIRRIIHRCCH = var7;
      this.CIOHOCIHRRHOHOIRIHCCRCHIICIHOR.clear();
      this.IICOORROIHOICHCRHOIHCOCRORCRRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(this.ICHIHCCCOICHRHIORROCCORRRIHCRH, this.CIOHOCIHRRHOHOIRIHCCRCHIICIHOR, var6);

      try {
         int var11 = var6 * this.OCIIOOCHCRHICHOHRIHHRHOIHROCOR.getChannels() * this.OCIIOOCHCRHICHOHRIHHRHOIHROCOR.getBytesPerSample();
         this.CIOHOCIHRRHOHOIRIHCCRCHIICIHOR.get(this.data, 0, var11);
         this.ORHROIHIHCHRIIHOIIHHHCOHRIOOCC.write(this.data, 0, var11);
      } catch (IOException var12) {
         var12.printStackTrace();
      }

      var1.COIIRRRCCRRRIRICICOCHRCCCRRICH().OOCCRCRCOHIIORCCORCRCIRRROIOOR(var9);
   }

   public void IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      this.ORHROIHIHCHRIIHOIIHHHCOHRIOOCC.close();

      try {
         var1.COIIRRRCCRRRIRICICOCHRCCCRRICH().cleanup();
         this.IICOORROIHOICHCRHOIHCOCRORCRRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(this.ICHIHCCCOICHRHIORROCCORRRIHCRH);
         this.IICOORROIHOICHCRHOIHCOCRORCRRI.IIHRRHORCRCROCHHOHORCHCROCIHRO(this.ICHIHCCCOICHRHIORROCCORRRIHCRH);
      } catch (Exception var6) {
         var6.printStackTrace();
      } finally {
         this.ICHIHCCCOICHRHIORROCCORRRIHCRH = null;
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
            .bridge$schedule(() -> IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSoundHandler().bridge$reload());
      }
   }

   public void destroy() {
      if (this.ROHIHHCIICCOICIIIRCRIIHRIORRCC != null && IRCIIHHICIHRCOCRROCOICRIHHCCHH.getMinecraftVersion().OOICHHIHHIHROCCRRRIIIIRIRICCIH()) {
         this.IICOORROIHOICHCRHOIHCOCRORCRRI.OCOHORHCROHICRRIHCIHHRRCIHICRI(this.ROHIHHCIICCOICIIIRCRIIHRIORRCC);
      }
   }

   @Generated
   public Object CCCHHOHCOHHHHHIIHIHCRIIHCOIIHR() {
      return this.ICHIHCCCOICHRHIORROCCORRRIHCRH;
   }

   @Generated
   public Object CRCOROIRICHHOCOICHCIOHCROHCHRC() {
      return this.ROHIHHCIICCOICIIIRCRIIHRIORRCC;
   }

   @Generated
   public File getFile() {
      return this.file;
   }
}
