package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OOOOCCOOOHCHCIIHOIHCRIIOOROHRC;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.HashSet;
import org.jetbrains.annotations.Nullable;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   RIOOCHICIHRHOHCCCCCHOCCCOHCRHI IOCICCICOCORRIOCHHORCHCRCOHHHR = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.class);
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI RRCRHHRHHIIHCIIOIOIIOIHHOIHOHI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "etherwarpPreviewColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(1157562623)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI ORHIROICHCCHIIHIHRROIIROHCCOHI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "etherwarpPreviewInvalid"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI IORCIICRROOROHORRRORRORRIOHCCI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "etherwarpPreviewInvalidColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(1157562368)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HIHRORICRRIOOHRCIRIHHIHRIHIIOI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "etherwarpPreviewShowThroughWalls"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OOOOCCOOOHCHCIIHOIHCRIIOOROHRC HOCOOHOOCRRIOCRRORIOROIIHIIHOH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IHIOHHCIRCORCHHIRRRRHCCCORCHIC(
         "etherwarpValidSound"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OOOOCCOOOHCHCIIHOIHCRIIOOROHRC ORORCHCIORRRHIHOOCCRROICRIIHCH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IHIOHHCIRCORCHHIRRRRHCCCORCHIC(
         "etherwarpInvalidSound"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HashSet<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> ORCIIOCRCHRCRHRCIRRRCOHIHHICIC;

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(true);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ITEMS
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI::RRRCCHIOCICOIOIRRCOOIRHHCORCIH
         )
      );
      this.handle(RRCRRCORICCHOHHIRCHIROOHIIOHCO.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(ORHIOICIOCRRHOOCOHRORIHICHRCRR.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         this::IRCIIHHICIHRCOCRROCOICRIHHCCHH
      );
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII();
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC = new HashSet<>();
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.RIOHCCCCIRIROIHCHIIRCCHOHHIOHR());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.IIOOHRRHRIIRRCICIRCORHCHORORHO());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.IRHOHHRHCIHHOOOHIHOCCICHOROOCO());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.ROIOCCCOORCHCIIROORRRCHCOHCCII());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.OCCHCOCHHRORORHICHRRHCCICCIIIH());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.RHIICHCRRORRROCHRRHOORCORIOCRH());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.IROHOHRHROICICIHRCIHCOCRIHOHHC());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.IOCCCCOCCCIIOCROHCRIOCCCCHIRHC());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.HRHROCRCHOHRIIIICOCOROOOIRRRCH());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.ROOHCOHROHHCRICROHOHHOHIHHHRRO());
      this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.IHRIHICCOHRCCCRHIHRIROORCCHIRH());
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 33) {
         this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.ORRRCRCCHIRHIHRHIROROCOHROCHCO());
         this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.add(var2.IRORRCRORIHIIROORHIIRHROOIIHOO());
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RRCRRCORICCHOHHIRCHIROOHIIOHCO var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      if (var2 != null) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = this.OCIIROIOORRIOIIIRHIRRCCIIRRROH(
            var1.HHIIOHOORHHCCHRHHRCIORCROORCOI().HOHIHCIHIHRCOOIOCOHIOHROHHIOHR()
         );
         if (var3 != null && var3.RRCHHOCOIORORHIIROIHHIRCIOOIIH() != null) {
            RORCHCIIICOHIRROOORHOCCCCIOCCI var4 = var3.RRCHHOCOIORORHIIROIHHIRCIOOIIH();
            OHHRIOHROOIHOROCIRHCHORIHRRRRI var5 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3.ROCIIRCOORHCCCCHCOCIRRIRICICCH());
            if (var5 != null) {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = var2.CIOHHCORHRCCRICCCORIHCRHCCCRRR(
                     var4
                  )
                  .bridge$getAABB(var2, var4);
               if (var6 != null) {
                  RORCHCIIICOHIRROOORHOCCCCIOCCI var7 = var4.bridge$offset(0, 1, 0);
                  if (var2.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var7).bridge$isCarpet()) {
                     var6 = var6.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(0.0, 1.1, 0.0);
                     var6 = var6.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(1.0, 1.1, 1.0);
                  }

                  this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var6.RRCRRCORICCHOHHIRCHIROOHIIOHCO(0.01).IRCIIHHICIHRCOCRROCOICRIHHCCHH(var4), var5);
               }
            }
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1) {
      if (var1.CCHIRIHIOHIRRIORROIHHRIROOHCOC() == this.IOCICCICOCORRIOCHHORCHCRCOHHHR.OROOOOIRRCHIOROCROIOOOIROOICIO()) {
         OIHCOHRCICCCRHRCROOCIOIRRHHHIH var2 = this.mc.bridge$getObjectMouseOver();
         if (var2 == null || !var2.bridge$isTypeOfHit(RHOCHHIRRCHHHOHOIRROIROHHHIHIO.BLOCK)) {
            this.CICCRHROCROIOHOCHORICRIIOOCHOI();
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      if (var1.OOCHIRIROOICOCOOHHOHCICHRHIRHO() == 0) {
         this.CICCRHROCROIOHOCHORICRIIOOCHOI();
      }
   }

   private void CICCRHROCROIOHOCHORICRIIOOCHOI() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = this.OCIIROIOORRIOIIIRHIRRCCIIRRROH(
         1.0F
      );
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = var1
            == null
         ? com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NONE
         : var1.ROCIIRCOORHCCCCHCOCIRRIRICICCH();
      if (var2
         == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.VALID
         )
       {
         com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.HOCOOHOOCRRIOCRRORIOROIIHIIHOH, this
         );
      } else if (var2
         == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.INVALID
         )
       {
         com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.ORORCHCIORRRHIHOOCCRROICRIIHCH, this
         );
      }
   }

   @Nullable
   private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OCIIROIOORRIOIIIRHIRRCCIIRRROH(float var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      if (var2 != null && var3 != null) {
         IIRHCHHOICHRICOOCRORCCIOOIHOIR var4 = this.IOCICCICOCORRIOCHHORCHCRCOHHHR.OROOOOIRRCHIOROCROIOOOIROOICIO();
         if (var4 == null) {
            return null;
         }

         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = var4.bridge$getDataComponent(
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRCHCROCHRROHROOCCHIHIOCHOICOC
         );
         return !this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5, var2.bridge$isSneaking())
            ? null
            : this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var5, var1)
               .ICIORHHOCHHHIIICIHIIRHHOCIIHIH()
               .map(
                  var2x -> {
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3x = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
                        .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           var2x.HRICRCHIIHIIICIHCICRHOOCRCCHIO().bridge$getX(),
                           var2x.HRICRCHIIHIIICIHCICRHOOCRCCHIO().bridge$getY(),
                           var2x.HRICRCHIIHIIICIHCICRHOOCRCCHIO().bridge$getZ()
                        );
                     int var4x = (int)Math.ceil(var3.OCOHORHCROHICRRIHCIHHRRCIHICRI(var3x).bridge$getCollisionShapeMaxY(var3, var3x));
                     RORCHCIIICOHIRROOORHOCCCCIOCCI var5x = var3x.bridge$offset(0, var4x, 0);
                     RORCHCIIICOHIRROOORHOCCCCIOCCI var6 = var3x.bridge$offset(0, var4x + 1, 0);
                     return new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        var3x, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3x, var5x, var6)
                     );
                  }
               )
               .orElseGet(
                  () -> new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     null,
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.INVALID
                  )
               );
      } else {
         return null;
      }
   }

   private boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      boolean var2
   ) {
      return this.IOCICCICOCORRIOCHHORCHCRCOHHHR.COHRHRIIROIICHHHHCHCCHOIRROOHO().equals("ETHERWARP_CONDUIT")
         ? true
         : com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               var1
            )
            && var2;
   }

   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1,
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3,
      float var4
   ) {
      int var5 = 57 + this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3);
      return (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIIROOHHCOOHCHHRIIOOCRRCIHRICH
         )
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var5, var4)
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var2x, var3x) -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var2x, var3x))
         .OHCOIORHOCCRICIHIOIRHRIRROCHRR()
         .CHRCRHHRCCOICCOOIIRIOHCOHCHHIC(var2);
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RRCRRCORICCHOHHIRCHIROOHIIOHCO var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      OHHRIOHROOIHOROCIRHCHORIHRRRRI var3
   ) {
      boolean var4 = this.HIHRORICRRIOOHRCIRIHHIHRIHIIOI.get();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var5 = var1.HHIIOHOORHHCCHRHHRCIORCROORCOI();
      var5.push();
      var5.translate(-var1.getX(), -var1.getY(), -var1.getZ());
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH var6 = var5.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         var4
            ? com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRHOIICRCICCICRHHOCIOOHIHIORRO
            : com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HCCCRCCCOOCROOHRCHCRIHHRHHOHHC
      );
      var6.HICHHHOOCRROHCCCCOOHOCHHOIOHCR();
      CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var6,
         var2.bridge$getMinX(),
         var2.bridge$getMinY(),
         var2.bridge$getMinZ(),
         var2.bridge$getMaxX(),
         var2.bridge$getMaxY(),
         var2.bridge$getMaxZ(),
         var3.OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F)
      );
      var6.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.BATCHED
      );
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var7 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
            HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
         )
         .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var8 = var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var7.CHICCHOOCRHHRIHOHRCICCOOOIHHII().get(), var4
      );
      CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var8,
         var2.bridge$getMinX(),
         var2.bridge$getMinY(),
         var2.bridge$getMinZ(),
         var2.bridge$getMaxX(),
         var2.bridge$getMaxY(),
         var2.bridge$getMaxZ(),
         com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI.ICORRRIOCIIRICCCOIHCRRIORHOIIC(var3.OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F))
      );
      var8.end();
      var5.pop();
   }

   private int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      if (var1 == null) {
         return 0;
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = var1.bridge$getData();
      return var2 == null ? 0 : var2.bridge$getInteger("tuned_transmission");
   }

   @Nullable
   private OHHRIOHROOIHOROCIRHCHORIHRRRRI RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      return switch (var1) {
         case VALID -> this.RRCRHHRHHIIHCIIOIOIIOIHHOIHOHI;
         case INVALID -> this.ORHIROICHCCHIIHIHRROIIROHCCOHI.get() ? this.IORCIICRROOROHORRRORRORRIOHCCI : null;
         case NONE -> null;
      };
   }

   private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RORCHCIIICOHIRROOORHOCCCCIOCCI var1, RORCHCIIICOHIRROOORHOCCCCIOCCI var2, RORCHCIIICOHIRROOORHOCCCCIOCCI var3
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var5 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      if (var4 != null && var5 != null) {
         OIHCOHRCICCCRHRCROOCIOIRRHHHIH var6 = this.mc.bridge$getObjectMouseOver();
         if (var6 != null) {
            if (var6.bridge$isTypeOfHit(RHOCHHIRRCHHHOHOIRROIROHHHIHIO.ENTITY)) {
               return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NONE;
            }

            if (var6.bridge$isTypeOfHit(RHOCHHIRRCHHHOHOIRROIROHHHIHIO.BLOCK)) {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = var4.CIOHHCORHRCCRICCCORIHCRHCCCRRR(
                  var6.bridge$getBlockPosition()
               );
               if (this.ORCIIOCRCHRCRHRCIRRRCOHIHHICIC.contains(var7)
                  || var7.bridge$isHandOpenableTrapDoor()
                  || var7.bridge$isFenceGate()
                  || var7.bridge$isCauldron()) {
                  return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.INVALID;
               }
            }
         }

         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8 = var4.OCOHORHCROHICRRIHCIHHRRCIHICRI(
            var1
         );
         if (var8.bridge$isFluid()) {
            return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NONE;
         } else {
            return !(var4.OCOHORHCROHICRRIHCIHHRRCIHICRI(var2).bridge$getCollisionShapeMaxY(var4, var2) > 0.0)
                  && !(var4.OCOHORHCROHICRRIHCIHHRRCIHICRI(var3).bridge$getCollisionShapeMaxY(var4, var3) > 0.0)
               ? com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.VALID
               : com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.INVALID;
         }
      } else {
         return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NONE;
      }
   }

   private boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      RORCHCIIICOHIRROOORHOCCCCIOCCI var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3
   ) {
      return var3.bridge$isSign() ? true : var3.bridge$getCollisionShapeMaxY(var1, var2) > 0.0 && !this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var3);
   }

   private boolean HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      return var1.bridge$isCandle()
         || var1.bridge$getBlock()
            == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII()
               .OCOOOIIHORIIIOIORRRRRHHRROHICC()
         || var1.bridge$getBlock()
            == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII()
               .ROCOICHOOCIOHOHICOHRICCHOROCRH()
         || var1.bridge$isFlowerPot()
         || IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 16
            && var1.bridge$getBlock()
               == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII()
                  .IOIHHCIHRHHCIOCROCHCHRHIOHOOIO();
   }

   @com.moonsworth.lunar.client.util.OIHCOHRCICCCRHRCROOCIOIRRHHHIH
   @Override
   public String getId() {
      return "ETHERWARP_PREVIEW";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.RRCRHHRHHIIHCIIOIOIIOIHHOIHOHI, this.ORHIROICHCCHIIHIHRROIIROHCCOHI);
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IORCIICRROOROHORRRORRORRIOHCCI).CIOHHCORHRCCRICCCORIHCRHCCCRRR(() -> !this.ORHIROICHCCHIIHIHRROIIROHCCOHI.get());
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HIHRORICRRIOOHRCIRIHHIHRIHIIOI);
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HOCOOHOOCRRIOCRRORIOROIIHIIHOH, this.ORORCHCIORRRHIHOOCCRROICRIIHCH);
   }

   @Override
   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ORIRHOHRHHROCHHRRIOOCRIHRIIIOC() {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIICCCRRHHCHRRHRIRCHOICCHROHCR()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCOCHOCIRORHHORHCROHOIOCRCHIO
         )
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO(this);
   }

   private enum IRCIIHHICIHRCOCRROCOICRIHHCCHH {
      NONE,
      VALID,
      INVALID;
   }

   private record RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      @Nullable
      private final RORCHCIIICOHIRROOORHOCCCCIOCCI IIROHIIHICIHHOHIROCOIORROCOCOR;
      private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH IRIIIORHCIHORICHHCIIRCRHRRIIHC;

      private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         @Nullable RORCHCIIICOHIRROOORHOCCCCIOCCI var1,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
      ) {
         this.IIROHIIHICIHHOHIROCOIORROCOCOR = var1;
         this.IRIIIORHCIHORICHHCIIRCRHRRIIHC = var2;
      }

      @Nullable
      public RORCHCIIICOHIRROOORHOCCCCIOCCI RRCHHOCOIORORHIIROIHHIRCIOOIIH() {
         return this.IIROHIIHICIHHOHIROCOIORROCOCOR;
      }

      public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ROCIIRCOORHCCCCHCOCIRRIRICICCH() {
         return this.IRIIIORHCIHORICHHCIIRCRHRRIIHC;
      }
   }
}
