package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RICRIRRCOHRCOCRRHHCRHRROOIOHHR;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.lib.adventure.text.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import org.joml.Matrix4f;
import org.joml.Vector2d;
import org.joml.Vector3d;
import org.joml.Vector3f;

public class CIOHHCORHRCCRICCCORIHCRHCCCRRR extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IOHRRORHRCOOCRIHHHHOHCROOHORII = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "testDynamicBlockRaycast"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RIROICHCRROROHCCROOCCCCOCHCCRI<com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH> ORCRRRICOIRRHOCHHOOHOHRROHRCIO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         "raycastMode", com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.BLOCK
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI RHCORRHROCIOCIHIORHOHRHHCCOOIR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "hitYourself"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RIROICHCRROROHCCROOCCCCOCHCCRI<CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> HRIIOICROHCRRCIHOCIHCIHOHRHCHH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         "blockRaycastType", CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BLOCK
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RICRIRRCOHRCOCRRHHCRHRROOIOHHR CRRHOHRIOIICIHOHRROHOCOIIOICCH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.RRHCOCRHRORRORRCRICOOCCCCHCOIR("distance")
      .RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(50.0)
      .IRRCCOICORICIHCHRHIHIHROIRHOCR(0.0, 1000.0)
      .OCCHHIHOOOHHORHHOHRCHRCCIOCOCI(1)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI ORCCCOIHIHOHHIROIIOORRROORHIRH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "renderRay"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IHCRIIOOHICOICOIHIHOHCORICICIH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "alwaysShowRay"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IIICOCHRRRCIIRORCCIHOHHROCIHCH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "renderBox"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI HICICOHCRHIHCCIRHRHOCIRIOOOHII = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "renderText"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI RHCHIOHOIHHCIROCRCIRIOCRRHROII = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showAll"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IHRHCHOCCHHICIIOIORIRCIHHHHHIH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "accurateMode"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI CHRHOHORRICRRHRCRCICOORCHHCIOH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "hitEntitiesWithoutBoundingBox"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH, RORCHCIIICOHIRROOORHOCCCCIOCCI, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH, com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> IIROIICHRICOHIOCHCICOORCCCOCRC;

   public CIOHHCORHRCCRICCCORIHCRHCCCRRR() {
      super(false);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class,
         this::HHCCIRHCCCIIRHCROHIORHIRHHIORH
      );
   }

   @Override
   public String getId() {
      return "RAYCAST_DEBUG";
   }

   private void HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var2 = var1.HHIIOHOORHHCCHRHHRCIORCROORCOI();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IHRHHIOIIICOROOORIOHCIROIRCOHH();
      if (var3 != null
         && (
            !com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.getMinecraftVersion().OOICHHIHHIHROCCRRRIIIIRIRICCIH()
               || !var3.bridge$getCamera().isEmpty()
         )) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4 = this.mc
            .bridge$getPlayer();
         if (this.IOHRRORHRCOOCRIHHHHOHCROOHORII.get()) {
            if (this.IIROIICHRICOHIOCHCICOORCCCOCRC == null) {
               com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var15 = com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OICIICOCOHRIOHIIHROIOICIIHRIOR
                  )
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var0, var1x) -> !var1x.bridge$isAir());
               if (this.RHCHIOHOIHHCIROCRCIRIOCRRHROII.get()) {
                  var15.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
                     (var3x, var4x) -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var3x, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4x))
                  );
               }

               var15 = var15.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, this.CRRHOHRIOIICIHOHRROHOCOIIOICCH.get());
               this.IIROIICHRICOHIOCHCICOORCCCOCRC = var15.OHCOIORHOCCRICIHIOIRHRIRROCHRR();
            }

            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var17 = this.IIROIICHRICOHIOCHCICOORCCCOCRC
               .CHRCRHHRCCOICCOOIIRIOHCOHCHHIC(IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH());
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, this.IIROIICHRICOHIOCHCICOORCCCOCRC, var17, var2);
         } else {
            com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = this.ORCRRRICOIRRHOCHHOOHOHRROHRCIO
               .get();
            boolean var6 = var5
                  == com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.COSMETIC
               && this.RHCORRHROCIOCIHIORHOHRHHCCOOIR.get();

            com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = switch (var5) {
               case BLOCK -> {
                  switch ((CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)this.HRIIOICROHCRRCIHOCIHCIHOHRHCHH.get()) {
                     case BLOCK:
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var23 = com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OICIICOCOHRIOHIIHROIOICIIHRIOR
                           )
                           .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var0, var1x) -> !var1x.bridge$isAir());
                        if (this.RHCHIOHOIHHCIROCRCIRIOCRRHROII.get()) {
                           var23.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
                              (var3x, var4x) -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var3x, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4x))
                           );
                        }

                        yield var23;
                     case BIOME:
                        com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var22 = var4.RRIOHRHHRHORRROIIRHRHROICRHCRO();
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9 = com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CCRCRHHIIHRCICOHHOHIRIOOOROICO
                           )
                           .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var1x, var2x) -> var2x != var22);
                        if (this.RHCHIOHOIHHCIROCRCIRIOCRRHROII.get()) {
                           var9.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
                              (var3x, var4x) -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var3x, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4x))
                           );
                        }

                        yield var9;
                     case BLOCK_LIGHT:
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var21 = com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HROCIHHHIRRHRIRROHCCOHROOOIIHR
                           )
                           .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var0, var1x) -> var1x >= 15);
                        if (this.RHCHIOHOIHHCIROCRCIRIOCRRHROII.get()) {
                           var21.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
                              (var3x, var4x) -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var3x, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4x))
                           );
                        }

                        yield var21;
                     case SKY_LIGHT:
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var20 = com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHCIRROHRRCIRCIRRROIOIOIOHRIO
                           )
                           .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var0, var1x) -> var1x >= 15);
                        if (this.RHCHIOHOIHHCIROCRCIRIOCRRHROII.get()) {
                           var20.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
                              (var3x, var4x) -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var3x, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4x))
                           );
                        }

                        yield var20;
                     default:
                        yield com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OICIICOCOHRIOHIIHROIOICIIHRIOR
                        );
                  }
               }
               case ENTITY -> {
                  com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var19 = com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOHHIRRRHIORHOCHCORHHIHROCROH
                     )
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        new com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                           this.CHRHOHORRICRRHRCRCICOORCHHCIOH.get()
                        )
                     )
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var0, var1x) -> IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH() != var1x);
                  if (this.RHCHIOHOIHHCIROCRCIRIOCRRHROII.get()) {
                     var19.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
                        (var3x, var4x) -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var3x, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4x))
                     );
                  }

                  yield var19;
               }
               case COSMETIC -> var6
                  ? com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CCOOCICCOOCCIOOROCIIOHHOHRCHCI
                     )
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        new com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                           this.IHRHCHOCCHHICIIOIORIRCIHHHHHIH.get()
                        )
                     )
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var0, var1x) -> true)
                  : com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOHHIRRRHIORHOCHCORHHIHROCROH
                     )
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        (var0, var1x) -> var1x instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH
                           && IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH() != var1x
                     );
               case SPRAY -> {
                  com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var18 = com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CROCCRCRICOHRRIRHIIORROOIRROCI
                     )
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var0, var1x) -> true);
                  if (this.RHCHIOHOIHHCIROCRCIRIOCRRHROII.get()) {
                     var18.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
                        (var3x, var4x) -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var3x, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4x))
                     );
                  }

                  yield var18;
               }
               case CHUNK -> {
                  com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8 = com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHCIRHRORRCRRRHROCCOROICRRIHI
                     )
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var1x, var2x) -> {
                        Vector2d var3x = new Vector2d(var4.bridge$getPosX(), var4.bridge$getPosZ());
                        return new Vector2d((var2x.bridge$getX() << 4) + 8, (var2x.bridge$getZ() << 4) + 8).distance(var3x) >= 96.0;
                     });
                  if (this.RHCHIOHOIHHCIROCRCIRIOCRRHROII.get()) {
                     var8.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
                        (var3x, var4x) -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var3x, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4x))
                     );
                  }

                  yield var8;
               }
               default -> com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OICIICOCOHRIOHIIHROIOICIIHRIOR
               );
            };
            if (var6) {
               IICCOOCHCHROORHHIIHROHCCRHRCOR.IHRHHIOIIICOROOORIOHCIROIRCOHH()
                  .bridge$getCamera()
                  .ifPresentOrElse(
                     var2x -> {
                        CRHROHHHCIHHCOHCOORCRIHHIICROR var3x = this.OCOHORHCROHICRRIHCIHHRRCIHICRI(var2x.bridge$getPitch(), var2x.bridge$getYaw());
                        CRHROHHHCIHHCOHCOORCRIHHIICROR var4x = CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
                           var2x.bridge$getPosX(), var2x.bridge$getPosY(), var2x.bridge$getPosZ()
                        );
                        byte var5x = 4;
                        var7.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                           CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
                              var4x.bridge$xCoord() + var3x.bridge$xCoord() * var5x,
                              var4x.bridge$yCoord() + var3x.bridge$yCoord() * var5x,
                              var4x.bridge$zCoord() + var3x.bridge$zCoord() * var5x
                           ),
                           var4x
                        );
                     },
                     () -> {
                        CRHROHHHCIHHCOHCOORCRIHHIICROR var3x = this.OCOHORHCROHICRRIHCIHHRRCIHICRI(
                           (float)var4.bridge$getRotationPitch(), (float)var4.bridge$getRotationYaw()
                        );
                        CRHROHHHCIHHCOHCOORCRIHHIICROR var4x = CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
                           var4.bridge$getPosX(), var4.bridge$getPosY(), var4.bridge$getPosZ()
                        );
                        byte var5x = 4;
                        var7.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                           CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
                              var4x.bridge$xCoord() + var3x.bridge$xCoord() * var5x,
                              var4x.bridge$yCoord() + var3x.bridge$yCoord() * var5x,
                              var4x.bridge$zCoord() + var3x.bridge$zCoord() * var5x
                           ),
                           var4x
                        );
                     }
                  );
            } else {
               var7.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, this.CRRHOHRIOIICIHOHRROHOCOIIOICCH.get(), var1.HOHIHCIHIHRCOOIOCOHIOHROHHIOHR());
            }

            com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var24 = var7.OHCOIORHOCCRICIHIOIRHRIRROCHRR();
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var25;
            if (var6) {
               var25 = var24.CHRCRHHRCCOICCOOIIRIOHCOHCHHIC(var4);
            } else if (var5
               == com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SPRAY) {
               ArrayList var10 = new ArrayList();

               for (List var12 : IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                  .RHOOIIHCIOORCHHHRCHORROICICIHO()
                  .HRIROROCRRHCORIHICIHCCHRIRHCHR()
                  .values()) {
                  for (com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRRRICCRROCOHHOHIICIHORCOORRRH var14 : var12) {
                     var10.add(var14);
                  }
               }

               var25 = var24.CHRCRHHRCCOICCOOIIRIOHCOHCHHIC(var10);
            } else {
               var25 = var24.CHRCRHHRCCOICCOOIIRIOHCOHCHHIC(IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH());
            }

            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var24, var25, var2);
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH<?, ?> var3,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var4
   ) {
      boolean var5 = var3.OCOCOIHOCHCIOORHOCIRIHRCHICORO()
         != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.MISS;
      Vector3d var6 = new Vector3d(
         var2.IHHHCCIORHCHIHHCOIHOHHCHRRHIHR().bridge$xCoord(),
         var2.IHHHCCIORHCHIHHCOIHOHHCHRRHIHR().bridge$yCoord(),
         var2.IHHHCCIORHCHIHHCOIHOHHCHRRHIHR().bridge$zCoord()
      );
      if (var5) {
         if (var3 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7
            )
          {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var1, var7, var6);
         } else if (var3 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8
            )
          {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var14 = var8.HCICROIHRHRCORRHCOIHIHCCCCHRHH();
            if (this.ORCRRRICOIRRHOCHHOOHOHRROHRCIO.get()
               == com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.COSMETIC) {
               if (var14 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var15
                  && com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CCOOCICCOOCCIOOROCIIOHHOHRCHCI
                     )
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.mc.bridge$getPlayer(), this.CRRHOHRIOIICIHOHRROHOCOIIOICCH.get(), 0.0F)
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var0, var1x) -> true)
                     .OHCOIORHOCCRICIHIOIRHRIRROCHRR()
                     .CHRCRHHRCCOICCOOIIRIOHCOHCHHIC(var15) instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var17
                  )
                {
                  this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var1, var17, var6);
               }
            } else {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var1, var8, var6);
            }
         } else if (var3 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9
            )
          {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var1, var9, var6);
         } else if (var3 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var10
            )
          {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var1, var10, var6);
         } else if (var3 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var11
            )
          {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var1, var11, var6);
         } else if (var3 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var12
            )
          {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var1, var12, var6);
         } else if (var3 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var13
            )
          {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var1, var13, var6);
         }
      }

      if (this.ORCCCOIHIHOHHIROIIOORRROORHIRH.get()
         && (var5 || this.IHCRIIOOHICOICOIHIHOHCORICICIH.get())
         && this.mc.bridge$getGameSettings().bridge$getThirdPersonView() != 0) {
         var4.push();
         var4.translate(-var1.bridge$renderPosX(), -var1.bridge$renderPosY(), -var1.bridge$renderPosZ());
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var18 = var4.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            1.0F
         );
         if (!var5) {
            var18.HHCCIRHCCCIIRHCROHIORHIRHHIORH(1.0F, 0.0F, 0.0F, 1.0F);
         }

         var18.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            var6.x,
            var6.y,
            var6.z,
            var2.IRCIOOHIOIHHOIHRHHCRHICOOCRIRH().bridge$xCoord(),
            var2.IRCIOOHIOIHHOIHRHHCRHICOOCRIRH().bridge$yCoord(),
            var2.IRCIOOHIOIHHOIHRHHCRHICOOCRIRH().bridge$zCoord()
         );
         var18.end();
         var4.pop();
      }
   }

   private Vector3d RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1) {
      CRHROHHHCIHHCOHCOORCRIHHIICROR var2 = var1.IHHHCCIORHCHIHHCOIHOHHCHRRHIHR();
      return new Vector3d(var2.bridge$xCoord(), var2.bridge$yCoord(), var2.bridge$zCoord());
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3,
      Vector3d var4
   ) {
      CRHROHHHCIHHCOHCOORCRIHHIICROR var5 = var3.IIHOCOIHHIROCHIHHCCCORRCOHCHRC();
      RORCHCIIICOHIRROOORHOCCCCIOCCI var6 = var3.HRICRCHIIHIIICIHCICRHOOCRCCHIO();
      if (this.HICICOHCRHIHCCIRHRHOCIRIOOOHII.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var2,
            var4,
            new Vector3d(var5.bridge$xCoord(), var5.bridge$yCoord(), var5.bridge$zCoord()),
            IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH().CIOHHCORHRCCRICCCORIHCRHCCCRRR(var6).bridge$getName()
         );
      }

      if (this.IIICOCHRRRCIIRORCCIHOHHROCIHCH.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var2,
            var6.bridge$getX(),
            var6.bridge$getY(),
            var6.bridge$getZ(),
            var6.bridge$getX() + 1,
            var6.bridge$getY() + 1,
            var6.bridge$getZ() + 1,
            -16711936
         );
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3,
      Vector3d var4
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IIHRRHORCRCROCHHOHORCHCROCIHRO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = (com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IIHRRHORCRCROCHHOHORCHCROCIHRO.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var3.RCRIICIORIOIRIIIOHCHOCHOIOCCHI();
      Vector3f var6 = var5.HRIRRHCHRHCIHIRROCIIRHHCIOCOOR();
      if (this.HICICOHCRHIHCCIRHRHOCIRIOOOHII.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var4, new Vector3d(var6), Component.text(var5.ORRRORHRCOHCHRRHRIRORRIRCRHCRH().getName()));
      }

      if (this.IIICOCHRRRCIIRORCCIHOHHROCIHCH.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var6.x - 0.005, var6.y - 0.005, var6.z - 0.005, var6.x + 0.005, var6.y + 0.005, var6.z + 0.005, -65536);
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3,
      Vector3d var4
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var5 = var3.HCICROIHRHRCORRHCOIHIHCCCCHRHH();
      CRHROHHHCIHHCOHCOORCRIHHIICROR var6 = var5.bridge$getEyePosition();
      if (this.HICICOHCRHIHCCIRHRHOCIRIOOOHII.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1, var2, var4, new Vector3d(var6.bridge$xCoord(), var6.bridge$yCoord(), var6.bridge$zCoord()), var5.bridge$getTypeName()
         );
      }

      if (this.IIICOCHRRRCIIRORCCIHOHHROCIHCH.get()) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = var5.bridge$getBoundingBox();
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var2,
            var7.bridge$getMinX(),
            var7.bridge$getMinY(),
            var7.bridge$getMinZ(),
            var7.bridge$getMaxX(),
            var7.bridge$getMaxY(),
            var7.bridge$getMaxZ(),
            -16711936
         );
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3,
      Vector3d var4
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = var3.IRIICICHHHCHCIOCCRRORHHHRRHHOH();
      if (this.HICICOHCRHIHCCIRHRHOCIRIOOOHII.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var2,
            var4,
            new Vector3d(var5.bridge$getX() << 4, IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH().bridge$getPosY(), var5.bridge$getZ() << 4),
            Component.text().content("(" + var5.bridge$getX() + ", " + var5.bridge$getZ() + ")").build()
         );
      }

      if (this.IIICOCHRRRCIIRORCCIHOHHROCIHCH.get()) {
         int var6 = var5.bridge$getX() << 4;
         int var7 = var5.bridge$getZ() << 4;
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var2,
            var6,
            IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH().bridge$getMinBuildHeight(),
            var7,
            var6 + 16,
            IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH().bridge$getMaxBuildHeight(),
            var7 + 16,
            -16711936
         );
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3,
      Vector3d var4
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = var3.IHRIHCICOCCIIIRRIIIROHHIROCOOO();
      RORCHCIIICOHIRROOORHOCCCCIOCCI var6 = var3.HRICRCHIIHIIICIHCICRHOOCRCCHIO();
      if (this.HICICOHCRHIHCCIRHRHOCIRIOOOHII.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var2,
            var4,
            new Vector3d(var6.bridge$getX(), var6.bridge$getY(), var6.bridge$getZ()),
            Component.text().content(var5.bridge$getBiomeName()).build()
         );
      }

      if (this.IIICOCHRRRCIIRORCCIHOHHROCIHCH.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var2,
            var6.bridge$getX(),
            var6.bridge$getY(),
            var6.bridge$getZ(),
            var6.bridge$getX() + 1,
            var6.bridge$getY() + 1,
            var6.bridge$getZ() + 1,
            -16711936
         );
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3,
      Vector3d var4
   ) {
      RORCHCIIICOHIRROOORHOCCCCIOCCI var5 = var3.HRICRCHIIHIIICIHCICRHOOCRCCHIO();
      if (this.HICICOHCRHIHCCIRHRHOCIRIOOOHII.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var2,
            var4,
            new Vector3d(var5.bridge$getX(), var5.bridge$getY(), var5.bridge$getZ()),
            Component.text().content(var3.CCRIIHCIOCOROCCOHHHCOIOCOOHIHC() + "").build()
         );
      }

      if (this.IIICOCHRRRCIIRORCCIHOHHROCIHCH.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var2,
            var5.bridge$getX(),
            var5.bridge$getY(),
            var5.bridge$getZ(),
            var5.bridge$getX() + 1,
            var5.bridge$getY() + 1,
            var5.bridge$getZ() + 1,
            -16711936
         );
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3,
      Vector3d var4
   ) {
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var3.IIRIOHIIORCORORHHROIRHHHORICCC();
      Vector3d var6 = var3.OHOHCCRCCCIIOOCOIHICIHCRRIIOCI();
      Matrix4f var7 = var3.IRHOROOOCOICCRIIOROORIIIRIIHOO();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8 = var3.OIIHICRIICHCHIROIOHRRCHICOCOCO();
      if (this.HICICOHCRHIHCCIRHRHOCIRIOOOHII.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var4, var6, Component.text().content(var5.getName()).build());
      }

      if (this.IIICOCHRRRCIIRORCCIHOHHROCIHCH.get()) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var6.x - 0.005, var6.y - 0.005, var6.z - 0.005, var6.x + 0.005, var6.y + 0.005, var6.z + 0.005, -65536);
         float var9 = 0.01F;
         Vector3f var10 = new Vector3f((float)var8.bridge$getMinX() - 0.01F, (float)var8.bridge$getMinY() - 0.01F, (float)var8.bridge$getMinZ() - 0.01F);
         Vector3f var11 = new Vector3f((float)var8.bridge$getMaxX() + 0.01F, (float)var8.bridge$getMaxY() + 0.01F, (float)var8.bridge$getMaxZ() + 0.01F);
         var7.transformPosition(var10);
         var7.transformPosition(var11);
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var10.x(), var10.y(), var10.z(), var11.x(), var11.y(), var11.z(), -16711936);
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      Vector3d var3,
      Vector3d var4,
      Component var5
   ) {
      var1.push();
      double var6 = var2.bridge$renderPosX();
      double var8 = var2.bridge$renderPosY();
      double var10 = var2.bridge$renderPosZ();
      double var12 = var4.x - var6;
      double var14 = var4.y - var8;
      double var16 = var4.z - var10;
      Vector3d var18 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var4, 0.9);
      Vector3d var19 = new Vector3d(var18.x - var6, var18.y - var8 + 1.0, var18.z - var10);
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1, var19
      );
      float var20 = 0.016666668F * (float)(1.0 + Math.sqrt(var12 * var12 + var14 * var14 + var16 * var16) * 0.15F);
      var1.scale(-var20, -var20, var20);
      var1.IIORCRHOICRHCHRROORHCRRRCRRCOI();
      IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR()
         .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            var1, var5, IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5, 0.0F), -10.0F, -1, true
         );
      var1.ICCHIORIROIOCROIHHRCICOCOIICHO();
      var1.pop();
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      double var3,
      double var5,
      double var7,
      double var9,
      double var11,
      double var13,
      int var15
   ) {
      var1.push();
      var1.translate(-var2.bridge$renderPosX(), -var2.bridge$renderPosY(), -var2.bridge$renderPosZ());
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var16 = var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         1.0F
      );
      var16.CORCOCICIRIOHROHROIIOOHICCHCRR(var15);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3, var5, var7, var9, var5, var7);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var9, var5, var7, var9, var5, var13);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var9, var5, var13, var3, var5, var13);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3, var5, var7, var3, var5, var13);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3, var11, var7, var9, var11, var7);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var9, var11, var7, var9, var11, var13);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var9, var11, var13, var3, var11, var13);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3, var11, var7, var3, var11, var13);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3, var5, var7, var3, var11, var7);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var9, var5, var7, var9, var11, var7);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3, var5, var13, var3, var11, var13);
      var16.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var9, var5, var13, var9, var11, var13);
      var16.end();
      var1.pop();
   }

   private Vector3d RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Vector3d var1, Vector3d var2, double var3) {
      Vector3d var5 = new Vector3d(var2).sub(var1);
      double var6 = var5.length();
      var5.normalize();
      double var8 = var6 * var3;
      return new Vector3d(var1.x + var8 * var5.x, var1.y + var8 * var5.y, var1.z + var8 * var5.z);
   }

   public CRHROHHHCIHHCOHCOORCRIHHIICROR OCOHORHCROHICRRIHCIHHRRCIHICRI(float var1, float var2) {
      float var3 = var1 * (float) (Math.PI / 180.0);
      float var4 = -var2 * (float) (Math.PI / 180.0);
      float var5 = (float)Math.cos(var4);
      float var6 = (float)Math.sin(var4);
      float var7 = (float)Math.cos(var3);
      float var8 = (float)Math.sin(var3);
      return CRHROHHHCIHHCOHCOORCRIHHIICROR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var6 * var7, -var8, var5 * var7);
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IOHRRORHRCOOCRIHHHHOHCROOHORII);
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.ORCRRRICOIRRHOCHHOOHOHRROHRCIO).CIOHHCORHRCCRICCCORIHCRHCCCRRR(() -> this.IOHRRORHRCOOCRIHHHHOHCROOHORII.get());
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HRIIOICROHCRRCIHOCIHCIHOHRHCHH)
         .CIOHHCORHRCCRICCCORIHCRHCCCRRR(
            () -> this.IOHRRORHRCOOCRIHHHHOHCROOHORII.get()
               || this.ORCRRRICOIRRHOCHHOOHOHRROHRCIO.get()
                  != com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.BLOCK
         );
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CRRHOHRIOIICIHOHRROHOCOIIOICCH)
         .CIOHHCORHRCCRICCCORIHCRHCCCRRR(
            () -> this.ORCRRRICOIRRHOCHHOOHOHRROHRCIO.get()
                  == com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.COSMETIC
               && this.RHCORRHROCIOCIHIORHOHRHHCCOOIR.get()
         );
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.ORCCCOIHIHOHHIROIIOORRROORHIRH, var1x -> var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IHCRIIOOHICOICOIHIHOHCORICICIH)
      );
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IIICOCHRRRCIIRORCCIHOHHROCIHCH, this.HICICOHCRHIHCCIRHRHOCIRIOOOHII);
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.RHCHIOHOIHHCIROCRCIRIOCRRHROII)
         .CIOHHCORHRCCRICCCORIHCRHCCCRRR(
            () -> this.ORCRRRICOIRRHOCHHOOHOHRROHRCIO.get()
               == com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.COSMETIC
         );
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.RHCORRHROCIOCIHIORHOHRHHCCOOIR, this.IHRHCHOCCHHICIIOIORIRCIHHHHHIH)
         .CIOHHCORHRCCRICCCORIHCRHCCCRRR(
            () -> this.ORCRRRICOIRRHOCHHOOHOHRROHRCIO.get()
               != com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.COSMETIC
         );
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CHRHOHORRICRRHRCRCICOORCHHCIOH)
         .CIOHHCORHRCCRICCCORIHCRHCCCRRR(
            () -> this.ORCRRRICOIRRHOCHHOOHOHRROHRCIO.get()
               != com.moonsworth.lunar.client.util.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ENTITY
         );
      this.IOHRRORHRCOOCRIHHHHOHCROOHORII.IIOCHOIICCIORCOROIROHICCHIOHIC(var1x -> this.IIROIICHRICOHIOCHCICOORCCCOCRC = null);
      this.RHCHIOHOIHHCIROCRCIRIOCRRHROII.IIOCHOIICCIORCOROIROHICCHIOHIC(var1x -> this.IIROIICHRICOHIOCHCICOORCCCOCRC = null);
      this.CRRHOHRIOIICIHOHRROHOCOIIOICCH.IIOCHOIICCIORCOROIROHICCHIOHIC(var1x -> this.IIROIICHRICOHIOCHCICOORCCCOCRC = null);
   }

   @Override
   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ORIRHOHRHHROCHHRRIOOCRIHRIIIOC() {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIICCCRRHHCHRRHRIRCHOICCHROHCR()
         .CRRRICCRROCOHHOHIICIHORCOORRRH(() -> "Raycast Debug Mod")
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RROHICHROOOOORICCIRCHOOIRCRHIO,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CCCIRORHIRRORROOOOCCHCRIORHOIC
         )
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO(this);
   }

   private enum RCIRROCCCIIHCIHCCRHHCCHOHHHCHH implements ORHIOICIOCRRHOOCOHRORIHICHRCRR {
      BLOCK,
      BLOCK_LIGHT,
      SKY_LIGHT,
      BIOME;

      @Override
      public String id() {
         return this.name().toLowerCase(Locale.ROOT);
      }
   }
}
