package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHIIIRHOOCHRCCCCIORIROCOIRRHCC;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IIHRRHORCRCROCHHOHORCHCROCIHRO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HCHRIROHHHCORIOCROOCHRCIOROOCI;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.RHHIOCHRCICCHOHCIHOOHOIHCCHRCO;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.ThreadLocalRandom;
import javax.annotation.Nullable;
import lombok.Generated;

public class CRRRICCRROCOHHOHIICIHORCOORRRH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final EnumMap<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH, HHCCIRHCCCIIRHCROHIORHIRHHIORH> OCRRIRIRRICHHRIIICHRHOROIIORIH = new EnumMap<>(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class
   );
   private final IRCIIHHICIHRCOCRROCOICRIHHCCHH IOCHOHHHHIRIIHOIHIIOHHRCCORROI = IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this);
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HHRRICRIORRHIOIRIOIORRROROIHHI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "alwaysEnchantStrikes"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HHHCIRHHOICIHORHCRROOOHHIICHIC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "hideFirstPersonParticles"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI COIROROORCRRCIOCCOIIHHCCIRRHRC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "hideBlockBreakParticles"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI CHICHIOHCORHHHIHCCOHCOHOIICCRC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "hideAllParticles"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();

   public CRRRICCRROCOHHOHIICIHORCOORRRH() {
      super(false);
      this.handle(OIHCOHRCICCCRHRCROOCIOIRRHHHIH.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(HICRRICCHCCROOHHCHOCOCCHOIHHOC.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RCORHRRHIHHCRHHHOIIIHIOORIRHCI,
         IIRHCHHOICHRICOOCRORCCIOOIHOIR.CICIOCCCRRRHCCIIRIRORHIROOCHRR().HRRHRCCOOIOIIIRORIOOORORHOORIH(false)
      );
   }

   @Override
   public String getId() {
      return "PARTICLE_CHANGER";
   }

   @Override
   protected List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH> CICCRRIHRRIOIRCCIOOOCROCORIRHI() {
      ArrayList var1 = new ArrayList();
      var1.add(this.IOCHOHHHHIRIIHOIHIIOHHRCCORROI);
      this.OCRRIRIRRICHHRIIICHRHOROIIORIH
         .put(
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.BLOOD,
            this.IOCHOHHHHIRIIHOIHIIOHHRCCORROI
         );

      for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var5 : com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.values()) {
         if ((IICCOOCHCHROORHHIIHROHCCRHRCOR.RHRRIHCHRHCCROOHIHROIHHOROCHRH || var5.isAvailable())
            && var5
               != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.BLOOD
            )
          {
            HHCCIRHCCCIIRHCROHIORHIRHHIORH var6 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, var5);
            var1.add(var6);
            this.OCRRIRIRRICHHRIIICHRHOROIIORIH.put(var5, var6);
         }
      }

      return var1;
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
         "generalOptions",
         var1x -> var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(
            this.HHRRICRIORRHIOIRIOIORRROROIHHI, this.HHHCIRHHOICIHORHCRROOOHHIICHIC, this.COIROROORCRRCIOCCOIIHHCCIRRHRC, this.CHICHIOHCORHHHIHCCOHCOHOIICCRC
         )
      );
      var1.HOCRHCOCIHIOHHCRIOOIHRCCCRIRHR();
      var1.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
         "particleOptions",
         var1x -> {
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(
               IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH("scale")
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     (var1xx, var2x) -> new HCHRIROHHHCORIOCROOCHRCIOROOCI<>(var1xx, var2x, this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1xx))
                  )
                  .RROIIRROOOOHIORHRICHOCHIHCRRCH(1.0F)
                  .CRHROHHHCIHHCOHCOORCRIHHIICROR(0.25F, 2.0F),
               IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH("particleMultiplier")
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     (var1xx, var2x) -> new HCHRIROHHHCORIOCROOCHRCIOROOCI<>(var1xx, var2x, this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1xx))
                  )
                  .RROIIRROOOOHIORHRICHOCHIHCRRCH(1.0F)
                  .CRHROHHHCIHHCOHCOORCRIHHIICROR(0.25F, 10.0F),
               IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("hideParticle")
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     (var1xx, var2x) -> new RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(var1xx, var2x, this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1xx))
                  )
            );
            HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2 = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("overlayColor")
               .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
            OHHRIOHROOIHOROCIRHCHORIHRRRRI var3 = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("color")
               .RCIICICHIIRIIRHHROCOOOHRROOIIC(-1)
               .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
            RIROICHCRROROHCCROOCCCCOCHCCRI var4 = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  "colorMode", RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OVERLAY
               )
               .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var2,
               var4x -> var4x.CRRRICCRROCOHHOHIICIHORCOORRRH(
                  var3,
                  var4,
                  IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH("applyToAll")
                     .RCIROOOOICRHCCRRCIORHHIRCOIIIC(() -> this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var3, var4))
               )
            );
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HOIIRIHOHCRIHOOHRCRCRCRRHIHRCO(true), this.HOIIRIHOHCRIHOOHRCRCRCRRHIHRCO(false));
         }
      );
   }

   private RHHIOCHRCICCHOHCIHOOHOIHCCHRCO IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI<?>... var1
   ) {
      return (var2, var3) -> {
         RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC.IICCRHIHRIHOHICHCRIROICOICROOR
         );
         if (var4 == null) {
            return true;
         }

         var4.getChildren()
            .stream()
            .map(
               var0 -> var0.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRHCCHCRHIHOCRICOHOIICHCHOHICC
               )
            )
            .filter(Objects::nonNull)
            .forEach(var1xx -> var1xx.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1xxx -> {
               for (com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI var5 : var1) {
                  if (Objects.equals(var5.getId(), var1xxx.getId())) {
                     try {
                        var1xxx.ORHIOICIOCRRHOOCOHRORIHICHRCRR(var5);
                     } catch (IllegalArgumentException var7) {
                        com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.warn("ParticleMod applyToAll", var7);
                     }
                  }
               }

               return false;
            }));
         return true;
      };
   }

   private IIHRRHORCRCROCHHOHORCHCROCIHRO HOIIRIHOHCRIHOOHRCRCRCRRHIHRCO(boolean var1) {
      return IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH(var1 ? "enableAll" : "disableAll")
         .RCIROOOOICRHCCRRCIORHHIRCOIIIC(
            () -> {
               for (HHCCIRHCCCIIRHCROHIORHIRHHIORH var3 : this.OCRRIRIRRICHHRIIICHRHOROIIORIH.values()) {
                  var3.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRIIIRORRHRROOOIRHROOOIIHIHIRH
                     )
                     .setEnabled(var1);
               }
            }
         )
         .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC var1) {
      if (this.HHRRICRIORRHIOIRIOIORRROROIHHI.get()
         && var1.HCHOOIOHICCRIOIICHCHOIIRRRIHCI() instanceof CORCOCICIRIOHROHROIIOOHICCHCRR
         && !(
            var1 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
         )
         && !var1.HCHOOIOHICCRIOIICHCHOIIRRRIHCI().bridge$isInvisible()
         && var1.HCHOOIOHICCRIOIICHCHOIIRRRIHCI().bridge$isAlive()) {
         HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ENCHANTED_HIT
         );
         if (var2 != null) {
            float var3 = var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(ThreadLocalRandom.current());

            for (int var4 = 0; var4 < var3; var4++) {
               this.mc
                  .bridge$getEffectRenderer()
                  .bridge$emitParticleAtEntity(
                     var1.HCHOOIOHICCRIOIICHCHOIIRRRIHCI(),
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ENCHANTED_HIT
                  );
            }
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(OIHCOHRCICCCRHRCROOCIOIRRHHHIH var1) {
      if (this.CHICHIOHCORHHHIHCCOHCOHOIICCRC.get()) {
         var1.setCancelled(true);
      } else {
         HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.OCHRROICICIRRCOCRRRICIIRCHIORR().bridge$getParticleType());
         if (var2 != null && var2.COOOIHCOIIOIOIIOHHCIORROIICHII()) {
            var1.setCancelled(true);
         }
      }
   }

   @Nullable
   public HHCCIRHCCCIIRHCROHIORHIRHHIORH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      return var1 == null ? null : this.OCRRIRIRRICHHRIIICHRHOROIIORIH.get(var1);
   }

   public boolean IROCIRHCHORHRIIOCRIROIHCHRHCHC() {
      return this.isEnabled() && this.HHHCIRHHOICIHORHCRROOOHHIICHIC.get();
   }

   public boolean IIRHHCORRCIIOIOCICRRIORCCIOHCR() {
      return this.isEnabled() && this.COIROROORCRRCIOCCOIIHHCCIRRHRC.get();
   }

   @Generated
   public IRCIIHHICIHRCOCRROCOICRIHHCCHH HCHORIRRHRIIOHORRCOIIIHRCIHICO() {
      return this.IOCHOHHHHIRIIHOIHIIOHHRCCORROI;
   }
}
