package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHIIIRHOOCHRCCCCIORIROCOIRRHCC;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RIICORHIROOOHRRIHOCRORIORHIRHC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "playerBloodParticles"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI ORIIOIIHROCOCIOOOIOOIRHHOHOIHC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "entityBloodParticles"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI CORCCRHIHHCRRIRCOOHCOIRCIOOHRI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "selfBloodParticles"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RRCCCCOHOOOCIIICHROHHHRHHIIHHI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("playBloodSound")
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH RCIHRCORRCICRICORIOHRIICCOOCOC = null;
   private CRHROHHHCIHHCOHCOORCRIHHIICROR CHIHHHIOORIHOIRRORRCRHOHCHICRI = null;

   private IRCIIHHICIHRCOCRROCOICRIHHCCHH(CRRRICCRROCOHHOHIICIHORCOORRRH var1) {
      super(
         var1,
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.BLOOD
      );
      this.handle(HICRRICCHCCROOHHCHOCOCCHOIHHOC.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::ORCOOCHRICHOIHHIHIOHCHCRIOHRCR);
   }

   @Override
   protected RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ORIRHOHRHHROCHHRRIOOCRIHRIIIOC() {
      return RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIICCCRRHHCHRRHRIRCHOICCHROHCR()
         .CRRRICCRROCOHHOHIICIHORCOORRRH(() -> this.HCCHOCRCORHOIOICRIICIHHHRORHIH().IRCIIHHICIHRCOCRROCOICRIHHCCHH("bloodDisplayName"))
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO(this);
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
         this.RIICORHIROOOHRRIHOCRORIORHIRHC, this.ORIIOIIHROCOCIOOOIOOIRHHOHOIHC, this.CORCCRHIHHCRRIRCOOHCOIRCIOOHRI, this.RRCCCCOHOOOCIIICHROHHHRHHIIHHI
      );
      super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC var1) {
      this.RCIHRCORRCICRICORIOHRIICCOOCOC = var1.HCHOOIOHICCRIOIICHCHOIIRRRIHCI();
      this.CHIHHHIOORIHOIRRORRCRHOHCHICRI = var1.ICHRHRHIORHOOHHRIRORHIIIOORRIO();
   }

   private void ORCOOCHRICHOIHHIHIOHCHCRIOHRCR() {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() != null && !this.COOOIHCOIIOIOIIOHHCIORROIICHII()) {
         for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var2 : IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH()
            .bridge$entitiesForRendering()) {
            if ((
                  var2 != IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH()
                     || this.CORCCRHIHHCRRIRCOOHCOIRCIOOHRI.get() && !this.HCCHOCRCORHOIOICRIICIHHHRORHIH().IROCIRHCHORHRIIOCRIROIHCHRHCHC()
               )
               && !var2.bridge$isInvisible()
               && var2.bridge$isAlive()
               && this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(var2)
               && (
                  !(
                        var2 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH
                     )
                     || this.RIICORHIROOOHRRIHOCRORIORHIRHC.get()
               )
               && (!(var2 instanceof CORCOCICIRIOHROHROIIOOHICCHCRR) || this.ORIIOIIHROCOCIOOOIOOIRHHOHOIHC.get())) {
               double var3;
               double var5;
               double var7;
               if (this.RCIHRCORRCICRICORIOHRIICCOOCOC == var2) {
                  var3 = this.CHIHHHIOORIHOIRRORRCRHOHCHICRI.bridge$xCoord();
                  var5 = this.CHIHHHIOORIHOIRRORRCRHOHCHICRI.bridge$yCoord();
                  var7 = this.CHIHHHIOORIHOIRRORRCRHOHCHICRI.bridge$zCoord();
               } else {
                  var3 = var2.bridge$getPosX();
                  var5 = var2.bridge$getPosY() + var2.bridge$getHeight() / 2.0;
                  var7 = var2.bridge$getPosZ();
               }

               IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
                  .bridge$getEffectRenderer()
                  .bridge$spawnBloodParticles(var2.bridge$getWorld(), var3, var5, var7);
            }
         }
      }

      this.RCIHRCORRCICRICORIOHRIICCOOCOC = null;
      this.CHIHHHIOORIHOIRRORRCRHOHCHICRI = null;
   }

   private boolean ICICIOCHHHIHOCHCOHORIHRCOHHOCR(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      return var1 instanceof CORCOCICIRIOHROHROIIOOHICCHCRR var2 ? var2.bridge$wasJustHurt() : false;
   }

   public boolean RRIHCIIOCOHOICHOOHCIIHOIOCOHCH() {
      return this.isEnabled() && this.RRCCCCOHOOOCIIICHROHHHRHHIIHHI.get();
   }

   public static IRCIIHHICIHRCOCRROCOICRIHHCCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CRRRICCRROCOHHOHIICIHORCOORRRH var0) {
      String var1 = "PARTICLE_CHANGER_BLOOD_CHILD";
      return new IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0) {
         @Override
         public String getId() {
            return "PARTICLE_CHANGER_BLOOD_CHILD";
         }
      };
   }
}
