package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.lib.adventure.text.Component;
import com.moonsworth.lunar.lib.adventure.text.TextComponent;
import com.moonsworth.lunar.lib.adventure.text.format.NamedTextColor;
import java.util.ArrayList;
import java.util.List;

@com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 33)
public class HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ICOIRHOHHCCIOCOCRCIIRCOORORRCR;
   protected final IRCIIHHICIHRCOCRROCOICRIHHCCHH IHIIOIRCCCICIHRCIIRHIIHOICRIIH;

   public HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR = var2;
      this.IHIIOIRCCCICIHRCIIRHIIHOICRIIH = var1;
   }

   public void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3,
      float var4,
      float var5,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH<?> var6
   ) {
      Component var7;
      Component var8;
      Component var9;
      if (var3.IRICRORHCROOCHHCHRRRIIROHHRIIC()) {
         var7 = this.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(279, false);
         var8 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(4, true, false);
         var9 = this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(true, var2.RIIOOCHCRIIIHHROOCRICOICRCICIR());
      } else {
         var7 = this.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.RIHHHORRIICOOIRCROCHIRIIIOOIIO(), false);
         var8 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.RCORHHORCOIIHIROIHHHHIRIOIIRCR(), this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.OOOIRHOOHIROHICRCRCCIROHHHICIR(), false
         );
         var9 = this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.HIOCIHIOIHRRROHOORCHCOIOIOIRIO(), var2.RIIOOCHCRIIIHHROOCRICOICRCICIR());
      }

      boolean var10 = var3.OIHRHHIIROCRCOOICHCIIRHOIIHHRI() >= 6;
      this.IHIIOIRCCCICIHRCIIRHIIHOICRIIH
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var7,
            var4 + (var10 ? 20 : 25),
            var5 + 6.5F,
            1.0F,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SHADOW
         );
      this.IHIIOIRCCCICIHRCIIRHIIHOICRIIH
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var8,
            var4 + (var10 ? 43 : 75),
            var5 + 6.5F,
            1.0F,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SHADOW
         );
      if (var10) {
         this.IHIIOIRCCCICIHRCIIRHIIHOICRIIH
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1,
               var9,
               var4 + 75.0F,
               var5 + 6.5F,
               1.0F,
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SHADOW
            );
      }

      if (var6.RHIIOORHHCCOCIORHIRCICHCHRRIII() >= var5
         && var6.RHIIOORHHCCOCIORHIRCICHCHRRIII() <= var5 + 15.0F
         && var6.COCCOIROHORRRHIHICORRHRRORIIIH() >= var4
         && var6.COCCOIROHORRRHIHICORRHRRORIIIH() <= var4 + 100.0F) {
         this.IHIIOIRCCCICIHRCIIRHIIHOICRIIH.HOHCCHOIOHOHHOROHOIIHOOHORRHRO(this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var3));
      }
   }

   public void HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3,
      float var4,
      float var5,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH<?> var6
   ) {
      TextComponent var9 = Component.text("    ");
      Component var7;
      Component var8;
      if (var3.IRICRORHCROOCHHCHRRRIIROHHRIIC()) {
         Component var10 = this.RICRIRRCOHRCOCRRHHCRHRROOIOHHR(20, 9, 29);
         Component var11 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(4, true, true);
         Component var12 = this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(true, true);
         Component var13 = this.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(26, false);
         Component var14 = this.RRRIRIOCCHRHRIRHIRIIHCOHRHHIIC(0);
         Component var15 = this.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(279, true);
         var7 = var10.append(var9).append(var11).append(var9).append(var12);
         var8 = var13.append(var9).append(var14).append(var9).append(var15);
      } else {
         int var17 = this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.HHIRCOHHHICIOOICICICIIHOORROCI() * 2;
         if (this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.CCHHRCCCOOOIICRRRHCOIRRHOHCCOR()) {
            var17--;
         }

         Component var18 = this.RICRIRRCOHRCOCRRHHCRHRROOIOHHR(
            this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.OOROIRCIIOIRICORICOCOCIRRHIHHH(),
            this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.IOOICCOHIOROOCIRHOIHHROCHIRHRO() - this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.OOROIRCIIOIRICORICOCOCIRRHIHHH(),
            this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.IOOICCOHIOROOCIRHOIHHROCHIRHRO()
         );
         Component var19 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.RCORHHORCOIIHIROIHHHHIRIOIIRCR(), this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.OOOIRHOOHIROHICRCRCCIROHHHICIR(), true
         );
         Component var20 = var3.OIHRHHIIROCRCOOICHCIIRHOIIHHRI() >= 6
            ? this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.HIOCIHIOIHRRROHOORCHCOIOIOIRIO(), true)
            : Component.empty();
         Component var21 = this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.OOROIRCIIOIRICORICOCOCIRRHIHHH() == 0
            ? this.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(-1, false)
            : this.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
               this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.RIRRCOHHCCRCCRHORIHCCRIRRRRCRR(),
               this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.RIHHHORRIICOOIRCROCHIRIIIOOIIO() >= 300
            );
         Component var22 = this.RRRIRIOCCHRHRIRHIRIIHCOHRHHIIC(var17);
         Component var16 = this.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.RIHHHORRIICOOIRCROCHIRIIIOOIIO(), true);
         var7 = var18.append(var9).append(var19).append(var9).append(var20);
         var8 = var21.append(var9).append(var22).append(var9).append(var16);
      }

      this.IHIIOIRCCCICIHRCIIRHIIHOICRIIH
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var7,
            var4 + 50.0F,
            var5 + 5.0F,
            0.4F,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SHADOW
         );
      this.IHIIOIRCCCICIHRCIIRHIIHOICRIIH
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            var8,
            var4 + 50.0F,
            var5 + 10.0F,
            0.4F,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SHADOW
         );
      if (var6.RHIIOORHHCCOCIORHIRCICHCHRRIII() >= var5
         && var6.RHIIOORHHCCOCIORHIRCICHCHRRIII() <= var5 + 15.0F
         && var6.COCCOIROHORRRHIHICORRHRRORIIIH() >= var4
         && var6.COCCOIROHORRRHIHICORRHRRORIIIH() <= var4 + 100.0F) {
         this.IHIIOIRCCCICIHRCIIRHIIHOICRIIH.HOHCCHOIOHOHHOROHOIIHOOHORRHRO(this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var3));
      }
   }

   private Component RICRIRRCOHRCOCRRHHCRHRROOIOHHR(int var1, int var2, int var3) {
      return var1 == 0
         ? ((TextComponent)Component.text("Secrets: ").color(NamedTextColor.GRAY)).append(Component.text("?").color(NamedTextColor.AQUA))
         : ((TextComponent)((TextComponent)((TextComponent)((TextComponent)((TextComponent)Component.text("Secrets: ").color(NamedTextColor.GRAY))
                        .append(Component.text(var1).color(NamedTextColor.AQUA)))
                     .append(Component.text("-").color(NamedTextColor.DARK_GRAY)))
                  .append(Component.text(var2).color(NamedTextColor.YELLOW)))
               .append(Component.text("-").color(NamedTextColor.GRAY)))
            .append(Component.text(var3).color(NamedTextColor.RED));
   }

   private Component RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(int var1, boolean var2, boolean var3) {
      NamedTextColor var4;
      if (var1 >= 5) {
         var4 = NamedTextColor.GREEN;
      } else if (var1 >= 1) {
         var4 = NamedTextColor.YELLOW;
      } else {
         var4 = NamedTextColor.RED;
      }

      Component var5 = var3
         ? ((TextComponent)Component.text("Crypts: ").color(NamedTextColor.GRAY)).append(Component.text(var1).color(var4))
         : ((TextComponent)Component.text(var1).color(var4)).append(Component.text("c"));
      return var2 ? var5.append(Component.text('♕').color(NamedTextColor.GOLD)) : var5;
   }

   private Component CRICCOOHHHCHOORCICOCOHIHOIRHOO(boolean var1, boolean var2) {
      Component var3 = Component.text("Mimic: ").color(NamedTextColor.GRAY);
      Component var4 = var1 ? Component.text('✔').color(NamedTextColor.GREEN) : Component.text('✖').color(NamedTextColor.RED);
      return var2 ? var3.append(var4) : var4;
   }

   private Component HRCHROOHRIHCRCRHRIIROCIRHOIRHH(int var1, boolean var2) {
      Component var3 = Component.text("Min Secrets: ").color(NamedTextColor.GRAY);
      if (var1 == -1) {
         return var3.append(Component.text("?").color(NamedTextColor.AQUA));
      }

      NamedTextColor var4 = var2 ? NamedTextColor.GREEN : NamedTextColor.YELLOW;
      return var3.append(Component.text(var1).color(var4));
   }

   private Component RRRIRIOCCHRHRIRHIRIIHCOHRHHIIC(int var1) {
      Component var2 = Component.text("Deaths: ").color(NamedTextColor.GRAY);
      return var1 > 0
         ? var2.append(Component.text("-").color(NamedTextColor.RED)).append(Component.text(var1).color(NamedTextColor.RED))
         : var2.append(Component.text(var1).color(NamedTextColor.GREEN));
   }

   private Component OOROOCCIRCCRHOIOIORIHCHHOOCCOR(int var1, boolean var2) {
      NamedTextColor var3;
      if (var1 >= 300) {
         var3 = NamedTextColor.GREEN;
      } else if (var1 >= 270) {
         var3 = NamedTextColor.YELLOW;
      } else {
         var3 = NamedTextColor.RED;
      }

      Component var4 = Component.text(var1).color(var3);
      return var2 ? ((TextComponent)Component.text("Score: ").color(NamedTextColor.GRAY)).append(var4) : var4;
   }

   private List<Component> HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      if (var1.IRICRORHCROOCHHCHRRRIIROHHRIIC()) {
         return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, 279, 100, 84, 84, 7, 20, 9, 29, 4, true, true, 26, 0);
      }

      int var2 = this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.HHIRCOHHHICIOOICICICIIHOORROCI() * 2;
      if (this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.CCHHRCCCOOOIICRRRHCOIRRHOHCCOR()) {
         var2--;
      }

      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1,
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.RIHHHORRIICOOIRCROCHIRIIIOOIIO(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.HIRHIIHOIOICOCCIIHOCCIORCROHRH(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.IRHORRIOICHCRRORIROICHICCOCOIC(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.ORHROCHHOORCCOCHHRCHIRIHROHHRI(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.CIOIIHHCCOOCHRRHCRICOOCRCHIOII(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.OOROIRCIIOIRICORICOCOCIRRHIHHH(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.IOOICCOHIOROOCIRHOIHHROCHIRHRO() - this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.OOROIRCIIOIRICORICOCOCIRRHIHHH(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.IOOICCOHIOROOCIRHOIHHROCHIRHRO(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.RCORHHORCOIIHIROIHHHHIRIOIIRCR(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.HIOCIHIOIHRRROHOORCHCOIOIOIRIO(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.OOOIRHOOHIROHICRCRCCIROHHHICIR(),
         this.ICOIRHOHHCCIOCOCRCIIRCOORORRCR.RIRRCOHHCCRCCRHORIHCCRIRRRRCRR(),
         var2
      );
   }

   private List<Component> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      int var2,
      int var3,
      int var4,
      int var5,
      int var6,
      int var7,
      int var8,
      int var9,
      int var10,
      boolean var11,
      boolean var12,
      int var13,
      int var14
   ) {
      Component var15 = Component.text("?").color(NamedTextColor.AQUA);
      ArrayList var16 = new ArrayList();
      var16.add(Component.text("Total Score: ").append(Component.text(var2).color(NamedTextColor.AQUA)));
      var16.add(Component.text("Skill Score: ").append(Component.text(var3).color(NamedTextColor.GREEN)));
      var16.add(Component.text("Exploration Score: ").append(Component.text(var4).color(NamedTextColor.GREEN)));
      var16.add(Component.text("Time Score: ").append(Component.text(var5).color(NamedTextColor.GREEN)));
      var16.add(Component.text("Bonus Score: ").append(Component.text(var6).color(NamedTextColor.GREEN)));
      var16.add(Component.empty());
      var16.add(Component.text("Secrets Found: ").append(Component.text(var7).color(NamedTextColor.AQUA)));
      TextComponent var17 = Component.text("Secrets Left: ");
      TextComponent var18 = Component.text("Total Secrets: ");
      if (var7 == 0) {
         var16.add(var17.append(var15));
         var16.add(var18.append(var15));
      } else {
         var16.add(var17.append(Component.text(var8).color(NamedTextColor.YELLOW)));
         var16.add(var18.append(Component.text(var9).color(NamedTextColor.RED)));
      }

      var16.add(Component.empty());
      var16.add(Component.text("Crypts: ").append(Component.text(var10).color(NamedTextColor.GREEN)));
      if (var1.OIHRHHIIROCRCOOICHCIIRHOIIHHRI() >= 6) {
         Component var19 = var11 ? Component.text('✔').color(NamedTextColor.GREEN) : Component.text('✖').color(NamedTextColor.RED);
         var16.add(Component.text("Mimic: ").append(var19));
      }

      if (var12) {
         String var20 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .CCHHHHCICRCCCIOOIOICOOCRCRHCCR()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("features.SKYBLOCK.info", "dungeonPrince");
         var16.add(Component.text(var20 + ": ").append(Component.text('✔').color(NamedTextColor.GREEN)));
      }

      var16.add(Component.empty());
      TextComponent var21 = Component.text("Min Secrets (S+): ");
      if (var7 == 0) {
         var16.add(var21.append(var15));
      } else {
         var16.add(var21.append(Component.text(var13).color(NamedTextColor.GREEN)));
      }

      var16.add(Component.text("Death Penalty: ").append(Component.text(var14).color(NamedTextColor.RED)));
      return var16;
   }
}
