package com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.eliotlash.molang.ast.Evaluator;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import lombok.Generated;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH
   implements com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH, HRCHROOHRIHCRCRHRIIROCIRHOIRHH> {
   protected final List<RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> COIORCORCHIRIRHCHICHOCROCHRCHR = new ArrayList<>();
   private CORCOCICIRIOHROHROIIOOHICCHCRR HIIIHHRRRRCCCRHCHRIORIRIRCCIIH;
   protected Evaluator HROCICIOCORIOOCCIIICORCRRHHICI;

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(CORCOCICIRIOHROHROIIOOHICCHCRR var1) {
      this.HIIIHHRRRRCCCRHCHRIORIRIRCCIIH = var1;
   }

   public int IRCIIHHICIHRCOCRROCOICRIHHCCHH(HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1) {
      this.COIORCORCHIRIRHCHICHOCROCHRCHR.clear();
      if (!this.shouldRender(var1)) {
         return 0;
      }

      com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HOIOHRCOCOOHHCHHHHROHHCOCOOOHI();
      List var3 = var1.bridge$getWornCosmetics();
      boolean var4 = false;
      boolean var5 = false;
      if (var3 != null) {
         for (RRCRRCORICCHOHHIRCHIROOHIIOHCO var7 : var3) {
            if (this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var7.OOICHRIOOOOIOHOIHOIRIRROCHRIOO())
               && var7.OOICHRIOOOOIOHOIHOIRIRROCHRIOO() instanceof RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var8) {
               if (var8.RCIIIRRHHHHRHRIRHHROIRICHIHROC().isHeldItemCosmetic() && var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var8)) {
                  com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var11 = var8.RIRCHOIHHICCICOHHRROCIROROCHRO()
                     .get();
                  if (var8.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.bridge$getMainHandItemRenderState(), var1) && !var4) {
                     this.COIORCORCHIRIRHCHICHOCROCHRCHR.add(new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7, false));
                     var4 = true;
                  }

                  if (var11 instanceof com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var10
                     && var10.HHCIHRHRIIOCIROOCCRCIOCROOOCHH() != CRICCOOHHHCHOORCICOCOHIHOIRHOO.NONE
                     && IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 5
                     && var8.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.bridge$getOffHandItemRenderState(), var1)
                     && !var5) {
                     this.COIORCORCHIRIRHCHICHOCROCHRCHR.add(new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7, true));
                     var5 = true;
                  }
               } else {
                  this.COIORCORCHIRIRHCHICHOCROCHRCHR.add(new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7, false));
               }
            }
         }
      }

      return this.COIORCORCHIRIRHCHICHOCROCHRCHR.size();
   }

   public Optional<RCIROOOOICRHCCRRCIORHHIRCOIIIC> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1, int var2) {
      return this.HROCICIOCORIOOCCIIICORCRRHHICI == null
         ? Optional.empty()
         : this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2)
            .map(var0 -> (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI)var0.OOICHRIOOOOIOHOIHOIRIRROCHRIOO())
            .flatMap(
               var1x -> var1x.CHCIRIRCCOCCHCRORRCRIHRCROCRIR().map(var2x -> var2x.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1x, this.HROCICIOCORIOOCCIIICORCRRHHICI))
            );
   }

   public Optional<RRCRRCORICCHOHHIRCHIROOHIIOHCO> IRCIIHHICIHRCOCRROCOICRIHHCCHH(HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1, int var2) {
      return Optional.of(this.COIORCORCHIRIRHCHICHOCROCHRCHR.get(var2).HIHOHHCCOIIHICOOCHICHCHRRCCHCI());
   }

   public static Color RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var0, HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1) {
      if (var0.RCIIIRRHHHHRHRIRHHROIRICHIHROC()
         == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.SHIELDS) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORIOHRCIHRCOOHICCCRIIIHCRHHIHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
            .HHRIIIOOIIRHICORCRIRCHRCOHCRHO();
         if (var2.isEnabled()) {
            int var3 = var2.RCOCRROHHROHHOCRCCCHCIROIIOORC(var1.bridge$getUniqueID());
            if (var3 != -1) {
               return new Color(var3 >> 16 & 0xFF, var3 >> 8 & 0xFF, var3 & 0xFF, var3 >> 24 & 0xFF);
            }
         }
      }

      return new Color(255, 255, 255, 255);
   }

   @Override
   public Optional<IRRCCOICORICIHCHRHIHIHROIRHOCR> RCIROOOOICRHCCRRCIORHHIRCOIIIC(RCIROOOOICRHCCRRCIORHHIRCOIIIC var1) {
      return Optional.of(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHRRORCOHRRIROCHIICHORRHHOROOH
            .get(var1)
      );
   }

   @Override
   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1) {
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHHIHROORHHOOCCOOCHRIRHRHCRHIH()
         .OHOHCHORHIIHCCOIHOHCCICRHHICIR()
         .IIHRRHORCRCROCHHOHORCHCROCIHRO(var1);
   }

   protected boolean shouldRender(HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1) {
      return !var1.bridge$isSpectator();
   }

   protected boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      return !var1.bridge$isInvisible() && !var1.bridge$isInvisibleToPlayer()
         ? true
         : var2.RCIIIRRHHHHRHRIRHHROIRICHIHROC().isHeldItemCosmetic()
            && var2.RCIIIRRHHHHRHRIRHHROIRICHIHROC()
               != com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HAND;
   }

   protected com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2
   ) {
      if (var1.IHHRIHOOOHHHROCIHOCCRHIIIIOHRH()) {
         com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 = com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CCHIHCHICORHHHIHRHCRCICCROHORR()
            .CCOOIHRHHRROHCIORHIRRHHHORHOOH()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.bridge$getUniqueID(), var2);
         return var4 == null
            ? com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CHOIHHRCRIHHICHIRHCCORRHHIICRI()
            : var4;
      }

      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION < 26) {
         return com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var1,
            var2
         );
      }

      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() == null) {
         return com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            null, var2
         );
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH()
         .bridge$getPlayerByUniqueId(var1.bridge$getUniqueID())
         .orElse(null);
      return com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var3,
         var2
      );
   }

   @Generated
   public CORCOCICIRIOHROHROIIOOHICCHCRR IHRCHHCOIHOHCRCRCCHIRIHIRROROR() {
      return this.HIIIHHRRRRCCCRHCHRIORIRIRCCIIH;
   }
}
