package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   implements com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IIHRRHORCRCROCHHOHORCHCROCIHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final double IROCIHHRHIHCRIHIOHOOHHRIICCCRH;
   private final double OOCICRIIIRRIOOCRHRRRRRHIRHRCRO;
   private final String OOHRHRIRICHRRRHRHIHCHCICICHICH;

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(double var1, double var3, String var5) {
      this.IROCIHHRHIHCRIHIOHOOHHRIICCCRH = var1;
      this.OOCICRIIIRRIOOCRHRRRRRHIRHRCRO = var3;
      this.OOHRHRIRICHRRRHRHIHCHCICICHICH = var5;
   }

   @Override
   public double IOOCIRHHCORRHOICIIIIOORRICRRCH() {
      return this.IROCIHHRHIHCRIHIOHOOHHRIICCCRH;
   }

   @Override
   public double IHORHRHORRRCCRHRCRORHOOOIHCROH() {
      return this.OOCICRIIIRRIOOCRHRRRRRHIRHRCRO;
   }

   @Override
   public String bridge$getName() {
      return this.OOHRHRIRICHRRRHRHIHCHCICICHICH;
   }
}
