package com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ICICIOCHHHIHOCHCOHORIHRCOHHOCR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends ICICIOCHHHIHOCHCOHORIHRCOHHOCR<HCHRIROHHHCORIOCROOCHRCIOROOCI<Integer>> {
   private static List<IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> RICOOCCRORIOOIHHOCIHCHRHRIOOOH = null;

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      HCHRIROHHHCORIOCROOCHRCIOROOCI<Integer> var1,
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      super(var1, var2);
      if (RICOOCCRORIOOIHHOCIHCHRHRIOOOH == null) {
         ArrayList var3 = new ArrayList();
         int var4 = 0;

         for (String var8 : CRRRICCRROCOHHOHIICIHORCOORRRH.HRORCRCIRCCCIICCHCICHORHIIHOIH) {
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHHRCIROCCOHCHOIOHIOCHOIIHOCIO(
               var8
            );
            var3.add(new IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var9, RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var9, var4++)));
         }

         RICOOCCRORIOOIHHOCIHCHRHRIOOOH = Collections.unmodifiableList(var3);
      }

      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         (var2x, var3x) -> {
            float var4x = var2x.COCCOIROHORRRHIHICORRHRRORIIIH();
            float var5 = var2x.RHIIOORHHCCOCIORHIRCICHCHRRIII();
            int var6 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(var4x, var5);
            if (var6 >= 0 && var6 < RICOOCCRORIOOIHHOCIHCHRHRIOOOH.size()) {
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = RICOOCCRORIOOIHHOCIHCHRHRIOOOH.get(
                     var6
                  )
                  .RHHHOHCROIIORCHOOIICHHHORRCRCH;
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8x = var7.CRICOHCIOHIOOCRIHHORCOIHOROCII();
               if (var8x
                  == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SMALL
                  )
                {
                  var8x = var8x.bigger();
               }

               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9x = var1.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
                     CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRRIRICROIIHIICICIRCOHCCHROIRI
                  )
                  .RHCICORHIHIIHRHHIIHICRICOIRCHO();
               var9x.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var7.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var8x, false));
               return true;
            } else {
               return false;
            }
         }
      );
   }

   private static RCIROOOOICRHCCRRCIORHHIRCOIIIC RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0,
      int var1
   ) {
      if (var0.isEmpty()) {
         return null;
      }

      int var2 = var0.CRICOHCIOHIOOCRIHHORCOIHOROCII().size();
      BufferedImage var3 = new BufferedImage(var2, var2, 2);
      boolean[] var4 = var0.ICCCIHRHOCCOICCORHORCHHHROOIRC();

      for (int var5 = 0; var5 < var2 * var2; var5++) {
         if (var4[var5]) {
            var3.setRGB(var5 % var3.getWidth(), var5 / var3.getHeight(), -1);
         }
      }

      RCIROOOOICRHCCRRCIORHHIRCOIIIC var7 = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "custom_crosshair_preset_" + var1);
      CORCOCICIRIOHROHROIIOOHICCHCRR var6 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3);
      IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getTextureManager().bridge$loadTexture(var7, var6);
      return var7;
   }

   public int RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(float var1, float var2) {
      if ((var1 - this.x) % 22.75F > 15.0F) {
         return -1;
      }

      if ((var2 - (this.y + 3.0F)) % 25.0F > 15.0F) {
         return -1;
      }

      int var3 = (int)Math.floor((var1 - this.x) / 22.75F);
      int var4 = (int)Math.floor((var2 - (this.y + 3.0F)) / 25.0F);
      return var3 >= 0 && var3 < 14 && var4 == 0 ? var3 : -1;
   }

   @Override
   public void update() {
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      boolean var3
   ) {
      float var4 = var2.COCCOIROHORRRHIHICORRHRRORIIIH();
      float var5 = var2.RHIIOORHHCCOCIORHIRCICHCHRRIII();
      int var6 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(var4, var5);

      for (int var7 = 0; var7 < 14; var7++) {
         float var8 = this.x + 1.0F + var7 * 22.75F;
         RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1, var8, this.y + 3.0F, 15.0F, 15.0F, 4.0F, 1076176165, 553648127, var6 == var7 ? 1174405119 : 553648127
         );
         IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9 = RICOOCCRORIOOIHHOCIHCHRHRIOOOH.get(var7);
         if (var9.RHIOIRHRHRCOICIICHIRCCORRRIHOR != null) {
            float var10 = var8 + 6.85F;
            float var11 = this.y + 10.0F;
            int var12 = var9.RHHHOHCROIIORCHOOIICHHHORRCRCH.CRICOHCIOHIOOCRIHHORCOIHOROCII().size();
            int var13 = (int)Math.floor(var12 / 2.0F);
            RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               var1, var9.RHIOIRHRHRCOICIICHIRCCORRRIHOR, var10 - var13, var11 - var13, var12, var12, -1
            );
         }
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      char var1, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
   }

   @Override
   public void close() {
   }

   @Override
   public float getHeight() {
      return this.getOption().isHidden() ? 0.0F : 30.0F;
   }

   @Override
   public boolean CRRIHOOHIRHRHHCROHIHHCICRICIIH() {
      return false;
   }

   @Override
   public String getLanguagePath() {
      return "gui.crosshair_edit";
   }

   private record RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RHHHOHCROIIORCHOOIICHHHORRCRCH;
      private final RCIROOOOICRHCCRRCIORHHIRCOIIIC RHIOIRHRHRCOICIICHIRCCORRRIHOR;

      private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
         RCIROOOOICRHCCRRCIORHHIRCOIIIC var2
      ) {
         this.RHHHOHCROIIORCHOOIICHHHORRCRCH = var1;
         this.RHIOIRHRHRCOICIICHIRCCORRRIHOR = var2;
      }

      public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH COOHHCRCIHRIHCOIRICCRHIOCOIOOR() {
         return this.RHHHOHCROIIORCHOOIICHHHORRCRCH;
      }

      public RCIROOOOICRHCCRRCIORHHIRCOIIIC OHIRIIIHOHRHCHOHOORHCORORIOIHI() {
         return this.RHIOIRHRHRCOICIICHIRCCORRRIHOR;
      }
   }
}
