package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import java.io.Serializable;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.reflect.Member;
import java.lang.reflect.Modifier;

@Target({ElementType.ANNOTATION_TYPE, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
public @interface OOROOCCIRCCRHOIOIORIHCHHOOCCOR {
   OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH OORHRHRRRHIICIHORIHCOOCCROIOCH() default OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;

   OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH RCROHHHIRHOIIIORIOCIHRROIRHOIH() default OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;

   OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH OOHHOIIIRRIIOIICCIOHIIRCOOORHC() default OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;

   OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH OHHRRRCIOICRROOHRCIOIROHIRIOOO() default OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;

   OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH OOIIHHOORORCOCCRORIIIOCOOHHRCC() default OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;

   enum IRCIIHHICIHRCOCRROCOICRIHHCCHH {
      ANY,
      NON_PRIVATE,
      PROTECTED_AND_PUBLIC,
      PUBLIC_ONLY,
      NONE,
      DEFAULT;

      public boolean isVisible(Member var1) {
         switch (this) {
            case ANY:
               return true;
            case NONE:
               return false;
            case NON_PRIVATE:
               return !Modifier.isPrivate(var1.getModifiers());
            case PROTECTED_AND_PUBLIC:
               if (Modifier.isProtected(var1.getModifiers())) {
                  return true;
               }
            case PUBLIC_ONLY:
               return Modifier.isPublic(var1.getModifiers());
            default:
               return false;
         }
      }
   }

   class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      implements com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH<OOROOCCIRCCRHOIOIORIHCHHOOCCOR>,
      Serializable {
      private static final long ORRORORROHIIRCHCCROHCCOCOICOOC = 1L;
      private static final OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH HIOHRHRCCCIRIHRIROHORCCHCCRRIH = OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.PUBLIC_ONLY;
      protected static final OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IIRRHORHHOIOIHCIIRIIHHCHRHRHRR = new OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HIOHRHRCCCIRIHRIROHORCCHCCRRIH,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.PUBLIC_ONLY,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.PUBLIC_ONLY,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ANY,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.PUBLIC_ONLY
      );
      protected static final OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ROOICORIHHCOHOHICCCORIOROHIHCH = new OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT
      );
      protected final OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH RRCCCIHICROCRCHOCIRCIIICRICHCH;
      protected final OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH IROOOICRRROOIOCRCCRROORCIOICIH;
      protected final OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH CCCOCHOHRHHRORHOHRCCIRRRHORCRH;
      protected final OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH IRCRHHRIRROOHICHHROHOOCIICRCOH;
      protected final OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH COICHHIHOCCOHIIIRHOHCICIIORIIH;

      private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5
      ) {
         this.RRCCCIHICROCRCHOCIRCIIICRICHCH = var1;
         this.IROOOICRRROOIOCRCCRROORCIOICIH = var2;
         this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH = var3;
         this.IRCRHHRIRROOHICHHROHOOCIICRCOH = var4;
         this.COICHHIHOCCOHIIIRHOHCICIIORIIH = var5;
      }

      public static OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCCOIHCIIHHRHCRCRRCORIOCCRICHR() {
         return IIRRHORHHOIOIHCIIRIIHHCHRHRHRR;
      }

      public static OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HIOHOCHOHROOCCHHORIIOROOOCRCCI() {
         return ROOICORIHHCOHOHICCCORIOROHIHCH;
      }

      public static OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(OOROOCCIRCCRHOIOIORIHCHHOOCCOR var0) {
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var0.OOIIHHOORORCOCCRORIIIOCOOHHRCC(),
            var0.OORHRHRRRHIICIHORIHCOOCCROIOCH(),
            var0.RCROHHHIRHOIIIORIOCIHRROIRHOIH(),
            var0.OOHHOIIIRRIIOIICCIOHIIRCOOORHC(),
            var0.OHHRRRCIOICRROOHRCIOIROHIRIOOO()
         );
      }

      public static OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         IIHRHCCOOHOOOOCHRRCOROOIOHCOOO var0, OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
      ) {
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var6 = OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT;
         switch (var0) {
            case CREATOR:
               var6 = var1;
               break;
            case FIELD:
               var2 = var1;
               break;
            case GETTER:
               var3 = var1;
               break;
            case IS_GETTER:
               var4 = var1;
            case NONE:
            default:
               break;
            case SETTER:
               var5 = var1;
               break;
            case ALL:
               var6 = var1;
               var5 = var1;
               var4 = var1;
               var3 = var1;
               var2 = var1;
         }

         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var4, var5, var6);
      }

      public static OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4
      ) {
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0, var1, var2, var3, var4);
         if (var5 == null) {
            var5 = new OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, var2, var3, var4);
         }

         return var5;
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
      ) {
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            this.IROOOICRRROOIOCRCCRROORCIOICIH,
            this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH,
            this.IRCRHHRIRROOHICHHROHOOCIICRCOH,
            this.COICHHIHOCCOHIIIRHOHCICIIORIIH
         );
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
      ) {
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.RRCCCIHICROCRCHOCIRCIIICRICHCH,
            var1,
            this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH,
            this.IRCRHHRIRROOHICHHROHOOCIICRCOH,
            this.COICHHIHOCCOHIIIRHOHCICIIORIIH
         );
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
      ) {
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.RRCCCIHICROCRCHOCIRCIIICRICHCH,
            this.IROOOICRRROOIOCRCCRROORCIOICIH,
            var1,
            this.IRCRHHRIRROOHICHHROHOOCIICRCOH,
            this.COICHHIHOCCOHIIIRHOHCICIIORIIH
         );
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CRRRICCRROCOHHOHIICIHORCOORRRH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
      ) {
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.RRCCCIHICROCRCHOCIRCIIICRICHCH,
            this.IROOOICRRROOIOCRCCRROORCIOICIH,
            this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH,
            var1,
            this.COICHHIHOCCOHIIIRHOHCICIIORIIH
         );
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RRCRRCORICCHOHHIRCHIROOHIIOHCO(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
      ) {
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.RRCCCIHICROCRCHOCIRCIIICRICHCH,
            this.IROOOICRRROOIOCRCCRROORCIOICIH,
            this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH,
            this.IRCRHHRIRROOHICHHROHOOCIICRCOH,
            var1
         );
      }

      public static OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0, OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
      ) {
         return var0 == null ? var1 : var0.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
      ) {
         if (var1 == null || var1 == ROOICORIHHCOHOHICCCORIOROHIHCH || var1 == this) {
            return this;
         }

         if (IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, var1)) {
            return this;
         }

         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = var1.RRCCCIHICROCRCHOCIRCIIICRICHCH;
         if (var2 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT) {
            var2 = this.RRCCCIHICROCRCHOCIRCIIICRICHCH;
         }

         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var1.IROOOICRRROOIOCRCCRROORCIOICIH;
         if (var3 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT) {
            var3 = this.IROOOICRRROOIOCRCCRROORCIOICIH;
         }

         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = var1.CCCOCHOHRHHRORHOHRCCIRRRHORCRH;
         if (var4 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT) {
            var4 = this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH;
         }

         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 = var1.IRCRHHRIRROOHICHHROHOOCIICRCOH;
         if (var5 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT) {
            var5 = this.IRCRHHRIRROOHICHHROHOOCIICRCOH;
         }

         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var6 = var1.COICHHIHOCCOHIIIRHOHCICIIORIIH;
         if (var6 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT) {
            var6 = this.COICHHIHOCCOHIIIRHOHCICIIORIIH;
         }

         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var4, var5, var6);
      }

      @Override
      public Class<OOROOCCIRCCRHOIOIORIHCHHOOCCOR> HIHCROOHCOCCCIHCIHCHORCCHIIIIC() {
         return OOROOCCIRCCRHOIOIORIHCHHOOCCOR.class;
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH COORHRHHRICOCROCRCCCROCOHIRHCO() {
         return this.RRCCCIHICROCRCHOCIRCIIICRICHCH;
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH HROCCOHHOCIHIHRHCHIIHIOOHROIIH() {
         return this.IROOOICRRROOIOCRCCRROORCIOICIH;
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH RHHHIIOHCHCCIHOCRHCORRIIHCRORH() {
         return this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH;
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH IOROIRCHRHIIOOCORHRHHRCOOOOOIH() {
         return this.IRCRHHRIRROOHICHHROHOOCIICRCOH;
      }

      public OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH RRIOCORORHIRIHICOIIHRHCIRRCRII() {
         return this.COICHHIHOCCOHIIIRHOHCICIIORIIH;
      }

      protected Object readResolve() {
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            this.RRCCCIHICROCRCHOCIRCIIICRICHCH,
            this.IROOOICRRROOIOCRCCRROORCIOICIH,
            this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH,
            this.IRCRHHRIRROOHICHHROHOOCIICRCOH,
            this.COICHHIHOCCOHIIIRHOHCICIIORIIH
         );
         return var1 == null ? this : var1;
      }

      @Override
      public String toString() {
         return String.format(
            "JsonAutoDetect.Value(fields=%s,getters=%s,isGetters=%s,setters=%s,creators=%s)",
            this.RRCCCIHICROCRCHOCIRCIIICRICHCH,
            this.IROOOICRRROOIOCRCCRROORCIOICIH,
            this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH,
            this.IRCRHHRIRROOHICHHROHOOCIICRCOH,
            this.COICHHIHOCCOHIIIRHOHCICIIORIIH
         );
      }

      @Override
      public int hashCode() {
         return 1 + this.RRCCCIHICROCRCHOCIRCIIICRICHCH.ordinal()
            ^ 3 * this.IROOOICRRROOIOCRCCRROORCIOICIH.ordinal()
               - 7 * this.CCCOCHOHRHHRORHOHRCCIRRRHORCRH.ordinal()
               + 11 * this.IRCRHHRIRROOHICHHROHOOCIICRCOH.ordinal()
            ^ 13 * this.COICHHIHOCCOHIIIRHOHCICIIORIIH.ordinal();
      }

      @Override
      public boolean equals(Object var1) {
         if (var1 == this) {
            return true;
         } else {
            return var1 == null
               ? false
               : var1.getClass() == this.getClass()
                  && IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, (OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var1);
         }
      }

      private static OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4
      ) {
         if (var0 == HIOHRHRCCCIRIHRIROHORCCHCCRRIH) {
            if (var1 == IIRRHORHHOIOIHCIIRIIHHCHRHRHRR.IROOOICRRROOIOCRCCRROORCIOICIH
               && var2 == IIRRHORHHOIOIHCIIRIIHHCHRHRHRR.CCCOCHOHRHHRORHOHRCCIRRRHORCRH
               && var3 == IIRRHORHHOIOIHCIIRIIHHCHRHRHRR.IRCRHHRIRROOHICHHROHOOCIICRCOH
               && var4 == IIRRHORHHOIOIHCIIRIIHHCHRHRHRR.COICHHIHOCCOHIIIRHOHCICIIORIIH) {
               return IIRRHORHHOIOIHCIIRIIHHCHRHRHRR;
            }
         } else if (var0 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT
            && var1 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT
            && var2 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT
            && var3 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT
            && var4 == OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEFAULT) {
            return ROOICORIHHCOHOHICCCORIOROHIHCH;
         }

         return null;
      }

      private static boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0, OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
      ) {
         return var0.RRCCCIHICROCRCHOCIRCIIICRICHCH == var1.RRCCCIHICROCRCHOCIRCIIICRICHCH
            && var0.IROOOICRRROOIOCRCCRROORCIOICIH == var1.IROOOICRRROOIOCRCCRROORCIOICIH
            && var0.CCCOCHOHRHHRORHOHRCCIRRRHORCRH == var1.CCCOCHOHRHHRORHOHRCCIRRRHORCRH
            && var0.IRCRHHRIRROOHICHHROHOOCIICRCOH == var1.IRCRHHRIRROOHICHHROHOOCIICRCOH
            && var0.COICHHIHOCCOHIIIRHOHCICIIORIIH == var1.COICHHIHOCCOHIIIRHOHCICIIORIIH;
      }
   }
}
