package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRRCCOICORICIHCHRHIHIHROIRHOCR;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;

class IRCIIHHICIHRCOCRROCOICRIHHCCHH implements HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH {
   private static final RCIROOOOICRHCCRRCIORHHIRCOIIIC CORRCHOOOOOCHRHOCHHOCORRCIHRRO = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "icons/compass.png");

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      float var3,
      float var4,
      double var5
   ) {
      float var7 = (int)RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.RICRIRRCOHRCOCRRHHCRHRROOIOHHR((float)(var5 * 256.0 / 360.0 + 0.5)) & 0xFF;
      int var8 = var1.IIHOICCRCIRHOOCCIRRORCCIROIIRO.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(var3 + var4);
      if (var7 < 128.0F) {
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2, CORRCHOOOOOCHRHOCHHOCORRCIHRRO, var3, var4, (int)var7, 0, 65, 12, -1
         );
      } else {
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2, CORRCHOOOOOCHRHOCHHOCORRCIHRRO, var3, var4, (int)(var7 - 128.0F), 12, 65, 12, -1
         );
      }

      var8 = var8 & 16777215 | 0xFF000000;
      if (var7 < 128.0F) {
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2, CORRCHOOOOOCHRHOCHHOCORRCIHRRO, var3, var4, (int)var7, 24, 65, 12, var8
         );
      } else {
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2, CORRCHOOOOOCHRHOCHHOCORRCIHRRO, var3, var4, (int)(var7 - 128.0F), 36, 65, 12, var8
         );
      }

      if (var1.RIHOORCROICHOCRCICIRIRRRCCRRCO.get()) {
         var1.OHCOICRCICRHIICOIROOHCCOCCRCHO.CRRRICCRROCOHHOHIICIHORCOORRRH(var2, "|", var3 + 32.0F, var4 + 1.0F);
         var1.OHCOICRCICRHIICOIROOHCCOCCRCHO.CRRRICCRROCOHHOHIICIHORCOORRRH(var2, "|", var3 + 32.0F, var4 + 5.0F);
      }
   }
}
