package com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import org.joml.Math;

public class CRRRICCRROCOHHOHIICIHORCOORRRH
   implements RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH> {
   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      RRCRRCORICCHOHHIRCHIROOHIIOHCO var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var4
   ) {
      int var5 = var4.CCHHCROIOCRIIRICHRRIIHCHCOHHOI();
      var4.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(var5 + 1);
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var4, var3.bridge$getEyePosition()
      );
      double var6 = var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3);
      if (var6 > 144.0) {
         com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2, var3, var4
         );
      }

      if (var5 % 4 == 1) {
         int var8 = (int)Math.floor(var4.bridge$getPosX());
         int var9 = (int)Math.floor(var4.bridge$getPosY());
         int var10 = (int)Math.floor(var4.bridge$getPosZ());
         if (!com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var2, var8, var9, var10, var4
            )
            && !com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var2, var3, var4
            )) {
            double var11 = var3.bridge$getPosX() + 2000.0;
            double var13 = var3.bridge$getPosY() - 2000.0;
            double var15 = var3.bridge$getPosZ() + 2000.0;
            var4.bridge$setPosX(var11);
            var4.bridge$setPosY(var13);
            var4.bridge$setPosZ(var15);
            var4.bridge$setPreviousPosX(var11);
            var4.bridge$setPreviousPosY(var13);
            var4.bridge$setPreviousPosZ(var15);
         }
      }

      return false;
   }
}
