package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Map.Entry;
import java.util.function.Consumer;
import lombok.Generated;
import org.jetbrains.annotations.Nullable;

public class HICHRCOHCCRHOHCICOOCHOIHCCHIRI implements com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRICCOOHHHCHOORCICOCOHIHOIRHOO {
   private final Map<Class<com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH>, List<com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO<com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH>>> RCRRRCRRRRCIRRRHCRRHCRRHROIRHH = new HashMap<>();
   private final Set<com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH> OCHHHCOCRHOCHCOHHHRHCIOORHIHCC = new HashSet<>();
   private final List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> IIHHRHORORRCHHIIORIIRHRCRHIHCR = new ArrayList<>();
   private final List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH> IHHCHHIRCIRRCHOCHCCRHRRIOOHCCH = new ArrayList<>();
   private final List<Runnable> CROIOOHROCORRRRRCRRICHHCRHCIRC = new ArrayList<>();
   private final List<Runnable> RHOHHCIOCCHCHRCOCIIIICOCHRRIRO = new ArrayList<>();
   private final List<Runnable> HOIOIIHIHROORRCIHROCCIOHROOROO = new ArrayList<>();
   private boolean OIHORHHRORCHHOROCOIHCCIHRCROOO = false;
   private boolean RCRIHRHROCHHHOHCRIRHHOCHRHCICI = false;
   private boolean COHORHHIHRHRHICRIHIOCOHIIIRIOH = false;

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, boolean var2, boolean var3
   ) {
      if (var2 != this.RCRIHRHROCHHHOHCRIRHHOCHRHCICI) {
         if (var3) {
            String var4 = var2 ? "enabled " : "disabled ";
            System.out.println("[ServerIntegration] " + var4 + var1.getId());
         }

         this.RCRIHRHROCHHHOHCRIRHHOCHRHCICI = var2;
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var5 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
            HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR
         );
         if (var5 != null) {
            var5.RICRIHOOHROHICCHHIIHRHCORHIOHR(false);
         }

         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var5,
            var3,
            var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IICCRHIHRIHOHICHCRIROICOICROOR),
            var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
         );
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      @Nullable OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1, @Nullable RRCRRCORICCHOHHIRCHIROOHIIOHCO var2, @Nullable CRRRICCRROCOHHOHIICIHORCOORRRH var3
   ) {
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, false, var2, var3);
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      @Nullable OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1, boolean var2, @Nullable RRCRRCORICCHOHHIRCHIROOHIIOHCO var3, @Nullable CRRRICCRROCOHHOHIICIHORCOORRRH var4
   ) {
      boolean var5 = var1 == null || var1.RRRORRHCRIRRRCRCOOCHROIORIHIHC();
      boolean var6 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4);
      boolean var7 = this.RCRIHRHROCHHHOHCRIRHHOCHRHCICI && var5 && var6;
      if (var7 != this.OIHORHHRORCHHOROCOIHCCIHRCROOO) {
         this.OIHORHHRORCHHOROCOIHCCIHRCROOO = var7;
         if (var7) {
            this.OIICOCRORORCHHIOHCCROIHROHCCCI();
         } else {
            this.IHOCCIHHORIIHRHIHHOHOHHOCIHRCC();
         }

         if (var3 != null) {
            this.OOCCRCRCOHIIORCCORCRCIRRROIOOR(var3.getChildren());
         }
      }

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var9 : this.IHHCHHIRCIRRCHOCHCCRHRRIOOHCCH) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRICCOOHHHCHOORCICOCOHIHOIRHOO var10 = var9.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
            HICRRICCHCCROOHHCHOCOCCHOIHHOC.CHOCIHRHOOCRCRRORCRRIHHCRIHHRI
         );
         if (var10 != null) {
            var10.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var9, var7, var2);
         }
      }
   }

   private boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(@Nullable CRRRICCRROCOHHOHIICIHORCOORRRH var1) {
      if (var1 == null) {
         return true;
      }

      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2 = var1.<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH>RHHCIICOCRRIHOOCHHHRHICRORCCRI()
         .IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CHOCIHRHOOCRCRRORCRRIHHCRIHHRI);
      return var2 == null
         ? this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1.<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH>RHHCIICOCRRIHOOCHHHRHICRORCCRI()
               .IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
         )
         : var2.ICRIIIIRRCHIRRROOHCOOHROIIHRHR();
   }

   private void OOCCRCRCOHIIORCCORCRCIRRROIOOR(List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH> var1) {
      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 : var1) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRICCOOHHHCHOORCICOCOHIHOIRHOO var4 = var3.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
            HICRRICCHCCROOHHCHOCOCCHOIHHOC.CHOCIHRHOOCRCRRORCRRIHHCRIHHRI
         );
         if (var4 != null) {
            var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var3.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR),
               var3.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IICCRHIHRIHOHICHCRIROICOICROOR),
               var3.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
            );
         } else {
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var5 = var3.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
               HICRRICCHCCROOHHCHOCOCCHOIHHOC.IICCRHIHRIHOHICHCRIROICOICROOR
            );
            if (var5 != null) {
               this.OOCCRCRCOHIIORCCORCRCIRRROIOOR(var5.getChildren());
            }
         }
      }
   }

   @Override
   public int HOIICRCHCHRRIHCHOOICHRCRRRRHOI() {
      int var1 = 0;

      for (List var3 : this.RCRRRCRRRRCIRRRHCRRHCRRHROIRHH.values()) {
         var1 += var3.size();
      }

      return var1;
   }

   protected void OIICOCRORORCHHIOHCCROIHROHCCCI() {
      this.OCHHHCOCRHOCHCOHHHRHCIOORHIHCC
         .forEach(com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH::RCHOIICOHORCIHHIIOOHHCCOIIIOHC);

      for (Entry var2 : this.RCRRRCRRRRCIRRRHCRRHCRRHROIRHH.entrySet()) {
         for (com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 : (List)var2.getValue()) {
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
               .IRCIIHHICIHRCOCRROCOICRIHHCCHH((Class)var2.getKey(), var4.COIOHCOCOHIRRRRRCCIHRRCICOCOII(), var4.priority());
         }
      }

      this.CROIOOHROCORRRRRCRRICHHCRHCIRC.forEach(Runnable::run);
      if (!this.COHORHHIHRHRHICRIHIOCOHIIIRIOH) {
         this.COHORHHIHRHRHICRIHIOCOHIIIRIOH = true;
         this.HOIOIIHIHROORRCIHROCCIOHROOROO.forEach(Runnable::run);
      }
   }

   protected void IHOCCIHHORIIHRHIHHOHOHHOCIHRCC() {
      this.OCHHHCOCRHOCHCOHHHRHCIOORHIHCC
         .forEach(com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH::HOCCOCRCOHORCHOHCHIROIHCOHOIRR);

      for (Entry var2 : this.RCRRRCRRRRCIRRRHCRRHCRRHROIRHH.entrySet()) {
         for (com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 : (List)var2.getValue()) {
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
               .CRRRICCRROCOHHOHIICIHORCOORRRH((Class)var2.getKey(), var4.COIOHCOCOHIRRRRRCCIHRRCICOCOII());
         }
      }

      this.RHOHHCIOCCHCHRCOCIIIICOCHRRIRO.forEach(Runnable::run);
   }

   @Override
   public <T extends com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> void handle(Class<T> var1, Consumer<T> var2) {
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, 100);
   }

   @Override
   public <T extends com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Class<T> var1, Consumer<T> var2, int var3
   ) {
      this.RCRRRCRRRRCIRRRHCRRHCRRHROIRHH
         .computeIfAbsent(var1, var0 -> new ArrayList<>())
         .add(new com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO<>(var3, var2));
      if (this.OIHORHHRORCHHOROCOIHCCIHRCROOO) {
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
            .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.OCHHHCOCRHOCHCOHHHRHCIOORHIHCC.add(var1);
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      if (this.IIHHRHORORRCHHIIORIIRHRCRHIHCR.isEmpty()) {
         this.handle(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.class,
            var1x -> {
               for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 : this.IIHHRHORORRCHHIIORIIRHRCRHIHCR) {
                  if (var3.isEnabled() && var1x.IRCRIHCRIRIRICRCRCROHORIROOOIO(var3.HCIOCIHRHRCCRIRCOCIHHOOHHROHHC())) {
                     if (!var3.HICROROICOCOHOOHHCRCROOCCRCIHR(var1x.getCommand())) {
                        IICCOOCHCHROORHHIIHROHCCRHRCOR.OCCIHCOCHOHOOHIHCRCORCCCOCCOCH("Failed to execute command: " + var1x.getCommand());
                     }

                     var1x.cancel();
                     return;
                  }
               }
            }
         );
         this.handle(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class,
            var1x -> {
               for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 : this.IIHHRHORORRCHHIIORIIRHRCRHIHCR) {
                  if (var3.isEnabled() && var1x.IRCRIHCRIRIRICRCRCROHORIROOOIO(var3.HCIOCIHRHRCCRIRCOCIHHOOHHROHHC())) {
                     var1x.OHCOROOHHRHOIOCHIOOHIIOHROOCCO();
                     return;
                  }
               }
            }
         );
         this.handle(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.class,
            var1x -> {
               for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 : this.IIHHRHORORRCHHIIORIIRHRCRHIHCR) {
                  if (var3.isEnabled() && var3.IICRCCIHHCHRROCRICCIRHRIOHCRIH()) {
                     var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3);
                  }
               }
            }
         );
      }

      this.IIHHRHORORRCHHIIORIIRHRCRHIHCR.add(var1);
   }

   @Override
   public void RRCRRCORICCHOHHIRCHIROOHIIOHCO(Runnable var1) {
      this.CROIOOHROCORRRRRCRRICHHCRHCIRC.add(var1);
   }

   @Override
   public void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(Runnable var1) {
      this.RHOHHCIOCCHCHRCOCIIIICOCHRRIRO.add(var1);
   }

   @Override
   public void HRCHROOHRIHCRCRHRIIROCIRHOIRHH(Runnable var1) {
      this.HOIOIIHIHROORRCIHROCCIOHROOROO.add(var1);
   }

   @Override
   public void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.IHHCHHIRCIRRCHOCHCCRHRRIOOHCCH.add(var1);
      if (this.OIHORHHRORCHHOROCOIHCCIHRCROOO) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
            HICRRICCHCCROOHHCHOCOCCHOIHHOC.CHOCIHRHOOCRCRRORCRRIHHCRIHHRI
         );
         if (var2 != null) {
            var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, true, false);
         }
      }
   }

   @Override
   public void HRCHROOHRIHCRCRHRIIROCIRHOIRHH(com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.IHHCHHIRCIRRCHOCHCCRHRRIOOHCCH.remove(var1);
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CHOCIHRHOOCRCRRORCRRIHHCRIHHRI
      );
      if (var2 != null) {
         var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, false, false);
      }
   }

   @Generated
   @Override
   public boolean ICRIIIIRRCHIRRROOHCOOHROIIHRHR() {
      return this.OIHORHHRORCHHOROCOIHCCIHRCROOO;
   }

   @Generated
   @Override
   public boolean CORRCORIIHCIHHCIRIIIICCHHOHORI() {
      return this.RCRIHRHROCHHHOHCRIRHHOCHRHCICI;
   }
}
