package com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

public class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends RCIRROCCCIIHCIHCCRHHCCHOHHHCHH implements RIOOCHICIHRHOHCCCCCHOCCCOHCRHI {
   public static final com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OOIRCCCOCCCHHHHROORCOICHIORHRH = new CRRRICCRROCOHHOHIICIHORCOORRRH(
      null,
      new com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         50.0
      )
   );
   public com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HROCHHORIRORCRIOHROCCIIOCOCCCC = com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IORRCOHROOHHORCRCOOIRHRCORHHHH;

   public HHCCIRHCCCIIRHCROHIORHIRHHIORH() {
      this.HIICCHIOORRHORRIRHOOCHIRRHHOIH = OOIRCCCOCCCHHHHROORCOICHIORHRH;
   }

   @Override
   public com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      JsonElement var1, com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      if (!var1.isJsonObject()) {
         return super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2);
      }

      JsonObject var3 = var1.getAsJsonObject();
      if (var3.has("spawn_rate")) {
         this.HROCHHORIRORCRIOHROCCIIOCOCCCC = var2.IHIRRIIORRHORHRORIHOROIRCORCOO(var3.get("spawn_rate"));
      }

      if (var3.has("max_particles")) {
         this.HIICCHIOORRHORRIRHOOCHIRRHHOIH = var2.IHIRRIIORRHORHRORIHOROIRCORCOO(var3.get("max_particles"));
      }

      return super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var2);
   }

   @Override
   public JsonElement RCHIIHHHCCIOHHRORHOORICCCRHOOI() {
      JsonObject var1 = new JsonObject();
      if (!com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         this.HROCHHORIRORCRIOHROCCIIOCOCCCC
      )) {
         var1.add("spawn_rate", this.HROCHHORIRORCRIOHROCCIIOCOCCCC.RCHIIHHHCCIOHHRORHOORICCCRHOOI());
      }

      if (!com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.HIICCHIOORRHORRIRHOOCHIRRHHOIH, 50.0
      )) {
         var1.add("max_particles", this.HIICCHIOORRHORRIRHOOCHIRRHHOIH.RCHIIHHHCCIOHHRORHOORICCCRHOOI());
      }

      return var1;
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      float var2
   ) {
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      float var2
   ) {
      if (var1.playing) {
         double var3 = var1.HCCCCIHIOIHCHCCHOOHHCIHRCRRRHH(var2) * this.HROCHHORIRORCRIOHROCCIIOCOCCCC.get();
         double var5 = var3 - var1.ORCCHIRHHCCIHICRHHOCCIIHHCIRRI;
         double var7 = Math.ceil(var5);
         if (var7 > 0.0) {
            var1.HHOIOCRIRIOCOIHHOOHICIOIIOHCOR(var2);

            for (int var9 = 0; var9 < var7; var9++) {
               if (var1.OOICORIRHOCIOOHRHHIOOOOIIICHII.size() < this.HIICCHIOORRHORRIRHOOCHIRRHHOIH.get()) {
                  var1.CHROROOROICHCRRCRHRRHOIHHRIRII();
               }
            }

            var1.ORCCHIRHHCCIHICRHHOCCIIHHCIRRI += var7;
         }
      }
   }

   @Override
   public int IHHCCIORHRCORORHHIOICIRCHCHOHH() {
      return 10;
   }
}
