package com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.google.common.collect.Range;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.lunarclient.websocket.cosmetic.v2.FavoriteCosmeticRequest;
import com.lunarclient.websocket.cosmetic.v2.UnfavoriteCosmeticRequest;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH;
import com.moonsworth.webosr.javascript.CallbackJS;
import it.unimi.dsi.fastutil.longs.LongSet;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

public class CRRRICCRROCOHHOHIICIHORCOORRRH
   implements com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH,
   com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private static final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI RIOIHIOCOCCORHOHOOOCOCRRIIOIHC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showClothCloaksForOthers"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private static final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI HRIROICCHRCOIOOCROCRRHRIIROCHH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "flipArm"
      )
      .IRCIIHHICIHRCOCRROCOICRIHHCCHH(com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.PI_SWAP_ARROW_HORIZONTAL_STROKE)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private static com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IHIRRIIORRHORHRORIHOROIRCORCOO CHHHCHIICIIHRCRRCOHHCRIHIROIRI;
   private static final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI IRICIROHIOCOIROORIRROCCIIICOHC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showHatAboveHelmet"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private static final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI OROOIIOCOHRCOHOIIHIOIHCHOCHIOI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showOverChestplate"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private static final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI CRCRHIHRHICIOHOHROOIRRCOIHOIHH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showOverLeggings"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private static final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI HCIOHCOOICHRHOHCRCCIHCRHORRROR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showOverBoots"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();

   @Override
   public com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHCCIRHCCCIIRHCROHIORHIRHHIORH CORROIRHRRIHCRHIROHHORCCHIIRCO() {
      return com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC()
         .CORROIRHRRIHCRHIROHHORCCHIIRCO();
   }

   @Override
   public JsonElement provide() {
      return this.HRRORHCRHHRROHIOROOOORRIRRCCIC();
   }

   @CallbackJS("getCosmeticData")
   public static String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Integer[] var0) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC();
      JsonArray var2 = new JsonArray();

      for (Integer var6 : var0) {
         com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7 = var1.CCOCOIIRIOCICOCRCRRICHOCOCOHHI()
            .get(var6);
         if (var7 != null) {
            boolean var8 = var1.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(var7.getId()).isPresent();
            com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var9 = var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var7.getId(), new JsonObject()
            );
            if (var9 != null) {
               JsonObject var10 = var9.provide().getAsJsonObject();
               var10.addProperty("owned", var8);
               var2.add(var10);
            }
         }
      }

      return var2.toString();
   }

   @CallbackJS("updateCosmeticOption")
   public static String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Integer var0, String var1, String var2) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC();
      UUID var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSession().bridge$getProfile().getId();
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var5 = var3.RRHOOOORORHHOOIHRCCHIIHHIIIIOH(
         var0.intValue()
      );
      if (var5 == null) {
         var5 = var3.HHHCHIOIRIORIIORICORCIHCCCROCO()
            .stream()
            .filter(var1x -> var1x.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var0.intValue())
            .findFirst()
            .orElse(null);
      }

      if (var5 == null) {
         return COIHORRCHRRCHOCIRHHRRIOIHRIHCC(var0);
      }

      if (var1.equals(HCIOHCOOICHRHOHCRCCIHCRHORRROR.getId())) {
         var5.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().RHCHRCOCCOIIIHCHRHIRCORHRHRICR(Boolean.parseBoolean(var2));
      } else if (var1.equals(CRCRHIHRHICIOHOHROOIRRCOIHOIHH.getId())) {
         var5.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().IIHRHCCOOHOOOOCHRRCOROOIOHCOOO(Boolean.parseBoolean(var2));
      } else if (var1.equals(OROOIIOCOHRCOHOIIHIOIHCHOCHIOI.getId())) {
         var5.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().IOHHOIIOCRHCHHCRORICCOHOHROOIH(Boolean.parseBoolean(var2));
      } else if (var1.equals(IRICIROHIOCOIROORIRROCCIIICOHC.getId())) {
         var5.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().RORCHCIIICOHIRROOORHOCCCCIOCCI(Boolean.parseBoolean(var2));
      } else if (var1.equals(RIOIHIOCOCCORHOHOOOCOCRRIIOIHC.getId())) {
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().IHIHCOIRIHIRHICORCCHCOOICIIOIC().HIRROCORCHCHRORRHRIHCIHIHCCHIC()) {
            var5.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().CRHROHHHCIHHCOHCOORCRIHHIICROR(Boolean.parseBoolean(var2));
         } else {
            String var7 = com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
               .CCHHHHCICRCCCIOOIOICOOCRCRHCCR()
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("popups", "purchase_lunar_plus");
            IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().IHCHHRRIIIORORCHIICIIOORCOIOIO().CIICCRHHHOHOIOHCHRHOORCICRCORC(var7);
         }
      } else if (var1.equals(HRIROICCHRCOIOOCROCRRHRIIROCHH.getId())) {
         List var13 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HCCICHCRRIICICCHCIRCRRIIRROHHC()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var4, com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.PET
            );
         if (var5.HCHHRIOHCCIORCIIIHOCIICOROOCIO()) {
            com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var8 = (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO)var13.get(
               0
            );
            boolean var9 = var8.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().IHIHRCORCCCOHIIHHRHCCHIOORIHCH();
            if (var13.size() == 1) {
               var8.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(!var9);
            } else {
               com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var10 = (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO)var13.get(
                  1
               );
               if (var9) {
                  var8.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(false);
                  var10.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(true);
               } else {
                  var8.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(true);
                  var10.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(false);
               }

               var10.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5.IHIRCRORCHIOICOROIOHIIOCIHCHRC());
            }
         } else {
            var5.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(Boolean.parseBoolean(var2));
         }
      } else if (CHHHCHIICIIHRCRRCOHHCRIHIROIRI != null && var1.equals(CHHHCHIICIIHRCRRCOHHCRIHIROIRI.getId())) {
         com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var16 = var5.OOICHRIOOOOIOHOIHOIRIRROCHRIOO();
         if (var16 != null
            && IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
               .HCCICHCRRIICICCHCIRCRRIIRROHHC()
               .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var16.ROICHIIIIOCIOCHRCHOIRORIHCCIRI()) instanceof com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var20
            && var20.ROIROOICOCHORORRIOOROCOORRICOR().isPresent()) {
            Range var22 = var20.ROIROOICOCHORORRIOOROCOORRICOR().get();
            var5.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var22));
         }
      } else if (var5.OOICHRIOOOOIOHOIHOIRIRROCHRIOO() instanceof com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var6
         && var6.RIRCHOIHHICCICOHHRROCIROROCHRO().isPresent()) {
         for (com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var19 : var6.RIRCHOIHHICCICOHHRROCIROROCHRO()
            .get()
            .IHCCHHOIHROOCRHRHRIOOHCHRCIRIC()) {
            if (var19.getId().equals(var1)) {
               com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var21 = var19.CRIIHCHHHOHCIOCCCOHRHRRHROHCOC();

               Serializable var11 = switch (var21) {
                  case INT -> Integer.parseInt(var2);
                  case FLOAT -> Float.parseFloat(var2);
                  case BOOLEAN -> Boolean.parseBoolean(var2);
                  default -> var2;
               };
               var5.IHIRCRORCHIOICOROIOHIIOCIHCHRC()
                  .add(
                     var1,
                     com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.getJsonPrimitive(
                        var11
                     )
                  );
               break;
            }
         }
      }

      var5.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5.IHIRCRORCHIOICOROIOHIIOCIHCHRC());
      ORHIOICIOCRRHOOCOHRORIHICHRCRR var12 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().RCRIIICORIICOIIOHIIHICCCOCRICC();
      if (var12.CIIRRCOOCICOCCIRRRRCCCIOIOICIC() != null && var5.HCHHRIOHCCIORCIIIHOCIICOROOCIO()) {
         var12.CIIRRCOOCICOCCIRRRRCCCIOIOICIC().OCICCRCHIOCOCRICCRROOIROOCCHRH().HOHIOHROCHIHROHCRRCHCOIICORICI();
      }

      return HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var5);
   }

   @CallbackJS("sync")
   public static void HOHIOHROCHIHROHCRRCHCOIICORICI() {
      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHHIHROORHHOOCCOOCHRIRHRHCRHIH()
         .COOICHOCCROHOHRORRRROIOHCORIHC()
         .HRIIIOIIRHOHORIRICIOIORRIRCHHO();
      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HCCICHCRRIICICCHCIRCRRIIRROHHC().HOHIOHROCHIHROHCRRCHCOIICORICI();
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH var0 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .RCRIIICORIICOIIOHIIHICCCOCRICC()
         .CIIRRCOOCICOCCIRRRRCCCIOIOICIC();
      if (var0 != null && var0.OCICCRCHIOCOCRICCRROOIROOCCHRH() != null) {
         var0.OCICCRCHIOCOCRICCRROOIROOCCHRH().HOHIOHROCHIHROHCRRCHCOIICORICI();
      }
   }

   @CallbackJS("updateContext")
   public static void HIIRCHIIRCCHHROCOICCCCIHHROROO() {
      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HCCICHCRRIICICCHCIRCRRIIRROHHC().IRCCIIIOCIRCCCROHOHOROORRHOHHI();
   }

   @CallbackJS("requestData")
   public static String COIHORRCHRRCHOCIRHHRRIOIHRIHCC(Integer var0) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC();
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2 = var1.RRHOOOORORHHOOIHRCCHIIHHIIIIOH(
         var0.intValue()
      );
      if (var2 == null) {
         var2 = var1.HHHCHIOIRIORIIORICORCIHCCCROCO()
            .stream()
            .filter(var1x -> var1x.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var0.intValue())
            .findFirst()
            .orElse(null);
      }

      return var2 == null ? "{}" : HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var2);
   }

   private static String HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var0
   ) {
      JsonObject var1 = new JsonObject();
      JsonArray var2 = new JsonArray();
      UUID var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSession().bridge$getProfile().getId();
      boolean var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().IHIHCOIRIHIRHICORCCHCOOICIIOIC().HIRROCORCHCHRORRHRIHCIHIHCCHIC();
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var0, var4);
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var0);
      IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var3, var0);
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var0);
      if (var0.OOICHRIOOOOIOHOIHOIRIRROCHRIOO() instanceof com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var5
         && var5.RIRCHOIHHICCICOHHRROCIROROCHRO().isPresent()) {
         com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var12 = var5.RIRCHOIHHICCICOHHRROCIROROCHRO()
            .get();

         for (com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var8 : var12.IHCCHHOIHROOCRHRHRIOOHCHRCIRIC()) {
            HCHRIROHHHCORIOCROOCHRCIOROOCI var9;
            try {
               var9 = com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.getOption(
                  var0, var8
               );
            } catch (RuntimeException var11) {
               com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.error(
                  "Failed to build cosmetic option " + var8.getId() + " for " + var12.IIIOCHRRICHHOOOHRIOCCHCHCCRIOC(), var11
               );
               continue;
            }

            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var10 = var9.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
               com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRHRCRCCHCICIRIRCIRHRCIHCIRHIO
            );
            if (var10 != null) {
               var2.add(var10.provide());
            }
         }
      }

      var1.add("options", var2);
      var1.add("cosmetic", var0.provide());
      return var1.toString();
   }

   private static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      JsonArray var0, UUID var1, com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2
   ) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HCCICHCRRIICICCHCIRCRRIIRROHHC()
            .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().ROICHIIIIOCIOCHRCHOIRORIHCCIRI()) instanceof com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4
         && var4.ROIROOICOCHORORRIOOROCOORRICOR().isPresent()) {
         float var5 = var2.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().getHatHeightOffset();
         Range var6 = var4.ROIROOICOCHORORRIOOROCOORRICOR().get();
         CHHHCHIICIIHRCRRCOHHCRIHIROIRI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH("cosmeticHeight")
            .RROIIRROOOOHIORHRICHOCHIHCRRCH(0.0F)
            .CRHROHHHCIHHCOHCOORCRIHHIICROR((Float)var6.lowerEndpoint(), (Float)var6.upperEndpoint())
            .IRCIIHHICIHRCOCRROCOICRIHHCCHH(com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.PI_ALIGN_UP_STROKE)
            .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
         CHHHCHIICIIHRCRRCOHHCRIHIROIRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var5);
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var7 = CHHHCHIICIIHRCRRCOHHCRIHIROIRI.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRHRCRCCHCICIRIRCIRHRCIHCIRHIO
         );
         if (var7 != null) {
            var0.add(var7.provide());
         }
      }
   }

   private static float RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var0, Range<Float> var1) {
      float var2;
      try {
         var2 = Float.parseFloat(var0);
      } catch (NumberFormatException var4) {
         return 0.0F;
      }

      return !Float.isFinite(var2)
         ? 0.0F
         : RHRIIOOOCRHIIOORCOCRCHRCCRRCIH.OIHCOHRCICCCRHRCROOCIOIRRHHHIH(var2, (Float)var1.lowerEndpoint(), (Float)var1.upperEndpoint());
   }

   private static void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      JsonArray var0, UUID var1, com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2
   ) {
      if (var2.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCIIIRRHHHHRHRIRHHROIRICHIHROC()
         == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.PET) {
         HRIROICCHRCOIOOCROCRRHRIIROCHH.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(var2.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().IHIHRCORCCCOHIIHHRHCCHIOORIHCH());
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3 = HRIROICCHRCOIOOCROCRRHRIIROCHH.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRHRCRCCHCICIRIRCIRHRCIHCIRHIO
         );
         if (var3 != null) {
            var0.add(var3.provide());
         }
      }
   }

   private static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      JsonArray var0,
      UUID var1,
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2,
      boolean var3
   ) {
      if (var2.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCIIIRRHHHHRHRIRHHROIRICHIHROC()
         == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CLOAK) {
         if (!var3) {
            var2.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().CRHROHHHCIHHCOHCOORCRIHHIICROR(false);
         }

         RIOIHIOCOCCORHOHOOOCOCRRIIOIHC.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(var2.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().OIRCOHHHOOCCRRRIORORIHIHHRIOIH());
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4 = RIOIHIOCOCCORHOHOOOCOCRRIIOIHC.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRHRCRCCHCICIRIRCIRHRCIHCIRHIO
         );
         if (var4 != null) {
            var0.add(var4.provide());
         }
      }
   }

   private static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      JsonArray var0, com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1
   ) {
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = var1.OOICHRIOOOOIOHOIHOIRIRROCHRIOO();
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC()
         .CCOCOIIRIOCICOCRCRRICHOCOCOHHI()
         .get((int)var2.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH());
      com.moonsworth.lunar.client.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC()
         .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3);
      if (var4 != null && var4.RICHIIORICCHROCCRIORORHOOIRIRH() && var4.RHHIRHCIOIORIIRCROOIOIRCIOHIII() != null) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR var5 = var4.RHHIRHCIOIORIIRCROOIOIRCIOHIII()
            .getArmorSlot();
         switch (var5) {
            case FEET:
               HCIOHCOOICHRHOHCRCCIHCRHORRROR.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(var1.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().isShowOverBoots());
               com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var9 = HCIOHCOOICHRHOHCRCCIHCRHORRROR.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
                  com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRHRCRCCHCICIRIRCIRHRCIHCIRHIO
               );
               if (var9 != null) {
                  var0.add(var9.provide());
               }
               break;
            case LEGS:
               CRCRHIHRHICIOHOHROOIRRCOIHOIHH.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(var1.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().isShowOverLeggings());
               com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var8 = CRCRHIHRHICIOHOHROOIRRCOIHOIHH.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
                  com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRHRCRCCHCICIRIRCIRHRCIHCIRHIO
               );
               if (var8 != null) {
                  var0.add(var8.provide());
               }
               break;
            case CHEST:
               OROOIIOCOHRCOHOIIHIOIHCHOCHIOI.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(var1.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().isShowOverChestplate());
               com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var7 = OROOIIOCOHRCOHOIIHIOIHCHOCHIOI.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
                  com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRHRCRCCHCICIRIRCIRHRCIHCIRHIO
               );
               if (var7 != null) {
                  var0.add(var7.provide());
               }
               break;
            case HEAD:
               IRICIROHIOCOIROORIRROCCIIICOHC.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(var1.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().HICHRIIIOOIOCICROICCOICRHCIOOC());
               com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var6 = IRICIROHIOCOIROORIRROCCIIICOHC.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
                  com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRHRCRCCHCICIRIRCIRHRCIHCIRHIO
               );
               if (var6 != null) {
                  var0.add(var6.provide());
               }
         }
      }
   }

   @CallbackJS("markAllAsSeen")
   public static void IRRRRCHHCCIIHCRRRIOHCCICIOHRIH() {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR var0 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC();
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHHIHROORHHOOCCOOCHRIRHRHCRHIH()
         .COOICHOCCROHOHRORRRROIOHCORIHC();
      var0.OHHRCRIOOCIORORHIOHRICRHHORCIH()
         .stream()
         .map(
            com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::RCOCIIHHOIHOOCCCIICCRHHRRCCCCH
         )
         .filter(var1x -> !((LongSet)var1.HHHHHHHHCHOICOICIOIIRICHOOHCRH().get()).contains(var1x))
         .forEach(var1.HHHHHHHHCHOICOICIOIIRICHOOHCRH()::RRRHHIRORHCHHCOOCIHOICORHHCHHO);
      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHHIHROORHHOOCCOOCHRIRHRHCRHIH()
         .COOICHOCCROHOHRORRRROIOHCORIHC()
         .HRIIIOIIRHOHORIRICIOIORRIRCHHO();
      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HCCICHCRRIICICCHCIRCRRIIRROHHC().IRCCIIIOCIRCCCROHOHOROORRHOHHI();
   }

   @CallbackJS("markAsSeen")
   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0) {
      var0.CHOIIRRIHIOOORCORIHCHCCCRIHHIR()
         .forEach(
            var0x -> IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
               .HHHIHROORHHOOCCOOCHRIRHRHCRHIH()
               .COOICHOCCROHOHRORRRROIOHCORIHC()
               .HHHHHHHHCHOICOICIOIIRICHOOHCRH()
               .RRRHHIRORHCHHCOOCIHOICORHHCHHO(var0x)
         );
      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHHIHROORHHOOCCOOCHRIRHRHCRHIH()
         .COOICHOCCROHOHRORRRROIOHCORIHC()
         .HRIIIOIIRHOHORIRICIOIORRIRCHHO();
      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HCCICHCRRIICICCHCIRCRRIIRROHHC().IRCCIIIOCIRCCCROHOHOROORRHOHHI();
   }

   @CallbackJS("unequipAll")
   public static void RCHOOIIHCIHOCOIHOCOIICIHCCRIHI() {
      Optional.ofNullable(IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().RCRIIICORIICOIIOHIIHICCCOCRICC().CIIRRCOOCICOCCIRRRRCCCIOIOICIC())
         .ifPresent(
            var0 -> {
               com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = var0.OCICCRCHIOCOCRICCRROOIROOCCHRH();
               var1.ROIOCHICROROCCOOHIIIIORCCIRHRO().clear();
               var1.HOHIOHROCHIHROHCRRCHCOIICORICI();
               IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                  .IOHRIRCHOCIOIOIHIHOCCCHOHOHOCH()
                  .ORHIOICIOCRRHOOCOHRORIHICHRCRR(IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH());
            }
         );
   }

   private static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0,
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      if (var0.RCIIIRRHHHHRHRIRHHROIRICHIHROC() != var1.RCIIIRRHHHHRHRIRHHROIRICHIHROC()) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .IHCHHRRIIIORORCHIICIIOORCOIOIO()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR.WARNING,
               var1.getName() + " was unequipped as it is incompatible with " + var0.getName()
            );
      }
   }

   @CallbackJS("showCosmeticLocker")
   public static void RICORROHROIROIHOORRHRCCCCIRHHC() {
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OIOOICHIIHICCRCOOIOIOCIRRIIIRC();
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROCOCHICHORROOHCHOCIIICOHCHIOC()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.COHIRIHOOCIOHORROCCRCIHHROOOIR,
            new com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.COSMETICS,
               null,
               false
            )
         );
   }

   @CallbackJS("toggleCosmetic")
   public static void IOIIROROOICRCHCOHHIIHRCRIOIOOH(int var0) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC();
      Optional.ofNullable(IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().RCRIIICORIICOIIOHIIHICCCOCRICC().CIIRRCOOCICOCCIRRRRCCCIOIOICIC())
         .ifPresent(
            var2 -> {
               com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var2.OCICCRCHIOCOCRICCRROOIROOCCHRH();
               com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 = var3.ROIOCHICROROCCOOHIIIIORCCIRHRO()
                  .stream()
                  .filter(var1xx -> var1xx.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var0)
                  .findFirst()
                  .orElse(null);
               if (var4 == null) {
                  com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = var1.HRCCOIRIHRCRHCHIRICIHCRRIOICCR()
                     .get((long)var0);
                  if (var5 != null) {
                     var4 = new com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO(
                        var5, new JsonObject()
                     );
                  }
               }

               if (var4 != null) {
                  RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var3.ROIOCHICROROCCOOHIIIIORCCIRHRO(), true);
                  var3.HOHIOHROCHIHROHCRRCHCOIICORICI();
                  if (var4.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCIIIRRHHHHRHRIRHHROIRICHIHROC()
                        == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.COMPANION
                     && IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH() != null) {
                     IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                        .IOHRIRCHOCIOIOIHIHOCCCHOHOHOCH()
                        .ORHIOICIOCRRHOOCOHRORIHICHRCRR(IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH());
                  }
               }
            }
         );
   }

   @CallbackJS("previewCosmetics")
   public static String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0, boolean var1) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC();
      if (var0 == null) {
         return "{}";
      }

      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var3 = com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var0.OCORCRRRCOHHHHHROCOOHICOIORHRI.id(),
            var0.OCORCRRRCOHHHHHROCOOHICOIORHRI.RRRHORHHRHRHIRCRIOIIIROOCCICRO() == null
               ? new JsonObject()
               : var0.OCORCRRRCOHHHHHROCOOHICOIORHRI.RRRHORHHRHRHIRCRIOIIIROOCCICRO()
         );
      if (var3 == null) {
         return "{}";
      }

      ArrayList var4 = new ArrayList<>(
         Arrays.stream(var0.CICHICOIHICRCIRCICHIRRRIIRRIOR)
            .map(
               var1x -> {
                  com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2x = null;

                  for (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4x : var2.OHHRCRIOOCIORORHIOHRICRHHORCIH()) {
                     if (var4x.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var1x.id()) {
                        var2x = var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           var1x.id(), var1x.RRRHORHHRHRHIRCRIOIIIROOCCICRO() == null ? new JsonObject() : var1x.RRRHORHHRHRHIRCRIOIIIROOCCICRO()
                        );
                        break;
                     }
                  }

                  return var2x;
               }
            )
            .filter(Objects::nonNull)
            .toList()
      );
      ArrayList var5 = new ArrayList(var4);
      if (!var5.contains(var3)) {
         var5.add(var3);
      }

      List var6 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, var4, false);
      var6.removeIf(var1x -> {
         for (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var3x : var4) {
            if (var3x.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var1x.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH()) {
               return false;
            }
         }

         return true;
      });
      var6.removeIf(var1x -> var1x.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var3.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH());
      List var7 = COCCRCRCRHROIRCCHOHRICCCIOCICI(var6);
      List var8 = var6.stream()
         .map(
            com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::RCOCIIHHOIHOOCCCIICCRHHRRCCCCH
         )
         .toList();
      var4.removeIf(var1x -> var8.contains(var1x.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH()));
      var4.add(var3);
      var7.removeIf(
         var1x -> var1x.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCIIIRRHHHHRHRIRHHROIRICHIHROC()
            == var3.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCIIIRRHHHHRHRIRHHROIRICHIHROC()
      );
      JsonObject var9 = new JsonObject();
      JsonArray var10 = new JsonArray();

      for (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var12 : var1 ? var7 : var4) {
         JsonObject var13 = new JsonObject();
         var13.addProperty("id", var12.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH());
         var13.addProperty("name", var12.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().getName());
         var13.addProperty("type", var12.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCIIIRRHHHHRHRIRHHROIRICHIHROC().getDisplayName());
         var12.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().IRCIIHHICIHRCOCRROCOICRIHHCCHH(var12.IHIRCRORCHIOICOROIOHIIOCIHCHRC());
         var13.add("metadata", var12.IHIRCRORCHIOICOROIOHIIOCIHCHRC());
         var10.add(var13);
      }

      var9.add("cosmetics", var10);
      return var9.toString();
   }

   @CallbackJS("setCosmeticFavorite")
   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Integer var0, Boolean var1) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC();
      if (var1 && var2.CCCOHOCOICIHROHIICIRCRICORCHCR().add(var0)) {
         com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
            .RCOIHOICHRIIHOCCCIHRRHHRROORCR()
            .RRICCCRROHRIHHIOCIRCOCCIRHHIIO()
            .favoriteCosmetic(null, FavoriteCosmeticRequest.newBuilder().setCosmeticId(var0).build(), var0x -> {});
      } else if (!var1 && var2.CCCOHOCOICIHROHIICIRCRICORCHCR().remove(var0)) {
         com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
            .RCOIHOICHRIIHOCCCIHRRHHRROORCR()
            .RRICCCRROHRIHHIOCIRCOCCIRHHIIO()
            .unfavoriteCosmetic(null, UnfavoriteCosmeticRequest.newBuilder().setCosmeticId(var0).build(), var0x -> {});
      }

      var2.IRCCIIIOCIRCCCROHOHOROORRHOHHI();
   }

   private static List<com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO> COCCRCRCRHROIRCCHOHRICCCIOCICI(
      List<com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> var0
   ) {
      ArrayList var1 = new ArrayList();

      for (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 : var0) {
         for (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 : IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HCCICHCRRIICICCHCIRCRRIIRROHHC()
            .OHHRCRIOOCIORORHIOHRICRHHORCIH()) {
            if (var5.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var3.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH()) {
               var1.add(
                  new com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO(
                     var5, new JsonObject()
                  )
               );
               break;
            }
         }
      }

      return var1;
   }

   private static List<com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var0,
      List<com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO> var1,
      boolean var2
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HCCICHCRRIICICCHCIRCRRIIRROHHC();
      com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = var0.OOICHRIOOOOIOHOIHOIRIRROCHRIOO();
      ArrayList var5 = new ArrayList();
      boolean var6 = var4.HOOORHCOICHHOHOORROICHHHORRHHH() > 0L && var4.HOOORHCOICHHOHOORROICHHHORRHHH() < System.currentTimeMillis();
      ArrayList var7 = new ArrayList(var1);
      boolean var8 = var1.stream()
         .anyMatch(var1x -> var1x.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var4.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH());
      if (var8 && var2) {
         var5.add(var4);
      } else if (!var6) {
         if (var4 instanceof com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var9
            && var9.RIRCHOIHHICCICOHHRROCIROROCHRO().isPresent()) {
            String var10 = var9.RIRCHOIHHICCICOHHRROCIROROCHRO().get().CICCORCRROHRCIHHCICCHOCOCOIRCI();
            Map var11 = var3.HRCCOIRIHRCRHCHIRICIHCRRIOICCR();
            IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
               .RHCHCCIOOCORHOHICHOIOHRIOCCIHC()
               .IHRRCOCOIIIIICRHRRICIOCRCIRHCO(var10)
               .ifPresent(
                  var2x -> var2x.OCORIIIOCOCORORIRRCCROCOOHOIOR()
                     .forEach(
                        var2xx -> {
                           com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3x = (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var11.get(
                              var2xx
                           );
                           if (var3x != null) {
                              var5.add(var3x);
                           }
                        }
                     )
               );
         }

         var7.forEach(
            var2x -> {
               com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3x = var2x.OOICHRIOOOOIOHOIHOIRIRROCHRIOO();
               if (var3x instanceof com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var4x
                  && var4x.RIRCHOIHHICCICOHHRROCIROROCHRO().isPresent()) {
                  String var5x = var4x.RIRCHOIHHICCICOHHRROCIROROCHRO().get().CICCORCRROHRCIHHCICCHOCOCOIRCI();
                  IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                     .RHCHCCIOOCORHOHICHOIOHRIOCCIHC()
                     .IHRRCOCOIIIIICRHRRICIOCRCIRHCO(var5x)
                     .ifPresent(var3xx -> var3xx.OCORIIIOCOCORORIRRCCROCOOHOIOR().forEach(var3xxx -> {
                        if (var3xxx == var4.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH()) {
                           var5.add(var3x);
                        }
                     }));
               }
            }
         );

         for (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var17 : var7) {
            com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var21 = var17.OOICHRIOOOOIOHOIHOIRIRROCHRIOO();
            if (var21 != var4) {
               if (var21.RCIIIRRHHHHRHRIRHHROIRICHIHROC().getRenderAs()
                     == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HAT
                  && var4.RCIIIRRHHHHRHRIRHHROIRICHIHROC().getRenderAs()
                     == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HAT) {
                  com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var24 = var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var4.ROICHIIIIOCIOCHRCHOIRORIHCCIRI()
                  );
                  com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var26 = var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var21.ROICHIIIIOCIOCHRCHOIRORIHCCIRI()
                  );
                  if (var24 == null
                     || var26 == null
                     || !var24.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var26, var21, var4) && !var26.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var24, var21, var4)) {
                     var5.add(var21);
                  }
               } else if (var21.RCIIIRRHHHHRHRIRHHROIRICHIHROC()
                     == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.BACKPACK
                  && var4.RCIIIRRHHHHRHRIRHHROIRICHIHROC()
                     == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CLOAK) {
                  var5.add(var21);
               } else if (var21.RCIIIRRHHHHRHRIRHHROIRICHIHROC()
                     == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CLOAK
                  && var4.RCIIIRRHHHHRHRIRHHROIRICHIHROC()
                     == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.BACKPACK) {
                  var5.add(var21);
               } else if (var21.RCIIIRRHHHHRHRIRHHROIRICHIHROC() == var4.RCIIIRRHHHHRHRIRHHROIRICHIHROC()) {
                  List var12 = var1.stream()
                     .filter(
                        var0x -> var0x.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCIIIRRHHHHRHRIRHHROIRICHIHROC()
                           == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.PET
                     )
                     .toList();
                  boolean var13 = var1.stream()
                     .anyMatch(var1x -> var1x.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var21.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH());
                  if ((
                        var21.RCIIIRRHHHHRHRIRHHROIRICHIHROC()
                              != com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.PET
                           || var12.size() != 1
                           || !var13
                     )
                     && (
                        !var21.RCIIIRRHHHHRHRIRHHROIRICHIHROC().isHeldItemCosmetic()
                           || var21.CIIRCIOCIROICHOOIOHCCHIHORICCH() == var4.CIIRCIOCIROICHOOIOHCCHIHORICCH()
                     )) {
                     var5.add(var21);
                  }
               }
            }
         }

         if (var2) {
            var1.add(var0);
            if (var4 instanceof com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var15
               && var15.RIRCHOIHHICCICOHHRROCIROROCHRO().isPresent()) {
               for (com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var25 : var15.RIRCHOIHHICCICOHHRROCIROROCHRO()
                  .get()
                  .IHCCHHOIHROOCRHRHRIOOHCHRCIRIC()) {
                  if (!var0.IHIRCRORCHIOICOROIOHIIOCIHCHRC().has(var25.getId())) {
                     var0.IHIRCRORCHIOICOROIOHIIOCIHCHRC()
                        .add(
                           var25.getId(),
                           com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.getJsonPrimitive(
                              var25.getDefaultValue()
                           )
                        );
                  }
               }
            }
         }

         ArrayList var16 = new ArrayList();

         for (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var23 : var7) {
            if (var23.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCIIIRRHHHHRHRIRHHROIRICHIHROC()
               == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.PET) {
               var16.add(var23);
            }
         }

         if (var4.RCIIIRRHHHHRHRIRHHROIRICHIHROC()
               == com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.PET
            && var16.size() == 1) {
            com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var20 = (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO)var16.get(
               0
            );
            var0.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(!var20.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().IHIHRCORCCCOHIIHHRHCCHIOORIHCH());
            var0.OICIHICHOHCIHIHIHHIRHIIRIHRCRR().IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0.IHIRCRORCHIOICOROIOHIIOCIHCHRC());
         }
      }

      if (var2) {
         var5.forEach(
            var2x -> {
               if (var1.stream()
                  .anyMatch(var1xx -> var1xx.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var2x.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH())) {
                  RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var2x);
               }

               var1.removeIf(var1xx -> var1xx.OOICHRIOOOOIOHOIHOIRIRROCHRIOO().RCOCIIHHOIHOOCCCIICCRHHRRCCCCH() == var2x.RCOCIIHHOIHOOCCCIICCRHHRRCCCCH());
            }
         );
      }

      return var5;
   }

   public record IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
      @SerializedName("seen")
      private final List<Long> CHCRRHIHRHHRCCRHHHROCCHRHCHOCI;

      public IRCIIHHICIHRCOCRROCOICRIHHCCHH(List<Long> var1) {
         this.CHCRRHIHRHHRCCRHHHROCCHRHCHOCI = var1;
      }

      @SerializedName("seen")
      public List<Long> CHOIIRRIHIOOORCORIHCHCCCRIHHIR() {
         return this.CHCRRHIHRHHRCCRHHHROCCHRHCHOCI;
      }
   }

   public record RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      @SerializedName("active")
      private final com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH[] CICHICOIHICRCIRCICHIRRRIIRRIOR;
      @SerializedName("preview")
      private final com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OCORCRRRCOHHHHHROCOOHICOIORHRI;

      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH[] var1,
         com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
      ) {
         this.CICHICOIHICRCIRCICHIRRRIIRRIOR = var1;
         this.OCORCRRRCOHHHHHROCOOHICOIORHRI = var2;
      }

      @SerializedName("active")
      public com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH[] RRICRRIOIIOCOCORROCHIHIOIRHRHO() {
         return this.CICHICOIHICRCIRCICHIRRRIIRRIOR;
      }

      @SerializedName("preview")
      public com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HOIOHCCROHHOCOIIROCRHIOCRIIOOO() {
         return this.OCORCRRRCOHHHHHROCOOHICOIORHRI;
      }
   }
}
