package com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import java.nio.file.Path;
import java.util.List;

public interface OOROOCCIRCCRHOIOIORIHCHHOOCCOR {
   default void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
   }

   default void IIIIRHIHROIRCROHHROIHIIHRCRRHO(int var1, int var2) {
   }

   default void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      int var2,
      int var3,
      int var4,
      int var5
   ) {
   }

   default void RCIROOOOICRHCCRRCIORHHIRCOIIIC(int var1, int var2, int var3) {
   }

   default void RRCRRCORICCHOHHIRCHIROOHIIOHCO(double var1, double var3) {
   }

   default void ROIOROHRIHRRHIHRRRIHHHIICCHIOI(List<Path> var1) {
   }

   default void onClose() {
   }

   default void HCRCORICHHICIRIHORRRHHOROOHROC() {
   }
}
