package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;

import java.util.Map;
import lombok.Generated;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private String[] OCOIOOHHHCOHCHCIRCOOIRORRRCCIC;
   private Map<String, RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> IIORHOCIOCCROROOHRIIRIRCRIHHCC;

   @Generated
   public String[] getValues() {
      return this.OCOIOOHHHCOHCHCIRCOOIRORRRCCIC;
   }

   @Generated
   public Map<String, RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> IOICCORIRIHIHOCRORIIIRRIOCCRIO() {
      return this.IIORHOCIOCCROROOHRIIRIRCRIHHCC;
   }

   @Generated
   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String[] var1, Map<String, RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> var2) {
      this.OCOIOOHHHCOHCHCIRCOOIRORRRCCIC = var1;
      this.IIORHOCIOCCROROOHRIIRIRCRIHHCC = var2;
   }
}
