package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOOOCCOOOHCHCIIHOIHCRIIOOROHRC;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IIIIRHIHROIRCROHHROIHIIHRCRRHO;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import org.apache.commons.lang3.text.WordUtils;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final HashMap<String, Class<CRRRICCRROCOHHOHIICIHORCOORRRH>> RHRRHOOHHIHCHROCIHHHHRIOOHOOHH = new HashMap<>();
   private final HashMap<String, String> OHIHHICHHIROCRCHHCIIIOOIIIOOIR = new HashMap<>();
   private final IHIRRIIORRHORHRORIHOROIRCORCOO RRCHHOCOIORORHIIROIHHIRCIOOIIH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH("playerSize")
      .RROIIRROOOOHIORHRICHOCHIHCRRCH(1.0F)
      .CRHROHHHCIHHCOHCOORCRIHHIICROR(0.5F, 1.0F)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final IHIRRIIORRHORHRORIHOROIRCORCOO CHHOHIHIRRHCRCCRORHIORIHOOCCRH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH(
         "otherPlayerSize"
      )
      .RROIIRROOOOHIORHRICHOCHIHCRRCH(1.0F)
      .CRHROHHHCIHHCOHCOORCRIHHIICROR(0.5F, 1.0F)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RCRHHRCCCHHRCCRROHICHCOCCCOROO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("changeNpcSize")
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HCICIRHOROHIIROICCRCRRIRIOIOOO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "playerSizeSkyblockOnly"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HashMap<Class<CRRRICCRROCOHHOHIICIHORCOORRRH>, IHIRRIIORRHORHRORIHOROIRCORCOO> HCCOOHIIHCIRHCIORHCOHOIHIICOOR = new HashMap<>();

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      super(false);
      this.handle(CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.CIOROOHRIOHIOORIIORRIIOHHHOROH();
      this.OHIHHICHHIROCRCHHCIIIOOIIIOOIR.put("Entity Horse", "Horse");
      this.OHIHHICHHIROCRCHHCIIIOOIIIOOIR.put("Ozelot", "Ocelot");
      this.OHIHHICHHIROCRCHHCIIIOOIIIOOIR.put("Lava Slime", "Magma Cube");
      this.OHIHHICHHIROCRCHHCIIIOOIIIOOIR.put("Wither Boss", "Wither");
      this.OHIHHICHHIROCRCHHCIIIOOIIIOOIR.put("Villager Golem", "Iron Golem");
      this.OHIHHICHHIROCRCHHCIIIOOIIIOOIR.put("Pig Zombie", "Zombie Pigman");
      this.OHIHHICHHIROCRCHHCIIIOOIIIOOIR.put("Creaking Transient", "Creaking");
      this.OHIHHICHHIROCRCHHCIIIOOIIIOOIR.put("Mushroom Cow", "Mooshroom");
   }

   private void CIOROOHRIOHIOORIIORRIIOHHHOROH() {
      Map var1 = IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRHHRCHIRRCHICHIORIICHRCHOCHR().OCOCRRIRIORIROOICHRIROHOIHIOHH();

      for (Entry var3 : var1.entrySet()) {
         String var4 = (String)var3.getKey();
         Class var5 = (Class)var3.getValue();
         if (!var4.equals("Mob")
            && !HHCCIRHCCCIIRHCROHIORHIRHHIORH.class.isAssignableFrom(var5)
            && com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR.class.isAssignableFrom(var5)) {
            this.RHRRHOOHHIHCHROCIHHHHRIOOHOOHH.put(var4, var5);
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1) {
      if (!this.HCICIRHOROHIIROICCRCRRIRIOIOOO.get() || OCOHORHCROHICRRIHCIHHRRCIHICRI.RRRCCHIOCICOIOIRRCOOIRHHCORCIH()) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR var2 = var1.RRIIHHICRHRIIICCIOHCROIIIRIROR();
         if (var2 instanceof HHCCIRHCCCIIRHCROHIORHIRHHIORH var3) {
            if (var3.IHHRIHOOOHHHROCIHOCCRHIIIIOHRH()) {
               return;
            }

            if (!this.RCRHHRCCCHHRCCRROHICHCOCCCOROO.get()
               && IIIIRHIHROIRCROHHROIHIIHRCRRHO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  var3,
                  com.moonsworth.lunar.client.HCHRIROHHHCORIOCROOCHRCIOROOCI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                     com.moonsworth.lunar.client.HCHRIROHHHCORIOCROOCHRCIOROOCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HYPIXEL
                  )
               )) {
               return;
            }

            float var4 = var3.bridge$isSelf() ? this.RRCHHOCOIORORHIIROIHHIRCIOOIIH.get() : this.CHHOHIHIRRHCRCCRORHIORIHOOCCRH.get();
            var1.OHIIIOHIRIRCCRRIOIICCHHIORRHOH(var4);
         } else {
            Class var6 = var2.getClass();
            IHIRRIIORRHORHRORIHOROIRCORCOO var5 = this.HCCOOHIIHCIRHCIORHCOHOIHIICOOR.get(var6);
            if (var5 == null) {
               return;
            }

            var1.OHIIIOHIRIRCCRRIOIICCHHIORRHOH(var5.get());
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IRCRRHRCIRHIHIHROHCRRHIIHHHHCH var1) {
      if (!this.HCICIRHOROHIIROICCRCRRIRIOIOOO.get() || OCOHORHCROHICRRIHCIHHRRCIHICRI.RRRCCHIOCICOIOIRRCOOIRHHCORCIH()) {
         RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2 = var1.CCCHCRRRIRRHICOOIOCHCHRCRICHOC();
         double var3 = var1.getY();
         double var5 = var2.bridge$getHeight();
         var1.setY(var3 - var5 * (1.0F - var2.bridge$getLunarScale()));
      }
   }

   @Override
   public String getId() {
      return "MOB_SIZE";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.GENERAL,
         var1x -> var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HCICIRHOROHIIROICCRCRRIRIOIOOO).HRICOCOIOCCCICCIORHIIIIOROCOHC(1)
      );
      var1.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
         "playerOptions",
         var1x -> var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(
            this.RRCHHOCOIORORHIIROIHHIRCIOOIIH, this.CHHOHIHIRRHCRCCRORHIORIHOOCCRH, this.RCRHHRCCCHHRCCRROHICHCOCCCOROO
         )
      );
      var1.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
         "mobOptions",
         var1x -> {
            ArrayList var2 = new ArrayList();

            for (Entry var4 : this.RHRRHOOHHIHCHROCIHHHHRIOOHOOHH.entrySet()) {
               String var5 = (String)var4.getKey();
               Class var6 = (Class)var4.getValue();
               IHIRRIIORRHORHRORIHOROIRCORCOO var7 = IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH(this.RCHHCIOCRICRORCCOIOIOIHROHCRCH(var5))
                  .RROIIRROOOOHIORHRICHOCHIHCRRCH(1.0F)
                  .CRHROHHHCIHHCOHCOORCRIHHIICROR(0.5F, 1.0F)
                  .COOCHIHCIHRRIRCCIRHRIOHOCORCRR()
                  .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
               var7.IIOCHOIICCIORCOROIROHICCHIOHIC(
                  var1xx -> {
                     if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 8) {
                        RRCRRCORICCHOHHIRCHIROOHIIOHCO var2x = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
                        com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                           .HRRCCIHOOORRIHCCRORRCRHRIICRRH();
                        if (var2x != null && var3.IROHHROORRIHROCOCHCRCHRORRHOOI()) {
                           com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4x = var3.IOOCOICIHOHOIOOCOIRRHCHOCRRORC();
                           var2x.bridge$getEntities().forEach(var2xx -> {
                              if (var6.isInstance(var2xx)) {
                                 var4x.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var2xx.HOCRIORCCCIHIIHHHORIHOOCHOCORH(), false);
                              }
                           });
                        }
                     }
                  }
               );
               this.HCCOOHIIHCIRHCIORHCOHOIHIICOOR.put(var6, var7);
               var2.add(var7);
            }

            var2.sort(Comparator.comparing(HCHRIROHHHCORIOCROOCHRCIOROOCI::getId));
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(var2.toArray(new HCHRIROHHHCORIOCROOCHRCIOROOCI[0]));
         }
      );
   }

   private String RCHHCIOCRICRORCCOIOIOIHROHCRCH(String var1) {
      String var2;
      if (Character.isUpperCase(var1.charAt(0))) {
         var2 = var1.replaceAll("(.)([A-Z])", "$1 $2");
      } else {
         var2 = WordUtils.capitalizeFully(var1.replace('_', ' '));
      }

      return this.OHIHHICHHIROCRCHHCIIIOOIIIOOIR.getOrDefault(var2, var2) + " Size";
   }
}
