package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

@Deprecated
public class OCOHORHCROHICRRIHCIHHRRCIHICRI extends IIHRRHORCRCROCHHOHORCHCROCIHRO {
   public static final OCOHORHCROHICRRIHCIHHRRCIHICRI CHHOHOHCHORCROCCOCIIOIOHCRROIC = new OCOHORHCROHICRRIHCIHHRRCIHICRI();

   private OCOHORHCROHICRRIHCIHHRRCIHICRI() {
   }
}
