package com.moonsworth.lunar.client;

import com.google.common.collect.ImmutableSet;
import com.google.common.collect.ImmutableSet.Builder;
import com.lunarclient.common.v1.LauncherVersion;
import com.lunarclient.common.v1.LunarClientUiVersion;
import com.lunarclient.common.v1.LunarClientVersion;
import com.lunarclient.common.v1.MinecraftVersion;
import com.lunarclient.common.v1.PlayerModpack;
import com.lunarclient.common.v1.UuidAndUsername;
import com.lunarclient.websocket.analytics.v1.RecordEnabledModsRequest;
import com.lunarclient.websocket.handshake.v1.GameHandshake;
import com.lunarclient.websocket.handshake.v1.Handshake;
import com.lunarclient.websocket.handshake.v1.InstalledMod;
import com.lunarclient.websocket.handshake.v1.MinecraftIdentity;
import com.lunarclient.websocket.heartbeat.v1.GameHeartbeatRequest;
import com.lunarclient.websocket.language.v1.Language;
import com.moonsworth.lunar.client.HCHRIROHHHCORIOCROOCHRCIOROOCI.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CCIHHRIOOOOCOHRCIHOHROOICIORCC;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HCHRIROHHHCORIOCROOCHRCIOROOCI;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHRIICOIOORCHCOIICOOIHIRHHICRI;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.ICICIOCHHHIHOCHCOHORIHRCOHHOCR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IHCRORHRORIICHRHRCHRRIRRHHOCOO;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IHICORCROOROHCIHIHCOIHRRHICICO;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IIHRRHORCRCROCHHOHORCHCROCIHRO;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IOHIHIIHCCCCCIHRORIOIOORCIOHII;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OHIIIOHIRIRCCRRIOIICCHHIORRHOH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OOCCRCRCOHIIORCCORCRCIRRROIOOR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RICRIRRCOHRCOCRRHHCRHRROOIOHHR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH;
import com.moonsworth.lunar.client.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;
import com.moonsworth.lunar.client.util.CCHORHIOORICCIRIHRIIHIICORIORO;
import com.moonsworth.lunar.client.util.COIHORRCHRRCHOCIRHHRRIOIHRIHCC;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IRRCHICCRHCHRRCHIOHIIRIORIRHRI;
import com.moonsworth.lunar.client.util.OCIOROHIHRROROOIRRHRRCCHHRRRHI;
import com.moonsworth.lunar.client.util.ORCOCORROHIROCCIORORRRRCHIOOCH;
import com.moonsworth.lunar.client.util.RIHOOCIHRICOCHRHCOOCCOIHOCHRCR;
import com.moonsworth.lunar.ichor.api.IchorAPI;
import io.netty.util.concurrent.DefaultThreadFactory;
import io.sentry.Breadcrumb;
import io.sentry.Sentry;
import io.sentry.SentryLevel;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;
import java.util.stream.Collectors;
import lombok.Generated;
import mchorse.emoticons.Emoticons;
import org.apache.commons.io.FileUtils;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private static RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OHRIIRHRIHOCCHORCORHICIOHHHOIC;
   public static final ExecutorService RCIORCRHCIOIHCOCORCIHIOROCOOCR = Executors.newCachedThreadPool(new DefaultThreadFactory("lunar-executor-thread"));
   private IRCIIHHICIHRCOCRROCOICRIHHCCHH COOHOHRHHICRHIORRORHIOOIIHRHHI;
   private final com.moonsworth.lunar.client.IOIICIRIICICIIOORHCIIIIRRIHRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IOOHIHOOOCICOHHCHHOHHRCOHIOHRC;
   private final CRRRICCRROCOHHOHIICIHORCOORRRH OHOOOOOIHOIROIHIRCIOCIRHIIRIOR;
   private final HCHRIROHHHCORIOCROOCHRCIOROOCI CRHOICICCRIHHRRRICIHIIROCRROOR;
   private com.moonsworth.lunar.client.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CCIOHRRCIROCHOORCRCRHRORIOOOOO;
   private com.moonsworth.lunar.client.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ORRIOOIROHHROIRCIIHIOOCIOOIIOO;
   private boolean OCCHIHRHRHIROIOCOCICRRRHIORRRH = false;
   private String world = "";
   private RRCRRCORICCHOHHIRCHIROOHIIOHCO IRCCRRIOIROIORCOICRROIOOCIOOCH;
   private final Set<RIOOCHICIHRHOHCCCCCHOCCCOHCRHI> OROHIHCCRHRHOOHIOHHOICHIOHIOCO;
   private final IHIRRIIORRHORHRORIHOROIRCORCOO RIRRCRRIHRORROIOOHIHIOCRIROOHC;
   private final HHRIICOIOORCHCOIICOOIHIRHHICRI ROHIICRIRROCRHRHOOHORCIRHOIOII;
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI HROORRHRIICCHICHORHOHCCORICIIH;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CCIOHCIIORCIOIHHCOHHIHIHCHOCRC;
   private final OHIIIOHIRIRCCRRIOIICCHHIORRHOH HRHHOCIORIIRRHIOORIORHOIHHROOH;
   private final IIHRRHORCRCROCHHOHORCHCROCIHRO OCHRCCCICRIOCRCOORCIRCHRIHOIRO;
   private final OOCCRCRCOHIIORCCORCRCIRRROIOOR HRIOCRHIOOHOHOCRCROIIRORHICICC;
   private final com.moonsworth.lunar.client.ICICIOCHHHIHOCHCOHORIHRCOHHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CCCIOOHOCOCHCRIRHIIORCRIOOIRHO;
   private final IIHRHCCOOHOOOOCHRRCOROOIOHCOOO OHIROHHCCHRIIORCHRCOIICOHOOCOO;
   private final OCOHORHCROHICRRIHCIHHRRCIHICRI HROHRRCRRHOIRHIRICOOROHRRRORIH;
   private final IHHCHHHCRIHOOCOIOOCRIIICIOROIR IOHOCCRORRHOHRROHCIHIIROIHRHOO;
   private final IIRHCHHOICHRICOOCRORCCIOOIHOIR CHIOCHOIHHHCHOIHHIIHIOHCRHRIII;
   private final OOROOCCIRCCRHOIOIORIHCHHOOCCOR OIORROROOROHHRIIORIHHHOCIIHRRC;
   private final CORCOCICIRIOHROHROIIOOHICCHCRR RHHROIIIHCCIHOCOCOHCHIHIOOIRIO;
   private final RIROICHCRROROHCCROOCCCCOCHCCRI OCIRIHHHIICCRCHICCCHHHHIOHCHHH;
   private final ORHIOICIOCRRHOOCOHRORIHICHRCRR RCIICOICCOIOCCCHCOOCCRHRIHOOHI;
   private final CRICCOOHHHCHOORCICOCOHIHOIRHOO IROHORIIHOCCORRIHICCROIHRRIRCI;
   private final RHOCHHIRRCHHHOHOIRROIROHHHIHIO HOHIROROCHIROOCCROHOCOORCHCORC;
   private final IOIICIRIICICIIOORHCIIIIRRIHRHI CIIHCIOHIICOOOOIIOIRCICRRICCOH;
   private final ICICIOCHHHIHOCHCOHORIHRCOHHOCR CRHHOHCOORHRIIRCHCHCORIIORCOHC;
   private final CRHROHHHCIHHCOHCOORCRIHHIICROR HORCOHHRCCOICRCIOHHRRHHCRHCCOR;
   private final HHCCIRHCCCIIRHCROHIORHIRHHIORH OCCCOHHOICRHORIICHHRCCCRHOOCII;
   private final ROOCOCCCIRHHHIRIOIHHHHRHIICHHR OOIOOICRHHHIICOHOHCOHCRRRCRCHH;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI RRICCCRROHRIHHIOCIRCOCCIRHHIIO;
   private final RICRIRRCOHRCOCRRHHCRHRROOIOHHR CRHOICIHHOCICHICICRRORHOHRIROH;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO HRCHHIRIHROOIHHRCHICORRROHRCRR;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH RRIOIROCRCCCCROHHCRHOOROOHRROI;
   private final IRRCCOICORICIHCHRHIHIHROIRHOCR ORRHICRCROIRCICRCCIRRIRHCRICRI;
   private final com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.IRCIIHHICIHRCOCRROCOICRIHHCCHH ICRIIOCRRORIOIIRORHORIOHHCCOCO;
   private final com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR HCRCHOCOIOIIIRRCOIOORIHHRIIROO;
   private final RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO HRHIRCRROIHRIOHCOOCCHIHCCROHRR;
   private final IRCRRHRCIRHIHIHROHCRRHIIHHHHCH OIRHCCHIOOIIIOIRCHCOHOHOIOCIOC;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IOHCCHCCHHRRRICOCRHHIRICCCCOOO;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH RICIRORIRHHIHIICHOHROROHRIIOOR;
   private final com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI HHHROIRRRRCHCHROHCORIIOHOIIOCC;
   private final RIRHOCHIORCCIIOIIRHOCCCRHHCHHH IRROIHHOOHCIOHICHHROOOCOCHCCOI;
   private final com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IOIOORHICOIOOHCRIIROHCIROICCCO;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH OHORCIHORHOCIRIIIRCCRHRCOCCHCH;
   private final IHICORCROOROHCIHIHCOIHRRHICICO HIRROHCROOOIRHOOCRIRRORORIIRCI;
   private final OIHCOHRCICCCRHRCROOCIOIRRHHHIH CRHHIRIIHRRIRCOHRIORHORCOCIHHI;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OCOHORHCROHICRRIHCIHHRRCIHICRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR ICRIHROIRHIHOCOOCRCHCHRRCHOHHC;
   private final com.moonsworth.lunar.client.OCOHORHCROHICRRIHCIHHRRCIHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH RCRCORCICHOIHRHRCICOCCIRHIHICR;
   private final IHCRORHRORIICHRHRCHRRIRRHHOCOO CIRORIOCCCICOHIHRICOHOCIICIOIH;
   private final HICRRICCHCCROOHHCHOCOCCHOIHHOC HCORIRRICOOCHCORIIIROIOCHOCCCR;
   private final com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH HHOHOCIOHIHHCCOCIOROCIHRORCIHI;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ROOCHOCCIHCIIIRHHCROCIHHCICOIH;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH CORROIRHRRIHCRHIROHHORCCHIIRCO;
   private final RCIROOOOICRHCCRRCIORHHIRCOIIIC ROORROCCCRCRCOHHOROROIRHCIROHR;
   private final HRCHROOHRIHCRCRHRIIROCIRHOIRHH CCICICRIROHROHHOICIRHICOICIICC;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ORCROCOOIHHHHOOHOIRIIHHCRIHIRR;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCRIHICRIIROCHHHHCROCRCHHRIIOI;
   private final CCIHHRIOOOOCOHRCIHOHROOICIORCC OHOHORIHRCRCORIRRIRCCRHOHORIRI;
   private final com.moonsworth.lunar.client.OOCCRCRCOHIIORCCORCRCIRRROIOOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CRCHORHCICOCRCCHOOCICICRIOCOIC;
   private final com.moonsworth.lunar.client.RCIROOOOICRHCCRRCIORHHIRCOIIIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IIROIIIIICHCROIIORRHCOOHHHCOHH;
   private final IOHHOIIOCRHCHHCRORICCOHOHROOIH CIRRIOOCOIROROOOIHIRIHOORRRIOO;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH HIOIHCRCIHHCIHIHRRCROICIRIIHCR;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OICHRIIHIORHOOOIOCHHOCRORIHIOH;
   private final com.moonsworth.lunar.client.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCHHCIORHROICHORIROHHOOHHCRIHO;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HRIOHCCIOOIORHRHCIRCRRIIOHCHHI;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH HIRHRCRHCHCIICCIOOCROHOOIOIRHH;
   private final RORCHCIIICOHIRROOORHOCCCCIOCCI IIRORHHOIHCICOROIIIRRIHHRHIHOC;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CIHCCOCICROCOOCOCCOCRHOCIHRCRO;
   private final com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH RROOHCOHROIIROCRCRICHOHHCCOOCR;
   private final com.moonsworth.lunar.client.OIHCOHRCICCCRHRCROOCIOIRRHHHIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH HOOOHCROCOIRIIRCIIICOCOHRRCOCR;
   private final IOHIHIIHCCCCCIHRORIOIOORCIOHII COCOCCIORORHIIROHIOIOHIHCRIOOO;
   private final com.moonsworth.lunar.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HIIIRHIIHCIOOCCCCRCHRRRHCROOCC;
   private Optional<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.COIHORRCHRRCHOCIRHHRRIOIHRIHCC.HHCCIRHCCCIIRHCROHIORHIRHHIORH> RHRRROIHCRIICHOORRIHCOCHCHCHCR = Optional.empty();
   private final com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHCCIRHCCCIIRHCROHIORHIRHHIORH RRCCCRRROOIIRHCROOROOIHHHRIRCH = new com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHCCIRHCCCIIRHCROHIORHIRHHIORH();
   @Nullable
   private Map<String, Boolean> RCIIHOCRHIIIRHHCHCORHIOHHROIOR = null;

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
         .HOIRROCROIIHIROHORIOOROCCHOCHI()
         .lock();
      long var1 = System.currentTimeMillis();
      com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.bootstrap();
      com.moonsworth.lunar.client.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.init();
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this);
      com.moonsworth.lunar.client.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.bootstrap();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI().CRICCIRRRCIICCHOOIORCHIHIIROHO();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHRCROHROHOCCHIHOHRROHOCOIRHIO()
         .bridge$setDisplayTitle(ICCCHIOICRORIHCOOCRIRRIORIIROO());
      com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH("Starting Lunar client...");
      this.HIIIRHIIHCIOOCCCCRCHRRRHCROOCC = new com.moonsworth.lunar.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.util.RIROICHCRROROHCCROOCCCCOCHCCRI.OOHIORCOCHIIHHCCIHHIRICROCCROR()
      );
      this.HIIIRHIIHCIOOCCCCRCHRRRHCROOCC.start();
      this.ROCCROHOHRHROOOORROCICOCCOCORO();
      this.IOOHIHOOOCICOHHCHHOHHRCOHIOHRC = new com.moonsworth.lunar.client.IOIICIRIICICIIOORHCIIIIRRIHRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();
      this.OHOOOOOIHOIROIHIRCIOCIRHIIRIOR = new CRRRICCRROCOHHOHIICIHORCOORRRH();
      this.CRHOICICCRIHHRRRICIHIIROCRROOR = new HCHRIROHHHCORIOCROOCHRCIOROOCI();
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCCRHHHOIOHOIICHCHHIROIROOICOH()
         .RCRIHOOCOHRIHORHRICCOHCOIRCIHO();
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CHIOCICOIIORICIOROOHHRIOIOHCOO()
         .init();
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CCCCHCRIHOHHIIIICHRCOOIRHOHIOH(
         IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 6 ? "Starting Lunar Client" : "Starting Minecraft"
      );
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
         .HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class,
            var0 -> new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IRCIIHHICIHRCOCRROCOICRIHHCCHH()
         );

      try {
         this.IRCCRRIOIROIORCOICRROIOOCIOOCH = new RRCRRCORICCHOHHIRCHIROOHIIOHCO();
         this.CRCHORHCICOCRCCHOOCICICRIOCOIC = new com.moonsworth.lunar.client.OOCCRCRCOHIIORCCORCRCIRRROIOOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();
         this.IIROIIIIICHCROIIORRHCOOHHHCOHH = new com.moonsworth.lunar.client.RCIROOOOICRHCCRRCIORHHIRCOIIIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();
         this.OHOHORIHRCRCORIRRIRCCRHOHORIRI = new CCIHHRIOOOOCOHRCIHOHROOICIORCC();
         this.ICRIIOCRRORIOIIRORHORIOHHCCOCO = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.IRCIIHHICIHRCOCRROCOICRIHHCCHH();
         this.HCRCHOCOIOIIIRRCOIOORIHHRIIROO = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR();
         this.ORRHICRCROIRCICRCCIRRIRHCRICRI = new IRRCCOICORICIHCHRHIHIHROIRHOCR();
         this.OCCCOHHOICRHORIICHHRCCCRHOOCII = new HHCCIRHCCCIIRHCROHIORHIRHHIORH();
         this.ICRIHROIRHIHOCOOCRCHCHRRCHOHHC = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OCOHORHCROHICRRIHCIHHRRCIHICRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR();
         this.RIRRCRRIHRORROIOOHIHIOCRIROOHC = new IHIRRIIORRHORHRORIHOROIRCORCOO();
         this.HRHHOCIORIIRRHIOORIORHOIHHROOH = new OHIIIOHIRIRCCRRIOIICCHHIORRHOH();
         this.HROORRHRIICCHICHORHOHCCORICIIH = new OHHRIOHROOIHOROCIRHCHORIHRRRRI().HCCIIIROHORCOCRRRCICRIICHIRCHI();
         this.ROHIICRIRROCRHRHOOHORCIRHOIOII = new HHRIICOIOORCHCOIICOOIHIRHHICRI();
         Builder var3 = ImmutableSet.builder();
         var3.add(
            new RIOOCHICIHRHOHCCCCCHOCCCOHCRHI[]{
               new CIOHHCORHRCCRICCCORIHCRHCCCRRR(),
               this.OHOHORIHRCRCORIRRIRCCRHOHORIRI,
               this.ICRIIOCRRORIOIIRORHORIOHHCCOCO,
               this.HCRCHOCOIOIIIRRCOIOORIHHRIIROO,
               this.ORRHICRCROIRCICRCCIRRIRHCRICRI,
               this.OCCCOHHOICRHORIICHHRCCCRHOOCII,
               this.ICRIHROIRHIHOCOOCRCHCHRRCHOHHC,
               this.HRHHOCIORIIRRHIOORIORHOIHHROOH,
               this.HROORRHRIICCHICHORHOHCCORICIIH,
               this.ROHIICRIRROCRHRHOOHORCIRHOIOII,
               this.RIRRCRRIHRORROIOOHIHIOCRIROOHC,
               this.CCIOHCIIORCIOIHHCOHHIHIHCHOCRC = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
               this.OHIROHHCCHRIIORCHRCOIICOHOOCOO = new IIHRHCCOOHOOOOCHRRCOROOIOHCOOO(),
               this.HROHRRCRRHOIRHIRICOOROHRRRORIH = new OCOHORHCROHICRRIHCIHHRRCIHICRI(),
               this.IOHOCCRORRHOHRROHCIHIIROIHRHOO = new IHHCHHHCRIHOOCOIOOCRIIICIOROIR(),
               this.OIORROROOROHHRIIORIHHHOCIIHRRC = new OOROOCCIRCCRHOIOIORIHCHHOOCCOR(),
               this.HIRROHCROOOIRHOOCRIRRORORIIRCI = new IHICORCROOROHCIHIHCOIHRRHICICO(),
               this.CRHHIRIIHRRIRCOHRIORHORCOCIHHI = new OIHCOHRCICCCRHRCROOCIOIRRHHHIH(),
               this.CHIOCHOIHHHCHOIHHIIHIOHCRHRIII = new IIRHCHHOICHRICOOCRORCCIOOIHOIR(),
               this.HRHIRCRROIHRIOHCOOCCHIHCCROHRR = new RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(),
               this.RHHROIIIHCCIHOCOCOHCHIHIOOIRIO = new CORCOCICIRIOHROHROIIOOHICCHCRR(),
               this.OCIRIHHHIICCRCHICCCHHHHIOHCHHH = new RIROICHCRROROHCCROOCCCCOCHCCRI(),
               this.RCIICOICCOIOCCCHCOOCCRHRIHOOHI = new ORHIOICIOCRRHOOCOHRORIHICHRCRR(),
               this.IROHORIIHOCCORRIHICCROIHRRIRCI = new CRICCOOHHHCHOORCICOCOHIHOIRHOO(),
               this.HIOIHCRCIHHCIHIHRRCROICIRIIHCR = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH(),
               this.OCHRCCCICRIOCRCOORCIRCHRIHOIRO = new IIHRRHORCRCROCHHOHORCHCROCIHRO(),
               this.HRIOCRHIOOHOHOCRCROIIRORHICICC = new OOCCRCRCOHIIORCCORCRCIRRROIOOR(),
               this.CCCIOOHOCOCHCRIRHIIORCRIOOIRHO = new com.moonsworth.lunar.client.ICICIOCHHHIHOCHCOHORIHRCOHHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
               this.HOHIROROCHIROOCCROHOCOORCHCORC = new RHOCHHIRRCHHHOHOIRROIROHHHIHIO(),
               this.RRICCCRROHRIHHIOCIRCOCCIRHHIIO = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(),
               this.CIIHCIOHIICOOOOIIOIRCICRRICCOH = new IOIICIRIICICIIOORHCIIIIRRIHRHI(),
               this.CRHHOHCOORHRIIRCHCHCORIIORCOHC = new ICICIOCHHHIHOCHCOHORIHRCOHHOCR(),
               this.HORCOHHRCCOICRCIOHHRRHHCRHCCOR = new CRHROHHHCIHHCOHCOORCRIHHIICROR(),
               this.OOIOOICRHHHIICOHOHCOHCRRRCRCHH = new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(),
               this.CRHOICIHHOCICHICICRRORHOHRIROH = new RICRIRRCOHRCOCRRHHCRHRROOIOHHR(),
               this.HRCHHIRIHROOIHHRCHICORRROHRCRR = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO(),
               this.RRIOIROCRCCCCROHHCRHOOROOHRROI = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(),
               this.OIRHCCHIOOIIIOIRCHCOHOHOIOCIOC = new IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(),
               this.IRROIHHOOHCIOHICHHROOOCOCHCCOI = new RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(),
               this.IOHCCHCCHHRRRICOCRHHIRICCCCOOO = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
               this.RICIRORIRHHIHIICHOHROROHRIIOOR = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(),
               this.IOIOORHICOIOOHCRIIROHCIROICCCO = new com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
               this.OHORCIHORHOCIRIIIRCCRHRCOCCHCH = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(),
               this.CIRORIOCCCICOHIHRICOHOCIICIOIH = new IHCRORHRORIICHRHRCHRRIRRHHOCOO(),
               this.RCRCORCICHOIHRHRCICOCCIRHIHICR = new com.moonsworth.lunar.client.OCOHORHCROHICRRIHCIHHRRCIHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(),
               this.HCORIRRICOOCHCORIIIROIOCHOCCCR = new HICRRICCHCCROOHHCHOCOCCHOIHHOC(),
               this.HHOHOCIOHIHHCCOCIOROCIHRORCIHI = new com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(),
               this.ROOCHOCCIHCIIIRHHCROCIHHCICOIH = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(),
               this.CORROIRHRRIHCRHIROHHORCCHIIRCO = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(),
               this.ROORROCCCRCRCOHHOROROIRHCIROHR = new RCIROOOOICRHCCRRCIORHHIRCOIIIC(),
               this.CCICICRIROHROHHOICIRHICOICIICC = new HRCHROOHRIHCRCRHRIIROCIRHOIRHH(),
               this.OICHRIIHIORHOOOIOCHHOCRORIHIOH = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
               this.RCRIHICRIIROCHHHHCROCRCHHRIIOI = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
               this.CIRRIOOCOIROROOOIHIRIHOORRRIOO = new IOHHOIIOCRHCHHCRORICCOHOHROOIH(),
               this.RCHHCIORHROICHORIROHHOOHHCRIHO = new com.moonsworth.lunar.client.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
               this.HRIOHCCIOOIORHRHCIRCRRIIOHCHHI = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
               this.RROOHCOHROIIROCRCRICHOHHCCOOCR = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(),
               this.HIRHRCRHCHCIICCIOOCROHOOIOIRHH = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(),
               this.IIRORHHOIHCICOROIIIRRIHHRHIHOC = new RORCHCIIICOHIRROOORHOCCCCIOCCI(),
               this.CIHCCOCICROCOOCOCCOCRHOCIHRCRO = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
               this.COCOCCIORORHIIROHIOIOHIHCRIOOO = new IOHIHIIHCCCCCIHRORIOIOORCIOHII(),
               this.HOOOHCROCOIRIIRCIIICOCOHRRCOCR = new com.moonsworth.lunar.client.OIHCOHRCICCCRHRCROOCIOIRRHHHIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH()
            }
         );
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 8) {
            var3.add(
               this.ORCROCOOIHHHHOOHOIRIIHHCRIHIRR = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
            );
         } else {
            this.ORCROCOOIHHHHOOHOIRIIHHCRIHIRR = null;
         }

         this.OROHIHCCRHRHOOHIOHHOICHIOHIOCO = var3.build();
         this.IRCCRRIOIROIORCOICRROIOOCIOOCH.close();
         this.IRCCRRIOIROIORCOICRROIOOCIOOCH = null;
      } catch (Throwable var6) {
         com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH(
            "Failed to construct managers!"
         );
         var6.printStackTrace();
         throw var6;
      }

      com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH("Finished making managers.");
      this.OROHIHCCRHRHOOHIOHHOICHIOHIOCO
         .stream()
         .filter(
            var0 -> var0 instanceof com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH
         )
         .forEach(
            var0 -> com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
               (com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var0
            )
         );
      com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH("Setting up listeners...");
      new com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH();
      new com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH();
      new com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();
      this.HHHROIRRRRCHCHROHCORIIOHOIIOCC = new com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI();
      new com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR();
      new com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO();
      new com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH();
      new com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH();
      new com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH();
      com.moonsworth.lunar.client.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.bootstrap();
      this.ORRORHRIRHOCCRIROCCIIRRHHOHOIC();
      com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         "Init GameUI and GameUIRenderer..."
      );
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ICHIRRICROROCIOCRIOICHHCHCIRIR();
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.init();
      com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH("Setting up fixes...");
      if (RIHOOCIHRICOCHRHCOOCCOIHOCHRCR.isLinux()
         && com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.getMinecraftVersion().OOICHHIHHIHROCCRRRIIIIRIRICCIH()) {
         new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();
      }

      new COIHORRCHRRCHOCIRHHRRIOIHRIHCC();
      Emoticons.register();
      this.HIOIHCRCIHHCIHIHRRCROICIRIIHCR.register();
      if (!com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRRICCIOIHROCCOIIORROIROCIIOR) {
         this.RRHOOICIIHOCROIHCHRRORRORHHROH();
      }

      com.moonsworth.lunar.ichor.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var7 = (com.moonsworth.lunar.ichor.OOROOCCIRCCRHOIOIORIHCHHOOCCOR)IchorAPI.getPipeline(
            this.getClass().getClassLoader()
         )
         .orElseThrow(() -> new IllegalStateException("Pipeline not found!"));
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class,
            () -> new com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var7.OICHHOCICHCIIOCHRIIRRHRHRIIIIR()
                  .collect(
                     Collectors.toMap(
                        com.moonsworth.lunar.ichor.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH::getKey,
                        var0x -> (com.moonsworth.lunar.ichor.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var0x
                     )
                  )
            )
         );
      if (com.moonsworth.lunar.client.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
            com.moonsworth.lunar.client.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class
         )
         .isEmpty()) {
         com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            "Ichor", "Disabling ReplayMod because there is no valid link."
         );
         this.RIRRCRRIHRORROIOOHIHIOCRIROOHC
            .HOOHRIIRIHCIHIIHIOHHOHHORIOHOR()
            .RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC.IOCHHHIIRIHOIRHHICHICCRIHOIOHC
            )
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RIRRCRRIHRORROIOOHIHIOCRIROOHC.HOOHRIIRIHCIHIIHIOHHOHHORIOHOR(),
               com.moonsworth.lunar.client.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CLIENT_INTERNAL,
               false
            );
      }

      this.start();
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICRRICCHCCROOHHCHOCOCCHOIHHOC.class,
            () -> new com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICRRICCHCCROOHHCHOCOCCHOIHHOC(
               IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSelectedResourcePack()
            )
         );
      if (!RCIORCRHCIOIHCOCORCIHIOROCOOCR.isShutdown()) {
         RCIORCRHCIOIHCOCORCIHIOROCOOCR.shutdown();

         try {
            if (!RCIORCRHCIOIHCOCORCIHIOROCOOCR.awaitTermination(1L, TimeUnit.DAYS)) {
               RCIORCRHCIOIHCOCORCIHIOROCOOCR.shutdownNow();
               Thread.currentThread().interrupt();
            }
         } catch (InterruptedException var5) {
            throw new RuntimeException(var5);
         }
      }

      com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH("Finished Lunar initialization.");
      IchorAPI.getPipeline(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class)
         .ifPresent(com.moonsworth.lunar.ichor.OOROOCCIRCCRHOIOIORIHCHHOOCCOR::HHCCOOHOOHRCRHHCRRHIHCROOCHOCI);
      com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         "Lunar took " + (System.currentTimeMillis() - var1) + "ms to initialize."
      );
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
         .HOIRROCROIIHIROHORIOOROCCHOCHI()
         .unlock();
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCIRHORHIRCHOORHHOHIROROOCIHOR()
         .init();
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCCIIOCRHCIOCICCHHIIRROCHHOHCH()
         .init();
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.bootstrap();
      if (!com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRRICCIOIHROCCOIIORROIROCIIOR) {
         this.ROCICHRHCOCRHHHRHCOIOROOORHHHI();
      }
   }

   private void ROCICHRHCOCRHHHRHCOIOROOORHHHI() {
      try {
         Class var1 = ClassLoader.getSystemClassLoader().loadClass("com.moonsworth.lunar.genesis.Genesis");
         Field var2 = var1.getDeclaredField("START_TIME");
         long var3 = (Long)var2.get(null);
         long var5 = System.nanoTime() - var3;
         System.out.printf("BOOT TIMING: Took %.2f seconds to boot\n", (double)var5 / Duration.ofSeconds(1L).toNanos());
         this.getClass().getClassLoader().getClass().getClassLoader().loadClass("com.moonsworth.lunar.ichor.ProfileData").getDeclaredMethod("log").invoke(null);
      } catch (Throwable var7) {
         throw new RuntimeException(var7);
      }
   }

   public boolean HIRCHICICRHIOOOHRIRIRHHRHICOHC() {
      return this.OROHIHCCRHRHOOHIOHHOICHIOHIOCO != null && this.IRCCRRIOIROIORCOICRROIOOCIOOCH == null;
   }

   private void RRHOOICIIHOCROIHCHRRORRORHHROH() {
      try {
         Class var1 = Class.forName("com.moonsworth.lunar.client.dev.DevEnvironment");
         Method var2 = var1.getDeclaredMethod("init");
         var2.invoke(null);
      } catch (ReflectiveOperationException var3) {
         var3.printStackTrace();
      }
   }

   private void start() {
      com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH("Lunar.start");
      this.ORRHICRCROIRCICRCCIRRIRHCRICRI.setLanguage(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.OORHIHHCIRRIRCOHICHCICHIHOOHCO);
      this.ICRIIOCRRORIOIIRORHORIOHHCCOCO
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI(),
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$displayWidth(),
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$displayHeight()
         );
      this.CCIOHCIIORCIOIHHCOHHIHIHCHOCRC.init();

      for (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2 : this.OROHIHCCRHRHOOHIOHHOICHIOHIOCO) {
         if (var2 != this.CCIOHCIIORCIOIHHCOHHIHIHCHOCRC) {
            try {
               var2.init();
            } catch (Exception var5) {
               com.moonsworth.lunar.client.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5, "Manager Init");
            }
         }
      }

      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CCCCHCRIHOHHIIIICHRCOOIRHOHIOH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.getMinecraftVersion().OOICHHIHHIHROCCRRRIIIIRIRICCIH()
            ? "Starting Minecraft"
            : "Finalizing"
      );
      com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH("Launching");
      this.OCCHIHRHRHIROIOCOCICRRRHIORRRH = true;
      if (com.moonsworth.lunar.client.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
            com.moonsworth.lunar.client.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class
         )
         .isPresent()) {
         try {
            Class.forName("gg.essential.model.backend.minecraft.RenderLayerFactory", true, RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class.getClassLoader());
            com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               "Essentials Mod: Preloaded RenderLayerFactory class to initialize its render types"
            );
         } catch (ClassNotFoundException var4) {
            com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               "Essentials Mod: Not present"
            );
         }
      }

      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
         .HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI.class,
            var0 -> {
               com.moonsworth.lunar.client.util.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.tick();
               ORCOCORROHIROCCIORORRRRCHIOOCH.tick();
            }
         );
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
         .HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIROICHCRROROHCCROOCCCCOCHCCRI.class,
            var1 -> {
               if (IRRCHICCRHCHRRCHIOHIIRIORIRHRI.CCHIIRRRIHRORIORCRRRCIRRCRIRCC != null) {
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2x = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI();
                  if (IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().ICRIOCOOICRIIIRIHIRIOIHCOHHIIC().HHRIIIRIRIICRRHHICOHIHICHHRCRR()) {
                     IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
                        .bridge$connect(
                           var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              IRRCHICCRHCHRRCHIOHIIRIORIRHRI.CCHIIRRRIHRORIORCRRRCIRRCRIRCC,
                              IRRCHICCRHCHRRCHIOHIIRIORIRHRI.CCHIIRRRIHRORIORCRRRCIRRCRIRCC,
                              false
                           ),
                           var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              new com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                                 com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHOCHCOIHOCCORORIORHICRCCIOICH,
                                 null
                              )
                           )
                        );
                  } else {
                     com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORORCIORRICORCHRRCCHHRRHROORRI();
                     IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                        .IHCHHRRIIIORORCHIICIIOORCOIOIO()
                        .CIICCRHHHOHOIOHCHRHOORCICRCORC("Please login before attempt to join a server from the Launcher!");
                     com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        "Unable to quick join " + IRRCHICCRHCHRRCHIOHIIRIORIRHRI.CCHIIRRRIHRORIORCRRRCIRRCRIRCC + " as the user can not play online!"
                     );
                  }

                  IRRCHICCRHCHRRCHIOHIIRIORIRHRI.CCHIIRRRIHRORIORCRRRCIRRCRIRCC = null;
               }

               if (!IICCOOCHCHROORHHIIHROHCCRHRCOR.IIIIIOCCCIIOHOCRRCCOOCHOHRCRCO().isEmpty()
                  && IICCOOCHCHROORHHIIHROHCCRHRCOR.IIIIIOCCCIIOHOCRRCCOOCHOHRCRCO().get().ROORROCCCRCRCOHHOROROIRHCIROHR()
                     == com.moonsworth.lunar.client.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.READY) {
                  int var6 = com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI.ROCHOOHIHIHCIRHCICIOHHCIOHHHRH
                     / 20;
                  if (var6 % 60 == 0
                     && !IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                        .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
                        .IOIOHOOCRRORCCCOCIRROHCOCCCRCO()
                        .HRIICOIOIIIIRIHHOICRHOIIRCIRIC()) {
                     IICCOOCHCHROORHHIIHROHCCRHRCOR.IIIIIOCCCIIOHOCRRCCOOCHOHRCRCO()
                        .ifPresent(var0 -> var0.HRHIRCRROIHRIOHCOOCCHIHCCROHRR().gameHeartbeat(null, GameHeartbeatRequest.getDefaultInstance(), var0x -> {}));
                  }

                  if (var6 % 30 == 0) {
                     HashMap var3 = new HashMap();

                     for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5x : IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                        .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
                        .OHHRCRIOOCIORORHIOHRICRHHORCIH()) {
                        var3.put(var5x.getId(), var5x.isEnabled());
                     }

                     if (this.RCIIHOCRHIIIRHHCHCORHIOHHROIOR == null || !this.RCIIHOCRHIIIRHHCHCORHIOHHROIOR.equals(var3)) {
                        this.RCIIHOCRHIIIRHHCHCORHIOHHROIOR = var3;
                        IICCOOCHCHROORHHIIHROHCCRHRCOR.IIIIIOCCCIIOHOCRRCCOOCHOHRCRCO().ifPresent(var1x -> {
                           RecordEnabledModsRequest var2xx = RecordEnabledModsRequest.newBuilder().putAllMods(var3).build();
                           var1x.IOIOORHICOIOOHCRIIROHCIROICCCO().recordEnabledMods(null, var2xx, var0x -> {});
                        });
                     }
                  }
               } else {
                  this.RCIIHOCRHIIIRHHCHCORHIOHHROIOR = null;
               }
            }
         );
   }

   public void close() {
      try {
         if (this.HIIIRHIIHCIOOCCCCRCHRRRHCROOCC != null) {
            this.HIIIRHIIHCIOOCCCCRCHRRRHCROOCC.shutdown();
         }

         com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IOHRICHRCCCIIHROIHIRCHICIOHCRI();
         com.moonsworth.lunar.client.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
               com.moonsworth.lunar.client.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class
            )
            .ifPresent(
               var1 -> {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2x = this.RIRRCRRIHRORROIOOHIHIOCRIROOHC
                     .HOOHRIIRIHCIHIIHIOHHOHHORIOHOR();
                  if (!var2x.isEnabled() || !var1.isRecording()) {
                     var1.CHCOIOOICHHIOCHHRCHOOCHRROOOCO();
                  }
               }
            );
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
               com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH::new
            );
         if (this.OROHIHCCRHRHOOHIOHHOICHIOHIOCO != null) {
            for (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2 : this.OROHIHCCRHRHOOHIOHHOICHIOHIOCO) {
               var2.close();
            }
         }

         if (com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCHHHIIHOIIHCOCRRORRHROOHCHIHO()
            )
          {
            com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.OIICORCHORCIIRIHOORCHOROHCCHCO()
               .close();
         }

         if (this.CCIOHRRCIROCHOORCRCRHRORIOOOOO != null && this.CCIOHRRCIROCHOORCRCRHRORIOOOOO.isOpen()) {
            this.CCIOHRRCIROCHOORCRCRHRORIOOOOO.close();
         }

         if (this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO != null && this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO.isOpen()) {
            this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO.close();
         }

         com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHICORCROOROHCIHIHCOIHRRHICICO(
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getMcDataDir()
         );
         ORCOCORROHIROCCIORORRRRCHIOOCH.shutdown();
      } catch (Throwable var3) {
         var3.printStackTrace();
      }
   }

   private void ROCCROHOHRHROOOORROCICOCCOCORO() {
      File var1 = com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI.toPath().resolve("version").toFile();
      if (!com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI.exists()) {
         com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI.mkdirs();
         boolean var2 = false;
         if (com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI.exists()) {
            var2 = true;

            try {
               FileUtils.copyDirectory(
                  com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI,
                  com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI
               );
            } catch (IOException var20) {
               var2 = false;
            }
         }

         if (!var2) {
            String var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getMcDataDir() + File.separator + "config" + File.separator;
            File var4 = new File(var3 + "assets" + File.separator + "lunar");
            File var5 = new File(var3 + "lunar");
            File var6 = null;
            if (var4.exists() && var5.exists()) {
               if (var4.lastModified() > var5.lastModified()) {
                  var6 = var4;
               } else {
                  var6 = var5;
               }
            } else if (var4.exists()) {
               var6 = var4;
            } else if (var5.exists()) {
               var6 = var5;
            }

            if (var6 != null) {
               try {
                  FileUtils.copyDirectory(var6, com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI);
               } catch (Exception var19) {
                  var19.printStackTrace();
               }
            }

            try {
               if (var1.createNewFile()) {
                  try (OutputStreamWriter var7 = new OutputStreamWriter(new FileOutputStream(var1), StandardCharsets.UTF_8)) {
                     var7.write(
                        String.valueOf(
                           com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OCCRIIOROHCIIOROCCCHOCIHHOOCIH
                        )
                     );
                  } catch (IOException var17) {
                     var17.printStackTrace();
                  }
               }

               com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI.mkdirs();
               FileUtils.copyDirectory(
                  com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI,
                  com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI
               );
            } catch (Exception var18) {
               var18.printStackTrace();
            }
         }
      } else {
         try {
            int var21 = 0;
            if (var1.exists()) {
               String var22 = Files.readString(var1.toPath(), StandardCharsets.UTF_8);

               try {
                  var21 = Integer.parseInt(var22);
                  com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     "Loading settings with version: " + var21
                  );
               } catch (NumberFormatException var13) {
                  com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH(
                     "Could not read version string: " + var22
                  );
               }
            }

            if (var21
               < com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OCCRIIOROHCIIOROCCCHOCIHHOOCIH
               )
             {
               FileUtils.deleteDirectory(com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI);
               FileUtils.copyDirectory(
                  com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI,
                  com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI
               );
            } else if (var21
               > com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OCCRIIOROHCIIOROCCCHOCIHHOOCIH
               )
             {
               if (com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI.exists()) {
                  FileUtils.deleteDirectory(com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI);
                  FileUtils.copyDirectory(
                     com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI,
                     com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI
                  );
               } else {
                  FileUtils.deleteDirectory(com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI);
                  FileUtils.copyDirectory(
                     com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.ROCIHIROIOOIHHHHIRIRCCIIOOHHHI,
                     com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHOCHRHIHRHORHIOIIIHHCCIRIOCI
                  );
               }
            }

            var1.delete();
            if (var1.createNewFile()) {
               try (OutputStreamWriter var23 = new OutputStreamWriter(new FileOutputStream(var1), StandardCharsets.UTF_8)) {
                  var23.write(
                     String.valueOf(
                        com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OCCRIIOROHCIIOROCCCHOCIHHOOCIH
                     )
                  );
               } catch (IOException var12) {
                  var12.printStackTrace();
               }
            }
         } catch (Exception var14) {
            var14.printStackTrace();
         }
      }
   }

   private Handshake.Builder HCHCHOORHHOHHOCICRHICIRRIOHICR() {
      Set var1 = IchorAPI.getPipeline(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class.getClassLoader())
         .map(var0 -> var0.HCCIOOOIRIRHCOHOIRCHIIOHCRRIIR().keySet())
         .orElse(Set.of());
      return Handshake.newBuilder()
         .setLauncherVersion(LauncherVersion.newBuilder().setSemver(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.ORCCHCHHORORRHCHRRCCHICHIHCCCO).build())
         .setInstallationId(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.CIIRORRIRORRRHCROCICCCHIHOHRCR)
         .setOverwolfMuid(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.OOROIOCCRCOROORRIOOOICRHHRIHHC)
         .setCanaryToken(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.RCIROCRHCOHOCCCCIIIHCORRRRCORI)
         .setOperatingSystem(com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.HIOCHICRIOCICHRCOOCOROIHIIHCHO)
         .setOperatingSystemRelease(com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OHCCRCCRIOHROIOOIIICORCHOHCOHH)
         .setCpuArchitecture(com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OCOIIIHIRRCCCCCHCHRIOCHHRHIICI)
         .setLanguage(Language.newBuilder().setMinecraftCode(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.OORHIHHCIRRIRCOHICHCICHIHOOHCO).build())
         .setGameHandshake(
            GameHandshake.newBuilder()
               .setMinecraftVersion(
                  MinecraftVersion.newBuilder()
                     .setEnum(com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.getMinecraftVersion().getId())
                     .build()
               )
               .setLunarClientVersion(
                  LunarClientVersion.newBuilder()
                     .setGitBranch(com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRIRIIICIRRIIRICRRORCCRCOHIHIO)
                     .setGitCommit(com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCICHOOCICHRIIIHHROHCRHHROOHIO)
                     .setSemver(CROIHRIIRROCHORIIRIOCROOORRCCH())
                     .build()
               )
               .setLocation(com.moonsworth.lunar.client.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRHHOHCOORHRIIRCHCHCORIIORCOHC())
               .addAllIchorModules(var1)
               .addAllInstalledMods(
                  ((com.moonsworth.lunar.ichor.OOROOCCIRCCRHOIOIORIHCHHOOCCOR)IchorAPI.getPipeline(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class).orElseThrow())
                     .OICHHOCICHCIIOCHRIIRRHRHRIIIIR()
                     .map(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::IRCIIHHICIHRCOCRROCOICRIHHCCHH)
                     .collect(Collectors.toList())
               )
               .setModpack(
                  PlayerModpack.newBuilder()
                     .setModrinthId(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.HOOHROHCIHOICOCOIICCOCOICROIRR)
                     .setModrinthVersionId(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.IOHHIIICRCIOHCHHORCHRCRHCHCRIO)
                     .setCurseforgeId(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.RHHRRICCIHHIHRHIORRRRRROCHIHHH)
                     .setCurseforgeFileId(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.IRHCRHIORHIRHOCRROCRICRIIRCIOR)
                     .build()
               )
               .addAllGlExtensions(
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHCHHROCORIHCIORRRIIOHIRHCRIOH()
                     .IIRIIICCOORHIRHCIIROIHOROCICCC()
               )
               .setLaunchId(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.OOHOHIOIORIORCHRORCHIOCHOIRCCO)
               .setLunarClientUiVersion(
                  LunarClientUiVersion.newBuilder()
                     .setGitBranch(com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOHOROHRCOHIIRCHHOHOCIRHROOOHR)
                     .setGitCommit(
                        com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HIHIROOIICRIICOROCRCRCCIHCICIC == null
                           ? "latest"
                           : com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HIHIROOIICRIICOROCRCRCCIHCICIC
                     )
                     .build()
               )
               .build()
         );
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var1, Consumer<String> var2) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHICORCROOROHCIHIHCOIHRRHICICO var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
         .bridge$getSession();
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .ICRIOCOOICRIIIRIHIRIOIHCOHHIIC()
         .IOOIOIRHHCHIROHHCCCORCRCHICROO();
      if (var4 == null) {
         com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            "Auth", "Failed to establish connection with the auth server, account null."
         );
         var2.accept(null);
      } else if (!var4.CRHCHHROOCCHRHHOHRCHICCIRRIHRC()) {
         com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            "Auth", "Failed to establish connection with the auth server, access token invalid."
         );
         var2.accept(null);
      } else {
         UuidAndUsername var5 = CCHORHIOORICCIRIHRIIHIICORIORO.CORCOCICIRIOHROHROIIOOHICCHCRR(
            UUID.fromString(OCIOROHIHRROROOIRRHRRCCHHRRRHI.CCHHHHCICRCCCIOOIOICOOCRCRHCCR(var3.bridge$getPlayerID())), var3.bridge$getUsername()
         );
         new com.moonsworth.lunar.client.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5, var1, var2).connect();
      }
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(@Nullable RRCRRCORICCHOHHIRCHIROOHIIOHCO var1) {
      Handshake.Builder var2 = this.HCHCHOORHHOHHOCICRHICIRRIOHICR();
      new Thread(
            () -> {
               com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  "Assets", "Establishing connection"
               );
               if (this.CCIOHRRCIROCHOORCRCRHRORIOOOOO != null && this.CCIOHRRCIROCHOORCRCRHRORIOOOOO.isOpen()) {
                  try {
                     this.CCIOHRRCIROCHOORCRCRHRORIOOOOO.closeBlocking();
                  } catch (InterruptedException var4) {
                  }
               }

               if (var1 != null) {
                  Optional var3 = var1.RCHHCIORHROICHORIROHHOOHHCRIHO();
                  if (var3.isPresent()) {
                     com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        "Assets", "Skipping Authenticator call, using reconnect JWT instead."
                     );
                     this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((String)var3.get(), var2);
                  } else {
                     com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        "Assets", "Connecting to Authenticator to obtain JWT, no reconnect JWT offered."
                     );
                     this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2);
                  }
               } else {
                  com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                     "Assets", "Connecting to Authenticator to obtain JWT, no previous connection."
                  );
                  this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2);
               }
            }
         )
         .start();
   }

   public void ORRORHRIRHOCCRIROCCIIRRHHOHOIC() {
      new Thread(
            () -> {
               try {
                  if (this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO != null && this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO.isOpen()) {
                     this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO.closeBlocking();
                  }

                  com.lunarclient.gameipc.handshake.v1.Handshake var1 = this.CHCCHOIHRRRCCRRCCHIRIRCORRHIHR();
                  if (var1 == null) {
                     com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        "IPC", "Unable to construct IPC handshake."
                     );
                     return;
                  }

                  this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO = new com.moonsworth.lunar.client.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
                  this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO.connect();
                  IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
                     .bridge$submit(
                        () -> com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCCOIRHHOOHICHHIOOOIRORRCRIRRO()
                           .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class,
                              () -> new com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                                 this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO
                              )
                           )
                     );
               } catch (InterruptedException var2) {
                  var2.printStackTrace();
               }
            }
         )
         .start();
   }

   @Nullable
   private Handshake CHCCHOIHRRRCCRRCCHIRIRCORRHIHR() {
      String var1 = IRRCHICCRHCHRRCHIOHIIRIORIRHRI.OOHOHIOIORIORCHRORCHIOCHOIRCCO;
      String var2 = IRRCHICCRHCHRRCHIOHIIRIORIRHRI.CIIRORRIRORRRHCROCICCCHIHOHRCR;
      label26:
      if (!var1.equalsIgnoreCase("not supplied")) {
         com.lunarclient.gameipc.handshake.v1.Handshake.Builder var3 = com.lunarclient.gameipc.handshake.v1.Handshake.newBuilder()
            .setLaunchId(var1)
            .setInstallationId(var2);

         try {
            long var4 = ProcessHandle.current().pid();
            var3.setProcessId(Long.toString(var4));
         } catch (Exception var6) {
         }

         return var3.build();
      } else {
         if (com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRRICCIOIHROCCOIIORROIROCIIOR) {
            return null;
         }

         var1 = "00000000-0000-0000-0000-000000000000";

         try {
            var2 = Files.readString(com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CRIRIRCRICOHRCRHHCICRHCOOIICCO.resolve("installation-id"));
            break label26;
         } catch (IOException var7) {
            var7.printStackTrace();
            return null;
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Handshake.Builder var1) {
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("GAME_WEBSOCKET", var2 -> {
         if (var2 != null) {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var1);
         }
      });
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var1, Handshake.Builder var2) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHICORCROOROHCIHIHCOIHRRHICICO var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
         .bridge$getSession();
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .ICRIOCOOICRIIIRIHIRIOIHCOHHIIC()
         .IOOIOIRHHCHIROHHCCCORCRCHICROO();
      if (!com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRRICCIOIHROCCOIIORROIROCIIOR) {
         IRRCHICCRHCHRRCHIOHIIRIORIRHRI.ORCCHCHHORORRHCHRRCCHICHIHCCCO = "gradle";
      }

      this.CCIOHRRCIROCHOORCRCRHRORIOOOOO = new com.moonsworth.lunar.client.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var2.setIdentity(
               MinecraftIdentity.newBuilder()
                  .setPlayer(
                     CCHORHIOORICCIRIHRIIHIICORIORO.CORCOCICIRIOHROHROIIOOHICCHCRR(
                        UUID.fromString(OCIOROHIHRROROOIRRHRRCCHHRRRHI.CCHHHHCICRCCCIOOIOICOOCRCRHCCR(var3.bridge$getPlayerID())), var3.bridge$getUsername()
                     )
                  )
                  .setType(var4.CRCHRRIICIOCRCIOIHICHHRROIOCHR().getProtobufType())
                  .setAuthenticatorJwt(var1)
                  .build()
            )
            .build()
      );
      this.CCIOHRRCIROCHOORCRCRHRORIOOOOO.connect();
      com.moonsworth.lunar.client.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         Breadcrumb.debug("Connected to the AssetServer")
      );
   }

   @NotNull
   private static InstalledMod IRCIIHHICIHRCOCRROCOICRIHHCCHH(com.moonsworth.lunar.ichor.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0) {
      InstalledMod.Builder var1 = InstalledMod.newBuilder()
         .setId(var0.getId())
         .setName(var0.getId())
         .setType(
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.getMinecraftVersion().OOICHHIHHIHROCCRRRIIIIRIRICCIH()
               ? (var0.CRICCOOHHHCHOORCICOCOHIHOIRHOO() ? InstalledMod.Type.TYPE_FABRIC_INTERNAL : InstalledMod.Type.TYPE_FABRIC_EXTERNAL)
               : InstalledMod.Type.TYPE_FORGE_INTERNAL
         );
      String var2 = var0.getVersion();
      if (var2 == null) {
         var1.clearVersion();
      } else {
         var1.setVersion(var2);
      }

      return var1.build();
   }

   public boolean ROCIHHOOOHCROIRIRCHRICCICOHRIR() {
      return this.COOHOHRHHICRHIORRORHIOOIIHRHHI == null;
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHICORCROOROHCIHIHCOIHRRHICICO var1
   ) {
      try {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHICORCROOROHCIHIHCOIHRRHICICO var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
            .bridge$getSession();
         if (this.COOHOHRHHICRHIORRORHIOOIIHRHHI != null
            && Objects.equals(this.COOHOHRHHICRHIORRORHIOOIIHRHHI.HRIOHCCIOOIORHRHCIRCRRIIOHCHHI(), var2.bridge$getProfile().getId())
            && Objects.equals(this.COOHOHRHHICRHIORRORHIOOIIHRHHI.getName(), var2.bridge$getUsername())) {
            return;
         }

         boolean var3 = var1 != null && var1.bridge$getProfile() != null && var1.bridge$getProfile().getId() != null;
         boolean var4 = var3 && !var1.bridge$getProfile().getId().equals(var2.bridge$getProfile().getId());
         if (var3 && var4) {
            this.RHHROIIIHCCIHOCOCOHCHIHIOOIRIO.HIRHCIRIOHIHHCOIIORHROIOCRRRIO();
            this.RCIICOICCOIOCCCHCOOCCRHRIHOOHI.HIRHCIRIOHIHHCOIIORHROIOCRRRIO();
         }

         this.COOHOHRHHICRHIORRORHIOOIIHRHHI = new IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2.bridge$getProfile().getId(), var2.bridge$getUsername());
         this.COOHOHRHHICRHIORRORHIOOIIHRHHI
            .IRCIIHHICIHRCOCRROCOICRIHHCCHH(com.moonsworth.lunar.client.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.ONLINE);
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
            .bridge$submit(
               () -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((com.moonsworth.lunar.client.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO)null)
            );
      } catch (Exception var5) {
         var5.printStackTrace();
      }
   }

   public void HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR var1
   ) {
      if (var1 == null) {
         Sentry.clearBreadcrumbs();
      } else {
         String var2 = var1.getClass().getName();
         if (var1 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH
            )
          {
            if (((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH)var1)
               .RRIOOIOROCIRHRORIRHIRHIHOCHICH() instanceof com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
               )
             {
               return;
            }

            var2 = ((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH)var1)
               .RRIOOIOROCIRHRORIRHIRHIHOCHICH()
               .getClass()
               .getName();
         }

         String var3 = var1.RICCICOHIICIIORHCHCRCRHOOOCHIC().orElse(var2);
         if (!"/".equals(var3)) {
            Breadcrumb var4 = new Breadcrumb();
            var4.setLevel(SentryLevel.DEBUG);
            var4.setType("debug");
            var4.setCategory("screen.open");
            var4.setMessage("User opened " + var3);
            Sentry.addBreadcrumb(var4);
         }
      }
   }

   public boolean HRICIORORHCRHCCCIIIHRRHCICOHOR(String var1) {
      return this.world.isEmpty() || var1.isEmpty() || var1.equals(this.world);
   }

   public static String ICCCHIOICRORIHCOOCRIRRIORIIROO() {
      return "Lunar Client " + ORIRHOCICIIRCRHCHHRHOHIIHRHOCI();
   }

   public static String ORIRHOCICIIRCRHCHHRHOHIIHRHOCI() {
      String var0 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.getMinecraftVersion().getDisplayName();
      return var0 + " (" + CROIHRIIRROCHORIIRIOCROOORRCCH() + ")";
   }

   public static String CROIHRIIRROCHORIIRIOCROOORRCCH() {
      return IHCRORHRORIICHRHRCHRRIRRHHOCOO(true);
   }

   public static String IHCRORHRORIICHRHRCHRRIRRHHOCOO(boolean var0) {
      return com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RIOIHOIOIIHRRHIOIHHOICRHIRCHCO
         ? (var0 ? "v" : "") + com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORORCHIOOOCIOHHOROHICHOHHCCHIO
         : com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOCRRHCRORRCCCIRHOIORIHRIIHOOC
            + "/"
            + com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRIRIIICIRRIIRICRRORCCRCOHIHIO;
   }

   public static String getClientBrand() {
      return "lunarclient:" + CROIHRIIRROCHORIIRIOCROOORRCCH();
   }

   public static int ICIIOHIRRHRORROIIHCIRCIIOIHCHR() {
      return 64;
   }

   public boolean CHORCRIIRRIIOCCORCRHRRRIHIOIIO() {
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() == null;
   }

   public void RIHHOOICOHICCIIHOHRHOCOHIIOIIO() {
      this.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(false);
   }

   public void ICICIOCHHHIHOCHCOHORIHRCOHHOCR(boolean var1) {
      if (this.HOOCOOIRHCHIICICHOICHCOIRICIHI()
         && !(
            IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR
         )) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
            .bridge$displayScreen(
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
                  .COCOHIHCICRHOOCHIHCCORHHIRHIOH()
            );
      } else {
         com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROCOCHICHORROOHCHOCIIICOHCHIOC()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHOCHCOIHOCCORORIORHICRCCIOICH,
               var1
                  || !IICCOOCHCHROORHHIIHROHCCRHRCOR.IRHCOOHHRHIRCRHHROCRHCHIOIROHH()
                  || IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen() == null
            );
      }
   }

   public boolean HOOCOOIRHCHIICICHOICHCOIRICIHI() {
      return this.ROHIICRIRROCRHRHOOHORCIRHOIOII != null
         && this.ROHIICRIRROCRHRHOOHORCIRHOIOII.OHOHCHORHIIHCCOIHOHCCICRHHICIR().OIHHOCRIHHRHIIHIHOCORIRCHHIRIC().get()
            == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.VANILLA;
   }

   public static Optional<File> HORHRIOCOOOORHCRIHHORCRIRCOOCI() {
      return Optional.ofNullable(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.CHHRCIOCRCCOOCIRCRRCCHOCOHOIOC);
   }

   public static Optional<File> IIHICIOCICHCOIOCHCIOOHHRHRHIRC() {
      return Optional.ofNullable(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.ORHOOOCOOHROHRCOCOOHIRIHIIOROI);
   }

   public static Optional<File> OCHCHCCROOCOHHOIOHRRHCROICOOHI() {
      return Optional.ofNullable(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.OHRRIHCCHIOOOHRORORIHHHOOIOOII);
   }

   public static Optional<File> HIIHRIHORROOHHHIHROHCOIROIIIOO() {
      return Optional.ofNullable(IRRCHICCRHCHRRCHIOHIIRIORIRHRI.RRRICIIICRIICCOHRRROCHIORHCRCR);
   }

   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0) {
      if (OHRIIRHRIHOCCHORCORHICIOHHHOIC != null) {
         throw new IllegalStateException("Lunar is already initialized");
      }

      OHRIIRHRIHOCCHORCORHICIOHHHOIC = var0;
   }

   @Generated
   public IRCIIHHICIHRCOCRROCOICRIHHCCHH RROHIIOHORHICRHIHCCRRRHIHCHRCC() {
      return this.COOHOHRHHICRHIORRORHIOOIIHRHHI;
   }

   @Generated
   public com.moonsworth.lunar.client.IOIICIRIICICIIOORHCIIIIRRIHRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IIRIROIRHRRRHRRHCROIRHCROCCCOC() {
      return this.IOOHIHOOOCICOHHCHHOHHRCOHIOHRC;
   }

   @Generated
   public CRRRICCRROCOHHOHIICIHORCOORRRH ORHHIORCCIOHCRRHOCHCHORIHHROOO() {
      return this.OHOOOOOIHOIROIHIRCIOCIRHIIRIOR;
   }

   @Generated
   public HCHRIROHHHCORIOCROOCHRCIOROOCI IOORROIRICCOCCOOCCIROIIIHRCCCC() {
      return this.CRHOICICCRIHHRRRICIHIIROCRROOR;
   }

   @Generated
   public com.moonsworth.lunar.client.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCOIHOICHRIIHOCCCIHRRHHRROORCR() {
      return this.CCIOHRRCIROCHOORCRCRHRORIOOOOO;
   }

   @Generated
   public com.moonsworth.lunar.client.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IHOOORHRIIRHRCCCCORHRIRHIROHIO() {
      return this.ORRIOOIROHHROIRCIIHIOOCIOOIIOO;
   }

   @Generated
   public boolean IIIOHRRCOOORCCICORHROCCHCRRRIR() {
      return this.OCCHIHRHRHIROIOCOCICRRRHIORRRH;
   }

   @Generated
   public String getWorld() {
      return this.world;
   }

   @Generated
   public RRCRRCORICCHOHHIRCHIROOHIIOHCO HCHRCOICHOOIOROORHRIIIOIIHIHOC() {
      return this.IRCCRRIOIROIORCOICRROIOOCIOOCH;
   }

   @Generated
   public Set<RIOOCHICIHRHOHCCCCCHOCCCOHCRHI> HOHCOIRRHIICOCOORHHRRRCRIOOIHR() {
      return this.OROHIHCCRHRHOOHIOHHOICHIOHIOCO;
   }

   @Generated
   public IHIRRIIORRHORHRORIHOROIRCORCOO HHCCIRORCRCHOIOHRRIRRRIORRCRRR() {
      return this.RIRRCRRIHRORROIOOHIHIOCRIROOHC;
   }

   @Generated
   public HHRIICOIOORCHCOIICOOIHIRHHICRI HHHIHROORHHOOCCOOCHRIRHRHCRHIH() {
      return this.ROHIICRIRROCRHRHOOHORCIRHOIOII;
   }

   @Generated
   public OHHRIOHROOIHOROCIRHCHORIHRRRRI RCCICCRCRHHRIHHRHIHCCCOIHHRCCH() {
      return this.HROORRHRIICCHICHORHOHCCORICIIH;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ICRIOCOOICRIIIRIHIRIOIHCOHHIIC() {
      return this.CCIOHCIIORCIOIHHCOHHIHIHCHOCRC;
   }

   @Generated
   public OHIIIOHIRIRCCRRIOIICCHHIORRHOH HRCRHCHRCCRIOHCCCOCRCICORHRRCI() {
      return this.HRHHOCIORIIRRHIOORIORHOIHHROOH;
   }

   @Generated
   public IIHRRHORCRCROCHHOHORCHCROCIHRO COOCRCHRIOOCHCIHCIOCHHIOOIRHIC() {
      return this.OCHRCCCICRIOCRCOORCIRCHRIHOIRO;
   }

   @Generated
   public OOCCRCRCOHIIORCCORCRCIRRROIOOR RHOOIIHCIOORCHHHRCHORROICICIHO() {
      return this.HRIOCRHIOOHOHOCRCROIIRORHICICC;
   }

   @Generated
   public com.moonsworth.lunar.client.ICICIOCHHHIHOCHCOHORIHRCOHHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ICOIRCOIORIRIIRIRRHCROCCICOHOR() {
      return this.CCCIOOHOCOCHCRIRHIIORCRIOOIRHO;
   }

   @Generated
   public IIHRHCCOOHOOOOCHRRCOROOIOHCOOO HOHHHORIIORRRROHRIIRCHCCICHHCI() {
      return this.OHIROHHCCHRIIORCHRCOIICOHOOCOO;
   }

   @Generated
   public OCOHORHCROHICRRIHCIHHRRCIHICRI IHHIHIOCIRRCRRORORHHHRIHCCCOCO() {
      return this.HROHRRCRRHOIRHIRICOOROHRRRORIH;
   }

   @Generated
   public IHHCHHHCRIHOOCOIOOCRIIICIOROIR RORROHRORCOOOOHRROHIOHCRHHCRCO() {
      return this.IOHOCCRORRHOHRROHCIHIIROIHRHOO;
   }

   @Generated
   public IIRHCHHOICHRICOOCRORCCIOOIHOIR OIICRCOIOOHOOHORCRCIOHRCOIIHIC() {
      return this.CHIOCHOIHHHCHOIHHIIHIOHCRHRIII;
   }

   @Generated
   public OOROOCCIRCCRHOIOIORIHCHHOOCCOR IORIICHCCOROCHIIIICCCOCIHCHHHO() {
      return this.OIORROROOROHHRIIORIHHHOCIIHRRC;
   }

   @Generated
   public CORCOCICIRIOHROHROIIOOHICCHCRR HCCICHCRRIICICCHCIRCRRIIRROHHC() {
      return this.RHHROIIIHCCIHOCOCOHCHIHIOOIRIO;
   }

   @Generated
   public RIROICHCRROROHCCROOCCCCOCHCCRI IHIHCOIRIHIRHICORCCHCOOICIIOIC() {
      return this.OCIRIHHHIICCRCHICCCHHHHIOHCHHH;
   }

   @Generated
   public ORHIOICIOCRRHOOCOHRORIHICHRCRR RCRIIICORIICOIIOHIIHICCCOCRICC() {
      return this.RCIICOICCOIOCCCHCOOCCRHRIHOOHI;
   }

   @Generated
   public CRICCOOHHHCHOORCICOCOHIHOIRHOO ICHHCOOCHRRHICRROCROHIRCCRRHOC() {
      return this.IROHORIIHOCCORRIHICCROIHRRIRCI;
   }

   @Generated
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO IOICCCHOCCOIIHICRCIRIRROHRCHCC() {
      return this.HOHIROROCHIROOCCROHOCOORCHCORC;
   }

   @Generated
   public IOIICIRIICICIIOORHCIIIIRRIHRHI IOOOCCROCOCHCICCHIHOCCRHROHOHC() {
      return this.CIIHCIOHIICOOOOIIOIRCICRRICCOH;
   }

   @Generated
   public ICICIOCHHHIHOCHCOHORIHRCOHHOCR OORRROHOHHOOROORRRCCCOCCOOCCHI() {
      return this.CRHHOHCOORHRIIRCHCHCORIIORCOHC;
   }

   @Generated
   public CRHROHHHCIHHCOHCOORCRIHHIICROR RHIIORHOIHHICHORHRIRHIIROCHOHO() {
      return this.HORCOHHRCCOICRCIOHHRRHHCRHCCOR;
   }

   @Generated
   public HHCCIRHCCCIIRHCROHIORHIRHHIORH RCCIROHIHIOOOIOOCIRORHCRROIROR() {
      return this.OCCCOHHOICRHORIICHHRCCCRHOOCII;
   }

   @Generated
   public ROOCOCCCIRHHHIRIOIHHHHRHIICHHR RICRRCRROIHCOOOCHCRROCHIOCOORI() {
      return this.OOIOOICRHHHIICOHOHCOHCRRRCRCHH;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI RCROOHHCROORIIICHORIHRROIOOHHC() {
      return this.RRICCCRROHRIHHIOCIRCOCCIRHHIIO;
   }

   @Generated
   public RICRIRRCOHRCOCRRHHCRHRROOIOHHR CROHIOCIRCHHOROIOOROHIRHRHRORR() {
      return this.CRHOICIHHOCICHICICRRORHOHRIROH;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO HOHOOIHHIHCRCCROOCIOOIHCRCHICR() {
      return this.HRCHHIRIHROOIHHRCHICORRROHRCRR;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH OIHHCIOCHOCOIHCICOOIOICCRICORH() {
      return this.RRIOIROCRCCCCROHHCRHOOROOHRROI;
   }

   @Generated
   public IRRCCOICORICIHCHRHIHIHROIRHOCR CCHHHHCICRCCCIOOIOICOOCRCRHCCR() {
      return this.ORRHICRCROIRCICRCCIRRIRHCRICRI;
   }

   @Generated
   public com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.IRCIIHHICIHRCOCRROCOICRIHHCCHH IHIHHCICIRHOCHCIOCIORCCOCHORHC() {
      return this.ICRIIOCRRORIOIIRORHORIOHHCCOCO;
   }

   @Generated
   public com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR IHCHHRRIIIORORCHIICIIOORCOIOIO() {
      return this.HCRCHOCOIOIIIRRCOIOORIHHRIIROO;
   }

   @Generated
   public RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO RCRHICHHOOHCRHHCCCHCHIIRRHHRRH() {
      return this.HRHIRCRROIHRIOHCOOCCHIHCCROHRR;
   }

   @Generated
   public IRCRRHRCIRHIHIHROHCRRHIIHHHHCH HHRIHOIIOIRRCHRHRIHIRICOIHRHRO() {
      return this.OIRHCCHIOOIIIOIRCHCOHOHOIOCIOC;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCRRCCORORHORHOOIOIRCROCIROOCR() {
      return this.IOHCCHCCHHRRRICOCRHHIRICCCCOOO;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH OIOOIHRRCRIIOCCRROOOROOIOCCOHO() {
      return this.RICIRORIRHHIHIICHOHROROHRIIOOR;
   }

   @Generated
   public com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI CICIHRIOIHHROIRHIIRORIOIIRCIRR() {
      return this.HHHROIRRRRCHCHROHCORIIOHOIIOCC;
   }

   @Generated
   public RIRHOCHIORCCIIOIIRHOCCCRHHCHHH HIROOIRICIRHIHHIIIRCIOHHHIOHIC() {
      return this.IRROIHHOOHCIOHICHHROOOCOCHCCOI;
   }

   @Generated
   public com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HOIOHRCOCOOHHCHHHHROHHCOCOOOHI() {
      return this.IOIOORHICOIOOHCRIIROHCIROICCCO;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH RHCHCCIOOCORHOHICHOIOHRIOCCIHC() {
      return this.OHORCIHORHOCIRIIIRCCRHRCOCCHCH;
   }

   @Generated
   public IHICORCROOROHCIHIHCOIHRRHICICO HRHHIRHOCROHRRCRHIHCRIIRIOHHOH() {
      return this.HIRROHCROOOIRHOOCRIRRORORIIRCI;
   }

   @Generated
   public OIHCOHRCICCCRHRCROOCIOIRRHHHIH HOICCHRHOCIORIICICCOOIHRRHIIOR() {
      return this.CRHHIRIIHRRIRCOHRIORHORCOCIHHI;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OCOHORHCROHICRRIHCIHHRRCIHICRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR CRHHCROOHRIIHCRRHOHRRCROOHICOO() {
      return this.ICRIHROIRHIHOCOOCRCHCHRRCHOHHC;
   }

   @Generated
   public com.moonsworth.lunar.client.OCOHORHCROHICRRIHCIHHRRCIHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH CCRHICOCOHIIRIHCOCIRCHHROHCCRR() {
      return this.RCRCORCICHOIHRHRCICOCCIRHIHICR;
   }

   @Generated
   public IHCRORHRORIICHRHRCHRRIRRHHOCOO IHORRHHCCOHHOCOHOCCHRROHIHHROC() {
      return this.CIRORIOCCCICOHIHRICOHOCIICIOIH;
   }

   @Generated
   public HICRRICCHCCROOHHCHOCOCCHOIHHOC OOHHHCORHROHOROOOHROROCCCCIICI() {
      return this.HCORIRRICOOCHCORIIIROIOCHOCCCR;
   }

   @Generated
   public com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH CIRCCCHCCCROROIIOIHIOROIHCHRCH() {
      return this.HHOHOCIOHIHHCCOCIOROCIHRORCIHI;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HCCICHICCIRRRHIIIIHOIOIRIOHCCI() {
      return this.ROOCHOCCIHCIIIRHHCROCIHHCICOIH;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH OOCROCIOHHCIIROICOCRHCCCHRCIOI() {
      return this.CORROIRHRRIHCRHIROHHORCCHIIRCO;
   }

   @Generated
   public RCIROOOOICRHCCRRCIORHHIRCOIIIC IHHIHCIHHHCORHHHOIOOOCHOOIIRRH() {
      return this.ROORROCCCRCRCOHHOROROIRHCIROHR;
   }

   @Generated
   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH IOHRIRCHOCIOIOIHIHOCCCHOHOHOCH() {
      return this.CCICICRIROHROHHOICIRHICOICIICC;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HRRCCIHOOORRIHCCRORRCRHRIICRRH() {
      return this.ORCROCOOIHHHHOOHOIRIIHHCRIHIRR;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HIROIHOHCHRCCRRCROCIIHOCHICCOO() {
      return this.RCRIHICRIIROCHHHHCROCRCHHRIIOI;
   }

   @Generated
   public CCIHHRIOOOOCOHRCIHOHROOICIORCC HOOCCHIIOIRIIRRIRHRROHOHHRHROI() {
      return this.OHOHORIHRCRCORIRRIRCCRHOHORIRI;
   }

   @Generated
   public com.moonsworth.lunar.client.OOCCRCRCOHIIORCCORCRCIRRROIOOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HCCRCICOCHOIHHHICIROOIOOCROCII() {
      return this.CRCHORHCICOCRCCHOOCICICRIOCOIC;
   }

   @Generated
   public com.moonsworth.lunar.client.RCIROOOOICRHCCRRCIORHHIRCOIIIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HHOIROCHCHORIOOOIHCIIIRHIORIIH() {
      return this.IIROIIIIICHCROIIORRHCOOHHHCOHH;
   }

   @Generated
   public IOHHOIIOCRHCHHCRORICCOHOHROOIH HRICIIRCIHIRHHOCIICHOHOHHHOOHI() {
      return this.CIRRIOOCOIROROOOIHIRIHOORRRIOO;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH HCOHROCRRIIHOORRCCROCROICRICIC() {
      return this.HIOIHCRCIHHCIHIHRRCROICIRIIHCR;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CHIROHOORHIRORIORHOHORHOHHHOOH() {
      return this.OICHRIIHIORHOOOIOCHHOCRORIHIOH;
   }

   @Generated
   public com.moonsworth.lunar.client.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCICCRRICHCCRHHCOCOIRCRIICCOIH() {
      return this.RCHHCIORHROICHORIROHHOOHHCRIHO;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCICHRRIHOHCCHRORHIIOCHCROHRIC() {
      return this.HRIOHCCIOOIORHRHCIRCRRIIOHCHHI;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH IIORRHCROCRRCCIIOHOICORIROIOCH() {
      return this.HIRHRCRHCHCIICCIOOCROHOOIOIRHH;
   }

   @Generated
   public RORCHCIIICOHIRROOORHOCCCCIOCCI HCCHICOOHHCOOIRCHRCRICOCRIHHHC() {
      return this.IIRORHHOIHCICOROIIIRRIHHRHIHOC;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HHCHCOIHCIIROIOIOCHOOORRCOIHCI() {
      return this.CIHCCOCICROCOOCOCCOCRHOCIHRCRO;
   }

   @Generated
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH RROIIICIHOROCICRICHOOROIROHIRH() {
      return this.RROOHCOHROIIROCRCRICHOHHCCOOCR;
   }

   @Generated
   public com.moonsworth.lunar.client.OIHCOHRCICCCRHRCROOCIOIRRHHHIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH ORCOCROHCRORRCCHRCCHCRRCCCORRH() {
      return this.HOOOHCROCOIRIIRCIIICOCOHRRCOCR;
   }

   @Generated
   public IOHIHIIHCCCCCIHRORIOIOORCIOHII COIIOIICHIIHIIRCOHCHIHHRHROCRO() {
      return this.COCOCCIORORHIIROHIOIOHIHCRIOOO;
   }

   @Generated
   public com.moonsworth.lunar.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ORIIIHRRCOIHCRCHOHHIICIHCRCICR() {
      return this.HIIIRHIIHCIOOCCCCRCHRRRHCROOCC;
   }

   @Generated
   public Optional<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.COIHORRCHRRCHOCIRHHRRIOIHRIHCC.HHCCIRHCCCIIRHCROHIORHIRHHIORH> OHRIHHCHRIORCOCCCOOIOOHIIRIOII() {
      return this.RHRRROIHCRIICHOORRIHCOCHCHCHCR;
   }

   @Generated
   public com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHCCIRHCCCIIRHCROHIORHIRHHIORH CRRRROHRROIHHICOIRCOIRRCHHIIHC() {
      return this.RRCCCRRROOIIRHCROOROOIHHHRIRCH;
   }

   @Nullable
   @Generated
   public Map<String, Boolean> IOCCCHCCCCHRROCOIOHCIOHHCCIROO() {
      return this.RCIIHOCRHIIIRHHCHCORHIOHHROIOR;
   }

   @Generated
   public static RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CCIHHCIOHIHIRHICIHROCOOCCCCCCR() {
      return OHRIIRHRIHOCCHORCORHICIOHHHOIC;
   }

   @Generated
   public void IHHCHIIHOOHRROCRRRHHHCOOHCOORC(String var1) {
      this.world = var1;
   }

   @Generated
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Optional<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.COIHORRCHRRCHOCIRHHRRIOIHRIHCC.HHCCIRHCCCIIRHCROHIORHIRHHIORH> var1
   ) {
      this.RHRRROIHCRIICHOORRIHCOCHCHCHCR = var1;
   }
}
