package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.OOOOCCOOOHCHCIIHOIHCRIIOOROHRC;
import com.moonsworth.lunar.lib.adventure.text.Component;
import com.moonsworth.lunar.lib.adventure.text.TextComponent;
import com.moonsworth.lunar.lib.adventure.text.format.NamedTextColor;
import com.moonsworth.lunar.lib.adventure.text.format.Style;
import java.util.regex.Pattern;
import lombok.Generated;

public class CORCOCICIRIOHROHROIIOOHICCHCRR {
   private final TextComponent RHIOICICIHIOIICCRCCOCCCRIHOCII;
   private final Pattern HOHIRRIRCIICCIRIRIOCIRCIRRRROR;
   private long startTime = -1L;
   private long RIIHOCROCCIRCHOIRIOHOOIHHRIHCC = -1L;
   private double OHOCHORROIHHOIIIHCCHOIHIRRRHRC = -1.0;
   private double RHCHCHOHHCICRHCCRIORHHHIOIROHR = -1.0;
   private OOOOCCOOOHCHCIIHOIHCRIIOOROHRC IHCRRRCRIIHCCCHIHIOOIHHHIIHROH;
   private double RIRIRHRHRIRRIIICHIIHCOCOHOICRC = -1.0;

   public CORCOCICIRIOHROHROIIOOHICCHCRR(TextComponent var1, String var2) {
      this.RHIOICICIHIOIICCRCCOCCCRIHOCII = var1;
      this.HOHIRRIRCIICCIRIRIOCIRCIRRRROR = Pattern.compile("^" + var2 + "$");
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(CORCOCICIRIOHROHROIIOOHICCHCRR var1) {
      this.RHIOICICIHIOIICCRCCOCCCRIHOCII = var1.IOOOHCHRIIIRIRRCHRICHIHRIOIOHO();
      this.HOHIRRIRCIICCIRIRIOCIRCIRRRROR = var1.IRIIOROCIHRRCCCRIHCRCCORRHCOOO();
      this.OHOCHORROIHHOIIIHCCHOIHIRRRHRC = var1.RIIICICCHHOCCICIHCCCIRRRCCOCRO();
      this.RHCHCHOHHCICRHCCRIORHHHIOIROHR = var1.RIHHICCHCCCORRCHRCRCHOICOHIRHO();
   }

   public double ROIHCCHCCCRIOOIIIRIOHHRCRHIROH() {
      if (this.startTime == -1L) {
         return 0.0;
      } else {
         return this.RIIHOCROCCIRCHOIRIOHOOIHHRIHCC == -1L
            ? (IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() - this.startTime) / 1000.0
            : (this.RIIHOCROCCIRCHOIRIOHOOIHHRIHCC - this.startTime) / 1000.0;
      }
   }

   public TextComponent RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RHOCHHIRRCHHHOHOIRROIROHHHIHIO var1) {
      double var2 = this.ROIHCCHCCCRIOOIIIRIOHHRCRHIROH();
      String var4 = String.format("%." + var1.IRCHHHRIRRRHIHCHCCOHCORRRIICCH().get() + "f", var2) + "s";
      Style var5;
      if (this.startTime == -1L) {
         var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1.CHHHRHORIHIOCIOHIIHROIHICHOCCC()
         );
      } else if (this.RIIHOCROCCIRCHOIRIOHOOIHHRIHCC == -1L) {
         if (var1.HHRCIHCIRHCHCHRHORHHRIRHIRIOCR().get()
               == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OFF
            || !(this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC < 0.0) && !(var2 <= this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC)) {
            if (var1.CHRIHHOIRCRHROROORHIRRIRICCOCR().get()
                  == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OFF
               || !(this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC < 0.0) && !(var2 > this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC)) {
               var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1.CHHHRHORIHIOCIOHIIHROIHICHOCCC()
               );
            } else {
               var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1.CHRIHHOIRCRHROROORHIRRIRICCOCR()
               );
            }
         } else {
            var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1.HHRCIHCIRHCHCHRHORHHRIRHIRIOCR()
            );
         }
      } else if (var1.IIOIORICOCIROOOCOCHICHHROROOCC().get()
            == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OFF
         || !(this.RHCHCHOHHCICRHCCRIORHHHIOIROHR < 0.0) && !(var2 <= this.RHCHCHOHHCICRHCCRIORHHHIOIROHR)) {
         if (var1.HHRCIHCIRHCHCHRHORHHRIRHIRIOCR().get()
               == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OFF
            || !(this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC < 0.0) && !(var2 <= this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC)) {
            if (var1.CHRIHHOIRCRHROROORHIRRIRICCOCR().get()
               != com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OFF
               )
             {
               var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1.CHRIHHOIRCRHROROORHIRRIRICCOCR()
               );
            } else {
               var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1.CHHHRHORIHIOCIOHIIHROIHICHOCCC()
               );
            }
         } else {
            var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1.HHRCIHCIRHCHCHRHORHHRIRHIRIOCR()
            );
         }
      } else {
         var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1.IIOIORICOCIROOOCOCHICHHROROOCC()
         );
      }

      return (TextComponent)Component.text(var4).style(var5);
   }

   public TextComponent IRCIIHHICIHRCOCRROCOICRIHHCCHH(RHOCHHIRRCHHHOHOIRROIROHHHIHIO var1) {
      if (!var1.OCOOOCIOOCORIORRIOCIIORIROICHC().get()) {
         return Component.empty();
      }

      if (this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC < 0.0) {
         return Component.empty();
      }

      double var2 = this.ROIHCCHCCCRIOOIIIRIOHHRCRHIROH();
      return var2 < this.RHCHCHOHHCICRHCCRIORHHHIOIROHR && this.RIIHOCROCCIRCHOIRIOHOOIHHRIHCC == -1L
         ? Component.empty()
         : Component.text(" (" + String.format("%+." + var1.IRCHHHRIRRRHIHCHCCOHCORRRIICCH().get() + "f", var2 - this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC) + "s)");
   }

   public TextComponent HHCCIRHCCCIIRHCROHIORHIRHHIORH(RHOCHHIRRCHHHOHOIRROIROHHHIHIO var1) {
      TextComponent var2 = (TextComponent)this.RHIOICICIHIOIICCRCCOCCCRIHOCII.append(Component.text(": "));
      TextComponent var3 = (TextComponent)this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1).append(this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1));
      TextComponent var4 = (TextComponent)((TextComponent)Component.empty().append(var2)).append(var3);
      if (var1.IOORCRCOOHICHCOCOHICHHIRIIRRHH().get()) {
         String var5 = this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH != null
            ? " (" + this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH.RRHIICCHIOCIHCOIHHIROHCHCOHOHO() + ")"
            : " (0.00s)";
         var4 = (TextComponent)var4.append(Component.text(var5).color(NamedTextColor.GRAY));
      }

      return var4;
   }

   public void start(int var1) {
      this.startTime = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() + var1;
      if (this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH != null) {
         this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH.destroy();
      }

      this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH = new OOOOCCOOOHCHCIIHOIHCRIIOOROHRC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
         .OIRHHRHOICCRORRCOOROHIOROHHCRI()
         .IICCOOCHCHROORHHIIHROHCCRHRCOR(-var1)
         .CRHOOHHCIOOCCHRCRICCIICIOHHCRR(true)
         .OHRHHOOHHCRORRROIROCHORCROHHCI()
         .HRHIIHCRHHIIHCHCOHHHROORIIHOCR();
   }

   public void start() {
      this.start(0);
   }

   public void stop() {
      this.RIIHOCROCCIRCHOIRIOHOOIHHRIHCC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
      if (this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH != null) {
         this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH.stop();
      }
   }

   public void reset() {
      this.startTime = -1L;
      this.RIIHOCROCCIRCHOIRIOHOOIHHRIHCC = -1L;
      if (this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH != null) {
         this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH.destroy();
         this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH = null;
      }
   }

   public void RCCCROCHCICCROHCOCCRRROCIIHCCH(double var1) {
      this.OHOCHORROIHHOIIIHCCHOIHIRRRHRC = var1;
      this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC = var1;
   }

   @Generated
   public TextComponent IOOOHCHRIIIRIRRCHRICHIHRIOIOHO() {
      return this.RHIOICICIHIOIICCRCCOCCCRIHOCII;
   }

   @Generated
   public Pattern IRIIOROCIHRRCCCRIHCRCCORRHCOOO() {
      return this.HOHIRRIRCIICCIRIRIOCIRCIRRRROR;
   }

   @Generated
   public long getStartTime() {
      return this.startTime;
   }

   @Generated
   public long ROHIICRIRROCRHRHOOHORCIRHOIOII() {
      return this.RIIHOCROCCIRCHOIRIOHOOIHHRIHCC;
   }

   @Generated
   public double RIIICICCHHOCCICIHCCCIRRRCCOCRO() {
      return this.OHOCHORROIHHOIIIHCCHOIHIRRRHRC;
   }

   @Generated
   public double RIHHICCHCCCORRCHRCRCHOICOHIRHO() {
      return this.RHCHCHOHHCICRHCCRIORHHHIOIROHR;
   }

   @Generated
   public OOOOCCOOOHCHCIIHOIHCRIIOOROHRC IRHIOHCROIRIHCICOOIOHRRICRCHRI() {
      return this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH;
   }

   @Generated
   public double CHRORRIRRHCCHICOIHHCHHRIIORRHI() {
      return this.RIRIRHRHRIRRIIICHIIHCOCOHOICRC;
   }

   @Generated
   public void IIOIROIHIHHCCRICRCOOCHIICHRCOI(long var1) {
      this.startTime = var1;
   }

   @Generated
   public void RHOORRIIOCHIRRHOHOOHIROHCRICRO(long var1) {
      this.RIIHOCROCCIRCHOIRIOHOOIHHRIHCC = var1;
   }

   @Generated
   public void OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(double var1) {
      this.OHOCHORROIHHOIIIHCCHOIHIRRRHRC = var1;
   }

   @Generated
   public void RHRRHOHCRCHCCRRHOHHIRCCHOCICHC(double var1) {
      this.RHCHCHOHHCICRHCCRIORHHHIOIROHR = var1;
   }

   @Generated
   public void CRRRICCRROCOHHOHIICIHORCOORRRH(OOOOCCOOOHCHCIIHOIHCRIIOOROHRC var1) {
      this.IHCRRRCRIIHCCCHIHIOOIHHHIIHROH = var1;
   }
}
