package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RIROICHCRROROHCCROOCCCCOCHCCRI;
import java.util.Set;

public class RRCRRCORICCHOHHIRCHIROOHIIOHCO
   extends com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH {
   private static final long COIRCRRIIRIIROHIIIRORCROHIHROO = 29L;

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2,
      CRRRICCRROCOHHOHIICIHORCOORRRH[] var3,
      CRRRICCRROCOHHOHIICIHORCOORRRH[] var4
   ) {
      super(var1, var2, var3, var4);
   }

   protected RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      super(var1);
   }

   protected RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var2
   ) {
      super(var1, var2);
   }

   protected RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var2,
      Object var3
   ) {
      super(var1, var2, var3);
   }

   protected RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      Set<String> var2,
      Set<String> var3
   ) {
      super(var1, var2, var3);
   }

   protected RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      CRRRICCRROCOHHOHIICIHORCOORRRH[] var2,
      CRRRICCRROCOHHOHIICIHORCOORRRH[] var3
   ) {
      super(var1, var2, var3);
   }

   @Deprecated
   public static RRCRRCORICCHOHHIRCHIROOHIIOHCO COIHORRCHRRCHOCIRHHRRIOIHRIHCC(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var0
   ) {
      return new RRCRRCORICCHOHHIRCHIROOHIIOHCO(var0, null, OORCOORICOCHHRRHRRCCCROOHOHCHO, null);
   }

   public static RRCRRCORICCHOHHIRCHIROOHIIOHCO RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var0,
      RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var1
   ) {
      return new RRCRRCORICCHOHHIRCHIROOHIIOHCO(var0, var1, OORCOORICOCHHRRHRRCCCROOHOHCHO, null);
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> unwrappingSerializer(
      RIROICHCRROROHCCROOCCCCOCHCCRI var1
   ) {
      return new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICRRICCHCCROOHHCHOCOCCHOIHHOC(
         this, var1
      );
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var1
   ) {
      return new RRCRRCORICCHOHHIRCHIROOHIIOHCO(this, var1, this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC);
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH RICRHCHRRCCIICRCHICCIHHHCIICOH(
      Object var1
   ) {
      return new RRCRRCORICCHOHHIRCHIROOHIIOHCO(this, this.CRRCRCIIOHCRROOROCIOOHCICHRIHR, var1);
   }

   @Override
   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
      Set<String> var1, Set<String> var2
   ) {
      return new RRCRRCORICCHOHHIRCHIROOHIIOHCO(this, var1, var2);
   }

   @Override
   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      CRRRICCRROCOHHOHIICIHORCOORRRH[] var1, CRRRICCRROCOHHOHIICIHORCOORRRH[] var2
   ) {
      return new RRCRRCORICCHOHHIRCHIROOHIIOHCO(this, var1, var2);
   }

   @Override
   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH RCOCRCOCHHRCIHCOIIIROIIOOHIOOC() {
      return this.CRRCRCIIOHCRROOROCIOOHCICHRIHR == null && this.HICIHORCICIORRCOIOOHRRHCOHIIIO == null && this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC == null
         ? new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            this
         )
         : this;
   }

   @Override
   public final void serialize(
      Object var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
   ) {
      if (this.CRRCRCIIOHCRROOROCIOOHCICHRIHR != null) {
         var2.IHHCHIIHOOHRROCRRRHHHCOOHCOORC(var1);
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, true);
      } else {
         var2.IRRIHROCORIOOCHHCHCHOHCIOHHRRI(var1);
         if (this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC != null) {
            this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1, var2, var3);
         } else {
            this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, var2, var3);
         }

         var2.RORCROIROCHHOOICHRICCCRHROHROC();
      }
   }

   @Override
   public String toString() {
      return "BeanSerializer for " + this.handledType().getName();
   }
}
