package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

public interface RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   void IHICORCROOROHCIHIHCOIHRRHICICO(byte[] var1, int var2, int var3);
}
