package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHRIOOOOCOHRCIHOHROOICIORCC;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import java.io.Serializable;

public class IRRCCOICORICIHCHRHIHIHROIRHOCR implements Serializable {
   private static final long OCHHCIICCROICHCRRRROIICIROHRIO = 1L;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI HIICHORRIRCOHOROOIRCCRHRHIHRHH;
   public final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHCRORHRORIICHRHRCHRRIRRHHOCOO HHCRIROROHHRRCRICIOOIOHCHOHRIC;
   public final CCIHHRIOOOOCOHRCIHOHROOICIORCC<?> OHRROIOICICOICCICOHCRCHOIHCORH;
   public final RORCHCIIICOHIRROOORHOCCCCIOCCI CCOCRIOIHHIHHCOCROCCHHRHIHICCR;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> OOOROHICCCOIROIRRORCRHCCRCRICR;
   public final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIROICHCRROROHCCROOCCCCOCHCCRI HHHIICCIHCIRHROIRIOOOCOOHCORIO;

   protected IRRCCOICORICIHCHRHIHIHROIRHOCR(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHCRORHRORIICHRHRCHRRIRRHHOCOO var2,
      CCIHHRIOOOOCOHRCIHOHROOICIORCC<?> var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<?> var4,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIROICHCRROROHCCROOCCCCOCHCCRI var5,
      RORCHCIIICOHIRROOORHOCCCCIOCCI var6
   ) {
      this.HIICHORRIRCOHOROOIRCCRHRHIHRHH = var1;
      this.HHCRIROROHHRRCRICIOOIOHCHOHRIC = var2;
      this.OHRROIOICICOICCICOHCRCHOIHCORH = var3;
      this.CCOCRIOIHHIHHCOCROCCHHRHIHICCR = var6;
      this.OOOROHICCCOIROIRRORCRHCCRCRICR = var4;
      this.HHHIICCIHCIRHROIRIOOOCOOHCORIO = var5;
   }

   public static IRRCCOICORICIHCHRHIHIHROIRHOCR RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var0,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHCRORHRORIICHRHRCHRRIRRHHOCOO var1,
      CCIHHRIOOOOCOHRCIHOHROOICIORCC<?> var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<?> var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIROICHCRROROHCCROOCCCCOCHCCRI var4,
      RORCHCIIICOHIRROOORHOCCCCIOCCI var5
   ) {
      return new IRRCCOICORICIHCHRHIHIHROIRHOCR(var0, var1, var2, var3, var4, var5);
   }

   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR<Object> CICCIRRCCCRICCCIICHOOCROHIOOCC() {
      return this.OOOROHICCCOIROIRRORCRHCCRCRICR;
   }

   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI OROHHRIICHCIOOOIOICCCOHROCHROH() {
      return this.HIICHORRIRCOHOROOIRCCRHRHIHRHH;
   }

   public boolean HRCIORRCROHRORIIIICRCCCRICIOCI() {
      return this.OHRROIOICICOICCICOHCRCHOIHCORH.HRCIORRCROHRORIIIICRCCCRICIOCI();
   }

   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var1, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      return this.OHRROIOICICOICCICOHCRCHOIHCORH.HICRRICCHCCROOHHCHOCOCCHOIHHOC(var1, var2);
   }

   public Object OOCCRCRCOHIIORCCORCRCIRRROIOOR(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2
   ) {
      return this.OOOROHICCCOIROIRRORCRHCCRCRICR.deserialize(var1, var2);
   }
}
