package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;

import java.util.concurrent.Executor;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends RRCRRCORICCHOHHIRCHIROOHIIOHCO {
   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(String var1, Executor var2) {
      super(
         var1,
         var2,
         CRRRICCRROCOHHOHIICIHORCOORRRH.HRICRICHOHHRRCCORRHHOOHIHOHHCH(),
         RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OICRIOOOIOHRCRCCOOIOHRRRCOOHRO
      );
   }

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(Executor var1, CORCOCICIRIOHROHROIIOOHICCHCRR var2) {
      super("default", var1, CRRRICCRROCOHHOHIICIHORCOORRRH.HRICRICHOHHRRCCORRHHOOHIHOHHCH(), var2);
   }

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(Executor var1) {
      super(
         "default",
         var1,
         CRRRICCRROCOHHOHIICIHORCOORRRH.HRICRICHOHHRRCCORRHHOOHIHOHHCH(),
         RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OICRIOOOIOHRCRCCOOIOHRRRCOOHRO
      );
   }
}
