package com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.google.common.collect.ImmutableList;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;
import com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.client.util.IOIOHIORIROHRRCOOOHCROHORCOIIH;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.Generated;

public final class IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private static final IOIOHIORIROHRRCOOOHCROHORCOIIH CRHICRIRHCOHCICRCRROCIOOCICRHH = new IOIOHIORIROHRRCOOOHCROHORCOIIH(
      "key.keyboard.unknown", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NONE, 0
   );
   private static final Map<String, IOIOHIORIROHRRCOOOHCROHORCOIIH> OOIOIHIOHCICCOIIRCIRCOCHRRCHCO = new HashMap<>();
   private static final Map<Integer, IOIOHIORIROHRRCOOOHCROHORCOIIH> CHICCORCOHRHCORICIRRCRIOCOICOR = new HashMap<>();
   private static final Map<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH, IOIOHIORIROHRRCOOOHCROHORCOIIH> ICRIHOORIRHIOHOOCRROHOIOCRHIHO = new HashMap<>();
   private static JsonObject IHHHIHOHOOHOHCIIRHIIICCRHCRRRR = new JsonObject();
   private static com.moonsworth.lunar.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH OOICRIICOOHRRRCIIRICROHOHOIHHR;
   private static final List<HHCCIRHCCCIIRHCROHIORHIRHHIORH> HIOHIRIHICICOHOCRCHRRHIHHORHOI = ImmutableList.of(new CRRRICCRROCOHHOHIICIHORCOORRRH());
   private static final List<HHCCIRHCCCIIRHCROHIORHIRHHIORH> OOCHCOCCOROORIIOICORHCOIHRIIRR = ImmutableList.of(
      new com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(),
      new com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH()
   );
   private static final List<HHCCIRHCCCIIRHCROHIORHIRHHIORH> HHHCCCIICRIRROIHRRCICHHICIHRCI = ImmutableList.of(
      new com.moonsworth.lunar.client.CCIHHRIOOOOCOHRCIHOHROOICIORCC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
   );
   private static boolean dirty = true;
   private static boolean initialized = false;

   public static void OOCCRCRCOHIIORCCORCRCIRRROIOOR(File var0) {
      try {
         File var1 = new File(var0, "optionsLC.txt");
         if (!var1.exists()) {
            return;
         }

         JsonParser var2 = new JsonParser();
         JsonElement var3 = var2.parse(new FileReader(var1));
         if (var3.isJsonObject()) {
            IHHHIHOHOOHOHCIIRHIIICCRHCRRRR = var3.getAsJsonObject();
            String var4 = IHHHIHOHOOHOHCIIRHIIICCRHCRRRR.has("lastLaunchedVersion")
               ? IHHHIHOHOOHOHCIIRHIIICCRHCRRRR.get("lastLaunchedVersion").getAsString()
               : "";
            OOICRIICOOHRRRCIIRICROHOHOIHHR = com.moonsworth.lunar.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.get(var4)
               .orElse(com.moonsworth.lunar.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CHRHIIHHCIHIICRCHOOOOCOCIIROHC);
            com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH("Loaded File: Options");
            initialized = true;
         }
      } catch (Exception var5) {
         com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH(
            "Couldn't load file [" + var5.getMessage() + "]"
         );
         var5.printStackTrace();
      }
   }

   public static void OHIIIOHIRIRCCRRIOIICCHHIORRHOH(File var0) {
      dirty = false;

      try {
         File var1 = new File(var0, "optionsLC.txt");
         if (!var1.exists() && !var1.createNewFile()) {
            com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
               "Saving", "Failed to create save file!"
            );
            return;
         }

         if (HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IOCICCRHICIIROIOICRCHOCHIHHOOH().isPresent() && !HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IRRIHCHHIOHRIHCOHHHRHROOHOIRRH()) {
            IHHHIHOHOOHOHCIIRHIIICCRHCRRRR.add("maxFPS", new JsonPrimitive(HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IOCICCRHICIIROIOICRCHOCHIHHOOH().getAsInt()));
         }

         IHHHIHOHOOHOHCIIRHIIICCRHCRRRR.addProperty(
            "lastLaunchedVersion", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.getMinecraftVersion().toString()
         );

         try (FileWriter var2 = new FileWriter(var1)) {
            IIRHCHHOICHRICOOCRORCCIOOIHOIR.ORHHIICRRIOIOHCHHCHHHRCIORCHRI.toJson(IHHHIHOHOOHOHCIIRHIIICCRHCRRRR, var2);
            com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("Saved File: Options");
         }
      } catch (IOException var7) {
         var7.printStackTrace();
      }
   }

   public static JsonPrimitive RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var0, JsonPrimitive var1) {
      try {
         if (IHHHIHOHOOHOHCIIRHIIICCRHCRRRR.has(var0) && !IHHHIHOHOOHOHCIIRHIIICCRHCRRRR.get(var0).isJsonNull()) {
            var1 = IHHHIHOHOOHOHCIIRHIIICCRHCRRRR.get(var0).getAsJsonPrimitive();
         }

         var1 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, HIOHIRIHICICOHOCRCHRRHIHHORHOI, "pre-type");
         var1 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, OOCHCOCCOROORIIOICORHCOIHRIIRR, "base converter");
         var1 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, HHHCCCIICRIRROIHRRCICHHICIHRCI, "fov converter");
      } catch (Exception var3) {
         com.moonsworth.lunar.client.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, "Setting Conversion");
      }

      return var1;
   }

   public static JsonPrimitive RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var0, JsonPrimitive var1, List<HHCCIRHCCCIIRHCROHIORHIRHHIORH> var2, String var3) {
      for (HHCCIRHCCCIIRHCROHIORHIRHHIORH var5 : var2) {
         if (var5.HHCCIRHCCCIIRHCROHIORHIRHHIORH(OOICRIICOOHRRRCIIRICROHOHOIHHR)) {
            if (dirty) {
               var1 = var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1);
            } else {
               JsonPrimitive var6 = var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1);
               if (!var6.equals(var1)) {
                  dirty = true;
               }

               var1 = var6;
            }
         }
      }

      return var1;
   }

   public static void HIIHHIORRHCCIRICCOIOCICHOOIICC(String var0) {
      String[] var1 = var0.split(":");
      String var2 = var1[0];
      String var3 = var1.length >= 2 ? var0.substring(var2.length() + 1) : "";
      IHHHIHOHOOHOHCIIRHIIICCRHCRRRR.addProperty(var2, var3);
   }

   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var0, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, int var2
   ) {
      IOIOHIORIROHRRCOOOHCROHORCOIIH var3 = new IOIOHIORIROHRRCOOOHCROHORCOIIH(var0, var1, var2);
      OOIOIHIOHCICCOIIRCIRCOCHRRCHCO.put(var0, var3);
      CHICCORCOHRHCORICIRRCRIOCOICOR.put(var2, var3);
      ICRIHOORIRHIOHOOCRROHOIOCRHIHO.put(var1, var3);
   }

   public static com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH OHCOCHRROHHHHOIRROORROROHHIOCR(
      String var0
   ) {
      return OOIOIHIOHCICCOIIRCIRCOCHRRCHCO.getOrDefault(var0, CRHICRIRHCOHCICRCRROCIOOCICRHH).CCICCIOCIHOOIHCIRCHHHRROHIHHIH();
   }

   public static com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH OIOCHROIHRRIORCCCIIORRHICHORCR(
      int var0
   ) {
      return CHICCORCOHRHCORICIRRCRIOCOICOR.getOrDefault(var0, CRHICRIRHCOHCICRCRROCIOOCICRHH).CCICCIOCIHOOIHCIRCHHHRROHIHHIH();
   }

   public static String IRRCCOICORICIHCHRHIHIHROIRHOCR(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0
   ) {
      return ICRIHOORIRHIOHOOCRROHOIOCRHIHO.getOrDefault(var0, CRHICRIRHCOHCICRCRROCIOOCICRHH).IRIOOOOCHCCRHORROIRRIIOOOHCOHI();
   }

   public static String RHCCCHORORCCOIRIRHCRRHOIRHCCIH(int var0) {
      return CHICCORCOHRHCORICIRRCRIOCOICOR.getOrDefault(var0, CRHICRIRHCOHCICRCRROCIOOCICRHH).IRIOOOOCHCCRHORROIRRIIOOOHCOHI();
   }

   public static int RICRIRRCOHRCOCRRHHCRHRROOIOHHR(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0
   ) {
      return ICRIHOORIRHIOHOOCRROHOIOCRHIHO.getOrDefault(var0, CRHICRIRHCOHCICRCRROCIOOCICRHH).CROOIRROCHHIIHROIORHRIOHOROOIC();
   }

   public static int IRIIHHRHRORIIHOHIICRICCIICIICC(String var0) {
      return OOIOIHIOHCICCOIIRCIRCOCHRRCHCO.getOrDefault(var0, CRHICRIRHCOHCICRCRROCIOOCICRHH).CROOIRROCHHIIHROIORHRIOHOROOIC();
   }

   public static void IHICORCROOROHCIHIHCOIHRRHICICO(File var0) {
      if (dirty) {
         OHIIIOHIRIRCCRRIOIICCHHIORRHOH(var0);
      }
   }

   @Generated
   private IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
      throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
   }

   @Generated
   public static JsonObject OICRHCRCCICHHHIOOHICHHORCOCHCR() {
      return IHHHIHOHOOHOHCIIRHIIICCRHCRRRR;
   }

   @Generated
   public static boolean isInitialized() {
      return initialized;
   }

   static {
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.mouse.left", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_MOUSE1, -100
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.mouse.right", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_MOUSE2, -99
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.mouse.middle", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_MOUSE3, -98
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.mouse.4", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_MOUSE4, -97
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.mouse.5", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_MOUSE5, -96
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.0", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_0, 11
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.1", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_1, 2
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.2", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_2, 3
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.3", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_3, 4
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.4", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_4, 5
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.5", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_5, 6
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.6", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_6, 7
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.7", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_7, 8
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.8", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_8, 9
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.9", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_9, 10
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.a", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_A, 30
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.b", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_B, 48
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.c", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_C, 46
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.d", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_D, 32
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.e", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_E, 18
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F, 33
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.g", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_G, 34
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.h", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_H, 35
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.i", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_I, 23
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.j", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_J, 36
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.k", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_K, 37
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.l", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_L, 38
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.m", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_M, 50
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.n", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_N, 49
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.o", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_O, 24
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.p", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_P, 25
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.q", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_Q, 16
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.r", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_R, 19
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.s", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_S, 31
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.t", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_T, 20
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.u", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_U, 22
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.v", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_V, 47
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.w", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_W, 17
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.x", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_X, 45
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.y", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_Y, 21
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.z", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_Z, 44
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f1", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F1, 59
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f2", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F2, 60
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f3", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F3, 61
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f4", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F4, 62
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f5", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F5, 63
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f6", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F6, 64
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f7", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F7, 65
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f8", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F8, 66
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f9", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F9, 67
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f10", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F10, 68
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f11", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F11, 87
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f12", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F12, 88
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f13", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F13, 100
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f14", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F14, 101
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f15", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F15, 102
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f16", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F16, 103
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f17", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F17, 104
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f18", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F18, 105
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.f19", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_F19, 113
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.num.lock",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMLOCK,
         69
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.0",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD0,
         82
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.1",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD1,
         79
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.2",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD2,
         80
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.3",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD3,
         81
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.4",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD4,
         75
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.5",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD5,
         76
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.6",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD6,
         77
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.7",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD7,
         71
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.8",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD8,
         72
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.9",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPAD9,
         73
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.add",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_ADD,
         78
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.decimal",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_DECIMAL,
         83
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.enter",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPADENTER,
         156
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.equal",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NUMPADEQUALS,
         141
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.multiply",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_MULTIPLY,
         55
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.divide",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_DIVIDE,
         181
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.keypad.subtract",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_SUBTRACT,
         74
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.down", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_DOWN, 208
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.left", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_LEFT, 203
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.right", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_RIGHT, 205
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.up", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_UP, 200
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.apostrophe",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_APOSTROPHE,
         40
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.backslash",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_BACKSLASH,
         43
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.comma", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_COMMA, 51
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.equal", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_EQUALS, 13
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.grave.accent",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_GRAVE,
         41
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.left.bracket",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_LBRACKET,
         26
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.minus", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_MINUS, 12
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.period",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_PERIOD,
         52
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.right.bracket",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_RBRACKET,
         27
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.semicolon",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_SEMICOLON,
         39
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.slash", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_SLASH, 53
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.space", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_SPACE, 57
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.tab", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_TAB, 15
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.left.alt",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_LMENU,
         56
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.left.control",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_LCONTROL,
         29
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.left.shift",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_LSHIFT,
         42
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.right.alt",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_RMENU,
         184
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.right.control",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_RCONTROL,
         157
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.right.shift",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_RSHIFT,
         54
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.enter", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_RETURN, 28
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.escape", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_ESCAPE, 1
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.backspace",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_BACK,
         14
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.delete",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_DELETE,
         211
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.end", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_END, 207
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.home", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_HOME, 199
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.insert",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_INSERT,
         210
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.caps.lock",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_CAPITAL,
         58
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.pause", com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_PAUSE, 197
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "key.keyboard.scroll.lock",
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_SCROLL,
         70
      );
   }
}
