package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;

import java.io.Serializable;

public abstract class IRCRRHRCIRHIHIHROHCRRHIIHHHHCH
   extends com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
   implements Serializable {
   private static final long RIROOICCHOCICIHIHRIOOOOOOCCICH = 1L;
   public static final IRCRRHRCIRHIHIHROHCRRHIIHHHHCH HCRRIOOOCICIOCHHCROHRCCIRHIHIO = new IRCRRHRCIRHIHIHROHCRRHIIHHHHCH() {
      private static final long ICCOCCHOROHIOOHRRHRRHRHHRRHROI = 1L;

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OIHCOHRCICCCRHRCROOCIOIRRHHHIH version() {
         return com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIROICHCRROROHCCROOCCCCOCHCCRI.CIRIRRHCOHOCCHOIHOOHIRROIRCIIR;
      }
   };

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OIHCOHRCICCCRHRCROOCIOIRRHHHIH version() {
      return com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OIHCOHRCICCCRHRCROOCIOIRRHHHIH.RRCIOHOROHCHCRIICCIOICORCRIIOR();
   }
}
