package com.moonsworth.lunar.client.HCHRIROHHHCORIOCROOCHRCIOROOCI;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RICRIRRCOHRCOCRRHHCRHRROOIOHHR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IOCCCRIHOCHRCHRHCRHROIRIRHHHIR;
import org.jetbrains.annotations.TestOnly;
import org.jetbrains.annotations.VisibleForTesting;
import org.jspecify.annotations.Nullable;

public class CRRRICCRROCOHHOHIICIHORCOORRRH implements HRCHROOHRIHCRCRHRIIROCIRHOIRHH {
   private static final com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> CCRIHHHCCRRRRHHCIHIIRCORIHIIIR = com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO(
      null
   );

   public CRRRICCRROCOHHOHIICIHORCOORRRH() {
      this.handle(RICRIRRCOHRCOCRRHHCRHRROOIOHHR.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.handle(IHHCHHHCRIHOOCOIOOCRIIICIOROIR.class, this::HHCCIRHCCCIIRHCROHIORHIRHHIORH);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.class,
         this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      );
   }

   private void HHCCIRHCCCIIRHCROHIORHIRHHIORH(@Nullable IHHCHHHCRIHOOCOIOOCRIIICIOROIR var1) {
      for (RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.values()) {
         if (var5.getBrand() != null && IOCCCRIHOCHRCHRHCRHROIRIRHHHIR.IORIICHCCOROCHIIIICCCOCIHCHHHO(var5.getBrand())) {
            CCRIHHHCCRRRRHHCIHIIRCORIHIIIR.set(var5);
            break;
         }
      }

      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = CCRIHHHCCRRRRHHCIHIIRCORIHIIIR.get();
      if (var6 != null) {
         for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var8 : IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
            .OHHRCRIOOCIORORHIOHRICRHHORCIH()) {
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, var8);
         }
      }
   }

   @VisibleForTesting
   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0, com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      IRRCCOICORICIHCHRHIHIHROIRHOCR var2 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IHHOCHOCHOCCHIIICRHRRROICHHIIC);
      if (var2 != null && var2.HHROHRHRRCORIHOCRCOHRRORHIHCCH() && var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0)) {
         CORCOCICIRIOHROHROIIOOHICCHCRR var3 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRIIIRORRHRROOOIRHROOOIIHIHIRH);
         if (var3 != null) {
            boolean var4 = var3.isEnabled();
            if (var4) {
               var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, true);
            }

            var2.setFlipped(var4);
         }
      }

      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var6 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.IICCRHIHRIHOHICHCRIROICOICROOR
      );
      if (var6 != null) {
         for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 : var6.getChildren()) {
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var5);
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = CCRIHHHCCRRRRHHCIHIIRCORIHIIIR.get();
      if (var2 != null) {
         CCRIHHHCCRRRRHHCIHIIRCORIHIIIR.set(null);

         for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 : IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
            .OHHRCRIOOCIORORHIOHRICRHHORCIH()) {
            IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var4);
         }

         ORHRIHHCCIRHRCOROHHRICROCIHIOC();
      }
   }

   @VisibleForTesting
   public static void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0, com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      IRRCCOICORICIHCHRHIHIHROIRHOCR var2 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IHHOCHOCHOCCHIIICRHRRROICHHIIC);
      if (var2 != null && var2.HHROHRHRRCORIHOCRCOHRRORHIHCCH() && var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0)) {
         CORCOCICIRIOHROHROIIOOHICCHCRR var3 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRIIIRORRHRROOOIRHROOOIIHIHIRH);
         if (var3 != null && var3.isEnabled()) {
            boolean var4 = var2.HCICCOORCOCCRORHCCIIOROCCOOORR();
            var3.setEnabled(false);
            if (var4) {
               var2.setFlipped(true);
               var3.setEnabled(true);
               var2.setFlipped(true);
            }
         }
      }

      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var6 = var1.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.IICCRHIHRIHOHICHCRIROICOICROOR
      );
      if (var6 != null) {
         for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 : var6.getChildren()) {
            IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0, var5);
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(RICRIRRCOHRCOCRRHHCRHRROOIOHHR var1) {
      if (var1.OCRRROOOOICIORIRCIROCROROHIORR()) {
         ORHRIHHCCIRHRCOROHHRICROCIHIOC();
      }
   }

   private static void ORHRIHHCCIRHRCOROHHRICROCIHIOC() {
      IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .OHHRCRIOOCIORORHIOHRICRHHORCIH()
         .forEach(
            var0 -> {
               var0.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IOCHHHIIRIHOIRHHICHICCRIHOIOHC)
                  .ifPresent(
                     var1xx -> var1xx.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        var0,
                        com.moonsworth.lunar.client.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SERVER,
                        null
                     )
                  );
               var0.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRHCCHCRHIHOCRICOHOIICHCHOHICC)
                  .ifPresent(
                     var0x -> var0x.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        var0xx -> {
                           var0xx.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(CRICCOOHHHCHOORCICOCOHIHOIRHOO.COIIHHRHOCRHHHCICCIHOHHOCICORR)
                              .ifPresent(
                                 var1xx -> var1xx.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                                    var0xx,
                                    com.moonsworth.lunar.client.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SERVER,
                                    null
                                 )
                              );
                           return false;
                        }
                     )
                  );
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1x = var0.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
                  HICRRICCHCCROOHHCHOCOCCHOIHHOC.IICCRHIHRIHOHICHCRIROICOICROOR
               );
               if (var1x != null) {
                  var1x.OOCCRCRCOHIIORCCORCRCIRRROIOOR(
                     var0x -> {
                        var0x.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IOCHHHIIRIHOIRHHICHICCRIHOIOHC)
                           .ifPresent(
                              var1xx -> var1xx.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                                 var0x,
                                 com.moonsworth.lunar.client.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SERVER,
                                 null
                              )
                           );
                        var0x.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRHCCHCRHIHOCRICOHOIICHCHOHICC)
                           .ifPresent(
                              var0xx -> var0xx.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                 var0xxx -> {
                                    var0xxx.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(CRICCOOHHHCHOORCICOCOHIHOIRHOO.COIIHHRHOCRHHHCICCIHOHHOCICORR)
                                       .ifPresent(
                                          var1xx -> var1xx.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                                             var0xxx,
                                             com.moonsworth.lunar.client.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SERVER,
                                             null
                                          )
                                       );
                                    return false;
                                 }
                              )
                           );
                     }
                  );
               }
            }
         );

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 : IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .OHHRCRIOOCIORORHIOHRICRHHORCIH()) {
         CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1);
      }
   }

   private static void CIOHHCORHRCCRICCCORIHCRHCCCRRR(com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0) {
      var0.updateEnabled();
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1 = var0.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.IICCRHIHRIHOHICHCRIROICOICROOR
      );
      if (var1 != null) {
         var1.OOCCRCRCOHIIORCCORCRCIRRROIOOR(com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH::updateEnabled);
      }
   }

   public static boolean HHCCIRHCCCIIRHCROHIORHIRHHIORH(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0) {
      return CCRIHHHCCRRRRHHCIHIIRCORIHIIIR.get() == var0;
   }

   public static RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HCOORICOHCCRCCHCRCOCORIOCCIRIC() {
      return CCRIHHHCCRRRRHHCIHIIRCORIHIIIR.get();
   }

   @TestOnly
   @VisibleForTesting
   public static void CRRRICCRROCOHHOHIICIHORCOORRRH(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0) {
      CCRIHHHCCRRRRHHCIHIIRCORIHIIIR.set(var0);
   }
}
