package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORIOHRCIHRCOOHICCCRIIIHCRHHIHI;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IRCIIHHICIHRCOCRROCOICRIHHCCHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IROCHOHCORHCOCCCOCHORCICRORIIC;
import com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import lombok.Generated;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI OOIRIHORHICIIOIIIRCOROROICCICR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "enableShieldColors"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI IORRRROCRRCHCHHRCCOHCRRCRHCRHH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "animateColorTransition"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI OOOIHICRCHCOHHIIORORHIOIRCICOI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "shieldActiveColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-16711936)
      .RCIORIIRHRHOHHOHRHOROOIICIRHIR()
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI CHICCROOICRRCRCCCOOCIOIHOIIRHC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "shieldInactiveColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-65536)
      .RCIORIIRHRHOHHOHRHOROOIICIRHIR()
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RRRIROIHCCICHIIOIIOHHHRHCHOICH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "shieldInactiveSound"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI COIHOORIRRCRCRHRCIROHCHHIIRHHR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("shieldUseSound")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RCOROCRIICIOORHHCCIHHOOCCHRCIH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("ignore5Ticks")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI OOHIRRIROCROCIHHIHIOOHHHCRRCOH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("betterBlocking")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final Map<UUID, IROCHOHCORHCOCCCOCHORCICRORIIC<Integer>> RIRIIIOHCOICRORRICHOICCHIRHOII = new HashMap<>();
   private final Map<UUID, IROCHOHCORHCOCCCOCHORCICRORIIC<Integer>> HCCCOOOCHRCRRRORROHRCHCCCCCIHC = new HashMap<>();
   private int CIOOORRCOROIHHIHIOIRRRHRHOORRR = -1;

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.IHHOCHOCHOCCHIIICRHRRROICHHIIC,
         var0 -> var0.RRCRRCORICCHOHHIRCHIROOHIIOHCO(IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCROOCCIOCCCHIRCOHHHCHRCCOOIRC)
      );
      this.handle(IIRHCHHOICHRICOOCRORCCIOOIHOIR.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::RRCRRCORICCHOHHIRCHIROOHIIOHCO);
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION < 29) {
         this.handle(IHHCHHHCRIHOOCOIOOCRIIICIOROIR.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
         this.handle(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICRRICCHCCROOHHCHOCOCCHOIHHOC.class,
            this::RRCRRCORICCHOHHIRCHIROOHIIOHCO
         );
         this.handle(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.class,
            this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
         );
      }
   }

   @Override
   public String getId() {
      return "SHIELDS";
   }

   @Override
   protected RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ORIRHOHRHHROCHHRRIOOCRIHRIIIOC() {
      return RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIICCCRRHHCHRRHRIRCHOICCHROHCR()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCRCRIHOIHICCCCCOOROIHIIRIHCHI)
         .OOROOCCIRCCRHOIOIORIHCHHOOCCOR("xb4d", "Walksy")
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO(this);
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.OOIRIHORHICIIOIIIRCOROROICCICR,
         var1x -> var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(
            this.OOOIHICRCHCOHHIIORORHIOIRCICOI, this.CHICCROOICRRCRCCCOOCIOIHOIIRHC, this.IORRRROCRRCHCHHRCCOHCRRCRHCRHH
         )
      );
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.RRRIROIHCCICHIIOIIOHHHRHCHOICH, this.COIHOORIRRCRCRHRCIROHCHHIIRHHR).COIIIOIIOHICCOCIOROOHIIHHIOIOR(28);
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.RCOROCRIICIOORHHCCIHHOOCCHRCIH, this.OOHIRRIROCROCIHHIHIOOHHHCRRCOH);
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IHHCHHHCRIHOOCOIOOCRIIICIOROIR var1) {
      if (var1.HCICROIHRHRCORRHCOIHIHCCCCHRHH() != IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH()
         && var1.HCICROIHRHRCORRHCOIHIHCCCCHRHH() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2
         && var2.bridge$isBlocking()) {
         if (var1.HOCROOHRHRIOIICORHRIIICROCCRHC() == 30 || var1.HOCROOHRHRIOIICORHRIIICROCCRHC() == 29) {
            int var5 = var1.HOCROOHRHRIOIICORHRIIICROCCRHC() == 30 ? 100 : 5;
            if (var5 != 5 || !this.RCOROCRIICIOORHHCCIHHOOCCHRCIH.get()) {
               IROCHOHCORHCOCCCOCHORCICRORIIC var4 = this.RIRIIIOHCOICRORRICHOICCHIRHOII
                  .computeIfAbsent(var2.bridge$getUniqueID(), var0 -> new IROCHOHCORHCOCCCOCHORCICRORIIC<>(0));
               var4.value = (V)Math.max((Integer)var4.value, var5);
            }
         }

         if (this.RRRIROIHCCICHIIOIIOHHHRHCHOICH.get() && var1.HOCROOHRHRIOIICORHRIIICROCCRHC() == 30) {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               "minecraft:item.shield.break",
               var1.HCICROIHRHRCORRHCOIHIHCCCCHRHH().bridge$getPosX(),
               var1.HCICROIHRHRCORRHCOIHIHCCCCHRHH().bridge$getPosY(),
               var1.HCICROIHRHRCORRHCOIHIHCCCCHRHH().bridge$getPosZ()
            );
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() != null) {
         String var2 = var1.HOHHIHRHOHIIHRHCHHIRORRRCOIHCC().toString();
         if ("minecraft:item.shield.break".equals(var2) || "minecraft:item.shield.block".equals(var2)) {
            List var3 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1.HIIRCCHHCIHROHCRICCOCIHRRHCRIH(), var1.CICHIHIRRIRIICHCOCHIIOIIHRHROR(), var1.CIROCOHOCRHOHCCRIHIRHOICHRIRIR(), 0.5
            );
            if (!var3.isEmpty()) {
               int var4 = "minecraft:item.shield.break".equals(var2) ? 100 : 5;
               if (var4 != 5 || !this.RCOROCRIICIOORHHCCIHHOOCCHRCIH.get()) {
                  IROCHOHCORHCOCCCOCHORCICRORIIC var5 = this.RIRIIIOHCOICRORRICHOICCHIRHOII
                     .computeIfAbsent(((CRRRICCRROCOHHOHIICIHORCOORRRH)var3.get(0)).bridge$getUniqueID(), var0 -> new IROCHOHCORHCOCCCOCHORCICRORIIC<>(0));
                  var5.value = (V)Math.max((Integer)var5.value, var4);
               }
            }
         }
      }
   }

   private void RRCRRCORICCHOHHIRCHIROOHIIOHCO(IOIICIRIICICIIOORHCIIIIRRIHRHI var1) {
      this.RIRIIIOHCOICRORRICHOICCHIRHOII.entrySet().removeIf(var0 -> {
         IROCHOHCORHCOCCCOCHORCICRORIIC var1x = var0.getValue();
         IROCHOHCORHCOCCCOCHORCICRORIIC var2 = var1x;
         Integer var3 = (Integer)var2.value;
         var2.value = (V)(Integer)var2.value - 1;
         return (Integer)var1x.value <= 0;
      });
      this.HCCCOOOCHRCRRRORROHRCHCCCCCIHC.entrySet().removeIf(var0 -> {
         IROCHOHCORHCOCCCOCHORCICRORIIC var1x = var0.getValue();
         IROCHOHCORHCOCCCOCHORCICRORIIC var2 = var1x;
         Integer var3 = (Integer)var2.value;
         var2.value = (V)(Integer)var2.value - 1;
         return (Integer)var1x.value <= 0;
      });
      if (this.OOHIRRIROCROCIHHIHIOOHHHCRRCOH.get() && IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() != null) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH()
            .bridge$getPlayerEntities()
            .forEach(
               var1x -> {
                  if (var1x != IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH()) {
                     if (var1x.bridge$isUsingItem() && IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 1) {
                        com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR var2 = var1x.bridge$getEquipmentInSlot(
                           com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.MAINHAND
                        );
                        boolean var3 = "minecraft:shield".equals(var2.bridge$getItemRegistryName());
                        if (this.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1x) && (var3 || var2.bridge$getMaxItemUseDuration() == 0)) {
                           com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR var4 = var3
                              ? com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.MAINHAND
                              : com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.OFFHAND;
                           var1x.bridge$setUseItem(var1x.bridge$getEquipmentInSlot(var4));
                           IROCHOHCORHCOCCCOCHORCICRORIIC var5 = this.HCCCOOOCHRCRRRORROHRCHCCCCCIHC
                              .computeIfAbsent(var1x.bridge$getUniqueID(), var0 -> new IROCHOHCORHCOCCCOCHORCICRORIIC<>(72000));
                           var1x.bridge$setUseItemRemaining((Integer)var5.value);
                        } else {
                           this.HCCCOOOCHRCRRRORROHRCHCCCCCIHC.remove(var1x.bridge$getUniqueID());
                        }
                     } else {
                        this.HCCCOOOCHRCRRRORROHRCHCCCCCIHC.remove(var1x.bridge$getUniqueID());
                     }
                  }
               }
            );
      }
   }

   private void RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICRRICCHCCROOHHCHOCOCCHOIHHOC var1
   ) {
      if (this.COIHOORIRRCRCRHRCIROHCHHIIRHHR.get() && IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH() != null) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
         if (!var2.bridge$getEquipmentInSlot(
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.MAINHAND
            )
            .bridge$getItem()
            .bridge$isAxe()) {
            double var3 = var2.bridge$getPosX();
            double var5 = var2.bridge$getPosY();
            double var7 = var2.bridge$getPosZ();
            if (var1.HCHOOIOHICCRIOIICHCHOIIRRRIHCI() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var9
               && var9.bridge$canShieldBeAttacked(var3, var5, var7)) {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  "minecraft:item.shield.block",
                  var1.HCHOOIOHICCRIOIICHCHOIIRRRIHCI().bridge$getPosX(),
                  var1.HCHOOIOHICCRIOIICHCHOIIRRRIHCI().bridge$getPosY(),
                  var1.HCHOOIOHICCRIOIICHCHOIIRRRIHCI().bridge$getPosZ()
               );
            }
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var1
   ) {
      if (this.COIHOORIRRCRCRHRCIROHCHHIIRHHR.get() && IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() != null) {
         double var2 = var1.CCRCRRIRHROHHCIHRCCIOCRCRCHHOH() * 2.0F;
         List var4 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.getX(), var1.getY(), var1.getZ(), var2 + 0.5);
         var4.stream()
            .map(
               var0 -> (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH)var0
            )
            .filter(var1x -> var1x.bridge$canShieldBeAttacked(var1.getX(), var1.getY(), var1.getZ()))
            .forEach(
               var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  "minecraft:item.shield.block", var1x.bridge$getPosX(), var1x.bridge$getPosY(), var1x.bridge$getPosZ()
               )
            );
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var1, double var2, double var4, double var6) {
      IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
         .bridge$getPlayer()
         .bridge$getWorld()
         .bridge$playSound(var2, var4, var6, var1, 1.0F, (float)(0.8F + Math.random() * 0.4F), false);
   }

   private List<CRRRICCRROCOHHOHIICIHORCOORRRH> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(double var1, double var3, double var5, double var7) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var9 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1 - var7, var3 - var7, var5 - var7, var1 + var7, var3 + var7, var5 + var7);
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH()
         .bridge$getEntities(
            var9,
            var1x -> var1x != IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH()
                  && var1x instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2
                  && var2.bridge$isBlocking()
                  && var1x.bridge$isAlive()
               ? this.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2)
               : false
         );
   }

   private boolean IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION < 5) {
         return false;
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = var1.bridge$getMainHandItemRenderState();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var1.bridge$getOffHandItemRenderState();
      return "minecraft:shield".equals(var2.bridge$getItemRegistryName()) || "minecraft:shield".equals(var3.bridge$getItemRegistryName());
   }

   public int RCOCRROHHROHHOCRCCCHCIROIIOORC(UUID var1) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH() != null
         && this.OOIRIHORHICIIOIIIRCOROROICCICR.get()
         && !IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH().bridge$getUniqueID().equals(var1)) {
         ORHIOICIOCRRHOOCOHRORIHICHRCRR var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreenOrRewind();
         if (var2 != null
            && var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class
            )) {
            return -1;
         }

         boolean var3 = this.RIRIIIOHCOICRORRICHOICCHIRHOII.containsKey(var1);
         float var4 = var3 ? 1.0F : 0.0F;
         if (var3 && this.IORRRROCRRCHCHHRCCOHCRRCRHCRHH.get()) {
            var4 = Math.min(1.0F, Math.max(0.3F, ((Integer)this.RIRIIIOHCOICRORRICHOICCHIRHOII.get(var1).value).intValue() / 50.0F));
         }

         return OCOHORHCROHICRRIHCIHHRRCIHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            this.CHICCROOICRRCRCCCOOCIOIHOIIRHC.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F),
            this.OOOIHICRCHCOHHIIORORHIOIRCICOI.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F),
            var4
         );
      } else {
         return -1;
      }
   }

   @Generated
   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI HCORRCHROOIRCCIIORCHIRCOHOCHII() {
      return this.OOIRIHORHICIIOIIIRCOROROICCICR;
   }

   @Generated
   public int ROCHHHHROOICCHRHHCRCCCRCOHCROH() {
      return this.CIOOORRCOROIHHIHIOIRRRHRHOORRR;
   }

   @Generated
   public void CIIRCHOCCHCHOOHIIICOCIIRCCCCOH(int var1) {
      this.CIOOORRCOROIHHIHIOIRRRHRHOORRR = var1;
   }
}
