package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import java.io.Serializable;
import java.lang.reflect.Modifier;
import java.lang.reflect.Type;
import java.util.List;

public abstract class OCOHORHCROHICRRIHCIHHRRCIHICRI
   extends com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   implements Serializable,
   Type {
   private static final long RCROICROHOOCIROCRCRHHCROOICICO = 1L;
   protected final Class<?> IIIHIIRCHORHOCIHHOCIHCHCROORHI;
   protected final int IOROCRRRROOICRHICCCRHHICRROCCR;
   protected final Object RHRHIOHRIRCOHIHOIOHIHHHCIORHRH;
   protected final Object CHRRICCIOOIIHICIHHHHOCROIORHOI;
   protected final boolean RRRHICCICCHHIHHRCCCHHORCHHORIH;

   protected OCOHORHCROHICRRIHCIHHRRCIHICRI(Class<?> var1, int var2, Object var3, Object var4, boolean var5) {
      this.IIIHIIRCHORHOCIHHOCIHCHCROORHI = var1;
      this.IOROCRRRROOICRHICCCRHHICRROCCR = 31 * var2 + var1.hashCode();
      this.RHRHIOHRIRCOHIHOIOHIHHHCIORHRH = var3;
      this.CHRRICCIOOIIHICIHHHHOCROIORHOI = var4;
      this.RRRHICCICCHHIHHRCCCHHORCHHORIH = var5;
   }

   protected OCOHORHCROHICRRIHCIHHRRCIHICRI(OCOHORHCROHICRRIHCIHHRRCIHICRI var1) {
      this.IIIHIIRCHORHOCIHHOCIHCHCROORHI = var1.IIIHIIRCHORHOCIHHOCIHCHCROORHI;
      this.IOROCRRRROOICRHICCCRHHICRROCCR = var1.IOROCRRRROOICRHICCCRHHICRROCCR;
      this.RHRHIOHRIRCOHIHOIOHIHHHCIORHRH = var1.RHRHIOHRIRCOHIHOIOHIHHHCIORHRH;
      this.CHRRICCIOOIIHICIHHHHOCROIORHOI = var1.CHRRICCIOOIIHICIHHHHOCROIORHOI;
      this.RRRHICCICCHHIHHRCCCHHORCHHORIH = var1.RRRHICCICCHHIHHRCCCHHORCHHORIH;
   }

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI OOROOCCIRCCRHOIOIORIHCHHOOCCOR(OCOHORHCROHICRRIHCIHHRRCIHICRI var1);

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI HHRHHIOOHOHIHRCHCHRORRRIIRIIHO();

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI RCOCHOROICROOIRHRCRIOHIHCOCIII(Object var1);

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI HCIHORIHHCOOORRIOHIHIICCRHHOHC(Object var1);

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI OICIRICHOHHIIHIRRRROORCRRRCORH(Object var1);

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI HIIRCRROICHCOROOCCCCOIOOOCCIIC(Object var1);

   public OCOHORHCROHICRRIHCIHHRRCIHICRI CORCOCICIRIOHROHROIIOOHICCHCRR(OCOHORHCROHICRRIHCIHHRRCIHICRI var1) {
      OCOHORHCROHICRRIHCIHHRRCIHICRI var2 = this;
      Object var3 = var1.ORRHHOOICCCIIRICRIOCIOIOHOIICH();
      if (var3 != this.CHRRICCIOOIIHICIHHHHOCROIORHOI) {
         var2 = var2.RCOCHOROICROOIRHRCRIOHIHCOCIII(var3);
      }

      var3 = var1.IRHHHRHOCIHRRRRHIIOIIROCHHRCCH();
      if (var3 != this.RHRHIOHRIRCOHIHOIOHIHHHCIORHRH) {
         var2 = var2.OICIRICHOHHIIHIRRRROORCRRRCORH(var3);
      }

      return var2;
   }

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Class<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR var2,
      OCOHORHCROHICRRIHCIHHRRCIHICRI var3,
      OCOHORHCROHICRRIHCIHHRRCIHICRI[] var4
   );

   @Deprecated
   public OCOHORHCROHICRRIHCIHHRRCIHICRI HOHCCHOIOHOHHOROHOIIHOOHORRHRO(Class<?> var1) {
      return var1 == this.IIIHIIRCHORHOCIHHOCIHCHCROORHI ? this : this.IICCOOCHCHROORHHIIHROHCCRHRCOR(var1);
   }

   @Deprecated
   protected abstract OCOHORHCROHICRRIHCIHHRRCIHICRI IICCOOCHCHROORHHIIHROHCCRHRCOR(Class<?> var1);

   @Override
   public final Class<?> RRICIOOORRIORHHICIRCIOCHRHRCHH() {
      return this.IIIHIIRCHORHOCIHHOCIHCHCROORHI;
   }

   @Override
   public final boolean RIHOOCIHRICOCHRHCOOCCOIHOCHRCR(Class<?> var1) {
      return this.IIIHIIRCHORHOCIHHOCIHCHCROORHI == var1;
   }

   public boolean HOOHORRHROCRORCHCOCCRRICIIRIOH() {
      return true;
   }

   public final boolean IROCHOHCORHCOCCCOCHORCICRORIIC(Class<?> var1) {
      return this.IIIHIIRCHORHOCIHHOCIHCHCROORHI == var1 || var1.isAssignableFrom(this.IIIHIIRCHORHOCIHHOCIHCHCROORHI);
   }

   public final boolean RRHHORICORICIRHICOHHROHIIHICCH(Class<?> var1) {
      return this.IIIHIIRCHORHOCIHHOCIHCHCROORHI == var1 || this.IIIHIIRCHORHOCIHHOCIHCHCROORHI.isAssignableFrom(var1);
   }

   @Override
   public boolean isAbstract() {
      return Modifier.isAbstract(this.IIIHIIRCHORHOCIHHOCIHCHCROORHI.getModifiers());
   }

   @Override
   public boolean RIOIOCRRCHIICRIRHHHRIHORCRHHOO() {
      int var1 = this.IIIHIIRCHORHOCIHHOCIHCHCROORHI.getModifiers();
      return (var1 & 1536) == 0 ? true : this.IIIHIIRCHORHOCIHHOCIHCHCROORHI.isPrimitive();
   }

   @Override
   public boolean IRHHOHICHCIIICCIORCRORCICIIIOC() {
      return Throwable.class.isAssignableFrom(this.IIIHIIRCHORHOCIHHOCIHCHCROORHI);
   }

   @Override
   public boolean OCOHHROOICIIRHRIRHIRHIORORROOI() {
      return false;
   }

   @Override
   public final boolean ORHRHCHCOHHORROCRRRCIHRIOORORC() {
      return com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HIORIIIIOCCCRCHCOROROCCOIOOIIR(
         this.IIIHIIRCHORHOCIHHOCIHCHCROORHI
      );
   }

   public final boolean RRRCCRIOIHHIHIOIOOHIROHIOHRICR() {
      return com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HIORIIIIOCCCRCHCOROROCCOIOOIIR(
            this.IIIHIIRCHORHOCIHHOCIHCHCROORHI
         )
         && this.IIIHIIRCHORHOCIHHOCIHCHCROORHI != Enum.class;
   }

   public final boolean OOIHOHRRRCCCCOHOIORRHOOHCOOORH() {
      return com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.ORCORCRRIRIROIORRCCCCHRHRCOHOH(
         this.IIIHIIRCHORHOCIHHOCIHCHCROORHI
      );
   }

   @Override
   public final boolean isInterface() {
      return this.IIIHIIRCHORHOCIHHOCIHCHCROORHI.isInterface();
   }

   @Override
   public final boolean isPrimitive() {
      return this.IIIHIIRCHORHOCIHHOCIHCHCROORHI.isPrimitive();
   }

   @Override
   public final boolean isFinal() {
      return Modifier.isFinal(this.IIIHIIRCHORHOCIHHOCIHCHCROORHI.getModifiers());
   }

   @Override
   public abstract boolean HCHCCRRRHHICOIRRIOOOOHHHOIIORR();

   @Override
   public boolean RORHOIHRHICCCCHOIOHCIOIIHIROIC() {
      return false;
   }

   @Override
   public boolean CHIHCRICHHCIOCRIIROHIIIHOOORIC() {
      return false;
   }

   public final boolean CRCORIOIHCIIRRRORROCIORRRHHICR() {
      return this.IIIHIIRCHORHOCIHHOCIHCHCROORHI == Object.class;
   }

   public final boolean HOOIIHOHCOCOCHRORICRICIIHOHIIO() {
      return this.RRRHICCICCHHIHHRCCCHHORCHHORIH;
   }

   @Override
   public boolean COOCHRHOICHORRORCIIROROHORRCCI() {
      return this.CRRHOOOHOICRIRHRIHRRRCHCIHHICC() > 0;
   }

   public OCOHORHCROHICRRIHCIHHRRCIHICRI RIHORRHRCROORRIIRICHRRRICCICOO() {
      return null;
   }

   public OCOHORHCROHICRRIHCIHHRRCIHICRI RCCRIHIHOIICHCIICCOHHHIRICOHHC() {
      return null;
   }

   public OCOHORHCROHICRRIHCIHHRRCIHICRI ROIRRRIHROCRRIIIICORRRIRHROCCO() {
      return null;
   }

   @Override
   public abstract int CRRHOOOHOICRIRHRIHRRRCHCIHHICC();

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI CHHIOCOORROCRHIIORHHHIIRIOORCO(int var1);

   @Deprecated
   @Override
   public abstract String ORCIRRCRRCICHICRCOOHIRRRRROORC(int var1);

   @Deprecated
   @Override
   public Class<?> IIHOIIHCHOHCRIHHORCOCHRICOHCOO() {
      return null;
   }

   public OCOHORHCROHICRRIHCIHHRRCIHICRI CCOCIRRRCCCHIHOOROIOCCIHHHHCCO(int var1) {
      OCOHORHCROHICRRIHCIHHRRCIHICRI var2 = this.CHHIOCOORROCRHIIORHHHIIRIOORCO(var1);
      return var2 == null
         ? com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR.HIHOHHRCIOIIOHRRHRRRRCOHORHHOI()
         : var2;
   }

   public abstract com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR HOHCHIIHCCCCHCOORROOHHOIIRIHRH();

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI IHROCRRIRIROCCCRCRRROCRRCRIIHH(Class<?> var1);

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI ROIOOCRIOROIICCRHICRHRCCIOOIHH();

   public abstract List<OCOHORHCROHICRRIHCIHHRRCIHICRI> getInterfaces();

   public abstract OCOHORHCROHICRRIHCIHHRRCIHICRI[] IHRHHHORORIROOCORCIORRCOCHHHRI(Class<?> var1);

   public <T> T IRHHHRHOCIHRRRRHIIOIIROCHHRCCH() {
      return (T)this.RHRHIOHRIRCOHIHOIOHIHHHCIORHRH;
   }

   public <T> T ORRHHOOICCCIIRICRIOCIOIOHOIICH() {
      return (T)this.CHRRICCIOOIIHICIHHHHOCROIORHOI;
   }

   public Object IHORRICIRCHRHCICHCCCIIIIHOHICR() {
      return null;
   }

   public Object OROIIROICHCOCHHCIRRICCICHHHCRI() {
      return null;
   }

   public boolean OIRRRHORCHCCRIHORIICOIORRCCOHI() {
      return this.RHRHIOHRIRCOHIHOIOHIHHHCIORHRH != null;
   }

   public boolean COHORIOHIIRHCHCCOIHRRCOICRRHOI() {
      return this.CHRRICCIOOIIHICIHHHHOCROIORHOI != null || this.RHRHIOHRIRCOHIHOIOHIHHHCIORHRH != null;
   }

   public String getGenericSignature() {
      StringBuilder var1 = new StringBuilder(40);
      this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1);
      return var1.toString();
   }

   public abstract StringBuilder RRCRRCORICCHOHHIRCHIROOHIIOHCO(StringBuilder var1);

   public String RCOROICRCRCCHHRCOHHOIHOHRICCHR() {
      StringBuilder var1 = new StringBuilder(40);
      this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return var1.toString();
   }

   public abstract StringBuilder RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(StringBuilder var1);

   @Override
   public abstract String toString();

   @Override
   public abstract boolean equals(Object var1);

   @Override
   public int hashCode() {
      return this.IOROCRRRROOICRHICCCRHHICRROCCR;
   }
}
