package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IOHIHIIHCCCCCIHRORIOIOORCIOHII;

public abstract class HICRRICCHCCROOHHCHOCOCCHOIHHOC
   extends com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR {
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH IOIORROIOIIIOCHRHIIHROIIHRICIR;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH IIHCRORORRORIRRHRIHHROIROHCRIO;

   protected HICRRICCHCCROOHHCHOCOCCHOIHHOC(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      this.IOIORROIOIIIOCHRHIIHROIIHRICIR = var1;
      this.IIHCRORORRORIRRHRIHHROIROHCRIO = var2;
   }

   @Override
   public abstract IOHIHIIHCCCCCIHRORIOIOORCIOHII.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CHOIOIOCOICOIROHOOCHICOORIIHHO();

   @Override
   public String HCOCORHRRHOCRCCRCHRIICIIORROOR() {
      return null;
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH COIICHCIOCROHRRHCCROCHIHIOCHOC() {
      return this.IOIORROIOIIIOCHRHIIHROIIHRICIR;
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2
   ) {
      this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2);
      return var2.COCIHCORCIRICHRHHCCCIHIIHCCIRC == null ? null : var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2);
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2
   ) {
      return var2 == null ? null : var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2);
   }

   protected void HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      Object var2 = var1.COCIHCORCIRICHRHHCCCIHIIHCCIRC;
      if (var2 == null) {
         Object var3 = var1.CHRIICCOCCCRHROHCIIRRRHIRCRIHR;
         Class var4 = var1.RRRCIIIORORRCRIICOOCRICIHHROHH;
         if (var4 == null) {
            var2 = this.OICOHRRRRCOICCHOIOROHOCOORCHII(var3);
         } else {
            var2 = this.CORCOCICIRIOHROHROIIOOHICCHCRR(var3, var4);
         }

         var1.COCIHCORCIRICHRHHCCCIHIIHCCIRC = var2;
      }
   }

   protected String OICOHRRRRCOICCHOIOROHOCOORCHII(Object var1) {
      String var2 = this.IOIORROIOIIIOCHRHIIHROIIHRICIR.OICOHRRRRCOICCHOIOROHOCOORCHII(var1);
      if (var2 == null) {
         this.COCCOIROHORRRHIHICORRHRRORIIIH(var1);
      }

      return var2;
   }

   protected String CORCOCICIRIOHROHROIIOOHICCHCRR(Object var1, Class<?> var2) {
      String var3 = this.IOIORROIOIIIOCHRHIIHROIIHRICIR.CORCOCICIRIOHROHROIIOOHICCHCRR(var1, var2);
      if (var3 == null) {
         this.COCCOIROHORRRHIHICORRHRRORIIIH(var1);
      }

      return var3;
   }

   protected void COCCOIROHORRRHIHICORRHRRORIIIH(Object var1) {
   }
}
