package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IOHIHIIHCCCCCIHRORIOIOORCIOHII;
import java.util.Collection;

public class IIRHCHHOICHRICOOCRORCCIOOIHOIR
   implements com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OOROOCCIRCCRHOIOIORIHCHHOOCCOR<IIRHCHHOICHRICOOCRORCCIOOIHOIR> {
   protected IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH RCHCRCOHIIOIIOIHCCRHRORHOOIHHR;
   protected IOHIHIIHCCCCCIHRORIOIOORCIOHII.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ORHCIHHROOOCRHHIOHCHICRCICCHRO;
   protected String IHIIOIORIRIRCHICHRRCOORCRRIOIO;
   protected boolean HORIHRICOHRIHRRIHHROOHHCOIOROH = false;
   protected Class<?> IOCRIHIHRCRCHRORRHCHOHICCOOHHR;
   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH RCIICICOCIOOCRIIRHHORCCHHHRHRH;

   public IIRHCHHOICHRICOOCRORCCIOOIHOIR() {
   }

   protected IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, IOHIHIIHCCCCCIHRORIOIOORCIOHII.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2, String var3
   ) {
      this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR = var1;
      this.ORHCIHHROOOCRHHIOHCHICRCICCHRO = var2;
      this.IHIIOIORIRIRCHICHRRCOORCRRIOIO = var3;
   }

   protected IIRHCHHOICHRICOOCRORCCIOOIHOIR(IIRHCHHOICHRICOOCRORCCIOOIHOIR var1, Class<?> var2) {
      this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR = var1.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR;
      this.ORHCIHHROOOCRHHIOHCHICRCICCHRO = var1.ORHCIHHROOOCRHHIOHCHICRCICCHRO;
      this.IHIIOIORIRIRCHICHRRCOORCRRIOIO = var1.IHIIOIORIRIRCHICHRRCOORCRRIOIO;
      this.HORIHRICOHRIHRRIHHROOHHCOIOROH = var1.HORIHRICOHRIHRRIHHROOHHCOIOROH;
      this.RCIICICOCIOOCRIIRHHORCCHHHRHRH = var1.RCIICICOCIOOCRIIRHHORCCHHHRHRH;
      this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR = var2;
   }

   public static IIRHCHHOICHRICOOCRORCCIOOIHOIR IIHHOROHOOROIIIIIOCHRIROIICOHI() {
      return new IIRHCHHOICHRICOOCRORCCIOOIHOIR().IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NONE, null);
   }

   public IIRHCHHOICHRICOOCRORCCIOOIHOIR IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var2
   ) {
      if (var1 == null) {
         throw new IllegalArgumentException("idType cannot be null");
      }

      this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR = var1;
      this.RCIICICOCIOOCRIIRHHORCCHHHRHRH = var2;
      this.IHIIOIORIRIRCHICHRRCOORCRRIOIO = var1.getDefaultPropertyName();
      return this;
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2,
      Collection<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH> var3
   ) {
      if (this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR == IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NONE) {
         return null;
      }

      if (var2.isPrimitive() && !this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1, var2)) {
         return null;
      }

      if (this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR == IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEDUCTION) {
         return CRRRICCRROCOHHOHIICIHORCOORRRH.IHCOHOOHRIHHHRORORHRCORICORHRR();
      }

      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var4 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1, var2, this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1), var3, true, false
      );
      switch (this.ORHCIHHROOOCRHHIOHCHICRCICCHRO) {
         case WRAPPER_ARRAY:
            return new IRCIIHHICIHRCOCRROCOICRIHHCCHH(var4, null);
         case PROPERTY:
            return new CORCOCICIRIOHROHROIIOOHICCHCRR(var4, null, this.IHIIOIORIRIRCHICHRRCOORCRRIOIO);
         case WRAPPER_OBJECT:
            return new HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var4, null);
         case EXTERNAL_PROPERTY:
            return new HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var4, null, this.IHIIOIORIRIRCHICHRRCOORCRRIOIO);
         case EXISTING_PROPERTY:
            return new RRCRRCORICCHOHHIRCHIROOHIIOHCO(var4, null, this.IHIIOIORIRIRCHICHRRCOORCRRIOIO);
         default:
            throw new IllegalStateException("Do not know how to construct standard type serializer for inclusion type: " + this.ORHCIHHROOOCRHHIOHCHICRCICCHRO);
      }
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2,
      Collection<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH> var3
   ) {
      if (this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR == IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NONE) {
         return null;
      }

      if (var2.isPrimitive() && !this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1, var2)) {
         return null;
      }

      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH var4 = this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(
         var1, var2
      );
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var5 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1, var2, var4, var3, false, true
      );
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var6 = this.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
         var1, var2
      );
      if (this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR == IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DEDUCTION) {
         return new HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2, var5, var6, var1, var3);
      }

      switch (this.ORHCIHHROOOCRHHIOHCHICRCICCHRO) {
         case WRAPPER_ARRAY:
            return new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var5, this.IHIIOIORIRIRCHICHRRCOORCRRIOIO, this.HORIHRICOHRIHRRIHHROOHHCOIOROH, var6);
         case PROPERTY:
         case EXISTING_PROPERTY:
            return new OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
               var2,
               var5,
               this.IHIIOIORIRIRCHICHRRCOORCRRIOIO,
               this.HORIHRICOHRIHRRIHHROOHHCOIOROH,
               var6,
               this.ORHCIHHROOOCRHHIOHCHICRCICCHRO,
               this.CORCOCICIRIOHROHROIIOOHICCHCRR(var1, var2)
            );
         case WRAPPER_OBJECT:
            return new CRICCOOHHHCHOORCICOCOHIHOIRHOO(var2, var5, this.IHIIOIORIRIRCHICHRRCOORCRRIOIO, this.HORIHRICOHRIHRRIHHROOHHCOIOROH, var6);
         case EXTERNAL_PROPERTY:
            return new RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var2, var5, this.IHIIOIORIRIRCHICHRRCOORCRRIOIO, this.HORIHRICOHRIHRRIHHROOHHCOIOROH, var6);
         default:
            throw new IllegalStateException("Do not know how to construct standard type serializer for inclusion type: " + this.ORHCIHHROOOCRHHIOHCHICRCICCHRO);
      }
   }

   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      if (this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR != null) {
         if (this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR == Void.class
            || this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR
               == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.class
            )
          {
            return var1.CRRIRCRIRCHCHIRCICOROIIOIIICCC().OCOHORHCROHICRRIHCIHHRRCIHICRI(this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR);
         }

         if (var2.RIHOOCIHRICOCHRHCOOCCOIHOCHRCR(this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR)) {
            return var2;
         }

         if (var2.RRHHORICORICIRHICOHHROHIIHICCH(this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR)) {
            return var1.CRRIRCRIRCHCHIRCICOROIIOIIICCC().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR);
         }

         if (var2.RIHOOCIHRICOCHRHCOOCCOIHOCHRCR(this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR)) {
            return var2;
         }
      }

      return var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.USE_BASE_TYPE_AS_DEFAULT_IMPL
            )
            && !var2.isAbstract()
         ? var2
         : null;
   }

   public IIRHCHHOICHRICOOCRORCCIOOIHOIR IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOHIHIIHCCCCCIHRORIOIOORCIOHII.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1) {
      if (var1 == null) {
         throw new IllegalArgumentException("includeAs cannot be null");
      }

      this.ORHCIHHROOOCRHHIOHCHICRCICCHRO = var1;
      return this;
   }

   public IIRHCHHOICHRICOOCRORCCIOOIHOIR HCHRRCIIIIHOCRHRIIOROCCHHCOHII(String var1) {
      if (var1 == null || var1.isEmpty()) {
         var1 = this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR.getDefaultPropertyName();
      }

      this.IHIIOIORIRIRCHICHRRCOORCRRIOIO = var1;
      return this;
   }

   public IIRHCHHOICHRICOOCRORCCIOOIHOIR RHIHRRICIHORIHHIHHOIIOHHRCIIIH(Class<?> var1) {
      this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR = var1;
      return this;
   }

   public IIRHCHHOICHRICOOCRORCCIOOIHOIR RHHIRORIIHOHRHIRHOHICHIIOCHCOR(boolean var1) {
      this.HORIHRICOHRIHRRIHHROOHHCOIOROH = var1;
      return this;
   }

   public IIRHCHHOICHRICOOCRORCCIOOIHOIR HCHHOOOCRCRHHICHICORHOCHCCCHRH(Class<?> var1) {
      if (this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR == var1) {
         return this;
      }

      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         IIRHCHHOICHRICOOCRORCCIOOIHOIR.class, this, "withDefaultImpl"
      );
      return new IIRHCHHOICHRICOOCRORCCIOOIHOIR(this, var1);
   }

   @Override
   public Class<?> OOROHRHIIRROCRROHHIRRHCOIRHRCO() {
      return this.IOCRIHIHRCRCHRORRHCHOHICCOOHHR;
   }

   public String IRHRRRRRCRIHOOOCRHOCIICHHRIRHC() {
      return this.IHIIOIORIRIRCHICHRRCOORCRRIOIO;
   }

   public boolean IHRHHCRRCHCHORORRORORIIRIOHIIC() {
      return this.HORIHRICOHRIHRRIHHROOHHCOIOROH;
   }

   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH var3,
      Collection<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH> var4,
      boolean var5,
      boolean var6
   ) {
      if (this.RCIICICOCIOOCRIIRHHORCCHHHRHRH != null) {
         return this.RCIICICOCIOOCRIIRHHORCCHHHRHRH;
      }

      if (this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR == null) {
         throw new IllegalStateException("Cannot build, 'init()' not yet called");
      }

      switch (this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR) {
         case DEDUCTION:
         case CLASS:
            return IIHRRHORCRCROCHHOHORCHCROCIHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var1, var3);
         case MINIMAL_CLASS:
            return CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var1, var3);
         case NAME:
            return RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var4, var5, var6);
         case NONE:
            return null;
         case CUSTOM:
         default:
            throw new IllegalStateException("Do not know how to construct standard type id resolver for idType: " + this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR);
      }
   }

   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var1
   ) {
      return var1.HRRORROOIRCCIIRIIOHRHCCHCIOHOR();
   }

   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH var3 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1
      );
      if (this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR == IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CLASS
         || this.RCHCRCOHIIOIIOIHCCRHRORHOOIHHR == IOHIHIIHCCCCCIHRORIOIOORCIOHII.IRCIIHHICIHRCOCRROCOICRIHHCCHH.MINIMAL_CLASS) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = var3.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            var1, var2
         );
         if (var4
            == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.DENIED
            )
          {
            return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3);
         }

         if (var4
            == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ALLOWED
            )
          {
            return OCOHORHCROHICRRIHCIHHRRCIHICRI.HCHCRHOCRRHIROCROHHRHCOHHHHICI;
         }
      }

      return var3;
   }

   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH var3
   ) {
      throw new IllegalArgumentException(
         String.format(
            "Configured `PolymorphicTypeValidator` (of type %s) denied resolution of all subtypes of base type %s",
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RRROIHOIHOORCCOHOOCHRRRCIIRHHH(
               var3
            ),
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RRROIHOIHOORCCOHOOCHRRRCIIRHHH(
               var2.RRICIOOORRIORHHICIRCIOCHRHRCHH()
            )
         )
      );
   }

   protected boolean RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      return false;
   }

   protected boolean CORCOCICIRIOHROHROIIOOHICCHCRR(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      return var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.REQUIRE_TYPE_ID_FOR_SUBTYPES
         )
         ? true
         : this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(var1, var2);
   }

   protected boolean CRICCOOHHHCHOORCICOCOHIHOIRHOO(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH var3 = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         var1, var2.RRICIOOORRIORHHICIRCIOCHRHRCHH()
      );
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = var1.RCRORHCOCRIIOHICORIHOHRIIRIORH();
      return var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var3, var2) != null;
   }
}
