package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

public class CORCOCICIRIOHROHROIIOOHICCHCRR
   implements com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR> {
   @NotNull
   @Override
   public String RRIICCIOCHRHOHIRIHCHRHOCOROOCC() {
      return "nether_brick";
   }

   public boolean HICRRICCHCCROOHHCHOCOCCHOIHHOC(@NotNull IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      String var2 = var1.bridge$getItemRegistryName();
      return "minecraft:nether_bricks".equals(var2)
         || "minecraft:red_nether_bricks".equals(var2)
         || "minecraft:nether_brick".equals(var2)
         || "minecraft:netherbrick".equals(var2)
         || "minecraft:red_nether_brick".equals(var2);
   }

   @NotNull
   public CRRRICCRROCOHHOHIICIHORCOORRRH ORHIOICIOCRRHOOCOHRORIHICHRCRR(@NotNull IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      String var2 = var1.bridge$getItemRegistryName();
      if (!"minecraft:red_nether_bricks".equals(var2) && !"minecraft:red_nether_brick".equals(var2)) {
         if (!"minecraft:nether_bricks".equals(var2) && (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 5 || !"minecraft:nether_brick".equals(var2))) {
            return !"minecraft:netherbrick".equals(var2) && (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION <= 5 || !"minecraft:nether_brick".equals(var2))
               ? com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.OORIOHCICHIHCIRRIIOHCCHCIHCOIH()
               : com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.OOIHOHCIIRORIOHIRRRORHHHIIIHCH(
                  "item"
               );
         } else {
            return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.OOIHOHCIIRORIOHIRRRORHHHIIIHCH(
               "block"
            );
         }
      } else {
         return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.OOIHOHCIIRORIOHIRRRORHHHIIIHCH(
            "red"
         );
      }
   }

   @Override
   public Optional<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      @NotNull CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      String var2 = switch (var1.IHCICHIIIHORHRIICHOHOHHOCHRORO("block")) {
         case "red" -> IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 5 ? "minecraft:red_nether_bricks" : "minecraft:red_nether_brick";
         case "block" -> IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 5 ? "minecraft:nether_bricks" : "minecraft:nether_brick";
         case "item" -> IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 5 ? "minecraft:nether_brick" : "minecraft:netherbrick";
         default -> "";
      };
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ICHHRRHHCCCCIRHCORIHIRHHOCHIOO(
         var2
      );
   }
}
