package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

public class IIHRRHORCRCROCHHOHORCHCROCIHRO
   implements com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR> {
   @NotNull
   @Override
   public String RRIICCIOCHRHOHIRIHCHRHOCOROOCC() {
      return "signs";
   }

   public boolean HICRRICCHCCROOHHCHOCOCCHOIHHOC(@NotNull IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      return var1.bridge$getItem().bridge$isItemSign();
   }

   @NotNull
   public CRRRICCRROCOHHOHIICIHORCOORRRH ORHIOICIOCRRHOOCOHRORIHICHRCRR(@NotNull IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 5
         ? com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHIRRIIORRHORHRORIHOROIRCORCOO(
               var1
            )
            .map(
               var0 -> {
                  if (var0.contains("_hanging_sign")) {
                     var0 = var0.replace("_hanging_sign", "");
                     return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.OOIHOHCIIRORIOHIRRRORHHHIIIHCH(
                        var0 + ":hanging"
                     );
                  } else {
                     var0 = var0.replace("_standing_sign", "");
                     var0 = var0.replace("_wall_sign", "");
                     var0 = var0.replace("_sign", "");
                     return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.OOIHOHCIIRORIOHIRRRORHHHIIIHCH(
                        var0
                     );
                  }
               }
            )
            .orElse(
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.OORIOHCICHIHCIRRIIOHCCHCIHCOIH()
            )
         : com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.OORIOHCICHIHCIRRIIOHCCHCIHCOIH();
   }

   @Override
   public Optional<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      @NotNull CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      String var2 = var1.IHCICHIIIHORHRIICHOHOHHOCHRORO("oak");
      boolean var3 = false;
      if (var2.endsWith(":hanging")) {
         var2 = var2.replace(":hanging", "");
         var3 = true;
      }

      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION <= 5) {
         return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ICHHRRHHCCCCIRHCORIHIRHHOCHIOO(
            "minecraft:sign"
         );
      }

      String var4 = var2;
      if (var3 && IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 15) {
         var4 = var4 + "_hanging_sign";
      } else {
         var4 = var4 + "_sign";
      }

      Optional var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ICHHRRHHCCCCIRHCORIHIRHHOCHIOO(
         "minecraft:" + var4
      );
      return var5.isPresent()
         ? var5
         : com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ICHHRRHHCCCCIRHCORIHIRHHOCHIOO(
            "minecraft:oak_sign"
         );
   }
}
