package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

public class OOROOCCIRCCRHOIOIORIHCHHOOCCOR extends RRCRRCORICCHOHHIRCHIROOHIIOHCO {
   @NotNull
   @Override
   public String RRIICCIOCHRHOHIRIHCHRHOCOROOCC() {
      return "log";
   }

   @Override
   public boolean HICRRICCHCCROOHHCHOCOCCHOIHHOC(@NotNull IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      String var2 = var1.bridge$getItemRegistryName();
      return var2.startsWith("minecraft:") && var2.endsWith("_log") || var2.equals("minecraft:log") || var2.equals("minecraft:log2");
   }

   @Override
   protected String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      int var1, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR var2
   ) {
      int var3 = var2.bridge$getItemDamage();
      if (var2.bridge$getItemRegistryName().endsWith("log2")) {
         var3 += 4;
      }

      return (String)RIROICHCRROROHCCROOCCCCOCHCCRI.OCHOHHOIOIRCICHRRHHCOIORHHCIRH.inverse().getOrDefault(var3, "oak");
   }

   @Override
   protected int HCIIICCOOORRIIRROCIIHIOHRRHIOI(String var1) {
      return (Integer)RIROICHCRROROHCCROOCCCCOCHCCRI.OCHOHHOIOIRCICHRRHHCOIORHHCIRH.getOrDefault(var1, 0);
   }

   @Override
   protected String COIROICCIRCOIOOOHROIRCOIOOORCH() {
      return "oak";
   }

   @Override
   public Optional<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      @NotNull CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 5) {
         return super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      }

      int var2 = this.HCIIICCOOORRIIRROCIIHIOHRRHIOI(var1.value());
      String var3 = "minecraft:log";
      if (var2 > 3) {
         var3 = var3 + "2";
         var2 -= 4;
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR var4 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHIOICROIRRRIROHIHICIRRHCCIRHO(
         var3
      );
      var4.bridge$setItemDamage(var2);
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHRIICOIOORCHCOIICOOIHIRHHICRI(
         var4
      );
   }
}
