package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Nullable;
import lombok.Generated;

class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private boolean loaded = false;
   private List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> CRHRRCHHOHOIIHCOOOCCHCCCHRHOCR;
   private List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> IROOCOIHCCOROCIOHOORCOHIHCRRCO;

   public void load() {
      this.CRHRRCHHOHOIIHCOOOCCHCCCHRHOCR = new ArrayList<>();
      this.IROOCOIHCCOROCIOHOORCOHIHCRRCO = new ArrayList<>();
      this.loaded = true;
      String var1 = "hypixel/teamview.json";
      Path var2 = IIRHCHHOICHRICOOCRORCCIOOIHOIR.HHIRHHICRHCCHRHIIIOIRRROCRHRIH.resolve(var1);
      if (!var2.toFile().exists()) {
         com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            "Unable to load %s, file doesn't exist", var1
         );
      } else {
         String var3 = Files.readString(var2);
         JsonElement var4 = JsonParser.parseString(var3);
         if (!var4.isJsonObject()) {
            com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
               "Unable to load %s, not a json object", var1
            );
         } else {
            JsonObject var5 = var4.getAsJsonObject();
            if (var5.has("partySupport")) {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5.getAsJsonArray("partySupport"), this.CRHRRCHHOHOIIHCOOOCCHCCCHRHOCR);
            }

            if (var5.has("blacklist")) {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5.getAsJsonArray("blacklist"), this.IROOCOIHCCOROCIOHOORCOHIHCRRCO);
            }
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      JsonArray var1,
      List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> var2
   ) {
      for (JsonElement var4 : var1) {
         if (var4 instanceof JsonObject var5) {
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = null;
            if (var5.has("gametype")) {
               var6 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  new String[]{var5.get("gametype").getAsString()}, false
               );
            } else if (var5.has("gametypeRegex")) {
               var6 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  new String[]{var5.get("gametypeRegex").getAsString()}, true
               );
            } else if (var5.has("gametypes")) {
               var6 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  this.CORCOCICIRIOHROHROIIOOHICCHCRR(var5.get("gametypes")), false
               );
            }

            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = null;
            if (var5.has("mode")) {
               var7 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  new String[]{var5.get("mode").getAsString()}, false
               );
            } else if (var5.has("modeRegex")) {
               var7 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  new String[]{var5.get("modeRegex").getAsString()}, true
               );
            } else if (var5.has("modes")) {
               var7 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  this.CORCOCICIRIOHROHROIIOOHICCHCRR(var5.get("modes")), false
               );
            }

            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8 = null;
            if (var5.has("map")) {
               var8 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  new String[]{var5.get("map").getAsString()}, false
               );
            } else if (var5.has("mapRegex")) {
               var8 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  new String[]{var5.get("mapRegex").getAsString()}, true
               );
            } else if (var5.has("maps")) {
               var8 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  this.CORCOCICIRIOHROHROIIOOHICCHCRR(var5.get("maps")), false
               );
            }

            var2.add(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  var6, var7, var8
               )
            );
         }
      }
   }

   private String[] CORCOCICIRIOHROHROIIOOHICCHCRR(JsonElement var1) {
      if (var1 instanceof JsonArray var2) {
         String[] var3 = new String[var2.size()];

         for (int var4 = 0; var4 < var2.size(); var4++) {
            JsonElement var5 = var2.get(var4);
            if (var5.isJsonPrimitive()) {
               var3[var4] = var5.getAsString();
            }
         }

         return var3;
      } else {
         return new String[0];
      }
   }

   public boolean CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      if (!var1.CHICHOOHORHIRICCCRHCHCIOHOCHHI() && var1.CIOCCCICHORIOIRROOOCCCRHHORRRI != null) {
         for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 : this.CRHRRCHHOHOIIHCOOOCCHCCCHRHOCR) {
            if (var3.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1)) {
               return true;
            }
         }

         return false;
      } else {
         return true;
      }
   }

   public boolean RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      if (var1.CHICHOOHORHIRICCCRHCHCIOHOCHHI()) {
         return false;
      }

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 : this.IROOCOIHCCOROCIOHOORCOHIHCRRCO) {
         if (var3.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1)) {
            return true;
         }
      }

      return false;
   }

   @Generated
   public boolean isLoaded() {
      return this.loaded;
   }

   private record IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
      @Nullable
      private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OCHRHIIRCOIRHCIROCIIRRHRORHCHC;
      @Nullable
      private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OORORCIOCCHICOIIIOIIHORRRRHOHO;
      @Nullable
      private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH COOCOCIOIOIIRORICHIHRIHRHCOIRC;

      private IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         @Nullable com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
         @Nullable com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
         @Nullable com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3
      ) {
         this.OCHRHIIRCOIRHCIROCIIRRHRORHCHC = var1;
         this.OORORCIOCCHICOIIIOIIHORRRRHOHO = var2;
         this.COOCOCIOIOIIRORICHIHRIHRHCOIRC = var3;
      }

      public boolean RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
         com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
      ) {
         return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.OCHRHIIRCOIRHCIROCIIRRHRORHCHC, var1.HRCOCIRHOIRHCHRCOHHIROHIORRRIH)
            && this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.OORORCIOCCHICOIIIOIIHORRRRHOHO, var1.CIOCCCICHORIOIRROOOCCCRHHORRRI)
            && this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.COOCOCIOIOIIRORICHIHRIHRHCOIRC, var1.CHCCORCICOHOCHICRHIRORIORHOICC);
      }

      private boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
         String var2
      ) {
         if (var1 == null || var1.CIHHOIICHOIRRCIICCORORHIIRHHOO.length == 0) {
            return true;
         }

         if (var2 == null) {
            return false;
         }

         for (String var6 : var1.CIHHOIICHOIRRCIICCORORHIIRHHOO) {
            if (var1.CORHRRRCIICROORCCCCHCOCIOORRRI ? var2.matches(var6) : var2.equals(var6)) {
               return true;
            }
         }

         return false;
      }

      @Nullable
      public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OICRRRHRRHHCHCIRCOHHRHIRRRCHRI() {
         return this.OCHRHIIRCOIRHCIROCIIRRHRORHCHC;
      }

      @Nullable
      public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ORCHCRCOHCHIOHHCORCHRRHROHHICI() {
         return this.OORORCIOCCHICOIIIOIIHORRRRHOHO;
      }

      @Nullable
      public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OCCIHCOIICHOROICRRRROOCCHIHRIO() {
         return this.COOCOCIOIOIIRORICHIHRIHRHCOIRC;
      }
   }

   private record RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      private final String[] CIHHOIICHOIRRCIICCORORHIIRHHOO;
      private final boolean CORHRRRCIICROORCCCCHCOCIOORRRI;

      private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String[] var1, boolean var2) {
         this.CIHHOIICHOIRRCIICCORORHIIRHHOO = var1;
         this.CORHRRRCIICROORCCCCHCOCIOORRRI = var2;
      }

      public String[] RORCIIIRRORIOIIIHIOIOCRHOOOOOH() {
         return this.CIHHOIICHOIRRCIICCORORHIIRHHOO;
      }

      public boolean regex() {
         return this.CORHRRRCIICROORCCCCHCOCIOORRRI;
      }
   }
}
