package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import it.unimi.dsi.fastutil.floats.FloatArrayList;
import it.unimi.dsi.fastutil.floats.FloatList;
import java.util.ArrayList;
import java.util.HashMap;
import lombok.Generated;
import org.joml.Vector3d;
import org.joml.Vector3i;

public class HRCHROOHRIHCRCRHRIIROCIRHOIRHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private static final String RRCOIOICOHCCICIHRROICHRCRRORII = "block.sand.step";
   private static final String HHORIRRCIHORIOOIICOICHHCHOHCIR = "entity.cat.purreow";
   private String OCOIIROOHHHHCOCIHHOOROHOCHIHHH;
   private String CIIHHRCCRHIOOIRROCHRCHCIHOOHHC;
   private final ArrayList<HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> HHRIIIOOIIRHICORCRIRCHRCOHCRHO = new ArrayList<>();
   private final FloatList RRCCCHCRHCIOCIOIOHOROCORIIIICR = new FloatArrayList();
   private IIRHCHHOICHRICOOCRORCCIOOIHOIR IRCRHHOCICOICRCCCCICHOOICOHIRI = null;
   private long HICRHORRRIHRCCCICRRIHCOIROHRIO = -1L;

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      CRRRICCRROCOHHOHIICIHORCOORRRH var1, com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2
   ) {
      super(true);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(false, var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRIIIRORRHRROOOIRHROOOIIHIHIRH,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH(var2)
      );
      this.handle(IHIRRIIORRHORHRORIHOROIRCORCOO.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(IIRHCHHOICHRICOOCRORCCIOOIHOIR.class, this::HHCCIRHCCCIIRHCROHIORHIRHHIORH);
      this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.class,
         this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         this::OCOHORHCROHICRRIHCIHHRRCIHICRI
      );
      this.handle(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
   }

   @Override
   public String getId() {
      return "SKYBLOCK_EGG_LOCATOR";
   }

   @Override
   protected void CCHHCIRHICHHHHRRIHIORCCORCCIHR(boolean var1) {
   }

   @Override
   public void COIHORRCHRRCHOCIRHHRRIOIHRIHCC(boolean var1) {
      if (!var1) {
         this.ICOIRCCHOOIRRIIOCRRHIHIIOCOIHC();
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IHIRRIIORRHORHRORIHOROIRCORCOO var1) {
      if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OIRRRHIROHCIRROICIRIRORIHHOOOI()
         )
       {
         if (this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1)) {
            Vector3d var2 = new Vector3d(var1.ICIHOIHROICHIHRIIOOCHOCCOHRIRR(), var1.HRRIHICRHIHCCOIRIOROIHOHRHCOHI(), var1.IIOCRCOCCHCIOCCORROCIRHOICIICR());
            this.HHRIIIOOIIRHICORCRIRCHRCOHCRHO
               .add(new HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, this.IRCRHHOCICOICRCCCCICHOOICOHIRI.getPitch()));
            this.OOHOIRHOCRCCIOOICHRCORHCCRHRIO();
         }
      }
   }

   private void HHCCIRHCCCIIRHCROHIORHIRHHIORH(IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OIRRRHIROHCIRROICIRIRORIHHOOOI()
         )
       {
         String var2 = var1.getPath();
         if ("block.sand.step".equals(var2)) {
            float var3 = var1.getPitch();
            if (var3 == 1.0F && var1.getVolume() == 0.15F) {
               return;
            }

            if (this.IRCRHHOCICOICRCCCCICHOOICOHIRI != null && this.IRCRHHOCICOICRCCCCICHOOICOHIRI.getPitch() > var1.getPitch()) {
               this.clearCaches();
            }

            this.IRCRHHOCICOICRCCCCICHOOICOHIRI = var1;
            this.RRCCCHCRHCIOCIOIOHOROCORIIIICR.add(var1.getPitch());
            this.HICRHORRRIHRCCCICRRIHCOIROHRIO = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
         } else if ("entity.cat.purreow".equals(var2)) {
            this.clearCaches();
            this.ICOIRCCHOOIRRIIOCRRHIHIIOCOIHC();
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOIICIRIICICIIOORHCIIIIRRIHRHI var1) {
      if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OIRRRHIROHCIRROICIRIRORIHHOOOI()
         )
       {
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() - this.HICRHORRRIHRCCCICRRIHCOIROHRIO > 1000L) {
            this.clearCaches();
         }
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1
   ) {
      if (this.OCOIIROOHHHHCOCIHHOOROHOCHIHHH != null) {
         if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OIRRRHIROHCIRROICIRIRORIHHOOOI()
            )
          {
            CRRRICCRROCOHHOHIICIHORCOORRRH var2 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
               .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            if (var2.HRCHRHIHOCOOORIIOCCCOIROOORHOI() != null) {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
               if (var3 != null) {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = var2.HRCHRHIHOCOOORIIOCCCOIROOORHOI();
                  String var5 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
                     .name();
                  HashMap var6 = var4.RRRRCIIHORIRCIHCRORHCOCOIIRRIO().get(var5);
                  if (var6 != null) {
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var6.get(
                        this.OCOIIROOHHHHCOCIHHOOROHOCHIHHH
                     );
                     Vector3i var8 = var7.OICOOOCHCRRIRCCOOCCCOICHRCHHHO();
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var9 = var1.HHIIOHOORHHCCHRHHRCIORCROORCOI();
                     com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var10 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IHRHHIOIIICOROOORIOHCIROIRCOHH();
                     var9.push();
                     var9.translate(-var10.bridge$renderPosX(), -var10.bridge$renderPosY(), -var10.bridge$renderPosZ());
                     if (var2.CCIHHRIOOOOCOHRCIHOHROOICIORCC(var5, this.OCOIIROOHHHHCOCIHHOOROHOCHIHHH)) {
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           var9, var8, var2.HHRORIRIOHHRRICRIHCHRRHORHCHOI().OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F), true
                        );
                     } else {
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           var9, var8, var2.RIHOIRCIOOHIHRRRIIHCOCOOROORIC().OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F), true
                        );
                     }

                     double var11 = var10.bridge$renderPosX();
                     double var13 = var10.bridge$renderPosY();
                     double var15 = var10.bridge$renderPosZ();
                     double var17 = var8.x() + 0.5;
                     double var19 = var8.y() + 1.5;
                     double var21 = var8.z() + 0.5;
                     double var23 = var3.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(var17, var19, var21);
                     if (var23 > 100.0) {
                        double var25 = Math.sqrt(var23);
                        var17 = (var17 - var11) * (10.0 / var25) + var11;
                        var19 = (var19 - var13) * (10.0 / var25) + var13;
                        var21 = (var21 - var15) * (10.0 / var25) + var15;
                     }

                     if (var2.CCIHHRIOOOOCOHRCIHOHROOICIORCC(var5, this.OCOIIROOHHHHCOCIHHOOROHOCHIHHH)) {
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           var9,
                           "Egglocator Estimate (Duplicate)",
                           var17,
                           var19,
                           var21,
                           com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI.ICORRRIOCIIRICCCOIHCRRIORHOIIC(
                              var2.HHRORIRIOHHRRICRIHCHRRHORHCHOI().OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F)
                           ),
                           true
                        );
                     } else {
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           var9,
                           "Egglocator Estimate",
                           var17,
                           var19,
                           var21,
                           com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI.ICORRRIOCIIRICCCOIHCRRIORHOIIC(
                              var2.RIHOIRCIOOHIHRRRIIHCOCOOROORIC().OCOHORHCROHICRRIHCIHHRRCIHICRI(0.0F)
                           ),
                           true
                        );
                     }

                     var9.pop();
                  }
               }
            }
         }
      }
   }

   private void OCOHORHCROHICRRIHCIHHRRCIHICRI(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RRRCCHIOCICOIOIRRCOOIRHHCORCIH()
         )
       {
         if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.OIRRRHIROHCIRROICIRIRORIHHOOOI()
            )
          {
            if (this.CIIHHRCCRHIOOIRROCHRCHCIHOOHHC != null) {
               String var2 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.getTextWithoutFormattingCodes(
                  var1.OCOCIORRCHHHHHHHOOIHRRHOIHICRH()
               );
               var2 = var2.replace("’", "'");
               if (var2.startsWith("HOPPITY'S HUNT You found a Chocolate ") && var2.endsWith(this.CIIHHRCCRHIOOIRROCHRCHCIHOOHHC)) {
                  this.ICOIRCCHOOIRRIIOCRRHIHIIOCOIHC();
               }
            }
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.clearCaches();
      this.ICOIRCCHOOIRRIIOCRRHIHIIOCOIHC();
   }

   private boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(IHIRRIIORRHORHRORIHOROIRCORCOO var1) {
      if (var1.ICRCIIIHROCRHOHHHHRCCCOOCICHOO()
         != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HAPPY_VILLAGER
         )
       {
         return false;
      }

      if (var1.IIORORCRIHOHCOHCOCICHICROHICII() != 0.0F || var1.CROCHRCHHIOCRHRHOOIRIHIHCIHORI() != 0.0F || var1.OCCIIHIOCOICOCCCHHHCHCIHHIIIRH() != 0.0F) {
         return false;
      }

      if (this.IRCRHHOCICOICRCCCCICHOOICOHIRI == null) {
         return false;
      }

      double var2 = this.IRCRHHOCICOICRCCCCICHOOICOHIRI.HIIRCCHHCIHROHCRICCOCIHRRHCRIH() - var1.ICIHOIHROICHIHRIIOOCHOCCOHRIRR();
      double var4 = this.IRCRHHOCICOICRCCCCICHOOICOHIRI.CICHIHIRRIRIICHCOCHIIOIIHRHROR() - var1.HRRIHICRHIHCCOIRIOROIHOHRHCOHI();
      double var6 = this.IRCRHHOCICOICRCCCCICHOOICOHIRI.CIROCOHOCRHOHCCRIHIRHOICHRIRIR() - var1.IIOCRCOCCHCIOCCORROCIRHOICIICR();
      double var8 = var2 * var2 + var4 * var4 + var6 * var6;
      return var8 < 0.5;
   }

   private void OOHOIRHOCRCCIOOICHRCORHCCRHRIO() {
      if (this.HHRIIIOOIIRHICORCRIRCHRCOHCRHO.size() >= 5) {
         Vector3d var1 = this.HHRIIIOOIIRHICORCRIRCHRCOHCRHO.get(0).ROOCCHRHHIIOICICHIIRRHCOCOCIHC();
         Vector3d var2 = new Vector3d(this.HHRIIIOOIIRHICORCRIRCHRCOHCRHO.get(this.HHRIIIOOIIRHICORCRIRCHRCOHCRHO.size() - 1).ROOCCHRHHIIOICICHIIRRHCOCOCIHC());
         double var3 = Math.E
               / com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  this.RRCCCHCRHCIOCIOIOHOROCORIIIICR
               )
            - var1.distance(var2);
         Vector3d var5 = new Vector3d(var2)
            .sub(this.HHRIIIOOIIRHICORCRIRCHRCOHCRHO.get(this.HHRIIIOOIIRHICORCRIRCHRCOHCRHO.size() - 4).ROOCCHRHHIIOICICHIIRRHCOCOCIHC())
            .normalize();
         Vector3d var6 = var2.add(var5.mul(var3));
         Vector3i var7 = new Vector3i((int)Math.floor(var6.x()), (int)Math.floor(var6.y()), (int)Math.floor(var6.z()));
         CRRRICCRROCOHHOHIICIHORCOORRRH var8 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
            .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
         if (var8.HRCHRHIHOCOOORIIOCCCOIROOORHOI() != null) {
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var9 = var8.HRCHRHIHOCOOORIIOCCCOIROOORHOI();
            String var10 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
               .name();
            HashMap var11 = var9.RRRRCIIHORIRCIHCRORHCOCOIIRRIO().get(var10);
            if (var11 != null) {
               String var12 = null;
               String var13 = null;
               double var14 = 0.0;

               for (String var17 : var11.keySet()) {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var18 = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var11.get(
                     var17
                  );
                  Vector3i var19 = var18.OICOOOCHCRRIRCCOOCCCOICHRCHHHO();
                  double var20 = var7.distanceSquared(var19);
                  if (var12 == null || var20 <= var14) {
                     var12 = var17;
                     var13 = var18.getMessage();
                     var14 = var20;
                  }
               }

               this.OCOIIROOHHHHCOCIHHOOROHOCHIHHH = var12;
               this.CIIHHRCCRHIOOIRROCHRCHCIHOOHHC = var13;
            }
         }
      }
   }

   private void clearCaches() {
      this.HHRIIIOOIIRHICORCRIRCHRCOHCRHO.clear();
      this.RRCCCHCRHCIOCIOIOHOROCORIIIICR.clear();
      this.IRCRHHOCICOICRCCCCICHOOICOHIRI = null;
   }

   private void ICOIRCCHOOIRRIIOCRRHIHIIOCOIHC() {
      this.OCOIIROOHHHHCOCIHHOOROHOCHIHHH = null;
      this.CIIHHRCCRHIOOIRROCHRCHCIHOOHHC = null;
   }

   @Generated
   public String IIRHOHOORIHOIRCCCOCCOCIOCHRHOH() {
      return this.OCOIIROOHHHHCOCIHHOOROHOCHIHHH;
   }

   private static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      private final Vector3d RIRRCRRIRRHHIORCICCOHHRRHOCIIC;
      private final float IRCICHRCRCHRIRRCHHCRRHCHCOHICI;

      @Generated
      public Vector3d ROOCCHRHHIIOICICHIIRRHCOCOCIHC() {
         return this.RIRRCRRIRRHHIORCICCOHHRRHOCIIC;
      }

      @Generated
      public float getPitch() {
         return this.IRCICHRCRCHRIRRCHHCRRHCHCOHICI;
      }

      @Generated
      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Vector3d var1, float var2) {
         this.RIRRCRRIRRHHIORCICCOHHRRHOCIIC = var1;
         this.IRCICHRCRCHRIRRCHHCRRHCHCOHICI = var2;
      }
   }
}
