package com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;

import com.eliotlash.molang.ast.Evaluatable;
import com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import lombok.Generated;
import org.jetbrains.annotations.NotNull;
import org.jspecify.annotations.Nullable;

public class RIOOCHICIHRHOHCCCCCHOCCCOHCRHI {
   @ORHIOICIOCRRHOOCOHRORIHICHRCRR(value = "id", required = true)
   @NotNull
   private String id;
   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("condition")
   private Evaluatable ORCRIRICIIRRRHOOIIIRHOCHIHIOCR = new com.moonsworth.lunar.client.IHIRRIIORRHORHRORIHOROIRCORCOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      1.0
   );
   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("tasks")
   private HICHRCOHCCRHOHCICOOCHOIHCCHIRI @Nullable [] HOCICICIHOIOHIRHOCHOOOHIIIRROC;
   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("animation")
   private @Nullable IRCIIHHICIHRCOCRROCOICRIHHCCHH CROIHRRRCIHOOHICRCCRIRRIIIOCOI;
   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("cooldown")
   private int HRICOCIOOHCIIORRHCRORRICCHIRIO = 0;

   @NotNull
   @Generated
   public String getId() {
      return this.id;
   }

   @Generated
   public Evaluatable ORIROHHHIRIOHIRCOHOORCHIIHHHII() {
      return this.ORCRIRICIIRRRHOOIIIRHOCHIHIOCR;
   }

   @Generated
   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI @Nullable [] RCRRCOIHCICORCOCHICHHRCOOIIHII() {
      return this.HOCICICIHOIOHIRHOCHOOOHIIIRROC;
   }

   @Generated
   public @Nullable IRCIIHHICIHRCOCRROCOICRIHHCCHH IHROOCHOOCICIIHORIIHICOIRIORCI() {
      return this.CROIHRRRCIHOOHICRCCRIRRIIIOCOI;
   }

   @Generated
   public int RICRICHHOCOIOIOHOCHHIRRIHCHRHI() {
      return this.HRICOCIOOHCIIORRHCRORRICCHIRIO;
   }
}
