package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import java.time.Year;
import java.time.format.DateTimeFormatter;

public class OCOHORHCROHICRRIHCIHHRRCIHICRI extends CRRRICCRROCOHHOHIICIHORCOORRRH<Year> {
   private static final long OCRRICHOIIRHICHCROIHRCIRROCORH = 1L;
   public static final OCOHORHCROHICRRIHCIHHRRCIHICRI IRIHOCIOHROCCCOCHROIHOOIOIRHII = new OCOHORHCROHICRRIHCIHHRRCIHICRI();

   protected OCOHORHCROHICRRIHCIHHRRCIHICRI() {
      this(null);
   }

   public OCOHORHCROHICRRIHCIHHRRCIHICRI(DateTimeFormatter var1) {
      super(Year.class, var1);
   }

   protected OCOHORHCROHICRRIHCIHHRRCIHICRI(OCOHORHCROHICRRIHCIHHRRCIHICRI var1, Boolean var2, DateTimeFormatter var3) {
      super(var1, var2, var3, null);
   }

   protected OCOHORHCROHICRRIHCIHHRRCIHICRI HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      Boolean var1,
      DateTimeFormatter var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3
   ) {
      return new OCOHORHCROHICRRIHCIHHRRCIHICRI(this, var1, var2);
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Year var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
   ) {
      if (this.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var3)) {
         var2.CORHHROICCOCRHRCCOOHCRCRHICHOI(var1.getValue());
      } else {
         String var4 = this.OHHOIOOHIROIIHHOIRIOIHCIIORIIC == null ? var1.toString() : var1.format(this.OHHOIOOHIROIIHHOIRIOIHCIIORIIC);
         var2.writeString(var4);
      }
   }

   @Override
   protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var3 = var1.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO(
         var2
      );
      if (var3 != null) {
         var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.LONG
         );
      }
   }

   @Override
   protected OHHRIOHROOIHOROCIRHCHORIHRRRRI CORCOCICIRIOHROHROIIOOHICCHCRR(RCIROOOOICRHCCRRCIORHHIRCOIIIC var1) {
      return this.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1) ? OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_NUMBER_INT : OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_STRING;
   }
}
