package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import java.time.Instant;
import java.time.format.DateTimeFormatter;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends HHCCIRHCCCIIRHCROHIORHIRHHIORH<Instant> {
   private static final long CRCCOIOIOIHHOORRHCCHCHHICCIROR = 1L;
   public static final IRCIIHHICIHRCOCRROCOICRIHHCCHH OCCHIIIIIRHHRCCICIIROHHRICCCCR = new IRCIIHHICIHRCOCRROCOICRIHHCCHH();

   protected IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
      super(Instant.class, Instant::toEpochMilli, Instant::getEpochSecond, Instant::getNano, null);
   }

   @Deprecated
   protected IRCIIHHICIHRCOCRROCOICRIHHCCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, Boolean var2, DateTimeFormatter var3) {
      this(var1, var2, var1.CCHIIRIOROCIOIORCCHICHHRICRCHI, var3);
   }

   protected IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      Boolean var2,
      DateTimeFormatter var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4
   ) {
      super(var1, var2, var1.CCHIIRIOROCIOIORCCHICHHRICRCHI, var3, var4);
   }

   protected IRCIIHHICIHRCOCRROCOICRIHHCCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, Boolean var2, Boolean var3, DateTimeFormatter var4) {
      super(var1, var2, var3, var4);
   }

   @Override
   protected CRRRICCRROCOHHOHIICIHORCOORRRH<Instant> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      Boolean var1,
      DateTimeFormatter var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3
   ) {
      return new IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, var1, var2, var3);
   }

   @Override
   protected CRRRICCRROCOHHOHIICIHORCOORRRH<?> CRRRICCRROCOHHOHIICIHORCOORRRH(Boolean var1, Boolean var2) {
      return new IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, this.ROHIROIRIRIRRIIRHRHHIRHCIICCRI, var2, this.OHHOIOOHIROIIHHOIRIOIHCIIORIIC);
   }
}
