package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IOHIHIIHCCCCCIHRORIOIOORCIOHII;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import java.lang.reflect.Type;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;

abstract class CRRRICCRROCOHHOHIICIHORCOORRRH<T>
   extends RRCRRCORICCHOHHIRCHIROOHIIOHCO<T>
   implements com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRICCOOHHHCHOORCICOCOHIHOIRHOO {
   private static final long CCORIOORROCCRIHRCIROIHRRCRRHOR = 1L;
   protected final Boolean ROHIROIRIRIRRIIRHRHHIRHCIICCRI;
   protected final Boolean CCHIIRIOROCIOIORCCHICHHRICRCHI;
   protected final DateTimeFormatter OHHOIOOHIROIIHHOIRIOIHCIIORIIC;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH HORORHCIOHHIIRROROOHRRCRHIOCCO;
   protected transient volatile com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI HORHIICORCRRRHOIOIRRIHRIIHIIII;

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(Class<T> var1) {
      this(var1, null);
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(Class<T> var1, DateTimeFormatter var2) {
      super(var1);
      this.ROHIROIRIRIRRIIRHRHHIRHCIICCRI = null;
      this.CCHIIRIOROCIOIORCCHICHHRICRCHI = null;
      this.HORORHCIOHHIIRROROOHRRCRHIOCCO = null;
      this.OHHOIOOHIROIIHHOIRIOIHCIIORIIC = var2;
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(
      CRRRICCRROCOHHOHIICIHORCOORRRH<?> var1,
      Boolean var2,
      DateTimeFormatter var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4
   ) {
      this(var1, var2, null, var3, var4);
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(
      CRRRICCRROCOHHOHIICIHORCOORRRH<?> var1,
      Boolean var2,
      Boolean var3,
      DateTimeFormatter var4,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var5
   ) {
      super(var1.handledType());
      this.ROHIROIRIRIRRIIRHRHHIRHCIICCRI = var2;
      this.CCHIIRIOROCIOIORCCHICHHRICRCHI = var3;
      this.OHHOIOOHIROIIHHOIRIOIHCIIORIIC = var4;
      this.HORORHCIOHHIIRROROOHRRCRHIOCCO = var5;
   }

   protected abstract CRRRICCRROCOHHOHIICIHORCOORRRH<?> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      Boolean var1,
      DateTimeFormatter var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3
   );

   @Deprecated
   protected CRRRICCRROCOHHOHIICIHORCOORRRH<?> RHRCRCIOIOICRHRCCROIICCRRCOOOI(Boolean var1) {
      return this;
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH<?> CRRRICCRROCOHHOHIICIHORCOORRRH(Boolean var1, Boolean var2) {
      return this;
   }

   @Override
   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> createContextual(
      RCIROOOOICRHCCRRCIORHHIRCOIIIC var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var3 = this.findFormatOverrides(
         var1, var2, this.handledType()
      );
      if (var3 == null) {
         return this;
      }

      Boolean var4 = null;
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var5 = var3.HIHRRCOCICCHICROIHIOCRIRCCHHCI();
      if (var5
            != com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ARRAY
         && !var5.isNumeric()) {
         var4 = var5
               == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.STRING
            ? Boolean.FALSE
            : null;
      } else {
         var4 = Boolean.TRUE;
      }

      DateTimeFormatter var6 = this.OHHOIOOHIROIIHHOIRIOIHCIIORIIC;
      if (var3.IOHHCIROOCCCHCHHHCHOHIORHIRRCC()) {
         var6 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var3);
      }

      CRRRICCRROCOHHOHIICIHORCOORRRH var7 = this;
      if (var5 != this.HORORHCIOHHIIRROROOHRRCRHIOCCO || var4 != this.ROHIROIRIRIRRIIRHRHHIRHCIICCRI || var6 != this.OHHOIOOHIROIIHHOIRIOIHCIIORIIC) {
         var7 = var7.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var4, var6, var5);
      }

      Boolean var8 = var3.CRRRICCRROCOHHOHIICIHORCOORRRH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WRITE_DATES_WITH_ZONE_ID
      );
      Boolean var9 = var3.CRRRICCRROCOHHOHIICIHORCOORRRH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS
      );
      if (var8 != null || var9 != null) {
         var7 = var7.CRRRICCRROCOHHOHIICIHORCOORRRH(var8, var9);
      }

      return var7;
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR getSchema(
      RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, Type var2
   ) {
      return this.createSchemaNode(var1.CRICCOOHHHCHOORCICOCOHIHOIRHOO(IOHIHIIHCCCCCIHRORIOIOORCIOHII.WRITE_DATES_AS_TIMESTAMPS) ? "array" : "string", true);
   }

   @Override
   public void acceptJsonFormatVisitor(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      if (this.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1.COCCOCCOIHOCRICOHOIHHORHROHRHO())) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2);
      } else {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.OCOHORHCROHICRRIHCIHHRRCIHICRI var3 = var1.RORCHCIIICOHIRROOORHOCCCCIOCCI(
            var2
         );
         if (var3 != null) {
            var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CIOHHCORHRCCRICCCORIHCRHCCCRRR.DATE_TIME
            );
         }
      }
   }

   protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var1.CRHROHHHCIHHCOHCOORCRIHHIICROR(
         this.CRICCOOHHHCHOORCICOCOHIHOIRHOO(var1.COCCOCCOIHOCRICOHOIHHORHROHRHO())
      );
      if (var3 != null) {
         var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.INTEGER
         );
      }
   }

   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI CRICCOOHHHCHOORCICOCOHIHOIRHOO(
      RCIROOOOICRHCCRRCIORHHIRCOIIIC var1
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2 = this.HORHIICORCRRRHOIOIRRIHRIIHIIII;
      if (var2 == null) {
         var2 = var1.CCOCHOROIOICHHICOCIHCHHOCOOIII().RIROICHCRROROHCCROOCCCCOCHCCRI(List.class, Integer.class);
         this.HORHIICORCRRRHOIOIRRIHRIIHIIII = var2;
      }

      return var2;
   }

   protected IOHIHIIHCCCCCIHRORIOIOORCIOHII RIRORCIRHIHIHCHOCHRRIOCIRIIRIH() {
      return IOHIHIIHCCCCCIHRORIOIOORCIOHII.WRITE_DATES_AS_TIMESTAMPS;
   }

   protected boolean HICHRCOHCCRHOHCICOOCHOIHCCHIRI(RCIROOOOICRHCCRRCIORHHIRCOIIIC var1) {
      if (this.ROHIROIRIRIRRIIRHRHHIRHCIICCRI != null) {
         return this.ROHIROIRIRIRRIIRHRHHIRHCIICCRI;
      }

      if (this.HORORHCIOHHIIRROROOHRRCRHIOCCO != null) {
         if (this.HORORHCIOHHIIRROROOHRRCRHIOCCO
            == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.STRING
            )
          {
            return false;
         }

         if (this.HORORHCIOHHIIRROROOHRRCRHIOCCO
            == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.NUMBER_INT
            )
          {
            return true;
         }
      }

      return this.OHHOIOOHIROIIHHOIRIOIHCIIORIIC == null && var1 != null && var1.CRICCOOHHHCHOORCICOCOHIHOIRHOO(this.RIRORCIRHIHIHCHOCHRRIOCIRIIRIH());
   }

   protected boolean IIHRRHORCRCROCHHOHORCHCROCIHRO(RCIROOOOICRHCCRRCIORHHIRCOIIIC var1) {
      return this.ROHIROIRIRIRRIIRHRHHIRHCIICCRI != null ? this.ROHIROIRIRIRRIIRHRHHIRHCIICCRI : false;
   }

   protected boolean OCOHORHCROHICRRIHCIHHRRCIHICRI(RCIROOOOICRHCCRRCIORHHIRCOIIIC var1) {
      if (this.CCHIIRIOROCIOIORCCHICHHRICRCHI != null) {
         return this.CCHIIRIOROCIOIORCCHICHHRICRCHI;
      }

      if (this.HORORHCIOHHIIRROROOHRRCRHIOCCO != null) {
         if (this.HORORHCIOHHIIRROROOHRRCRHIOCCO
            == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.NUMBER_INT
            )
          {
            return false;
         }

         if (this.HORORHCIOHHIIRROROOHRRCRHIOCCO
            == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.NUMBER_FLOAT
            )
          {
            return true;
         }
      }

      return var1 != null && var1.CRICCOOHHHCHOORCICOCOHIHOIRHOO(IOHIHIIHCCCCCIHRORIOIOORCIOHII.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS);
   }

   protected DateTimeFormatter RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RCIROOOOICRHCCRRCIORHHIRCOIIIC var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      String var4 = var2.getPattern();
      Locale var5 = var2.RIHIRHHOIHCIRRRIRCIIIRHOHCCORI() ? var2.IRHRHRRHRIOICORHHHIROIRCCHOHCO() : var1.IRHRHRRHRIOICORHHHIROIRCCHOHCO();
      DateTimeFormatter var3;
      if (var5 == null) {
         var3 = DateTimeFormatter.ofPattern(var4);
      } else {
         var3 = DateTimeFormatter.ofPattern(var4, var5);
      }

      if (var2.RRCIORCRCORHCOHOIHRIORHHHORRRI()) {
         var3 = var3.withZone(var2.getTimeZone().toZoneId());
      }

      return var3;
   }
}
