package com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

import lombok.Generated;

public enum IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   BOOL(1, "bool", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BOOL, false),
   BVEC2(2, "bvec2", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BOOL, false),
   BVEC3(3, "bvec3", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BOOL, false),
   BVEC4(4, "bvec4", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BOOL, false),
   INT(1, "int", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.INT, true),
   IVEC2(2, "ivec2", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.INT, false),
   IVEC3(3, "ivec3", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.INT, true),
   IVEC4(4, "ivec4", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.INT, false),
   UINT(1, "uint", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.UINT, false),
   UVEC2(2, "uvec2", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.UINT, false),
   UVEC3(3, "uvec3", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.UINT, false),
   UVEC4(4, "uvec4", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.UINT, false),
   FLOAT(1, "float", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, true),
   VEC2(2, "vec2", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, true),
   VEC3(3, "vec3", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, true),
   VEC4(4, "vec4", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, true),
   DOUBLE(1, "double", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DOUBLE, false),
   DVEC2(2, "dvec2", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DOUBLE, false),
   DVEC3(3, "dvec3", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DOUBLE, false),
   DVEC4(4, "dvec4", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DOUBLE, false),
   MATRIX2X2(4, "matrix2x2", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false),
   MATRIX3X2(6, "matrix3x2", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false),
   MATRIX4X2(8, "matrix4x2", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false),
   MATRIX2X3(6, "matrix2x3", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false),
   MATRIX3X3(9, "matrix3x3", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false),
   MATRIX4X3(12, "matrix4x3", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false),
   MATRIX2X4(8, "matrix2x4", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false),
   MATRIX3X4(12, "matrix3x4", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false),
   MATRIX4X4(16, "matrix4x4", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, true),
   TEXEL_BUFFER(16, "texel_buffer", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false),
   UNIFORM_BUFFER(16, "uniform_buffer", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FLOAT, false);

   private final int count;
   private final String name;
   private final IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH scalarType;
   private final boolean supportedByMojang;

   public boolean isMatrix() {
      return this.ordinal() >= 20 && this.ordinal() <= 28;
   }

   public String asMojangType() {
      if (!this.supportedByMojang) {
         throw new UnsupportedOperationException("Can't get mojang type for uniform type: " + this.name);
      } else {
         return this.isMatrix() ? this.name : this.scalarType.name().toLowerCase();
      }
   }

   public String asGlslType() {
      if (this.isMatrix()) {
         return switch (this) {
            case MATRIX2X2 -> "mat2";
            case MATRIX3X3 -> "mat3";
            case MATRIX4X4 -> "mat4";
            default -> this.name.replace("matrix", "mat");
         };
      } else {
         return this.name;
      }
   }

   @Generated
   public int getCount() {
      return this.count;
   }

   @Generated
   public String getName() {
      return this.name;
   }

   @Generated
   public IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH getScalarType() {
      return this.scalarType;
   }

   @Generated
   public boolean isSupportedByMojang() {
      return this.supportedByMojang;
   }

   @Generated
   IRCIIHHICIHRCOCRROCOICRIHHCCHH(int var3, String var4, IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5, boolean var6) {
      this.count = var3;
      this.name = var4;
      this.scalarType = var5;
      this.supportedByMojang = var6;
   }

   public enum RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      BOOL,
      INT,
      UINT,
      FLOAT,
      DOUBLE;
   }
}
