package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.util.HIHCCHCCOCOHRICOICHRCOIHIIRIHO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.lib.adventure.text.Component;
import com.moonsworth.lunar.lib.adventure.text.format.TextColor;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;

public class CORCOCICIRIOHROHROIIOOHICCHCRR
   implements com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<Component> HHHOHHORHCOIRHCICRCIRIHOHRCHIH = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      null, true, true
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH> CHRIROOICCRRHHIHHIOOIIRHIHICHC = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.OOHHOHICHIOCRRORCIHCRHRIOCHOOO(-1), false, true
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<Boolean> IOIHIIHCHROIIIOCORIHHROCCCIORR = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      true, false, true
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<Double> OHCIHHICHHCCHHHRCRRHCOIRIHHICC = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      1.0, false, true
   );
   private Float HCRCCCICHHRRHROCHIOOHCHCRORCCO = null;

   public CORCOCICIRIOHROHROIIOOHICCHCRR() {
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(Component var1) {
      this.HHHOHHORHCOIRHCICRCIRIHOHRCHIH.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(
      @com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR(
   CHHOHHOIRCCRRCRIHCCOHHRCIHRHII = HIHCCHCCOCOHRICOICHRCOIHIIRIHO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.MOD_INFO,
   HHOIHRHIRCHHHRHCROOCIICRHOOIHR = "getInfo",
   RCOCOIRRCCIHCHOROORRCROHCIOCOR = true
) String var1
   ) {
      this.RHIIOORHHCCOCIORHIRCICHCHRRIII(var1);
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(
      @com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR(
   CHHOHHOIRCCRRCRIHCCOHHRCIHRHII = HIHCCHCCOCOHRICOICHRCOIHIIRIHO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.MOD_INFO,
   HHOIHRHIRCHHHRHCROOCIICRHOOIHR = "getInfo",
   RCOCOIRRCCIHCHOROORRCROHCIOCOR = true
) String var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2
   ) {
      this.RHIIOORHHCCOCIORHIRCICHCHRRIII(var1);
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2);
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(
      @com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR(
   CHHOHHOIRCCRRCRIHCCOHHRCIHRHII = HIHCCHCCOCOHRICOICHRCOIHIIRIHO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.MOD_INFO,
   HHOIHRHIRCHHHRHCROOCIICRHOOIHR = "getInfo",
   RCOCOIRRCCIHCHOROORRCROHCIOCOR = true
) String var1,
      TextColor var2
   ) {
      this.RHIIOORHHCCOCIORHIRCICHCHRRIII(var1);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2);
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(
      @com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR(
   CHHOHHOIRCCRRCRIHCCOHHRCIHRHII = HIHCCHCCOCOHRICOICHRCOIHIIRIHO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.MOD_INFO,
   HHOIHRHIRCHHHRHCROOCIICRHOOIHR = "getInfo",
   RCOCOIRRCCIHCHOROORRCROHCIOCOR = true
) String var1,
      com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      this.RHIIOORHHCCOCIORHIRCICHCHRRIII(var1);
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2);
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(Supplier<String> var1) {
      this.IOHIHIIHCCCCCIHRORIOIOORCIOHII(var1);
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(
      Supplier<String> var1, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2
   ) {
      this.IOHIHIIHCCCCCIHRORIOIOORCIOHII(var1);
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2);
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(Supplier<String> var1, TextColor var2) {
      this.IOHIHIIHCCCCCIHRORIOIOORCIOHII(var1);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2);
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR(
      Supplier<String> var1, com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      this.IOHIHIIHCCCCCIHRORIOIOORCIOHII(var1);
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2);
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR RHIIOORHHCCOCIORHIRCICHCHRRIII(
      @com.moonsworth.lunar.client.util.CORCOCICIRIOHROHROIIOOHICCHCRR(
   CHHOHHOIRCCRRCRIHCCOHHRCIHRHII = HIHCCHCCOCOHRICOICHRCOIHIIRIHO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.MOD_INFO,
   HHOIHRHIRCHHHRHCROOCIICRHOOIHR = "getInfo",
   RCOCOIRRCCIHCHOROORRCROHCIOCOR = true
) String var1
   ) {
      this.HHHOHHORHCOIRHCICRCIRIHOHRCHIH.IRRCCOICORICIHCHRHIHIHROIRHOCR(Component.text(var1));
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR IOHIHIIHCCCCCIHRORIOIOORCIOHII(Supplier<String> var1) {
      this.HHHOHHORHCOIRHCICRCIRIHOHRCHIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(() -> Component.text((String)var1.get()));
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR OCOHORHCROHICRRIHCIHHRRCIHICRI(Component var1) {
      this.HHHOHHORHCOIRHCICRCIRIHOHRCHIH.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR RCIROOOOICRHCCRRCIORHHIRCOIIIC(Supplier<Component> var1) {
      this.HHHOHHORHCOIRHCICRCIRIHOHRCHIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR OCIROOIHIHRHOCCHIIIROOCRIIOCRR(int var1) {
      this.CHRIROOICCRRHHIHHIOOIIRHIHICHC
         .IRRCCOICORICIHCHRHIHIHROIRHOCR(
            com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.OOHHOHICHIOCRRORCIHCRHRIOCHOOO(var1)
         );
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR OOCCRCRCOHIIORCCORCRCIRRROIOOR(Supplier<Integer> var1) {
      this.CHRIROOICCRRHHIHHIOOIIRHIHICHC
         .RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
            () -> com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.OOHHOHICHIOCRRORCIHCRHRIOCHOOO(
               (Integer)var1.get()
            )
         );
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      this.CHRIROOICCRRHHIHHIOOIIRHIHICHC.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR OHIIIOHIRIRCCRRIOIICCHHIORRHOH(
      Supplier<com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH> var1
   ) {
      this.CHRIROOICCRRHHIHHIOOIIRHIHICHC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1
   ) {
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR IHICORCROOROHCIHIHCOIHRRHICICO(
      Supplier<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO> var1
   ) {
      AtomicReference var2 = new AtomicReference();
      AtomicReference var3 = new AtomicReference();
      this.OHIIIOHIRIRCCRRIOIICCHHIORRHOH(
         () -> {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var3x = (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO)var1.get();
            if (var3x != var2.get()) {
               var2.set(var3x);
               var3.set(com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var3x));
            }

            return (com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH)var3.get();
         }
      );
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(TextColor var1) {
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var1)
      );
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR HCHRIROHHHCORIOCROOCHRCIOROOCI(Supplier<TextColor> var1) {
      AtomicReference var2 = new AtomicReference();
      AtomicReference var3 = new AtomicReference();
      this.OHIIIOHIRIRCCRRIOIICCHHIORRHOH(() -> {
         TextColor var3x = (TextColor)var1.get();
         if (var3x != var2.get()) {
            var2.set(var3x);
            var3.set(com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var3x));
         }

         return (com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH)var3.get();
      });
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR IIIIRHIHROIRCROHHROIHIIHRCRRHO(boolean var1) {
      this.IOIHIIHCHROIIIOCORIHHROCCCIORR.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR ICICIOCHHHIHOCHCOHORIHRCOHHOCR(double var1) {
      this.OHCIHHICHHCCHHHRCRRHCOIRIHHICC.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public CORCOCICIRIOHROHROIIOOHICCHCRR CCIHHRIOOOOCOHRCIHOHROOICIORCC(Supplier<Double> var1) {
      this.OHCIHHICHHCCHHHRCRRHCOIRIHHICC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      float var1,
      float var2,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3
   ) {
      Component var4 = this.HHHOHHORHCOIRHCICRCIRIHOHRCHIH.get();
      if (var4 != null) {
         float var5 = this.OHCIHHICHHCCHHHRCRRHCOIRIHHICC.get().floatValue();
         com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH var6 = this.CHRIROOICCRRHHIHHIOOIIRHIHICHC.get();
         var3.IRROHRCCCHCIRHCOICHHROIHICCORO().push();
         var3.IRROHRCCCHCIRHCOICHHROIHICCORO().scale(var5, var5, 1.0F);
         var6.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3.IRROHRCCCHCIRHCOICHHROIHICCORO(), var4, var1 / var5, var2 / var5, this.IOIHIIHCHROIIIOCORIHHROCCCIORR.get());
         var3.IRROHRCCCHCIRHCOICHHROIHICCORO().pop();
      }
   }

   @Override
   public void clearCache() {
      this.HCRCCCICHHRRHROCHIOOHCHCRORCCO = null;
      this.HHHOHHORHCOIRHCICRCIRIHOHRCHIH.clearCache();
      this.CHRIROOICCRRHHIHHIOOIIRHIHICHC.clearCache();
      this.IOIHIIHCHROIIIOCORIHHROCCCIORR.clearCache();
      this.OHCIHHICHHCCHHHRCRRHCOIRIHHICC.clearCache();
   }

   @Override
   public float getWidth() {
      if (this.HHHOHHORHCOIRHCICRCIRIHOHRCHIH.get() == null) {
         return 0.0F;
      }

      if (this.HCRCCCICHHRRHROCHIOOHCHCRORCCO == null) {
         float var1 = this.OHCIHHICHHCCHHHRCRRHCOIRIHHICC.get().floatValue();
         this.HCRCCCICHHRRHROCHIOOHCHCRORCCO = IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR()
               .bridge$getStringWidth(this.HHHOHHORHCOIRHCICRCIRIHOHRCHIH.get())
            * var1;
      }

      return this.HCRCCCICHHRRHROCHIOOHCHCRORCCO;
   }

   @Override
   public float getHeight() {
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR().OHRCIORHOCHOORCRHHOHRRRCCOICCO()
         * this.OHCIHHICHHCCHHHRCRRHCOIRIHHICC.get().floatValue();
   }
}
