package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import java.util.function.Supplier;

public class HRCHROOHRIHCRCRHRIIROCIRHOIRHH
   extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<HRCHROOHRIHCRCRHRIIROCIRHOIRHH>
   implements com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<Float> RIIOIHHIHRHOHCORCRHHRHCHICCHOR = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      0.0F, false, true
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<Float> HRCOICIHHHICHCRHCICCROORCRICII = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      0.0F, false, true
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<Float> ICHCICHCCICHIHOOCRRIHICHCHCORC = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      0.0F, false, true
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<Float> CIOORCOIROROCRIROORRIRIHIRHHHO = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      0.0F, false, true
   );

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH() {
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(var1);
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH RICRIHOOHROHICCHHIIHRHCORHIOHR(float var1) {
      this.RIIOIHHIHRHOHCORCRHHRHCHICCHOR.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      this.HRCOICIHHHICHCRHCICCROORCRICII.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      this.ICHCICHCCICHIHOOCRRIHICHCHCORC.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      this.CIOORCOIROROCRIROORRIRIHIRHHHO.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(Supplier<Float> var1) {
      this.RIIOIHHIHRHOHCORCRHHRHCHICCHOR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      this.HRCOICIHHHICHCRHCICCROORCRICII.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      this.ICHCICHCCICHIHOOCRRIHICHCHCORC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      this.CIOORCOIROROCRIROORRIRIHIRHHHO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH RIIHIHHCRHCHRCICHOROHCHIIHCICH(float var1) {
      this.RIIOIHHIHRHOHCORCRHHRHCHICCHOR.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH IHCRORHRORIICHRHRCHRRIRRHHOCOO(Supplier<Float> var1) {
      this.RIIOIHHIHRHOHCORCRHHRHCHICCHOR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH IHIIIRHOOCHRCCCCIORIROCOIRRHCC(float var1) {
      this.HRCOICIHHHICHCRHCICCROORCRICII.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH ICICIOCHHHIHOCHCOHORIHRCOHHOCR(Supplier<Float> var1) {
      this.HRCOICIHHHICHCRHCICCROORCRICII.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH HHIRHRHHRHIHRHOHCHRHIORRHIIHOR(float var1) {
      this.ICHCICHCCICHIHOOCRRIHICHCHCORC.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(Supplier<Float> var1) {
      this.ICHCICHCCICHIHOOCRRIHICHCHCORC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH HRRHRCCOOIOIIIRORIOOORORHOORIH(float var1) {
      this.CIOORCOIROROCRIROORRIRIHIRHHHO.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(Supplier<Float> var1) {
      this.CIOORCOIROROCRIROORRIRIHIRHHHO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   public float IICCORIIRRORIRIOCOOICIRHRHCRCH() {
      return this.RIIOIHHIHRHOHCORCRHHRHCHICCHOR.get() + this.HRCOICIHHHICHCRHCICCROORCRICII.get();
   }

   @Override
   public float getWidth() {
      return this.RIIOIHHIHRHOHCORCRHHRHCHICCHOR.get() + super.getWidth() + this.HRCOICIHHHICHCRHCICCROORCRICII.get();
   }

   @Override
   public float getHeight() {
      return this.ICHCICHCCICHIHOOCRRIHICHCHCORC.get() + super.getHeight() + this.CIOORCOIROROCRIROORRIRIHIRHHHO.get();
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      float var1,
      float var2,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3
   ) {
      super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1 + this.RIIOIHHIHRHOHCORCRHHRHCHICCHOR.get(), var2 + this.ICHCICHCCICHIHOOCRRIHICHCHCORC.get(), var3);
   }

   @Override
   public void clearCache() {
      this.RIIOIHHIHRHOHCORCRHHRHCHICCHOR.clearCache();
      this.HRCOICIHHHICHCRHCICCROORCRICII.clearCache();
      this.ICHCICHCCICHIHOOCRRIHICHCHCORC.clearCache();
      this.CIOORCOIROROCRIROORRIRIHIRHHHO.clearCache();
      super.clearCache();
   }
}
