package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import java.util.function.Supplier;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH
   extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<IRCIIHHICIHRCOCRROCOICRIHHCCHH> {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH> RIIRRIORRHICOCCIHOHHCIRRHOORHR = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.OOHHOHICHIOCRRORCIHCRHRIOCHOOO(Integer.MIN_VALUE),
      true,
      true
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<Boolean> RRHOIHCOCIOIOIHORHORCORCIICCCH = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
      true, false, true
   );

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
   }

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(var1);
   }

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH HIHHOCRHHRORRHHRORRRIIHHORIHOC(int var1) {
      this.RIIRRIORRHICOCCIHOHHCIRRHOORHR
         .IRRCCOICORICIHCHRHIHIHROIRHOCR(
            com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.OOHHOHICHIOCRRORCIHCRHRIOCHOOO(var1)
         );
      return this;
   }

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH IIHRRHORCRCROCHHOHORCHCROCIHRO(Supplier<Integer> var1) {
      this.RIIRRIORRHICOCCIHOHHCIRRHOORHR
         .RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
            () -> com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.OOHHOHICHIOCRRORCIHCRHRIOCHOOO(
               (Integer)var1.get()
            )
         );
      return this;
   }

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      this.RIIRRIORRHICOCCIHOHHCIRRHOORHR.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH OCOHORHCROHICRRIHCIHHRRCIHICRI(
      Supplier<com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH> var1
   ) {
      this.RIIRRIORRHICOCCIHOHHCIRRHOORHR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH OOCHRIIIRIHRRCRIORHCROIIHCRRIC(boolean var1) {
      this.RRHOIHCOCIOIOIHORHORCORCIICCCH.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
      return this;
   }

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH CIOHHCORHRCCRICCCORIHCRHCCCRRR(Supplier<Boolean> var1) {
      this.RRHOIHCOCIOIOIHORHORCORCIICCCH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1);
      return this;
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      float var1,
      float var2,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3
   ) {
      com.moonsworth.lunar.client.util.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH var4 = this.RIIRRIORRHICOCCIHOHHCIRRHOORHR.get();
      if (this.RRHOIHCOCIOIOIHORHORCORCIICCCH.get() && var4 != null) {
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var3.IRROHRCCCHCIRHCOICHHROIHICCORO(), var1, var2, this.getWidth(), this.getHeight(), var4
         );
      }

      super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3);
   }

   @Override
   public void clearCache() {
      this.RIIRRIORRHICOCCIHOHHCIRRHOORHR.clearCache();
      this.RRHOIHCOCIOIOIHORHORCORCIICCCH.clearCache();
      super.clearCache();
   }
}
