package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.lib.adventure.text.TextComponent;
import com.moonsworth.lunar.lib.adventure.text.format.TextColor;
import com.moonsworth.lunar.lib.adventure.text.format.TextDecoration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.jetbrains.annotations.Nullable;

public class CIOHHCORHRCCRICCCORIHCRHCCCRRR extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private static final Pattern CIHCIHRHHHRORHHROHCIRRCOROOOOR = Pattern.compile("^ ❣ (?<revivedPlayer>\\w+) was revived by (?<reviver>\\w+)!$");
   private static final RCIROOOOICRHCCRRCIORHHIRCOIIIC OCRHORCIIHHRHCHICROHCRCICORCOO = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "lunar", "skyblock/hud/revive_stone.png"
   );
   private static final RCIROOOOICRHCCRRCIORHHIRCOIIIC RCHOCHHRCIHIRCOHICICROOIHIIIRI = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "steve.png");
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH ICICOCHCIROCOIRRCHRRRCCIIICOOH = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class
   );
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI IORIIOHRCORHCCICHRCRHRRIRCROCC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "reviveHeaderColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-1)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI ROCRRORCIIIIICRCRCRORRRHIORHCR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "playerNameColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-1)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI CIRHCHIIOIOCHCRORROCCOIHCOIHIO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "reviveCooldownColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-3726080)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI ORCIRIHCIHRHORRRCOHHRHHRHHICRR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "reviveReadyColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-16711936)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HashMap<String, Long> CHHRRRHRCOHIICOHRRHCHCIROHRCCO = new HashMap<>();
   private int HOHRRCCOCCIICICOROCCIOHCHCROOO;

   public CIOHHCORHRCCRICCCORIHCRHCCCRRR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            new CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DUNGEONS
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this,
            () -> com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
               == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.DUNGEON
         )
      );
      this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(this::onDisable);
      this.handle(RIROICHCRROROHCCROOCCCCOCHCCRI.class, this::RIOOCHICIHRHOHCCCCCHOCCCOHCRHI);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         this::OCOHORHCROHICRRIHCIHHRRCIHICRI
      );
      this.handle(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
   }

   private void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(RIROICHCRROROHCCROOCCCCOCHCCRI var1) {
      this.ICICOCHCIROCOIRRCHRRRCCIIICOOH
         .OCHICCHCROOOHRHCIIIIHORRCRCROO()
         .ifPresent(var1x -> this.HOHRRCCOCCIICICOROCCIOHCHCROOO = var1x.getPlayers().stream().mapToInt(this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH).sum());
   }

   private void OCOHORHCROHICRRIHCIHHRRCIHICRI(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = this.ICICOCHCIROCOIRRCHRRRCCIIICOOH
         .OCHICCHCROOOHRHCIIIIHORRCRCROO()
         .orElse(null);
      if (var2 != null) {
         Matcher var3 = CIHCIHRHHHRORHHROHCIRRCOROOOOR.matcher(var1.OIHOIRRICORHHRHOIOIHORCHOIRCOO());
         if (var3.matches()) {
            String var4 = var3.group("revivedPlayer");
            String var5 = var3.group("reviver");
            if (this.CHHRRRHRCOHIICOHRRHCHCIROHRCCO.getOrDefault(var5, 0L)
               <= IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime()) {
               var2.COHRICOCOHIIRICOHIOOHHCCRROCCI(var5)
                  .ifPresent(
                     var4x -> {
                        if (var4x.OOCHRRORICOORORHRHICCOOIHIHRCH()
                           == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HEALER
                           )
                         {
                           if (var4x.IIHCCOIOHIIRROOICHRIOCIICCHIIO() <= 0 || !var4.equals(var5)) {
                              long var5x = var2.getPlayers()
                                 .stream()
                                 .filter(
                                    var0 -> var0.OOCHRRORICOORORHRHICCOOIHIHRCH()
                                       == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HEALER
                                 )
                                 .count();
                              int var7 = 100 - var4x.RHRCIHHOOIIHORHRCCHOHOIOHIOHIR() - (var5x == 1L ? 10 : 0);
                              this.CHHRRRHRCOHIICOHRRHCHCIROHRCCO
                                 .put(var5, IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() + var7 * 1000L);
                           }
                        }
                     }
                  );
            }
         }
      }
   }

   private void onDisable() {
      this.CHHRRRHRCOHIICOHRRHCHCIROHRCCO.clear();
      this.HOHRRCCOCCIICICOROCCIOHCHCROOO = 0;
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.CHHRRRHRCOHIICOHRRHCHCIROHRCCO.clear();
      this.HOHRRCCOCCIICICOROCCIOHCHCROOO = 0;
   }

   private int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      int var2 = var1.IIHCCOIOHIIRROOICHRIOCIICCHIIO();
      if (var1.OOCHRRORICOORORHRHICCOOIHIHRCH()
            == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HEALER
         && this.CHHRRRHRCOHIICOHRRHCHCIROHRCCO.getOrDefault(var1.ORICICIICROCRICRHRHHRCHHRCRHOR(false), 0L)
            < IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime()) {
         var2++;
      }

      return var2;
   }

   @Override
   public String getId() {
      return "SKYBLOCK_REVIVE_HUD";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.COLOR,
         var1x -> var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(
            this.IORIIOHRCORHCCICHRCRHRRIRCROCC, this.ROCRRORCIIIIICRCRCRORRRHIORHCR, this.CIRHCHIIOIOCHCRORROCCOIHCOIHIO, this.ORCIRIHCIHRHORRRCOHHRHHRHHICRR
         )
      );
   }

   private class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO<List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR>> {
      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
         super(
            0.0F,
            0.0F,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.TOP_CENTER,
            false,
            true
         );
      }

      @Override
      public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH HRRIHHICORIHCHICOHCCRCHCHOHRCH() {
         return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            50, 100, 200, 100, 160, 300
         );
      }

      @Nullable
      public List<OOROOCCIRCCRHOIOIORIHCHHOOCCOR> IROCHOHCORHCOCCCOCHORCICRORIIC(boolean var1) {
         if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
            != com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.DUNGEON
            )
          {
            return null;
         }

         TextColor var2 = TextColor.color(CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.IORIIOHRCORHCCICHRCRHRRIRCROCC.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F));
         TextColor var3 = TextColor.color(CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.ORCIRIHCIHRHORRRCOHHRHHRHHICRR.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F));
         TextColor var4 = TextColor.color(CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.CIRHCHIIOIOCHCRORROCCOIHCOIHIO.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F));
         TextColor var5 = TextColor.color(CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.IORIIOHRCORHCCICHRCRHRRIRCROCC.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F));
         if (var1) {
            return List.of(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  CIOHHCORHRCCRICCCORIHCRHCCCRRR.OCRHORCIIHHRHCHICROHCRCICORCOO,
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC(CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("availableRevives"))
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH("3")
                     .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2)
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(TextDecoration.BOLD)
                     .HHCCIRHCCCIIRHCROHIORHIRHHIORH(var3)
                     .IRCIIHHICIHRCOCRROCOICRIHHCCHH(TextDecoration.BOLD)
                     .build()
               ),
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCHOCHHRCIHIRCOHICICROOIHIIIRI,
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC("Player_1")
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH("1")
                     .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5)
                     .HHCCIRHCCCIIRHCROHIORHIRHHIORH(var3)
                     .build()
               ),
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCHOCHHRCIHIRCOHICICROOIHIIIRI,
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC("Player_2")
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH("2")
                     .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5)
                     .HHCCIRHCCCIIRHCROHIORHIRHHIORH(var3)
                     .build()
               ),
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCHOCHHRCIHIRCOHICICROOIHIIIRI,
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC("Player_3")
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH("0")
                     .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5)
                     .HHCCIRHCCCIIRHCROHIORHIRHHIORH(var4)
                     .build()
               )
            );
         }

         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.ICICOCHCIROCOIRRCHRRRCCIIICOOH
            .OCHICCHCROOOHRHCIIIIHORRCRCROO()
            .orElse(null);
         if (var6 == null) {
            return null;
         }

         ArrayList var7 = new ArrayList();
         var7.add(
            new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
               CIOHHCORHRCCRICCCORIHCRHCCCRRR.OCRHORCIIHHRHCHICROHCRCICORCOO,
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                  .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC(CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("availableRevives"))
                  .HORORHCCHRRCHIOCOCIHIRIRRIHCCH(Integer.toString(CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.HOHRRCCOCCIICICOROCCIOHCHCROOO))
                  .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2)
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(TextDecoration.BOLD)
                  .HHCCIRHCCCIIRHCROHIORHIRHHIORH(CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.HOHRRCCOCCIICICOROCCIOHCHCROOO > 0 ? var3 : var4)
                  .IRCIIHHICIHRCOCRROCOICRIHHCCHH(TextDecoration.BOLD)
                  .build()
            )
         );
         var6.getPlayers()
            .forEach(
               var4x -> {
                  int var5x = CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4x);
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH var6x = var4x.RHOHOCRRHIRCIOCRCHRIHCCCHOCRIH()
                     .orElse(null);
                  RCIROOOOICRHCCRRCIORHHIRCOIIIC var7x = var6x != null ? var6x.bridge$getServerSkinTexture() : null;
                  TextComponent var8 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RHRROHRCOCCCHICROCHCOORHIOCRII()
                     .ICCRCOIRIROHCRHCCCCHCOIIRHHHOC(var4x.ORICICIICROCRICRHRHHRCHHRCRHOR(false))
                     .HORORHCCHRRCHIOCOCIHIRIRRIHCCH(Integer.toString(var5x))
                     .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                        TextColor.color(CIOHHCORHRCCRICCCORIHCRHCCCRRR.this.ROCRRORCIIIIICRCRCRORRRHIORHCR.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F))
                     )
                     .HHCCIRHCCCIIRHCROHIORHIRHHIORH(var5x > 0 ? var3 : var4)
                     .build();
                  if (var7x != null) {
                     var7.add(
                        new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                           var1xx -> {
                              var1xx.push();
                              var1xx.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(2.0F, 2.0F);
                              com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                                 var1xx, var7x, 0.0F, 0.0F, -1, true
                              );
                              var1xx.pop();
                           },
                           var8
                        )
                     );
                  } else {
                     var7.add(
                        new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                           CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCHOCHHRCIHIRCOHICICROOIHIIIRI, var8
                        )
                     );
                  }
               }
            );
         return var7;
      }

      @Override
      protected com.moonsworth.lunar.client.IHCRORHRORIICHRHRCHRRIRRHHOCOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IIHHOIIRORCHCIHROROHOORCCCRCOH() {
         return com.moonsworth.lunar.client.IHCRORHRORIICHRHRCHRRIRRHHOCOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.LEFT;
      }

      @Override
      protected boolean OOHOCHOCHHOCROOIRICCIHCCCRCCRC() {
         return true;
      }
   }
}
