package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.Map.Entry;

public abstract class CRRRICCRROCOHHOHIICIHORCOORRRH
   extends HCHRIROHHHCORIOCROOCHRCIOROOCI<Object>
   implements com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRICCOOHHHCHOORCICOCOHIHOIRHOO,
   com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IIRHCHHOICHRICOOCRORCCIOOIHOIR,
   com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.RRCRRCORICCHOHHIRCHIROOHIIOHCO {
   protected static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHCRORHRORIICHRHRCHRRIRRHHOCOO IROIHCHCRCROHOCRORIRIICROHIOOH = new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
      "#object-ref"
   );
   protected static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] OORCOORICOCHHRRHRRCCCROOHOHCHO = new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[0];
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI IICCRRIIHRIIHCHRCHHRRIIOHOOHHH;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] RIOCROROHHHHCIIRORRIIRROICICCO;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HICIHORCICIORRCOIOOHRRHCOHIIIO;
   protected final Object CRICHHICCCIIOHOOOCCOHHOCOCRIRC;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO HCIRIHRCCORCIHCOORIHHCHIOHOOCI;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR CRRCRCIIOHCRROOROCIOOHCICHRIHR;
   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH HORIHRCHOHIRRICCROHORHICHCIHIO;

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var4
   ) {
      super(var1);
      this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH = var1;
      this.RIOCROROHHHHCIIRORRIIRROICICCO = var3;
      this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH = var4;
      if (var2 == null) {
         this.HCIRIHRCCORCIHCOORIHHCHIOHOOCI = null;
         this.HICIHORCICIORRCOIOOHRRHCOHIIIO = null;
         this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC = null;
         this.CRRCRCIIOHCRROOROCIOOHCICHRIHR = null;
         this.HORIHRCHOHIRRICCROHORHICHCIHIO = null;
      } else {
         this.HCIRIHRCCORCIHCOORIHHCHIOHOOCI = var2.OHIRICIOHHHOHHICRCIICHCORCOHCC();
         this.HICIHORCICIORRCOIOOHRRHCOHIIIO = var2.RIOCICHCIOORHICCIIIICCRHOOCHRH();
         this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC = var2.RHIORHRHOOIROORIROOOIOROROOHCC();
         this.CRRCRCIIOHCRROOROCIOOHCICHRIHR = var2.CIRHOHHIOHCRORCCHROIOHOIHCCHOI();
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var5 = var2.OIHIROOIIRCOCOOCIIOHRIIHIHORHR()
            .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH)null
            );
         this.HORIHRCHOHIRRICCROHORHICHCIHIO = var5.HIHRRCOCICCHICROIHIOCRIRCCHHCI();
      }
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(
      CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var3
   ) {
      super(var1._handledType);
      this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH = var1.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH;
      this.RIOCROROHHHHCIIRORRIIRROICICCO = var2;
      this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH = var3;
      this.HCIRIHRCCORCIHCOORIHHCHIOHOOCI = var1.HCIRIHRCCORCIHCOORIHHCHIOHOOCI;
      this.HICIHORCICIORRCOIOOHRRHCOHIIIO = var1.HICIHORCICIORRCOIOOHRRHCOHIIIO;
      this.CRRCRCIIOHCRROOROCIOOHCICHRIHR = var1.CRRCRCIIOHCRROOROCIOOHCICHRIHR;
      this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC = var1.CRICHHICCCIIOHOOOCCOHHOCOCRIRC;
      this.HORIHRCHOHIRRICCROHORHICHCIHIO = var1.HORIHRCHOHIRRICCROHORHICHCIHIO;
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(
      CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var2
   ) {
      this(var1, var2, var1.CRICHHICCCIIOHOOOCCOHHOCOCRIRC);
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(
      CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var2,
      Object var3
   ) {
      super(var1._handledType);
      this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH = var1.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH;
      this.RIOCROROHHHHCIIRORRIIRROICICCO = var1.RIOCROROHHHHCIIRORRIIRROICICCO;
      this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH = var1.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH;
      this.HCIRIHRCCORCIHCOORIHHCHIOHOOCI = var1.HCIRIHRCCORCIHCOORIHHCHIOHOOCI;
      this.HICIHORCICIORRCOIOOHRRHCOHIIIO = var1.HICIHORCICIORRCOIOOHRRHCOHIIIO;
      this.CRRCRCIIOHCRROOROCIOOHCICHRIHR = var2;
      this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC = var3;
      this.HORIHRCHOHIRRICCROHORHICHCIHIO = var1.HORIHRCHOHIRRICCROHORHICHCIHIO;
   }

   @Deprecated
   protected CRRRICCRROCOHHOHIICIHORCOORRRH(CRRRICCRROCOHHOHIICIHORCOORRRH var1, String[] var2) {
      this(
         var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC(
            var2
         ),
         null
      );
   }

   @Deprecated
   protected CRRRICCRROCOHHOHIICIHORCOORRRH(CRRRICCRROCOHHOHIICIHORCOORRRH var1, Set<String> var2) {
      this(var1, var2, null);
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(CRRRICCRROCOHHOHIICIHORCOORRRH var1, Set<String> var2, Set<String> var3) {
      super(var1._handledType);
      this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH = var1.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH;
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var4 = var1.RIOCROROHHHHCIIRORRIIRROICICCO;
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var5 = var1.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH;
      int var6 = var4.length;
      ArrayList var7 = new ArrayList(var6);
      ArrayList var8 = var5 == null ? null : new ArrayList(var6);

      for (int var9 = 0; var9 < var6; var9++) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var10 = var4[var9];
         if (!com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var10.getName(), var2, var3
         )) {
            var7.add(var10);
            if (var5 != null) {
               var8.add(var5[var9]);
            }
         }
      }

      this.RIOCROROHHHHCIIRORRIIRROICICCO = var7.toArray(
         new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[var7.size()]
      );
      this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH = var8 == null
         ? null
         : var8.toArray(
            new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[var8.size()]
         );
      this.HCIRIHRCCORCIHCOORIHHCHIOHOOCI = var1.HCIRIHRCCORCIHCOORIHHCHIOHOOCI;
      this.HICIHORCICIORRCOIOOHRRHCOHIIIO = var1.HICIHORCICIORRCOIOOHRRHCOHIIIO;
      this.CRRCRCIIOHCRROOROCIOOHCICHRIHR = var1.CRRCRCIIOHCRROOROCIOOHCICHRIHR;
      this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC = var1.CRICHHICCCIIOHOOOCCOHHOCOCRIRC;
      this.HORIHRCHOHIRRICCROHORHICHCIHIO = var1.HORIHRCHOHIRRICCROHORHICHCIHIO;
   }

   public abstract CRRRICCRROCOHHOHIICIHORCOORRRH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var1
   );

   @Deprecated
   protected CRRRICCRROCOHHOHIICIHORCOORRRH CCIHHRIOOOOCOHRCIHOHROOICIORCC(Set<String> var1) {
      return this.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1, null);
   }

   protected abstract CRRRICCRROCOHHOHIICIHORCOORRRH HICHRCOHCCRHOHCICOOCHOIHCCHIRI(Set<String> var1, Set<String> var2);

   @Deprecated
   protected CRRRICCRROCOHHOHIICIHORCOORRRH OHCIIOCHHOHOHCOHHCRRHHCRHOIICC(String[] var1) {
      return this.CCIHHRIOOOOCOHRCIHOHROOICIORCC(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC(
            var1
         )
      );
   }

   protected abstract CRRRICCRROCOHHOHIICIHORCOORRRH RCOCRCOCHHRCIHCOIIIROIIOOHIOOC();

   public abstract CRRRICCRROCOHHOHIICIHORCOORRRH RICRHCHRRCCIICRCHICCIHHHCIICOH(Object var1);

   protected abstract CRRRICCRROCOHHOHIICIHORCOORRRH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var2
   );

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(CRRRICCRROCOHHOHIICIHORCOORRRH var1) {
      this(var1, var1.RIOCROROHHHHCIIRORRIIRROICICCO, var1.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH);
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH(
      CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RIROICHCRROROHCCROOCCCCOCHCCRI var2
   ) {
      this(
         var1,
         RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.RIOCROROHHHHCIIRORRIIRROICICCO, var2),
         RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH, var2)
      );
   }

   private static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var0,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RIROICHCRROROHCCROOCCCCOCHCCRI var1
   ) {
      if (var0 != null
         && var0.length != 0
         && var1 != null
         && var1
            != com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.RIROICHCRROROHCCROOCCCCOCHCCRI.RCHIOORHRIIHCCIIRRCRHRRIHHIOOI
         )
       {
         int var2 = var0.length;
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var3 = new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[var2];

         for (int var4 = 0; var4 < var2; var4++) {
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var5 = var0[var4];
            if (var5 != null) {
               var3[var4] = var5.rename(var1);
            }
         }

         return var3;
      } else {
         return var0;
      }
   }

   @Override
   public void CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1
   ) {
      int var2 = this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH == null ? 0 : this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH.length;
      int var3 = 0;

      for (int var4 = this.RIOCROROHHHHCIIRORRIIRROICICCO.length; var3 < var4; var3++) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var5 = this.RIOCROROHHHHCIIRORRIIRROICICCO[var3];
         if (!var5.willSuppressNulls() && !var5.hasNullSerializer()) {
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO var6 = var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var5
            );
            if (var6 != null) {
               var5.assignNullSerializer(var6);
               if (var3 < var2) {
                  com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var7 = this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH[var3];
                  if (var7 != null) {
                     var7.assignNullSerializer(var6);
                  }
               }
            }
         }

         if (!var5.hasSerializer()) {
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO var10 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1, var5
            );
            if (var10 == null) {
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var11 = var5.getSerializationType();
               if (var11 == null) {
                  var11 = var5.getType();
                  if (!var11.isFinal()) {
                     if (var11.HCHCCRRRHHICOIRRIOOOOHHHOIIORR() || var11.CRRHOOOHOICRIRHRIHRRRCHCIHHICC() > 0) {
                        var5.setNonTrivialBaseType(var11);
                     }
                     continue;
                  }
               }

               var10 = var1.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var11, var5);
               if (var11.HCHCCRRRHHICOIRRIOOOOHHHOIIORR()) {
                  com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var8 = var11.RCCRIHIHOIICHCIICCOHHHIRICOHHC()
                     .ORRHHOOICCCIIRICRIOCIOIOHOIICH();
                  if (var8 != null
                     && var10 instanceof com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CORCOCICIRIOHROHROIIOOHICCHCRR
                     )
                   {
                     com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CORCOCICIRIOHROHROIIOOHICCHCRR var9 = ((com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CORCOCICIRIOHROHROIIOOHICCHCRR)var10)
                        .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var8);
                     var10 = var9;
                  }
               }
            }

            if (var3 < var2) {
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var12 = this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH[var3];
               if (var12 != null) {
                  var12.assignSerializer(var10);
                  continue;
               }
            }

            var5.assignSerializer(var10);
         }
      }

      if (this.HICIHORCICIORRCOIOOHRRHCOHIIIO != null) {
         this.HICIHORCICIORRCOIOOHRRHCOHIIIO.CRRRICCRROCOHHOHIICIHORCOORRRH(var1);
      }
   }

   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var1.RCRORHCOCRIIOHICORIHOHRIIRIORH();
      if (var3 != null) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var4 = var2.getMember();
         if (var4 != null) {
            Object var5 = var3.RHOCHHIRRCHHHOHOIRROIROHHHIHIO(var4);
            if (var5 != null) {
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.CRICCOOHHHCHOORCICOCOHIHOIRHOO var6 = var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var2.getMember(), var5
               );
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var7 = var6.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
                  var1.CCOCHOROIOICHHICOCIHCHHOCOOIII()
               );
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO var8 = var7.CRCORIOIHCIIRRRORROCIORRRHHICR()
                  ? null
                  : var1.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var7, var2);
               return new IOHIHIIHCCCCCIHRORIOIOORCIOHII(var6, var7, var8);
            }
         }
      }

      return null;
   }

   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> createContextual(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var1.RCRORHCOCRIIOHICORIHOHRIIRIORH();
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO var4 = var2
               != null
            && var3 != null
         ? var2.getMember()
         : null;
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var5 = var1.RROOOCRCORCHCRRIRCRIIHHHHROOHO();
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var6 = this.findFormatOverrides(
         var1, var2, this._handledType
      );
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var7 = null;
      if (var6 != null && var6.IOIOHCRORRHHRCIIRCIOOHHCCOOOIC()) {
         var7 = var6.HIHRRCOCICCHICROIHIOCRIRCCHHCI();
         if (var7
               != com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ANY
            && var7 != this.HORIHRCHOHIRRICCROHORHICHCIHIO) {
            if (this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH.ORHRHCHCOHHORROCRRRCIHRIOORORC()) {
               switch (var7) {
                  case STRING:
                  case NUMBER:
                  case NUMBER_INT:
                     com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var8 = var5.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(
                        this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH
                     );
                     OCOHORHCROHICRRIHCIHHRRCIHICRI var9 = OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH.RRICIOOORRIORHHICIRCIOCHRHRCHH(), var1.RROOOCRCORCHCRRIRCRIIHHHHROOHO(), var8, var6
                     );
                     return var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var9, var2);
               }
            } else if (var7
                  == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.NATURAL
               && (!this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH.CHIHCRICHHCIOCRIIROHIIIHOOORIC() || !Map.class.isAssignableFrom(this._handledType))
               && Entry.class.isAssignableFrom(this._handledType)) {
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var24 = this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH
                  .IHROCRRIRIROCCCRCRRROCRRCRIIHH(Entry.class);
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var26 = var24.CCOCIRRRCCCHIHOOROIOCCIHHHHCCO(
                  0
               );
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var27 = var24.CCOCIRRRCCCHIHOOROIOCCIHHHHCCO(
                  1
               );
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var28 = new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH, var26, var27, false, null, var2
               );
               return var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var28, var2);
            }
         }
      }

      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var22 = this.CRRCRCIIOHCRROOROCIOOHCICHRIHR;
      int var25 = 0;
      Set var10 = null;
      Set var11 = null;
      Object var12 = null;
      if (var4 != null) {
         var10 = var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5, var4).CCIOOIHRHCHRHHHCRCHOHHRRCRROCC();
         var11 = var3.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var5, var4).CCCHHORHRRIOORHCHRRRIIOOCORHHC();
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH var13 = var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var4
         );
         if (var13 == null) {
            if (var22 != null) {
               var13 = var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, null);
               if (var13 != null) {
                  var22 = this.CRRCRCIIOHCRROOROCIOOHCICHRIHR.IOHOHIHHHOOHOOHRRIOCRIRRORICIO(var13.HIORICCIIOHIROROCHIOCIHCHHIHOR());
               }
            }
         } else {
            var13 = var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var13);
            Class var14 = var13.IOHICRICCOOOIROCHCHHCICHIRHRCR();
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var15 = var1.OCOHORHCROHICRRIHCIHHRRCIHICRI(
               var14
            );
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var16 = var1.CCOCHOROIOICHHICOCIHCHHOCOOIII()
               .RRCRRCORICCHOHHIRCHIROOHIIOHCO(
                  var15, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHRIOOOOCOHRCIHOHROOICIORCC.class
               )[0];
            if (var14
               == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRHROHHHCIHHCOHCOORCRIHHIICROR.CRRRICCRROCOHHOHIICIHORCOORRRH.class
               )
             {
               String var39 = var13.RHHRIIIRRHCHHIOIHHHHOCHHORCORH().getSimpleName();
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var18 = null;
               int var19 = 0;
               int var20 = this.RIOCROROHHHHCIIRORRIIRROICICCO.length;

               while (true) {
                  if (var19 == var20) {
                     var1.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                        this.IICCRRIIHRIIHCHRCHHRRIIOHOOHHH,
                        String.format(
                           "Invalid Object Id definition for %s: cannot find property with name %s",
                           com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.ROIHROCROORRCCOIRRIHHORCROOORO(
                              this.handledType()
                           ),
                           com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.ROCICROOOORCIRIIRRCICIHRHIORHH(
                              var39
                           )
                        )
                     );
                  }

                  com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var21 = this.RIOCROROHHHHCIIRORRIIRROICICCO[var19];
                  if (var39.equals(var21.getName())) {
                     var18 = var21;
                     var25 = var19;
                     var16 = var18.getType();
                     com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var41 = new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO(
                        var13, var18
                     );
                     var22 = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        var16,
                        (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHCRORHRORIICHRHRCHRRIRRHHOCOO)null,
                        var41,
                        var13.HIORICCIIOHIROROCHIOCIHCHHIHOR()
                     );
                     break;
                  }

                  var19++;
               }
            } else {
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHRIOOOOCOHRCIHOHROOICIORCC var17 = var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  var4, var13
               );
               var22 = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var16, var13.RHHRIIIRRHCHHIOIHHHHOCHHORCORH(), var17, var13.HIORICCIIOHIROROCHIOCIHCHHIHOR()
               );
            }
         }

         Object var32 = var3.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var4
         );
         if (var32 != null && (this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC == null || !var32.equals(this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC))) {
            var12 = var32;
         }
      }

      CRRRICCRROCOHHOHIICIHORCOORRRH var31 = this;
      if (var25 > 0) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var33 = Arrays.copyOf(
            this.RIOCROROHHHHCIIRORRIIRROICICCO, this.RIOCROROHHHHCIIRORRIIRROICICCO.length
         );
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var35 = var33[var25];
         System.arraycopy(var33, 0, var33, 1, var25);
         var33[0] = var35;
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var38;
         if (this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH == null) {
            var38 = null;
         } else {
            var38 = Arrays.copyOf(this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH, this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH.length);
            var35 = var38[var25];
            System.arraycopy(var38, 0, var38, 1, var25);
            var38[0] = var35;
         }

         var31 = var31.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var33, var38);
      }

      if (var22 != null) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO var34 = var1.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            var22.IIIHCCIHCRIORIHOOHICIRCROOHORR, var2
         );
         var22 = var22.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(var34);
         if (var22 != this.CRRCRCIIOHCRROOROCIOOHCICHRIHR) {
            var31 = var31.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var22);
         }
      }

      if (var10 != null && !var10.isEmpty() || var11 != null) {
         var31 = var31.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var10, var11);
      }

      if (var12 != null) {
         var31 = var31.RICRHCHRRCCIICRCHICCIHHHCIICOH(var12);
      }

      if (var7 == null) {
         var7 = this.HORIHRCHOHIRRICCROHORHICHCIHIO;
      }

      return var7
            == com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ARRAY
         ? var31.RCOCRCOCHHRCIHCOIIIROIIOOHIOOC()
         : var31;
   }

   @Override
   public Iterator<com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR> properties() {
      return Arrays.asList(this.RIOCROROHHHHCIIRORRIIRROICICCO).iterator();
   }

   @Override
   public boolean usesObjectId() {
      return this.CRRCRCIIOHCRROOROCIOOHCICHRIHR != null;
   }

   @Override
   public abstract void serialize(
      Object var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
   );

   @Override
   public void serializeWithType(
      Object var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var4
   ) {
      if (this.CRRCRCIIOHCRROOROCIOOHCICHRIHR != null) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var4);
      } else {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var5 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var4, var1, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.START_OBJECT
         );
         var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var5);
         var2.IHHCHIIHOOHRROCRRRHHHCOOHCOORC(var1);
         if (this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC != null) {
            this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1, var2, var3);
         } else {
            this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, var2, var3);
         }

         var4.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var5);
      }
   }

   protected final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Object var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3,
      boolean var4
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var5 = this.CRRCRCIIOHCRROOROCIOOHCICHRIHR;
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIROICHCRROROHCCROOCCCCOCHCCRI var6 = var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1, var5.OHHRCIRRHCCIRRIRCIRHHRHCCORIOO
      );
      if (!var6.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var5)) {
         Object var7 = var6.COOROCRCCHCIHRCCIROCICCIIIRHHC(var1);
         if (var5.CCIROCORHOIHCHCIRRHCCRCHHRRIIO) {
            var5.HHOCCIOIRHCCHRIROICIROIIRIIRRR.serialize(var7, var2, var3);
         } else {
            if (var4) {
               var2.IRRIHROCORIOOCHHCHCHOHCIOHHRRI(var1);
            }

            var6.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var3, var5);
            if (this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC != null) {
               this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1, var2, var3);
            } else {
               this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, var2, var3);
            }

            if (var4) {
               var2.RORCROIROCHHOOICHRICCCRHROHROC();
            }
         }
      }
   }

   protected final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Object var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var4
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var5 = this.CRRCRCIIOHCRROOROCIOOHCICHRIHR;
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIROICHCRROROHCCROOCCCCOCHCCRI var6 = var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1, var5.OHHRCIRRHCCIRRIRCIRHHRHCCORIOO
      );
      if (!var6.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var5)) {
         Object var7 = var6.COOROCRCCHCIHRCCIROCICCIIIRHHC(var1);
         if (var5.CCIROCORHOIHCHCIRRHCCRCHHRRIIO) {
            var5.HHOCCIOIRHCCHRIROICIROIIRIIRRR.serialize(var7, var2, var3);
         } else {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var4, var6);
         }
      }
   }

   protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Object var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var4,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIROICHCRROROHCCROOCCCCOCHCCRI var5
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR var6 = this.CRRCRCIIOHCRROOROCIOOHCICHRIHR;
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var7 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var4, var1, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.START_OBJECT
      );
      var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var7);
      var2.IHHCHIIHOOHRROCRRRHHHCOOHCOORC(var1);
      var5.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var3, var6);
      if (this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC != null) {
         this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var1, var2, var3);
      } else {
         this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, var2, var3);
      }

      var4.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var7);
   }

   protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var1,
      Object var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI var3
   ) {
      if (this.HCIRIHRCCORCIHCOORIHHCHIOHOOCI == null) {
         return var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3);
      }

      Object var4 = this.HCIRIHRCCORCIHCOORIHHCHIOHOOCI.getValue(var2);
      if (var4 == null) {
         var4 = "";
      }

      return var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var4);
   }

   @Deprecated
   protected final String RRIOHRHHRHORRROIIRHRHROICRHCRO(Object var1) {
      Object var2 = this.HCIRIHRCCORCIHCOORIHHCHIOHOOCI.getValue(var1);
      if (var2 == null) {
         return "";
      } else {
         return var2 instanceof String ? (String)var2 : var2.toString();
      }
   }

   protected void RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      Object var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var4;
      if (this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH != null && var3.CRCCCCCCRCOHCHRCOOROIHCHCCCIOC() != null) {
         var4 = this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH;
      } else {
         var4 = this.RIOCROROHHHHCIIRORRIIRROICICCO;
      }

      int var5 = 0;

      try {
         for (int var6 = var4.length; var5 < var6; var5++) {
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var12 = var4[var5];
            if (var12 != null) {
               var12.serializeAsField(var1, var2, var3);
            }
         }

         if (this.HICIHORCICIORRCOIOOHRRHCOHIIIO != null) {
            this.HICIHORCICIORRCOIOOHRRHCOHIIIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3);
         }
      } catch (Exception var9) {
         String var11 = var5 == var4.length ? "[anySetter]" : var4[var5].getName();
         this.wrapAndThrow(var3, var9, var1, var11);
      } catch (StackOverflowError var10) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR var7 = new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
            var2, "Infinite recursion (StackOverflowError)", var10
         );
         String var8 = var5 == var4.length ? "[anySetter]" : var4[var5].getName();
         var7.CRICCOOHHHCHOORCICOCOHIHOIRHOO(var1, var8);
         throw var7;
      }
   }

   protected void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      Object var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var4;
      if (this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH != null && var3.CRCCCCCCRCOHCHRCOOROIHCHCCCIOC() != null) {
         var4 = this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH;
      } else {
         var4 = this.RIOCROROHHHHCIIRORRIIRROICICCO;
      }

      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CIOHHCORHRCCRICCCORIHCRHCCCRRR var5 = this.findPropertyFilter(
         var3, this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC, var1
      );
      if (var5 == null) {
         this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, var2, var3);
      } else {
         int var6 = 0;

         try {
            for (int var7 = var4.length; var6 < var7; var6++) {
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var13 = var4[var6];
               if (var13 != null) {
                  var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var13);
               }
            }

            if (this.HICIHORCICIORRCOIOOHRRHCOHIIIO != null) {
               this.HICIHORCICIORRCOIOOHRRHCOHIIIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var5);
            }
         } catch (Exception var10) {
            String var12 = var6 == var4.length ? "[anySetter]" : var4[var6].getName();
            this.wrapAndThrow(var3, var10, var1, var12);
         } catch (StackOverflowError var11) {
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR var8 = new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
               var2, "Infinite recursion (StackOverflowError)", var11
            );
            String var9 = var6 == var4.length ? "[anySetter]" : var4[var6].getName();
            var8.CRICCOOHHHCHOORCICOCOHIHOIRHOO(var1, var9);
            throw var8;
         }
      }
   }

   @Deprecated
   @Override
   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR getSchema(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, Type var2
   ) {
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.HICRRICCHCCROOHHCHOCOCCHOIHHOC var3 = this.createSchemaNode(
         "object", true
      );
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = this._handledType
         .getAnnotation(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class
         );
      if (var4 != null) {
         String var5 = var4.id();
         if (var5 != null && !var5.isEmpty()) {
            var3.HIHCHCORCCRCOHCRROHOHOOCHOROCC("id", var5);
         }
      }

      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.HICRRICCHCCROOHHCHOCOCCHOIHHOC var9 = var3.HCHHCOCCORCCROIRHORIIOOORRCCHH();
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CIOHHCORHRCCRICCCORIHCRHCCCRRR var6;
      if (this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC != null) {
         var6 = this.findPropertyFilter(var1, this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC, null);
      } else {
         var6 = null;
      }

      for (int var7 = 0; var7 < this.RIOCROROHHHHCIIRORRIIRROICICCO.length; var7++) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var8 = this.RIOCROROHHHHCIIRORRIIRROICICCO[var7];
         if (var6 == null) {
            var8.depositSchemaProperty(var9, var1);
         } else {
            var6.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var8, var9, var1);
         }
      }

      var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("properties", var9);
      return var3;
   }

   @Override
   public void acceptJsonFormatVisitor(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
   ) {
      if (var1 != null) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO var3 = var1.CCIHHRIOOOOCOHRCIHOHROOICIORCC(
            var2
         );
         if (var3 != null) {
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var4 = var1.COCCOCCOIHOCRICOHOIHHORHROHRHO();
            if (this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC != null) {
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CIOHHCORHRCCRICCCORIHCRHCCCRRR var5 = this.findPropertyFilter(
                  var1.COCCOCCOIHOCRICOHOIHHORHROHRHO(), this.CRICHHICCCIIOHOOOCCOHHOCOCRIRC, null
               );
               int var6 = 0;

               for (int var7 = this.RIOCROROHHHHCIIRORRIIRROICICCO.length; var6 < var7; var6++) {
                  var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.RIOCROROHHHHCIIRORRIIRROICICCO[var6], var3, var4);
               }
            } else {
               Class var10 = this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH != null && var4 != null ? var4.CRCCCCCCRCOHCHRCOOROIHCHCCCIOC() : null;
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH[] var11;
               if (var10 != null) {
                  var11 = this.HHHOIHOCIIRCCIRHIIOIRRRRIHRIIH;
               } else {
                  var11 = this.RIOCROROHHHHCIIRORRIIRROICICCO;
               }

               int var12 = 0;

               for (int var8 = var11.length; var12 < var8; var12++) {
                  com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CRRRICCRROCOHHOHIICIHORCOORRRH var9 = var11[var12];
                  if (var9 != null) {
                     var9.depositSchemaProperty(var3, var4);
                  }
               }
            }
         }
      }
   }
}
