package com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.util.OOOOCCOOOHCHCIIHOIHCRIIOOROHRC;
import java.util.Collections;
import java.util.Set;
import java.util.WeakHashMap;

public class CRRRICCRROCOHHOHIICIHORCOORRRH implements com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH {
   public static final Set<OOOOCCOOOHCHCIIHOIHCRIIOOROHRC> RCICIRRHHICHCCHRRCOROICHHHRRIO = Collections.newSetFromMap(new WeakHashMap<>());

   public CRRRICCRROCOHHOHIICIHORCOORRRH() {
      this.handle(CORCOCICIRIOHROHROIIOOHICCHCRR.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(CORCOCICIRIOHROHROIIOOHICCHCRR var1) {
      RCICIRRHHICHCCHRRCOROICHHHRRIO.forEach(OOOOCCOOOHCHCIIHOIHCRIIOOROHRC::ORCOOCHRICHOIHHIHIOHCHCRIOHRCR);
   }
}
