package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import java.util.Comparator;
import java.util.Iterator;
import java.util.NavigableSet;
import java.util.Set;
import org.checkerframework.checker.nullness.qual.Nullable;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
   emulated = true
)
abstract class RHOORRIIOCHIRRHOHOOHIROHCRICRO<E> extends CCRHOICIRORRHOOOCIHHHHCHCICHOH<E> implements IHRCROHROHOCCHIHOHRROHOCOIRHIO<E> {
   private transient @Nullable Comparator<? super E> comparator;
   private transient @Nullable NavigableSet<E> elementSet;
   private transient @Nullable Set<CRIIOOIHIOHHRRRHIOROOCHCHHCCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E>> entrySet;

   abstract IHRCROHROHOCCHIHOHRROHOCOIRHIO<E> IORHHICCHHHHOHOOHRHCHHCCHCIOIO();

   @Override
   public Comparator<? super E> comparator() {
      Comparator var1 = this.comparator;
      return var1 == null
         ? (
            this.comparator = IOIHHIORCICCHIIHOIOIOHHRICRHIO.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO().comparator())
               .HCHORRRCIORCRHCRIIHROIRRRHCCOR()
         )
         : var1;
   }

   @Override
   public NavigableSet<E> elementSet() {
      NavigableSet var1 = this.elementSet;
      return var1 == null ? (this.elementSet = new COOOIIOHIRCRCHIHRHHICOOHIOORRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH<>(this)) : var1;
   }

   @Override
   public CRIIOOIHIOHHRRRHIOROOCHCHHCCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E> RIICRHCRCOHCOCOROORRRHIOCOHRHI() {
      return this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO().CIOHICCRCCIOHIHIIOIHOIOHIHOIII();
   }

   @Override
   public CRIIOOIHIOHHRRRHIOROOCHCHHCCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E> CIOHICCRCCIOHIHIIOIHOIOHIHOIII() {
      return this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO().RIICRHCRCOHCOCOROORRRHIOCOHRHI();
   }

   @Override
   public IHRCROHROHOCCHIHOHRROHOCOIRHIO<E> CRRRICCRROCOHHOHIICIHORCOORRRH(E var1, IOIICIRIICICIIOORHCIIIIRRIHRHI var2) {
      return this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO().HHCCIRHCCCIIRHCROHIORHIRHHIORH((E)var1, var2).HRHCOORCOHHCHCOCOIROOHHICIOCCH();
   }

   @Override
   public IHRCROHROHOCCHIHOHRROHOCOIRHIO<E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      E var1, IOIICIRIICICIIOORHCIIIIRRIHRHI var2, E var3, IOIICIRIICICIIOORHCIIIIRRIHRHI var4
   ) {
      return this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((E)var3, var4, (E)var1, var2).HRHCOORCOHHCHCOCOIROOHHICIOCCH();
   }

   @Override
   public IHRCROHROHOCCHIHOHRROHOCOIRHIO<E> HHCCIRHCCCIIRHCROHIORHIRHHIORH(E var1, IOIICIRIICICIIOORHCIIIIRRIHRHI var2) {
      return this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO().CRRRICCRROCOHHOHIICIHORCOORRRH((E)var1, var2).HRHCOORCOHHCHCOCOIROOHHICIOCCH();
   }

   @Override
   protected CRIIOOIHIOHHRRRHIOROOCHCHHCCCI<E> CIHHORHICHHIRCRRIIROCIOCICIRCI() {
      return this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO();
   }

   @Override
   public IHRCROHROHOCCHIHOHRROHOCOIRHIO<E> HRHCOORCOHHCHCOCOIROOHHICIOCCH() {
      return this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO();
   }

   @Override
   public CRIIOOIHIOHHRRRHIOROOCHCHHCCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E> CIIOCCIOHROHHCOHRROIHCCORICHIC() {
      return this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO().OHIIICCRRHCCHRRRHRIIHCOHIIRIOO();
   }

   @Override
   public CRIIOOIHIOHHRRRHIOROOCHCHHCCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E> OHIIICCRRHCCHRRRHRIIHCOHIIRIOO() {
      return this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO().CIIOCCIOHROHHCOHRROIHCCORICHIC();
   }

   abstract Iterator<CRIIOOIHIOHHRRRHIOROOCHCHHCCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E>> entryIterator();

   @Override
   public Set<CRIIOOIHIOHHRRRHIOROOCHCHHCCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E>> entrySet() {
      Set var1 = this.entrySet;
      return var1 == null ? (this.entrySet = this.createEntrySet()) : var1;
   }

   Set<CRIIOOIHIOHHRRRHIOROOCHCHHCCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E>> createEntrySet() {
      class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends CCRIHCIIOOIOHIRCCHIICCRHIROORC.CRRRICCRROCOHHOHIICIHORCOORRRH<E> {
         @Override
         CRIIOOIHIOHHRRRHIOROOCHCHHCCCI<E> OOIORIRHCHIIOOIRCRIRHRHIOIRROO() {
            return RHOORRIIOCHIRRHOHOOHIROHCRICRO.this;
         }

         @Override
         public Iterator<CRIIOOIHIOHHRRRHIOROOCHCHHCCCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E>> iterator() {
            return RHOORRIIOCHIRRHOHOOHIROHCRICRO.this.entryIterator();
         }

         @Override
         public int size() {
            return RHOORRIIOCHIRRHOHOOHIROHCRICRO.this.IORHHICCHHHHOHOOHRHCHHCCHCIOIO().entrySet().size();
         }
      }

      return new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();
   }

   @Override
   public Iterator<E> iterator() {
      return CCRIHCIIOOIOHIRCCHIICCRHIROORC.HHCCIRHCCCIIRHCROHIORHIRHHIORH(this);
   }

   @Override
   public Object[] toArray() {
      return this.standardToArray();
   }

   @Override
   public <T> T[] toArray(T[] var1) {
      return (T[])this.standardToArray(var1);
   }

   @Override
   public String toString() {
      return this.entrySet().toString();
   }
}
