package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import java.io.Serializable;
import java.util.Collection;
import java.util.Comparator;
import java.util.Iterator;
import java.util.NavigableMap;
import java.util.NoSuchElementException;
import java.util.Set;
import java.util.TreeMap;
import java.util.Map.Entry;
import org.checkerframework.checker.nullness.qual.Nullable;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
public class OICIRICHOHHIIHIRRRROORCRRRCORH<C extends Comparable<?>> extends HICHRCOHCCRHOHCICOOCHOIHCCHIRI<C> implements Serializable {
   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH
   final NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> OIHRCCICICOIRIOOCCHCCRROCRIIOH;
   private transient @Nullable Set<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> asRanges;
   private transient @Nullable Set<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> asDescendingSetOfRanges;
   private transient @Nullable IIOORRCRHCRIORIOCOHHIROOIIHROC<C> IHRIRRIOIIHOIROOOHRRICIIIOIHHH;

   public static <C extends Comparable<?>> OICIRICHOHHIIHIRRRROORCRRRCORH<C> RHIOICICIHIOIICCRCCOCCCRIHOCII() {
      return new OICIRICHOHHIIHIRRRROORCRRRCORH<>(new TreeMap<>());
   }

   public static <C extends Comparable<?>> OICIRICHOHHIIHIRRRROORCRRRCORH<C> CORCOCICIRIOHROHROIIOOHICCHCRR(IIOORRCRHCRIORIOCOHHIROOIIHROC<C> var0) {
      OICIRICHOHHIIHIRRRROORCRRRCORH var1 = RHIOICICIHIOIICCRCCOCCCRIHOCII();
      var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0);
      return var1;
   }

   public static <C extends Comparable<?>> OICIRICHOHHIIHIRRRROORCRRRCORH<C> IOIOHIORIROHRRCOOOHCROHORCOIIH(Iterable<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var0) {
      OICIRICHOHHIIHIRRRROORCRRRCORH var1 = RHIOICICIHIOIICCRCCOCCCRIHOCII();
      var1.addAll(var0);
      return var1;
   }

   private OICIRICHOHHIIHIRRRROORCRRRCORH(NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var1) {
      this.OIHRCCICICOIRIOOCCHCCRROCRIIOH = var1;
   }

   @Override
   public Set<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> asRanges() {
      Set var1 = this.asRanges;
      return var1 == null
         ? (this.asRanges = new OICIRICHOHHIIHIRRRROORCRRRCORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.values()))
         : var1;
   }

   @Override
   public Set<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> asDescendingSetOfRanges() {
      Set var1 = this.asDescendingSetOfRanges;
      return var1 == null
         ? (
            this.asDescendingSetOfRanges = new OICIRICHOHHIIHIRRRROORCRRRCORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.descendingMap().values()
            )
         )
         : var1;
   }

   @Override
   public @Nullable IIHROHOIOHICCRRHRICHCIHRCROOIO<C> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(C var1) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      Entry var2 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.floorEntry(RCCCROCHCICCROHCOCCRRROCIIHCCH.CRRRICCRROCOHHOHIICIHORCOORRRH((C)var1));
      return var2 != null && ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue()).contains(var1) ? (IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue() : null;
   }

   @Override
   public boolean HHCCIRHCCCIIRHCROHIORHIRHHIORH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      Entry var2 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.ceilingEntry(var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH);
      if (var2 != null
         && ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue()).CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1)
         && !((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue()).IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1).isEmpty()) {
         return true;
      }

      Entry var3 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.lowerEntry(var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH);
      return var3 != null
         && ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var3.getValue()).CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1)
         && !((IIHROHOIOHICCRRHRICHCIHRCROOIO)var3.getValue()).IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1).isEmpty();
   }

   @Override
   public boolean CRRRICCRROCOHHOHIICIHORCOORRRH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      Entry var2 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.floorEntry(var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH);
      return var2 != null && ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue()).CRRRICCRROCOHHOHIICIHORCOORRRH(var1);
   }

   private @Nullable IIHROHOIOHICCRRHRICHCIHRCROOIO<C> RICRIRRCOHRCOCRRHHCRHRROOIOHHR(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      Entry var2 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.floorEntry(var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH);
      return var2 != null && ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue()).CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
         ? (IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue()
         : null;
   }

   @Override
   public IIHROHOIOHICCRRHRICHCIHRCROOIO<C> HIOHORRRRRIIICOCRHCHHCCCICHCRC() {
      Entry var1 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.firstEntry();
      Entry var2 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.lastEntry();
      if (var1 == null) {
         throw new NoSuchElementException();
      } else {
         return IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var1.getValue()).RIIHICHIOIORCIIRCOCCRHOOOHCOIH,
            ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue()).RHRIOOIRIIIHHHROHOHRIIHORCORRO
         );
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      if (!var1.isEmpty()) {
         RCCCROCHCICCROHCOCCRRROCIIHCCH var2 = var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH;
         RCCCROCHCICCROHCOCCRRROCIIHCCH var3 = var1.RHRIOOIRIIIHHHROHOHRIIHORCORRO;
         Entry var4 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.lowerEntry(var2);
         if (var4 != null) {
            IIHROHOIOHICCRRHRICHCIHRCROOIO var5 = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var4.getValue();
            if (var5.RHRIOOIRIIIHHHROHOHRIIHORCORRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2) >= 0) {
               if (var5.RHRIOOIRIIIHHHROHOHRIIHORCORRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3) >= 0) {
                  var3 = var5.RHRIOOIRIIIHHHROHOHRIIHORCORRO;
               }

               var2 = var5.RIIHICHIOIORCIIRCOCCRHOOOHCOIH;
            }
         }

         Entry var7 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.floorEntry(var3);
         if (var7 != null) {
            IIHROHOIOHICCRRHRICHCIHRCROOIO var6 = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var7.getValue();
            if (var6.RHRIOOIRIIIHHHROHOHRIIHORCORRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3) >= 0) {
               var3 = var6.RHRIOOIRIIIHHHROHOHRIIHORCORRO;
            }
         }

         this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.subMap(var2, var3).clear();
         this.HICRRICCHCCROOHHCHOCOCCHOIHHOC(IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3));
      }
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      if (!var1.isEmpty()) {
         Entry var2 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.lowerEntry(var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH);
         if (var2 != null) {
            IIHROHOIOHICCRRHRICHCIHRCROOIO var3 = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue();
            if (var3.RHRIOOIRIIIHHHROHOHRIIHORCORRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH) >= 0) {
               if (var1.hasUpperBound() && var3.RHRIOOIRIIIHHHROHOHRIIHORCORRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.RHRIOOIRIIIHHHROHOHRIIHORCORRO) >= 0) {
                  this.HICRRICCHCCROOHHCHOCOCCHOIHHOC(
                     IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.RHRIOOIRIIIHHHROHOHRIIHORCORRO, var3.RHRIOOIRIIIHHHROHOHRIIHORCORRO)
                  );
               }

               this.HICRRICCHCCROOHHCHOCOCCHOIHHOC(
                  IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3.RIIHICHIOIORCIIRCOCCRHOOOHCOIH, var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH)
               );
            }
         }

         Entry var5 = this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.floorEntry(var1.RHRIOOIRIIIHHHROHOHRIIHORCORRO);
         if (var5 != null) {
            IIHROHOIOHICCRRHRICHCIHRCROOIO var4 = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var5.getValue();
            if (var1.hasUpperBound() && var4.RHRIOOIRIIIHHHROHOHRIIHORCORRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.RHRIOOIRIIIHHHROHOHRIIHORCORRO) >= 0) {
               this.HICRRICCHCCROOHHCHOCOCCHOIHHOC(
                  IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.RHRIOOIRIIIHHHROHOHRIIHORCORRO, var4.RHRIOOIRIIIHHHROHOHRIIHORCORRO)
               );
            }
         }

         this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.subMap(var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH, var1.RHRIOOIRIIIHHHROHOHRIIHORCORRO).clear();
      }
   }

   private void HICRRICCHCCROOHHCHOCOCCHOIHHOC(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
      if (var1.isEmpty()) {
         this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.remove(var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH);
      } else {
         this.OIHRCCICICOIRIOOCCHCCRROCRIIOH.put(var1.RIIHICHIOIORCIIRCOCCRHOOOHCOIH, var1);
      }
   }

   @Override
   public IIOORRCRHCRIORIOCOHHIROOIIHROC<C> COHORCHIHROROOHICOCOOOHRIHOHHI() {
      IIOORRCRHCRIORIOCOHHIROOIIHROC var1 = this.IHRIRRIOIIHOIROOOHRRICIIIOIHHH;
      return var1 == null ? (this.IHRIRRIOIIHOIROOOHRRICIIIOIHHH = new OICIRICHOHHIIHIRRRROORCRRRCORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH()) : var1;
   }

   @Override
   public IIOORRCRHCRIORIOCOHHIROOIIHROC<C> HICHRCOHCCRHOHCICOOCHOIHCCHIRI(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
      return var1.equals(IIHROHOIOHICCRRHRICHCIHRCROOIO.OCORIOCROHHRRRICCHCOROROIRICCR())
         ? this
         : new OICIRICHOHHIIHIRRRROORCRRRCORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1);
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH
   static final class CRRRICCRROCOHHOHIICIHORCOORRRH<C extends Comparable<?>>
      extends CRICCOOHHHCHOORCICOCOHIHOIRHOO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> {
      private final NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> HHOOHROORHCIOHOIHHCICICIRCOHHR;
      private final IIHROHOIOHICCRRHRICHCIHRCROOIO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> CRIIIHCRRHRROROCHRROORIHOCRCIR;

      CRRRICCRROCOHHOHIICIHORCOORRRH(NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var1) {
         this.HHOOHROORHCIOHOIHHCICICIRCOHHR = var1;
         this.CRIIIHCRRHRROROCHRROORIHOCRCIR = IIHROHOIOHICCRRHRICHCIHRCROOIO.OCORIOCROHHRRRICCHCOROROIRICCR();
      }

      private CRRRICCRROCOHHOHIICIHORCOORRRH(
         NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var1,
         IIHROHOIOHICCRRHRICHCIHRCROOIO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> var2
      ) {
         this.HHOOHROORHCIOHOIHHCICICIRCOHHR = var1;
         this.CRIIIHCRRHRROROCHRROORIHOCRCIR = var2;
      }

      private NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> RIROICHCRROROHCCROOCCCCOCHCCRI(
         IIHROHOIOHICCRRHRICHCIHRCROOIO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> var1
      ) {
         return var1.CIOHHCORHRCCRICCCORIHCRHCCCRRR(this.CRIIIHCRRHRROROCHRROORIHOCRCIR)
            ? new OICIRICHOHHIIHIRRRROORCRRRCORH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(
               this.HHOOHROORHCIOHOIHHCICICIRCOHHR, var1.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(this.CRIIIHCRRHRROROCHRROORIHOCRCIR)
            )
            : RCHHHORIRORROOHRRHHIIIOIROHHCC.IOOIHOHCROCHRCIOHICROHHCHCIOHI();
      }

      public NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var1, boolean var2, RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var3, boolean var4
      ) {
         return this.RIROICHCRROROHCCROOCCCCOCHCCRI(
            IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var2), var3, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var4)
            )
         );
      }

      public NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var1, boolean var2
      ) {
         return this.RIROICHCRROROHCCROOCCCCOCHCCRI(
            IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var2))
         );
      }

      public NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var1, boolean var2
      ) {
         return this.RIROICHCRROROHCCROOCCCCOCHCCRI(
            IIHROHOIOHICCRRHRICHCIHRCROOIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var2))
         );
      }

      @Override
      public Comparator<? super RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> comparator() {
         return IOIHHIORCICCHIIHOIOIOHHRICRHIO.OHOOIHRHCOIOIRHICHOOROHHIHOCRC();
      }

      @Override
      public boolean containsKey(@Nullable Object var1) {
         return this.CCRHRROIOIIRROHCOOCCCRRIOIHHHO(var1) != null;
      }

      public IIHROHOIOHICCRRHRICHCIHRCROOIO<C> CCRHRROIOIIRROHCOOCCCRRIOIHHHO(@Nullable Object var1) {
         if (var1 instanceof RCCCROCHCICCROHCOCCRRROCIIHCCH) {
            try {
               RCCCROCHCICCROHCOCCRRROCIIHCCH var2 = (RCCCROCHCICCROHCOCCRRROCIIHCCH)var1;
               if (!this.CRIIIHCRRHRROROCHRROORIHOCRCIR.contains(var2)) {
                  return null;
               }

               Entry var3 = this.HHOOHROORHCIOHOIHHCICICIRCOHHR.lowerEntry(var2);
               if (var3 != null && ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var3.getValue()).RHRIOOIRIIIHHHROHOHRIIHORCORRO.equals(var2)) {
                  return (IIHROHOIOHICCRRHRICHCIHRCROOIO<C>)var3.getValue();
               }
            } catch (ClassCastException var4) {
               return null;
            }
         }

         return null;
      }

      @Override
      Iterator<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>> entryIterator() {
         final Iterator var1;
         if (!this.CRIIIHCRRHRROROCHRROORIHOCRCIR.hasLowerBound()) {
            var1 = this.HHOOHROORHCIOHOIHHCICICIRCOHHR.values().iterator();
         } else {
            Entry var2 = this.HHOOHROORHCIOHOIHHCICICIRCOHHR.lowerEntry(this.CRIIIHCRRHRROROCHRROORIHOCRCIR.lowerEndpoint());
            if (var2 == null) {
               var1 = this.HHOOHROORHCIOHOIHHCICICIRCOHHR.values().iterator();
            } else if (this.CRIIIHCRRHRROROCHRROORIHOCRCIR
               .RIIHICHIOIORCIIRCOCCRHOOOHCOIH
               .isLessThan(((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.getValue()).RHRIOOIRIIIHHHROHOHRIIHORCORRO)) {
               var1 = this.HHOOHROORHCIOHOIHHCICICIRCOHHR.tailMap((RCCCROCHCICCROHCOCCRRROCIIHCCH<C>)var2.getKey(), true).values().iterator();
            } else {
               var1 = this.HHOOHROORHCIOHOIHHCICICIRCOHHR.tailMap(this.CRIIIHCRRHRROROCHRROORIHOCRCIR.lowerEndpoint(), true).values().iterator();
            }
         }

         return new com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>>(
            
         ) {
            protected Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> computeNext() {
               if (!var1.hasNext()) {
                  return this.ROCOROCOICRHOICORCIIRRRROCOHOC();
               }

               IIHROHOIOHICCRRHRICHCIHRCROOIO var1x = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var1.next();
               return CRRRICCRROCOHHOHIICIHORCOORRRH.this.CRIIIHCRRHRROROCHRROORIHOCRCIR
                     .RHRIOOIRIIIHHHROHOHRIIHORCORRO
                     .isLessThan(var1x.RHRIOOIRIIIHHHROHOHRIIHORCORRO)
                  ? this.ROCOROCOICRHOICORCIIRRRROCOHOC()
                  : ROCHRRCORRCOOOOOCOICOCROIIHIHH.immutableEntry(var1x.RHRIOOIRIIIHHHROHOHRIIHORCORRO, var1x);
            }
         };
      }

      @Override
      Iterator<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>> descendingEntryIterator() {
         Collection var1;
         if (this.CRIIIHCRRHRROROCHRROORIHOCRCIR.hasUpperBound()) {
            var1 = this.HHOOHROORHCIOHOIHHCICICIRCOHHR.headMap(this.CRIIIHCRRHRROROCHRROORIHOCRCIR.upperEndpoint(), false).descendingMap().values();
         } else {
            var1 = this.HHOOHROORHCIOHOIHHCICICIRCOHHR.descendingMap().values();
         }

         final IRIRICIHHCOICHHCHCOCCHHOROOCHH var2 = HRCROCOHHHICRHIHHOOCIIRRRCCIRR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1.iterator());
         if (var2.hasNext()
            && this.CRIIIHCRRHRROROCHRROORIHOCRCIR
               .RHRIOOIRIIIHHHROHOHRIIHORCORRO
               .isLessThan(((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.peek()).RHRIOOIRIIIHHHROHOHRIIHORCORRO)) {
            var2.next();
         }

         return new com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>>(
            
         ) {
            protected Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> computeNext() {
               if (!var2.hasNext()) {
                  return this.ROCOROCOICRHOICORCIIRRRROCOHOC();
               }

               IIHROHOIOHICCRRHRICHCIHRCROOIO var1x = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.next();
               return CRRRICCRROCOHHOHIICIHORCOORRRH.this.CRIIIHCRRHRROROCHRROORIHOCRCIR
                     .RIIHICHIOIORCIIRCOCCRHOOOHCOIH
                     .isLessThan(var1x.RHRIOOIRIIIHHHROHOHRIIHORCORRO)
                  ? ROCHRRCORRCOOOOOCOICOCROIIHIHH.immutableEntry(var1x.RHRIOOIRIIIHHHROHOHRIIHORCORRO, var1x)
                  : this.ROCOROCOICRHOICORCIIRRRROCOHOC();
            }
         };
      }

      @Override
      public int size() {
         return this.CRIIIHCRRHRROROCHRROORIHOCRCIR.equals(IIHROHOIOHICCRRHRICHCIHRCROOIO.OCORIOCROHHRRRICCHCOROROIRICCR())
            ? this.HHOOHROORHCIOHOIHHCICICIRCOHHR.size()
            : HRCROCOHHHICRHIHHOOCIIRRRCCIRR.size(this.entryIterator());
      }

      @Override
      public boolean isEmpty() {
         return this.CRIIIHCRRHRROROCHRROORIHOCRCIR.equals(IIHROHOIOHICCRRHRICHCIHRCROOIO.OCORIOCROHHRRRICCHCOROROIRICCR())
            ? this.HHOOHROORHCIOHOIHHCICICIRCOHHR.isEmpty()
            : !this.entryIterator().hasNext();
      }
   }

   private static final class HHCCIRHCCCIIRHCROHIORHIRHHIORH<C extends Comparable<?>>
      extends CRICCOOHHHCHOORCICOCOHIHOIRHOO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> {
      private final NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> HRCCCHRIOIHRCIOCIHOOCRRRIHIHHR;
      private final NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> HCIIHCICRRIIICCCRIOIIOOOCORHOI;
      private final IIHROHOIOHICCRRHRICHCIHRCROOIO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> OHOICRORCIIIHCOIOICOOIHRRIRORR;

      HHCCIRHCCCIIRHCROHIORHIRHHIORH(NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var1) {
         this(var1, IIHROHOIOHICCRRHRICHCIHRCROOIO.OCORIOCROHHRRRICCHCOROROIRICCR());
      }

      private HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var1,
         IIHROHOIOHICCRRHRICHCIHRCROOIO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> var2
      ) {
         this.HRCCCHRIOIHRCIOCIHOOCRRRIHIHHR = var1;
         this.HCIIHCICRRIIICCCRIOIIOOOCORHOI = new OICIRICHOHHIIHIRRRROORCRRRCORH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(var1);
         this.OHOICRORCIIIHCOIOICOOIHRRIRORR = var2;
      }

      private NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> RIROICHCRROROHCCROOCCCCOCHCCRI(
         IIHROHOIOHICCRRHRICHCIHRCROOIO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> var1
      ) {
         if (!this.OHOICRORCIIIHCOIOICOOIHRRIRORR.CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1)) {
            return RCHHHORIRORROOHRRHHIIIOIROHHCC.IOOIHOHCROCHRCIOHICROHHCHCIOHI();
         }

         var1 = var1.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(this.OHOICRORCIIIHCOIOICOOIHRRIRORR);
         return new OICIRICHOHHIIHIRRRROORCRRRCORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH<>(this.HRCCCHRIOIHRCIOCIHOOCRRRIHIHHR, var1);
      }

      public NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var1, boolean var2, RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var3, boolean var4
      ) {
         return this.RIROICHCRROROHCCROOCCCCOCHCCRI(
            IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var2), var3, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var4)
            )
         );
      }

      public NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var1, boolean var2
      ) {
         return this.RIROICHCRROROHCCROOCCCCOCHCCRI(
            IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var2))
         );
      }

      public NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var1, boolean var2
      ) {
         return this.RIROICHCRROROHCCROOCCCCOCHCCRI(
            IIHROHOIOHICCRRHRICHCIHRCROOIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var2))
         );
      }

      @Override
      public Comparator<? super RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> comparator() {
         return IOIHHIORCICCHIIHOIOIOHHRICRHIO.OHOOIHRHCOIOIRHICHOOROHHIHOCRC();
      }

      @Override
      Iterator<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>> entryIterator() {
         Collection var1;
         if (this.OHOICRORCIIIHCOIOICOOIHRRIRORR.hasLowerBound()) {
            var1 = this.HCIIHCICRRIIICCCRIOIIOOOCORHOI
               .tailMap(
                  this.OHOICRORCIIIHCOIOICOOIHRRIRORR.lowerEndpoint(),
                  this.OHOICRORCIIIHCOIOICOOIHRRIRORR.HHRHCHOCIRCHOIOIRCICHOCOIIOOHR() == IOIICIRIICICIIOORHCIIIIRRIHRHI.CLOSED
               )
               .values();
         } else {
            var1 = this.HCIIHCICRRIIICCCRIOIIOOOCORHOI.values();
         }

         final IRIRICIHHCOICHHCHCOCCHHOROOCHH var2 = HRCROCOHHHICRHIHHOOCIIRRRCCIRR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1.iterator());
         final RCCCROCHCICCROHCOCCRRROCIIHCCH var3;
         if (!this.OHOICRORCIIIHCOIOICOOIHRRIRORR.contains(RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO())
            || var2.hasNext()
               && ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.peek()).RIIHICHIOIORCIIRCOCCRHOOOHCOIH
                  == RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO()) {
            if (!var2.hasNext()) {
               return HRCROCOHHHICRHIHHOOCIIRRRCCIRR.HICCIROIRICHHOCICHCIOOROHHIOOR();
            }

            var3 = ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.next()).RHRIOOIRIIIHHHROHOHRIIHORCORRO;
         } else {
            var3 = RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO();
         }

         return new com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>>(
            
         ) {
            RCCCROCHCICCROHCOCCRRROCIIHCCH<C> HHCCHRCOHCORIHHRIHOICOROCHHHIR = var3;

            protected Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> computeNext() {
               if (!HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.OHOICRORCIIIHCOIOICOOIHRRIRORR
                     .RHRIOOIRIIIHHHROHOHRIIHORCORRO
                     .isLessThan(this.HHCCHRCOHCORIHHRIHOICOROCHHHIR)
                  && this.HHCCHRCOHCORIHHRIHOICOROCHHHIR != RCCCROCHCICCROHCOCCRRROCIIHCCH.CHOORICROROOCHCHOCOHRHRRRHCCRH()) {
                  IIHROHOIOHICCRRHRICHCIHRCROOIO var1x;
                  if (var2.hasNext()) {
                     IIHROHOIOHICCRRHRICHCIHRCROOIO var2x = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.next();
                     var1x = IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        this.HHCCHRCOHCORIHHRIHOICOROCHHHIR, var2x.RIIHICHIOIORCIIRCOCCRHOOOHCOIH
                     );
                     this.HHCCHRCOHCORIHHRIHOICOROCHHHIR = var2x.RHRIOOIRIIIHHHROHOHRIIHORCORRO;
                  } else {
                     var1x = IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        this.HHCCHRCOHCORIHHRIHOICOROCHHHIR, RCCCROCHCICCROHCOCCRRROCIIHCCH.CHOORICROROOCHCHOCOHRHRRRHCCRH()
                     );
                     this.HHCCHRCOHCORIHHRIHOICOROCHHHIR = RCCCROCHCICCROHCOCCRRROCIIHCCH.CHOORICROROOCHCHOCOHRHRRRHCCRH();
                  }

                  return ROCHRRCORRCOOOOOCOICOCROIIHIHH.immutableEntry(var1x.RIIHICHIOIORCIIRCOCCRHOOOHCOIH, var1x);
               } else {
                  return this.ROCOROCOICRHOICORCIIRRRROCOHOC();
               }
            }
         };
      }

      @Override
      Iterator<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>> descendingEntryIterator() {
         RCCCROCHCICCROHCOCCRRROCIIHCCH var1 = this.OHOICRORCIIIHCOIOICOOIHRRIRORR.hasUpperBound()
            ? this.OHOICRORCIIIHCOIOICOOIHRRIRORR.upperEndpoint()
            : RCCCROCHCICCROHCOCCRRROCIIHCCH.CHOORICROROOCHCHOCOHRHRRRHCCRH();
         boolean var2 = this.OHOICRORCIIIHCOIOICOOIHRRIRORR.hasUpperBound()
            && this.OHOICRORCIIIHCOIOICOOIHRRIRORR.CCCORHHHOCOICHHCIHOIRHHCOROROO() == IOIICIRIICICIIOORHCIIIIRRIHRHI.CLOSED;
         final IRIRICIHHCOICHHCHCOCCHHOROOCHH var3 = HRCROCOHHHICRHIHHOOCIIRRRCCIRR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(
            this.HCIIHCICRRIIICCCRIOIIOOOCORHOI.headMap(var1, var2).descendingMap().values().iterator()
         );
         RCCCROCHCICCROHCOCCRRROCIIHCCH var4;
         if (var3.hasNext()) {
            var4 = ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var3.peek()).RHRIOOIRIIIHHHROHOHRIIHORCORRO
                  == RCCCROCHCICCROHCOCCRRROCIIHCCH.CHOORICROROOCHCHOCOHRHRRRHCCRH()
               ? ((IIHROHOIOHICCRRHRICHCIHRCROOIO)var3.next()).RIIHICHIOIORCIIRCOCCRHOOOHCOIH
               : this.HRCCCHRIOIHRCIOCIHOOCRRRIHIHHR.higherKey(((IIHROHOIOHICCRRHRICHCIHRCROOIO)var3.peek()).RHRIOOIRIIIHHHROHOHRIIHORCORRO);
         } else {
            if (!this.OHOICRORCIIIHCOIOICOOIHRRIRORR.contains(RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO())
               || this.HRCCCHRIOIHRCIOCIHOOCRRRIHIHHR.containsKey(RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO())) {
               return HRCROCOHHHICRHIHHOOCIIRRRCCIRR.HICCIROIRICHHOCICHCIOOROHHIOOR();
            }

            var4 = this.HRCCCHRIOIHRCIOCIHOOCRRRIHIHHR.higherKey(RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO());
         }

         final RCCCROCHCICCROHCOCCRRROCIIHCCH var5 = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IOIICIRIICICIIOORHCIIIIRRIHRHI.firstNonNull(
            var4, RCCCROCHCICCROHCOCCRRROCIIHCCH.CHOORICROROOCHCHOCOHRHRRRHCCRH()
         );
         return new com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>>(
            
         ) {
            RCCCROCHCICCROHCOCCRRROCIIHCCH<C> OOCOICIHROCCRCCIROHRCHCOCIRRHC = var5;

            protected Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> computeNext() {
               if (this.OOCOICIHROCCRCCIROHRCHCOCIRRHC == RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO()) {
                  return this.ROCOROCOICRHOICORCIIRRRROCOHOC();
               }

               if (var3.hasNext()) {
                  IIHROHOIOHICCRRHRICHCIHRCROOIO var1x = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var3.next();
                  IIHROHOIOHICCRRHRICHCIHRCROOIO var2x = IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var1x.RHRIOOIRIIIHHHROHOHRIIHORCORRO, this.OOCOICIHROCCRCCIROHRCHCOCIRRHC
                  );
                  this.OOCOICIHROCCRCCIROHRCHCOCIRRHC = var1x.RIIHICHIOIORCIIRCOCCRHOOOHCOIH;
                  if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.OHOICRORCIIIHCOIOICOOIHRRIRORR
                     .RIIHICHIOIORCIIRCOCCRHOOOHCOIH
                     .isLessThan(var2x.RIIHICHIOIORCIIRCOCCRHOOOHCOIH)) {
                     return ROCHRRCORRCOOOOOCOICOCROIIHIHH.immutableEntry(var2x.RIIHICHIOIORCIIRCOCCRHOOOHCOIH, var2x);
                  }
               } else if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.OHOICRORCIIIHCOIOICOOIHRRIRORR
                  .RIIHICHIOIORCIIRCOCCRHOOOHCOIH
                  .isLessThan(RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO())) {
                  IIHROHOIOHICCRRHRICHCIHRCROOIO var3x = IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO(), this.OOCOICIHROCCRCCIROHRCHCOCIRRHC
                  );
                  this.OOCOICIHROCCRCCIROHRCHCOCIRRHC = RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO();
                  return ROCHRRCORRCOOOOOCOICOCROIIHIHH.immutableEntry(RCCCROCHCICCROHCOCCRRROCIIHCCH.OHICORHHOHIHHRRHIOOHOROICOCCIO(), var3x);
               }

               return this.ROCOROCOICRHOICORCIIRRRROCOHOC();
            }
         };
      }

      @Override
      public int size() {
         return HRCROCOHHHICRHIHHOOCIIRRRCCIRR.size(this.entryIterator());
      }

      public @Nullable IIHROHOIOHICCRRHRICHCIHRCROOIO<C> CCRHRROIOIIRROHCOOCCCRRIOIHHHO(Object var1) {
         if (var1 instanceof RCCCROCHCICCROHCOCCRRROCIIHCCH) {
            try {
               RCCCROCHCICCROHCOCCRRROCIIHCCH var2 = (RCCCROCHCICCROHCOCCRRROCIIHCCH)var1;
               Entry var3 = this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, true).firstEntry();
               if (var3 != null && ((RCCCROCHCICCROHCOCCRRROCIIHCCH)var3.getKey()).equals(var2)) {
                  return (IIHROHOIOHICCRRHRICHCIHRCROOIO<C>)var3.getValue();
               }
            } catch (ClassCastException var4) {
               return null;
            }
         }

         return null;
      }

      @Override
      public boolean containsKey(Object var1) {
         return this.CCRHRROIOIIRROHCOOCCCRRIOIHHHO(var1) != null;
      }
   }

   private final class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends OICIRICHOHHIIHIRRRROORCRRRCORH<C> {
      IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
         super(new OICIRICHOHHIIHIRRRROORCRRRCORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH<>(OICIRICHOHHIIHIRRRROORCRRRCORH.this.OIHRCCICICOIRIOOCCHCCRROCRIIOH));
      }

      @Override
      public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
         OICIRICHOHHIIHIRRRROORCRRRCORH.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1);
      }

      @Override
      public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
         OICIRICHOHHIIHIRRRROORCRRRCORH.this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      }

      @Override
      public boolean contains(C var1) {
         return !OICIRICHOHHIIHIRRRROORCRRRCORH.this.contains(var1);
      }

      @Override
      public IIOORRCRHCRIORIOCOHHIROOIIHROC<C> COHORCHIHROROOHICOCOOOHRIHOHHI() {
         return OICIRICHOHHIIHIRRRROORCRRRCORH.this;
      }
   }

   final class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      extends OOCHRIIIRIHRRCRIORHCROIIHCRRIC<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>
      implements Set<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> {
      final Collection<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> OCCRHRIHOOOHOCCCHCRRICICHHIOHR;

      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Collection<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var2) {
         this.OCCRHRIHOOOHOCCCHCRRICICHHIOHR = var2;
      }

      @Override
      protected Collection<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> delegate() {
         return this.OCCRHRIHOOOHOCCCHCRRICICHHIOHR;
      }

      @Override
      public int hashCode() {
         return ICRHCCCCOIICOCHHCRCOOIHICROIHI.hashCodeImpl(this);
      }

      @Override
      public boolean equals(@Nullable Object var1) {
         return ICRHCCCCOIICOCHHCRCOOIHICROIHI.equalsImpl(this, var1);
      }
   }

   private static final class RIOOCHICIHRHOHCCCCCHOCCCOHCRHI<C extends Comparable<?>>
      extends CRICCOOHHHCHOORCICOCOHIHOIRHOO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> {
      private final IIHROHOIOHICCRRHRICHCIHRCROOIO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> HIICCRHOICOHOOOORIOHCOOOROROCR;
      private final IIHROHOIOHICCRRHRICHCIHRCROOIO<C> CORORCOIIRHIOOOHROOOHRIICCOCCI;
      private final NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> COCCRROORIOCRICIRCOORORIRRIIOO;
      private final NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> HIHIORHRORIHOOICRCIHRCHRCCOOCI;

      private RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
         IIHROHOIOHICCRRHRICHCIHRCROOIO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> var1,
         IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var2,
         NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var3
      ) {
         this.HIICCRHOICOHOOOORIOHCOOOROROCR = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
            var1
         );
         this.CORORCOIIRHIOOOHROOOHRIICCOCCI = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
            var2
         );
         this.COCCRROORIOCRICIRCOORORIRRIIOO = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
            var3
         );
         this.HIHIORHRORIHOOICRCIHRCHRCCOOCI = new OICIRICHOHHIIHIRRRROORCRRRCORH.CRRRICCRROCOHHOHIICIHORCOORRRH<>(var3);
      }

      private NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> RIROICHCRROROHCCROOCCCCOCHCCRI(
         IIHROHOIOHICCRRHRICHCIHRCROOIO<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> var1
      ) {
         return !var1.CIOHHCORHRCCRICCCORIHCRHCCCRRR(this.HIICCRHOICOHOOOORIOHCOOOROROCR)
            ? RCHHHORIRORROOHRRHHIIIOIROHHCC.IOOIHOHCROCHRCIOHICROHHCHCIOHI()
            : new OICIRICHOHHIIHIRRRROORCRRRCORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI<>(
               this.HIICCRHOICOHOOOORIOHCOOOROROCR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1),
               this.CORORCOIIRHIOOOHROOOHRIICCOCCI,
               this.COCCRROORIOCRICIRCOORORIRRIIOO
            );
      }

      public NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var1, boolean var2, RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var3, boolean var4
      ) {
         return this.RIROICHCRROROHCCROOCCCCOCHCCRI(
            IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var2), var3, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var4)
            )
         );
      }

      public NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var1, boolean var2
      ) {
         return this.RIROICHCRROROHCCROOCCCCOCHCCRI(
            IIHROHOIOHICCRRHRICHCIHRCROOIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var2))
         );
      }

      public NavigableMap<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         RCCCROCHCICCROHCOCCRRROCIIHCCH<C> var1, boolean var2
      ) {
         return this.RIROICHCRROROHCCROOCCCCOCHCCRI(
            IIHROHOIOHICCRRHRICHCIHRCROOIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, IOIICIRIICICIIOORHCIIIIRRIHRHI.forBoolean(var2))
         );
      }

      @Override
      public Comparator<? super RCCCROCHCICCROHCOCCRRROCIIHCCH<C>> comparator() {
         return IOIHHIORCICCHIIHOIOIOHHRICRHIO.OHOOIHRHCOIOIRHICHOOROHHIHOCRC();
      }

      @Override
      public boolean containsKey(@Nullable Object var1) {
         return this.CCRHRROIOIIRROHCOOCCCRRIOIHHHO(var1) != null;
      }

      public @Nullable IIHROHOIOHICCRRHRICHCIHRCROOIO<C> CCRHRROIOIIRROHCOOCCCRRIOIHHHO(@Nullable Object var1) {
         if (var1 instanceof RCCCROCHCICCROHCOCCRRROCIIHCCH) {
            try {
               RCCCROCHCICCROHCOCCRRROCIIHCCH var2 = (RCCCROCHCICCROHCOCCRRROCIIHCCH)var1;
               if (!this.HIICCRHOICOHOOOORIOHCOOOROROCR.contains(var2)
                  || var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.CORORCOIIRHIOOOHROOOHRIICCOCCI.RIIHICHIOIORCIIRCOCCRHOOOHCOIH) < 0
                  || var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.CORORCOIIRHIOOOHROOOHRIICCOCCI.RHRIOOIRIIIHHHROHOHRIIHORCORRO) >= 0) {
                  return null;
               }

               if (var2.equals(this.CORORCOIIRHIOOOHROOOHRIICCOCCI.RIIHICHIOIORCIIRCOCCRHOOOHCOIH)) {
                  IIHROHOIOHICCRRHRICHCIHRCROOIO var3 = ROCHRRCORRCOOOOOCOICOCROIIHIHH.valueOrNull(this.COCCRROORIOCRICIRCOORORIRRIIOO.floorEntry(var2));
                  if (var3 != null
                     && var3.RHRIOOIRIIIHHHROHOHRIIHORCORRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.CORORCOIIRHIOOOHROOOHRIICCOCCI.RIIHICHIOIORCIIRCOCCRHOOOHCOIH)
                        > 0) {
                     return var3.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(this.CORORCOIIRHIOOOHROOOHRIICCOCCI);
                  }
               } else {
                  IIHROHOIOHICCRRHRICHCIHRCROOIO var5 = this.COCCRROORIOCRICIRCOORORIRRIIOO.get(var2);
                  if (var5 != null) {
                     return var5.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(this.CORORCOIIRHIOOOHROOOHRIICCOCCI);
                  }
               }
            } catch (ClassCastException var4) {
               return null;
            }
         }

         return null;
      }

      @Override
      Iterator<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>> entryIterator() {
         if (this.CORORCOIIRHIOOOHROOOHRIICCOCCI.isEmpty()) {
            return HRCROCOHHHICRHIHHOOCIIRRRCCIRR.HICCIROIRICHHOCICHCIOOROHHIOOR();
         }

         if (this.HIICCRHOICOHOOOORIOHCOOOROROCR.RHRIOOIRIIIHHHROHOHRIIHORCORRO.isLessThan(this.CORORCOIIRHIOOOHROOOHRIICCOCCI.RIIHICHIOIORCIIRCOCCRHOOOHCOIH)) {
            return HRCROCOHHHICRHIHHOOCIIRRRCCIRR.HICCIROIRICHHOCICHCIOOROHHIOOR();
         }

         final Iterator var1;
         if (this.HIICCRHOICOHOOOORIOHCOOOROROCR.RIIHICHIOIORCIIRCOCCRHOOOHCOIH.isLessThan(this.CORORCOIIRHIOOOHROOOHRIICCOCCI.RIIHICHIOIORCIIRCOCCRHOOOHCOIH)) {
            var1 = this.HIHIORHRORIHOOICRCIHRCHRCCOOCI.tailMap(this.CORORCOIIRHIOOOHROOOHRIICCOCCI.RIIHICHIOIORCIIRCOCCRHOOOHCOIH, false).values().iterator();
         } else {
            var1 = this.COCCRROORIOCRICIRCOORORIRRIIOO
               .tailMap(
                  this.HIICCRHOICOHOOOORIOHCOOOROROCR.RIIHICHIOIORCIIRCOCCRHOOOHCOIH.endpoint(),
                  this.HIICCRHOICOHOOOORIOHCOOOROROCR.HHRHCHOCIRCHOIOIRCICHOCOIIOOHR() == IOIICIRIICICIIOORHCIIIIRRIHRHI.CLOSED
               )
               .values()
               .iterator();
         }

         final RCCCROCHCICCROHCOCCRRROCIIHCCH var2 = IOIHHIORCICCHIIHOIOIOHHRICRHIO.OHOOIHRHCOIOIRHICHOOROHHIHOCRC()
            .min(
               this.HIICCRHOICOHOOOORIOHCOOOROROCR.RHRIOOIRIIIHHHROHOHRIIHORCORRO,
               RCCCROCHCICCROHCOCCRRROCIIHCCH.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CORORCOIIRHIOOOHROOOHRIICCOCCI.RHRIOOIRIIIHHHROHOHRIIHORCORRO)
            );
         return new com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>>(
            
         ) {
            protected Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> computeNext() {
               if (!var1.hasNext()) {
                  return this.ROCOROCOICRHOICORCIIRRRROCOHOC();
               }

               IIHROHOIOHICCRRHRICHCIHRCROOIO var1x = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var1.next();
               if (var2.isLessThan(var1x.RIIHICHIOIORCIIRCOCCRHOOOHCOIH)) {
                  return this.ROCOROCOICRHOICORCIIRRRROCOHOC();
               }

               var1x = var1x.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.CORORCOIIRHIOOOHROOOHRIICCOCCI);
               return ROCHRRCORRCOOOOOCOICOCROIIHIHH.immutableEntry(var1x.RIIHICHIOIORCIIRCOCCRHOOOHCOIH, var1x);
            }
         };
      }

      @Override
      Iterator<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>> descendingEntryIterator() {
         if (this.CORORCOIIRHIOOOHROOOHRIICCOCCI.isEmpty()) {
            return HRCROCOHHHICRHIHHOOCIIRRRCCIRR.HICCIROIRICHHOCICHCIOOROHHIOOR();
         }

         RCCCROCHCICCROHCOCCRRROCIIHCCH var1 = IOIHHIORCICCHIIHOIOIOHHRICRHIO.OHOOIHRHCOIOIRHICHOOROHHIHOCRC()
            .min(
               this.HIICCRHOICOHOOOORIOHCOOOROROCR.RHRIOOIRIIIHHHROHOHRIIHORCORRO,
               RCCCROCHCICCROHCOCCRRROCIIHCCH.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CORORCOIIRHIOOOHROOOHRIICCOCCI.RHRIOOIRIIIHHHROHOHRIIHORCORRO)
            );
         final Iterator var2 = this.COCCRROORIOCRICIRCOORORIRRIIOO
            .headMap(var1.endpoint(), var1.RRHHOOICOIRCICHRCRORICHCICRORC() == IOIICIRIICICIIOORHCIIIIRRIHRHI.CLOSED)
            .descendingMap()
            .values()
            .iterator();
         return new com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH<Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>>>(
            
         ) {
            protected Entry<RCCCROCHCICCROHCOCCRRROCIIHCCH<C>, IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> computeNext() {
               if (!var2.hasNext()) {
                  return this.ROCOROCOICRHOICORCIIRRRROCOHOC();
               }

               IIHROHOIOHICCRRHRICHCIHRCROOIO var1x = (IIHROHOIOHICCRRHRICHCIHRCROOIO)var2.next();
               if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.CORORCOIIRHIOOOHROOOHRIICCOCCI
                     .RIIHICHIOIORCIIRCOCCRHOOOHCOIH
                     .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x.RHRIOOIRIIIHHHROHOHRIIHORCORRO)
                  >= 0) {
                  return this.ROCOROCOICRHOICORCIIRRRROCOHOC();
               }

               var1x = var1x.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.CORORCOIIRHIOOOHROOOHRIICCOCCI);
               return RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.this.HIICCRHOICOHOOOORIOHCOOOROROCR.contains(var1x.RIIHICHIOIORCIIRCOCCRHOOOHCOIH)
                  ? ROCHRRCORRCOOOOOCOICOCROIIHIHH.immutableEntry(var1x.RIIHICHIOIORCIIRCOCCRHOOOHCOIH, var1x)
                  : this.ROCOROCOICRHOICORCIIRRRROCOHOC();
            }
         };
      }

      @Override
      public int size() {
         return HRCROCOHHHICRHIHHOOCIIRRRCCIRR.size(this.entryIterator());
      }
   }

   private final class RRCRRCORICCHOHHIRCHIROOHIIOHCO extends OICIRICHOHHIIHIRRRROORCRRRCORH<C> {
      private final IIHROHOIOHICCRRHRICHCIHRCROOIO<C> IICCOCRCRCRIHRROHCOICHHIHCRROO;

      RRCRRCORICCHOHHIRCHIROOHIIOHCO(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var2) {
         super(
            new OICIRICHOHHIIHIRRRROORCRRRCORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
               IIHROHOIOHICCRRHRICHCIHRCROOIO.OCORIOCROHHRRRICCHCOROROIRICCR(), var2, OICIRICHOHHIIHIRRRROORCRRRCORH.this.OIHRCCICICOIRIOOCCHCCRROCRIIOH
            )
         );
         this.IICCOCRCRCRIHRROHCOICHHIHCRROO = var2;
      }

      @Override
      public boolean CRRRICCRROCOHHOHIICIHORCOORRRH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
         if (!this.IICCOCRCRCRIHRROHCOICHHIHCRROO.isEmpty() && this.IICCOCRCRCRIHRROHCOICHHIHCRROO.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)) {
            IIHROHOIOHICCRRHRICHCIHRCROOIO var2 = OICIRICHOHHIIHIRRRROORCRRRCORH.this.RICRIRRCOHRCOCRRHHCRHRROOIOHHR(var1);
            return var2 != null && !var2.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(this.IICCOCRCRCRIHRROHCOICHHIHCRROO).isEmpty();
         } else {
            return false;
         }
      }

      @Override
      public @Nullable IIHROHOIOHICCRRHRICHCIHRCROOIO<C> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(C var1) {
         if (!this.IICCOCRCRCRIHRROHCOICHHIHCRROO.contains((C)var1)) {
            return null;
         }

         IIHROHOIOHICCRRHRICHCIHRCROOIO var2 = OICIRICHOHHIIHIRRRROORCRRRCORH.this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((C)var1);
         return var2 == null ? null : var2.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(this.IICCOCRCRCRIHRROHCOICHHIHCRROO);
      }

      @Override
      public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
         com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkArgument(
            this.IICCOCRCRCRIHRROHCOICHHIHCRROO.CRRRICCRROCOHHOHIICIHORCOORRRH(var1),
            "Cannot add range %s to subRangeSet(%s)",
            var1,
            this.IICCOCRCRCRIHRROHCOICHHIHCRROO
         );
         super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      }

      @Override
      public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
         if (var1.CIOHHCORHRCCRICCCORIHCRHCCCRRR(this.IICCOCRCRCRIHRROHCOICHHIHCRROO)) {
            OICIRICHOHHIIHIRRRROORCRRRCORH.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(this.IICCOCRCRCRIHRROHCOICHHIHCRROO));
         }
      }

      @Override
      public boolean contains(C var1) {
         return this.IICCOCRCRCRIHRROHCOICHHIHCRROO.contains((C)var1) && OICIRICHOHHIIHIRRRROORCRRRCORH.this.contains(var1);
      }

      @Override
      public void clear() {
         OICIRICHOHHIIHIRRRROORCRRRCORH.this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(this.IICCOCRCRCRIHRROHCOICHHIHCRROO);
      }

      @Override
      public IIOORRCRHCRIORIOCOHHIROOIIHROC<C> HICHRCOHCCRHOHCICOOCHOIHCCHIRI(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1) {
         if (var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IICCOCRCRCRIHRROHCOICHHIHCRROO)) {
            return this;
         } else {
            return var1.CIOHHCORHRCCRICCCORIHCRHCCCRRR(this.IICCOCRCRCRIHRROHCOICHHIHCRROO)
               ? new OICIRICHOHHIIHIRRRROORCRRRCORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO(this.IICCOCRCRCRIHRROHCOICHHIHCRROO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1))
               : OHRRIORRCRIRORHRIOOCORIIRRRRRO.HIHHRRIHRHOHCCOOIIRRIHRORRRIOR();
         }
      }
   }
}
