package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import com.google.errorprone.annotations.DoNotMock;
import java.util.Set;
import org.checkerframework.checker.nullness.qual.Nullable;

@DoNotMock("Use ImmutableRangeSet or TreeRangeSet")
@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
public interface IIOORRCRHCRIORIOCOHHIROOIIHROC<C extends Comparable> {
   boolean contains(C var1);

   IIHROHOIOHICCRRHRICHCIHRCROOIO<C> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(C var1);

   boolean HHCCIRHCCCIIRHCROHIORHIRHHIORH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1);

   boolean CRRRICCRROCOHHOHIICIHORCOORRRH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1);

   boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIOORRCRHCRIORIOCOHHIROOIIHROC<C> var1);

   default boolean enclosesAll(Iterable<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var1) {
      for (IIHROHOIOHICCRRHRICHCIHRCROOIO var3 : var1) {
         if (!this.CRRRICCRROCOHHOHIICIHORCOORRRH(var3)) {
            return false;
         }
      }

      return true;
   }

   boolean isEmpty();

   IIHROHOIOHICCRRHRICHCIHRCROOIO<C> HIOHORRRRRIIICOCRHCHHCCCICHCRC();

   Set<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> asRanges();

   Set<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> asDescendingSetOfRanges();

   IIOORRCRHCRIORIOCOHHIROOIIHROC<C> COHORCHIHROROOHICOCOOOHRIHOHHI();

   IIOORRCRHCRIORIOCOHHIROOIIHROC<C> HICHRCOHCCRHOHCICOOCHOIHCCHIRI(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1);

   void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1);

   void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IIHROHOIOHICCRRHRICHCIHRCROOIO<C> var1);

   void clear();

   void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IIOORRCRHCRIORIOCOHHIROOIIHROC<C> var1);

   default void addAll(Iterable<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var1) {
      for (IIHROHOIOHICCRRHRICHCIHRCROOIO var3 : var1) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3);
      }
   }

   void HHCCIRHCCCIIRHCROHIORHIRHHIORH(IIOORRCRHCRIORIOCOHHIROOIIHROC<C> var1);

   default void removeAll(Iterable<IIHROHOIOHICCRRHRICHCIHRCROOIO<C>> var1) {
      for (IIHROHOIOHICCRRHRICHCIHRCROOIO var3 : var1) {
         this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3);
      }
   }

   @Override
   boolean equals(@Nullable Object var1);

   @Override
   int hashCode();

   @Override
   String toString();
}
