package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import java.io.Serializable;
import org.checkerframework.checker.nullness.qual.Nullable;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
   serializable = true
)
final class HHRIICOIOORCHCOIICOOIHIRHHICRI<F, T> extends IOIHHIORCICCHIIHOIOIOHHRICRHIO<F> implements Serializable {
   final com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<F, ? extends T> IHIHRIOOOOIIHIOCRCRCHIICIOCCOR;
   final IOIHHIORCICCHIIHOIOIOHHRICRHIO<T> HHOIHCCIIICHHCRIRORHCCORIRIICO;
   private static final long IRROCCRCIOOIHOCOHCRIRCRRRCHCIH = 0L;

   HHRIICOIOORCHCOIICOOIHIRHHICRI(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<F, ? extends T> var1,
      IOIHHIORCICCHIIHOIOIOHHRICRHIO<T> var2
   ) {
      this.IHIHRIOOOOIIHIOCRCRCHIICIOCCOR = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      this.HHOIHCCIIICHHCRIRORHCCORIRIICO = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var2
      );
   }

   @Override
   public int compare(F var1, F var2) {
      return this.HHOIHCCIIICHHCRIRORHCCORIRIICO
         .compare((T)this.IHIHRIOOOOIIHIOCRCRCHIICIOCCOR.apply((F)var1), (T)this.IHIHRIOOOOIIHIOCRCRCHIICIOCCOR.apply((F)var2));
   }

   @Override
   public boolean equals(@Nullable Object var1) {
      if (var1 == this) {
         return true;
      }

      if (!(var1 instanceof HHRIICOIOORCHCOIICOOIHIRHHICRI)) {
         return false;
      }

      HHRIICOIOORCHCOIICOOIHIRHHICRI var2 = (HHRIICOIOORCHCOIICOOIHIRHHICRI)var1;
      return this.IHIHRIOOOOIIHIOCRCRCHIICIOCCOR.equals(var2.IHIHRIOOOOIIHIOCRCRCHIICIOCCOR)
         && this.HHOIHCCIIICHHCRIRORHCCORIRIICO.equals(var2.HHOIHCCIIICHHCRIRORHCCORIRIICO);
   }

   @Override
   public int hashCode() {
      return com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHRIICOIOORCHCOIICOOIHIRHHICRI.hashCode(
         this.IHIHRIOOOOIIHIOCRCRCHIICIOCCOR, this.HHOIHCCIIICHHCRIRORHCCORIRIICO
      );
   }

   @Override
   public String toString() {
      return this.HHOIHCCIIICHHCRIRORHCCORIRIICO + ".onResultOf(" + this.IHIHRIOOOOIIHIOCRCRCHIICIOCCOR + ")";
   }
}
