package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import java.util.Comparator;
import java.util.function.Function;
import java.util.stream.Collector;
import java.util.stream.Collector.Characteristics;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
final class IHCRORHRORIICHRHRCHRRIRRHHOCOO {
   private static final Collector<Object, ?, COIRRRCIORROCHIROCHROCHICCICIC<Object>> CRIHCCROCOROCCOOROORIRORHOORIO = Collector.of(
      COIRRRCIORROCHIROCHROCHICCICIC::HOOCHHHRHCRIRHCIHIRIRCOICCOIOR,
      COIRRRCIORROCHIROCHROCHICCICIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::CCHHRHRHCRHIHIHRIOICROHCHIIIHI,
      COIRRRCIORROCHIROCHROCHICCICIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH,
      COIRRRCIORROCHIROCHROCHICCICIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::IORRHROIIRHIIOOHCOOIRHOIHRHRHI
   );
   private static final Collector<Object, ?, CICOIHIRIIHHCIOICHRHICRIRCIOHC<Object>> RCOCCHRHCIHHRCRHHICOOIHHOIOIRC = Collector.of(
      CICOIHIRIIHHCIOICHRHICRIRCIOHC::CIRICCRCCRRCHHIOOHROCHRHRHHIIR,
      CICOIHIRIIHHCIOICHRHICRIRCIOHC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::HCCCCIHIOIHCHCCHOOHHCIHRCRRRHH,
      CICOIHIRIIHHCIOICHRHICRIRCIOHC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH,
      CICOIHIRIIHHCIOICHRHICRIRCIOHC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::HCCCCRHROOROHRHCCIOIOIROIOOCIH
   );
   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
   private static final Collector<IIHROHOIOHICCRRHRICHCIHRCROOIO<Comparable>, ?, OHRRIORRCRIRORHRIOOCORIIRRRRRO<Comparable>> OIORRCCCICHICCCIROROOOICHHHHHO = Collector.of(
      OHRRIORRCRIRORHRIOOCORIIRRRRRO::RHOROCOCCHCRRRCIHCIOHHIOOHRROI,
      OHRRIORRCRIRORHRIOOCORIIRRRRRO.HHCCIRHCCCIIRHCROHIORHIRHHIORH::OCOHORHCROHICRRIHCIHHRRCIHICRI,
      OHRRIORRCRIRORHRIOOCORIIRRRRRO.HHCCIRHCCCIIRHCROHIORHIRHHIORH::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH,
      OHRRIORRCRIRORHRIOOCORIIRRRRRO.HHCCIRHCCCIIRHCROHIORHIRHHIORH::RIIRRCCOOHRCRRCIIIHHIHRCCOHRIO
   );

   static <T, K, V> Collector<T, ?, ICOHIIIRCIORCORHRRROOOOCOOROIC<K, V>> toImmutableBiMap(
      Function<? super T, ? extends K> var0, Function<? super T, ? extends V> var1
   ) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var0
      );
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      return Collector.of(
         ICOHIIIRCIORCORHRRROOOOCOOROIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::new,
         (var2, var3) -> var2.IRRCCOICORICIHCHRHIHIHROIRHOCR((K)var0.apply(var3), (V)var1.apply(var3)),
         ICOHIIIRCIORCORHRRROOOOCOOROIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH,
         ICOHIIIRCIORCORHRRROOOOCOOROIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::OCROOCRIHRORHIIHIOOHRIIROHOHIH
      );
   }

   static <E> Collector<E, ?, COIRRRCIORROCHIROCHROCHICCICIC<E>> toImmutableList() {
      return (Collector<E, ?, COIRRRCIORROCHIROCHROCHICCICIC<E>>)CRIHCCROCOROCCOOROORIRORHOORIO;
   }

   static <T, K, V> Collector<T, ?, OOHRIIOOHROIOHCIRIHRHRRICRRHOI<K, V>> toImmutableMap(
      Function<? super T, ? extends K> var0, Function<? super T, ? extends V> var1
   ) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var0
      );
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      return Collector.of(
         OOHRIIOOHROIOHCIRIHRHRRICRRHOI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::new,
         (var2, var3) -> var2.RICRIRRCOHRCOCRRHHCRHRROOIOHHR((K)var0.apply(var3), (V)var1.apply(var3)),
         OOHRIIOOHROIOHCIRIHRHRRICRRHOI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::IRCIIHHICIHRCOCRROCOICRIHHCCHH,
         OOHRIIOOHROIOHCIRIHRHRRICRRHOI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::CHRROORCHRCIIRRORRRIORRRRICIRI
      );
   }

   static <E> Collector<E, ?, CICOIHIRIIHHCIOICHRHICRIRCIOHC<E>> toImmutableSet() {
      return (Collector<E, ?, CICOIHIRIIHHCIOICHRHICRIRCIOHC<E>>)RCOCCHRHCIHHRCRHHICOOIHHOIOIRC;
   }

   static <T, K, V> Collector<T, ?, RCHHHORIRORROOHRRHHIIIOIROHHCC<K, V>> toImmutableSortedMap(
      Comparator<? super K> var0, Function<? super T, ? extends K> var1, Function<? super T, ? extends V> var2
   ) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var0
      );
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var2
      );
      return Collector.of(
         () -> new RCHHHORIRORROOHRRHHIIIOIROHHCC.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0),
         (var2x, var3) -> var2x.OIHCOHRCICCCRHRCROOCIOIRRHHHIH(var1.apply(var3), var2.apply(var3)),
         RCHHHORIRORROOHRRHHIIIOIROHHCC.IRCIIHHICIHRCOCRROCOICRIHHCCHH::CRRRICCRROCOHHOHIICIHORCOORRRH,
         RCHHHORIRORROOHRRHHIIIOIROHHCC.IRCIIHHICIHRCOCRROCOICRIHHCCHH::CRIIRHCCOCROCRIRROOCHOOHCORCHO,
         Characteristics.UNORDERED
      );
   }

   static <E> Collector<E, ?, HCCCCIHIOIHCHCCHOOHHCIHRCRRRHH<E>> toImmutableSortedSet(Comparator<? super E> var0) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var0
      );
      return Collector.of(
         () -> new HCCCCIHIOIHCHCCHOOHHCIHRCRRRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0),
         HCCCCIHIOIHCHCCHOOHHCIHRCRRRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::RICHHRCCHRIICHROOROCCICOIRRHCR,
         HCCCCIHIOIHCHCCHOOHHCIHRCRRRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::IRCIIHHICIHRCOCRROCOICRIHHCCHH,
         HCCCCIHIOIHCHCCHOOHHCIHRCRRRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::HCIIOHOOOOCOCICOCOCRIRIRCCORRC
      );
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
   static <E extends Comparable<? super E>> Collector<IIHROHOIOHICCRRHRICHCIHRCROOIO<E>, ?, OHRRIORRCRIRORHRIOOCORIIRRRRRO<E>> toImmutableRangeSet() {
      return (Collector<IIHROHOIOHICCRRHRICHCIHRCROOIO<E>, ?, OHRRIORRCRIRORHRIOOCORIIRRRRRO<E>>)OIORRCCCICHICCCIROROOOICHHHHHO;
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
   static <T, K extends Comparable<? super K>, V> Collector<T, ?, CCHHRHRHCRHIHIHRIOICROHCHIIIHI<K, V>> toImmutableRangeMap(
      Function<? super T, IIHROHOIOHICCRRHRICHCIHRCROOIO<K>> var0, Function<? super T, ? extends V> var1
   ) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var0
      );
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      return Collector.of(
         CCHHRHRHCRHIHIHRIOICROHCHIIIHI::OIOCRHROICOOOICICIRRRHCCRHIOHH,
         (var2, var3) -> var2.CRRRICCRROCOHHOHIICIHORCOORRRH((IIHROHOIOHICCRRHRICHCIHRCROOIO<K>)var0.apply(var3), (V)var1.apply(var3)),
         CCHHRHRHCRHIHIHRIOICROHCHIIIHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH,
         CCHHRHRHCRHIHIHRIOICROHCHIIIHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH::ICIOHRCRHIRCHCCRCHRICIRRHIRIOI
      );
   }
}
