package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
   serializable = true
)
class OHCIIOCHHOHOHCOHHCRRHHCRHOIICC extends HIHCCHCCOCOHRICOICHRCOIHIIRIHO<Object, Object> {
   static final OHCIIOCHHOHOHCOHHCRRHHCRHOIICC RHOHHCCOCOIIIIRICOIIIRIOHHIOIO = new OHCIIOCHHOHOHCOHHCRRHHCRHOIICC();
   private static final long RCHRHIRRHCHOOOCHHOHHHIRORCOIHR = 0L;

   private OHCIIOCHHOHOHCOHHCRRHHCRHOIICC() {
      super(OOHRIIOOHROIOHCIRIHRHRRICRRHOI.RIOCOIOOIIRHOROHOCHHOORRCCOIHR(), 0);
   }

   private Object readResolve() {
      return RHOHHCCOCOIIIIRICOIIIRIOHHIOIO;
   }
}
