package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.errorprone.annotations.DoNotCall;
import java.util.Arrays;
import java.util.Collection;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.SortedSet;
import java.util.stream.Stream;
import org.checkerframework.checker.nullness.qual.Nullable;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
   emulated = true
)
public abstract class RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> implements Iterable<E> {
   private final com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR<Iterable<E>> IOHRCCRRHHOIOOROCRCOORCCHIHORO;

   protected RRHOOOORORHHOOIHRCCHIIHHIIIIOH() {
      this.IOHRCCRRHHOIOOROCRCOORCCHIHORO = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IHIRCRORCOOROROHHRRIIOOOOCCHRH();
   }

   RRHOOOORORHHOOIHRCCHIIHHIIIIOH(Iterable<E> var1) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      this.IOHRCCRRHHOIOOROCRCOORCCHIHORO = com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.HIHCCHCCOCOHRICOICHRCOIHIIRIHO(
         this != var1 ? var1 : null
      );
   }

   private Iterable<E> getDelegate() {
      return this.IOHRCCRRHHOIOOROCRCOORCCHIHORO.or(this);
   }

   public static <E> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> IIHRRHORCRCROCHHOHORCHCROCIHRO(final Iterable<E> var0) {
      return var0 instanceof RRHOOOORORHHOOIHRCCHIIHHIIIIOH ? (RRHOOOORORHHOOIHRCCHIIHHIIIIOH)var0 : new RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E>(var0) {
         @Override
         public Iterator<E> iterator() {
            return var0.iterator();
         }
      };
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public static <E> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> IIRHCHHOICHRICOOCRORCCIOOIHOIR(E[] var0) {
      return IIHRRHORCRCROCHHOHORCHCROCIHRO(Arrays.asList((E[])var0));
   }

   @Deprecated
   @DoNotCall("instances of FluentIterable don't need to be converetd to a FluentIterable")
   public static <E> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> var0) {
      return com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var0
      );
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public static <T> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T> HHCCIRHCCCIIRHCROHIORHIRHHIORH(Iterable<? extends T> var0, Iterable<? extends T> var1) {
      return IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0, var1);
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public static <T> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Iterable<? extends T> var0, Iterable<? extends T> var1, Iterable<? extends T> var2
   ) {
      return IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0, var1, var2);
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public static <T> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Iterable<? extends T> var0, Iterable<? extends T> var1, Iterable<? extends T> var2, Iterable<? extends T> var3
   ) {
      return IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0, var1, var2, var3);
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public static <T> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Iterable<? extends T>... var0) {
      return IRCIIHHICIHRCOCRROCOICRIHHCCHH(Arrays.copyOf(var0, var0.length));
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public static <T> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T> OCOHORHCROHICRRIHCIHHRRCIHICRI(final Iterable<? extends Iterable<? extends T>> var0) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var0
      );
      return new RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T>() {
         @Override
         public Iterator<T> iterator() {
            return HRCROCOHHHICRHIHHOOCIIRRRCCIRR.concat(
               HRCROCOHHHICRHIHHOOCIIRRRCCIRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0.iterator(), IRIHOIRCHIRRCRIOORCOICORHHORHH.HRORRRCHCRRCIIRHCIHHOORHCIORHH())
            );
         }
      };
   }

   private static <T> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T> IRCIIHHICIHRCOCRROCOICRIHHCCHH(final Iterable<? extends T>... var0) {
      for (Iterable var4 : var0) {
         com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
            var4
         );
      }

      return new RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T>() {
         @Override
         public Iterator<T> iterator() {
            return HRCROCOHHHICRHIHHOOCIIRRRCCIRR.concat(new IRCIIHHICIHRCOCRROCOICRIHHCCHH<Iterator<? extends T>>(var0.length) {
               public Iterator<? extends T> get(int var1) {
                  return var0[var1].iterator();
               }
            });
         }
      };
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public static <E> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> OCIRRIIHIIICCHOIIOIOCIHOIHORCH() {
      return IIHRRHORCRCROCHHOHORCHCROCIHRO(COIRRRCIORROCHIROCHROCHICCICIC.HHOIROIHOHHRHIRRRHRIRHOOIRCIOH());
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public static <E> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(@Nullable E var0, E... var1) {
      return IIHRRHORCRCROCHHOHORCHCROCIHRO(RCHOIICIHOCIRCIOORIOHRCRHOCRCR.asList((E)var0, (E[])var1));
   }

   @Override
   public String toString() {
      return IRIHOIRCHIRRCRIOORCOICORHHORHH.toString(this.getDelegate());
   }

   public final int HROCHRIIROHCRIIHCHCCHHOROCRHRO() {
      return IRIHOIRCHIRRCRIOORCOICORHHORHH.size(this.getDelegate());
   }

   public final boolean CIHCOICOOICHOCCHICIHRCOCIHRIOC(@Nullable Object var1) {
      return IRIHOIRCHIRRCRIOORCOICORHHORHH.contains(this.getDelegate(), var1);
   }

   public final RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> OOCHICCHORIOROIHCROIORROCOCOCI() {
      return IIHRRHORCRCROCHHOHORCHCROCIHRO(IRIHOIRCHIRRCRIOORCOICORHHORHH.cycle(this.getDelegate()));
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public final RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> CIOHHCORHRCCRICCCORIHCRHCCCRRR(Iterable<? extends E> var1) {
      return HHCCIRHCCCIIRHCROHIORHIRHHIORH(this.getDelegate(), var1);
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public final RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> OHHRIOHROOIHOROCIRHCHORIHRRRRI(E... var1) {
      return HHCCIRHCCCIIRHCROHIORHIRHHIORH(this.getDelegate(), Arrays.asList((E[])var1));
   }

   public final RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH<? super E> var1
   ) {
      return IIHRRHORCRCROCHHOHORCHCROCIHRO(IRIHOIRCHIRRCRIOORCOICORHHORHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(this.getDelegate(), var1));
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
   public final <T> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T> RHOORRIIOCHIRRHOHOOHIROHCRICRO(Class<T> var1) {
      return IIHRRHORCRCROCHHOHORCHCROCIHRO(IRIHOIRCHIRRCRIOORCOICORHHORHH.filter(this.getDelegate(), var1));
   }

   public final boolean HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH<? super E> var1
   ) {
      return IRIHOIRCHIRRCRIOORCOICORHHORHH.CRRRICCRROCOHHOHIICIHORCOORRRH(this.getDelegate(), var1);
   }

   public final boolean OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH<? super E> var1
   ) {
      return IRIHOIRCHIRRCRIOORCOICORHHORHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO(this.getDelegate(), var1);
   }

   public final com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR<E> CORCOCICIRIOHROHROIIOOHICCHCRR(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH<? super E> var1
   ) {
      return IRIHOIRCHIRRCRIOORCOICORHHORHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(this.getDelegate(), var1);
   }

   public final <T> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T> CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<? super E, T> var1
   ) {
      return IIHRRHORCRCROCHHOHORCHCROCIHRO(IRIHOIRCHIRRCRIOORCOICORHHORHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.getDelegate(), var1));
   }

   public <T> RRHOOOORORHHOOIHRCCHIIHHIIIIOH<T> RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<? super E, ? extends Iterable<? extends T>> var1
   ) {
      return OCOHORHCROHICRRIHCIHHRRCIHICRI(this.CRRRICCRROCOHHOHIICIHORCOORRRH(var1));
   }

   public final com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR<E> CRHHHHHRCHORCRHCHRCRIROCCIIHRI() {
      Iterator var1 = this.getDelegate().iterator();
      return var1.hasNext()
         ? com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.COIRRRCIORROCHIROCHROCHICCICIC(
            (E)var1.next()
         )
         : com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IHIRCRORCOOROROHHRRIIOOOOCCHRH();
   }

   public final com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR<E> IIHOCIIHCICIRCCOOIOCIIROICICHH() {
      Iterable var1 = this.getDelegate();
      if (var1 instanceof List) {
         List var4 = (List)var1;
         return var4.isEmpty()
            ? com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IHIRCRORCOOROROHHRRIIOOOOCCHRH()
            : com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.COIRRRCIORROCHIROCHROCHICCICIC(
               (E)var4.get(var4.size() - 1)
            );
      }

      Iterator var2 = var1.iterator();
      if (!var2.hasNext()) {
         return com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.IHIRCRORCOOROROHHRRIIOOOOCCHRH();
      }

      if (var1 instanceof SortedSet) {
         SortedSet var5 = (SortedSet)var1;
         return com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.COIRRRCIORROCHIROCHROCHICCICIC(
            (E)var5.last()
         );
      }

      Object var3;
      do {
         var3 = var2.next();
      } while (var2.hasNext());

      return com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR.COIRRRCIORROCHIROCHROCHICCICIC(
         (E)var3
      );
   }

   public final RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> CHCIRRHRCIRCHIIROHOOOHRCOHORII(int var1) {
      return IIHRRHORCRCROCHHOHORCHCROCIHRO(IRIHOIRCHIRRCRIOORCOICORHHORHH.skip(this.getDelegate(), var1));
   }

   public final RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> OHHCCHCROIIRIOHRICRIHHHIIRCOHI(int var1) {
      return IIHRRHORCRCROCHHOHORCHCROCIHRO(IRIHOIRCHIRRCRIOORCOICORHHORHH.limit(this.getDelegate(), var1));
   }

   public final boolean OIIHCIIHHCOROIHOCICIOHOHOIOORI() {
      return !this.getDelegate().iterator().hasNext();
   }

   public final COIRRRCIORROCHIROCHROCHICCICIC<E> OCHIIICOHRHHRRIIRCHIICCICCHHRC() {
      return COIRRRCIORROCHIROCHROCHICCICIC.HICRRICCHCCROOHHCHOCOCCHOIHHOC(this.getDelegate());
   }

   public final COIRRRCIORROCHIROCHROCHICCICIC<E> HHCCIRHCCCIIRHCROHIORHIRHHIORH(Comparator<? super E> var1) {
      return IOIHHIORCICCHIIHOIOIOHHRICRHIO.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(var1).CORCOCICIRIOHROHROIIOOHICCHCRR(this.getDelegate());
   }

   public final CICOIHIRIIHHCIOICHRHICRIRCIOHC<E> OOIHHIHCOHRCRHOHOHRRCICCICHRRI() {
      return CICOIHIRIIHHCIOICHRHICRIRCIOHC.IOHIHIIHCCCCCIHRORIOIOORCIOHII(this.getDelegate());
   }

   public final HCCCCIHIOIHCHCCHOOHHCIHRCRRRHH<E> CRRRICCRROCOHHOHIICIHORCOORRRH(Comparator<? super E> var1) {
      return HCCCCIHIOIHCHCCHOOHHCIHRCRRRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1, this.getDelegate());
   }

   public final HOCCCIICRCIIIIRHHICOCOOIICHIOR<E> CCCHRIROIHOORHIIRCHHORICRHOIIO() {
      return HOCCCIICRCIIIIRHHICOCOOIICHIOR.ICICIOCHHHIHOCHCOHORIHRCOHHOCR(this.getDelegate());
   }

   public final <V> OOHRIIOOHROIOHCIRIHRHRRICRRHOI<E, V> RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<? super E, V> var1
   ) {
      return ROCHRRCORRCOOOOOCOICOCROIIHIHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(this.getDelegate(), var1);
   }

   public final <K> HIHCCHCCOCOHRICOICHRCOIHIIRIHO<K, E> HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<? super E, K> var1
   ) {
      return HORCRRHOCRRICHROCIOOIORIOHCIHH.CRRRICCRROCOHHOHIICIHORCOORRRH(this.getDelegate(), var1);
   }

   public final <K> OOHRIIOOHROIOHCIRIHRHRRICRRHOI<K, E> OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<? super E, K> var1
   ) {
      return ROCHRRCORRCOOOOOCOICOCROIIHIHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(this.getDelegate(), var1);
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH
   public final E[] CCHHCIRHICHHHHRRIHIORCCORCCIHR(Class<E> var1) {
      return IRIHOIRCHIRRCRIOORCOICORHHORHH.toArray(this.getDelegate(), var1);
   }

   @CanIgnoreReturnValue
   public final <C extends Collection<? super E>> C HICRRICCHCCROOHHCHOCOCCHOIHHOC(C var1) {
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.checkNotNull(
         var1
      );
      Iterable var2 = this.getDelegate();
      if (var2 instanceof Collection) {
         var1.addAll(RIRHOCHIORCCIIOIIRHOCCCRHHCHHH.cast(var2));
      } else {
         for (Object var4 : var2) {
            var1.add(var4);
         }
      }

      return (C)var1;
   }

   @com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   public final String IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHIRRIIORRHORHRORIHOROIRCORCOO var1
   ) {
      return var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this);
   }

   public final E OCOOOIIHORIIIOIORRRRRHHRROHICC(int var1) {
      return IRIHOIRCHIRRCRIOORCOICORHHORHH.get(this.getDelegate(), var1);
   }

   public final Stream<E> OIHOCHRRRCHOIRCRIORICHIHOCHHCI() {
      return RHCHHROCORIHCIORRRIIOHIRHCRIOH.stream(this.getDelegate());
   }

   private static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<E>
      implements com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRCCOICORICIHCHRHIHIHROIRHOCR<Iterable<E>, RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E>> {
      public RRHOOOORORHHOOIHRCCHIIHHIIIIOH<E> IHHCHHHCRIHOOCOIOOCRIIICIOROIR(Iterable<E> var1) {
         return RRHOOOORORHHOOIHRCCHIIHHIIIIOH.IIHRRHORCRCROCHHOHORCHCROCIHRO(var1);
      }
   }
}
