package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HCHRIROHHHCORIOCROOCHRCIOROOCI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

public interface RIOOCHICIHRHOHCCCCCHOCCCOHCRHI {
   float IROORRRIICOHCHRICIHCHICOIHRICO();

   float ICRHCHCOCIIIHCCRCHRICOCROCCHCO();

   void HOIRIIORIIICHOOOHHCIOIICOHRROH();

   void CIHIOIRCOOORICCICHCRCIICCCHIRR();

   default boolean isDone() {
      return this.ICRHCHCOCIIIHCCRCHRICOCROCCHCO() == 2.0F;
   }
}
