package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;

import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import java.io.File;
import java.nio.file.Path;

public class CRICCOOHHHCHOORCICOCOHIHOIRHOO {
   public static final int ROOCIHRCRIOCHIRROCRIOCCOHORORR = 3;
   public static final int HICCORIOHCOHCRRHHCIOIIIRCCROOC = 0;
   public static final int CCCHICIIIROIRRRHCROHIOIRIROCIH = 0;
   private static final File CRIHCHIIOHOOCHRRRCHCOCHHCRRROC = new File(
      IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getMcDataDir(), "rewind"
   );
   public static final File HHCHRRHOHIOHICROOOHCHHROOOOIIC = new File(CRIHCHIIOHOOCHRRRCHCOCHHCRRROC, ".record");
   public static final File OHHIRCCICCRRCHCHOORHHIOORHRIRO = new File(CRIHCHIIOHOOCHRRRCHCOCHHCRRROC, ".packs");
   public static final File HOCCOIIIHRROIHOHIOHRCIOHOOCORI = new File(CRIHCHIIOHOOCHRRRCHCOCHHCRRROC, "rewinds");
   public static final File OCRRRHIIOHIIIORRCRHOCORCCHOHRH = new File(
      HOCCOIIIHRROIHOHIOHRCIOHOOCORI,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.getMinecraftVersion().RIOHOIHIOORHIIICRCOCRCICORICRH()
   );
   public static final File IRRHHCIIHCICIRRHCCOHRRCRHICRHC = new File(OCRRRHIIOHIIIORRCRHOCORCCHOHRH, ".thumbnails");
   public static final File RHROIROROOHRHROIOCRROOIHCCOIRI = new File(CRIHCHIIOHOOCHRRRCHCOCHHCRRROC, "projects");
   public static final File CRHORCCRRIRHCRHIIRICCCHHROCIHH = new File(CRIHCHIIOHOOCHRRRCHCOCHHCRRROC, "videos");
   public static final File OHHCCCCRCIROOICOICIHIHIOCCIRCO = new File(CRIHCHIIOHOOCHRRRCHCOCHHCRRROC, "screenshots");
   public static final Path OCOROOROCICIRRRCRIHHOOOIHOOHRC = IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOOOHICOOORRRIRHCCHIHICIICIROI.resolve("ffmpeg");
   public static final int IIHOHROOICCOHCOHOCIOCRIOCHHROC = (int)Math.pow(2.0, 16.0);
}
