package com.moonsworth.lunar.client.IHIRRIIORRHORHRORIHOROIRCORCOO;

import java.util.HashMap;
import java.util.Map;

public class RRCRRCORICCHOHHIRCHIROOHIIOHCO {
   final Map<String, HICHRCOHCCRHOHCICOOCHOIHCCHIRI> OIOCORRRORCOOIIRHHOCIRRIHIOHIR = new HashMap<>();

   public void HORHCCHHRCROIOIICHIHRRICICHICH() {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH(this);
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var1, HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2) {
      this.OIOCORRRORCOOIIRHHOCIRRIHIOHIR.put(var1, var2);
   }

   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI IRORICOCICICOIRIHOICHOROCHORIR(String var1) {
      return this.OIOCORRRORCOOIIRHHOCIRRIHIOHIR.get(var1);
   }

   public com.moonsworth.lunar.client.IHIRRIIORRHORHRORIHOROIRCORCOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI IOCCIHRHOIRHORIRIRHOHRHIIOCRIO(
      String var1
   ) {
      return this.IRORICOCICICOIRIHOICHOROCHORIR(var1) instanceof com.moonsworth.lunar.client.IHIRRIIORRHORHRORIHOROIRCORCOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2
         ? var2
         : null;
   }

   public IIHRRHORCRCROCHHOHORCHCROCIHRO HCICHICRRHORRORIRRRIHOROCOOIHO(String var1) {
      return this.IRORICOCICICOIRIHOICHOROCHORIR(var1) instanceof IIHRRHORCRCROCHHOHORCHCROCIHRO var2 ? var2 : null;
   }

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO ICHCCIIHROIHHCOHIIHICCOIHOCRCO() {
      return new RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this);
   }

   public IIHRRHORCRCROCHHOHORCHCROCIHRO CCOCRIRCHICIROOHCCHCRCHHOCRRIO(String var1) {
      IIHRRHORCRCROCHHOHORCHCROCIHRO var2 = (IIHRRHORCRCROCHHOHORCHCROCIHRO)this.IRORICOCICICOIRIHOICHOROCHORIR(var1);
      if (var2 != null) {
         return var2;
      }

      IIHRRHORCRCROCHHOHORCHCROCIHRO var3 = new IIHRRHORCRCROCHHOHORCHCROCIHRO();
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var3);
      return var3;
   }

   private static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends RRCRRCORICCHOHHIRCHIROOHIIOHCO {
      private final RRCRRCORICCHOHHIRCHIROOHIIOHCO HHCHICCCRHIHHCCCHIIHRIRHHHCOIO;

      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RRCRRCORICCHOHHIRCHIROOHIIOHCO var1) {
         this.HHCHICCCRHIHHCCCHIIHRIRHHHCOIO = var1;
      }

      @Override
      public HICHRCOHCCRHOHCICOOCHOIHCCHIRI IRORICOCICICOIRIHOICHOROCHORIR(String var1) {
         HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2 = super.IRORICOCICICOIRIHOICHOROCHORIR(var1);
         return var2 != null ? var2 : this.HHCHICCCRHIHHCCCHIIHRIRHHHCOIO.IRORICOCICICOIRIHOICHOROCHORIR(var1);
      }
   }
}
