package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RICRIRRCOHRCOCRRHHCRHRROOIOHHR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import com.moonsworth.lunar.client.util.CIIHHCHIRCRRIHOIOCCCROHOIOCCII;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IIHHICHCCCOHCHROIRIHICCHHOROCR;
import com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import java.util.List;
import lombok.Generated;
import org.jetbrains.annotations.Nullable;

public class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   public static final RCIROOOOICRHCCRRCIORHHIRCOIIIC IOHORHOIROOHHCHRHCCOHCCROIRCHC = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "icons/rewind/circle.png");
   public static final RCIROOOOICRHCCRRCIORHHIRCOIIIC COICOHIICOIOCRCIIICROIHOORHIRI = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "lunar", "icons/rewind/circle-pause.png"
   );
   public static final RCIROOOOICRHCCRRCIORHHIRCOIIIC ICHOHIOIRHOCCRRCIRHIOCCRIOIHIO = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "icons/rewind/marker.png");
   public static final RCIROOOOICRHCCRRCIORHHIRCOIIIC RHRROHRCOCCCHICROCHCOORHIOCRII = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "icons/rewind/pause.png");
   public static final RCIROOOOICRHCCRRCIORHHIRCOIIIC HHRORIHCRIIOROORHOIIOICRCHCICH = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "icons/rewind/play.png");
   public static final RCIROOOOICRHCCRRCIORHHIRCOIIIC CHIOCHCHICHOCOCRHHHRCCIIRIOCCH = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "icons/rewind/record.png");
   public static final RCIROOOOICRHCCRRCIORHHIRCOIIIC CIHIIOCORHOCCIRIRCOHOHIOCOHCIH = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "icons/rewind/shadow.png");
   public static final RCIROOOOICRHCCRRCIORHHIRCOIIIC RRIRRIICCIORHIRHCROCCRIRROHROI = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "icons/rewind/stop.png");
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI COROCHCHHOORCHCCOOIIHOOORCHIIC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showOnlyOnPauseScreen"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HIICCHCRIIRRORHRRICCHOOOCCRRCH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showShadowRecording"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RHOCHHIRRCHHHOHOIRROIROHHHIHIO CIHCHRHCOIHIIOROIIOIRRIICCORIR = new RHOCHHIRRCHHHOHOIRROIROHHHIHIO(
      null, "record", CHIOCHCHICHOCOCRHHHRCCIIRIOCCH
   );
   private final RHOCHHIRRCHHHOHOIRROIROHHHIHIO OIRRRHIROHCIRROICIRIRORIHHOOOI = new RHOCHHIRRCHHHOHOIRROIROHHHIHIO(null, "", CIHIIOCORHOCCIRIRCOHOHIOCOHCIH);
   private final RHOCHHIRRCHHHOHOIRROIROHHHIHIO RRRCCHIOCICOIOIRRCOOIRHHCORCIH = new RHOCHHIRRCHHHOHOIRROIROHHHIHIO(null, "", RRIRRIICCIORHIRHCROCCRIRROHROI);
   private final RHOCHHIRRCHHHOHOIRROIROHHHIHIO HIOIORCICHOHCHCHRRIRHIIIOHICIH = new RHOCHHIRRCHHHOHOIRROIROHHHIHIO(null, "", RHRROHRCOCCCHICROCHCOORHIOCRII);
   private final RHOCHHIRRCHHHOHOIRROIROHHHIHIO HOOHOCOHHHRCOOCHOOIORIRCHHICHO = new RHOCHHIRRCHHHOHOIRROIROHHHIHIO(null, "", ICHOHIOIRHOCCRRCIRHIOCCRIOIHIO);
   private boolean canInteract;
   private boolean HCICIIIRIOOIRIHROOOOIRCICRCHHH;
   private boolean HCHOOOHCIICIIICOHIIHRRICICOIRC;

   public HHCCIRHCCCIIRHCROHIORHIRHHIORH(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1) {
      super(true);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO, this.IICCOHOIROCIHRRORCHROIHCICCCIR());
      this.handle(
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.class,
         var1x -> {
            if (com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.REWIND.isEnabled()) {
               if (this.HCICIIIRIOOIRIHROOOOIRCICRCHHH && this.canInteract) {
                  if (var1x.OOHCRRRICCHRROOHIHHIORHICHHHHI() == 0
                     && var1x.OCOHRCHROROIRROIRICOOOICRHICCR()
                        == com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CLICK) {
                     RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO);
                     com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = (com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var1x.RRRCORIOCCCIOIIHRRCRHIHOROHRCR()
                        .RRHOHHRRCHRROORRRHIRORHORIIIII()
                        .COOCCHICCCIIICRHIOCOCIOOORCOCC(var2.getScale());

                     for (com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 : this.OIIIHRCICHOHCHHCIOIRCRIIOHRRHI()) {
                        if (var5.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3)) {
                           var5.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var3, var1x.OOHCRRRICCHRROOHIHHIORHICHHHHI());
                           var1x.setCancelled(true);
                           return;
                        }
                     }
                  }
               }
            }
         }
      );
   }

   private List<RHOCHHIRRCHHHOHOIRROIROHHHIHIO> OIIIHRCICHOHCHHCIOIRCRIIOHRRHI() {
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
         .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = var1.OHOHRHIIIIIORCIHCHCHCIIHOOIIOI();
      if (var2 != null && !var2.ROIOHOROCOIRIRRRRRIRIRRIHRRIIH()) {
         return List.of(this.RRRCCHIOCICOIOIRRCOOIRHHCORCIH, this.HIOIORCICHOHCHCHRRIRHIIIOHICIH, this.HOOHOCOHHHRCOOCHOOIORIRCHHICHO);
      } else {
         return var2 == null ? List.of(this.CIHCHRHCOIHIIOROIIOIRRIICCORIR) : List.of(this.CIHCHRHCOIHIIOROIIOIRRIICCORIR, this.OIRRRHIROHCIRROICIRIRORIHHOOOI);
      }
   }

   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      ORHIOICIOCRRHOOCOHRORIHICHRCRR var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      boolean var3 = var1 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO
         || var1 instanceof RICRIRRCOHRCOCRRHHCRHRROOIOHHR
         || var1 instanceof RIROICHCRROROHCCROOCCCCOCHCCRI && IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() == null
         || com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROCOCHICHORROOHCHOCIIICOHCHIOC()
               .OOHIORICCROCHCRCHCICRHCIOROICR()
               .OROOOIHOCIHICROOHCRCRROIIORHCH()
            && IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH() == null;
      if (!this.COROCHCHHOORCHCCOOIIHOOORCHIIC.get() && var2 != null) {
         var3 = var3
            || var1 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI
            || var1 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH
            || var1 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
            || var1 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;
      }

      return var3;
   }

   private RIOOCHICIHRHOHCCCCCHOCCCOHCRHI IICCOHOIROCIHRRORCHROIHCICCCIR() {
      return new CRICCOOHHHCHOORCICOCOHIHOIRHOO<String>(0.0F, 0.0F, RRCRRCORICCHOHHIRCHIROOHIIOHCO.TOP_RIGHT) {
         @Override
         public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH RHRCHCRRICCCOOIHHROROOOICCOHRH() {
            return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.OHHIHHRICOHICCORICHHICCORCCCOH()
               .HOIHOROOIOOCOIHCRIRIRIRRICIIHC(false)
               .RRORCOIRRIICOOICOIOCORHORCHCOC(false)
               .IROORIICOORCHOHRHRROCHROORHOHR();
         }

         @Override
         public HRCHROOHRIHCRCRHRIIROCIRHOIRHH HRRIHHICORIHCHICOHCCRCHCHOHRCH() {
            return HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(10, 18, 22, 50, 56, Integer.MAX_VALUE);
         }

         @Override
         public boolean ORCOCORROHIROCCIORORRRRCHIOOCH(boolean var1) {
            return (var1 || !HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.COROCHCHHOORCHCCOOIIHOOORCHIIC.get()) && super.ORCOCORROHIROCCIORORRRRCHIOOCH(var1);
         }

         @Nullable
         public String HOHCCHOIOHOHHOROHOIIHOOHORRHRO(boolean var1) {
            if (!com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.REWIND.isEnabled()) {
               return null;
            }

            if (!var1 && HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.COROCHCHHOORCHCCOOIIHOOORCHIIC.get()) {
               return null;
            }

            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
                  HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
               )
               .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            if (var2.HOROHROIORRIRIIIOOCCIROCRCROHI() != null) {
               return null;
            }

            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var2.OHOHRHIIIIIORCIHCHCHCIIHOOIIOI();
            ORHIOICIOCRRHOOCOHRORIHICHRCRR var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen();
            HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.canInteract = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, var3);
            HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCICIIIRIOOIRIHROOOOIRCICRCHHH = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
                     .bridge$getCurrentScreen()
                  != null
               && (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.canInteract || var1);
            HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCHOOOHCIICIIICOHIIHRRICICOIRC = false;
            IRRCCOICORICIHCHRHIHIHROIRHOCR var5 = com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCIHHCIOHIHIRHICIHROCOOCCCCCCR()
               .CCHHHHCICRCCCIOOIOICOOCRCRHCCR();
            String var6;
            if (var3 != null) {
               HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCHOOOHCIICIIICOHIIHRRICICOIRC = true;
               if (var3.ROIOHOROCOIRIRRRRRIRIRRIHRRIIH()) {
                  if (!HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HIICCHCRIIRRORHRRICCHOOOCCRRCH.get()
                     && !HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCICIIIRIOOIRIHROOOOIRCICRCHHH) {
                     return null;
                  }

                  var6 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HIICCHCRIIRRORHRRICCHOOOCCRRCH.get()
                     ? var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("rewind", "shadow")
                     : "Rewind";
                  HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCHOOOHCIICIIICOHIIHRRICICOIRC = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HIICCHCRIIRRORHRRICCHOOOCCRRCH.get();
               } else {
                  var6 = CIIHHCHIRCRRIHOIOCCCROHOIOCCII.OIOORROOHCRRCOCOHICICRCIOCIIOH(var3.CIIRRHOICHIIHCHHORIIOICHHOIOCI().CHCRRCICCCHRHCCHICOCIIIHRORHIC());
               }
            } else {
               if (!HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCICIIIRIOOIRIHROOOOIRCICRCHHH) {
                  return null;
               }

               var6 = "Rewind";
            }

            return var6;
         }

         protected float RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(boolean var1, String var2, float var3) {
            float var4 = super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3);
            boolean var5 = !this.HRRIHRORHIIHCCOHIOCOIIRIIROOHH.get();
            if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCHOOOHCIICIIICOHIIHRRICICOIRC) {
               if (var5) {
                  var4 += 4.0F;
               }

               var4 += 16.0F;
            }

            if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCICIIIRIOOIRIHROOOOIRCICRCHHH) {
               if (var5) {
                  var4 += 4.0F;
               }

               for (RHOCHHIRRCHHHOHOIRROIROHHHIHIO var7 : HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.OIIIHRCICHOHCHHCIOIRCRIIOHRRHI()) {
                  var4 += var7.getWidth() + 5.0F;
               }
            }

            return var4;
         }

         @Override
         public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
            float var2,
            float var3,
            boolean var4
         ) {
            if (!HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.canInteract || var4) {
               super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3, var4);
            }
         }

         @Override
         protected float RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(float var1, float var2, float var3, boolean var4) {
            boolean var5 = !this.HRRIHRORHIIHCCOHIOCOIIRIIROOHH.get();
            return var1 + (var4 ? 4.0F : 0.0F) + (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCHOOOHCIICIIICOHIIHRRICICOIRC ? (var5 ? 18 : 14) : 0);
         }

         @Override
         protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
            float var2,
            float var3,
            boolean var4,
            boolean var5
         ) {
            if (!var5) {
               if (var4 || !HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.COROCHCHHOORCHCCOOIIHOOORCHIIC.get()) {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(
                        HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO
                     )
                     .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7 = var6.OHOHRHIIIIIORCIHCHCHCIIHOOIIOI();
                  float var8 = var3 + this.getHeight() / 2.0F;
                  if (var7 != null) {
                     float var9 = 0.1F + (float)Math.sin(System.currentTimeMillis() % 2500L / 2500.0 * Math.PI * 2.0) * 0.1F;
                     int var10 = var7.ROIOHOROCOIRIRRRRRIRIRRIHRRIIH() ? -7060035 : -969160;
                     var10 = OCOHORHCROHICRRIHCIHHRRCIHICRI.HRHRORCIRICHCCCCCHICOOICIRHRIO(var10, (int)(204.0F * (1.0F - var9)));
                     if (var7.ROOCIIHOIICIIHCIIHHRICHCHORHII()
                        == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.PAUSED
                        )
                      {
                        var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           HHCCIRHCCCIIRHCROHIORHIRHHIORH.COICOHIICOIOCRCIIICROIHOORHIRI, (int)(var2 + 2.5F), (int)(var8 - 6.0F), 12, 12, -2130706433
                        );
                     } else if (!var7.ROIOHOROCOIRIRRRRRIRIRRIHRRIIH() || HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HIICCHCRIIRRORHRRICCHOOOCCRRCH.get()) {
                        var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           HHCCIRHCCCIIRHCROHIORHIRHHIORH.IOHORHOIROOHHCHRHCCOHCCROIRCHC, (int)(var2 + 2.5F), (int)(var8 - 6.0F), 12, 12, var10
                        );
                     }
                  } else if (!HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCICIIIRIOOIRIHROOOOIRCICRCHHH) {
                     var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        HHCCIRHCCCIIRHCROHIORHIRHHIORH.IOHORHOIROOHHCHRHCCOHCCROIRCHC, (int)(var2 + 2.5F), (int)(var8 - 6.0F), 12, 12, -789498312
                     );
                  }

                  if (HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HCICIIIRIOOIRIHROOOOIRCICRCHHH) {
                     if (var7 != null) {
                        HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HIOIORCICHOHCHCHRRIRHIIIOHICIH
                           .RRCRRCORICCHOHHIRCHIROOHIIOHCO(
                              var7.ROOCIIHOIICIIHCIIHHRICHCHORHII()
                                    == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.PAUSED
                                 ? "resume"
                                 : "pause"
                           );
                        HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.HIOIORCICHOHCHCHRRIRHIIIOHICIH
                           .RHRRHOHCRCHCCRRHOHHIRCCHOCICHC(
                              var7.ROOCIIHOIICIIHCIIHHRICHCHORHII()
                                    == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.PAUSED
                                 ? HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHRORIHCRIIOROORHOIIOICRCHCICH
                                 : HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHRROHRCOCCCHICROCHCOORHIOCRII
                           );
                     }

                     com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var13 = (com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)IIHHICHCCCOHCHROIRIHICCHHOROCR.OHIRHORHHORIHRHIHOHIIIRCRORIRO()
                        .RRHOHHRRCHRROORRRHIRORHORIIIII()
                        .COOCCHICCCIIICRHIOCOCIOOORCOCC(this.getScale());
                     float var15 = var2 + this.getWidth();

                     for (RHOCHHIRRCHHHOHOIRROIROHHHIHIO var12 : HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.OIIIHRCICHOHCHHCIOIRCRIIOHRRHI()) {
                        var15 = HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var12, var15, var8 + 0.5F);
                        var12.ICRCOOIHHHRCCROCCRIRCIOCIRIHIH(this.CRRROHROCCIHHRRIIIOCRCHCRIHOHI.get());
                        HHCCIRHCCCIIRHCROHIORHIRHHIORH.this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var12, var1, var13);
                     }
                  }
               }
            }
         }
      };
   }

   private float RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, float var2, float var3
   ) {
      var1.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var2 - var1.getWidth() - 5.0F, var3 - 8.0F, var1.getWidth(), 16.0F);
      return var1.getX();
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RHOCHHIRRCHHHOHOIRROIROHHHIHIO var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3
   ) {
      var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var3, this.canInteract && var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var3));
   }

   @Override
   public String getId() {
      return "REWIND_RECORDING_INDICATOR_CHILD";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.COROCHCHHOORCHCCOOIIHOOORCHIIC, this.HIICCHCRIIRRORHRRICCHOOOCCRRCH);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.CIHCHRHCOIHIIOROIIOIRRIICCORIR,
         "newRecording",
         () -> {
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1x = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
               .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            var1x.CIRRCCCORCOOIIOCICRHCIRIRHCIHO().OCOICRICIHOCOHCHRHCHIRCRROOOHH().forEach(Runnable::run);
         }
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.OIRRRHIROHCIRROICIRIRORIHHOOOI,
         "saveShadow",
         () -> {
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1x = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
               .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            var1x.ICCOCCHHICOICORIHORRROOOROCIIO().OCOICRICIHOCOHCHRHCHIRCRROOOHH().forEach(Runnable::run);
         }
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.RRRCCHIOCICOIOIRRCOOIRHHCORCIH,
         "stop",
         () -> {
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1x = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
               .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            var1x.CIRRCCCORCOOIIOCICRHCIRIRHCIHO().OCOICRICIHOCOHCHRHCHIRCRROOOHH().forEach(Runnable::run);
         }
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.HIOIORCICHOHCHCHRRIRHIIIOHICIH,
         "pause",
         () -> {
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1x = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
               .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            var1x.HIRRICHIHCIIHICIRICRHICOROOIHI().OCOICRICIHOCOHCHRHCHIRCRROOOHH().forEach(Runnable::run);
         }
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.HOOHOCOHHHRCOOCHOOIORIRCHHICHO,
         "addMarker",
         () -> {
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1x = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
               .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
            var1x.CCHCIIRCIICOORIOROCOIOOCCROCOH().OCOICRICIHOCOHCHRHCHIRCRROOOHH().forEach(Runnable::run);
         }
      );
      this.CIHCHRHCOIHIIOROIIOIRRIICCORIR
         .HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               -1057933768, -969160
            )
         );
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, String var2, Runnable var3
   ) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         (var1x, var2x) -> {
            if (IICCOOCHCHROORHHIIHROHCCRHRCOR.RRHHORCCRCHCROOIOCOHOHCOOIOIOH()
               != com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class
               )
             {
               com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.OIOOICHIIHICCRCOOIOIOCIRRIIIRC();
            }

            var3.run();
            return true;
         }
      );
      var1.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var2);
      var1.HCRCROOHOHOHOHCOCRCCHRIHCORRIO(false);
   }

   @Generated
   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI OCRCRHRCOHCCICHCRCORHORIIOORCC() {
      return this.COROCHCHHOORCHCCOOIIHOOORCHIIC;
   }
}
