package com.moonsworth.lunar.client.util;

import java.util.ArrayList;
import java.util.List;

public class ROCRHIOCHIIOCROIHHOHHROCHCIHCH {
   public static final String ROCRRIIRIHCHRCCRRCCIIRCIIRCRCR = "LUNAR-SHADER-DEFINITION-MARKER";

   private static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0,
      String var1,
      String var2
   ) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .OHOHOOHHHICIHIORCHIIOHRRRCHRHI();
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = var3.HCIOORICORCCCRIHCOOOOOOROOICOI();
      if (var4 != null && var4.OCOOIIHCCHCHCIHIRHIOROHOIOOOHC()) {
         int var5 = IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, '\n');
         int var6 = IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, '\n');
         var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var6 - var5);
      }
   }

   private static int IRCIIHHICIHRCOCRROCOICRIHHCCHH(String var0, char var1) {
      int var2 = 0;

      for (int var3 = 0; var3 < var0.length(); var3++) {
         if (var1 == var0.charAt(var3)) {
            var2++;
         }
      }

      return var2;
   }

   private static String HCCICHCRRIICICCHCIRCRRIIRROHHC(String var0) {
      int var1 = var0.indexOf("LUNAR-SHADER-DEFINITION-MARKER");
      if (var1 == -1) {
         return null;
      }

      int var2 = var1 + "LUNAR-SHADER-DEFINITION-MARKER".length();
      return var2 >= var0.length() ? null : var0.substring(var2);
   }

   public static String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var0,
      com.moonsworth.lunar.client.util.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      String var3 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var0, var2, ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var1)
      );
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var0, var3);
      return var3;
   }

   public static String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var0,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      String var3 = HCCICHCRRIICICCHCIRCRRIIRROHHC(var0);
      if (var3 == null) {
         return var0;
      }

      boolean var4 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHCHRCCRRHORIOCIOHHCRHCHICRIHH()
         .HRHRIHRROHHORROCHCOHICRROHRRIO();
      int var5 = 0;
      int var6 = 0;
      int var7 = 0;
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 8) {
         var2.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("LUNAR_IN", "in");
         var2.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("LUNAR_OUT", "out");
         if (var1
            == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.FRAGMENT
            )
          {
            var2.RRCRRCORICCHOHHIRCHIROOHIIOHCO(
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.VEC4,
               "fragColor"
            );
         }
      } else if (var1
         == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.VERTEX
         )
       {
         var2.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("LUNAR_IN", "attribute");
         var2.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("LUNAR_OUT", "varying");
      } else {
         var2.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("LUNAR_IN", "varying");
      }

      StringBuilder var8 = new StringBuilder();
      if (var4) {
         var8.append("#version 450\n");
      } else if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 8) {
         var8.append("#version 330\n");
      } else {
         var8.append("#version 120\n");
      }

      for (com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var10 : var2.ICOHHIRRHHIROHOCORRRCOCRCHHROH) {
         var8.append("#define ")
            .append((String)var10.OHICIOOICHICOIOCOROIIOCCHRRCIC)
            .append(" ")
            .append((String)var10.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC)
            .append("\n");
      }

      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 30) {
         if (!var2.RCCOHHIRIHRHIIORIHCRHHIIHHRCRO.isEmpty()) {
            if (var4) {
               var8.append("layout(std140, set = 0, binding = ").append(var5++).append(") ");
            } else {
               var8.append("layout(std140) ");
            }

            var8.append("uniform LunarUniforms {\n");

            for (com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var16 : var2.RCCOHHIRIHRHIIORIHCRHHIIHHRCRO) {
               var8.append("    ")
                  .append(
                     ((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var16.OHICIOOICHICOIOCOROIIOCCHRRCIC)
                        .asGlslType()
                  )
                  .append(" ")
                  .append((String)var16.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC)
                  .append(";\n");
            }

            var8.append("};\n");
         }
      } else {
         for (com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var17 : var2.RCCOHHIRIHRHIIORIHCRHHIIHHRCRO) {
            if (var4) {
               var8.append("layout(set = 0, binding = ").append(var5++).append(") ");
            }

            var8.append("uniform ")
               .append(
                  ((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var17.OHICIOOICHICOIOCOROIIOCCHRRCIC)
                     .asGlslType()
               )
               .append(" ")
               .append((String)var17.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC)
               .append(";\n");
         }
      }

      for (String var18 : var2.OCICCRIICOIOOOOCHRIOCRRCHROOHI) {
         if (var4) {
            var8.append("layout(set = 0, binding = ").append(var5++).append(") ");
         }

         var8.append("uniform sampler2D ").append(var18).append(";\n");
      }

      for (com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var19 : var2.HIHHCCHCIORRIORCOOHOHOCCHRRCIC) {
         if (var4) {
            var8.append("layout(location = ").append(var6++).append(") ");
         }

         var8.append("LUNAR_IN ")
            .append(
               ((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var19.OHICIOOICHICOIOCOROIIOCCHRRCIC)
                  .asGlslType()
            )
            .append(" ")
            .append((String)var19.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC)
            .append(";\n");
      }

      for (com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var20 : var2.HHIIHOOOHRHCIIHORRRCCOCRCRIIRI) {
         if (var4) {
            var8.append("layout(location = ").append(var7++).append(") ");
         }

         var8.append("LUNAR_OUT ")
            .append(
               ((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var20.OHICIOOICHICOIOCOROIIOCCHRRCIC)
                  .asGlslType()
            )
            .append(" ")
            .append((String)var20.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC)
            .append(";\n");
      }

      return var8.append(var3).toString();
   }

   public static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
      private final List<com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH, String>> RCCOHHIRIHRHIIORIHCRHHIIHHRCRO = new ArrayList<>();
      private final List<String> OCICCRIICOIOOOOCHRIOCRRCHROOHI = new ArrayList<>();
      private final List<com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH, String>> HIHHCCHCIORRIORCOOHOHOCCHRRCIC = new ArrayList<>();
      private final List<com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO<com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH, String>> HHIIHOOOHRHCIIHORRRCCOCRCRIIRI = new ArrayList<>();
      private final List<com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO<String, String>> ICOHHIRRHHIROHOCORRRCOCRCHHROH = new ArrayList<>();

      private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      }

      public ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         String var1,
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
      ) {
         return this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2, var1);
      }

      public ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         String var2
      ) {
         this.RCCOHHIRIHRHIIORIHCRHHIIHHRCRO
            .add(
               com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORCOCORROHIROCCIORORRRRCHIOOCH(
                  var1, var2
               )
            );
         return this;
      }

      public ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IHIHCOIRIHIRHICORCCHCOOICIIOIC(String var1) {
         this.OCICCRIICOIOOOOCHRIOCRRCHROOHI.add(var1);
         return this;
      }

      public ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CRRRICCRROCOHHOHIICIHORCOORRRH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         String var2
      ) {
         this.HIHHCCHCIORRIORCOOHOHOCCHRRCIC
            .add(
               com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORCOCORROHIROCCIORORRRRCHIOOCH(
                  var1, var2
               )
            );
         return this;
      }

      public ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RRCRRCORICCHOHHIRCHIROOHIIOHCO(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         String var2
      ) {
         this.HHIIHOOOHRHCIIHORRRCCOCRCRIIRI
            .add(
               com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORCOCORROHIROCCIORORRRRCHIOOCH(
                  var1, var2
               )
            );
         return this;
      }

      public ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ICCIIIRHHOOIHCCHIRRCRHICHIHRIH(String var1, String var2) {
         this.ICOHHIRRHHIROHOCORRRCOCRCHHROH
            .add(
               com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORCOCORROHIROCCIORORRRRCHIOOCH(
                  var1, var2
               )
            );
         return this;
      }

      public static ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RRIORHOORCORHOIIIRHRRRCOOHRCOO() {
         return new ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();
      }

      public static ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0,
         com.moonsworth.lunar.client.util.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1
      ) {
         ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = RRIORHOORCORHOIIIRHRRRCOOHRCOO();
         var1.HIRIOOCHIHRICCIIRCCHCCOCRORCOC().forEach(var1x -> var2.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1x.getType(), var1x.getVarName()));
         com.moonsworth.lunar.client.util.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1.OOIIIROOHRCIHIRCCROHICORIROOOR(), var2::HHCCIRHCCCIIRHCROHIORHIRHHIORH
         );
         var1.HCIOCOOORRRHOROHIOOIROOCOICRHR().forEach(var1x -> var2.IHIHCOIRIHIRHICORCCHCOOICIIOIC(var1x.OIHIRICIOICCOOORIRORORICRHIHII()));
         var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1.OOIIIROOHRCIHIRCCROHICORIROOOR());
         var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0, var1.OOIIIROOHRCIHIRCCROHICORIROOOR());
         return var2;
      }

      public static ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0
      ) {
         ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = RRIORHOORCORHOIIIRHRRRCOOHRCOO();
         var0.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1::HHCCIRHCCCIIRHCROHIORHIRHHIORH);
         var0.CRHROHHHCIHHCOHCOORCRIHHIICROR(var1::IHIHCOIRIHIRHICORCCHCOOICIIOIC);
         return var1;
      }

      public ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
         com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2
      ) {
         if (var1
            == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.VERTEX
            )
          {
            var2.RRCRRCORICCHOHHIRCHIROOHIIOHCO(this::CRRRICCRROCOHHOHIICIHORCOORRRH);
            var2.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(this::RRCRRCORICCHOHHIRCHIROOHIIOHCO);
         } else {
            var2.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(this::CRRRICCRROCOHHOHIICIHORCOORRRH);
         }

         return this;
      }

      public ROCRHIOCHIIOCROIHHOHHROCHCIHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
         com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2
      ) {
         boolean var3 = var2.RIHOIHRHRRROOCIOHCIIRCICHHCHRH();
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 8) {
            this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("SAMPLE(tex, uv)", "texture(tex, uv)");
            this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("OUT_COLOR", "fragColor");
            if (var1
               == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.VERTEX
               )
             {
               this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("POS", "Position");
               if (var3) {
                  this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("UV", "UV0");
                  this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("NORMAL", "Normal");
               }
            }
         } else {
            this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("SAMPLE(tex, uv)", "texture2D(tex, uv)");
            this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("OUT_COLOR", "gl_FragColor");
            if (var1
               == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.VERTEX
               )
             {
               this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("POS", "gl_Vertex.xyz");
               if (var3) {
                  this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("UV", "gl_MultiTexCoord0");
                  this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("NORMAL", "gl_Normal");
               }
            }
         }

         if (var1
               == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.VERTEX
            && var3) {
            if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION < 6) {
               this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("MODEL_VIEW_MAT", "gl_ModelViewMatrix");
               this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("NORMAL_MAT", "gl_NormalMatrix");
               this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("LEGACY_MODELVIEW_RESIZE", "LunarLegacyUISize");
            } else {
               this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("MODEL_VIEW_MAT", "LunarModelViewMat");
               this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("NORMAL_MAT", "mat3(LunarNormalMat)");
            }
         }

         if (var2
            == com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IOHRRCOHOCOHCRCIOCRIRIICRHCCRI
            )
          {
            if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION < 6) {
               this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("PROJECTION_MAT", "gl_ProjectionMatrix");
            } else {
               this.ICCIIIRHHOOIHCCHIRRCRHICHIHRIH("PROJECTION_MAT", "LunarProjectionMat");
            }
         }

         return this;
      }
   }
}
