package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.lib.adventure.text.Component;
import java.util.Objects;
import lombok.Generated;
import org.joml.Vector3i;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final Vector3i ORCIRORHHRHCCOCCHHIIHCCOHRHHHO;
   private com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIHCCRIICRRIRIICCHOHIHIHHROHC;
   private long OCRRIOCOIROCIRRORICCICHCCHOHRC;

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Vector3i var1) {
      this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO = var1;
      this.RCIHCCRIICRRIRIICCHOHIHIHHROHC = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.MOB;
      this.OCRRIOCOIROCIRRORICCICHCCHOHRC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
   }

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Vector3i var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2
   ) {
      this(var1);
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2);
   }

   public boolean HHHICCROOOHHRCHCHOCIOOIRIRIHCR() {
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() - this.OCRRIOCOIROCIRRORICCICHCCHOHRC > 1000L;
   }

   public double CRRRICCRROCOHHOHIICIHORCOORRRH(Vector3i var1) {
      return this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO.distanceSquared(var1);
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(OCOHORHCROHICRRIHCIHHRRCIHICRI var1, IRCIIHHICIHRCOCRROCOICRIHHCCHH var2) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IHRHHIOIIICOROOORIOHCIROIRCOHH();
      var1.push();
      var1.translate(-var3.bridge$renderPosX(), -var3.bridge$renderPosY(), -var3.bridge$renderPosZ());
      int var4 = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.getColor(
         var2, this.RCIHCCRIICRRIRIICCHOHIHIHHROHC
      );
      CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         var1,
         this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO,
         com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI.HRHRORCIRICHCCCCCHICOOICIRHRIO(var4, 34),
         true
      );
      if (var2.IRRROCIRROORRCOHIICIOIHOHCICRH().get()) {
         CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO, var4);
      }

      String var5 = "Unknown";
      if (this.RCIHCCRIICRRIRIICCHOHIHIHHROHC != null) {
         var5 = switch (this.RCIHCCRIICRRIRIICCHOHIHIHHROHC) {
            case START -> "Start";
            case MOB -> "Mob";
            case TREASURE -> "Treasure";
         };
      }

      double var6 = this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO.x() + 0.5;
      double var8 = this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO.y() + 1.5;
      double var10 = this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO.z() + 0.5;
      CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, Component.text(var5), var6, var8, var10, true, 1.0F, true);
      var1.pop();
   }

   @Override
   public boolean equals(Object var1) {
      if (this == var1) {
         return true;
      } else if (var1 != null && this.getClass() == var1.getClass()) {
         RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = (RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var1;
         return this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO.equals(var2.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO);
      } else {
         return false;
      }
   }

   @Override
   public int hashCode() {
      return Objects.hash(this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO);
   }

   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      switch (var1) {
         case CRIT:
            this.OCRRIOCOIROCIRRORICCICHCCHOHRC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
            break;
         case DRIPPING_LAVA:
            this.OCRRIOCOIROCIRRORICCICHCCHOHRC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
            this.RCIHCCRIICRRIRIICCHOHIHIHHROHC = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.TREASURE;
            break;
         case ENCHANTED_HIT:
            this.OCRRIOCOIROCIRRORICCICHCCHOHRC = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
            this.RCIHCCRIICRRIRIICCHOHIHIHHROHC = com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.START;
      }
   }

   @Generated
   public Vector3i ORHROIHHHIHCHRRCIHOHIHHROOOOOR() {
      return this.ORCIRORHHRHCCOCCHHIIHCCOHRHHHO;
   }

   @Generated
   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HCRIOHHOCHORCIHORICOCCHCROCCIO() {
      return this.RCIHCCRIICRRIRIICCHOHIHIHHROHC;
   }

   @Generated
   public long HIIRCOOICCRCRCCORRIORHOIIRHRCH() {
      return this.OCRRIOCOIROCIRRORICCICHCCHOHRC;
   }
}
