package com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

public class CCIHHRIOOOOCOHRCIHOHROOICIORCC<T extends Enum<T> & com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.ORHIOICIOCRRHOOCOHRORIHICHRCRR>
   extends ICICIOCHHHIHOCHCOHORIHRCOHHOCR<com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI<T>> {
   private final ROOCOCCCIRHHHIRIOIHHHHRHIICHHR IICRHHCRROHHHOORHIIRRHOIHCOCHO = new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(
      this,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
         "lunar", "icons/settings/arrow-left-18x18.png"
      ),
      4.5F
   );
   private final ROOCOCCCIRHHHIRIOIHHHHRHIICHHR IIIOOCCIRCCOIROOCROORHHHHRCHRR = new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(
      this,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
         "lunar", "icons/settings/arrow-right-18x18.png"
      ),
      4.5F
   );

   public CCIHHRIOOOOCOHRCIHOHROOICIORCC(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI<T> var1,
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      super(var1, var2);
      Class var3 = ((Enum)var1.get()).getClass();
      Enum[] var4 = (Enum[])var3.getEnumConstants();
      int var5 = var4.length;
      this.IICRHHCRROHHHOORHIIRRHOIHCOCHO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var3x, var4x) -> {
         int var5x = ((Enum)var1.get()).ordinal();
         if (var5x - 1 < 0) {
            var1.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH((T)var4[var5 - 1]);
         } else {
            var1.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH((T)var4[var5x - 1]);
         }

         return true;
      });
      this.IIIOOCCIRCCOIROOCROORHHHHRCHRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var3x, var4x) -> {
         int var5x = ((Enum)var1.get()).ordinal();
         if (var5x + 1 >= var5) {
            var1.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH((T)var4[0]);
         } else {
            var1.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH((T)var4[var5x + 1]);
         }

         return true;
      });
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         (var1x, var2x) -> {
            if (this.IICRHHCRROHHHOORHIIRRHOIHCOCHO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1x)) {
               return this.IICRHHCRROHHHOORHIIRRHOIHCOCHO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1x, var2x);
            } else {
               return this.IIIOOCCIRCCOIROOCROORHHHHRCHRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1x)
                  ? this.IIIOOCCIRCCOIROOCROORHHHHRCHRR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1x, var2x)
                  : false;
            }
         }
      );
   }

   @Override
   public void IRRCCOICORICIHCHRHIHIHROIRHOCR(float var1, float var2, float var3) {
      super.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var1, var2, var3, this.getHeight());
      this.IICRHHCRROHHHOORHIIRRHOIHCOCHO.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(var1 + var3 - 60.0F, var2);
      this.IIIOOCCIRCCOIROOCROORHHHHRCHRR.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH(var1 + var3 - 22.0F, var2);
   }

   @Override
   public float getHeight() {
      return this.getOption().isHidden() ? 0.0F : 14.0F;
   }

   @Override
   public void update() {
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      boolean var3
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RRHIRIIIROHHIORRHOIHCIRRCHHCOH()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, this.option.getName(), this.x, this.y + 1.5F, -4079426);
      this.IICRHHCRROHHHOORHIIRRHOIHCOCHO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
      this.IIIOOCCIRCCOIROOCROORHHHHRCHRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IOIHCHOOHORCORHHHCHCORHORHCOOC()
         .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, this.option.get().toString(), this.x + this.width - 34.0F, this.y + 2.5F, -1346256706);
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      char var1, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
   }

   @Override
   public void close() {
   }
}
