package com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.Set;
import lombok.Generated;

public abstract class HICRRICCHCCROOHHCHOCOCCHOIHHOC<T extends com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI<?>>
   extends ICICIOCHHHIHOCHCOHORIHRCOHHOCR<T> {
   protected HHCCIRHCCCIIRHCROHIORHIRHHIORH HRHHHOCHOCRROCRCHHOORHHHRIIOHO;

   public HICRRICCHCCROOHHCHOCOCCHOIHHOC(
      T var1, com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      super((T)var1, var2);
   }

   public void CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      if ((
            !(this.option instanceof com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH)
               || !this.option.get().equals("NONE")
         )
         && (
            !(this.option instanceof com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH)
               || !((com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.ICICIOCHHHIHOCHCOHORIHRCOHHOCR)this.option.get())
                  .ICOHRHCIHIIOOHRHRICHIHOCCHHCRC()
                  .equals(com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NONE)
         )
         && (
            !(this.option instanceof com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHRIICOIOORCHCOIICOOIHIRHHICRI)
               || !((com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHRIICOIOORCHCOIICOOIHIRHHICRI)this.option)
                  .IHRICIIHICOOOIHIRIRCRHHHIHOROO()
                  .get()
                  .equals(com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NONE)
         )) {
         Set var3;
         if (this.option instanceof com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OIHCOHRCICCCRHRCROOCIOIRRHHHIH var4) {
            var3 = var4.RHCOIHCIIROIHIIRIIIHCRROICROHH();
         } else if (this.option instanceof com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHRIICOIOORCHCOIICOOIHIRHHICRI var5) {
            var3 = var5.IHRICIIHICOOOIHIRIRCRHHHIHOROO().RHCOIHCIIROIHIIRIIIHCRROICROHH();
         } else {
            var3 = null;
         }

         if (var3 != null && !var3.isEmpty()) {
            String var7 = this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
               "clashesWith",
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RED
                  + IICCOOCHCHROORHHIIHROHCCRHRCOR.CRRRICCRROCOHHOHIICIHORCOORRRH(var3, this.option.getId())
            );
            float var8 = com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.OCOHICCCCIROOROOOIRHRRHICOIORC()
               .IOOOHRRHCHICHHHCRIRHIICORRCIRO(var7);
            var1.CRICCOOHHHCHOORCICOCOHIHOIRHOO(0.0F, 0.0F, 100.0F);
            com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               var1,
               (float)(var2.ICORIROICCORCRROCRCIRRRHHHOOIR() + 8.0),
               (float)(var2.OICOHRRRRCOICCHOIOROHOCOORCHII() + 6.0),
               var8 + 10.0F,
               14.0F,
               4.0F,
               -1879048192
            );
            com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.OCOHICCCCIROOROOOIRHRRHICOIORC()
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1, var7, (float)(var2.ICORIROICCORCRROCRCIRRRHHHOOIR() + 12.5), (float)(var2.OICOHRRRRCOICCHOIOROHOCOORCHII() + 9.0), -1
               );
            var1.CRICCOOHHHCHOORCICOCOHIHOIRHOO(0.0F, 0.0F, -100.0F);
         }
      }
   }

   @Generated
   public HHCCIRHCCCIIRHCROHIORHIRHHIORH RRIROCOIRCIIIHCIORRHOOOHHOOIIC() {
      return this.HRHHHOCHOCRROCRCHHOORHHHRIIOHO;
   }
}
