package com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import lombok.Generated;
import org.jetbrains.annotations.Nullable;

public class IHICORCROOROHCIHIHCOIHRRHICICO<T extends Number & Comparable<T>>
   extends ICICIOCHHHIHOCHCOHORIHRCOHHOCR<com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI<T>>
   implements com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH {
   protected final OHIIIOHIRIRCCRRIOIICCHHIORRHOH<T> ICOOCRCOICOHIOCORICCCCHCOCCOHO;
   protected final RHRRHOHCRCHCCRRHOHHIRCCHOCICHC RRRROROOOOOHCCIIIHIORCOOCIHRRR;
   @Nullable
   protected final OHHRIOHROOIHOROCIRHCHORIHRRRRI OHHIRHHCOIRICCRCROCHICIHRCRCRI;
   protected boolean RHCHIIHIHIRCRIRHRCIRIIOROOOHOC = true;

   public IHICORCROOROHCIHIHCOIHRRHICICO(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI<T> var1,
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      this(var1, var2, true);
   }

   public IHICORCROOROHCIHIHCOIHRRHICICO(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI<T> var1,
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      boolean var3
   ) {
      super(var1, var2);
      this.ICOOCRCOICOHIOCORICCCCHCOCCOHO = new OHIIIOHIRIRCCRRIOIICCHHIORRHOH<>(var1, this);
      this.OHHIRHHCOIRICCRCROCHICIHRCRCRI = var3
         ? new OHHRIOHROOIHOROCIRHCHORIHRRRRI(
            this,
            "resetToDefaults",
            com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.COHIOCOOOORHIOOROCIIHHIIHOOCHR
         )
         : null;
      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR = new RHRRHOHCRCHCCRRHOHHIRCCHOCICHC(this, this.option.getValueAsString());
      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.IIOCHOIICCIORCOROIROHICCHIOHIC(this.RRRROROOOOOHCCIIIHIORCOOCIHRRR::getText);
      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR
         .IOHIHIIHCCCCCIHRORIOIOORCIOHII(
            var1x -> {
               int var2x = var1x.indexOf(46);
               if (var2x >= 0) {
                  int var3x = var1x.indexOf(46, var2x + 1);
                  if (var3x >= 0) {
                     return;
                  }
               }

               var1x = (var1x.startsWith("-") ? "-" : "") + var1x.replaceAll("[^0-9.]", "");
               var1x = com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.OHOCCRHCROCIHHCRRRROOHROHOROIC
                  .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1x, 50.0);
               this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.HICRRICCHCCROOHHCHOCOCCHOIHHOC(var1x, true);
               this.CICCCORIIOOOIIHOHRICCIHRHHIHOH();
            }
         );
      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(var1x -> {
         if (!var1x) {
            this.RORRIRRCIOCRHIIOCHCIORCHRROHOR();
         }
      });
      if (this.OHHIRHHCOIRICCRCROCHICIHRCRCRI != null) {
         this.OHHIRHHCOIRICCRCROCHICIHRCRCRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var1x, var2x) -> {
            this.HIORHORHOICHRHORRRCOORHIIICIIR();
            return true;
         });
      }

      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this::HHRIICOIOORCHCOIICOOIHIRHHICRI);
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         (var1x, var2x) -> {
            if (this.RHCHIIHIHIRCRIRHRCIRIIOROOOHOC
               && this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.isActive()
               && !this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1x)) {
               this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.RRCRRCORICCHOHHIRCHIROOHIIOHCO(() -> false);
               this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.RHCHICHORHCRCCRCIRCRCIHOOCIOHC().accept(false);
            }

            return false;
         }
      );
   }

   protected boolean HHRIICOIOORCHCOIICOOIHIRHHICRI(
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1, int var2
   ) {
      if (this.ICOOCRCOICOHIOCORICCCCHCOCCOHO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1)) {
         return this.ICOOCRCOICOHIOCORICCCCHCOCCOHO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1, var2);
      }

      if (this.OHHIRHHCOIRICCRCROCHICIHRCRCRI != null && this.OHHIRHHCOIRICCRCROCHICIHRCRCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1)) {
         return this.OHHIRHHCOIRICCRCROCHICIHRCRCRI.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1, var2);
      }

      if (this.RHCHIIHIHIRCRIRHRCIRIIOROOOHOC && this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.isActive()) {
         if (this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1)) {
            this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var1, var2);
            return true;
         } else {
            this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.RRCRRCORICCHOHHIRCHIROOHIIOHCO(() -> false);
            this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.RHCHICHORHCRCCRCIRCRCIHOOCIOHC().accept(false);
            return true;
         }
      } else if (this.RHCHIIHIHIRCRIRHRCIRIIOROOOHOC
         && this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1)
         && !this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.isActive()) {
         this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.HICRRICCHCCROOHHCHOCOCCHOIHHOC(this.option.getValueAsString(), true);
         this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.RHCHICHORHCRCCRCIRCRCIHOOCIOHC().accept(true);
         this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.RRCRRCORICCHOHHIRCHIROOHIIOHCO(() -> true);
         this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.setActive(true);
         return true;
      } else {
         return false;
      }
   }

   @Override
   public void IRRCCOICORICIHCHRHIHIHROIRHOCR(float var1, float var2, float var3) {
      super.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1, var2, var3 + 8.0F);
      float var4 = com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.OHOIIIRRIHCRIRRCHHIRIOROHIIHIO()
            .IOOOHRRHCHICHHHCRIRHIICORRCIRO(this.option.getName())
         + this.ICOOOORIOICOOORHRIIHRHCOHRHOCO()
         + 6.0F;
      float var5 = var3 - var3 / 3.0F;
      float var6 = var1 + var3 / 3.0F;
      if (var5 > var3 - (var4 + 15.0F)) {
         var5 = var3 - (var4 + 15.0F);
         var6 = var1 + var4 + 5.0F;
      }

      this.ICOOCRCOICOHIOCORICCCCHCOCCOHO
         .OHHRIOHROOIHOROCIRHCHORIHRRRRI(var6, var2, var5 - (this.OHHIRHHCOIRICCRCROCHICIHRCRCRI == null ? 0 : 10), this.height);
      if (this.OHHIRHHCOIRICCRCROCHICIHRCRCRI != null) {
         this.OHHIRHHCOIRICCRCROCHICIHRCRCRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var1 + var3 - 9.0F, var2 + 3.0F, 8.0F, 8.0F);
      }

      int var7 = Math.min((int)this.height, 12);
      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var6 - 20.0F, var2 + (this.height - var7) / 2.0F, 16.0F, var7);
      this.CICCCORIIOOOIIHOHRICCIHRHHIHOH();
   }

   private void RORRIRRCIOCRHIIOCHCIORCHRROHOR() {
      Number var1 = this.option.getDefaultValue();
      String var2 = this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.getText();

      Number var3;
      try {
         if (var1 instanceof Integer) {
            var3 = Integer.parseInt(var2);
         } else if (var1 instanceof Long) {
            var3 = Long.parseLong(var2);
         } else if (var1 instanceof Short) {
            var3 = Short.parseShort(var2);
         } else if (var1 instanceof Byte) {
            var3 = Byte.parseByte(var2);
         } else if (var1 instanceof Double) {
            var3 = Double.parseDouble(var2);
         } else {
            var3 = Float.parseFloat(var2);
         }
      } catch (NumberFormatException var5) {
         return;
      }

      this.option.OOCCCHRCIRHCRCIRHRHHCRIOHICRRC(var3.toString());
   }

   private void CICCCORIIOOOIIHOHRICCIHRHHIHOH() {
      float var1 = com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.OHOCCRHCROCIHHCRRRROOHROHOROIC
            .IOOOHRRHCHICHHHCRIRHIICORRCIRO(this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.getText())
         + 12.0F;
      if (var1 < 16.0F) {
         var1 = 16.0F;
      }

      if (var1 > 60.0F) {
         var1 = 60.0F;
      }

      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.IHRHHHORORIROOCORCIORRCOCHHHRI(var1);
      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.setX(this.ICOOCRCOICOHIOCORICCCCHCOCCOHO.getX() - 4.0F - var1);
      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.OCICOOCOOOIRCCORCOCIRCCRRHIHRC().OIIHROORCRORRRCOICCCHIOIHIHHRC(0);
   }

   private float ICOOOORIOICOOORHRIIHRHCOHRHOCO() {
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1 = this.option
         .RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CHOCCRCCIRIHOROCHHICOHHHOICHHH
         );
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RICCOIRRCIHROCHIRIOCRHICIHRCRC();
      return Math.max(
         var2.IOOOHRRHCHICHHHCRIRHIICORRCIRO(var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((T)var1.getMin())),
         var2.IOOOHRRHCHICHHHCRIRHIICORRCIRO(var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((T)var1.getMax()))
      );
   }

   @Override
   public float getHeight() {
      return this.getOption().isHidden() ? 0.0F : 14.0F;
   }

   @Override
   public void update() {
      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.update();
      this.ICOOCRCOICOHIOCORICCCCHCOCCOHO.update();
      if (this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.isActive() && !this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.OOIROOORICRIOHHROHORHIHCCRHORC().getAsBoolean()) {
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHCICHRICRIIIHRRCICHOOOIOOOICH()
            .IHIRRIIORRHORHRORIHOROIRCORCOO(false);
         this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.setActive(false);
      }
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      boolean var3
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.OHOIIIRRIHCRIRRCHHIRIOROHIIHIO()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, this.option.getName(), this.x, this.y + 1.5F, -4079426);
      this.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var1, var2, var3);
      this.ICOOCRCOICOHIOCORICCCCHCOCCOHO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
      if (this.OHHIRHHCOIRICCRCROCHICIHRCRCRI != null && !this.option.isDefault()) {
         this.OHHIRHHCOIRICCRCROCHICIHRCRCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
      }
   }

   protected void HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      boolean var3
   ) {
      if (this.RHCHIIHIHIRCRIRHRCIRIIOROOOHOC && this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.isActive()) {
         this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
      } else {
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4 = com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RICCOIRRCIHROCHIRIOCRHICIHRCRC();
         String var5 = this.option.getValueAsString();
         float var6 = var4.IOOOHRRHCHICHHHCRIRHIICORRCIRO(var5);
         var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1, var5, this.ICOOCRCOICOHIOCORICCCCHCOCCOHO.getX() - 8.0F - var6, this.y + this.height / 2.0F - var4.getHeight() / 2 - 2.0F, -1879048193
         );
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      char var1, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2);
   }

   @Override
   public boolean isEditing() {
      return this.RRRROROOOOOHCCIIIHIORCOOCIHRRR.isActive();
   }

   @Override
   public void close() {
   }

   @Generated
   public OHIIIOHIRIRCCRRIOIICCHHIORRHOH<T> OIOOCORCHROOHRRICIIIOHROOORIIR() {
      return this.ICOOCRCOICOHIOCORICCCCHCOCCOHO;
   }

   @Generated
   public boolean RRROROOIIRRCHOHORRRCROHCORRROO() {
      return this.RHCHIIHIHIRCRIRHRCIRIIOROOOHOC;
   }

   @Generated
   public void RROHCHORHCHCCRIHIIOHHIOORHCCCC(boolean var1) {
      this.RHCHIIHIHIRCRIRHRCIRIIOROOOHOC = var1;
   }
}
