package com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import lombok.Generated;
import org.jetbrains.annotations.NotNull;

public class RHOCHHIRRCHHHOHOIRROIROHHHIHIO
   extends com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RHORIIRCHOHHOCOOCICHOCRCOCRIOO = new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      -1593835521, -1
   );
   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC OOIOHHIRCRHCHHOOICOCORRIIROHIH;
   private final String ORORCICHCHCICORHIHCICHHOIIRHHC;
   private boolean textShadow = false;

   public RHOCHHIRRCHHHOHOIRROIROHHHIHIO(
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      String var2,
      @NotNull RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
   ) {
      super(var1);
      this.ORORCICHCHCICORHIHCICHHOIIRHHC = var2;
      this.OOIOHHIRCRHCHHOOICOCORRIIROHIH = var3;
   }

   @Override
   public void update() {
   }

   @Override
   public void close() {
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      char var1, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      boolean var3
   ) {
      boolean var4 = var3 && this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2);
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         var1,
         this.OOIOHHIRCRHCHHOOICOCORRIIROHIH,
         this.x,
         this.y + this.height / 2.0F - 4.0F,
         8.0F,
         8.0F,
         this.RHORIIRCHOHHOCOOCICHOCRCOCRIOO.CCRCIRCCOCHRCROCCOIORCIOHROCRH(var4)
      );
      var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0 -> {
         var0.HHIIOHOORHHCCHRHHRCIORCROORCOI().OIIHIOIORRHHRCRRCCORRHHCHRHORH();
         var0.HHIIOHOORHHCCHRHHRCIORCROORCOI().OIOIICCHICHHHCRROHIHIOICHROOCR();
      });
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR(),
         this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(this.ORORCICHCHCICORHIHCICHHOIIRHHC),
         this.x + 11.0F,
         this.y + this.height / 2.0F - 4.0F,
         this.RHORIIRCHOHHOCOOCICHOCRCOCRIOO.CCRCIRCCOCHRCROCCOIORCIOHROCRH(var4),
         this.textShadow
      );
      this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1, var2, var3);
      if (this.ORORCICHCHCICORHIHCICHHOIIRHHC.isEmpty()) {
         this.width = 8.0F;
      } else {
         this.width = 11.0F + IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR().bridge$getStringWidth(this.ORORCICHCHCICORHIHCICHHOIIRHHC);
      }
   }

   @Generated
   public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      this.RHORIIRCHOHHOCOOCICHOCRCOCRIOO = var1;
   }

   @Generated
   public void RHRRHOHCRCHCCRRHOHHIRCCHOCICHC(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1
   ) {
      this.OOIOHHIRCRHCHHOOICOCORRIIROHIH = var1;
   }

   @Generated
   public void ICRCOOIHHHRCCROCCRIRCIOCIRIHIH(boolean var1) {
      this.textShadow = var1;
   }
}
