package com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class RIRHOCHIORCCIIOIIRHOCCCRHHCHHH<T extends Enum<T> & com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.ORHIOICIOCRRHOOCOHRORIHICHRCRR>
   extends ICICIOCHHHIHOCHCOHORIHRCOHHOCR<com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI<T>> {
   private static final com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH IHCHHOOCIORRHRHIHOCORIHOHCRHIO = com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RHRHORICHRHIHIHORRHRCHHIRIHRRH;
   private static final int HCCIHCIHHOICHCRCOOCCOIHCHIRROH = 10;
   private final List<Enum<T>> OHORICIIRCCICIIRIOOOCCIOIHOIHO = new ArrayList<>();
   private final List<com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> OCIIIHHIIHROCHICCCHOOCHICHIHHR = new ArrayList<>();
   private final List<com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> RRHHRIOHCIHRHCIHOIRHCHHIIIRRHO = new ArrayList<>();

   public RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI<T> var1,
      com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      super(var1, var2);
      Class var3 = ((Enum)var1.get()).getClass();
      Enum[] var4 = (Enum[])var3.getEnumConstants();

      for (Enum var8 : var4) {
         this.OHORICIIRCCICIIRIOOOCCIOIHOIHO.add(var8);
         this.OCIIIHHIIHROCHICCCHOOCHICHIHHR
            .add(
               new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  553648127, -1593835521
               )
            );
         this.RRHHRIOHCIHRHCIHOIRHCHHIIIRRHO
            .add(
               new com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  553648127, 1174405119
               )
            );
      }

      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var2x, var3x) -> {
         float var4x = (this.width - 10 * (this.OHORICIIRCCICIIRIOOOCCIOIHOIHO.size() - 1)) / this.OHORICIIRCCICIIRIOOOCCIOIHOIHO.size();
         int var5 = (int)((var2x.ICORIROICCORCRROCRCIRRRHHHOOIR() - this.x) / (var4x + 10.0F));
         if (var5 >= 0 && var5 < this.OHORICIIRCCICIIRIOOOCCIOIHOIHO.size()) {
            if ((var2x.ICORIROICCORCRROCRCIRRRHHHOOIR() - this.x) % (var4x + 10.0F) > var4x) {
               return false;
            }

            var1.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH((T)this.OHORICIIRCCICIIRIOOOCCIOIHOIHO.get(var5));
            return true;
         } else {
            return false;
         }
      });
   }

   @Override
   public void IRRCCOICORICIHCHRHIHIHROIRHOCR(float var1, float var2, float var3) {
      super.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var1, var2, var3, this.getHeight());
   }

   @Override
   public float getHeight() {
      return this.getOption().isHidden() ? 0.0F : 15.0F;
   }

   @Override
   public void update() {
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2,
      boolean var3
   ) {
      float var4 = (this.width - 10 * (this.OHORICIIRCCICIIRIOOOCCIOIHOIHO.size() - 1)) / this.OHORICIIRCCICIIRIOOOCCIOIHOIHO.size();
      var3 = var3 && this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2);
      float var5 = this.y + 2.0F;
      float var6 = this.x;

      for (int var7 = 0; var7 < this.OHORICIIRCCICIIRIOOOCCIOIHOIHO.size(); var7++) {
         Enum var8 = this.OHORICIIRCCICIIRIOOOCCIOIHOIHO.get(var7);
         boolean var9 = var8 == this.getOption().get();
         boolean var10 = var3 && var2.COCCOIROHORRRHIHICORRHRRORIIIH() > var6 && var2.COCCOIROHORRRHIHICORRHRRORIIIH() < var6 + var4;
         int var11 = this.OCIIIHHIIHROCHICCCHOOCHICHIHHR.get(var7).CCRCIRCCOCHRCROCCOIORCIOHROCRH(var9);
         int var12 = this.RRHHRIOHCIHRHCIHOIRHCHHIIIRRHO.get(var7).CCRCIRCCOCHRCROCCOIORCIOHROCRH(var10);
         com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1, var6, var5, var4, this.height - 3.0F, 4.0F, 1076176165, var11, var12
         );
         String var13 = var8.toString().toUpperCase(Locale.ROOT).replace("", " ").trim();
         float var14 = (int)(var6 + var4 / 2.0F - IHCHHOOCIORRHRHIHOCORIHOHCRHIO.IOOOHRRHCHICHHHCRIRHIICORRCIRO(var13) / 2.0F);
         float var15 = (int)(var5 + (this.height - 3.0F) / 2.0F - IHCHHOOCIORRHRHIHOCORIHOHCRHIO.getHeight());
         IHCHHOOCIORRHRHIHOCORIHOHCRHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var13, var14 + 1.0F, var15 + 1.0F, 536870912);
         IHCHHOOCIORRHRHIHOCORIHOHCRHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var13, var14, var15, -4275267);
         var6 += var4 + 10.0F;
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      char var1, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
   }

   @Override
   public void close() {
   }

   @Override
   public boolean RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      return false;
   }
}
