package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RORCHCIIICOHIRROOORHOCCCCIOCCI;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH;
import com.moonsworth.lunar.lib.adventure.text.Component;
import com.moonsworth.lunar.lib.adventure.text.TextComponent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   public static final Set<String> ICHCRHCIRCHCRIIHHCICIROCOOCHRC = Set.of(
      "Decoy",
      "Defuse Kit",
      "Dungeon Chest Key",
      "Health Potion VIII",
      "Inflatable Jerry",
      "Spirit Leap",
      "Training Weights",
      "Trap",
      "Treasure Talisman",
      "Revive Stone",
      "Candycomb",
      "Secret Dye"
   );
   private static final List<IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> HHIIOCCROIROHIOCOIIHHCORRICOIH = new ArrayList<>();
   private static int HOHRORCRIIRHIROCHHCHIIIICOCIHH = 0;
   private static com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH CCIIOOIIORCHOCOHCOIROOICHHOHCI = null;

   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(OCOHORHCROHICRRIHCIHHRRCIHICRI var0, RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1) {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
      List var3 = var2.ORHIIOCHCRCORICHRHIOROCCRHIRIR();
      var2.HOIOCHRCHCOOHIOIOHOHOCOROHOOOH().forEach(var4 -> var2.HHRICHOIIRHICRHCOCRRROHHHCRIRR().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, var4, var3));
      var2.IOIICIHRHIRIHIHHCCRHOOIROROOOH()
         .ifPresent(
            var4 -> var4.OCHCROIHOHRHCCRIIRRHIOCHIOCICR()
               .forEach(var4x -> var2.HHRICHOIIRHICRHCOCRRROHHHCRIRR().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, var4x, var3))
         );
   }

   public static void ORCOOCHRICHOIHHIHIOHCHCRIOHRCR() {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var0 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      if (var0 == null) {
         HCOHIRIRHIHIOIIROORORCROCHHHIR();
      } else if (IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH() != null) {
         HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var1.CHIHHROCIHRROCOIOROOOOROIHCIOR()
            .orElse(null);
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var4 = var3
               != null
            ? var3.HRHHIRHRICRCOCOHICCIROOCCCCIOH().orElse(null)
            : null;
         if (var3 != CCIIOOIIORCHOCOHCOIROOICHHOHCI) {
            CCIIOOIIORCHOCOHCOIROOICHHOHCI = var3;
            HCOHIRIRHIHIOIIROORORCROCHHHIR();
         }

         var1.IIICOOCRROIRCIICCOHCOCICCCHCOH().ORCOOCHRICHOIHHIHIOHCHCRIOHRCR();
         HOHRORCRIIRHIROCHHCHIIIICOCIHH++;
         if (HOHRORCRIIRHIROCHHCHIIIICOCIHH > 100) {
            var1.IICRROHCCICIHROCIOIROOCIHIHOOI();
            HOHRORCRIIRHIROCHHCHIIIICOCIHH = 0;
         }

         if (HOHRORCRIIRHIROCHHCHIIIICOCIHH % 5 == 0) {
            var1.HOIOCHRCHCOOHIOIOHOHOCOROHOOOH().forEach(var1x -> var1.HHRICHOIIRHICRHCOCRRROHHHCRIRR().HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var1x));
            var1.IOIICIHRHIRIHIHHCCRHOOIROROOOH()
               .ifPresent(
                  var1x -> var1x.OCHCROIHOHRHCCRIIRRHIOCHIOCICR()
                     .forEach(var1xx -> var1.HHRICHOIIRHICRHCOCRRROHHHCRIRR().HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var1xx))
               );
            if (!var1.IIICOOCRROIRCIICCOHCOCICCCHCOH().HOCIOCRCIORCHRRHOHHOOOHIOIRIHH() && var4 != null) {
               var1.HOIOCHRCHCOOHIOIOHOHOCOROHOOOH()
                  .forEach(
                     var4x -> {
                        if (!var4x.OCOCCOROHRHIRHRRCRCRCOOCHHROIO().isEmpty()) {
                           com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var5x = var4x.OCOCCOROHRHIRHRRCRCRCOOCHHROIO()
                              .get(var4x.OCOCCOROHRHIRHRRCRCRCOOCHHROIO().size() - 1);
                           com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var6x = (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var5x.OHICIOOICHICOIOCOROIIOCCHRRCIC;
                           boolean var7x = var6x
                              == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SKULL;
                           if (var6x
                                 == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ITEM_DROP
                              || var7x) {
                              int[] var8 = var4.OCOHORHCROHICRRIHCIHHRRCIHICRI((int[])var5x.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC);
                              double var9 = Math.pow(var2.bridge$getPosX() - var8[0], 2.0)
                                 + Math.pow(var2.bridge$getPosY() - var8[1], 2.0)
                                 + Math.pow(var2.bridge$getPosZ() - var8[2], 2.0);
                              if (var9 < 25.0) {
                                 if (var7x) {
                                    com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var11 = var0.bridge$getBlockState(
                                       var8[0], var8[1], var8[2]
                                    );
                                    if (!var11.bridge$getBlock().bridge$isAir()) {
                                       return;
                                    }
                                 }

                                 var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var8, var7x);
                              }
                           }
                        }
                     }
                  );
            }
         }

         Iterator var5 = HHIIOCCROIROHIOCOIIHHCORRICOIH.iterator();

         while (var5.hasNext()) {
            IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 = (IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var5.next();
            if (var6.RCCRHIHCCOCOCIHIHIIOCICOIIHCCH().bridge$isRemoved()) {
               var5.remove();
               int[] var7 = new int[]{(int)Math.floor(var2.bridge$getPosX()), (int)var2.bridge$getPosY(), (int)Math.floor(var2.bridge$getPosZ())};
               RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var7, var6.ICIRCOOHHOHCIHHRIOHHHHCCOCRORI());
            }
         }
      }
   }

   public static void HCOHIRIRHIHIOIIROORORCROCHHHIR() {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var0 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
      if (var0.IIICOOCRROIRCIICCOHCOCICCCHCOH().HOCIOCRCIORCHRRHOHHOOOHIOIRIHH()) {
         var0.IIICOOCRROIRCIICCOHCOCICCCHCOH().RHHOOIROCRIIIHIHHHRCRIRCCRRHHO();
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH() != null) {
            TextComponent var1 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.asAdventure(
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                  "cancelledNotInRoom",
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.AQUA,
                  com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RED
               )
            );
            IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH().HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
         }
      }

      var0.IIICOHORORRCROHCHOROOCCCIRIRRC();
      var0.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(null);
   }

   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var0, String var1
   ) {
      if (var1.equals("DUNGEONBREAKER")
         && IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH().CIOHHCORHRCCRICCCORIHCRHCCCRRR(var0)
            != com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII()
               .CHHOOCORICIHCOHRRCOIRRCIOORRIC()) {
         IHIRRIIORRHORHRORIHOROIRCORCOO(var0);
      }
   }

   public static void IHIRRIIORRHORHRORIHOROIRCORCOO(RORCHCIIICOHIRROOORHOCCCCIOCCI var0) {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
      int[] var2 = new int[]{var0.bridge$getX(), var0.bridge$getY(), var0.bridge$getZ()};
      var1.IIICOOCRROIRCIICCOHCOCICCCHCOH()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.BREAK_BLOCK
         );
      var1.IIICOOCRROIRCIICCOHCOCICCCHCOH()
         .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DUNGEONBREAKER
         );
      var1.IRRCCOICORICIHCHRHIHIHROIRHOCR(var2);
   }

   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(RORCHCIIICOHIRROOORHOCCCCIOCCI var0, String var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      if (var2 != null) {
         HHCCIRHCCCIIRHCROHIORHIRHHIORH var3 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
         if (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.IOHOHIHHHOOHOOHRRIOCRIRRORICIO(
            var1
         )) {
            var3.IIICOOCRROIRCIICCOHCOCICCCHCOH().IIICORHHOORHIRRIIRCCOHIRRHOHCI();
         }

         if (var0 != null) {
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH()
               .OCOHORHCROHICRRIHCIHHRRCIHICRI(var0);
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = var4.bridge$getBlock();
            int[] var6 = new int[]{var0.bridge$getX(), var0.bridge$getY(), var0.bridge$getZ()};
            if (var5.bridge$isAnyChest()) {
               var3.IIICOOCRROIRCIICCOHCOCICCCHCOH()
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var6,
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CHEST
                  );
               var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, true);
            }

            if (var5.bridge$isSkull()) {
               var3.IIICOOCRROIRCIICCOHCOCICCCHCOH()
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var6,
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.SKULL
                  );
               var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, true);
            }

            if (var5
               == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCHCOROOHHCIHOHOCHIHRHOHOCROII()
                  .RORHCCHIOORIROORRHOCRHHOCRIHII()) {
               var3.IIICOOCRROIRCIICCOHCOCICCCHCOH()
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var6,
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.LEVER
                  );
               var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var6);
            }

            if (var5.bridge$isMushroom()) {
               var3.IIICOOCRROIRCIICCOHCOCICCCHCOH()
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     var6,
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.MUSHROOM
                  );
               var3.IRRCCOICORICIHCHRHIHIHROIRHOCR(var6);
            }
         }
      }
   }

   public static void OCIROOIHIHRHOCCHIIIROOCRIIOCRR(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var0
   ) {
      if (var0 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1
         )
       {
         Component var2 = var1.bridge$getCustomName();
         if (var2 != null) {
            String var3 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.getTextContent(
               var1.bridge$getCustomName()
            );

            for (String var5 : ICHCRHCIRCHCRIIHHCICIROCOOCHRC) {
               if (var3.contains(var5)) {
                  HRCOCHHHCCIORCORCHIOOOCCCCHICH(var0);
               }
            }
         }
      }
   }

   public static void HRCOCHHHCCIORCORCHIOOOCCCCHICH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var0
   ) {
      int[] var1 = new int[]{(int)var0.bridge$getPosX(), (int)var0.bridge$getPosY(), (int)var0.bridge$getPosZ()};
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
      var2.IIICOOCRROIRCIICCOHCOCICCCHCOH()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ITEM_DROP
         );
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var2.CHIHHROCIHRROCOIOROOOOROIHCIOR()
         .orElse(null);
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var4 = var3
            != null
         ? var3.HRHHIRHRICRCOCOHICCIROOCCCCIOH().orElse(null)
         : null;
      if (!var2.IIICOOCRROIRCIICCOHCOCICCCHCOH().HOCIOCRCIORCHRRHOHHOOOHIOIRIHH() && var4 != null) {
         int[][] var5 = new int[][]{null};
         double[] var6 = new double[]{100.0};
         var2.HOIOCHRCHCOOHIOIOHOHOCOROHOOOH()
            .forEach(
               var4x -> {
                  if (!var4x.OCOCCOROHRHIRHRRCRCRCOOCHHROIO().isEmpty()) {
                     com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var5x = var4x.OCOCCOROHRHIRHRRCRCRCOOCHHROIO()
                        .get(var4x.OCOCCOROHRHIRHRRCRCRCOOCHHROIO().size() - 1);
                     if (var5x.OHICIOOICHICOIOCOROIIOCCHRRCIC
                        == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ITEM_DROP
                        )
                      {
                        int[] var6x = var4.OCOHORHCROHICRRIHCIHHRRCIHICRI((int[])var5x.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC);
                        double var7 = Math.pow(var1[0] - var6x[0], 2.0) + Math.pow(var1[1] - var6x[1], 2.0) + Math.pow(var1[2] - var6x[2], 2.0);
                        if (var7 < var6[0]) {
                           var5[0] = var6x;
                           var6[0] = var7;
                        }
                     }
                  }
               }
            );
         if (var5[0] == null) {
            var2.IRRCCOICORICIHCHRHIHIHROIRHOCR(var1);
         } else {
            var2.IRRCCOICORICIHCHRHIHIHROIRHOCR(var5[0]);
         }
      }
   }

   public static void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(IIRHCHHOICHRICOOCRORCCIOOIHOIR var0) {
      String var1 = var0.HOHHIHRHOHIIHRHCHHIRORRRCOIHCC().bridge$getPath();
      if (var0.getVolume() == 1.0F
         && RHRIIOOOCRHIIOORCOCRCHRCCRRCIH.IHICORCROOROHCIHIHCOIHRRHICICO(var0.getPitch(), 0.53968, 1.0E-4)
         && (var1.equals("mob.enderdragon.hit") || var1.equals("entity.ender_dragon.hurt") || var1.equals("entity.enderdragon.hurt"))) {
         int[] var2 = new int[]{
            Math.round(var0.HIIRCCHHCIHROHCRICCOCIHRRHCRIH()) - 1,
            (int)var0.CICHIHIRRIRIICHCOCHIIOIIHRHROR() - 1,
            Math.round(var0.CIROCOHOCRHOHCCRIHIRHOICHRIRIR()) - 1
         };
         IIRHCHHOICHRICOOCRORCCIOOIHOIR(var2);
      }

      if (var0.getVolume() == 1.0F
         && var0.getPitch() != 1.0F
         && var0.getPitch() > 0.76
         && (var1.equals("random.explode") || var1.equals("entity.generic.explode"))) {
         int[] var3 = new int[]{
            Math.round(var0.HIIRCCHHCIHROHCRICCOCIHRRHCRIH()) - 1,
            (int)var0.CICHIHIRRIRIICHCOCHIIOIIHRHROR(),
            Math.round(var0.CIROCOHOCRHOHCCRIHIRHOICHRIRIR()) - 1
         };
         OHHRIOHROOIHOROCIRHCHORIHRRRRI(var3);
      }

      if (var1.equals("mob.bat.death") || var1.equals("entity.bat.death")) {
         int[] var4 = new int[]{
            Math.round(var0.HIIRCCHHCIHROHCRICCOCIHRRHCRIH()) - 1,
            (int)var0.CICHIHIRRIRIICHCOCHIIOIIHRHROR(),
            Math.round(var0.CIROCOHOCRHOHCCRIHIRHOICHRIRIR()) - 1
         };
         RHOCHHIRRCHHHOHOIRROIROHHHIHIO(var4);
      }
   }

   public static void ORRIIRHHCRCICRHIHCIRRIRORIICHI() {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var0 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
      var0.ORRIIRHHCRCICRHIHCIRRIRORIICHI();
   }

   public static void RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var0
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var2 = var0.OCOIORCRROIOOCHORHHHROCHCCIHRR;
      if (var2 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
         && var1 != null) {
         if (!(var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1) > 25.0)) {
            HHCCIRHCCCIIRHCROHIORHIRHHIORH var3 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
            var3.IIICOOCRROIRCIICCOHCOCICCCHCOH()
               .CCRRHORIICRIOHRCICRIHRIOHCHRIR()
               .ifPresent(var1x -> HHIIOCCROIROHIOCOIIHHCORRICOIH.add(new IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var1x)));
         }
      }
   }

   private static void IIRHCHHOICHRICOOCRORCCIOOIHOIR(int[] var0) {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
      var1.IIICOOCRROIRCIICCOHCOCICCCHCOH()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var0,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ETHERWARP
         );
      var1.IRRCCOICORICIHCHRHIHIHROIRHOCR(var0);
   }

   private static void OHHRIOHROOIHOROCIRHCHORIHRRRRI(int[] var0) {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
      var1.IIICOOCRROIRCIICCOHCOCICCCHCOH()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var0,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.TNT
         );
      var1.IRRCCOICORICIHCHRHIHIHROIRHOCR(var0);
   }

   private static void RHOCHHIRRCHHHOHOIRROIROHHHIHIO(int[] var0) {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
      var1.IIICOOCRROIRCIICCOHCOCICCCHCOH()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var0,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.BAT
         );
      var1.IRRCCOICORICIHCHRHIHIHROIRHOCR(var0);
   }

   private static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(int[] var0, HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1) {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HORCOCRHHOIIOCCIRRHHRCORCCHIIO().CORCCCIRRHHRHHCIIIHCOCCHRHCORC();
      var2.IIICOOCRROIRCIICCOHCOCICCCHCOH()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var0,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.PEARL,
            var1
         );
      var2.IRRCCOICORICIHCHRHIHIHROIRHOCR(var0);
      var2.IIICOOCRROIRCIICCOHCOCICCCHCOH().RIIIHICIIICIIIHIHHHIOCCCOHCRRC();
   }

   private record RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      private final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH OICHHOCICHCIIOCHRIIRRHRHRIIIIR;
      private final HRCHROOHRIHCRCRHRIIROCIRHOIRHH OICHHOHCIHROHHCRCIICIIRRCCICIH;

      private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         HRCHROOHRIHCRCRHRIIROCIRHOIRHH var2
      ) {
         this.OICHHOCICHCIIOCHRIIRRHRHRIIIIR = var1;
         this.OICHHOHCIHROHHCRCIICIIRRCCICIH = var2;
      }

      public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH RCCRHIHCCOCOCIHIHIIOCICOIIHCCH() {
         return this.OICHHOCICHCIIOCHRIIRRHRHRIIIIR;
      }

      public HRCHROOHRIHCRCRHRIIROCIRHOIRHH ICIRCOOHHOHCIHHRIOHHHHCCOCRORI() {
         return this.OICHHOHCIHROHHCRCIICIIRRCCICIH;
      }
   }
}
