package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.google.common.hash.Hashing;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import java.io.DataInputStream;
import java.io.File;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import java.nio.ShortBuffer;
import java.nio.charset.StandardCharsets;
import org.apache.commons.lang3.StringUtils;
import org.lwjgl.actually3.BufferUtils;
import org.lwjgl.util.opus.Opus;

public class CRRRICCRROCOHHOHIICIHORCOORRRH extends IRCIIHHICIHRCOCRROCOICRIHHCCHH<DataInputStream> {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HCRHOHHIIRRICRRIOCIHRRHOHIRRIC;
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH OOICCCCIOORHOHICCIHCCHIORHOOOR;
   private long IOHIICCOHRHOOOHOCCIOOHORCHRHHC;

   public CRRRICCRROCOHHOHIICIHORCOORRRH(
      File var1,
      String var2,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var4
   ) {
      super(var1, var2, var3);
      this.HCRHOHHIIRRICRRIOCIHRRHOHIRRIC = var4;
      this.OOICCCCIOORHOHICCIHCCHIORHOOOR = IIRHCHHOICHRICOOCRORCCIOOIHOIR.ORHHIICRRIOIOHCHHCHHHRCIORCHRI
         .fromJson(
            var4.RICIORHICRROHOCHRRCRIHCROOCIIC("audio/" + this.IORCRHHOIOHORRCOHORCCICOICICRI + ".json"),
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class
         );
      this.init();
      this.RCHCORHROIIHHOCROIRHICHCOHICIR();
   }

   @Override
   public String getName() {
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .CCHHHHCICRCCCIOOIOICOOCRCRHCCR()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("rewind", "audio" + StringUtils.capitalize(this.IORCRHHOIOHORRCOHORCCICOICICRI));
   }

   @Override
   protected void RCHCORHROIIHHOCROIRHICHCOHICIR() {
      this.IORIROHCRCHRCOCHOOHRCIIIRIRHRH();
      super.RCHCORHROIIHHOCROIRHICHCOHICIR();
      Opus.opus_decoder_destroy(this.IOHIICCOHRHOOOHOCCIOOHORCHRHHC);
   }

   @Override
   protected void createSource() {
      super.createSource();
      this.IORIROHCRCHRCOCHOOHRCIIIRIRHRH();
   }

   private void IORIROHCRCHRCOCHOOHRCIIIRIRHRH() {
      IntBuffer var1 = BufferUtils.createIntBuffer(1);
      this.IOHIICCOHRHOOOHOCCIOOHORCHRHHC = Opus.opus_decoder_create(
         this.OOICCCCIOORHOHICCIHCCHIORHOOOR.getFrequency(), this.OOICCCCIOORHOHICCIHCCHIORHOOOR.getChannels(), var1
      );
      if (var1.get() != 0) {
         throw new RuntimeException("Failed to create Opus decoder: " + var1.get());
      }
   }

   protected DataInputStream HRRCRHICORHIRCHRRORROCOIRCIICC() {
      return this.HCRHOHHIIRRICRRIOCIHRRHOHIRRIC.RCHRHOCCORRRCRORCHIIRRIIIRRCRR("audio/" + this.IORCRHHOIOHORRCOHORCCICOICICRI + ".dat");
   }

   @Override
   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CIOOCOCIIOCROCHOIRIOIHOIHOIHRC() {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.getFormat(
         this.OOICCCCIOORHOHICCIHCCHIORHOOOR.getChannels(), this.OOICCCCIOORHOHICCIHCCHIORHOOOR.getBytesPerSample()
      );
   }

   @Override
   protected int IIHOICCRCIRHOOCCIRRORCCIROIIRO() {
      return this.OOICCCCIOORHOHICCIHCCHIORHOOOR.getFrequency();
   }

   @Override
   protected int OHCOICRCICRHIICOIROOHCCOCCRCHO() {
      return this.OOICCCCIOORHOHICCIHCCHIORHOOOR.getFrameSize();
   }

   @Override
   protected String OHRHRHCRHCRIIIHOHOCIORHCIIIICO() {
      return Hashing.md5().hashString(this.ICCOOHHCCHCHHOHOIRCHCOHRIOCCRO, StandardCharsets.UTF_8).toString();
   }

   @Override
   public long CHCRRCICCCHRHCCHICOCIIIHRORHIC() {
      return this.OOICCCCIOORHOHICCIHCCHIORHOOOR.CHCRRCICCCHRHCCHICOCIIIHRORHIC();
   }

   protected void IRCIIHHICIHRCOCRROCOICRIHHCCHH(DataInputStream var1) {
      for (int var2 = 0; var2 < this.OOICCCCIOORHOHICCIHCCHIORHOOOR.getChannels(); var2++) {
         int var3 = CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
         var1.skipBytes(var3);
      }
   }

   protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(DataInputStream var1, ByteBuffer var2, ShortBuffer var3) {
      int var4 = CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
      byte[] var5 = new byte[var4];
      int var6 = var1.read(var5);
      if (var6 == -1) {
         this.CHRHCRCCIICRORCOHCORHRROIHRCHO(true);
      } else {
         var2.clear();
         var2.put(var5);
         var2.flip();
         var3.clear();
         var3.limit(Opus.opus_decode(this.IOHIICCOHRHOOOHOCCIOOHORCHRHHC, var2, var3, this.OOICCCCIOORHOHICCIHCCHIORHOOOR.getFrameSize(), 0));
      }
   }

   @Override
   public void cleanup() {
      super.cleanup();
      Opus.opus_decoder_destroy(this.IOHIICCOHRHOOOHOCCIOOHORCHRHHC);
   }

   @Override
   public void reload() {
      Opus.opus_decoder_destroy(this.IOHIICCOHRHOOOHOCCIOOHORCHRHHC);
      super.reload();
   }

   @Override
   public IRCIIHHICIHRCOCRROCOICRIHHCCHH<DataInputStream> OCHRHCIIOCRRCHHIIROHCIOROOCHRC() {
      return new CRRRICCRROCOHHOHIICIHORCOORRRH(
         this.IOCRIIROIORICRHHIICCIHIOIRIOOO, this.ICCOOHHCCHCHHOHOIRCHCOHRIOCCRO, this.HIHHCRRHHORCOHOCIRCRHHICCCIIHO, this.HCRHOHHIIRRICRRIOCIHRRHOHIRRIC
      );
   }
}
