package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CIOHHCORHRCCRICCCORIHCRHCCCRRR;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import org.jetbrains.annotations.Nullable;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI OOROHHOIIHIHCCIIROIOOCCRRHCIHC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("rightClick")
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI CRCCHCHOCRROOHCORCCOOIIHIIROHR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("showCPSText")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HCHICORCHHOHCOCRHCIRICHCRHIHHO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("reverseText")
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI CHIOHRCOCICOOIIRCIOHICOORCRHOH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "ignoreCancelledClicks"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI HICICOHHCRCOCIHCRCICIOCRHOOIOH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("lineColor")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-14671840)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IORHORROCCHORCRORIRCIOHCRHHHRR = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class
   );

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO,
         new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            
         )
      );
      this.OOROHHOIIHIHCCIIROIOOCCRRHCIHC.IIOCHOIICCIORCOROIROHICCHIOHIC(var1 -> this.IORHORROCCHORCRORIRCIOHCRHHHRR.RHRIHIOCORRHHRRHOCIOCOHIIIHIOH());
   }

   @Override
   public String getId() {
      return "CPS";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SETTINGS,
         var1x -> {
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.OOROHHOIIHIHCCIIROIOOCCRRHCIHC, var1xx -> var1xx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HICICOHHCRCOCIHCRCICIOCRHOOIOH)
            );
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CRCCHCHOCRROOHCORCCOOIIHIIROHR);
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.HCHICORCHHOHCOCRHCIRICHCRHIHHO);
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CHIOHRCOCICOOIIRCIOHICOORCRHOH);
         }
      );
   }

   private class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends CRICCOOHHHCHOORCICOCOHIHOIRHOO<String> {
      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
         super(0.0F, 0.0F, RRCRRCORICCHOHHIRCHIROOHIIOHCO.TOP_LEFT);
      }

      @Override
      public HRCHROOHRIHCRCRHRIIROCIRHOIRHH HRRIHHICORIHCHICOHCCRCHCHOHRCH() {
         return HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(10, 18, 22, 40, 56, 62);
      }

      @Nullable
      public String HOHCCHOIOHOHHOROHOIIHOOHORRHRO(boolean var1) {
         String var2 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.OOROHHOIIHIHCCIIROIOOCCRRHCIHC.get() ? "  " : "";
         String var3 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.CRCCHCHOCRROOHCORCCOOIIHIIROHR.get() ? " " : "";
         String var4 = Integer.toString(
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
               "leftCPS",
               RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.IORHORROCCHORCRORIRCIOHCRHHHRR
                  .HORHCHIRIOIOOCOHOIRIRICICHIORH(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.CHIOHRCOCICOOIIRCIOHICOORCRHOH.get())
            )
         );
         String var5 = Integer.toString(
            RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
               "rightCPS", RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.IORHORROCCHORCRORIRCIOHCRHHHRR.RRRRIHIHICHHOICOCIHIRICORCIROC()
            )
         );
         if (!RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.OOROHHOIIHIHCCIIROIOOCCRRHCIHC.get()) {
            var5 = "";
         }

         String var6 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.CRCCHCHOCRROOHCORCCOOIIHIIROHR.get()
            ? com.moonsworth.lunar.client.OHHRIOHROOIHOROCIRHCHORIHRRRRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOHOIHIOORHIIICRCOCRCICORICRH
            : "";
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.HCHICORCHHOHCOCRHCIRICHCRHIHHO.get() ? var6 + var3 + var4 + var2 + var5 : var4 + var2 + var5 + var3 + var6;
      }

      @Override
      protected void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
         float var2,
         float var3,
         boolean var4,
         boolean var5
      ) {
         if (var5) {
            if (RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.OOROHHOIIHIHCCIIROIOOCCRRHCIHC.get()) {
               boolean var6 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.CHIOHRCOCICOOIIRCIOHICOORCRHOH.get();
               float var7 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR().bridge$getStringWidth(this.HOHCCHOIOHOHHOROHOIIHOOHORRHRO(var4));
               float var8 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR()
                  .bridge$getStringWidth(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.IORHORROCCHORCRORIRCIOHCRHHHRR.HORHCHIRIOIOOCOHOIRIRICICHIORH(var6) + " ");
               float var9;
               if (RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.HCHICORCHHOHCOCRHCIRICHCRHIHHO.get()) {
                  float var10 = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.CRCCHCHOCRROOHCORCCOOIIHIIROHR.get()
                     ? IICCOOCHCHROORHHIIHROHCCRHRCOR.HRRIOIRCCHIICOOHHRCIHCCHCORICR()
                        .bridge$getStringWidth(
                           com.moonsworth.lunar.client.OHHRIOHROOIHOROCIRHCHORIHRRRRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOHOIHIOORHIIICRCOCRCICORICRH + " "
                        )
                     : 0.0F;
                  var9 = var2 + this.getWidth() / 2.04F - var7 / 2.0F + var10 + var8;
               } else {
                  var9 = var2 + this.getWidth() / 2.04F - var7 / 2.0F + var8;
               }

               if (this.CRRROHROCCIHHRRIIIOCRCHCRIHOHI.get()) {
                  var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var9 + 0.25F, var3 + this.getHeight() / 2.0F - 4.0F, 1.0F, 9.0F, 1862270976);
               }

               RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.this.HICICOHHCRCOCIHCRCICIOCRHOOIOH
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var9 - 0.5F, var3 + this.getHeight() / 2.0F - 4.5F, 1.0F, 9.0F);
            }
         }
      }
   }
}
