package com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR;

import com.eliotlash.molang.ast.Evaluatable;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import org.jspecify.annotations.Nullable;

public class CORCOCICIRIOHROHROIIOOHICCHCRR implements HICHRCOHCCRHOHCICOOCHOIHCCHIRI {
   private static final String HICCRHCCIOCRORRIIOCHHHCIRCOHHI = "lastBlockPos";
   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("distance")
   private int distance = 4;
   @ORHIOICIOCRRHOOCOHRORIHICHRCRR("should_continue")
   private @Nullable Evaluatable CIOCCIOORHHROHCCRROHCOROHIICHC = null;

   @Override
   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      return var2.OHCCRRICICRHIRRHCHRIIRIOHRCOOI().isDone();
   }

   @Override
   public boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      if (var2.OHCCRRICICRHIRRHCHRIIRIOHRCOOI().CRRRICCRROCOHHOHIICIHORCOORRRH(var1.OORHCIORORHOHHROIRROHIIOIHRCHH(), this.distance)) {
         var2.IHIOOORIOHRIHCIROHHHCHHIHIIHCO().put("lastBlockPos", var1.OORHCIORORHOHHROIRROHIIOIHRCHH().bridge$getBlockPos());
         return true;
      } else {
         return false;
      }
   }

   @Override
   public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      var2.OHCCRRICICRHIRRHCHRIIRIOHRCOOI().stop();
   }

   @Override
   public void CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.client.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2
   ) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var3 = var2.OHCCRRICICRHIRRHCHRIIRIOHRCOOI();
      if (var2.IHIOOORIOHRIHCIROHHHCHHIHIIHCO().get("lastBlockPos") instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4
         )
       {
         int var6 = Math.max(2, this.distance);
         if (var1.OORHCIORORHOHHROIRROHIIOIHRCHH().bridge$getBlockPos().OOROOCCIRCCRHOIOIORIHCHHOOCCOR(var4) >= var6 * var6) {
            if (this.CIOCCIOORHHROHCCRROHCOROHIICHC != null
               && this.CIOCCIOORHHROHCCRROHCOROHIICHC.evaluate(var1.CIHIIRROOHIHHRHOCHOIOIHIHIIORR().RICHHHRIHOICHRRHIHOORICIIOIHII()) != 1.0) {
               var3.stop();
            } else {
               var3.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(var1.OORHCIORORHOHHROIRROHIIOIHRCHH().bridge$getBlockPos());
               var3.IOOOOORRIHOORCOCOHHIICOHCCHOHR();
            }
         }
      }

      var3.tick();
   }

   @Override
   public String toString() {
      return "MoveToOwnerTask{distance=" + this.distance + "}";
   }
}
