package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.lunarclient.dfu.serialization.Codec;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.CRHROHHHCIHHCOHCOORCRIHHIICROR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHIIIOHIRIRCCRRIOIICCHHIORRHOH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;
import com.moonsworth.lunar.lib.adventure.text.Component;
import com.moonsworth.lunar.lib.adventure.text.TextComponent;
import com.moonsworth.lunar.lib.adventure.text.event.ClickEvent;
import com.moonsworth.lunar.lib.adventure.text.event.HoverEvent;
import com.moonsworth.lunar.lib.adventure.text.format.NamedTextColor;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.Generated;
import org.joml.Vector3d;
import org.joml.Vector3i;
import org.joml.Vector3ic;

public class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH IRIRIICCORRCHICCRRCRIRHCIIRROR = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class
   );
   private static final Pattern IRHRIRCIOHRICHOIIIHCRIRICHOCIC = Pattern.compile(
      "(?:[xX]: ?)?(?<x>(?:-|)[0-9.]+),? (?:[yY]: ?)?(?<y>(?:-|)[0-9.]+),? (?:[zZ]: ?)?(?<z>(?:-|)[0-9.]+)(?:\\s*[|:-]\\s*(?<metadata>.+))?"
   );
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI HCICOHIHICHHRHIOCHIOOORIOORORC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR(
         "chatWaypointColor"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-16776961)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO IIHOOICIOCRRCHOIRRHCCRHIOCRICC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.ICHOCHHROIHCROICCIRIHHCHRHROCO(
         "chatWaypointLifetime"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(30)
      .OCIROOIHIHRHOCCHIIIROOCRIIOCRR(10, 60)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HOHCHOCIRIRCHCRICIOHOCHOOOOICO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "chatWaypointRemoveWhenNear"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI OICCRORIHCRORCCORROROCRCCCIRCH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "chatWaypointAlerts"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI IHIOCOHHHRICIRCOCIIHRRHIRICCIC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "skyblockChatWaypointWhitelist"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RIHRIHRIORHHHOOCHOHOHHCOCOIOHO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "skyblockChatWaypointsNoMetaDataAllowed"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHIIIOHIRIRCCRRIOIICCHHIORRHOH<String> RICCOIRRCIHROCHIRIOCRHICIHRCRC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         "skyblockChatWaypointWhilelistList", Codec.STRING.listOf()
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final Set<String> OCOHICCCCIROOROOOIRHRRHICOIORC = new HashSet<>();
   private final List<HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> HRRROHCOIORCIOHRRIRHCCRRRCCORC = new ArrayList<>();

   public HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      super(true);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CHAT
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR,
         OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this,
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI::RRRCCHIOCICOIOIRRCOOIRHHCORCIH
         )
      );
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCRHORIRHHHIIOCOOCHICOOCIHORCC(
                  "chatwaypointblacklist"
               )
               .HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                  var1x -> com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.sendMessage(
                     Component.text(this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("chatWaypointBlacklistInvalidUsage"), NamedTextColor.RED)
                  )
               )
               .HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                        "user", HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CICHOCRIRRRRIHOIHRHIIRHHHHRCRH
                     )
                     .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1x -> this.COIIIOIIOHICCOCIOROOHIIHHIOIOR(var1x.getString("user")))
               )
         )
      );
      this.handle(RIROICHCRROROHCCROOCCCCOCHCCRI.class, this::RIOOCHICIHRHOHCCCCCHOCCCOHCRHI);
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.class,
         this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         this::HHCCIRHCCCIIRHCROHIORHIRHHIORH
      );
      this.handle(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
      this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
   }

   @OIHCOHRCICCCRHRCROOCIOIRRHHHIH
   @Override
   public String getId() {
      return "SKYBLOCK_CHAT_WAYPOINTS";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
         this.HCICOHIHICHHRHIOCHIOOORIOORORC,
         this.IIHOOICIOCRRCHOIRRHCCRHIOCRICC,
         this.HOHCHOCIRIRCHCRICIOHOCHOOOOICO,
         this.OICCRORIHCRORCCORROROCRCCCIRCH,
         IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH("chatWaypointsResetBlacklist")
            .CIOORRCRICOIICROHRHRHHOHRCCRII(100.0F)
            .RCIROOOOICRHCCRRCIORHHIRCOIIIC(this.OCOHICCCCIROOROOOIRHRRHICOIORC::clear)
      );
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         this.IHIOCOHHHRICIRCOCIIHRRHIRICCIC,
         var1x -> var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.RIHRIHRIORHHHOOCHOHOHHCOCOIOHO, this.RICCOIRRCIHROCHIRIOCRHICIHRCRC)
      );
   }

   @Override
   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ORIRHOHRHHROCHHRRIOOCRIHRIIIOC() {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIICCCRRHHCHRRHRIRCHOICCHROHCR()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCOCHOCIRORHHORHCROHOIOCRCHIO
         )
         .HRCHROOHRIHCRCRHRIIROCIRHOIRHH("Diana", "Griffin", "Burrow")
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO(this);
   }

   public Optional<Vector3ic> COHHROIORRCOOIHHOICCHCOCCICRII() {
      if (!this.isEnabled()) {
         return Optional.empty();
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      if (var1 == null) {
         return Optional.empty();
      }

      HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = null;
      double var3 = Float.MAX_VALUE;

      for (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 : this.HRRROHCOIORCIOHRRIRHCCRRRCCORC) {
         if (var2 == null) {
            var2 = var6;
         } else {
            double var7 = var1.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
               var6.HHHCICCCRHIIOCRHOHHRHRHHOROICR.x(), var6.HHHCICCCRHIIOCRHOHHRHRHHOROICR.y(), var6.HHHCICCCRHIIOCRHOHHRHRHHOROICR.z()
            );
            if (var7 < var3) {
               var2 = var6;
               var3 = var7;
            }
         }
      }

      return var2 == null ? Optional.empty() : Optional.of(var2.HHHCICCCRHIIOCRHOHHRHRHHOROICR);
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOIICIRIICICIIOORHCIIIIRRIHRHI var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      if (this.HOHCHOCIRIRCHCRICIOHOCHOOOOICO.get() && var2 != null) {
         this.HRRROHCOIORCIOHRRIRHCCRRRCCORC
            .removeIf(
               var1x -> var2.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                     var1x.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().x(), var1x.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().y(), var1x.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().z()
                  )
                  < 25.0
            );
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var1) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = var1.RCHRROROIOHCRRRCRCRHORHICHRCHO();
      if (!this.OCOHICCCCIROOROOOIRHRRHICOIORC.contains(var2.ROIRIOIHIOHIHCCIIHCRHCOCOIRIOH())) {
         this.HRICOCOIOCCCICCIORHIIIIOROCOHC(var2.message())
            .ifPresent(
               var2x -> {
                  if (this.IHIOCOHHHRICIRCOCIIHRRHIRICCIC.get()) {
                     if (var2x.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC == null) {
                        if (!this.RIHRIHRIORHHHOOCHOHOHHCOCOIOHO.get()) {
                           return;
                        }
                     } else if (this.RICCOIRRCIHROCHIRIOCRHICIHRCRC
                        .get()
                        .stream()
                        .map(String::toLowerCase)
                        .noneMatch(((String)var2x.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC).toLowerCase()::contains)) {
                        return;
                     }
                  }

                  this.HRRROHCOIORCIOHRRIRHCCRRRCCORC
                     .add(
                        new HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           var2.ROIRIOIHIOHIHCCIIHCRHCOCOIRIOH(),
                           (Vector3ic)var2x.OHICIOOICHICOIOCOROIIOCCHRRCIC,
                           IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime(),
                           (String)var2x.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC
                        )
                     );
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.sendMessage(
                     ((TextComponent)Component.text(
                              this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("chatWaypointAdded", var2.ROIRIOIHIOHIHCCIIHCRHCOCOIRIOH()), NamedTextColor.GREEN
                           )
                           .hoverEvent(
                              HoverEvent.showText(
                                 Component.text(this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("chatWaypointAddedHover", var2.ROIRIOIHIOHIHCCIIHCRHCOCOIRIOH()))
                              )
                           ))
                        .clickEvent(ClickEvent.runCommand("/chatwaypointblacklist " + var2.ROIRIOIHIOHIHCCIIHCRHCOCOIRIOH()))
                  );
                  if (this.OICCRORIHCRORCCORROROCRCCCIRCH.get()) {
                     Component var3 = Component.text(
                        this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("waypointFrom", var2.ROIRIOIHIOHIHCCIIHCRHCOCOIRIOH()), NamedTextColor.AQUA
                     );
                     if (var2x.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC != null) {
                        var3 = var3.append(Component.text(" (" + (String)var2x.CICIHRHOHOHIOCRHRIHCHHIHRIHIIC + ")").color(NamedTextColor.GRAY));
                     }

                     this.IRIRIICCORRCHICCRRCRIRHCIIRROR
                        .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                           com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOHRCCHICIICCOHHCHCHOOCCOCICC()
                              .OOIRCOCROHROCRHRICCHIHORHROHII("CHAT_WAYPOINT")
                              .RICRIRRCOHRCOCRRHHCRHRROOIOHHR(var3)
                              .RHCHRCOCCOIIIHCHRHIRCORHRHRICR(3000L)
                              .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                                 com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRITICAL
                              )
                              .HICRRCCIRRICIHOORRHRROHCIROIRI()
                        );
                  }
               }
            );
      }
   }

   private void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(RIROICHCRROROHCCROOCCCCOCHCCRI var1) {
      this.HRRROHCOIORCIOHRRIRHCCRRRCCORC
         .removeIf(
            var1x -> IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() - var1x.OICRCRIROIRHCIHIHIOCHICOICCCIH()
               > 1000L * this.IIHOOICIOCRRCHOIRRHCCRHIOCRICC.get().intValue()
         );

      while (this.HRRROHCOIORCIOHRRIRHCCRRRCCORC.size() > 10) {
         this.HRRROHCOIORCIOHRRIRHCCRRRCCORC.remove(0);
      }
   }

   private void HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      this.HRRROHCOIORCIOHRRIRHCCRRRCCORC.clear();
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OCOHORHCROHICRRIHCIHHRRCIHICRI var2 = var1.HHIIOHOORHHCCHRHHRCIORCROORCOI();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.IHRHHIOIIICOROOORIOHCIROIRCOHH();
      var2.push();
      var2.translate(-var3.bridge$renderPosX(), -var3.bridge$renderPosY(), -var3.bridge$renderPosZ());
      Vector3d var4 = var3.bridge$getCameraPos().RCICCRIHIORCCCRCCORIROCOIIORHC();

      for (HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 : this.HRRROHCOIORCIOHRRIRHCCRRRCCORC) {
         CRHROHHHCIHHCOHCOORCRIHHIICROR var7 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH().bridge$getEyePosition();
         double var8 = 0.05
            + 0.02
               * Math.sqrt(
                  Math.hypot(var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().x() - var7.bridge$xCoord(), var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().z() - var7.bridge$zCoord())
               );
         CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2,
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
               var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().x() + 0.5 - var8,
               var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().y() + 1,
               var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().z() + 0.5 - var8,
               var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().x() + 0.5 + var8,
               255.0,
               var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().z() + 0.5 + var8
            ),
            this.HCICOHIHICHHRHIOCHIOOORIOORORC.CHRHCORIRCORHHIIROCRORHIROICOC(),
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HRCCICRHCOIHOHHOCCORCHRORCCCRR
         );
         CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2,
            var6.HHHCICCCRHIIOCRHOHHRHRHHOROICR,
            com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI.HRHRORCIRICHCCCCCHICOOICIRHRIO(
               this.HCICOHIHICHHRHIOCHIOOORIOORORC.CHRHCORIRCORHHIIROCRORHIROICOC(), 34
            ),
            true
         );
         Vector3d var10 = new Vector3d(
            var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().x() + 0.5, var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().y() + 2, var6.CICHIRRCOOHCCRHRIRCCHRHHOHOROH().z() + 0.5
         );
         Vector3d var11 = var10.sub(var4, new Vector3d()).normalize(10.0);
         Vector3d var12 = var4.add(var11, new Vector3d());
         String var13 = var6.HOCIROCHOROOHHRCOHOHOHOROROICR();
         if (var6.RORHCRCHOHHIRCCCICIIHIHCIORCHR != null) {
            var13 = var13 + " (" + var6.RORHCRCHOHHIRCCCICIIHIHCIORCHR + ")";
         }

         CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.HHIIOHOORHHCCHRHHRCIORCROORCOI(), var13, var12.x(), var12.y(), var12.z(), -1, true);
      }

      var2.pop();
   }

   private Optional<com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO<Vector3ic, String>> HRICOCOIOCCCICCIORHIIIIOROCOHC(
      String var1
   ) {
      try {
         Matcher var2 = IRHRIRCIOHRICHOIIIHCRIRICHOCIC.matcher(var1);
         if (var2.matches()) {
            Vector3i var3 = new Vector3i(
               Integer.parseInt(var2.group("x").replaceAll(",", "")),
               Integer.parseInt(var2.group("y").replaceAll(",", "")),
               Integer.parseInt(var2.group("z").replaceAll(",", ""))
            );
            return Optional.of(
               new com.moonsworth.lunar.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO(
                  var3, var2.group("metadata")
               )
            );
         } else {
            return Optional.empty();
         }
      } catch (NumberFormatException var4) {
         return Optional.empty();
      }
   }

   private void COIIIOIIOHICCOCIOROOHIIHHIOIOR(String var1) {
      this.OCOHICCCCIROOROOOIRHRRHICOIORC.add(var1);
      this.HRRROHCOIORCIOHRRIRHCCRRRCCORC.removeIf(var1x -> var1x.HOCIROCHOROOHHRCOHOHOHOROROICR().equals(var1));
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.sendMessage(
         Component.text(this.IRCIIHHICIHRCOCRROCOICRIHHCCHH("chatWaypointBlacklistAdded", var1), NamedTextColor.GREEN)
      );
   }

   @Generated
   public OHHRIOHROOIHOROCIRHCHORIHRRRRI CHIHRIROCCRICOHIRCRIOOHOHRRCHC() {
      return this.HCICOHIHICHHRHIOCHIOOORIOORORC;
   }

   private record RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      private final String IIICHRHOOCHCOROCHHOIIOCRCRIHOO;
      private final Vector3ic HHHCICCCRHIIOCRHOHHRHRHHOROICR;
      private final long RRHIRIIIROHHIORRHOIHCIRRCHHCOH;
      private final String RORHCRCHOHHIRCCCICIIHIHCIORCHR;

      private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var1, Vector3ic var2, long var3, String var5) {
         this.IIICHRHOOCHCOROCHHOIIOCRCRIHOO = var1;
         this.HHHCICCCRHIIOCRHOHHRHRHHOROICR = var2;
         this.RRHIRIIIROHHIORRHOIHCIRRCHHCOH = var3;
         this.RORHCRCHOHHIRCCCICIIHIHCIORCHR = var5;
      }

      public String HOCIROCHOROOHHRCOHOHOHOROROICR() {
         return this.IIICHRHOOCHCOROCHHOIIOCRCRIHOO;
      }

      public Vector3ic CICHIRRCOOHCCRHRIRCCHRHHOHOROH() {
         return this.HHHCICCCRHIIOCRHOHHRHRHHOROICR;
      }

      public long OICRCRIROIRHCIHIHIOCHICOICCCIH() {
         return this.RRHIRIIIROHHIORRHOIHCIRRCHHCOH;
      }

      public String OCROIRROCCOHICROHHIHHOCRCHOROO() {
         return this.RORHCRCHOHHIRCCCICIIHIHCIORCHR;
      }
   }
}
