package com.moonsworth.lunar.client.RIROICHCRROROHCCROOCCCCOCHCCRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.util.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import org.jetbrains.annotations.NotNull;

public class RRCRRCORICCHOHHIRCHIROOHIIOHCO
   implements com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private final OOROOCCIRCCRHOIOIORIHCHHOOCCOR CHOOHCHIHCICRCIOROIHIRCRHHCRHH;

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO(HHCCIRHCCCIIRHCROHIORHIRHHIORH var1) {
      this.CHOOHCHIHCICRCIOROIHIRCRHHCRHH = var1.RHIHOIIRHIRCOIICICRHICOIOCCHRH();
   }

   @NotNull
   @Override
   public String IOOCCRIIIHHOCIHCCOROOIRRHIICCI() {
      return this.CHOOHCHIHCICRCIOROIHIRCRHHCRHH.OCRCCRHRCRICOCHRRIOCRCCORHOOCH();
   }

   @NotNull
   @Override
   public String HRRICIICIIHRRRHCOOOIIIOHHCRICR() {
      return this.CHOOHCHIHCICRCIOROIHIRCRHHCRHH.RCCRRIROHHOROOCIICCCCOOORIRORO();
   }

   @Override
   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH OHHRICORRCHOCIHCIIRCRCIRHICOOC() {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var1 = this.CHOOHCHIHCICRCIOROIHIRCRHHCRHH
         .OOIIIROOHRCIHIRCCROHICORIROOOR();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OHHRIOHROOIHOROCIRHCHORIHRRRRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = var1.RIHOIHRHRRROOCIOHCIIRCICHHCHRH()
         ? com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRROCIIOCCCHRIIOOOROICIHIOROCO
         : com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCCRRIHROHRHRROOORRHIOOHCCHHI;
      return com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRRIHROCORIOOCHHCHCHOHCIOHHRRI()
         .COOROCRCCHCIHRCCIROCICCIIIRHHC()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var2,
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.TRIANGLE_STRIP
         )
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)null
         )
         .CIOHHCORHRCCRICCCORIHCRHCCCRRR(false)
         .IHHCHHHCRIHOOCOIOOCRIIICIOROIR(true)
         .IIRHCHHOICHRICOOCRORCCIOOIHOIR(false)
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.NO_DEPTH_TEST
         );
   }

   @Override
   public com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ICCRHCROIHORRCRCRCCCRIRRROCHHI() {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = new com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();
      this.CHOOHCHIHCICRCIOROIHIRCRHHCRHH
         .OOIIIROOHRCIHIRCCROHICORIROOOR()
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO((var1x, var2) -> var1.HCHCICHCRROORRRHIOHIIHHCRCHHII(var2));
      return var1;
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      BiConsumer<String, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH> var1
   ) {
      for (CORCOCICIRIOHROHROIIOOHICCHCRR var3 : this.CHOOHCHIHCICRCIOROIHIRCRHHCRHH.HIRIOOCHIHRICCIIRCCHCCOCRORCOC()) {
         var1.accept(var3.getVarName(), var3.getType());
      }

      OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.CHOOHCHIHCICRCIOROIHIRCRHHCRHH.OOIIIROOHRCIHIRCCROHICORIROOOR(), var1);
   }

   @Override
   public void CRHROHHHCIHHCOHCOORCRIHHIICROR(Consumer<String> var1) {
      for (com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var3 : this.CHOOHCHIHCICRCIOROIHIRCRHHCRHH
         .HCIOCOOORRRHOROHIOOIROOCOICRHR()) {
         var1.accept(var3.OIHIRICIOICCOOORIRORORICRHIHII());
      }
   }
}
