package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ICICIOCHHHIHOCHCOHORIHRCOHHOCR;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import lombok.Generated;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI OIIIRRRRIRRCCIOIORIHIRHRICIOOO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("hitArmorColor")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(1721303040)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RIOOHORIOIOIIHICHRIIOROHIROHRO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "shouldColorArmor"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(ORHIOICIOCRRHOOCOHRORIHICHRCRR.class, this::RIOOCHICIHRHOHCCCCCHOCCCOHCRHI, 130);
   }

   private void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(ORHIOICIOCRRHOOCOHRORIHICHRCRR var1) {
      if (var1.COOCHHRROHRCCIOIOHRRIIOHCIRCCH() == ORHIOICIOCRRHOOCOHRORIHICHRCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.EQUIPPED_ARMOR
         && var1.HCICROIHRHRCORRHCOIHIHCCCCHRHH() != null
         && this.OHCCOCHRHIOIHHHROHRORIHROIOHRR().get()) {
         CORCOCICIRIOHROHROIIOOHICCHCRR var2 = (CORCOCICIRIOHROHROIIOOHICCHCRR)var1.HCICROIHRHRCORRHCOIHIHCCCCHRHH();
         if (var2.bridge$getHurtTime() > 0 || var2.bridge$getDeathTime() > 0.0F) {
            var1.setCancelled(true);
         }
      }
   }

   @Override
   public String getId() {
      return "HIT_COLOR";
   }

   public static int IOCCCRIHOCHRCHRHCRHROIRIRHHHIR(int var0) {
      com.moonsworth.lunar.client.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR();
      if (var1 == null) {
         return var0;
      }

      IHIRRIIORRHORHRORIHOROIRCORCOO var2 = var1.HHCCIRORCRCHOIOHRRIRRRIORRCRRR();
      if (var2 == null) {
         return var0;
      }

      if (var2.HOORIHHORRRRHCIRCIHCCCRRCCICIR().IHIOHOOHHIRRCOIIIICCOHORCCRCOI()) {
         return -16777216;
      }

      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = var2.COIHORORRIICCRIIRHIRIRRHCHOHHC();
      return var3 != null && var3.isEnabled() ? var3.CHOCRCRIIOCORIHRCHHIIHOIHCCRCR() : var0;
   }

   private int CHOCRCRIIOCORIHRCHHIIHOIHCCRCR() {
      int var1;
      if (this.isEnabled()) {
         var1 = this.OIIIRRRRIRRCCIOIORIHIRHRICIOOO.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(0.0F);
      } else {
         var1 = OCOHORHCROHICRRIHCIHHRRCIHICRI.ORHIOICIOCRRHOOCOHRORIHICHRCRR(255, 0, 0, 77);
      }

      int var2 = OCOHORHCROHICRRIHCIHHRRCIHICRI.HRHRORCIRICHCCCCCHICOOICIRHRIO(var1, 255 - OCOHORHCROHICRRIHCIHHRRCIHICRI.HOHROOIORCHOIIOOIIHHIHRCOCHIRO(var1));
      return OCOHORHCROHICRRIHCIHHRRCIHICRI.OCOHIOCHOCHRCCROORRIIIHIOHOIIR(var2);
   }

   public float RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(float var1) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .HOORIHHORRRRHCIRCIHCCCRRCCICIR()
         .IHIOHOOHHIRRCOIIIICCOHORCCRCOI()) {
         return 1.0F;
      } else {
         return !this.isEnabled()
            ? var1
            : OCOHORHCROHICRRIHCIHHRRCIHICRI.HRHICOCCOOHROCCIHHOHORHIHHHHOO(this.OIIIRRRRIRRCCIOIORIHIRHRICIOOO.HCHOOCHIOICRRHHIHHHICIRCIOICRI(0.0F));
      }
   }

   public float RRHOOOORORHHOOIHRCCHIIHHIIIIOH(float var1) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .HOORIHHORRRRHCIRCIHCCCRRCCICIR()
         .IHIOHOOHHIRRCOIIIICCOHORCCRCOI()) {
         return 1.0F;
      } else {
         return !this.isEnabled()
            ? var1
            : OCOHORHCROHICRRIHCIHHRRCIHICRI.HRHICOCCOOHROCCIHHOHORHIHHHHOO(this.OIIIRRRRIRRCCIOIORIHIRHRICIOOO.RORRCRCHIRCHHOOIHCCHRCHORHCICI(0.0F));
      }
   }

   public float HIHHOCRHHRORRHHRORRRIIHHORIHOC(float var1) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .HOORIHHORRRRHCIRCIHCCCRRCCICIR()
         .IHIOHOOHHIRRCOIIIICCOHORCCRCOI()) {
         return 1.0F;
      } else {
         return !this.isEnabled()
            ? var1
            : OCOHORHCROHICRRIHCIHHRRCIHICRI.HRHICOCCOOHROCCIHHOHORHIHHHHOO(this.OIIIRRRRIRRCCIOIORIHIRHRICIOOO.ROCHRRCORRCOOOOOCOICOCROIIHIHH(0.0F));
      }
   }

   public float OOCHRIIIRIHRRCRIORHCROIIHCRRIC(float var1) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
         .HOORIHHORRRRHCIRCIHCCCRRCCICIR()
         .IHIOHOOHHIRRCOIIIICCOHORCCRCOI()) {
         return 0.0F;
      } else {
         return !this.isEnabled()
            ? var1
            : OCOHORHCROHICRRIHCIHHRRCIHICRI.HRHICOCCOOHROCCIHHOHORHIHHHHOO(this.OIIIRRRRIRRCCIOIORIHIRHRICIOOO.IOHCRRIIHCIHORROOCHCCORIHRHCII(0.0F));
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.OIIIRRRRIRRCCIOIORIHIRHRICIOOO, this.RIOOHORIOIOIIHICHRIIOROHIROHRO);
   }

   @Generated
   public OHHRIOHROOIHOROCIRHCHORIHRRRRI CHCIROROOOIHHICHIIHICRIRHRIRRC() {
      return this.OIIIRRRRIRRCCIOIORIHIRHRICIOOO;
   }

   @Generated
   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI OHCCOCHRHIOIHHHROHRORIHROIOHRR() {
      return this.RIOOHORIOIOIIHICHRIIOROHIROHRO;
   }
}
