package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HCHRIROHHHCORIOCROOCHRCIOROOCI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;
import com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import it.unimi.dsi.fastutil.booleans.BooleanConsumer;
import lombok.Generated;

public class HRCHROOHRIHCRCRHRIIROCIRHOIRHH
   extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private String OIIIOCCOHROOHCHORRRCIHOCHOROHH;
   private String RIRORIRROHIHOROIOCHHOHCCICIIIO;
   private boolean pressed;
   private boolean value;

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CORCOCICIRIOHROHROIIOOHICCHCRR var1
   ) {
      this.OIIIOCCOHROOHCHORRRCIHOCHOROHH = var1.readString();
      this.RIRORIRROHIHOROIOCHHOHCCICIIIO = var1.readString();
      this.pressed = var1.readBoolean();
      this.value = var1.readBoolean();
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CORCOCICIRIOHROHROIIOOHICCHCRR var1
   ) {
      var1.RCRICHOCHHHCRCORROOIHCROOIICOC(this.OIIIOCCOHROOHCHORRRCIHOCHOROHH);
      var1.RCRICHOCHHHCRCORROOIHCROOIICOC(this.RIRORIRROHIHOROIOCHHOHCCICIIIO);
      var1.writeBoolean(this.pressed);
      var1.writeBoolean(this.value);
   }

   @Override
   public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      IHIRRIIORRHORHRORIHOROIRCORCOO var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HHCCIRORCRCHOIOHRRIRRRIORRCRRR();
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 = var2.COCOCRIOIHOCHHRIOICCICIOIHHOHH(
         this.OIIIOCCOHROOHCHORRRCIHOCHOROHH
      );
      if (var3 != null) {
         IHHCHHHCRIHOOCOIOOCRIIICIOROIR var4 = var3.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRHCCHCRHIHOCRICOHOIICHCHOHICC);
         if (var4 == null) {
            return;
         }

         for (HCHRIROHHHCORIOCROOCHRCIOROOCI var6 : var4.CRCOOHOOOCRICHRCCIOCCIRCCOHCRO()) {
            if (var6.getId().equals(this.RIRORIRROHIHOROIOCHHOHCCICIIIO) && var6 instanceof OIHCOHRCICCCRHRCROOCIOIRRHHHIH var7) {
               if (this.pressed) {
                  for (Runnable var9 : var7.OCOICRICIHOCOHCHRHCHIRCRROOOHH()) {
                     var9.run();
                  }
               } else {
                  for (BooleanConsumer var11 : var7.HOIOIRCRHCCHCHICOIOHHCICOIOCRR()) {
                     var11.accept(this.value);
                  }
               }
               break;
            }
         }
      }
   }

   @Generated
   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH(String var1, String var2, boolean var3, boolean var4) {
      this.OIIIOCCOHROOHCHORRRCIHOCHOROHH = var1;
      this.RIRORIRROHIHOROIOCHHOHCCICIIIO = var2;
      this.pressed = var3;
      this.value = var4;
   }

   @Generated
   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH() {
   }

   @Generated
   public String HCHCCOORROHRRIICCHCROIOORRIHIC() {
      return this.OIIIOCCOHROOHCHORRRCIHOCHOROHH;
   }

   @Generated
   public String HOOHROIRIHOIIIRCIHHCIRCRHIOOCO() {
      return this.RIRORIRROHIHOROIOCHHOHCCICIIIO;
   }

   @Generated
   public boolean HHORICCCICORIOIOROCCRRHHCHCOCR() {
      return this.pressed;
   }

   @Generated
   public boolean isValue() {
      return this.value;
   }
}
