package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRHIHIRHRCHHRORRRCORHOCIRHRIOR;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import lombok.Generated;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final RIRHOCHIORCCIIOIIRHOCCCRHHCHHH ROHOORRCIORHOROOCIOICRRIRHOORR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IHRROIOOOOHRRHIIIIHHHRORHHIIHC("thirdPersonKey")
      .ORIOHRCIHRCOOHICCCRIIIHCRHHIHI(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_LMENU
      )
      .IHCOIHIICIIHOOIICCHHCRORHORHCI(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RIRHOCHIORCCIIOIIRHOCCCRHHCHHH RHOOHRHOICCCORHOHCIRORICOCHIHC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IHRROIOOOOHRRHIIIIHHHRORHHIIHC(
         "forwardPersonKey"
      )
      .IHCOIHIICIIHOOIICCHHCRORHORHCI(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private int OORHIRCRHHOCHRROROOCOIICHOCOHO;
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI IICRICHRCOOHHCCOCIOOIIHROCRRRH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("smoothCamera")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI IHIOORIIHRCOOIHCOORICORRCOOOIO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "snaplookToggleMode"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private boolean active;

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      super(false);
   }

   @Override
   public String getId() {
      return "SNAPLOOK";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.CRRRICCRROCOHHOHIICIHORCOORRRH(
         this.ROHOORRCIORHOROOCIOICRRIRHOORR, this.RHOOHRHOICCCORHOHCIRORICOCHIHC, this.IICRICHRCOOHHCCOCIOOIIHROCRRRH, this.IHIOORIIHRCOOIHCOORICORRCOOOIO
      );
      this.ROHOORRCIORHOROOCIOICRRIRHOORR
         .OOCCRCRCOHIIORCCORCRCIRRROIOOR(() -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH.THIRD))
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1x -> {
               if (!this.IHIOORIIHRCOOIHCOORICORRCOOOIO.get() && !this.RHOOHRHOICCCORHOHCIRORICOCHIHC.isKeyDown()) {
                  this.active = false;
                  this.mc.bridge$getGameSettings().bridge$setThirdPersonView(this.OORHIRCRHHOCHRROROOCOIICHOCOHO);
                  this.mc.bridge$getLevelRenderer().bridge$setNeedsFullRenderChunkUpdate(true);
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOIICIRIICICIIOORHCIIIIRRIHRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IIIIRORCORHIIIRCRIOCIOOICOCROI()
                     .stop();
               }
            }
         );
      this.RHOOHRHOICCCORHOHCIRORICOCHIHC
         .OOCCRCRCOHIIORCCORCRCIRRROIOOR(() -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH.FORWARD))
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1x -> {
               if (!this.IHIOORIIHRCOOIHCOORICORRCOOOIO.get() && !this.ROHOORRCIORHOROOCIOICRRIRHOORR.isKeyDown()) {
                  this.active = false;
                  this.mc.bridge$getGameSettings().bridge$setThirdPersonView(this.OORHIRCRHHOCHRROROOCOIICHOCOHO);
                  this.mc.bridge$getLevelRenderer().bridge$setNeedsFullRenderChunkUpdate(true);
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOIICIRIICICIIOORHCIIIIRRIHRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IIIIRORCORHIIIRCRIOCIOOICOCROI()
                     .stop();
               }
            }
         );
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      if (!IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HHCCIRORCRCHOIOHRRIRRRIORRCRRR().CHICCHHHRCRROORCRCCCRHOICIOROC().isEnabled()
         || IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                  .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
                  .CHICCHHHRCRROORCRCCCRHOICIOROC()
                  .OHRHCCOCCIICCHOHRCROCIRICHHOHO()
                  .CCICCIOCIHOOIHCIRCHHHRROHIHHIH()
               != this.ROHOORRCIORHOROOCIOICRRIRHOORR.CCICCIOCIHOOIHCIRCHHHRROHIHHIH()
            && IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                  .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
                  .CHICCHHHRCRROORCRCCCRHOICIOROC()
                  .OHRHCCOCCIICCHOHRCROCIRICHHOHO()
                  .CCICCIOCIHOOIHCIRCHHHRROHIHHIH()
               != this.RHOOHRHOICCCORHOHCIRORICOCHIHC.CCICCIOCIHOOIHCIRCHHHRROHIHHIH()) {
         if (!IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .HHCCIRORCRCHOIOHRRIRRRIORRCRRR()
            .IOIOHOOCRRORCCCOCIRROHCOCCCRCO()
            .OOROOCCIRCCRHOIOIORIHCHHOOCCOR(var0 -> !var0.CCRHOIIHHCCIROCCROHHIIOCOHIRRC().CHORCRORCICOCOOORCIOOICCOOIOHC().isFixedToPlayer())) {
            if (this.IHIOORIIHRCOOIHCOORICORRCOOOIO.get()) {
               if (this.active) {
                  int var2 = this.mc.bridge$getGameSettings().bridge$getThirdPersonView();
                  if (var2 != var1.getPerspective()) {
                     this.mc.bridge$getGameSettings().bridge$setThirdPersonView(var1.getPerspective());
                     this.mc.bridge$getLevelRenderer().bridge$setNeedsFullRenderChunkUpdate(true);
                  } else {
                     this.active = false;
                     this.mc.bridge$getGameSettings().bridge$setThirdPersonView(this.OORHIRCRHHOCHRROROOCOIICHOCOHO);
                     this.mc.bridge$getLevelRenderer().bridge$setNeedsFullRenderChunkUpdate(true);
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOIICIRIICICIIOORHCIIIIRRIHRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IIIIRORCORHIIIRCRIOCIOOICOCROI()
                        .stop();
                  }
               } else {
                  this.active = true;
                  this.OORHIRCRHHOCHRROROOCOIICHOCOHO = this.mc.bridge$getGameSettings().bridge$getThirdPersonView();
                  this.mc.bridge$getGameSettings().bridge$setThirdPersonView(var1.getPerspective());
                  this.mc.bridge$getLevelRenderer().bridge$setNeedsFullRenderChunkUpdate(true);
                  if (this.IICRICHRCOOHHCCOCIOOIIHROCRRRH.get()) {
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOIICIRIICICIIOORHCIIIIRRIHRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IIIIRORCORHIIIRCRIOCIOOICOCROI()
                        .start();
                  }
               }
            } else {
               if (!this.active) {
                  this.OORHIRCRHHOCHRROROOCOIICHOCOHO = this.mc.bridge$getGameSettings().bridge$getThirdPersonView();
                  this.active = true;
               }

               this.mc.bridge$getGameSettings().bridge$setThirdPersonView(var1.getPerspective());
               this.mc.bridge$getLevelRenderer().bridge$setNeedsFullRenderChunkUpdate(true);
               if (this.IICRICHRCOOHHCCOCIOOIIHROCRRRH.get()) {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IOIICIRIICICIIOORHCIIIIRRIHRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IIIIRORCORHIIIRCRIOCIOOICOCROI()
                     .start();
               }
            }
         }
      }
   }

   @Override
   protected RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ORIRHOHRHHROCHHRRIOOCRIHRIIIOC() {
      return RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIICCCRRHHCHRRHRIRCHOICCHROHCR()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(HHCCIRHCCCIIRHCROHIORHIRHHIORH.RROHICHROOOOORICCIRCHOOIRCRHIO)
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO(this);
   }

   @Generated
   public int CHOHOCIOCROHRIHICIOOOOCIRCOIRR() {
      return this.OORHIRCRHHOCHRROROOCOIICHOCOHO;
   }

   @Generated
   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI RIROHCHIIHCCCCRHCROOIROIICORCH() {
      return this.IICRICHRCOOHHCCOCIOOIIHROCRRRH;
   }
}
