package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;
import com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI;

public abstract class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends IHHCHHHCRIHOOCOIOOCRIIICIOROIR {
   static final long RORRRROHCIOCHICCIIOIOROOCCOHCI = 2L;
   protected transient OCOHORHCROHICRRIHCIHHRRCIHICRI OHOCIROIRICROCCORCHRHHCOHICHII;
   protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR COHOOICCRCOOHCOIRORIIOHOHROIII;

   protected HHCCIRHCCCIIRHCROHIORHIRHHIORH(OCOHORHCROHICRRIHCIHHRRCIHICRI var1, String var2) {
      super(var2, var1 == null ? null : var1.COIIOIOCCIOCOOIROHCCHHRHCICIHI());
      this.OHOCIROIRICROCCORCHRHHCOHICHII = var1;
   }

   protected HHCCIRHCCCIIRHCROHIORHIRHHIORH(OCOHORHCROHICRRIHCIHHRRCIHICRI var1, String var2, Throwable var3) {
      super(var2, var1 == null ? null : var1.COIIOIOCCIOCOOIROHCCHHRHCICIHI(), var3);
      this.OHOCIROIRICROCCORCHRHHCOHICHII = var1;
   }

   protected HHCCIRHCCCIIRHCROHIORHIRHHIORH(OCOHORHCROHICRRIHCIHHRRCIHICRI var1, String var2, HICHRCOHCCRHOHCICOOCHOIHCCHIRI var3) {
      super(var2, var3, null);
      this.OHOCIROIRICROCCORCHRHHCOHICHII = var1;
   }

   protected HHCCIRHCCCIIRHCROHIORHIRHHIORH(OCOHORHCROHICRRIHCIHHRRCIHICRI var1, String var2, HICHRCOHCCRHOHCICOOCHOIHCCHIRI var3, Throwable var4) {
      super(var2, var3, var4);
      this.OHOCIROIRICROCCORCHRHHCOHICHII = var1;
   }

   protected HHCCIRHCCCIIRHCROHIORHIRHHIORH(String var1, HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2, Throwable var3) {
      super(var1, var2, var3);
   }

   protected HHCCIRHCCCIIRHCROHIORHIRHHIORH(String var1) {
      super(var1);
   }

   public abstract HHCCIRHCCCIIRHCROHIORHIRHHIORH CRICCOOHHHCHOORCICOCOHIHOIRHOO(OCOHORHCROHICRRIHCIHHRRCIHICRI var1);

   public abstract HHCCIRHCCCIIRHCROHIORHIRHHIORH IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR var1
   );

   public OCOHORHCROHICRRIHCIHHRRCIHICRI IOORHCCHRCCRCRROOOROOIOIRCRROC() {
      return this.OHOCIROIRICROCCORCHRHHCOHICHII;
   }

   public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR OHOOIROORCRIIRHCOCCHICHRRCCOCI() {
      return this.COHOOICCRCOOHCOIRORIIOHOHROIII;
   }

   public String RHORIRIHOCRHRHHIOIRORORHHRRIIR() {
      return this.COHOOICCRCOOHCOIRORIIOHOHROIII != null ? this.COHOOICCRCOOHCOIRORIIOHOHROIII.toString() : null;
   }

   @Override
   public String getMessage() {
      String var1 = super.getMessage();
      if (this.COHOOICCRCOOHCOIRORIIOHOHROIII != null) {
         var1 = var1 + "\nRequest payload : " + this.COHOOICCRCOOHCOIRORIIOHOHROIII.toString();
      }

      return var1;
   }
}
