package com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OHHRIOHROOIHOROCIRHCHORIHRRRRI;

public enum CRRRICCRROCOHHOHIICIHORCOORRRH {
   DISTANCE_TO_ORIGIN,
   ORTHOGRAPHIC_Z;
}
