package com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;

public class OCOHORHCROHICRRIHCIHHRRCIHICRI implements CRICCOOHHHCHOORCICOCOHIHOIRHOO {
   private static final RCIROOOOICRHCCRRCIORHHIRCOIIIC HIOOOIROHHRORCCHRHHHHRCHHIICRH = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create(
      "minecraft", "textures/gui/title/background/panorama"
   );
   private static final RCIROOOOICRHCCRRCIORHHIRCOIIIC ROHROHHOROOHRIHHOOHORRCRCCRCII = RCIROOOOICRHCCRRCIORHHIRCOIIIC.create("lunar", "backgrounds/splash.png");

   @Override
   public RCIROOOOICRHCCRRCIORHHIRCOIIIC HOCROCHROIIRROICRICOICHOIICRHH() {
      return ROHROHHOROOHRIHHOOHORRCRCCRCII;
   }

   @Override
   public RCIROOOOICRHCCRRCIORHHIRCOIIIC CRCCOCCHOIOOORRCHCCORCHOIICCCC() {
      return HIOOOIROHHRORCCHRHHHHRCHHIICRH;
   }

   @Override
   public String name() {
      return "vanilla";
   }

   @Override
   public boolean IIRCICRIHHHORICCOHRCHHHRIRICCI() {
      return true;
   }
}
