package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

import com.google.gson.JsonObject;
import com.google.protobuf.Any;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CIOHHCORHRCCRICCCORIHCRHCCCRRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IIHRRHORCRCROCHHOHORCHCROCIHRO;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.client.util.CIIHHCHIRCRRIHOIOCCCROHOIOCCII;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.RIHOOCIHRICOCHRHCOOCCOIHOCHRCR;
import io.netty.util.concurrent.DefaultThreadFactory;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import lombok.Generated;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HHRRROCROCCHROHIOCICIHICICCCRO;
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IRHRHHROCOHHCCCRCOCHCHCIIHHOIR;
   private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CCCHRRROOCIHCCRCCICICORHIICORI = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RECORDING;
   private final Executor COHHOHCHIRRRRROHRHICHHHORHOIRR = Executors.newSingleThreadExecutor(new DefaultThreadFactory("lunar-rewind-recorder-thread", true));
   private int tick = 0;
   private boolean CCOICRRHOHHHHROOOROIHIRHHCCIHI = false;
   private boolean OCHOCOHHHIOCRIOIOOIHOHRIIIHHOC = false;
   private final boolean IROOCHICCRORIHCRORROROOIHCORHR;
   private RRCRRCORICCHOHHIRCHIROOHIIOHCO RIIHHIHIIOOIIROCHOROCHOIOIHICI;
   private CRRRICCRROCOHHOHIICIHORCOORRRH COOCIIRHHHOICIROCROICIRRIRICIR;
   private final Map<String, Map<String, Object>> IIROOCCIORCICOOOIRIROCICICOCOR = new HashMap<>();
   private final Map<String, JsonObject> OHHCROIIIIOORCCCCOIHICRIOOCHRI = new HashMap<>();
   private final Map<String, CORCOCICIRIOHROHROIIOOHICCHCRR> RORHHHOCOICROOIRHORIIICOCICCII = new HashMap<>();
   private final List<HICHRCOHCCRHOHCICOOCHOIHCCHIRI> ORRRICIRRHCIOCCRRROOHHRRCCCIHR = List.of(
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(),
      new CIOHHCORHRCCRICCCORIHCRHCCCRRR(),
      new CRICCOOHHHCHOORCICOCOHIHOIRHOO(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR(),
      new OCOHORHCROHICRRIHCIHHRRCIHICRI(),
      new IHHCHHHCRIHOOCOIOOCRIIICIOROIR(),
      new IIHRRHORCRCROCHHOHORCHCROCIHRO(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(),
      new OOROOCCIRCCRHOIOIORIHCHHOOCCOR(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH(),
      new HRCHROOHRIHCRCRHRIIROCIRHOIRHH(),
      new RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH()
   );
   private final List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH> CIHCOICOIROIIOHIRHIRHRCHCHOCOR = List.of(
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(),
      new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH()
   );

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      boolean var2,
      boolean var3,
      boolean var4
   ) {
      super(true);
      if (var3) {
         try {
            this.RIIHHIHIIOOIIROCHOROCHOIOIHICI = new RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1);
         } catch (Exception var7) {
            var7.printStackTrace();
         }
      }

      if (var4) {
         try {
            if (RIHOOCIHRICOCHRHCOOCCOIHOCHRCR.isWindows()) {
               this.COOCIIRHHHOICIROCROICIRRIRICIR = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH();
            } else if (RIHOOCIHRICOCHRHCOOCCOIHOCHRCR.isLinux()) {
               this.COOCIIRHHHOICIROCROICIRRIRICIR = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH();
            } else if (RIHOOCIHRICOCHRHCOOCCOIHOCHRCR.isMacos()) {
               this.COOCIIRHHHOICIROCROICIRRIRICIR = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH();
            }
         } catch (Exception var6) {
            var6.printStackTrace();
         }
      }

      this.HHRRROCROCCHROHIOCICIHICICCCRO = var1;
      this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR = var2
         ? new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            this, this.RIIHHIHIIOOIIROCHOROCHOIOIHICI, this.COOCIIRHHHOICIROCROICIRRIRICIR
         )
         : new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            this, this.RIIHHIHIIOOIIROCHOROCHOIOIHICI, this.COOCIIRHHHOICIROCROICIRRIRICIR, var1.COCHHIRRCCHRROIIHRCCIHHCHRHROO().get(), false
         );
      this.IROOCHICCRORIHCRORROROOIHCORHR = var2;
      this.handle(IIRHCHHOICHRICOOCRORCCIOOIHOIR.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::HICHRCOHCCRHOHCICOOCHOIHCCHIRI);
      this.handle(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         ORHIOICIOCRRHOOCOHRORIHICHRCRR.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICRRICCHCCROOHHCHOCOCCHOIHHOC.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICRRICCHCCROOHHCHOCOCCHOIHHOC.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CIOHHCORHRCCRICCCORIHCRHCCCRRR.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.class,
         var1x -> this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2x -> var2x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR))
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH.class,
         this::RIOOCHICIHRHOHCCCCCHOCCCOHCRHI
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.class,
         this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      );
      if (this.RIIHHIHIIOOIIROCHOROCHOIOIHICI != null) {
         this.RIIHHIHIIOOIIROCHOROCHOIOIHICI.start();
      }

      if (this.COOCIIRHHHOICIROCROICIRRIRICIR != null) {
         this.COOCIIRHHHOICIROCROICIRRIRICIR.start();
      }

      this.IOHCRRIIHCIHORROOCHCCORIHRHCII(false);
   }

   public void OOROOCCIRCCRHOIOIORIHCHHOOCCOR(Any var1) {
      try {
         this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1.toByteArray()
               ),
               this.tick
            );
      } catch (Exception var3) {
         throw new RuntimeException(var3);
      }
   }

   public boolean IOHCRRIIHCIHORROOCHCCORIHRHCII(boolean var1) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
      if (var2 != null && var3 != null) {
         this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1
               ),
               this.tick
            );

         for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var5 : this.CIHCOICOIROIIOHIRHIRHRCHCHOCOR) {
            var5.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, var2, var3);
         }

         this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH(),
               this.tick
            );
         return true;
      } else {
         return false;
      }
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IIRHCHHOICHRICOOCRORCCIOOIHOIR var1) {
      if (this.isRecording()) {
         for (HICHRCOHCCRHOHCICOOCHOIHCCHIRI var3 : this.ORRRICIRRHCIOCCRRROOHHRRCCCIHR) {
            var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR);
         }
      }
   }

   public void ICIORIHOCHCOHRIHIHCHRRCCCHCOCO() {
      if (this.isRecording()) {
         for (HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2 : this.ORRRICIRRHCIOCCRRROOHHRRCCCIHR) {
            var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(new IRRCCOICORICIHCHRHIHIHROIRHOCR(), this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR);
         }
      }
   }

   private void HICHRCOHCCRHOHCICOOCHOIHCCHIRI(IOIICIRIICICIIOORHCIIIIRRIHRHI var1) {
      if (this.OCHOCOHHHIOCRIOIOOIHOHRIIIHHOC && !IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$isGamePaused()) {
         this.HIOHICORCIOOHORHORIHHRIOCRCCRR(false);
      }

      if (this.isRecording()) {
         for (HICHRCOHCCRHOHCICOOCHOIHCCHIRI var3 : this.ORRRICIRRHCIOCCRRROOHHRRCCCIHR) {
            var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, this, this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR);
         }

         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.IIROOCCIORCICOOOIRIROCICICOCOR,
            var1x -> {
               for (Entry var3x : var1x.getValue().entrySet()) {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var4 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO(
                     var1x.getKey(),
                     (String)var3x.getKey(),
                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CCIHHRIOOOOCOHRCIHOHROOICIORCC(
                        var3x.getValue()
                     ),
                     var3x.getValue()
                  );
                  this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, this.tick);
               }
            }
         );
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.OHHCROIIIIOORCCCCOIHICRIOOCHRI,
            var1x -> {
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR var2 = new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
                  var1x.getKey(), var1x.getValue()
               );
               this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, this.tick);
            }
         );
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            this.RORHHHOCOICROOIRHORIIICOCICCII, var1x -> this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1x.getValue(), this.tick)
         );
         this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR.HCIOIIHCHIHRHOHRICRIOCIRHRICOR(false);
         this.tick++;
      }
   }

   private void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      if (this.CCCHRRROOCIHCCRCCICICORHIICORI != RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.STOPPED) {
         this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH(
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.DISCONNECT
               ),
               this.tick
            );
      }
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1
   ) {
      if (this.isRecording()) {
         this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
                  var1.CHCICCIOORCHHCCIRCCCRIOIRIOCOI()
               ),
               this.tick
            );
      }
   }

   private <K, V> void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Map<K, V> var1, com.moonsworth.lunar.client.util.CRICCOOHHHCHOORCICOCOHIHOIRHOO<Entry<K, V>> var2) {
      for (Entry var4 : var1.entrySet()) {
         var2.accept(var4);
      }

      var1.clear();
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(com.moonsworth.lunar.client.util.CRICCOOHHHCHOORCICOCOHIHOIRHOO<HICHRCOHCCRHOHCICOOCHOIHCCHIRI> var1) {
      if (this.isRecording()) {
         for (HICHRCOHCCRHOHCICOOCHOIHCCHIRI var3 : this.ORRRICIRRHCIOCCRRROOHHRRCCCIHR) {
            var1.accept(var3);
         }
      }
   }

   public void HIOHICORCIOOHORHORIHHRIOCRCCRR(boolean var1) {
      if (!var1 || !this.IROOCHICCRORIHCRORROROOIHCORHR && this.HHRRROCROCCHROHIOCICIHICICCCRO.CCCORRRRHRICHRICICHHOHOIIHCCHO().get()) {
         if (var1) {
            this.IRIHOIRCHIRRCRIOORCOICORHHORHH(false);
            this.OCHOCOHHHIOCRIOIOOIHOHRIIIHHOC = true;
         } else if (this.OCHOCOHHHIOCRIOIOOIHOHRIIIHHOC) {
            this.resume();
            this.OCHOCOHHHIOCRIOIOOIHOHRIIIHHOC = false;
         }
      }
   }

   public void IRIHOIRCHIRRCRIOORCOICORHHORHH(boolean var1) {
      this.CCCHRRROOCIHCCRCCICICORHIICORI = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.PAUSED;
      this.CCOICRRHOHHHHROOOROIHIRHHCCIHI = var1;
      if (this.RIIHHIHIIOOIIROCHOROCHOIOIHICI != null) {
         this.RIIHHIHIIOOIIROCHOROCHOIOIHICI.RCOHCCHCRHIIIICRIHCOICIHHCCOOC(true);
      }

      if (this.COOCIIRHHHOICIROCROICIRRIRICIR != null) {
         this.COOCIIRHHHOICIROCROICIRRIRICIR.RCOHCCHCRHIIIICRIHCOICIHHCCOOC(true);
      }

      IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$schedule(this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR::pause);
   }

   public void resume() {
      if (!this.isRecording()) {
         this.CCCHRRROOCIHCCRCCICICORHIICORI = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RECORDING;
         if (this.RIIHHIHIIOOIIROCHOROCHOIOIHICI != null) {
            this.RIIHHIHIIOOIIROCHOROCHOIOIHICI.RCOHCCHCRHIIIICRIHCOICIHHCCOOC(false);
         }

         if (this.COOCIIRHHHOICIROCROICIRRIRICIR != null) {
            this.COOCIIRHHHOICIROCROICIRRIRICIR.RCOHCCHCRHIIIICRIHCOICIHHCCOOC(false);
         }

         if (this.CCOICRRHOHHHHROOOROIHIRHHCCIHI) {
            this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH(),
                  this.tick
               );
         } else if (!this.OCHOCOHHHIOCRIOIOOIHOHRIIIHHOC && !this.IOHCRRIIHCIHORROOCHCCORIHRHCII(false)) {
            this.IRIHOIRCHIRRCRIOORCOICORHHORHH(false);
            IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
               .IHCHHRRIIIORORCHIICIIOORCOIOIO()
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR.ERROR,
                  "Rewind",
                  "Cannot resume recording"
               );
         }

         this.CCOICRRHOHHHHROOOROIHIRHHCCIHI = false;
      }
   }

   public void IRRCCOHCIHHHRHHRRCHICOHROOIOOC() {
      if (this.IROOCHICCRORIHCRORROROOIHCORHR) {
         try {
            long var1 = this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR.RRIHCRHRRHRIHOCORCIOHHCHHRCCII();
            String var3 = CIIHHCHIRCRRIHOIOCCCROHOIOCCII.IHRHHHORORIROOCORCIORRCOCHHHRI(var1);
            if (var3.isEmpty()) {
               var3 = "0s";
            }

            if (this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR.ROIIIIIIORCOOCIHIOCCCCHCIORCRC()) {
               IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                  .IHCHHRRIIIORORCHIICIIOORCOIOIO()
                  .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                     com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR.SUCCESS,
                     "Shadow Rewind",
                     "Saved the last " + var3
                  );
            }

            this.IOHCRRIIHCIHORROOCHCCORIHRHCII(true);
         } catch (Exception var4) {
            IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
               .IHCHHRRIIIORORCHIICIIOORCOIOIO()
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR.ERROR,
                  "Rewind",
                  "Cannot save recording: " + var4.getMessage()
               );
            com.moonsworth.lunar.client.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, "Rewind");
         }
      }
   }

   public void RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(boolean var1, boolean var2) {
      this.CCCHRRROOCIHCCRCCICICORHIICORI = RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.STOPPED;
      if (this.RIIHHIHIIOOIIROCHOROCHOIOIHICI != null) {
         try {
            this.RIIHHIHIIOOIIROCHOROCHOIOIHICI.stop();
         } catch (IOException var5) {
            var5.printStackTrace();
         }
      }

      if (this.COOCIIRHHHOICIROCROICIRRIRICIR != null) {
         try {
            this.COOCIIRHHHOICIROCROICIRRIRICIR.stop();
         } catch (IOException var4) {
            var4.printStackTrace();
         }
      }

      Runnable var3 = () -> {
         try {
            if (!this.IROOCHICCRORIHCRORROROOIHCORHR && !var2) {
               try {
                  if (this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR.ROIIIIIIORCOOCIHIOCCCCHCIORCRC()) {
                     IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                        .IHCHHRRIIIORORCHIICIIOORCOIOIO()
                        .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR.SUCCESS,
                           "Rewind",
                           "Rewind saved!"
                        );
                  }
               } catch (Exception var4x) {
                  if (!var1) {
                     throw var4x;
                  }
               }
            } else {
               this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR.OCIOHOCHCICCCIOICOIHRRHCICHRIR();
            }
         } catch (Exception var5x) {
            IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
               .IHCHHRRIIIORORCHIICIIOORCOIOIO()
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR.ERROR,
                  "Rewind",
                  "Cannot save recording: " + var5x.getMessage()
               );
            com.moonsworth.lunar.client.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5x, "Rewind");
         }
      };
      if (var1) {
         var3.run();
      } else {
         this.HHRRROCROCCHROHIOCICIHICICCCRO.IHOICRRRORCOCOOCORHOOHHCOIOICR().add(() -> this.COHHOHCHIRRRRROHRHICHHHORHOIRR.execute(var3));
      }
   }

   public boolean isRecording() {
      return this.CCCHRRROOCIHCCRCCICICORHIICORI == RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RECORDING;
   }

   @Override
   public String getId() {
      return "REWIND_HANDLERS";
   }

   @Generated
   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IHIRHRICHCHORICRHIORHOHRIOIIOR() {
      return this.HHRRROCROCCHROHIOCICIHICICCCRO;
   }

   @Generated
   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CIIRRHOICHIIHCHHORIIOICHHOIOCI() {
      return this.IRHRHHROCOHHCCCRCOCHCHCIIHHOIR;
   }

   @Generated
   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ROOCIIHOIICIIHCIIHHRICHCHORHII() {
      return this.CCCHRRROOCIHCCRCCICICORHIICORI;
   }

   @Generated
   public int IIIOIORROHCRHCHHHOCOOCHOROIROH() {
      return this.tick;
   }

   @Generated
   public boolean IICOIOCRRCHOICRRHCCHIHIRHRIIOO() {
      return this.CCOICRRHOHHHHROOOROIHIRHHCCIHI;
   }

   @Generated
   public boolean ROHRCRHORCCHRRCRCHCHOHCHCORRRC() {
      return this.OCHOCOHHHIOCRIOIOOIHOHRIIIHHOC;
   }

   @Generated
   public boolean ROIOHOROCOIRIRRRRRIRIRRIHRRIIH() {
      return this.IROOCHICCRORIHCRORROROOIHCORHR;
   }

   @Generated
   public Map<String, Map<String, Object>> CCIIORHROCCRHCIIROIRHOIORCCHCI() {
      return this.IIROOCCIORCICOOOIRIROCICICOCOR;
   }

   @Generated
   public Map<String, JsonObject> IICCRRRIHCIRHHORHRORORIHHHOORO() {
      return this.OHHCROIIIIOORCCCCOIHICRIOOCHRI;
   }

   @Generated
   public Map<String, CORCOCICIRIOHROHROIIOOHICCHCRR> ORRRHOROCRORCICIOHRIOIOIHIOIRI() {
      return this.RORHHHOCOICROOIRHORIIICOCICCII;
   }
}
