package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import java.io.Serializable;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

@Target({ElementType.ANNOTATION_TYPE, ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
public @interface IRRCCOICORICIHCHRHIHIHROIRHOCR {
   String[] value() default {};

   boolean IIOICHRRHIIHHOIRRRRIRHOOIHHHOC() default false;

   boolean CIORICHIIRIIOOCCIHROORIIORRROI() default false;

   boolean HOHHCCRCIHOIIRRRROHOHHOHOIOIIC() default false;

   class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH implements IRCIIHHICIHRCOCRROCOICRIHHCCHH<IRRCCOICORICIHCHRHIHIHROIRHOCR>, Serializable {
      private static final long HRHHCOCHRCIIRCROHCOHOCRHCCHOIO = 1L;
      protected static final IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH COORHRCHOIOIOIRRIIRIIOIHIIIROI = new IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         Collections.emptySet(), false, false, false, true
      );
      protected final Set<String> RROHROICHICOOOCCCRORCOOCRRHROR;
      protected final boolean HHHROCHHHCIHCHHIOHRRRRRCHCCHCC;
      protected final boolean OHCRIHRROROROHCOHCIHRRIOHRCRHC;
      protected final boolean CCHHCOHCHORHIICIHOOOHCOCCCHHHO;
      protected final boolean OOOORCORRHCRHOOHIRCIROHHOCOHCH;

      protected RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Set<String> var1, boolean var2, boolean var3, boolean var4, boolean var5) {
         if (var1 == null) {
            this.RROHROICHICOOOCCCRORCOOCRRHROR = Collections.emptySet();
         } else {
            this.RROHROICHICOOOCCCRORCOOCRRHROR = var1;
         }

         this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC = var2;
         this.OHCRIHRROROROHCOHCIHRRIOHRCRHC = var3;
         this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO = var4;
         this.OOOORCORRHCRHOOHIRCIROHHOCOHCH = var5;
      }

      public static IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRRCCOICORICIHCHRHIHIHROIRHOCR var0) {
         return var0 == null
            ? COORHRCHOIOIOIRRIIRIIOIHIIIROI
            : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(var0.value()),
               var0.IIOICHRRHIIHHOIRRRRIRHOOIHHHOC(),
               var0.CIORICHIIRIIOOCCIHROORIIORRROI(),
               var0.HOHHCCRCIHOIIRRRROHOHHOHOIOIIC(),
               false
            );
      }

      public static IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         Set<String> var0, boolean var1, boolean var2, boolean var3, boolean var4
      ) {
         return IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0, var1, var2, var3, var4)
            ? COORHRCHOIOIOIRRIIRIIOIHIIIROI
            : new IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, var2, var3, var4);
      }

      public static IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HICORCHRRIIICICIRCCCHRIRCIIORO() {
         return COORHRCHOIOIOIRRIIRIIOIHIIIROI;
      }

      public static IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0, IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
      ) {
         return var0 == null ? var1 : var0.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      }

      public static IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH... var0
      ) {
         IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = null;

         for (IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 : var0) {
            if (var5 != null) {
               var1 = var1 == null ? var5 : var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5);
            }
         }

         return var1;
      }

      public static IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(Set<String> var0) {
         return COORHRCHOIOIOIRRIIRIIOIHIIIROI.OIHCOHRCICCCRHRCROOCIOIRRHHHIH(var0);
      }

      public static IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RHCHRCOCCOIIIHCHRHIRCORHRHRICR(String... var0) {
         return var0.length == 0
            ? COORHRCHOIOIOIRRIIRIIOIHIIIROI
            : COORHRCHOIOIOIRRIIRIIOIHIIIROI.OIHCOHRCICCCRHRCROOCIOIRRHHHIH(OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(var0));
      }

      public static IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IHORHRHORRRCCRHRCRORHOOOIHCROH(boolean var0) {
         return var0 ? COORHRCHOIOIOIRRIIRIIOIHIIIROI.HOHHCIORIHCOCHRHHHCRRRRCIOOHHH() : COORHRCHOIOIOIRRIIRIIOIHIIIROI.HHIOOHIHIIOIRIIIIRRCCHCCHCROIH();
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
      ) {
         if (var1 == null || var1 == COORHRCHOIOIOIRRIIRIIOIHIIIROI) {
            return this;
         }

         if (!var1.OOOORCORRHCRHOOHIRCIROHHOCOHCH) {
            return var1;
         }

         if (IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, var1)) {
            return this;
         }

         Set var2 = HRCHROOHRIHCRCRHRIIROCIRHOIRHH(this.RROHROICHICOOOCCCRORCOOCRRHROR, var1.RROHROICHICOOOCCCRORCOOCRRHROR);
         boolean var3 = this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC || var1.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC;
         boolean var4 = this.OHCRIHRROROROHCOHCIHRRIOHRCRHC || var1.OHCRIHRROROROHCOHCIHRRIOHRCRHC;
         boolean var5 = this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO || var1.CCHHCOHCHORHIICIHOOOHCOCCCHHHO;
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var4, var5, true);
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OIHCOHRCICCCRHRCROOCIOIRRHHHIH(Set<String> var1) {
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            var1,
            this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
            this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
            this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
            this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
         );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCCCROCHCICCROHCOCCRRROCIIHCCH(String... var1) {
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(var1),
            this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
            this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
            this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
            this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
         );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OOHCCHOOIHRCIHCROIHHRCRRRIOOOH() {
         return RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            null,
            this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
            this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
            this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
            this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
         );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HOHHCIORIHCOCHRHHHCRRRRCIOOHHH() {
         return this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC
            ? this
            : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RROHROICHICOOOCCCRORCOOCRRHROR,
               true,
               this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
               this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
               this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HHIOOHIHIIOIRIIIIRRCCHCCHCROIH() {
         return !this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC
            ? this
            : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RROHROICHICOOOCCCRORCOOCRRHROR,
               false,
               this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
               this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
               this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RIRRIIRORORHHIIRRRHHCHRCCCHCIH() {
         return this.OHCRIHRROROROHCOHCIHRRIOHRCRHC
            ? this
            : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RROHROICHICOOOCCCRORCOOCRRHROR,
               this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
               true,
               this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
               this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIHHIROCCHRHCRRICRICCCCRCIRRH() {
         return !this.OHCRIHRROROROHCOHCIHRRIOHRCRHC
            ? this
            : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RROHROICHICOOOCCCRORCOOCRRHROR,
               this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
               false,
               this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
               this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ROOHORCIHCOOOCCOOOCHHOHROOOCCR() {
         return this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO
            ? this
            : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RROHROICHICOOOCCCRORCOOCRRHROR,
               this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
               this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
               true,
               this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CHCCHOIRIRCCCCOHCRHOHIHRHIIHCO() {
         return !this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO
            ? this
            : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RROHROICHICOOOCCCRORCOOCRRHROR,
               this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
               this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
               false,
               this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CRRCHHHCORCCIIHHIIRCCHIIIHHCOR() {
         return this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            ? this
            : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RROHROICHICOOOCCCRORCOOCRRHROR,
               this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
               this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
               this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
               true
            );
      }

      public IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH ROIRORIRRHCHRORHORIOHROOHOIHOH() {
         return !this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            ? this
            : RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.RROHROICHICOOOCCCRORCOOCRRHROR,
               this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
               this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
               this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
               false
            );
      }

      @Override
      public Class<IRRCCOICORICIHCHRHIHIHROIRHOCR> HIHCROOHCOCCCIHCIHCHORCCHIIIIC() {
         return IRRCCOICORICIHCHRHIHIHROIRHOCR.class;
      }

      protected Object readResolve() {
         return IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               this.RROHROICHICOOOCCCRORCOOCRRHROR,
               this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
               this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
               this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
               this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            )
            ? COORHRCHOIOIOIRRIIRIIOIHIIIROI
            : this;
      }

      public Set<String> IOROICOICHOHOOOOHCHRORHICOIICH() {
         return this.RROHROICHICOOOCCCRORCOOCRRHROR;
      }

      public Set<String> CCIOOIHRHCHRHHHCRCHOHHRRCRROCC() {
         return this.OHCRIHRROROROHCOHCIHRRIOHRCRHC ? Collections.emptySet() : this.RROHROICHICOOOCCCRORCOOCRRHROR;
      }

      public Set<String> RIHROICRRCIOIHOIOIOHOOHRICCCHI() {
         return this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO ? Collections.emptySet() : this.RROHROICHICOOOCCCRORCOOCRRHROR;
      }

      public boolean CRIHHHOCRHRCRORCIHCRIIIOICIROI() {
         return this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC;
      }

      public boolean OCOHOIRRRCCIIRIIIIHIROOOIRCHCR() {
         return this.OHCRIHRROROROHCOHCIHRRIOHRCRHC;
      }

      public boolean HRIIORICRCHOOOOCCHORCHROHCROHO() {
         return this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO;
      }

      public boolean COCOHCCIOCIIRRIOHCCHHOOOCIROCH() {
         return this.OOOORCORRHCRHOOHIRCIROHHOCOHCH;
      }

      @Override
      public String toString() {
         return String.format(
            "JsonIgnoreProperties.Value(ignored=%s,ignoreUnknown=%s,allowGetters=%s,allowSetters=%s,merge=%s)",
            this.RROHROICHICOOOCCCRORCOOCRRHROR,
            this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC,
            this.OHCRIHRROROROHCOHCIHRRIOHRCRHC,
            this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO,
            this.OOOORCORRHCRHOOHIRCIROHHOCOHCH
         );
      }

      @Override
      public int hashCode() {
         return this.RROHROICHICOOOCCCRORCOOCRRHROR.size()
            + (this.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC ? 1 : -3)
            + (this.OHCRIHRROROROHCOHCIHRRIOHRCRHC ? 3 : -7)
            + (this.CCHHCOHCHORHIICIHOOOHCOCCCHHHO ? 7 : -11)
            + (this.OOOORCORRHCRHOOHIRCIROHHOCOHCH ? 11 : -13);
      }

      @Override
      public boolean equals(Object var1) {
         if (var1 == this) {
            return true;
         } else {
            return var1 == null
               ? false
               : var1.getClass() == this.getClass()
                  && IRCIIHHICIHRCOCRROCOICRIHHCCHH(this, (IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var1);
         }
      }

      private static boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var0, IRRCCOICORICIHCHRHIHIHROIRHOCR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
      ) {
         return var0.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC == var1.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC
            && var0.OOOORCORRHCRHOOHIRCIROHHOCOHCH == var1.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            && var0.OHCRIHRROROROHCOHCIHRRIOHRCRHC == var1.OHCRIHRROROROHCOHCIHRRIOHRCRHC
            && var0.CCHHCOHCHORHIICIHOOOHCOCCCHHHO == var1.CCHHCOHCHORHIICIHOOOHCOCCCHHHO
            && var0.RROHROICHICOOOCCCRORCOOCRRHROR.equals(var1.RROHROICHICOOOCCCRORCOOCRRHROR);
      }

      private static Set<String> OOOOCCOOOHCHCIIHOIHCRIIOOROHRC(String[] var0) {
         if (var0 != null && var0.length != 0) {
            HashSet var1 = new HashSet(var0.length);

            for (String var5 : var0) {
               var1.add(var5);
            }

            return var1;
         } else {
            return Collections.emptySet();
         }
      }

      private static Set<String> HRCHROOHRIHCRCRHRIIROCIRHOIRHH(Set<String> var0, Set<String> var1) {
         if (var0.isEmpty()) {
            return var1;
         }

         if (var1.isEmpty()) {
            return var0;
         }

         HashSet var2 = new HashSet(var0.size() + var1.size());
         var2.addAll(var0);
         var2.addAll(var1);
         return var2;
      }

      private static boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(Set<String> var0, boolean var1, boolean var2, boolean var3, boolean var4) {
         return var1 == COORHRCHOIOIOIRRIIRIIOIHIIIROI.HHHROCHHHCIHCHHIOHRRRRRCHCCHCC
               && var2 == COORHRCHOIOIOIRRIIRIIOIHIIIROI.OHCRIHRROROROHCOHCIHRRIOHRCRHC
               && var3 == COORHRCHOIOIOIRRIIRIIOIHIIIROI.CCHHCOHCHORHIICIHOOOHCOCCCHHHO
               && var4 == COORHRCHOIOIOIRRIIRIIOIHIIIROI.OOOORCORRHCRHOOHIRCIROHHOCOHCH
            ? var0 == null || var0.size() == 0
            : false;
      }
   }
}
