package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import java.text.DateFormat;
import java.util.Date;

@com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
public class HICHRCOHCCRHOHCICOOCHOIHCCHIRI extends IIHRRHORCRCROCHHOHORCHCROCIHRO<Date> {
   public static final HICHRCOHCCRHOHCICOOCHOIHCCHIRI CIRHCICOHCRIORIIOIHRRIIORORHCR = new HICHRCOHCCRHOHCICOOCHOIHCCHIRI();

   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI() {
      this(null, null);
   }

   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI(Boolean var1, DateFormat var2) {
      super(Date.class, var1, var2);
   }

   public HICHRCOHCCRHOHCICOOCHOIHCCHIRI HHCCIRHCCCIIRHCROHIORHIRHHIORH(Boolean var1, DateFormat var2) {
      return new HICHRCOHCCRHOHCICOOCHOIHCCHIRI(var1, var2);
   }

   protected long RRCRRCORICCHOHHIRCHIROOHIIOHCO(Date var1) {
      return var1 == null ? 0L : var1.getTime();
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      Date var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
   ) {
      if (this.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var3)) {
         var2.IOHCRRIIHCIHORROOCHCCORIHRHCII(this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1));
      } else {
         this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
      }
   }
}
