package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import java.util.Calendar;
import java.util.Date;
import java.util.UUID;

public abstract class OHIIIOHIRIRCCRRIOIICCHHIORRHOH {
   protected static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> IHHRIIIHHOOIOICROOIRIHOICCIIII = new OOCCRCRCOHIIORCCORCRCIRRROIOOR();
   protected static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> ROICOIRIICHROOCHIOROHIHHIRCORH = new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.CRRRICCRROCOHHOHIICIHORCOORRRH();

   public static com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var0, Class<?> var1, boolean var2
   ) {
      if (var1 == null || var1 == Object.class) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.IRCIIHHICIHRCOCRROCOICRIHHCCHH();
      }

      if (var1 == String.class) {
         return ROICOIRIICHROOCHIOROHIHHIRCORH;
      }

      if (var1.isPrimitive()) {
         var1 = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.OHHHIRCIIIRRCORHHRICIRCOORORCH(
            var1
         );
      }

      if (var1 == Integer.class) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(5, var1);
      } else if (var1 == Long.class) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(6, var1);
      } else if (var1.isPrimitive() || Number.class.isAssignableFrom(var1)) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(8, var1);
      } else if (var1 == Class.class) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(3, var1);
      } else if (Date.class.isAssignableFrom(var1)) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(1, var1);
      } else if (Calendar.class.isAssignableFrom(var1)) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(2, var1);
      } else if (var1 == UUID.class) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(8, var1);
      } else if (var1 == byte[].class) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(7, var1);
      } else {
         return var2 ? new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(8, var1) : null;
      }
   }

   @Deprecated
   public static com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var0, Class<?> var1
   ) {
      if (var1 != null) {
         if (var1 == Enum.class) {
            return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.IRCIIHHICIHRCOCRROCOICRIHHCCHH();
         }

         if (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HIORIIIIOCCCRCHCOROROCCOIOOIIR(
            var1
         )) {
            return OHIIIOHIRIRCCRRIOIICCHHIORRHOH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1,
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
                  var0, var1
               )
            );
         }
      }

      return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(8, var1);
   }

   public static com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR var0,
      Class<?> var1,
      com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      if (var1 != null) {
         if (var1 == Enum.class) {
            return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.IRCIIHHICIHRCOCRROCOICRIHHCCHH();
         }

         if (com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HIORIIIIOCCCRCHCOROROCCOIOOIIR(
            var1
         )) {
            return OHIIIOHIRIRCCRRIOIICCHHIORRHOH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1,
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
                  var0, var1
               ),
               OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1, var2)
            );
         }
      }

      return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(8, var1);
   }

   @Deprecated
   public static com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> HHHOCHIRHOORHCRCCICCCIRRHOIORI() {
      return IHHRIIIHHOOIOICROOIRIHOICCIIII;
   }

   public static class CRRRICCRROCOHHOHIICIHORCOORRRH extends HCHRIROHHHCORIOCROOCHRCIOROOCI<Object> {
      public CRRRICCRROCOHHOHIICIHORCOORRRH() {
         super(String.class, false);
      }

      @Override
      public void serialize(
         Object var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         var2.OICHRIIHIORHOOOIOCHHOCRORIHIOH((String)var1);
      }
   }

   public static class HHCCIRHCCCIIRHCROHIORHIRHHIORH extends HCHRIROHHHCORIOCROOCHRCIOROOCI<Object> {
      protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO ICCHHHIOCIHORIHRROIRCHCICORRRO;
      protected final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO RRRIHCRHRHCCORIROIROIOCOCHCIHR;

      protected HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         Class<?> var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO var2
      ) {
         super(var1, false);
         this.ICCHHHIOCIHORIHRROIRCHCICORRRO = var2;
         this.RRRIHCRHRHCCORIROIROIOCOCHCIHR = null;
      }

      protected HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         Class<?> var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO var3
      ) {
         super(var1, false);
         this.ICCHHHIOCIHORIHRROIRCHCICORRRO = var2;
         this.RRRIHCRHRHCCORIROIROIOCOCHCIHR = var3;
      }

      public static OHIIIOHIRIRCCRRIOIICCHHIORRHOH.HHCCIRHCCCIIRHCROHIORHIRHHIORH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         Class<?> var0,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO var1
      ) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var0, var1);
      }

      public static OHIIIOHIRIRCCRRIOIICCHHIORRHOH.HHCCIRHCCCIIRHCROHIORHIRHHIORH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         Class<?> var0,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IIHRRHORCRCROCHHOHORCHCROCIHRO var2
      ) {
         return new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var0, var1, var2);
      }

      @Override
      public void serialize(
         Object var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         if (var3.CRICCOOHHHCHOORCICOCOHIHOIRHOO(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IOHIHIIHCCCCCIHRORIOIOORCIOHII.WRITE_ENUMS_USING_TO_STRING
         )) {
            var2.OICHRIIHIORHOOOIOCHHOCRORIHIOH(var1.toString());
         } else {
            Enum var4 = (Enum)var1;
            if (this.RRRIHCRHRHCCORIROIROIOCOCHCIHR != null) {
               var2.HHCCIRHCCCIIRHCROHIORHIRHHIORH(this.RRRIHCRHRHCCORIROIROIOCOCHCIHR.CRRRICCRROCOHHOHIICIHORCOORRRH(var4));
            } else if (var3.CRICCOOHHHCHOORCICOCOHIHOIRHOO(
               com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IOHIHIIHCCCCCIHRORIOIOORCIOHII.WRITE_ENUM_KEYS_USING_INDEX
            )) {
               var2.OICHRIIHIORHOOOIOCHHOCRORIHIOH(String.valueOf(var4.ordinal()));
            } else {
               var2.HHCCIRHCCCIIRHCROHIORHIRHHIORH(this.ICCHHHIOCIHORIHRROIRCHCICORRRO.CRRRICCRROCOHHOHIICIHORCOORRRH(var4));
            }
         }
      }
   }

   public static class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends HCHRIROHHHCORIOCROOCHRCIOROOCI<Object> {
      protected transient com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI _dynamicSerializers = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRHOICRIOOCOIOIIHICRCOOCCRHCHR();

      public IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
         super(String.class, false);
      }

      Object readResolve() {
         this._dynamicSerializers = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.HRHOICRIOOCOIOIIHICRCOOCCRHCHR();
         return this;
      }

      @Override
      public void serialize(
         Object var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         Class var4 = var1.getClass();
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var5 = this._dynamicSerializers;
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO var6 = var5.IIHROHOIOHICCRRHRICHCIHRCROOIO(
            var4
         );
         if (var6 == null) {
            var6 = this._findAndAddDynamic(var5, var4, var3);
         }

         var6.serialize(var1, var2, var3);
      }

      @Override
      public void acceptJsonFormatVisitor(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
      ) {
         this.visitStringFormat(var1, var2);
      }

      protected com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<Object> _findAndAddDynamic(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI var1,
         Class<?> var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         if (var2 == Object.class) {
            OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = new OHIIIOHIRIRCCRRIOIICCHHIORRHOH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(8, var2);
            this._dynamicSerializers = var1.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(var2, var5);
            return var5;
         }

         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CRRRICCRROCOHHOHIICIHORCOORRRH var4 = var1.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
            var2, var3, null
         );
         if (var1 != var4.OCROIICCICHCIOHIRCOIIOHCCIRCHI) {
            this._dynamicSerializers = var4.OCROIICCICHCIOHIRCOIIOHCCIRCHI;
         }

         return var4.IHCIHCRHRHCIIOIHRCCOCRCOIIOIHR;
      }
   }

   public static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends HCHRIROHHHCORIOCROOCHRCIOROOCI<Object> {
      static final int RHRCIORHHIHOIHROHOHOHORORCIROH = 1;
      static final int HHORCIRCIHIHRHRCHIHIICHOROIIOI = 2;
      static final int CIOHICHRIIOCIROHICIICCIHHCHICI = 3;
      static final int IOCCRHIHICICOIOHOHCOIORHIRRROI = 4;
      static final int CHCRHCOOHRIRCCORIHCORIICCHIHIO = 5;
      static final int OCHRHCIHHHIHICCROOCCRCCIOCORCC = 6;
      static final int RIHRRCCOHCCCOHOHRIOCHHCIHORICH = 7;
      static final int RCOHICRCOHOORCCRHIHORIRRORICOH = 8;
      protected final int RCIRHRORRHOOOOCCHORIOROIHRIRIR;

      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(int var1, Class<?> var2) {
         super(var2, false);
         this.RCIRHRORRHOOOOCCHORIOROIHRIRIR = var1;
      }

      @Override
      public void serialize(
         Object var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         switch (this.RCIRHRORRHOOOOCCHORIOROIHRIRIR) {
            case 1:
               var3.IRCIIHHICIHRCOCRROCOICRIHHCCHH((Date)var1, var2);
               break;
            case 2:
               var3.IRCIIHHICIHRCOCRROCOICRIHHCCHH(((Calendar)var1).getTimeInMillis(), var2);
               break;
            case 3:
               var2.OICHRIIHIORHOOOIOCHHOCRORIHIOH(((Class)var1).getName());
               break;
            case 4:
               String var6;
               if (var3.CRICCOOHHHCHOORCICOCOHIHOIRHOO(
                  com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IOHIHIIHCCCCCIHRORIOIOORCIOHII.WRITE_ENUMS_USING_TO_STRING
               )) {
                  var6 = var1.toString();
               } else {
                  Enum var5 = (Enum)var1;
                  if (var3.CRICCOOHHHCHOORCICOCOHIHOIRHOO(
                     com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IOHIHIIHCCCCCIHRORIOIOORCIOHII.WRITE_ENUM_KEYS_USING_INDEX
                  )) {
                     var6 = String.valueOf(var5.ordinal());
                  } else {
                     var6 = var5.name();
                  }
               }

               var2.OICHRIIHIORHOOOIOCHHOCRORIHIOH(var6);
               break;
            case 5:
            case 6:
               var2.ROCHRRCORRCOOOOOCOICOCROIIHIHH(((Number)var1).longValue());
               break;
            case 7:
               String var4 = var3.RROOOCRCORCHCRRIRCRIIHHHHROOHO().RCCIOIICIOCROOHHORRHROIRRIOCOC().encode((byte[])var1);
               var2.OICHRIIHIORHOOOIOCHHOCRORIHIOH(var4);
               break;
            case 8:
            default:
               var2.OICHRIIHIORHOOOIOCHHOCRORIHIOH(var1.toString());
         }
      }
   }
}
