package com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import java.lang.reflect.Type;
import java.util.HashMap;

public class ROOCOCCCIRHHHIRIOIHHHHRHIICHHR {
   protected static final HashMap<String, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?>> OHORHIOOHCICIRCHRCRHCIHHCHHHIH = new HashMap<>();

   protected ROOCOCCCIRHHHIRIOIHHHHRHIICHHR() {
   }

   public static com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> IHHOICIRHRHHRRCROIOROOCCCOROIR(
      Class<?> var0
   ) {
      return OHORHIOOHCICIRCHRCRHCIHHCHHHIH.get(var0.getName());
   }

   static {
      OHORHIOOHCICIRCHRCRHCIHHCHHHIH.put(boolean[].class.getName(), new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH());
      OHORHIOOHCICIRCHRCRHCIHHCHHHIH.put(
         byte[].class.getName(),
         new com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI()
      );
      OHORHIOOHCICIRCHRCRHCIHHCHHHIH.put(char[].class.getName(), new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.IRCIIHHICIHRCOCRROCOICRIHHCCHH());
      OHORHIOOHCICIRCHRCRHCIHHCHHHIH.put(short[].class.getName(), new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH());
      OHORHIOOHCICIRCHRCRHCIHHCHHHIH.put(int[].class.getName(), new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RRCRRCORICCHOHHIRCHIROOHIIOHCO());
      OHORHIOOHCICIRCHRCRHCIHHCHHHIH.put(long[].class.getName(), new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI());
      OHORHIOOHCICIRCHRCRHCIHHCHHHIH.put(float[].class.getName(), new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.CRRRICCRROCOHHOHIICIHORCOORRRH());
      OHORHIOOHCICIRCHRCRHCIHHCHHHIH.put(double[].class.getName(), new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH());
   }

   @com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
   public static class CRRRICCRROCOHHOHIICIHORCOORRRH extends ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR<float[]> {
      private static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI CRIOIIRHHRRIHRRCCOHOOIIIOROORH = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHIOHOCHCOHIIOHHOOIRIOCIHCRRI()
         .HOIRIRROOCICRHIRIHCIRCOHCIHHHO(float.class);

      public CRRRICCRROCOHHOHIICIHORCOORRRH() {
         super(float[].class);
      }

      public CRRRICCRROCOHHOHIICIHORCOORRRH(
         ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
         Boolean var3
      ) {
         super(var1, var2, var3);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1, Boolean var2
      ) {
         return new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.CRRRICCRROCOHHOHIICIHORCOORRRH(this, var1, var2);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI RCCRIHIHOIICHCIICCOHHHIRICOHHC() {
         return CRIOIIRHHRRIHRRCCOHOOIIIOROORH;
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> IOIHIORCHIHOOHIHIRHOHIRHRCIOIO() {
         return null;
      }

      public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, float[] var2
      ) {
         return var2.length == 0;
      }

      public boolean HHCCIRHCCCIIRHCROHIORHIRHHIORH(float[] var1) {
         return var1.length == 1;
      }

      public final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         float[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = var1.length;
         if (var4 == 1 && this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var3)) {
            this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
         } else {
            var2.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var1, var4);
            this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
            var2.CCROCOHIICIIRIOIRRHHORRCHOIIRC();
         }
      }

      public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         float[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = 0;

         for (int var5 = var1.length; var4 < var5; var4++) {
            var2.IRIRICIHHCOICHHCHCOCCHHOROOCHH(var1[var4]);
         }
      }

      @Deprecated
      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR getSchema(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, Type var2
      ) {
         return this.createSchemaNode("array", true).RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("items", this.createSchemaNode("number"));
      }

      @Override
      public void acceptJsonFormatVisitor(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
      ) {
         this.visitArrayFormat(
            var1,
            var2,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.NUMBER
         );
      }
   }

   @com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
   public static class HHCCIRHCCCIIRHCROHIORHIRHHIORH
      extends com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<double[]> {
      private static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI CCHCICRRHRCCCORRHIIRCORHRRIHOO = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHIOHOCHCOHIIOHHOOIRIOCIHCRRI()
         .HOIRIRROOCICRHIRIHCIRCOHCIHHHO(double.class);

      public HHCCIRHCCCIIRHCROHIORHIRHHIORH() {
         super(double[].class);
      }

      protected HHCCIRHCCCIIRHCROHIORHIRHHIORH(
         ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
         Boolean var3
      ) {
         super(var1, var2, var3);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1, Boolean var2
      ) {
         return new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH(this, var1, var2);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CORCOCICIRIOHROHROIIOOHICCHCRR<?> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var1
      ) {
         return this;
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI RCCRIHIHOIICHCIICCOHHHIRICOHHC() {
         return CCHCICRRHRCCCORRHIIRCORHRRIHOO;
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> IOIHIORCHIHOOHIHIRHOHIRHRCIOIO() {
         return null;
      }

      public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, double[] var2
      ) {
         return var2.length == 0;
      }

      public boolean RIROICHCRROROHCCROOCCCCOCHCCRI(double[] var1) {
         return var1.length == 1;
      }

      public final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         double[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = var1.length;
         if (var4 == 1 && this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var3)) {
            this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
         } else {
            var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, 0, var1.length);
         }
      }

      public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         double[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = 0;

         for (int var5 = var1.length; var4 < var5; var4++) {
            var2.OCIOROHIHRROROOIRRHRRCCHHRRRHI(var1[var4]);
         }
      }

      @Deprecated
      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR getSchema(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, Type var2
      ) {
         return this.createSchemaNode("array", true).RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("items", this.createSchemaNode("number"));
      }

      @Override
      public void acceptJsonFormatVisitor(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
      ) {
         this.visitArrayFormat(
            var1,
            var2,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.NUMBER
         );
      }
   }

   @com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
   public static class HRCHROOHRIHCRCRHRIIROCIRHOIRHH extends ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR<short[]> {
      private static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI IHOHROROIHRRHICIHRIRRIHIIICIRR = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHIOHOCHCOHIIOHHOOIRIOCIHCRRI()
         .HOIRIRROOCICRHIRIHCIRCOHCIHHHO(short.class);

      public HRCHROOHRIHCRCRHRIIROCIRHOIRHH() {
         super(short[].class);
      }

      public HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
         ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
         Boolean var3
      ) {
         super(var1, var2, var3);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1, Boolean var2
      ) {
         return new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH(this, var1, var2);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI RCCRIHIHOIICHCIICCOHHHIRICOHHC() {
         return IHOHROROIHRRHICIHRIRRIHIIICIRR;
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> IOIHIORCHIHOOHIHIRHOHIRHRCIOIO() {
         return null;
      }

      public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, short[] var2
      ) {
         return var2.length == 0;
      }

      public boolean CRRRICCRROCOHHOHIICIHORCOORRRH(short[] var1) {
         return var1.length == 1;
      }

      public final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         short[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = var1.length;
         if (var4 == 1 && this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var3)) {
            this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
         } else {
            var2.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var1, var4);
            this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
            var2.CCROCOHIICIIRIOIRRHHORRCHOIIRC();
         }
      }

      public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         short[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = 0;

         for (int var5 = var1.length; var4 < var5; var4++) {
            var2.CORHHROICCOCRHRCCOOHCRCRHICHOI(var1[var4]);
         }
      }

      @Deprecated
      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR getSchema(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, Type var2
      ) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.HICRRICCHCCROOHHCHOCOCCHOIHHOC var3 = this.createSchemaNode(
            "array", true
         );
         return var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("items", this.createSchemaNode("integer"));
      }

      @Override
      public void acceptJsonFormatVisitor(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
      ) {
         this.visitArrayFormat(
            var1,
            var2,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.INTEGER
         );
      }
   }

   @com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
   public static class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends HCHRIROHHHCORIOCROOCHRCIOROOCI<char[]> {
      public IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
         super(char[].class);
      }

      public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, char[] var2
      ) {
         return var2.length == 0;
      }

      public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         char[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         if (var3.CRICCOOHHHCHOORCICOCOHIHOIRHOO(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IOHIHIIHCCCCCIHRORIOIOORCIOHII.WRITE_CHAR_ARRAYS_AS_JSON_ARRAYS
         )) {
            var2.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var1, var1.length);
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var1);
            var2.CCROCOHIICIIRIOIRRHHORRCHOIIRC();
         } else {
            var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, 0, var1.length);
         }
      }

      public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         char[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var4
      ) {
         boolean var5 = var3.CRICCOOHHHCHOORCICOCOHIHOIRHOO(
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IOHIHIIHCCCCCIHRORIOIOORCIOHII.WRITE_CHAR_ARRAYS_AS_JSON_ARRAYS
         );
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var6;
         if (var5) {
            var6 = var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var2,
               var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.START_ARRAY
               )
            );
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var1);
         } else {
            var6 = var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var2,
               var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  var1, com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OHHRIOHROOIHOROCIRHCHORIHRRRRI.VALUE_STRING
               )
            );
            var2.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, 0, var1.length);
         }

         var4.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var6);
      }

      private final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var1, char[] var2
      ) {
         int var3 = 0;

         for (int var4 = var2.length; var3 < var4; var3++) {
            var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2, var3, 1);
         }
      }

      @Deprecated
      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR getSchema(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, Type var2
      ) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.HICRRICCHCCROOHHCHOCOCCHOIHHOC var3 = this.createSchemaNode(
            "array", true
         );
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.HICRRICCHCCROOHHCHOCOCCHOIHHOC var4 = this.createSchemaNode(
            "string"
         );
         var4.HIHCHCORCCRCOHCRROHOHOOCHOROCC("type", "string");
         return var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("items", var4);
      }

      @Override
      public void acceptJsonFormatVisitor(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
      ) {
         this.visitArrayFormat(
            var1,
            var2,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.STRING
         );
      }
   }

   protected abstract static class OOROOCCIRCCRHOIOIORIHCHHOOCCOR<T>
      extends com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<T> {
      protected OOROOCCIRCCRHOIOIORIHCHHOOCCOR(Class<T> var1) {
         super(var1);
      }

      protected OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
         ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR<T> var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
         Boolean var3
      ) {
         super(var1, var2, var3);
      }

      @Override
      public final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CORCOCICIRIOHROHROIIOOHICCHCRR<?> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var1
      ) {
         return this;
      }
   }

   @com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
   public static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
      extends com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<boolean[]> {
      private static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI IHOIRRROHICROCROCOOCHOIICROHOH = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHIOHOCHCOHIIOHHOOIRIOCIHCRRI()
         .HOIRIRROOCICRHIRIHCIRCOHCIHHHO(Boolean.class);

      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
         super(boolean[].class);
      }

      protected RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
         Boolean var3
      ) {
         super(var1, var2, var3);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1, Boolean var2
      ) {
         return new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, var1, var2);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CORCOCICIRIOHROHROIIOOHICCHCRR<?> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var1
      ) {
         return this;
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI RCCRIHIHOIICHCIICCOHHHIRICOHHC() {
         return IHOIRRROHICROCROCOOCHOIICROHOH;
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> IOIHIORCHIHOOHIHIRHOHIRHRCIOIO() {
         return null;
      }

      public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, boolean[] var2
      ) {
         return var2.length == 0;
      }

      public boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(boolean[] var1) {
         return var1.length == 1;
      }

      public final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         boolean[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = var1.length;
         if (var4 == 1 && this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var3)) {
            this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
         } else {
            var2.OHHRIOHROOIHOROCIRHCHORIHRRRRI(var1, var4);
            this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
            var2.CCROCOHIICIIRIOIRRHHORRCHOIIRC();
         }
      }

      public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         boolean[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = 0;

         for (int var5 = var1.length; var4 < var5; var4++) {
            var2.writeBoolean(var1[var4]);
         }
      }

      @Deprecated
      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR getSchema(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, Type var2
      ) {
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.HICRRICCHCCROOHHCHOCOCCHOIHHOC var3 = this.createSchemaNode(
            "array", true
         );
         var3.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("items", this.createSchemaNode("boolean"));
         return var3;
      }

      @Override
      public void acceptJsonFormatVisitor(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
      ) {
         this.visitArrayFormat(
            var1,
            var2,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.BOOLEAN
         );
      }
   }

   @com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
   public static class RIOOCHICIHRHOHCCCCCHOCCCOHCRHI extends ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.OOROOCCIRCCRHOIOIORIHCHHOOCCOR<long[]> {
      private static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI ORCRCRHOICHOCOOCHCRCORHIORROHH = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHIOHOCHCOHIIOHHOOIRIOCIHCRRI()
         .HOIRIRROOCICRHIRIHCIRCOHCIHHHO(long.class);

      public RIOOCHICIHRHOHCCCCCHOCCCOHCRHI() {
         super(long[].class);
      }

      public RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(
         ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
         Boolean var3
      ) {
         super(var1, var2, var3);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1, Boolean var2
      ) {
         return new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(this, var1, var2);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI RCCRIHIHOIICHCIICCOHHHIRICOHHC() {
         return ORCRCRHOICHOCOOCHCRCORHIORROHH;
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> IOIHIORCHIHOOHIHIRHOHIRHRCIOIO() {
         return null;
      }

      public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, long[] var2
      ) {
         return var2.length == 0;
      }

      public boolean HRCHROOHRIHCRCRHRIIROCIRHOIRHH(long[] var1) {
         return var1.length == 1;
      }

      public final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         long[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = var1.length;
         if (var4 == 1 && this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var3)) {
            this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
         } else {
            var2.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, 0, var1.length);
         }
      }

      public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         long[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = 0;

         for (int var5 = var1.length; var4 < var5; var4++) {
            var2.IOHCRRIIHCIHORROOCHCCORIHRHCII(var1[var4]);
         }
      }

      @Deprecated
      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR getSchema(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, Type var2
      ) {
         return this.createSchemaNode("array", true).RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("items", this.createSchemaNode("number", true));
      }

      @Override
      public void acceptJsonFormatVisitor(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
      ) {
         this.visitArrayFormat(
            var1,
            var2,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.NUMBER
         );
      }
   }

   @com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
   public static class RRCRRCORICCHOHHIRCHIROOHIIOHCO
      extends com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<int[]> {
      private static final com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI OCCHRHOCIIIRIOOCRCHOHICRIRRHRO = com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR.IHHIOHOCHCOHIIOHHOOIRIOCIHCRRI()
         .HOIRIRROOCICRHIRIHCIRCOHCIHHHO(int.class);

      public RRCRRCORICCHOHHIRCHIROOHIIOHCO() {
         super(int[].class);
      }

      protected RRCRRCORICCHOHHIRCHIROOHIIOHCO(
         ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RRCRRCORICCHOHHIRCHIROOHIIOHCO var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
         Boolean var3
      ) {
         super(var1, var2, var3);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH var1, Boolean var2
      ) {
         return new ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.RRCRRCORICCHOHHIRCHIROOHIIOHCO(this, var1, var2);
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CIOHHCORHRCCRICCCORIHCRHCCCRRR.CORCOCICIRIOHROHROIIOOHICCHCRR<?> IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR var1
      ) {
         return this;
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI RCCRIHIHOIICHCIICCOHHHIRICOHHC() {
         return OCCHRHOCIIIRIOOCRCHOHICRIRRHRO;
      }

      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RHOCHHIRRCHHHOHOIRROIROHHHIHIO<?> IOIHIORCHIHOOHIHIRHOHIRHRCIOIO() {
         return null;
      }

      public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, int[] var2
      ) {
         return var2.length == 0;
      }

      public boolean RCCCROCHCICCROHCOCCRRROCIIHCCH(int[] var1) {
         return var1.length == 1;
      }

      public final void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         int[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = var1.length;
         if (var4 == 1 && this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(var3)) {
            this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3);
         } else {
            var2.CRRRICCRROCOHHOHIICIHORCOORRRH(var1, 0, var1.length);
         }
      }

      public void IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         int[] var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO var2,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var3
      ) {
         int var4 = 0;

         for (int var5 = var1.length; var4 < var5; var4++) {
            var2.CORHHROICCOCRHRCCOOHCRCRHICHOI(var1[var4]);
         }
      }

      @Deprecated
      @Override
      public com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IIRHCHHOICHRICOOCRORCCIOOIHOIR getSchema(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC var1, Type var2
      ) {
         return this.createSchemaNode("array", true).RCIRROCCCIIHCIHCCRHHCCHOHHHCHH("items", this.createSchemaNode("integer"));
      }

      @Override
      public void acceptJsonFormatVisitor(
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1,
         com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI var2
      ) {
         this.visitArrayFormat(
            var1,
            var2,
            com.moonsworth.lunar.lib.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.INTEGER
         );
      }
   }
}
