package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.HashMap;
import java.util.Map;
import org.jetbrains.annotations.NotNull;

@com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 1)
public class HRCHROOHRIHCRCRHRIIROCIRHOIRHH
   extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   private final Map<String, Map<String, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH>> OHCRRRCICOOCHRIHHOOROOORRHHRIR = new HashMap<>();
   private long COOHRHOICOCCIOHCOCHRIRORIIRIOR = 0L;

   public HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      super(var1);
   }

   public void CRCIIOHHHICOOCCCICIHCRHOHICCIC() {
      Map var1 = this.OHCRRRCICOOCHRIHHOOROOORRHHRIR.get(this.IIHCCIRHCCICIRHICOCHCCRIHIIOHC());
      if (var1 != null) {
         for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var3 : var1.values()) {
            if (var3.selected) {
               var3.RCIIIHHICHOROIIROORCOCIRRCROIR = true;
            }
         }
      }
   }

   public boolean CCHHCIRHICHHHHRRIHIORCCORCCIHR(String var1, String var2) {
      return this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, this.IIHCCIRHCCICIRHICOCHCCRIHIIOHC(), var2).selected;
   }

   public void COIHORRCHRRCHOCIRHHRRIOIHRIHCC(String var1, String var2) {
      this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, this.IIHCCIRHCCICIRHICOCHCCRIHIIOHC(), var2).selected = true;
   }

   public void CRRRICCRROCOHHOHIICIHORCOORRRH(String var1, String var2, String var3) {
      this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var1, var2, var3).selected = true;
   }

   public boolean IHROORCCHHHROHCCHHROIRRROOIRHC(String var1) {
      Map var2 = this.OHCRRRCICOOCHRIHHOOROOORRHHRIR.get(var1);
      if (var2 != null) {
         for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var4 : var2.values()) {
            if (var4.selected) {
               return true;
            }
         }
      }

      return false;
   }

   public void RHCCOIHOHRIHRRIIRHICRRROCICORR(String var1) {
      this.OHCRRRCICOOCHRIHHOOROOORRHHRIR.remove(var1);
   }

   public String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var1, int var2, int var3, int var4, int var5, String var6, boolean var7) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var8 = this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(
         "textinput", this.IIHCCIRHCCICIRHICOCHCCRIHIIOHC(), var1
      );
      var8.width = var4;
      var8.height = var5;
      int var9 = var7 ? 2 : 1;
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var4, var5, var8, var9);
      if (var8.selected) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var8);
      }

      boolean var10 = (IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime() - this.COOHRHOICOCCIOHCOCHRIRORIIRIOR) % 650L
         < 325L;
      boolean var11 = (var8.RHCRCHICRORHICCHIRROIHIHOCHHRR < var8.text.length() || var8.text.length() >= var8.ROHRIRHHHRCORCIRCHCICIHCRICIHR) && var8.selected;
      String var12 = this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var6, var8, var10, var11);
      if (this.OHRHHRCRORICRHRCHROHRROCRIIHRR().ROORIIHRCRHCIROIHRHIIICHOHCOOH) {
         this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, var3, var4, var5, var7, var8, var10, var11, var12);
      }

      if (var8.RCIIIHHICHOROIIROORCOCIRRCROIR) {
         var8.selected = false;
         var8.RCIIIHHICHOROIIROORCOCIRRCROIR = false;
      }

      if (this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IIRHCHHOICHRICOOCRORCCIOOIHOIR(var2 - 4 * var9, var3 - 4 * var9, var4 + 8 * var9, var5 + 8 * var9)) {
         this.IRHRCIRRRIRHRIRRRRRCIICRHRHIRR().RRRCCCRRRCOHCCCCHCIHOHHHHRRROC();
      }

      return var8.text;
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      int var1,
      int var2,
      int var3,
      int var4,
      boolean var5,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var6,
      boolean var7,
      boolean var8,
      String var9
   ) {
      if (var5) {
         this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IIHRRHORCRCROCHHOHORCHCROCIHRO(var1 - 2, var2 - 2, var3 + 4, var4 + 4);
      }

      this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.OCOHORHCROHICRRIHCIHHRRCIHICRI(var1, var2, var3, var4);
      double var10 = var4 / 10.0;
      this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.RRROICRCRIRHIRRRIIIRCROHIOHIOI();
      this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.CORCOCICIRIOHROHROIIOOHICCHCRR(var1, var2, var3, var4);
      int var12 = (int)(
         var1
            + this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO
                  .getStringWidth(
                     var6.text
                        .substring(var6.ORHOOHRCIHIORCCRCOOOOCIROHRHCO, Math.max(var6.ORHOOHRCIHIORCCRCOOOOCIROHRHCO, var6.RHCRCHICRORHICCHIRROIHIHOCHHRR))
                  )
               * var10
      );
      if (var6.selected && var6.IRCHOCHCRIOORIOOHCHOIOCHOHRROR != var6.RHCRCHICRORHICCHIRROIHIHOCHHRR) {
         int var13 = (int)(
            var1
               + this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO
                     .getStringWidth(
                        var6.text
                           .substring(var6.ORHOOHRCIHIORCCRCOOOOCIROHRHCO, Math.max(var6.ORHOOHRCIHIORCCRCOOOOCIROHRHCO, var6.IRCHOCHCRIOORIOOHCHOIOCHOHRROR))
                     )
                  * var10
         );
         this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var13 + 1, var2, var12 - var13, var4, -865704193);
      }

      this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var9, var1 + 1, var2 + 1, !var6.text.isEmpty() || var6.selected, (float)var10);
      this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HOCIOOIOHOHRRCCOROHCRRHORICCCH();
      if (var7 && var8) {
         this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var12, var2, 1, var4, -3750202);
      }
   }

   @NotNull
   private String RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var2,
      boolean var3,
      boolean var4
   ) {
      String var5 = var2.text;
      if (var5.isEmpty() && !var2.selected) {
         var5 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.GRAY + var1;
      } else if (var2.selected) {
         if (var2.IRCHOCHCRIOORIOOHCHOIOCHOHRROR != var2.RHCRCHICRORHICCHIRROIHIHOCHHRR) {
            int var6 = Math.min(var2.RHCRCHICRORHICCHIRROIHIHOCHHRR, var2.IRCHOCHCRIOORIOOHCHOIOCHOHRROR);
            int var7 = Math.max(var2.RHCRCHICRORHICCHIRROIHIHOCHHRR, var2.IRCHOCHCRIOORIOOHCHOIOCHOHRROR);
            var5 = var2.text.substring(var2.ORHOOHRCIHIORCCRCOOOOCIROHRHCO, Math.max(var2.ORHOOHRCIHIORCCRCOOOOCIROHRHCO, var6))
               + com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.BLUE
               + var2.text.substring(var6, var7)
               + com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RESET
               + var2.text.substring(var7);
         } else {
            var5 = var2.text.substring(var2.ORHOOHRCIHIORCCRCOOOOCIROHRHCO);
         }

         if (var3 && !var4) {
            var5 = var5 + "_";
         }
      }

      return var5;
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var1
   ) {
      for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var3 : this.CCOHHHCRRROOOHHORICOCRRHCCRORR()
         .HIRIRCOCCHCIHHOCRRORHCHICHCIHI()) {
         if (var3.RICRHCHRRCCIICRCHICCIHHHCIICOH() && var3.ORHOOCIRIHHOCHHRIRIOIIICHOORCR()) {
            var1.selected = false;
         }

         if (this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HRHCRRHICCRHOICIHCCIIROCHHHICH() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4
            )
          {
            var4.lunar$handleKeyEventOnState(var1, var3);
         }

         this.COOHRHOICOCCIOHCOCHRIRORIIRIOR = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
      }

      this.CCOHHHCRRROOOHHORICOCRRHCCRORR().HIRIRCOCCHCIHHOCRRORHCHICHCIHI().clear();
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      int var1,
      int var2,
      int var3,
      int var4,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var5,
      int var6
   ) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var7 = this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO
         .CIOHHCORHRCCRICCCORIHCRHCCCRRR(var1 - 4 * var6, var2 - 4 * var6, var3 + 8 * var6, var4 + 8 * var6);
      if (var7 != null) {
         if (var5.selected
            && this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HRHCRRHICCRHOICIHCCIIROCHHHICH() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var8
            )
          {
            var8.lunar$handleMousePressOnState(var5, var7.HCOCOROIHHIHIROIOCHOHICHCRHRIO(), var7.x() - var1 + 6, var7.y() - var2);
         }

         var5.selected = true;
         var5.RCIIIHHICHOROIIROORCOCIRRCROIR = false;
         this.COOHRHOICOCCIOHCOCHRIRORIIRIOR = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getSystemTime();
      }
   }

   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      String var1, String var2, String var3
   ) {
      Map var4 = this.OHCRRRCICOOCHRIHHOOROOORRHHRIR.computeIfAbsent(var2, var0 -> new HashMap<>());
      return var4.computeIfAbsent(
         var1 + "-" + var3,
         var0 -> new com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH(
            0, 0, 1000
         )
      );
   }
}
