package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

@com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 1)
public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      super(var1);
   }

   public int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var1, int var2, int var3, int var4, int var5) {
      boolean var6 = this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IIRHCHHOICHRICOOCRORCCIOOIHOIR(var2 - 2, var3 - 2, var4 + 4, var5 + 4);
      byte var7 = 0;
      if (this.CROHOOHHCCHOORCOIIRROIHCCCIICO().HOCOHRCIHCCHRRIOIRCHOCCHRCRICC() && var6) {
         if (this.OHRHHRCRORICRHRCHROHRROCRIIHRR().ROORIIHRCRHCIROIHRHIIICHOHCOOH) {
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 - 2, var3 - 2, var4 + 4, var5 + 4, this.getTheme().panelBorderOut);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 + var4, var3 - 1, 1, var5 + 1, this.getTheme().panelBorderLeft);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 - 1, var3 + var5, var4 + 2, 1, this.getTheme().panelBorderLeft);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 - 1, var3 - 1, var4 + 2, 1, this.getTheme().panelBorderRight);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 - 1, var3 - 1, 1, var5 + 2, this.getTheme().panelBorderRight);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2, var3, var4, var5, this.getTheme().insetBackground);
         }

         var7 = 1;
      } else {
         this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IIHRRHORCRCROCHHOHORCHCROCIHRO(var2, var3, var4, var5);
      }

      if (var1 != null) {
         float var8 = this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var4, var5);
         this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2 + var4 / 2 + var7 - 1, var3 + var5 / 2 + var7 - 1, false, var8);
      }

      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2 - 2, var3 - 2, var4 + 4, var5 + 4);
   }

   public int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var1, int var2, int var3, int var4, int var5, int var6) {
      boolean var7 = this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IIRHCHHOICHRICOOCRORCCIOOIHOIR(var2 - 2, var3 - 2, var4 + 4, var5 + 4);
      byte var8 = 0;
      if (this.CROHOOHHCCHOORCOIIRROIHCCCIICO().HOCOHRCIHCCHRRIOIRCHOCCHRCRICC() && var7) {
         if (this.OHRHHRCRORICRHRCHROHRROCRIIHRR().ROORIIHRCRHCIROIHRHIIICHOHCOOH) {
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 - 2, var3 - 2, var4 + 4, var5 + 4, this.getTheme().panelBorderOut);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 + var4, var3 - 1, 1, var5 + 1, this.getTheme().panelBorderLeft);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 - 1, var3 + var5, var4 + 2, 1, this.getTheme().panelBorderLeft);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 - 1, var3 - 1, var4 + 2, 1, this.getTheme().panelBorderRight);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2 - 1, var3 - 1, 1, var5 + 2, this.getTheme().panelBorderRight);
            this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var2, var3, var4, var5, this.getTheme().insetBackground);
         }

         var8 = 1;
      } else {
         this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IIHRRHORCRCROCHHOHORCHCROCIHRO(var2, var3, var4, var5);
      }

      if (var1 != null) {
         float var9 = this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var4 - 2, var5);
         if (var6 < 2) {
            var6 = 2;
         }

         this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO
            .IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2 + var6 + var8 - 1, (int)(var3 + var5 / 2 + var8 - 2 - 2.0F * var9), false, var9);
      }

      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IHHCHHHCRIHOOCOIOOCRIIICIOROIR(var2 - 2, var3 - 2, var4 + 4, var5 + 4);
   }
}
