package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.client.util.HRHRORCIRICHCCCCCHICOOICIRHRIO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;

@com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 1)
public class RRCRRCORICCHOHHIRCHIROOHIIOHCO
   extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   private boolean CIHIIRCOHCHHCRRHOCRIOCCOHHHROH;
   private HRHRORCIRICHCCCCCHICOOICIRHRIO CIOIORCCIIRHCOROOOCIOHOCCOOHIR;

   public RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      super(var1);
   }

   @Override
   public void end() {
      this.HIOHCICIOHHORHCORIIOCHIIIHCIHC();
   }

   public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(int var1, int var2, int var3, int var4, int var5) {
      if (!this.HIIRHRRHIIOCIOCROCHCOIHCCCRIHO().RICRIRRCOHRCOCRRHHCRHRROOIOHHR(var1, var2, var3, var4)) {
         if (this.OHRHHRCRORICRHRCHROHRROCRIIHRR().ROORIIHRCRHCIROIHRHIIICHOHCOOH) {
            this.IHCCRHOROROOHRCRRIOHCRIORRIRHI()
               .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var5x -> var5x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var1 + var3, var2 + var4, var5));
            this.IHCCRHOROROOHRCRRIOHCRIORRIRHI()
               .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
                  var6 -> {
                     if (!this.CIHIIRCOHCHHCRRHOCRIOCCOHHHROH) {
                        this.CIHIIRCOHCHHCRRHOCRIOCCOHHHROH = true;
                        com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRICCOOHHHCHOORCICOCOHIHOIRHOO(
                           var6.HHIIOHOORHHCCHRHHRCIORCROORCOI()
                        );
                     }

                     com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                        var1, var2, var3, var4, var5
                     );
                     if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 5 && IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION < 29) {
                        if (this.CIOIORCCIIRHCOROOOCIOHOCCOOHIR == null) {
                           this.CIOIORCCIIRHCOROOOCIOHOCCOOHIR = HRHRORCIRICHCCCCCHICOOICIRHRIO.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(var1, var2, var3, var4);
                        } else {
                           this.CIOIORCCIIRHCOROOOCIOHOCCOOHIR = HRHRORCIRICHCCCCCHICOOICIRHRIO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              this.CIOIORCCIIRHCOROOOCIOHOCCOOHIR, HRHRORCIRICHCCCCCHICOOICIRHRIO.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO(var1, var2, var3, var4)
                           );
                        }
                     }
                  }
               );
         }
      }
   }

   public void HIOHCICIOHHORHCORIIOCHIIIHCIHC() {
      if (this.CIHIIRCOHCHHCRRHOCRIOCCOHHHROH) {
         this.CIHIIRCOHCHHCRRHOCRIOCCOHHHROH = false;
         this.IHCCRHOROROOHRCRRIOHCRIORRIRHI()
            .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               var1 -> {
                  Runnable var2 = () -> com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI(
                     var1.HHIIOHOORHHCCHRHHRCIORCROORCOI()
                  );
                  if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 5 && IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION < 29) {
                     this.OIHRHOCIIIROHCRCCOOOCOOOOOHIHR().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.CIOIORCCIIRHCOROOOCIOHOCCOOHIR, var2);
                     this.OIHRHOCIIIROHCRCCOOOCOOOOOHIHR().RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.CIOIORCCIIRHCOROOOCIOHOCCOOHIR, 0.0F);
                     this.CIOIORCCIIRHCOROOOCIOHOCCOOHIR = null;
                  } else {
                     var2.run();
                  }
               }
            );
      }
   }
}
