package com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import it.unimi.dsi.fastutil.ints.Int2ObjectArrayMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.objects.Object2IntArrayMap;
import it.unimi.dsi.fastutil.objects.Object2IntMap;
import java.util.Optional;
import javax.annotation.Nullable;
import lombok.Generated;
import org.apache.commons.lang3.text.WordUtils;
import org.jetbrains.annotations.NotNull;

public enum RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   OCEAN("ocean", 0, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, -16752657),
   PLAINS("plains", 1, HHCCIRHCCCIIRHCROHIORHIRHHIORH.PLAINS, -10510539),
   DESERT("desert", 2, HHCCIRHCCCIIRHCROHIORHIRHHIORH.DESERT, -1516367),
   MOUNTAINS("mountains", 3, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   FOREST("forest", 4, HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -11629531),
   TAIGA("taiga", 5, HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, -11637939),
   SWAMP("swamp", 6, HHCCIRHCCCIIRHCROHIORHIRHHIORH.SWAMP, -12295900),
   RIVER("river", 7, HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIVER, -16752657),
   NETHER_WASTES("nether_wastes", 8, HHCCIRHCCCIIRHCROHIORHIRHHIORH.NETHER, -7729393),
   THE_END("the_end", 9, HHCCIRHCCCIIRHCROHIORHIRHHIORH.THEEND, -9568091),
   FROZEN_OCEAN("frozen_ocean", 10, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, true, -6308109),
   FROZEN_RIVER("frozen_river", 11, HHCCIRHCCCIIRHCROHIORHIRHHIORH.RIVER, true, -6308109),
   SNOWY_TUNDRA("snowy_tundra", 12, HHCCIRHCCCIIRHCROHIORHIRHHIORH.ICY, true, -6308109),
   SNOWY_MOUNTAINS("snowy_mountains", 13, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, true, -6308109),
   MUSHROOM_FIELDS("mushroom_fields", 14, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MUSHROOM, -9080700),
   MUSHROOM_FIELD_SHORE("mushroom_field_shore", 15, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MUSHROOM, -9080700),
   BEACH("beach", 16, HHCCIRHCCCIIRHCROHIORHIRHHIORH.BEACH, -1516367),
   DESERT_HILLS("desert_hills", 17, HHCCIRHCCCIIRHCROHIORHIRHHIORH.DESERT, -1516367),
   WOODED_HILLS("wooded_hills", 18, HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -11629531),
   TAIGA_HILLS("taiga_hills", 19, HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, -11637939),
   MOUNTAIN_EDGE("mountain_edge", 20, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   JUNGLE("jungle", 21, HHCCIRHCCCIIRHCROHIORHIRHHIORH.JUNGLE, -14913786),
   JUNGLE_HILLS("jungle_hills", 22, HHCCIRHCCCIIRHCROHIORHIRHHIORH.JUNGLE, -14913786),
   JUNGLE_EDGE("jungle_edge", 23, HHCCIRHCCCIIRHCROHIORHIRHHIORH.JUNGLE, -14913786),
   DEEP_OCEAN("deep_ocean", 24, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, true, -16752657),
   STONE_SHORE("stone_shore", 25, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   SNOWY_BEACH("snowy_beach", 26, HHCCIRHCCCIIRHCROHIORHIRHHIORH.BEACH, true, -6308109),
   BIRCH_FOREST("birch_forest", 27, HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -3223858),
   BIRCH_FOREST_HILLS("birch_forest_hills", 28, HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -3223858),
   DARK_FOREST("dark_forest", 29, HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -13145823),
   SNOWY_TAIGA("snowy_taiga", 30, HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, true, -6308109),
   SNOWY_TAIGA_HILLS("snowy_taiga_hills", 31, HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, true, -6308109),
   GIANT_TREE_TAIGA("giant_tree_taiga", 32, HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, -11637939),
   GIANT_TREE_TAIGA_HILLS("giant_tree_taiga_hills", 33, HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, -11637939),
   WOODED_MOUNTAINS("wooded_mountains", 34, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   SAVANNA("savanna", 35, HHCCIRHCCCIIRHCROHIORHIRHHIORH.SAVANNA, -8225734),
   SAVANNA_PLATEAU("savanna_plateau", 36, HHCCIRHCCCIIRHCROHIORHIRHHIORH.SAVANNA, -8225734),
   BADLANDS("badlands", 37, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MESA, -5022683),
   WOODED_BADLANDS_PLATEAU("wooded_badlands_plateau", 38, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MESA, -5022683),
   BADLANDS_PLATEAU("badlands_plateau", 39, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MESA, -5022683),
   SMALL_END_ISLANDS("small_end_islands", 40, HHCCIRHCCCIIRHCROHIORHIRHHIORH.THEEND, -9568091),
   END_MIDLANDS("end_midlands", 41, HHCCIRHCCCIIRHCROHIORHIRHHIORH.THEEND, -9568091),
   END_HIGHLANDS("end_highlands", 42, HHCCIRHCCCIIRHCROHIORHIRHHIORH.THEEND, -9568091),
   END_BARRENS("end_barrens", 43, HHCCIRHCCCIIRHCROHIORHIRHHIORH.THEEND, -9568091),
   WARM_OCEAN("warm_ocean", 44, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, -16711727),
   LUKEWARM_OCEAN("lukewarm_ocean", 45, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, -16711727),
   COLD_OCEAN("cold_ocean", 46, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, -6308109),
   DEEP_WARM_OCEAN("deep_warm_ocean", 47, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, -16711727),
   DEEP_LUKEWARM_OCEAN("deep_lukewarm_ocean", 48, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, -16711727),
   DEEP_COLD_OCEAN("deep_cold_ocean", 49, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, -6308109),
   DEEP_FROZEN_OCEAN("deep_frozen_ocean", 50, HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCEAN, true, -6308109),
   THE_VOID("the_void", 127, HHCCIRHCCCIIRHCROHIORHIRHHIORH.NONE, -9568091),
   SUNFLOWER_PLAINS("sunflower_plains", 129, HHCCIRHCCCIIRHCROHIORHIRHHIORH.PLAINS, -10240),
   DESERT_LAKES("desert_lakes", 130, HHCCIRHCCCIIRHCROHIORHIRHHIORH.DESERT, -1516367),
   GRAVELLY_MOUNTAINS("gravelly_mountains", 131, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   FLOWER_FOREST("flower_forest", 132, HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -32787),
   TAIGA_MOUNTAINS("taiga_mountains", 133, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -11637939),
   SWAMP_HILLS("swamp_hills", 134, HHCCIRHCCCIIRHCROHIORHIRHHIORH.SWAMP, true, -12295900),
   ICE_SPIKES("ice_spikes", 140, HHCCIRHCCCIIRHCROHIORHIRHHIORH.ICY, true, -6308109),
   MODIFIED_JUNGLE("modified_jungle", 149, HHCCIRHCCCIIRHCROHIORHIRHHIORH.JUNGLE, -14913786),
   MODIFIED_JUNGLE_EDGE("modified_jungle_edge", 151, HHCCIRHCCCIIRHCROHIORHIRHHIORH.JUNGLE, -14913786),
   TALL_BIRCH_FOREST("tall_birch_forest", 155, HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -3223858),
   TALL_BIRCH_HILLS("tall_birch_hills", 156, HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -3223858),
   DARK_FOREST_HILLS("dark_forest_hills", 157, HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -13145823),
   SNOWY_TAIGA_MOUNTAINS("snowy_taiga_mountains", 158, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, true, -6308109),
   GIANT_SPRUCE_TAIGA("giant_spruce_taiga", 160, HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, -11637939),
   GIANT_SPRUCE_TAIGA_HILLS("giant_spruce_taiga_hills", 161, HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, -11637939),
   MODIFIED_GRAVELLY_MOUNTAINS("modified_gravelly_mountains", 162, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   SHATTERED_SAVANNA("shattered_savanna", 163, HHCCIRHCCCIIRHCROHIORHIRHHIORH.SAVANNA, -8225734),
   SHATTERED_SAVANNA_PLATEAU("shattered_savanna_plateau", 164, HHCCIRHCCCIIRHCROHIORHIRHHIORH.SAVANNA, -8225734),
   ERODED_BADLANDS("eroded_badlands", 165, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MESA, -5022683),
   MODIFIED_WOODED_BADLANDS_PLATEAU("modified_wooded_badlands_plateau", 166, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MESA, -5022683),
   MODIFIED_BADLANDS_PLATEAU("modified_badlands_plateau", 167, HHCCIRHCCCIIRHCROHIORHIRHHIORH.MESA, -5022683),
   BAMBOO_JUNGLE("bamboo_jungle", 168, HHCCIRHCCCIIRHCROHIORHIRHHIORH.JUNGLE, -9925062),
   BAMBOO_JUNGLE_HILLS("bamboo_jungle_hills", 169, HHCCIRHCCCIIRHCROHIORHIRHHIORH.JUNGLE, -9925062),
   SOUL_SAND_VALLEY("soul_sand_valley", HHCCIRHCCCIIRHCROHIORHIRHHIORH.NETHER, -10270148),
   CRIMSON_FOREST("crimson_forest", HHCCIRHCCCIIRHCROHIORHIRHHIORH.NETHER, -7729393),
   WARPED_FOREST("warped_forest", HHCCIRHCCCIIRHCROHIORHIRHHIORH.NETHER, -15758473),
   BASALT_DELTAS("basalt_deltas", HHCCIRHCCCIIRHCROHIORHIRHHIORH.NETHER, -11118485),
   DRIPSTONE_CAVES("dripstone_caves", HHCCIRHCCCIIRHCROHIORHIRHHIORH.UNDERGROUND, -7368817),
   LUSH_CAVES("lush_caves", HHCCIRHCCCIIRHCROHIORHIRHHIORH.UNDERGROUND, -7368817),
   SNOWY_PLAINS("snowy_plains", HHCCIRHCCCIIRHCROHIORHIRHHIORH.ICY, true, -6308109),
   OLD_GROWTH_BIRCH_FOREST("old_growth_birch_forest", HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -3223858),
   OLD_GROWTH_PINE_TAIGA("old_growth_pine_taiga", HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, -11637939),
   OLD_GROWTH_SPRUCE_TAIGA("old_growth_pine_taiga", HHCCIRHCCCIIRHCROHIORHIRHHIORH.TAIGA, -11637939),
   WOODED_BADLANDS("wooded_badlands", HHCCIRHCCCIIRHCROHIORHIRHHIORH.MESA, -5022683),
   WINDSWEPT_HILLS("windswept_hills", HHCCIRHCCCIIRHCROHIORHIRHHIORH.EXTREME_HILLS, -11629531),
   WINDSWEPT_GRAVELLY_HILLS("windswept_gravelly_hills", HHCCIRHCCCIIRHCROHIORHIRHHIORH.EXTREME_HILLS, -11629531),
   WINDSWEPT_FOREST("windswept_forest", HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -11629531),
   WINDSWEPT_SAVANNA("windswept_savanna", HHCCIRHCCCIIRHCROHIORHIRHHIORH.SAVANNA, -8225734),
   SPARSE_JUNGLE("sparse_jungle", HHCCIRHCCCIIRHCROHIORHIRHHIORH.JUNGLE, -14913786),
   MEADOW("meadow", HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   GROVE("grove", HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -11629531),
   SNOWY_SLOPES("snowy_slopes", HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, true, -6308109),
   FROZEN_PEAKS("frozen_peaks", HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   JAGGED_PEAKS("jagged_peaks", HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   STONY_PEAKS("stony_peaks", HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   STONY_SHORE("stony_shore", HHCCIRHCCCIIRHCROHIORHIRHHIORH.BEACH, -7368817),
   DEEP_DARK("deep_dark", HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -7368817),
   MANGROVE_SWAMP("mangrove_swamp", HHCCIRHCCCIIRHCROHIORHIRHHIORH.SWAMP, -12295900),
   CHERRY_GROVE("cherry_grove", HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -4097635),
   PALE_GARDEN("pale_garden", HHCCIRHCCCIIRHCROHIORHIRHHIORH.FOREST, -4605511),
   SULFUR_CAVES("sulfur_caves", HHCCIRHCCCIIRHCROHIORHIRHHIORH.MOUNTAIN, -1644384);

   private static final Int2ObjectMap<RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> LEGACY_REGISTRY = new Int2ObjectArrayMap(SOUL_SAND_VALLEY.ordinal());
   private static final Object2IntMap<IRCIIHHICIHRCOCRROCOICRIHHCCHH> REVERSE_LOOKUP = new Object2IntArrayMap(values().length);
   private final String displayName;
   private final String resourceLocation;
   private final Integer legacyId;
   private final HHCCIRHCCCIIRHCROHIORHIRHHIORH category;
   private final boolean isSnowy;
   private final int color;

   RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var3, HHCCIRHCCCIIRHCROHIORHIRHHIORH var4, boolean var5, int var6) {
      this(var3, null, var4, var5, var6);
   }

   RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var3, Integer var4, HHCCIRHCCCIIRHCROHIORHIRHHIORH var5, boolean var6, int var7) {
      this.displayName = WordUtils.capitalize(var3.replace("_", " "), null);
      this.resourceLocation = var3;
      this.legacyId = var4;
      this.category = var5;
      this.isSnowy = var6;
      this.color = var7;
   }

   RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var3, Integer var4, HHCCIRHCCCIIRHCROHIORHIRHHIORH var5, int var6) {
      this(var3, var4, var5, false, var6);
   }

   RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var3, HHCCIRHCCCIIRHCROHIORHIRHHIORH var4, int var5) {
      this(var3, var4, false, var5);
   }

   public Optional<Integer> getLegacyId() {
      return Optional.ofNullable(this.legacyId);
   }

   @Nullable
   public static RCIRROCCCIIHCIHCCRHHCCHOHHHCHH fromBiomeBridgeOrNull(@Nullable IRCIIHHICIHRCOCRROCOICRIHHCCHH var0) {
      if (var0 == null) {
         return null;
      }

      int var1 = REVERSE_LOOKUP.getInt(var0);
      if (var1 != -1) {
         return values()[var1];
      }

      Optional var2 = var0.bridge$getBiomeID();
      if (var2.isPresent()) {
         RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = (RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)LEGACY_REGISTRY.get((Integer)var2.get());
         if (var3 != null) {
            REVERSE_LOOKUP.put(var0, var3.ordinal());
            return var3;
         }
      }

      for (RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var6 : values()) {
         if (var0.bridge$getBiomeName().equals("minecraft:" + var6.resourceLocation)) {
            REVERSE_LOOKUP.put(var0, var6.ordinal());
            return var6;
         }
      }

      return null;
   }

   @NotNull
   public static RCIRROCCCIIHCIHCCRHHCCHOHHHCHH fromBiomeBridge(@Nullable IRCIIHHICIHRCOCRROCOICRIHHCCHH var0) {
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = fromBiomeBridgeOrNull(var0);
      return var1 == null ? PLAINS : var1;
   }

   @Generated
   public String getDisplayName() {
      return this.displayName;
   }

   @Generated
   public String getResourceLocation() {
      return this.resourceLocation;
   }

   @Generated
   public HHCCIRHCCCIIRHCROHIORHIRHHIORH getCategory() {
      return this.category;
   }

   @Generated
   public boolean isSnowy() {
      return this.isSnowy;
   }

   @Generated
   public int getColor() {
      return this.color;
   }

   static {
      REVERSE_LOOKUP.defaultReturnValue(-1);

      for (RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 : values()) {
         if (var3.legacyId != null) {
            LEGACY_REGISTRY.put(var3.legacyId, var3);
         }
      }
   }
}
