package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private final List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> CRCHCIOCCIRROOCICIRIRRORCCOOIC = new ArrayList<>();
   private final List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> OROOOIOIIHOORIIHHIRRHIRROOIHOI = new ArrayList<>();

   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var1, byte[] var2
   ) {
      this.CRCHCIOCCIRROOCICIRIRRORCCOOIC
         .add(
            new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               var1, var2
            )
         );
      return this;
   }

   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RHOCHHIRRCHHHOHOIRROIROHHHIHIO(
      String var1, String var2
   ) {
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2.getBytes(StandardCharsets.UTF_8));
   }

   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      this.CRCHCIOCCIRROOCICIRIRRORCCOOIC.addAll(var1.CRCHCIOCCIRROOCICIRIRRORCCOOIC);
      this.OROOOIOIIHOORIIHHIRRHIRROOIHOI.addAll(var1.OROOOIOIIHOORIIHHIRRHIRROOIHOI);
      return this;
   }

   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var1, Exception var2
   ) {
      this.OROOOIOIIHOORIIHHIRRHIRROOIHOI
         .add(
            new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1, var2
            )
         );
      com.moonsworth.lunar.client.ROOCOCCCIRHHHIRIOIHHHHRHIICHHR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2, "FpsDataWithError");
      return this;
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(ZipOutputStream var1) {
      HashSet var2 = new HashSet();
      ArrayList var3 = new ArrayList<>(this.CRCHCIOCCIRROOCICIRIRRORCCOOIC);
      if (!this.OROOOIOIIHOORIIHHIRRHIRROOIHOI.isEmpty()) {
         String var4 = this.OROOOIOIIHOORIIHHIRRHIRROOIHOI
            .stream()
            .map(var0 -> var0.RROHHORIOCRHHRHCCIORRCCHCCHOIR + "\n" + var0.ORCIICIRRCHIHIIRCOCCHOIHIICRRR.getMessage())
            .collect(Collectors.joining("\n\n"));
         var3.add(
            new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               "errors.txt", var4.getBytes(StandardCharsets.UTF_8)
            )
         );
      }

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RHOCHHIRRCHHHOHOIRROIROHHHIHIO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var5 : var3) {
         String var6 = this.RRCRRCORICCHOHHIRCHIROOHIIOHCO(var5.CCHCRHOOICHCCIHIHROCIRRCRRRCIR, var2);
         var2.add(var6);
         var1.putNextEntry(new ZipEntry(var6));
         var1.write(var5.ICHICHRHOROIIHOHIHRRHHHHIIORHH);
         var1.closeEntry();
      }
   }

   private String RRCRRCORICCHOHHIRCHIROOHIIOHCO(String var1, Set<String> var2) {
      int var3 = -1;
      String var4 = var1;
      String var5 = var1.substring(0, var1.lastIndexOf(46));
      String var6 = var1.substring(var1.lastIndexOf(46));

      while (var2.contains(var4)) {
         var4 = var5 + "-" + ++var3 + "." + var6;
      }

      return var4;
   }

   private record IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
      private final String CCHCRHOOICHCCIHIHROCIRRCRRRCIR;
      private final byte[] ICHICHRHOROIIHOHIHRRHHHHIIORHH;

      private IRCIIHHICIHRCOCRROCOICRIHHCCHH(String var1, byte[] var2) {
         this.CCHCRHOOICHCCIHIHROCIRRCRRRCIR = var1;
         this.ICHICHRHOROIIHOHIHRRHHHHIIORHH = var2;
      }

      public String OIHOOHOHHOICRIOOCICCHCHHOROCIH() {
         return this.CCHCRHOOICHCCIHIHROCIRRCRRRCIR;
      }

      public byte[] RIHHCROROROHHROICCIRHOICCOOIHC() {
         return this.ICHICHRHOROIIHOHIHRRHHHHIIORHH;
      }
   }

   private record RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      private final String RROHHORIOCRHHRHCCIORRCCHCCHOIR;
      private final Exception ORCIICIRRCHIHIIRCOCCHOIHIICRRR;

      private RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var1, Exception var2) {
         this.RROHHORIOCRHHRHCCIORRCCHCCHOIR = var1;
         this.ORCIICIRRCHIHIIRCOCCHOIHIICRRR = var2;
      }

      public String IIOHCOCOCCOHHHIHIOHHIROHRRCHOC() {
         return this.RROHHORIOCRHHRHCCIORRCCHCCHOIR;
      }

      public Exception COCIRIICCCRICIOHOICRRRCOOCOOCO() {
         return this.ORCIICIRRCHIHIIRCOCCHOIHIICRRR;
      }
   }
}
