package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HHCCIRHCCCIIRHCROHIORHIRHHIORH;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.webosr.javascript.CallbackJS;
import java.io.IOException;
import java.util.Map.Entry;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   implements HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH,
   com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private boolean IOIHORCIRCCHOROHRHCRHROHRHRRHH;
   private static boolean CORRRIRCCCCOCHRORIHHOOHORRCRCI;
   private static boolean CHOCRHHRIHIHHRCICRICHHIRHIHCIC;

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH() {
      reset();
      CCRHRROIOIIRROHCOOCCCRRIOIHHHO(false);
      CORRRIRCCCCOCHRORIHHOOHORRCRCI = false;
      CHOCRHHRIHIHHRCICRICHHIRHIHCIC = false;
   }

   public static void reset() {
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((RRCRRCORICCHOHHIRCHIROOHIIOHCO<?>)null);
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO)null
      );
      ROIOROHRIHRRHIHRRRIHHHIICCHIOI(false);
      HHCCIRHCCCIIRHCROHIORHIRHHIORH(null);
      RRCRRCORICCHOHHIRCHIROOHIIOHCO(null);
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((CRRRICCRROCOHHOHIICIHORCOORRRH<?>)null);
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
      if (var0 != null) {
         HCOCRCHORROORHOHHRHOCCOHORHIIR();
         HIIOIRCRHHCRCHHOHCICIICICOICIC();
      }
   }

   @Override
   public HHCCIRHCCCIIRHCROHIORHIRHHIORH CORROIRHRRIHCRHIROHHORCCHIIRCO() {
      return !HOOHIHIOIHHCIHCCHIOOHOOIRICHOO().HRIICOIOIIIIRIHHOICRHOIIRCIRIC() ? null : ORIRCRCHCROOOORHHIHCOCRCROOIHR().CCRRRICCIIHCOIHOICHORCHIROICIR();
   }

   @Override
   public void RRCRRCORICCHOHHIRCHIROOHIIOHCO(double var1, double var3) {
      if (RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.isCtrlKeyDown() && !ORIRCRCHCROOOORHHIHCOCRCROOIHR().IHHCRHRIORROROHIIIRHOORHHRHOII()) {
         if (var3 < 0.0) {
            com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROCOCHICHORROOHCHOCIIICOHCHIOC()
               .HICHRCOHCCRHOHCICOOCHOIHCCHIRI("rewind-scroll", true);
         } else {
            com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROCOCHICHORROOHCHOCIIICOHCHIOC()
               .HICHRCOHCCRHOHCICOOCHOIHCCHIRI("rewind-scroll", false);
         }
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      int var2,
      int var3,
      int var4,
      int var5
   ) {
      if (!CORRRIRCCCCOCHRORIHHOOHORRCRCI && !CHOCRHHRIHIHHRCICRICHHIRHIHCIC) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var6 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
         if (var6 != null && !var6.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
            if (var4 != 1 && var4 != 2) {
               if (!this.IOIHORCIRCCHOROHRHCRHROHRHRRHH
                  && var4 == 0
                  && var1 == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_ESCAPE
                  && var6.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().IOHHOICRCORHRCICOCHIORRHHHCORC()) {
                  ORIRCRCHCROOOORHHIHCOCRCROOIHR().RCHCIOICIRCHRROHROCRORRRRHHCRO();
               }

               this.IOIHORCIRCCHOROHRHCRHROHRHRRHH = ORIRCRCHCROOOORHHIHCOCRCROOIHR().IHHCRHRIORROROHIIIRHOORHHRHOII();
            } else {
               com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var7 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
               if (var7 != null) {
                  HRCHROOHRIHCRCRHRIIROCIRHOIRHH var8 = var6.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().HOHHCCRIOOCRIRCIHHCOHOCIICCOOO();
                  CRRRICCRROCOHHOHIICIHORCOORRRH var9 = HHRRHIRCRORHOHRRIIHCRHROIIRCCO() == null
                     ? null
                     : CRHROHHHCIHHCOHCOORCRIHHIICROR(HHRRHIRCRORHOHRRIIHCRHROIIRCCO().getId());
                  if (var9 == null) {
                     RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((RRCRRCORICCHOHHIRCHIROOHIIOHCO<?>)null);
                  }

                  Entry var10 = var9 != null && HHRRHIRCRORHOHRRIIHCRHROIIRCCO() != null
                     ? var7.CRRHOHRIOIICIHOHRROHOCOIIOICCH().get(HHRRHIRCRORHOHRRIIHCRHROIIRCCO().getId())
                     : null;
                  if (var10 == null) {
                     RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((RRCRRCORICCHOHHIRCHIROOHIIOHCO<?>)null);
                  }

                  this.IOIHORCIRCCHOROHRHCRHROHRHRRHH = var6.IHHCRHRIORROROHIIIRHOORHHRHOII();
                  if (!var6.IHHCRHRIORROROHIIIRHOORHHRHOII()
                     || var1 == com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_ESCAPE) {
                     var6.OCCCRIHRIIOCCCOIIHHIOCCRICCIRI()
                        .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                              var1,
                              RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.isCtrlKeyDown(),
                              RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.isShiftKeyDown(),
                              RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.HHCHCIOROIIHRIORRROIIICHCHORHO()
                           ),
                           new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(
                              var6, var7, var8, var9, var10
                           ),
                           var4 == 2
                        );
                  }
               }
            }
         }
      }
   }

   @CallbackJS("updatePreviewWindow")
   public static void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Float var0, Float var1) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (var2 != null) {
         var2.HICRRICCHCCROOHHCHOCOCCHOIHHOC(var0, var1);
      }
   }

   @CallbackJS("updateEditorLayout")
   public static void IRCIIHHICIHRCOCRROCOICRIHHCCHH(Float var0, Float var1) {
      com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
         .HIROIHOHCHRCCRRCROCIIHOCHICCOO();
      if (var0 != null) {
         var2.HHOHOHOICROHIORCOOOIRCCRIOCROI().OHHRIOHROOIHOROCIRHCHORIHRRRRI(var0);
      }

      if (var1 != null) {
         var2.ICCOORHORCRRCHIOROCOIROHICCOHR().OHHRIOHROOIHOROCIRHCHORIHRRRRI(var1);
      }
   }

   @CallbackJS("exit")
   public static void exit() {
      ORIRCRCHCROOOORHHIHCOCRCROOIHR().RCHCIOICIRCHRROHROCRORRRRHHCRO();
   }

   @CallbackJS("pause")
   public static void IRIHOIRCHIRRCRIOORCOICORHHORHH(boolean var0) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var1.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
         if (var2 != null) {
            if (!var0) {
               RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO)null
               );
               HCOCRCHORROORHOHHRHOCCOHORHIIR();
               if (ORIRCRCHCROOOORHHIHCOCRCROOIHR().OCCOIHHIIICROCOOOOIIHHRCHCOCIC()) {
                  var2.ROCHRRCORRCOOOOOCOICOCROIIHIHH(0);
               }
            }

            var2.RCOHCCHCRHIIIICRIHCOICIHHCCOOC(var0);
            ROIRCHOCCHRHCOIHOHRIICICOOICIR();
         }
      }
   }

   @CallbackJS("save")
   public static void save() {
      try {
         OHIOOHHOOCHICHRCCCOHOOCRCHIRHH().HCOIOHCCHIHRCHCCICCIRCIOHCRIHH(false);
         IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .IHCHHRRIIIORORCHIICIIOORCOIOIO()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CORCOCICIRIOHROHROIIOOHICCHCRR.SUCCESS, "Rewind", "Project saved!")
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BOTTOM_RIGHT
            );
      } catch (IOException var1) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
            .IHCHHRRIIIORORCHIICIIOORCOIOIO()
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CORCOCICIRIOHROHROIIOOHICCHCRR.ERROR, "Rewind", "Error while saving replay: " + var1.getMessage())
            .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.BOTTOM_RIGHT
            );
         throw new RuntimeException(var1);
      }
   }

   @CallbackJS("undo")
   public static void undo() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var0.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         ORIRCRCHCROOOORHHIHCOCRCROOIHR().HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().HOHHCCRIOOCRIRCIHHCOHOCIICCOOO().undo();
         ORIRCRCHCROOOORHHIHCOCRCROOIHR().RRCRRIIRHHRCCICHOCOIHROROCICHC(true);
         ORIRCRCHCROOOORHHIHCOCRCROOIHR().RRRCCRHRIHCOHRCCHRCOOCCOIIOCHO();
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OIRICCRROORRCCICIIOIHHRICOHCIR();
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCHCCIRRCRRCRIIOHHHRHCOOOCRRRR();
      }
   }

   @CallbackJS("redo")
   public static void redo() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var0.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         ORIRCRCHCROOOORHHIHCOCRCROOIHR().HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().HOHHCCRIOOCRIRCIHHCOHOCIICCOOO().redo();
         ORIRCRCHCROOOORHHIHCOCRCROOIHR().RRCRRIIRHHRCCICHOCOIHROROCICHC(true);
         ORIRCRCHCROOOORHHIHCOCRCROOIHR().RRRCCRHRIHCOHRCCHRCOOCCOIIOCHO();
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.OIRICCRROORRCCICIIOIHHRICOHCIR();
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CCHCCIRRCRRCRIIOHHHRHCOOOCRRRR();
      }
   }

   @CallbackJS("forward")
   public static void forward() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var0.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
         if (var1 != null) {
            var1.ROCHRRCORRCOOOOOCOICOCROIIHIHH(var1.IHRHCHOCCHHICIIOIORIRCIHHHHHIH() + 1);
            ROIRCHOCCHRHCOIHOHRIICICOOICIR();
         }
      }
   }

   @CallbackJS("backward")
   public static void OCHHOCHHOCIIIHCOIHORIIIHCORORO() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var0.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
         if (var1 != null) {
            var1.ROCHRRCORRCOOOOOCOICOCROIIHIHH(Math.max(0, var1.IHRHCHOCCHHICIIOIORIRCIHHHHHIH() - 1));
            ROIRCHOCCHRHCOIHOHRIICICOOICIR();
         }
      }
   }

   @CallbackJS("goStart")
   public static void CCHHIHIOOICCHHRIHCRHOIIRRHHICC() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var0.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
         if (var1 != null) {
            var1.ROCHRRCORRCOOOOOCOICOCROIIHIHH(0);
            ROIRCHOCCHRHCOIHOHRIICICOOICIR();
         }
      }
   }

   @CallbackJS("reload")
   public static void reload() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var0.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$schedule(() -> {
            try {
               var0.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(var0.HRCHICHIOHOROOHHHOHROHCICCROIO().IIIROORHIIRICRHHOIHIROIOIHOOHI());
            } catch (IOException var2) {
               throw new RuntimeException(var2);
            }
         });
         ROIRCHOCCHRHCOIHOHRIICICOOICIR();
      }
   }

   @CallbackJS("goEnd")
   public static void ORRRRIIICHOIRORIHHHOCIHCRCOHRO() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var0.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
         if (var1 != null) {
            var1.ROCHRRCORRCOOOOOCOICOCROIIHIHH(var1.ORCCCOIHIHOHHIROIIOORRROORHIRH() - 1);
            ROIRCHOCCHRHCOIHOHRIICICOOICIR();
         }
      }
   }

   @CallbackJS("setPlayhead")
   public static void RHOCHHIRRCHHHOHOIRROIROHHHIHIO(Integer var0) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var1.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI()
            .bridge$schedule(
               () -> {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
                  if (var2 != null) {
                     boolean var3 = IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR()
                           .HIROIHOHCHRCCRRCROCIIHOCHICCOO()
                           .IIIHCCRHICIROORROCOHCIORRCOIHR()
                           .get()
                        && var1.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().OHCCRHHHRCHCCIIRRICHCIICIRHCRC() != null
                        && var1.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().OHCCRHHHRCHCCIIRRICHCIICIRHCRC().IIIOIRCOCCHRCHICHIIOHIRIHIOOHR();
                     if (var3 || !HOCRCHOHOICOCOIORIIRRHHOHRHOCR() || var0 > var2.IHRHCHOCCHHICIIOIORIRCIHHHHHIH()) {
                        var2.ROCHRRCORRCOOOOOCOICOCROIIHIHH(Math.max(0, var0));
                     }

                     if (HOCRCHOHOICOCOIORIIRRHHOHRHOCR()) {
                        RORRCRCHIRCHHOOIHCCHRCHORHCICI(var0);
                     }

                     ROIRCHOCCHRHCOIHOHRIICICOOICIR();
                     if (CIRCHHHORHIOOHIIHCCCORHIIOOIIO() != null) {
                        RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                           (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO)null
                        );
                        HCOCRCHORROORHOHHRHOCCOHORHIIR();
                     }

                     com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROCOCHICHORROOHCHOCIIICOHCHIOC()
                        .CHRCCRRRRHRCCIICIHRCCOOIRIICRO("rewind");
                  }
               }
            );
      }
   }

   @CallbackJS("startPlayheadDrag")
   public static void OOIROOIHIOIIHCRRCIIHORCCCCIIII() {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var0.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         CCRHRROIOIIRROHCOOCCCRRIOIHHHO(true);
      }
   }

   @CallbackJS("stopPlayheadDrag")
   public static void CHCCRHRIHRRHCRCIOIORIRCCORCOOC() {
      CCRHRROIOIIRROHCOOCCCRRIOIHHHO(false);
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var0 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
      if (var0 != null) {
         if (OHHIHHHRIOICRHROORORRIOHOOIIRC() >= 0) {
            var0.ROCHRRCORRCOOOOOCOICOCROIIHIHH(OHHIHHHRIOICRHROORORRIOHOOIIRC());
            RORRCRCHIRCHHOOIHCCHRCHORHCICI(-1);
         }

         ROIRCHOCCHRHCOIHOHRIICICOOICIR();
      }
   }

   @CallbackJS("setPreviewMode")
   public static void OOCCRCRCOHIIORCCORCRCIRRROIOOR(Boolean var0) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (!var1.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         ORIRCRCHCROOOORHHIHCOCRCROOIHR().CCRIHCIIOOIOHIRCCHIICCRHIROORC(var0);
         ORIRCRCHCROOOORHHIHCOCRCROOIHR().CCRHOIIHHCCIROCCROHHIIOCOHIRRC().update();
         ROIRCHOCCHRHCOIHOHRIICICOOICIR();
      }
   }

   @CallbackJS("clickPreview")
   public static void RICHIIOOOHORCHORORHIHIRRHCOOIH(int var0) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = ORIRCRCHCROOOORHHIHCOCRCROOIHR();
      if (var1 != null && !var1.OIRIRIIORHRCHRCHROORRROIRROIRI().CHCHOIHOHOCICIHCHRHIOHIRCIIRCO()) {
         if (!var1.OIOOIICIICCCIOCHROHIIRCCORIHOR().OCHHHRHIORHOHRHRICIRHOOHICICRC()) {
            if (!var1.RCHHHIICCRCOROCHCCOICIOIIRIHHO().COCOHIHCICRHOOCHIHCCORHHIRHIOH(var0)) {
               if (!var1.IHHCRHRIORROROHIIIRHOORHHRHOII()
                  && !var1.CCRHOIIHHCCIROCCROHHIIOCOHIRRC().CHORCRORCICOCOOORCIOOICCOOIOHC().isFixedToPlayer()
                  && var1.COHRHOOOCOHRIRHROHHOIOOHHCRHOC()) {
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var2 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
                  if (var2 == null) {
                     return;
                  }

                  if (var1.RICCCROHOIOCHORIRCHIIOORHIRHHR()) {
                     HRCHROOHRIHCRCRHRIIROCIRHOIRHH var3 = var1.HOCCHIRHIIOOOIHIHHICHRIRIHHHRO().HOHHCCRIOOCRIRCIHHCOHOCIICCOOO();
                     var3.OIRICCRROORRCCICIIOIHHRICOHCIR();
                  }

                  IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getGameSettings().bridge$unpressAllKeys();
                  var1.IHHCCRIROCRCRROCCRIHCCHOOOOIRC(true);
                  IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$setInGameFocus(true);
                  ORHIOICIOCRRHOOCOHRORIHICHRCRR var4 = IICCOOCHCHROORHHIIHROHCCRHRCOR.HHICOIRCIIRIRRICOOCROCCOHRCRRI().bridge$getCurrentScreen();
                  if (var4 != null) {
                     var4.bridge$setAllowUserInput(true);
                  }
               }
            }
         }
      }
   }

   @CallbackJS("setZoom")
   public static void ORIOHRCIHRCOOHICCCRIIIHCRHHIHI(float var0) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.ORIOHRCIHRCOOHICCCRIIIHCRHHIHI(
         var0
      );
      HCOCRCHORROORHOHHRHOCCOHORHIIR();
      com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.ROCOCHICHORROOHCHOCIIICOHCHIOC()
         .tick();
   }

   @CallbackJS("setRuleOfThirdsOverlay")
   public static void HRCROCOHHHICRHIHHOOCIIRRRCCIRR(boolean var0) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
      if (var1 != null) {
         var1.HRCROCOHHHICRHIHHOOCIIRRRCCIRR(var0);
         ROIRCHOCCHRHCOIHOHRIICICOOICIR();
      }
   }

   @CallbackJS("setQuartersOverlay")
   public static void RICHHRCCHRIICHROOROCCICOIRRHCR(boolean var0) {
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HIHHOCRHHRORRHHRORRRIIHHORIHOC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1 = HCCRHRRRHHCIIIRORIOHOCHCOCHHIC();
      if (var1 != null) {
         var1.RICHHRCCHRIICHROOROCCICOIRRHCR(var0);
         ROIRCHOCCHRHCOIHOHRIICICOOICIR();
      }
   }

   @CallbackJS("showSettings")
   public static void IIIRHHOCRRRCOHCHCRIHRCOOIRRHCH(boolean var0) {
      CORRRIRCCCCOCHRORIHHOOHORRCRCI = var0;
   }

   @CallbackJS("setInputFocused")
   public static void OCCORIIORHORROHHROHHOORHIHRIOO(boolean var0) {
      CHOCRHHRIHIHHRCICRICHHIRHIHCIC = var0;
   }
}
