package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.client.util.RCOCOHHCOOICCICCRCCORORROHRCCC;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Locale;
import lombok.Generated;
import org.jetbrains.annotations.Nullable;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private final String OICIIHRRCRRHCROCOHCCOOIOHROOOI;
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<?> RCCIOHHOIICHIIHCIOCRRRROOCIRIC;
   @Nullable
   private CRRRICCRROCOHHOHIICIHORCOORRRH IIOIOHCIROICIOICICIOCOCIOICICH;

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<?> var2
   ) {
      this.OICIIHRRCRRHCROCOHCCOOIOHROOOI = var1;
      this.RCCIOHHOIICHIIHCIOCRRRROOCIRIC = var2;
   }

   public static RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      String var0,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<?> var1
   ) {
      return new RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var0, var1);
   }

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CRRRICCRROCOHHOHIICIHORCOORRRH var1) {
      this.IIOIOHCIROICIOICICIOCOCIOICICH = var1;
      return this;
   }

   @Nullable
   public CRRRICCRROCOHHOHIICIHORCOORRRH OICCIHIHRCORIIROHICHOOOCOOIRIR() {
      return this.IIOIOHCIROICIOICICIOCOCIOICICH != null
         ? this.IIOIOHCIROICIOICICIOCOCIOICICH
         : this.RCCIOHHOIICHIIHCIOCRRRROOCIRIC.ROROORRHRIIOOIIIOIOCCORHORRRII();
   }

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OCOHORHCROHICRRIHCIHHRRCIHICRI(String... var1) {
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Arrays.asList(var1));
   }

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Iterable<String> var1) {
      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH((var1x, var2) -> {
         String var3 = var2.CIHCOIIRIOOCOCRHHHHRCCIOHCRCCH().toLowerCase(Locale.ROOT);

         for (String var5 : var1) {
            if (var5.toLowerCase(Locale.ROOT).startsWith(var3)) {
               var2.OHRCIORHOCHOORCRHHOHRRRCCOICCO(var5);
            }
         }
      });
   }

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(Enum<?>[] var1) {
      ArrayList var2 = new ArrayList(var1.length);

      for (Enum var6 : var1) {
         var2.add(var6.name());
      }

      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var2);
   }

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      return this;
   }

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      return this;
   }

   @Override
   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RCOCOHHCOOICCICCRCCORORROHRCCC var1,
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH var2
   ) {
      Object var3 = this.RCCIOHHOIICHIIHCIOCRRRROOCIRIC.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      if (var3 == null) {
         return false;
      }

      var2.CRRRICCRROCOHHOHIICIHORCOORRRH(this.OICIIHRRCRRHCROCOHCCOOIOHROOOI, var3);
      return true;
   }

   @Generated
   public String getName() {
      return this.OICIIHRRCRRHCROCOHCCOOIOHROOOI;
   }

   @Generated
   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<?> CCORCICRCCHHOHICORHIORICHIICRC() {
      return this.RCCIOHHOIICHIIHCIOCRRRROOCIRIC;
   }
}
