package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RORCHCIIICOHIRROOORHOCCCCIOCCI;

import com.google.common.util.concurrent.ThreadFactoryBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IHIRRIIORRHORHRORIHOROIRCORCOO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.OHHRIOHROOIHOROCIRHCHORIHRRRRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.ORHIOICIOCRRHOOCOHRORIHICHRCRR;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.client.util.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;
import lombok.Generated;
import org.jetbrains.annotations.Nullable;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO HCHRRCIOCOOOIHOIHIRHOOOOHCOOOH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.ICHOCHHROIHCROICCIRIHHCHRHROCO(
         "renderRangeLimit"
      )
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(2)
      .OCIROOIHIHRHOCCHIIIROOCRIIOCRR(1, 12)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final IRCRRHRCIRHIHIHROHCRRHIIHHHHCH RICHCORHRIHHIIHHCORHICOCCOIROH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CRRCIHRIHOHORIROHIROORCOCCHOOI("toggleKeybind")
      .OHHRIOHROOIHOROCIRHCHORIHRRRRI(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.KEY_NONE
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RHCIHOOCIRRCRCHCCHOIHRORICCIHR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("fastUpdates")
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI ORORIHICOHHORHRCIHRRHHIRIOOIOR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("culling")
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HROHIIRCCIIIORCCCIHHIRHRRCOIOI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "includeSkyLight"
      )
      .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI CCRORIRHRHCRRORHOCOIOIHCCCIHRC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "hideUnspawnableLight"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI RRHCORROHICCIRIIHCCCOROOIIOHHO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "customLightThreshold"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO CHCORCCHRICRCHHCIRCHIRORHHHCCH = IOHHOIIOCRHCHHCRORICCOHOHROOIH.ICHOCHHROIHCROICCIRIHHCHRHROCO("threshold")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(15)
      .OCIROOIHIHRHOCCHIIIROOCRIIOCRR(0, 15)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   protected final RIROICHCRROROHCCROOCCCCOCHCCRI<IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> RIOORORRHRRHCOOICHHORRRRRRRCOO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         "lightOverlayMode", IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CROSS
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   protected final HICHRCOHCCRHOHCICOOCHOIHCCHIRI OORHRORCRCHRICOIIORIROIHICRIIR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showLightValue"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   protected final IHIRRIIORRHORHRORIHOROIRCORCOO ORRICRRRRORHROIOIRHIRIRRCHORHO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.HOOIORHIHOIHOIIOORHROICRCOHCOH(
         "crossThickness"
      )
      .RROIIRROOOOHIORHRICHOCHIHCRRCH(2.0F)
      .CRHROHHHCIHHCOHCOORCRIHHIICROR(0.5F, 10.0F)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI HHOHICOCOCHOCHROOCCORCCOIRICCR = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "lightOverlayDynamicColor"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI OIOORCRRIOOIHOIIORRHRRRORICIOO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("brightColor")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-16711936)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final OHHRIOHROOIHOROCIRHCHORIHRRRRI HCHOCOHOIHOIHOHHRRRRCRIORHICOC = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("darkColor")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-65536)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   protected final OHHRIOHROOIHOROCIRHCHORIHRRRRI IHRHCHHOIORHRIRCRRRCRCOCIHROOO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHOCHCOCIIICCORORHHOCRIIIHOHHR("textColor")
      .RCIICICHIIRIIRHHROCOOOHRROOIIC(-1)
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   @Nullable
   private CRRRICCRROCOHHOHIICIHORCOORRRH HHHIROHIRIOIRRHCRHHIHRHHRCROOO = null;
   private final AtomicBoolean CCOCROIHRHHRCCCRHHIIICHCORROHC = new AtomicBoolean(false);
   private final AtomicBoolean IOHRIIRHRHRHCIOROHRCCCOCROIIOO = new AtomicBoolean(false);
   private final ExecutorService IRICCCOICHORIOCRHIHCIOHIIHIIRO = Executors.newFixedThreadPool(
      2,
      new ThreadFactoryBuilder()
         .setDaemon(true)
         .setNameFormat("Light Overlay Executor %d")
         .setUncaughtExceptionHandler(
            (var0, var1) -> com.moonsworth.lunar.client.RICRIRRCOHRCOCRRHHCRHRROOIOHHR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               var1, "Uncaught error on thread %s!", var0.getName()
            )
         )
         .build()
   );
   private volatile boolean needsUpdate = true;
   private long lastUpdate = -1L;
   private boolean CICOIHOIROIROIIHRCCORRIROIOORO = true;
   private long HRCCCOHOICIOCCORCRCRIIHOIRRRHH;
   private int HCIOICIORROCCIOOHIICHIHCRICOOR;

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH() {
      super(false);
      this.handle(CORCOCICIRIOHROHROIIOOHICCHCRR.class, this::RCIRROCCCIIHCIHCCRHHCCHOHHHCHH);
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, this::ORCOOCHRICHOIHHIHIOHCHCRIOHRCR);
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class,
         this::OIIHIRRIOORORHHROOCHIHHCCHIRHO
      );
      this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class,
         this::ORHROHHHCRRIHIIHOHHORCCCRRIHHC
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class,
         this::RRCRRCORICCHOHHIRCHIROOHIIOHCO
      );
      this.RICHCORHRIHHIIHHCORHICOCCOIROH.OOCCRCRCOHIIORCCORCRCIRRROIOOR(() -> {
         this.CICOIHOIROIROIIHRCCORRIROIOORO = !this.CICOIHOIROIROIIHRCCORRIROIOORO;
         IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HHCCIRORCRCHOIOHRRIRRRIORRCRRR().HRIIIOIIRHOHORIRICIOIORRIRCHHO();
      });
   }

   public static boolean COHORICRRRRRHRROCRHCOOIHOOIRHR() {
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.ICORCRCHRIICOHOOIHHIHOIHIIRCOR().HHCCIRORCRCHOIOHRRIRRRIORRCRRR().RRCCCHCRHCIOCIOIOHOROCORIIIICR().isEnabled();
   }

   @Override
   public String getId() {
      return "LIGHT_OVERLAY";
   }

   @Override
   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ORIRHOHRHHROCHHRRIOOCRIHRIIIOC() {
      return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CIICCCRRHHCHRRHRIRCHOICCHROHCR()
         .RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HCRCRIHOIHICCCCCOOROIHIIRIHCHI
         )
         .RRCRRCORICCHOHHIRCHIROOHIIOHCO(this);
   }

   @Override
   public void COIHORRCHRRCHOCIRHHRRIOIHRIHCC(boolean var1) {
      if (this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO != null) {
         this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO = null;
         System.gc();
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var2 = this.mc
         .bridge$getLevelRenderer();
      if (var2 != null) {
         var2.bridge$reloadChunks();
      }
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.GENERAL,
         var1x -> {
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(
               this.RICHCORHRIHHIIHHCORHICOCCOIROH,
               IOHHOIIOCRHCHHCRORICCOHOHROOIH.ICORROIIHHHRIICIOORIRIOHHIHOCI("")
                  .OHRRHHOCROROCCIRROIHOCCHCIHCIR(
                     () -> this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(this.CICOIHOIROIROIIHRCCORRIROIOORO ? "stateEnabled" : "stateDisabled")
                  )
            );
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(
               this.HCHRRCIOCOOOIHOIHIRHOOOOHCOOOH,
               this.RHCIHOOCIRRCRCHCCHOIHRORICCIHR,
               this.ORORIHICOHHORHRCIHRRHHIRIOOIOR,
               this.HROHIIRCCIIIORCCCIHHIRHRRCOIOI
            );
            var1x.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
               this.CCRORIRHRHCRRORHOCOIOIHCCCIHRC,
               var1xx -> var1xx.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
                  this.RRHCORROHICCIRIIHCCCOROOIIOHHO, var1xxx -> var1xxx.CRRRICCRROCOHHOHIICIHORCOORRRH(this.CHCORCCHRICRCHHCIRCHIRORHHHCCH)
               )
            );
         }
      );
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RENDER,
         var1x -> {
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.RIOORORRHRRHCOOICHHORRRRRRRCOO, this.OORHRORCRCHRICOIIORIROIHICRIIR);
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.ORRICRRRRORHROIOIRHIRIRRCHORHO)
               .IIHRRHORCRCROCHHOHORCHCROCIHRO(
                  () -> this.RIOORORRHRRHCOOICHHORRRRRRRCOO.get() != IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CROSS
               );
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.IHRHCHHOIORHRIRCRRRCRCOCIHROOO)
               .IIHRRHORCRCROCHHOHORCHCROCIHRO(
                  () -> !this.OORHRORCRCHRICOIIORIROIHICRIIR.get()
                     || this.RIOORORRHRRHCOOICHHORRRRRRRCOO.get() == IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.NONE
               );
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.OIOORCRRIOOIHOIIORRHRRRORICIOO, this.HCHOCOHOIHOIHOHHRRRRCRIORHICOC, this.HHOHICOCOCHOCHROOCCORCCOIRICCR);
         }
      );
   }

   @Override
   public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(JsonObject var1) {
      super.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
      var1.addProperty("enabledToggle", this.CICOIHOIROIROIIHRCCORRIROIOORO);
   }

   @Override
   public void load(JsonObject var1) {
      super.load(var1);
      JsonElement var2 = var1.get("enabledToggle");
      if (var2 != null && var2.isJsonPrimitive()) {
         this.CICOIHOIROIROIIHRCCORRIROIOORO = var2.getAsBoolean();
      }
   }

   @Override
   protected boolean HIOOOIRCCROCRIRCROOHRCCOOIOIOH(String var1) {
      return "enabledToggle".equals(var1);
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(CORCOCICIRIOHROHROIIOOHICCHCRR var1) {
      this.HRCCCOHOICIOCCORCRCRIIHOIRRRHH = Math.abs(var1.getWorldTime());
   }

   private void ORCOOCHRICHOIHHIHIOHCHCRIOHRCR() {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = this.mc
         .bridge$getPlayer();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var2 = this.mc
         .bridge$getWorld();
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var3 = this.mc
         .bridge$getLevelRenderer();
      if (var1 != null && var2 != null && var3 != null) {
         if (this.CICOIHOIROIROIIHRCCORRIROIOORO) {
            if (this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO == null) {
               this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO = new CRRRICCRROCOHHOHIICIHORCOORRRH();
            }

            if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION > 35 && this.mc.bridge$getIntegratedServer() != null) {
               this.HRCCCOHOICIOCCORCRCRIIHOIRRRHH = var2.bridge$getDayTimeline();
            }

            if (!this.HROHIIRCCIIIORCCCIHHIRHRRCOIOI.get()) {
               this.HCIOICIORROCCIOOHIICHIHCRICOOR = -1;
            } else {
               this.HCIOICIORROCCIOOHIICHIHCRICOOR = var1.bridge$getDimension() == 0
                  ? var2.bridge$calculateSkylightSubtract(this.HRCCCOHOICIOCCORCRCRIIHOIRRRHH)
                  : 0;
            }

            if ((this.RHCIHOOCIRRCRCHCCHOIHRORICCIHR.get() || this.lastUpdate == -1L || System.currentTimeMillis() - this.lastUpdate >= 500L)
               && this.needsUpdate
               && this.CCOCROIHRHHRCCCRHHIIICHCORROHC.compareAndSet(false, true)) {
               this.needsUpdate = false;
               CRRRICCRROCOHHOHIICIHORCOORRRH var4 = this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO;
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var5 = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CICOOHICHIROHIRCRRIOIIRRIHCCHC()
                  .orElse(null);
               if (var5 != null) {
                  var4.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO(var5.bridge$getRenderChunks());
               } else {
                  var4.IIHRHCCOOHOOOOCHRRCOROOIOHCOOO(var3.bridge$getRenderChunks());
               }

               this.IRICCCOICHORIOCRHIHCIOHIIHIIRO.execute(() -> {
                  try {
                     var4.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this, var2);
                  } finally {
                     this.CCOCROIHRHHRCCCRHHIIICHCORROHC.set(false);
                  }
               });
               this.lastUpdate = System.currentTimeMillis();
            }

            if ((this.RHCIHOOCIRRCRCHCCHOIHRORICCIHR.get() || IOIICIRIICICIIOORHCIIIIRRIHRHI.ROCHOOHIHIHCIRHCICIOHHCIOHHHRH % 2 == 0)
               && this.IOHRIIRHRHRHCIOROHRCCCOCROIIOO.compareAndSet(false, true)) {
               int var14 = var1.bridge$getBlockX();
               int var15 = var1.bridge$getBlockY();
               int var6 = var1.bridge$getBlockZ();
               boolean var7 = this.CCRORIRHRHCRRORHOCOIOIHCCCIHRC.get();
               boolean var8 = this.RRHCORROHICCIRIIHCCCOROOIIOHHO.get();
               int var9 = this.CHCORCCHRICRCHHCIRCHIRORHHHCCH.get();
               int var10 = this.HCHRRCIOCOOOIHOIHIRHOOOOHCOOOH.get();
               int var11 = this.HCIOICIORROCCIOOHIICHIHCRICOOR;
               boolean var12 = this.ORORIHICOHHORHRCIHRRHHIRIOOIOR.get();
               CRRRICCRROCOHHOHIICIHORCOORRRH var13 = this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO;
               this.IRICCCOICHORIOCRHIHCIOHIIHIIRO.execute(() -> {
                  try {
                     var13.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var14, var15, var6, var2, var12 ? var3::bridge$isBlockVisible : null, var7, var8, var9, var10, var11);
                  } finally {
                     this.IOHRIIRHRHRHCIOROHRCCCOCROIIOO.set(false);
                  }
               });
            }
         }
      } else {
         if (this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO != null) {
            this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO = null;
            System.gc();
         }

         this.needsUpdate = true;
      }
   }

   private void OIIHIRRIOORORHHROOCHIHHCCHIRHO() {
      this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO = null;
      this.needsUpdate = true;
   }

   private void ORHROHHHCRRIHIIHOHHORCCCRRIHHC() {
      if (this.CCOCROIHRHHRCCCRHHIIICHCORROHC.get()) {
         this.needsUpdate = true;
      }
   }

   private void RRCRRCORICCHOHHIRCHIROOHIIOHCO(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2 = this.mc
         .bridge$getEntityRenderDispatcher();
      if (var2 != null && this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO != null && this.CICOIHOIROIROIIHRCCORRIROIOORO) {
         this.HHHIROHIRIOIRRHCRHHIHRHHRCROOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1.HHIIOHOORHHCCHRHHRCIORCROORCOI(), var2, this);
      }
   }

   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var3 = this.mc
         .bridge$getWorld();
      return var3 != null && this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2) ? var3.bridge$canMonstersSpawn(var1) : false;
   }

   public boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var1,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var2,
      Object var3
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO var4 = this.mc
         .bridge$getWorld();
      return var4 != null && this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2) ? var4.bridge$canMonstersSpawn(var1, var3) : false;
   }

   private boolean IRCIIHHICIHRCOCRROCOICRIHHCCHH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = this.mc
         .bridge$getPlayer();
      if (var2 == null) {
         return false;
      }

      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = var1.bridge$getBlock();
      return !var3.bridge$isSpawner() && !var3.bridge$isGlass();
   }

   protected int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(byte var1, byte var2, int var3, float var4) {
      return !this.HHOHICOCOCHOCHROOCCORCCOIRICCR.get()
         ? (RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2, var3) ? this.HCHOCOHOIHOIHOHHRRRRCRIORHICOC : this.OIOORCRRIOOIHOIIORRHRRRORICIOO)
            .CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(var4)
         : OCOHORHCROHICRRIHCIHHRRCIHICRI.CRRRICCRROCOHHOHIICIHORCOORRRH(
            this.HCHOCOHOIHOIHOHHRRRRCRIORHICOC.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(var4),
            this.OIOORCRRIOOIHOIIORRHRRRORICIOO.CRHRHRIOIHRCHRIORHRRCHHIHCOCCC(var4),
            IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2, var3) / 15.0F
         );
   }

   protected static boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(byte var0, byte var1, int var2) {
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION < 10
         ? IRCIIHHICIHRCOCRROCOICRIHHCCHH(var0, var1, var2) <= 7
         : var0 == 0 && RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2) <= 7;
   }

   protected static int IRCIIHHICIHRCOCRROCOICRIHHCCHH(byte var0, byte var1, int var2) {
      return Math.max(var0, RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var2));
   }

   protected static int RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(byte var0, int var1) {
      return var1 == -1 ? 0 : var0 - var1;
   }

   @Generated
   public void OIICIRRCOOCIHRHOIOIOOROCRHCHIC(boolean var1) {
      this.needsUpdate = var1;
   }

   @Generated
   public int OROCHRROHRHIRRRCIOCICCIROCORHC() {
      return this.HCIOICIORROCCIOOHIICHIHCRICOOR;
   }

   protected enum RCIRROCCCIIHCIHCCRHHCCHOHHHCHH implements ORHIOICIOCRRHOOCOHRORIHICHRCRR {
      OVERLAY("overlay"),
      CROSS("cross"),
      NONE("none");

      private final String id;

      @Override
      public String id() {
         return this.id;
      }

      @Override
      public String toString() {
         return this.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI(this.id);
      }

      @Generated
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(String var3) {
         this.id = var3;
      }
   }
}
