package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;

@com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 1)
public abstract class HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   protected final IRCIIHHICIHRCOCRROCOICRIHHCCHH IHOOIORIHHOOCIHHOIIOOHOIRIORIO;

   public HHCCIRHCCCIIRHCROHIORHIRHHIORH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO = var1;
   }

   protected CRRRICCRROCOHHOHIICIHORCOORRRH OHRHHRCRORICRHRCHROHRROCRIIHRR() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.OHRHHRCRORICRHRCHROHRROCRIIHRR();
   }

   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HOIIIICHRHCOHICRROHRCHIIRHIHRI() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HOIIIICHRHCOHICRROHRCHIIRHIHRI();
   }

   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH HIIRHRRHIIOCIOCROCHCOIHCCCRIHO() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HIIRHRRHIIOCIOCROCHCOIHCCCRIHO();
   }

   protected OOROOCCIRCCRHOIOIORIHCHHOOCCOR IRHRCIRRRIRHRIRRRRRCIICRHRHIRR() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IRHRCIRRRIRHRIRRRRRCIICRHRHIRR();
   }

   protected RIOOCHICIHRHOHCCCCCHOCCCOHCRHI RRHHRHRIRIHRHRICRCOOIHRROOCCRC() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.RCOCIHIIHHOCHORCCHRHIRIROHHRRC();
   }

   protected RRCRRCORICCHOHHIRCHIROOHIIOHCO CRRIHIHCIRHCOOORROHIRCRHCOIHHI() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.CRRIHIHCIRHCOOORROHIRCRHCOIHHI();
   }

   protected HRCHROOHRIHCRCRHRIIROCIRHOIRHH HOCRCHHCRHOOCICRRHICCICHRCORHC() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.HOCRCHHCRHOOCICRRHICCICHRCORHC();
   }

   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH OOOHOOOIROICRCHHRIRHHOICCIIOOR() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.OOOHOOOIROICRCHHRIRHHOICCIIOOR();
   }

   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH OIOHHCCIICROHROCHCCOIIICCRCRHC() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.OIOHHCCIICROHROCHCCOIIICCRCRHC();
   }

   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH COOHCRIHOOCRROOIHHHIOIRHHHIRIC() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.COOHCRIHOOCRROOIHHHIOIRHHHIRIC();
   }

   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH COICICOCCHCIHRCORCIHHIIHCHOIIH() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.COICICOCCHCIHRCORCIHHIIHCHOIIH();
   }

   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CROHOOHHCCHOORCOIIRROIHCCCIICO() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.CROHOOHHCCHOORCOIIRROIHCCCIICO();
   }

   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CCOHHHCRRROOOHHORICOCRRHCCRORR() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.CCOHHHCRRROOOHHORICOCRRHCCRORR();
   }

   protected RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OIHRHOCIIIROHCRCCOOOCOOOOOHIHR() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.OIHRHOCIIIROHCRCCOOOCOOOOOHIHR();
   }

   protected String IIHCCIRHCCICIRHICOCHCCRIHIIOHC() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IIHCCIRHCCICIRHICOCHCCRIHIIOHC();
   }

   protected com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH getTheme() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.getTheme();
   }

   protected com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH IHCCRHOROROOHRCRRIOHCRIORRIRHI() {
      return this.IHOOIORIHHOOCIHHOIIOOHOIRIORIO.IHCCRHOROROOHRCRRIOHCRIORRIRHI();
   }

   public void start() {
   }

   public void end() {
   }
}
