package com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.OCOHORHCROHICRRIHCIHHRRCIHICRI;

public interface HHCCIRHCCCIIRHCROHIORHIRHHIORH {
   boolean RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1);

   String IRCIIHHICIHRCOCRROCOICRIHHCCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1);

   void IHIRRIIORRHORHRORIHOROIRCORCOO(boolean var1);

   int HHCCIRHCCCIIRHCROHIORHIRHHIORH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1);

   default boolean CCIHIROCOROHOHCHIOCOCRHCCIORCC(String var1) {
      if (!var1.startsWith("KEY_")) {
         var1 = "KEY_" + var1;
      }

      return this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH.valueOf(var1));
   }

   default IRCIIHHICIHRCOCRROCOICRIHHCCHH HROHCRIOCIHCORHOHIOCIHOHHCIIRH(String var1) {
      if (!var1.startsWith("KEY_")) {
         var1 = "KEY_" + var1;
      }

      return IRCIIHHICIHRCOCRROCOICRIHHCCHH.valueOf(var1);
   }
}
