package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.lunarclient.dfu.serialization.Codec;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CIOHHCORHRCCRICCCORIHCRHCCCRRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IRRCCOICORICIHCHRHIHIHROIRHOCR;
import com.moonsworth.lunar.client.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH
   extends IRRCCOICORICIHCHRHIHIHROIRHOCR<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.CRRRICCRROCOHHOHIICIHORCOORRRH IRIRCICRRHOCIIOIHRCICOROIHCCCH;
   private final boolean ROHOHIRHRCOOIROCRCHHRHRIIRCHCR;

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.CRRRICCRROCOHHOHIICIHORCOORRRH var1,
      String var2,
      boolean var3
   ) {
      super(
         var2,
         Codec.stringResolver(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH::apiName,
            var1x -> var1.IICCCOCIIOROCRIIOICHIROORRCIHR
               .getTierProvider()
               .ROICOCHCIHIRICHOOCHHCRHCHOORIR(var1x)
               .orElse(
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCCCOOCIRIIOOIROHCCCCHICICHHOR
               )
         ),
         var3
            ? com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCCCOOCIRIIOOIROHCCCCHICICHHOR
            : var1.IICCCOCIIOROCRIIOICHIROORRCIHR
               .getTierProvider()
               .OCRIOCRIHRIRCCOHOOOHOCHHHOORRR()
               .stream()
               .findFirst()
               .orElse(
                  com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCCCOOCIRIIOOIROHCCCCHICICHHOR
               ),
         Collections.emptyList(),
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH::niceName
      );
      this.IRIRCICRRHOCIIOIHRCICOROIHCCCH = var1;
      this.ROHOHIRHRCOOIROCRCHHRHRIIRCHCR = var3;
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1,
      boolean var2
   ) {
      super.CRRRICCRROCOHHOHIICIHORCOORRRH(var1, var2);

      for (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.HHCCIRHCCCIIRHCROHIORHIRHHIORH var4 : com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.VALUES) {
         var4.getTierProvider().IIOROOHCCHOIOHCOCIOHIHIIRRHIIR();
      }

      this.IRIRCICRRHOCIIOIHRCICOROIHCCCH.clearCaches();
   }

   @Override
   public void IOHOOIOHCHICOCHIICHCICCOHRCIII(
      List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> var1
   ) {
      super.IOHOOIOHCHICOCHIICHCICCOHRCIII(this.IHORRHOROHHHIORCCHRCRIRRHHCCCO(var1));
      this.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(this.RHHCHROCOCHCRRRIIOOIHCIRRIROOI());
      if (this.IRIRCICRRHOCIIOIHRCICOROIHCCCH.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IIRHHICCCOCCRRCOCOCCCOIROOIOOR)
         == CIOHHCORHRCCRICCCORIHCRHCCCRRR.COMPLETE) {
         RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIHOOOHRRCROHRICOOOOOIHIOOIRHI();
      }
   }

   @Override
   public List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> RCRIOCCCOOIRICRHHCCIRCIOHRRRIO() {
      return this.IHORRHOROHHHIORCCHRCRIRRHHCCCO(
         this.IRIRCICRRHOCIIOIHRCICOROIHCCCH.IICCCOCIIOROCRIIOICHIROORRCIHR.getTierProvider().OCRIOCRIHRIRCCOHOOOHOCHHHOORRR()
      );
   }

   public com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH RHHCHROCOCHCRRRIIOOIHCIRRIROOI() {
      if (this.ROHOHIRHRCOOIROCRCHHRHRIIRCHCR) {
         return com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCCCOOCIRIIOOIROHCCCCHICICHHOR;
      }

      List var1 = this.RCRIOCCCOOIRICRHHCCIRCIOHRRRIO();
      return var1.isEmpty()
         ? com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCCCOOCIRIIOOIROHCCCCHICICHHOR
         : (com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH)var1.get(
            0
         );
   }

   private List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> IHORRHOROHHHIORCCHRCRIRRHHCCCO(
      List<com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH> var1
   ) {
      if (!this.ROHOHIRHRCOOIROCRCHHRHRIIRCHCR) {
         return var1;
      }

      ArrayList var2 = new ArrayList(var1.size() + 1);
      var2.add(
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HOHCCHOIOHOHHOROHOIIHOOHORRHRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CCCCOOCIRIIOOIROHCCCCHICICHHOR
      );
      var2.addAll(var1);
      return var2;
   }
}
