package com.moonsworth.lunar.client.IRRCCOICORICIHCHRHIHIHROIRHOCR;

public interface RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   void OIHCOHRCICCCRHRCROOCIOIRRHHHIH(Runnable var1);

   void ROOCOCCCIRHHHIRIOIHHHHRHIICHHR(Runnable var1);
}
