package com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR;

import lombok.Generated;

public abstract class OOROOCCIRCCRHOIOIORIHCHHOOCCOR extends com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH {
   private final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH RROHIIOHIICRRHOICHIIHCRRCHRRHC;

   @Generated
   public OOROOCCIRCCRHOIOIORIHCHHOOCCOR(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
   ) {
      this.RROHIIOHIICRRHOICHIIHCRRCHRRHC = var1;
   }

   @Generated
   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH IRIICICHHHCHCIOCCRRORHHHRRHHOH() {
      return this.RROHIIOHIICRRHOICHIIHCRRCHRRHC;
   }

   public static class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends OOROOCCIRCCRHOIOIORIHCHHOOCCOR {
      public IRCIIHHICIHRCOCRROCOICRIHHCCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
      ) {
         super(var1);
      }
   }

   public static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends OOROOCCIRCCRHOIOIORIHCHHOOCCOR {
      public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RCIROOOOICRHCCRRCIORHHIRCOIIIC.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1
      ) {
         super(var1);
      }
   }
}
