package com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import lombok.Generated;

public class IIHRRHORCRCROCHHOHORCHCROCIHRO extends com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH {
   private final com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR RHCRCCCIHCIHHRICIIIHORROOCOOHR;
   private float yaw;

   @Generated
   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR RRIIHHICRHRIIICCIOHCROIIIRIROR() {
      return this.RHCRCCCIHCIHHRICIIIHORROOCOOHR;
   }

   @Generated
   public float getYaw() {
      return this.yaw;
   }

   @Generated
   public IIHRRHORCRCROCHHOHORCHCROCIHRO(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CORCOCICIRIOHROHROIIOOHICCHCRR var1, float var2
   ) {
      this.RHCRCCCIHCIHHRICIIIHORROOCOOHR = var1;
      this.yaw = var2;
   }
}
