package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOCCRCRCOHIIORCCORCRCIRRROIOOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH;

import com.google.gson.JsonObject;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RHOCHHIRRCHHHOHOIRROIROHHHIHIO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import org.jetbrains.annotations.Nullable;

class CRRRICCRROCOHHOHIICIHORCOORRRH implements RHOCHHIRRCHHHOHOIRROIROHHHIHIO {
   private final RCIRROCCCIIHCIHCCRHHCCHOHHHCHH OHOIIOHIRIIRRCRCORHROCIHRHICRO;
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI CCHICRCOHHHRRCCRCORHRIIOICCHCI;
   @com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 5)
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI OHIRRRROOICOOOIRRROOICOHIRRIOO = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("splitHands")
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private final boolean IOCRRIICOICORICHHCIICOOOORIHHC;
   private final HHCCIRHCCCIIRHCROHIORHIRHHIORH RCCHRHCRIHORHIRIHRRCHRHCCIHCCI = new HHCCIRHCCCIIRHCROHIORHIRHHIORH(this, IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIGHT);
   @com.moonsworth.lunar.ichor.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(min = 5)
   private final HHCCIRHCCCIIRHCROHIORHIRHHIORH HRRHOICHHIRRRHOHRRIOICIIHIHIIH = new HHCCIRHCCCIIRHCROHIORHIRHHIORH(this, IRCIIHHICIHRCOCRROCOICRIHHCCHH.LEFT);

   CRRRICCRROCOHHOHIICIHORCOORRRH(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1, String var2, boolean var3) {
      this.OHOIIOHIRIIRRCRCORHROCIHRHICRO = var1;
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 5) {
         this.OHIRRRROOICOOOIRRROOICOHIRRIOO
            .OHIIIOHIRIRCCRRIOIICCHHIORRHOH(
               () -> com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOCCRCRCOHIIORCCORCRCIRRROIOOR.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRRRICCRROCOHHOHIICIHORCOORRRH(
                  this.OHOIIOHIRIIRRCRCORHROCIHRHICRO, true
               )
            );
      }

      this.CCHICRCOHHHRRCCRCORHRIIOICCHCI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC("enabled")
         .RICIORHICRROHOCHRRCRIHCROOCIIC(true)
         .HICOHCCCIROCOIHCORCHOCROCIIOCI(var2)
         .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
      this.IOCRRIICOICORICHHCIICOOOORIHHC = var3;
   }

   @Override
   public void load(JsonObject var1) {
      this.CCHICRCOHHHRRCCRCORHRIIOICCHCI.load(var1);
      this.RCCHRHCRIHORHIRIHRRCHRHCCIHCCI.load(var1);
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 5) {
         this.OHIRRRROOICOOOIRRROOICOHIRRIOO.load(var1);
         this.HRRHOICHHIRRRHOHRRIOICIIHIHIIH.load(var1);
      }
   }

   @Override
   public void HHCCIRHCCCIIRHCROHIORHIRHHIORH(JsonObject var1) {
      this.CCHICRCOHHHRRCCRCORHRIIOICCHCI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
      this.RCCHRHCRIHORHIRIHRRCHRHCCIHCCI.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 5) {
         this.OHIRRRROOICOOOIRRROOICOHIRRIOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
         this.HRRHOICHHIRRRHOHRRIOICIIHIHIIH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(var1);
      }
   }

   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      var1.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this.CCHICRCOHHHRRCCRCORHRIIOICCHCI, var1x -> {
         this.RCCHRHCRIHORHIRIHRRCHRHCCIHCCI.CCIHHRIOOOOCOHRCIHOHROOICIORCC(var1x);
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 5) {
            this.HRRHOICHHIRRRHOHRRIOICIIHIHIIH.CCIHHRIOOOOCOHRCIHOHROOICIORCC(var1x);
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(this.OHIRRRROOICOOOIRRROOICOHIRRIOO);
         }

         if (this.IOCRRIICOICORICHHCIICOOOORIHHC) {
            var1x.CRRRICCRROCOHHOHIICIHORCOORRRH(IOHHOIIOCRHCHHCRORICCOHOHROOIH.OHCIIRROIRICICHOIORRIIHICCCRCH("remove").RCIROOOOICRHCCRRCIORHHIRCOIIIC(() -> {
               this.OHOIIOHIRIIRRCRCORHROCIHRHICRO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(this);
               this.CCHICRCOHHHRRCCRCORHRIIOICCHCI.IOOORHIIOIRRCRIHHCHIRCCHCRRCCR(true);
            }));
         }
      });
      var1.IIRHHCRORIOCIHIOIHIRHOHCIRIOHI().CIOHHCORHRCCRICCCORIHCRHCCCRRR(this.CCHICRCOHHHRRCCRCORHRIIOICCHCI::IHICHICHCHCRROIRCROHOHHHIIIHIH);
   }

   @Nullable
   public HHCCIRHCCCIIRHCROHIORHIRHHIORH RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 5
         && !this.OHIRRRROOICOOOIRRROOICOHIRRIOO.get()
         && IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH() != null
         && IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH().bridge$isMainHandSwapped()) {
         var1 = var1.opposite();
      }

      HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = this.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1);
      return var2 != null && var2.isEnabled() ? var2 : null;
   }

   @Nullable
   public HHCCIRHCCCIIRHCROHIORHIRHHIORH IRCIIHHICIHRCOCRROCOICRIHHCCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      if (var1 == IRCIIHHICIHRCOCRROCOICRIHHCCHH.LEFT && IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 5) {
         return this.HRRHOICHHIRRRHOHRRIOICIIHIHIIH;
      } else {
         return var1 == IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIGHT ? this.RCCHRHCRIHORHIRIHRRCHRHCCIHCCI : null;
      }
   }

   public boolean isEnabled() {
      return this.CCHICRCOHHHRRCCRCORHRIIOICCHCI.get();
   }

   public boolean RHRRCCCOIHIRCOCOOOCIRCROIRCHIO() {
      return IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 5 && this.OHIRRRROOICOOOIRRROOICOHIRRIOO.get();
   }
}
