package com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IIHRRHORCRCROCHHOHORCHCROCIHRO;

@com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH
public final class OOROOCCIRCCRHOIOIORIHCHHOOCCOR {
   static final String CICRHRROCRRCIIICOHHICHICRCHHHR = "-_.*";
   static final String HIRCCCICIOHOICIORRHOOCHHROIRIR = "-._~!$'()*,;&=@:";
   private static final com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI CIRHCIRRCIRIHOHOIIRCIHHOCHCOHC = new HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      "-_.*", true
   );
   private static final com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI OICCOHOOHOHIIIHICHCICCOHIHCOIR = new HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      "-._~!$'()*,;&=@:+", false
   );
   private static final com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI ICCHORORCOHCCRRHRRRRRHHIOOHOCC = new HRCHROOHRIHCRCRHRIIROCIRHOIRHH(
      "-._~!$'()*,;&=@:+/?", false
   );

   private OOROOCCIRCCRHOIOIORIHCHHOOCCOR() {
   }

   public static com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI CCHOHICCRIIROHRHCIHHCRCCCIIHRI() {
      return CIRHCIRRCIRIHOHOIIRCIHHOCHCOHC;
   }

   public static com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI CIOOOICHOHOICHCRIIIOIHRCIOHOHR() {
      return OICCOHOOHOHIIIHICHCICCOHIHCOIR;
   }

   public static com.moonsworth.lunar.genesis.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI CRRIROIOIIHIIORRIIRIIOHOICOOII() {
      return ICCHORORCOHCCRRHRRRRRHHIOOHOCC;
   }
}
