package com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI;

import com.lunarclient.dfu.serialization.Codec;
import com.moonsworth.lunar.client.util.HIHCCHCCOCOHRICOICHRCOIHIIRIHO;
import java.util.Set;
import org.jspecify.annotations.Nullable;

public class RHCHRCOCCOIIIHCHRHIRCORHRHRICR<V, S extends Set<V>> extends HRCHROOHRIHCRCRHRIIROCIRHOIRHH<S> {
   public RHCHRCOCCOIIIHCHRHIRCORHRHRICR(
      @HIHCCHCCOCOHRICOICHRCOIHIIRIHO(CHHOHHOIRCCRRCRIHCCOHHRCIHRHII = HIHCCHCCOCOHRICOICHRCOIHIIRIHO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SETTING) String var1,
      @Nullable Codec<S> var2,
      S var3
   ) {
      super(var1, var2, (S)var3);
   }

   public void RRRHHIRORHCHHCOOCIHOICORHHCHHO(V var1) {
      if (this.HRHHHHIICCCIROOOHIIIHIHIHHHOHC().add((V)var1)) {
         this.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(this.HRHHHHIICCCIROOOHIIIHIHIHHHOHC());
      }
   }

   public void HRCOCHHHCCIORCORCHIOOOCCCCHICH(V var1) {
      if (this.HRHHHHIICCCIROOOHIIIHIHIHHHOHC().remove(var1)) {
         this.RHRIIOOOCRHIIOORCOCRCHRCCRRCIH(this.HRHHHHIICCCIROOOHIIIHIHIHHHOHC());
      }
   }

   public static class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<V, S extends Set<V>>
      extends com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH<RHCHRCOCCOIIIHCHRHIRCORHRHRICR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH<V, S>, RHCHRCOCCOIIIHCHRHIRCORHRHRICR<V, S>, S> {
      protected RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         @HIHCCHCCOCOHRICOICHRCOIHIIRIHO(CHHOHHOIRCCRRCRIHCCOHHRCIHRHII = HIHCCHCCOCOHRICOICHRCOIHIIRIHO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.SETTING) String var1
      ) {
         super(var1);
      }

      @Override
      protected com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH ORCHRRHCCOIHHRROOHROROROOHOHIO() {
         return com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.CRRRICCRROCOHHOHIICIHORCOORRRH.UNKNOWN;
      }

      @Override
      protected @Nullable Codec<S> CIHHRHHHCCHCCCCCIRRORHICROCHHR() {
         return null;
      }

      protected RHCHRCOCCOIIIHCHRHIRCORHRHRICR<V, S> IOOOIOCRRRIOHIHRROIIIHOCRHRIOR() {
         if (this.defaultValue == null) {
            throw new com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH(
               this, "Value must be set!"
            );
         } else {
            return new RHCHRCOCCOIIIHCHRHIRCORHRHRICR<>(this.RROHIIOCCIOHRHHIIRIOIRHHIOCRRO, this.codec, this.defaultValue);
         }
      }
   }
}
