package com.moonsworth.lunar.client.util.IIHRRHORCRCROCHHOHORCHCROCIHRO;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.RCIROOOOICRHCCRRCIORHHIRCOIIIC;
import java.util.function.BiConsumer;
import lombok.Generated;

public class OCOHORHCROHICRRIHCIHHRRCIHICRI {
   private final RCIROOOOICRHCCRRCIORHHIRCOIIIC HIRIIOOORCORHICCRRROHOIOIIHROR;
   private final BiConsumer<Boolean, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI> IOOIHORCHOICOCRHIRHCIICHCROOOR;
   private com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH renderType = com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.CCIHIRRIHCOICHHHIHCHHHHCHRIICR;
   private boolean HCCCRRCRHOOOHRHCOIOCRCIRCOHORR = true;

   @Generated
   public OCOHORHCROHICRRIHCIHHRRCIHICRI(
      RCIROOOOICRHCCRRCIORHHIRCOIIIC var1,
      BiConsumer<Boolean, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI> var2,
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var3,
      boolean var4
   ) {
      this.HIRIIOOORCORHICCRRROHOIOIIHROR = var1;
      this.IOOIHORCHOICOCRHIRHCIICHCROOOR = var2;
      this.renderType = var3;
      this.HCCCRRCRHOOOHRHCOIOCRCIRCOHORR = var4;
   }

   @Generated
   public RCIROOOOICRHCCRRCIORHHIRCOIIIC IIHHORHOROOCIHHCORRRCIRHOIICCH() {
      return this.HIRIIOOORCORHICCRRROHOIOIIHROR;
   }

   @Generated
   public BiConsumer<Boolean, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI> RRCHIHHHRICCRHRRHOHRROICHOORHH() {
      return this.IOOIHORCHOICOCRHIRHCIICHCROOOR;
   }

   @Generated
   public com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH HOOOCIOCIHHRORIOHIOHCIHCOCCIIR() {
      return this.renderType;
   }

   @Generated
   public boolean HCCOCOICIROCRIIHOIOHOHHRHOHCRO() {
      return this.HCCCRRCRHOOOHRHCOIOCRCIRCOHORR;
   }

   @Generated
   public void CRRRICCRROCOHHOHIICIHORCOORRRH(
      com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var1
   ) {
      this.renderType = var1;
   }

   @Generated
   public void IOHHHRIOHHOIHORHRHIHRIHCICIIHR(boolean var1) {
      this.HCCCRRCRHOOOHRHCOIOCRCIRCOHORR = var1;
   }

   @Generated
   public OCOHORHCROHICRRIHCIHHRRCIHICRI(
      RCIROOOOICRHCCRRCIORHHIRCOIIIC var1,
      BiConsumer<Boolean, com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI> var2
   ) {
      this.HIRIIOOORCORHICCRRROHOIOIIHROR = var1;
      this.IOOIHORCHOICOCRHIRHCIICHCROOOR = var2;
   }
}
