package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HICHRCOHCCRHOHCICOOCHOIHCCHIRI.IRCIIHHICIHRCOCRROCOICRIHHCCHH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.CRRRICCRROCOHHOHIICIHORCOORRRH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CORCOCICIRIOHROHROIIOOHICCHCRR;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.CORCOCICIRIOHROHROIIOOHICCHCRR.IIHRRHORCRCROCHHOHORCHCROCIHRO.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RIROICHCRROROHCCROOCCCCOCHCCRI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.IOIICIRIICICIIOORHCIIIIRRIHRHI;
import com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import com.moonsworth.lunar.lib.adventure.text.Component;

public class IRCIIHHICIHRCOCRROCOICRIHHCCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH HCHOIRHIIRCOHRROOHRIOHHHRCCCOH = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH CCHOCHCRCRCICIHHOORCIHHCHRIRRI = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.class
   );
   private final com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH CRCIHRRCHHHOROIHCICHROORIIHROH = this.IIRHCHHOICHRICOOCRORCCIOOIHOIR(
      com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.class
   );
   private static final String IRRORIORIRRHCHIRHRCHHIRCIHHIOI = "[NPC] Elle: A Dropship is approaching! Take it down before it's too late!";
   private static final String IIICHHORIICICICRHCICIOOCHOIHIO = "[NPC] Elle: A fleet of Dropships are approaching! Take them down before it's too late!";
   private static final String ROICCRCIIRICCHIHOIHCOHIORCOOCI = "[NPC] Elle: That looks like it hurt! Quickly, while Kuudra is distracted, shoot him with the Ballista!";
   private static final String RICHHICCROCRORHORRHOIRHOIOCIOO = "[NPC] Elle: Phew! The Ballista is finally ready! It should be strong enough to tank Kuudra's blows now!";
   private static final String RHOOHOHOCOHRIOHRRROCIOORHOICII = "recovered a Fuel Cell and charged the Ballista! (100%)";
   private static final double IRORCORIRRHCHRHCOORCHCOHICOCRI = 55.0;
   private int HHCHCOIHCCOHCIROCRHCIOHCHCCIHH;

   public IRCIIHHICIHRCOCRROCOICRIHHCCHH(RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1, HICHRCOHCCRHOHCICOOCHOIHCCHIRI var2) {
      super(true);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO,
         com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(false, var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRIIIRORRHRROOOIRHROOOIIHIHIRH, CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH(var2)
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class,
         this::OCOHORHCROHICRRIHCIHHRRCIHICRI
      );
      this.handle(IOIICIRIICICIIOORHCIIIIRRIHRHI.class, var1x -> {
         this.IHOHORIRRIHHRCCCRRHROHRRRRROOO();
         this.OCCHICCRRRICRCOIHOHOROOOCCCRIR();
      });
      this.handle(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.class, this::IRCIIHHICIHRCOCRROCOICRIHHCCHH);
   }

   @Override
   public String getId() {
      return "SKYBLOCK_KUUDRA_ALERTS";
   }

   @Override
   protected void CCHHCIRHICHHHHRRIHIORCCORCCIHR(boolean var1) {
   }

   private void OCOHORHCROHICRRIHCIHHRRCIHICRI(
      com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      if (OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
         == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.KUUDRA
         )
       {
         String var2 = var1.OIHOIRRICORHHRHOIOIHORCHOIRCOO();
         RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var3 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
            .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
         if (var3.RCRRHIHIHHOIOIRCHRCRCHOOOCOIOI().get()
            && var2.equals("[NPC] Elle: That looks like it hurt! Quickly, while Kuudra is distracted, shoot him with the Ballista!")) {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, "stun", var3.CIROOIRRCHCRIROHROHORCCHCHCRRH(), 2000L);
         } else if (var3.OHRCHRHHHRCRHIHICCROHHIRIIIOOC().get()
            && var2.equals("[NPC] Elle: Phew! The Ballista is finally ready! It should be strong enough to tank Kuudra's blows now!")) {
            this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, "ballistaBuilt", var3.CHIIRICHHHIICCHRHHCOHORRHRRICH(), 2000L);
         } else if (var3.HIICOHHCIOOIHRHCIIICIROOHOCRHH().get()
            && (
               var2.equals("[NPC] Elle: A Dropship is approaching! Take it down before it's too late!")
                  || var2.equals("[NPC] Elle: A fleet of Dropships are approaching! Take them down before it's too late!")
            )) {
            this.HHCHCOIHCCOHCIROCRHCIOHCHCCIHH = 900;
         }

         if (!var2.contains(":")) {
            if (var3.CIRIIOIHRRCOHHIIOIHORRHIORIROC().get() && var2.endsWith("recovered a Fuel Cell and charged the Ballista! (100%)")) {
               this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3, "ballistaFueled", var3.RHHOCCHHOCORICRCOCHIHOCHIIOOCR(), 2000L);
            }
         }
      }
   }

   private void IHOHORIRRIHHRCCCRRHROHRRRRROOO() {
      if (OCOHORHCROHICRRIHCIHHRRCIHICRI.HIOIORCICHOHCHCHRRIRHIIIOHICIH()
         == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.CRRRICCRROCOHHOHIICIHORCOORRRH.KUUDRA
         )
       {
         if (this.HHCHCOIHCCOHCIROCRHCIOHCHCCIHH > 0) {
            this.HHCHCOIHCCOHCIROCRHCIOHCHCCIHH--;
            RRCRRCORICCHOHHIRCHIROOHIIOHCO var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.RIIOCICROIOIORIIRIICORCHHRIIRH();
            if (var1 != null) {
               if (this.HHCHCOIHCCOHCIROCRHCIOHCHCCIHH <= 0) {
                  for (com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH var3 : var1.bridge$getEntities()) {
                     if (var3 instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CORCOCICIRIOHROHROIIOOHICCHCRR.CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH
                        )
                      {
                        RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var4 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
                           .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
                        this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var4, "dropship", var4.CIHICHRHHCOIORIHIHCHIRHCRCRHOR(), 3000L);
                        return;
                     }
                  }
               }
            }
         }
      }
   }

   private void OCCHICCRRRICRCOIHOHOROOOCCCRIR() {
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1 = this.RIRHOCHIORCCIIOIIRHOCCCRHHCHHH(HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO)
         .RHHCIICOCRRIHOOCHHHRHICRORCCRI();
      if (var1.IOCOCCICCCRRCIRCRIORCIIICHHIHR().get()) {
         if (this.HCHOIRHIIRCOHRROOHRIOHHHRCCCOH.OHROIRORIHIOICHHHIHICCRCRROOHO()
            == com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH.T5
            )
          {
            HRCHROOHRIHCRCRHRIIROCIRHOIRHH var2 = this.CCHOCHCRCRCICIHHOORCIHHCHRIRRI.IRIORHRIOICOIOICROCOHCIIOCORCC();
            if (var2 != null && this.CCHOCHCRCRCICIHHOORCIHHCHRIRRI.RCCHCOOOICRHORHOOIOCIHHIOHIRRI()) {
               if (!var1.RHCCOHICOORCOCCIRHRHOROHIOIHRO().get() || !(var2.bridge$getUnboundedHealth() < 24900.0F)) {
                  if (!(var2.bridge$getPosY() >= 55.0) && !(var2.IICIIHIHHRCIIRHCRROHIHHOICROIR() < 55.0)) {
                     String var3 = null;
                     double var4 = var2.bridge$getPosX();
                     double var6 = var2.bridge$getPosZ();
                     if (var6 > -70.0) {
                        var3 = "front";
                     } else if (var6 < -140.0) {
                        var3 = "back";
                     } else if (var4 > -70.0) {
                        var3 = "left";
                     } else if (var4 < -140.0) {
                        var3 = "right";
                     }

                     if (var3 != null) {
                        if (var1.HCICHIHIIIOCRIORRRHHHHCRRRIOCH().get()) {
                           var3 = var3 + "Compass";
                        }

                        this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1, var3, var1.OROOCOHHCHHRROOCRIRHCCCOROCIIC(), 1000L);
                     }
                  }
               }
            }
         }
      }
   }

   private void IRCIIHHICIHRCOCRROCOICRIHHCCHH(RRIRHHRRRHRRCRCRHCCOHOHHRCCOOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      this.HHCHCOIHCCOHCIROCRHCIOHCHCCIHH = 0;
   }

   private void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      RCIRROCCCIIHCIHCCRHHCCHOHHHCHH var1,
      String var2,
      RIROICHCRROROHCCROOCCCCOCHCCRI<com.moonsworth.lunar.client.HICRRICCHCCROOHHCHOCOCCHOIHHOC.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH> var3,
      long var4
   ) {
      this.CRCIHRRCHHHOROIHCICHROORIIHROH
         .IRCIIHHICIHRCOCRROCOICRIHHCCHH(
            com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.ORRCOOOCHCIIRRRCORIIOOHHOHCOIH.RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.RHOHRCCHICIICCOHHCHCHOOCCOCICC()
               .OOIRCOCROHROCRHRICCHIHORHROHII("KUUDRA_ALERT")
               .RICRIRRCOHRCOCRRHHCRHRROOIOHHR(
                  Component.text(var1.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var2), RIOOCHICIHRHOHCCCCCHOCCCOHCRHI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var3))
               )
               .RHCHRCOCCOIIIHCHRHIRCORHRHRICR(var4)
               .HICRRCCIRRICIHOORRHRROHCIROIRI()
         );
   }
}
