package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RRCRRCORICCHOHHIRCHIROOHIIOHCO.IRCIIHHICIHRCOCRROCOICRIHHCCHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;

import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.IIRHCHHOICHRICOOCRORCCIOOIHOIR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCRRHRCIRHIHIHROHCRRHIIHHHHCH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR;
import com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HICRRICCHCCROOHHCHOCOCCHOIHHOC;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.IRCIIHHICIHRCOCRROCOICRIHHCCHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.OCOHORHCROHICRRIHCIHHRRCIHICRI;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.CRICCOOHHHCHOORCICOCOHIHOIRHOO;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH;
import com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.HHCCIRHCCCIIRHCROHIORHIRHHIORH.RRCRRCORICCHOHHIRCHIROOHIIOHCO;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HICHRCOHCCRHOHCICOOCHOIHCCHIRI;
import com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.IOHHOIIOCRHCHHCRORICCOHOHROOIH;
import com.moonsworth.lunar.client.util.IICCOOCHCHROORHHIIHROHCCRHRCOR;
import java.util.Arrays;
import java.util.Map.Entry;

public class RCIRROCCCIIHCIHCCRHHCCHOHHHCHH extends com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH {
   private final HICHRCOHCCRHOHCICOOCHOIHCCHIRI COROHROCIROOOIIHRHHOIIOIORICHI = IOHHOIIOCRHCHHCRORICCOHOHROOIH.CHCHHCCOHHIIHICCHCCICHIOCHOCOC(
         "showArmorToughness"
      )
      .CHCROCIHRRCHHCIHIICOCOCIIHCCOO();
   private String RRHCICIORCCCHCIRRICCICROCCIROH = "";
   private String CHROHIHHORHOCHCROIICCHHRHORRHO = "";

   public RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(IRCIIHHICIHRCOCRROCOICRIHHCCHH var1) {
      super(false);
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.CORCICHOCCRIHORROHIOCRROCCIICO, CRRRICCRROCOHHOHIICIHORCOORRRH.CRRRICCRROCOHHOHIICIHORCOORRRH(var1)
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORRCRCCOHRCIOOCOICRICOOHOCROCH,
         OCOHORHCROHICRRIHCIHHRRCIHICRI.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RRCRRCORICCHOHHIRCHIROOHIIOHCO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.GENERAL
         )
      );
      this.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
         HICRRICCHCCROOHHCHOCOCCHOIHHOC.HRRICIHOCORIIHCHROCROCICOIRIIO,
         CRICCOOHHHCHOORCICOCOHIHOIRHOO.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
            0.0F,
            0.0F,
            RRCRRCORICCHOHHIRCHIROOHIIOHCO.BOTTOM_RIGHT,
            HRCHROOHRIHCRCRHRIIROCIRHOIRHH.HHCCIRHCCCIIRHCROHIORHIRHHIORH(18, 20, 28, 34, 50, 62),
            var1x -> {
               if (var1x) {
                  return IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 6 && this.COROHROCIROOOIIHRHHOIIOIORICHI.get() ? Arrays.asList("80%", "+2.0") : "80%";
               } else {
                  return IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 6
                        && this.COROHROCIROOOIIHRHHOIIOIORICHI.get()
                        && !this.CHROHIHHORHOCHCROIICCHHRHORRHO.isEmpty()
                     ? Arrays.asList(this.RRHCICIORCCCHCIRRICCICROCCIROH, this.CHROHIHHORHOCHCROIICCHHRHORRHO)
                     : this.RRHCICIORCCCHCIRRICCICROCCIROH;
               }
            }
         )
      );
      this.handle(
         com.moonsworth.lunar.client.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.CORCOCICIRIOHROHROIIOOHICCHCRR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HRCHROOHRIHCRCRHRIIROCIRHOIRHH.class,
         var1x -> this.OIOROROIHRHHROOOCHCORICHICHRIH()
      );
      this.COROHROCIROOOIIHRHHOIIOIORICHI.IIOCHOIICCIORCOROIROHICCHIOHIC(var1x -> this.OIOROROIHRHHROOOCHCORICHICHRIH());
   }

   @Override
   public String getId() {
      return "ARMORSTATUS_PROTECTION_CHILD";
   }

   @Override
   public void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
      super.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(var1);
      if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 6) {
         var1.CRRRICCRROCOHHOHIICIHORCOORRRH(this.COROHROCIROOOIIHRHHOIIOIORICHI);
      }
   }

   protected void OIOROROIHRHHROOOCHCORICHICHRIH() {
      HHCCIRHCCCIIRHCROHIORHIRHHIORH var1 = IICCOOCHCHROORHHIIHROHCCRHRCOR.OHORHCCCORHIRHHCROHIRORRROROOH();
      if (var1 != null) {
         float var2 = 0.0F;
         if (IICCOOCHCHROORHHIIHROHCCRHRCOR.MC_VERSION >= 6 && this.COROHROCIROOOIIHRHHOIIOIORICHI.get()) {
            for (IHHCHHHCRIHOOCOIOOCRIIICIOROIR var6 : IHHCHHHCRIHOOCOIOOCRIIICIOROIR.armorValues()) {
               IIRHCHHOICHRICOOCRORCCIOOIHOIR var7 = var1.bridge$getEquipmentInSlot(var6);
               if (var7 != null
                  && var7.bridge$getItem() instanceof com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.HHCCIRHCCCIIRHCROHIORHIRHHIORH var9
                  )
                {
                  var2 += var9.bridge$getArmorToughness(var7);
               }
            }

            this.CHROHIHHORHOCHCROIICCHHRHORRHO = "+" + var2;
         }

         int var13 = 0;
         int var14 = 0;

         for (IHHCHHHCRIHOOCOIOOCRIIICIOROIR var20 : IHHCHHHCRIHOOCOIOOCRIIICIOROIR.armorValues()) {
            IIRHCHHOICHRICOOCRORCCIOOIHOIR var21 = var1.bridge$getEquipmentInSlot(var20);
            if (var21 != null) {
               com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.HRCHROOHRIHCRCRHRIIROCIRHOIRHH var10 = var21.bridge$getItem();
               if (var10.bridge$isArmor()) {
                  var13 += ((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.HHCCIRHCCCIIRHCROHIORHIRHHIORH)var10)
                     .bridge$getArmorValue(var21);
               }

               for (Entry var12 : var21.bridge$getEnchantments().entrySet()) {
                  if (((com.moonsworth.lunar.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IHHCHHHCRIHOOCOIOOCRIIICIOROIR.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH)var12.getKey())
                     .bridge$isProtection()) {
                     var14 = (int)(var14 + Math.floor((6 + (Integer)var12.getValue() ^ 2) * 0.75 / 3.0));
                     break;
                  }
               }
            }
         }

         float var16 = Math.min(Math.min(var14, 25) * 0.04F * 0.75F, 0.8F);
         float var18 = 1.0F - (1.0F - var13 * 0.04F) * (1.0F - var16);
         this.RRHCICIORCCCHCIRRICCICROCCIROH = String.format("%3.1f%%", var18 * 100.0F);
      }
   }
}
