package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.Generated;

public class HHCCIRHCCCIIRHCROHIORHIRHHIORH implements com.moonsworth.lunar.client.OHHRIOHROOIHOROCIRHCHORIHRRRRI.CRRRICCRROCOHHOHIICIHORCOORRRH {
   private static final Map<String, HHCCIRHCCCIIRHCROHIORHIRHHIORH> CCHROCORHRORCHHHRICHHRRORIICCR = new HashMap<>();
   private static final List<HHCCIRHCCCIIRHCROHIORHIRHHIORH> OHIOORHCRCHRIOCHIRHOIRROCHRORO = new ArrayList<>();
   public static final HHCCIRHCCCIIRHCROHIORHIRHHIORH HCRCRIHOIHICCCCCOOROIHIIRIHCHI = HHCCIRHCCCIIRHCROHIORHIRHHIORH("new", true);
   public static final HHCCIRHCCCIIRHCROHIORHIRHHIORH HHHRCOHIHORCIICROOOHCIOOOCROHI = HHCCIRHCCCIIRHCROHIORHIRHHIORH("hud", true);
   public static final HHCCIRHCCCIIRHCROHIORHIRHHIORH HHCOCHOCIRORHHORHCROHOIOCRCHIO = HHCCIRHCCCIIRHCROHIORHIRHHIORH("server", true);
   public static final HHCCIRHCCCIIRHCROHIORHIRHHIORH RROHICHROOOOORICCIRCHOOIRCRHIO = HHCCIRHCCCIIRHCROHIORHIRHHIORH("mechanic", true);
   public static final HHCCIRHCCCIIRHCROHIORHIRHHIORH CCCIRORHIRRORROOOOCCHCRIORHOIC = HHCCIRHCCCIIRHCROHIORHIRHHIORH(
      "dev", !com.moonsworth.lunar.client.CRRRICCRROCOHHOHIICIHORCOORRRH.RCIRROCCCIIHCIHCCRHHCCHOHHHCHH.HHRRICCIOIHROCCOIIORROIROCIIOR
   );
   public static final HHCCIRHCCCIIRHCROHIORHIRHHIORH OHHOIRCROHOCIOOHORCCCCIHCCHCRI = HHCCIRHCCCIIRHCROHIORHIRHHIORH("none", false);
   private final String ROCHHRICCOCORIIHOHRHOIICRCIRHH;

   @com.moonsworth.lunar.client.IOHHOIIOCRHCHHCRORICCOHOHROOIH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.OOROOCCIRCCRHOIOIORIHCHHOOCCOR.CRRRICCRROCOHHOHIICIHORCOORRRH(
      "categories"
   )
   @Override
   public String toString() {
      return this.ROCHHRICCOCORIIHOHRHOIICRCIRHH;
   }

   @Override
   public String getLanguagePath() {
      return "gui.components";
   }

   public static Collection<HHCCIRHCCCIIRHCROHIORHIRHHIORH> values() {
      return CCHROCORHRORCHHHRICHHRRORIICCR.values();
   }

   public static Collection<HHCCIRHCCCIIRHCROHIORHIRHHIORH> RRIORCOOCROHHRRIROIOIOOOIHOOII() {
      return OHIOORHCRCHRIOCHIRHOIRROCHRORO;
   }

   public static HHCCIRHCCCIIRHCROHIORHIRHHIORH HHCCIRHCCCIIRHCROHIORHIRHHIORH(String var0, boolean var1) {
      if (CCHROCORHRORCHHHRICHHRRORIICCR.containsKey(var0)) {
         return CCHROCORHRORCHHHRICHHRRORIICCR.get(var0);
      }

      HHCCIRHCCCIIRHCROHIORHIRHHIORH var2 = new HHCCIRHCCCIIRHCROHIORHIRHHIORH(var0);
      CCHROCORHRORCHHHRICHHRRORIICCR.put(var0, var2);
      if (var1) {
         OHIOORHCRCHRIOCHIRHOIRROCHRORO.add(var2);
      }

      return var2;
   }

   @Generated
   private HHCCIRHCCCIIRHCROHIORHIRHHIORH(String var1) {
      this.ROCHHRICCOCORIIHOHRHOIICRCIRHH = var1;
   }

   @Generated
   public String getName() {
      return this.ROCHHRICCOCORIIHOHRHOIICRCIRHH;
   }
}
