package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO;

public interface IIRHCHHOICHRICOOCRORCCIOOIHOIR {
   boolean CHOOCCORROORHCCOHOIORROICHCCOR();

   IIRHCHHOICHRICOOCRORCCIOOIHOIR HRRHRCCOOIOIIIRORIOOORORHOORIH(boolean var1);

   static IIRHCHHOICHRICOOCRORCCIOOIHOIR CICIOCCCRRRHCCIIRIRORHIROOCHRR() {
      return new com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO.CRRRICCRROCOHHOHIICIHORCOORRRH.IIRHCHHOICHRICOOCRORCCIOOIHOIR();
   }
}
