package com.moonsworth.lunar.client.CRICCOOHHHCHOORCICOCOHIHOIRHOO;

import com.google.gson.JsonElement;
import com.moonsworth.lunar.client.util.OIHCOHRCICCCRHRCROOCIOIRRHHHIH;

public interface IRCIIHHICIHRCOCRROCOICRIHHCCHH
   extends com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.RHOCHHIRRCHHHOHOIRROIROHHHIHIO,
   com.moonsworth.lunar.client.RORCHCIIICOHIRROOORHOCCCCIOCCI.CRICCOOHHHCHOORCICOCOHIHOIRHOO,
   com.moonsworth.lunar.client.RORCHCIIICOHIRROOORHOCCCCIOCCI.IHHCHHHCRIHOOCOIOOCRIIICIOROIR {
   @OIHCOHRCICCCRHRCROOCIOIRRHHHIH
   String getId();

   default boolean isEnabled() {
      CORCOCICIRIOHROHROIIOOHICCHCRR var1 = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.IRIIIRORRHRROOOIRHROOOIIHIHIRH);
      return var1 == null || var1.isEnabled();
   }

   default boolean OORRCOOCHRROHCHOHOCICCRRHHCOCH() {
      OOROOCCIRCCRHOIOIORIHCHHOOCCOR var1 = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.ORHOIHCRRCOIICCIOICHCIIROHCOIR);
      return var1 == null ? this.isEnabled() : this.isEnabled() && var1.RRRORRHCRIRRRCRCOOCHROIORIHIHC();
   }

   default void updateEnabled() {
   }

   default void RCIRROCCCIIHCIHCCRHHCCHOHHHCHH(
      com.moonsworth.lunar.client.HHRIICOIOORCHCOIICOOIHIRHHICRI.HHCCIRHCCCIIRHCROHIORHIRHHIORH.IRCIIHHICIHRCOCRROCOICRIHHCCHH.IRCIIHHICIHRCOCRROCOICRIHHCCHH var1
   ) {
   }

   void COIHORRCHRRCHOCIRHHRRIOIHRIHCC(boolean var1);

   default void CCCRRCHRRRHIOIHCIHRHROIROCIRRI() {
   }

   void ORHHROIRHRHOHCOCORCHROHRICCHOO();

   default void CIIIRIRRROOIOIHCRRORORRCCCOCII() {
   }

   default boolean HOCIIHOCHHORRHHOIOOHOCIRCOOIHR() {
      return true;
   }

   default boolean HRRCHHRHIROOCIROCOHRCOHHHCIHIR() {
      return false;
   }

   default String IRCIIHHICIHRCOCRROCOICRIHHCCHH(String var1, Object... var2) {
      RIOOCHICIHRHOHCCCCCHOCCCOHCRHI var3 = this.IHCRORHRORIICHRHRCHRRIRRHHOCOO(HICRRICCHCCROOHHCHOCOCCHOIHHOC.RRIIOCRCRHHRORCROHRRIOCCHROORO);
      return var3 == null ? var1 : var3.IRCIIHHICIHRCOCRROCOICRIHHCCHH(var1, var2);
   }

   JsonElement IHIROHIRRIHOHOCHHIOCHHOIORIHRI();
}
